### ISSUE TITLE
Question: io_uring_cqe.res meaning for non read/write operations

### ISSUE THREAD

**Issue by romange** [axboe/liburing#100]
Hi, I use `io_uring_prep_poll_add` on sockets. 
For listening sockets I mostly get completions with `res = 195`, but sometimes 'res=1'. 
For server-side sockets, I also get sometimes `res=195` and sometimes 1.  

There are other operations that I have not tested yet. In any case I did not find any documentation explaining the meaning of these numbers. Is it a mask? number of bytes waiting in a buffer?
Please, help, me! I can not sleep at night! :)

P.S. liburing is the next big thing for linux I/O since `epoll`  :+1:

**Comment by CarterLi** [comment]
io_uring_prep_poll_add returns poll opcode on success
For example, `io_uring_prep_poll_add(fd, POLLIN | POLLOUT)` returns `POLLIN` if the fd is ready to read or `POLLOUT` if the fd is read to write

**Comment by CarterLi** [comment]
Since poll_add always works on one-shot mode, these results are not very useful. There is [a proposal](https://github.com/axboe/liburing/issues/98) suggests that returning the number of bytes is ready to read / write.

**Comment by romange** [comment]
Well, I only use `io_uring_prep_poll_add(fd, POLLIN)` but I get both 195 or 1. So it seems the result is not defined well. I use 5.6 kernel with master version liburing.

**Comment by romange** [comment]
Just to comment on @CarterLi note, 195 is `POLLRDNORM | POLLRDBAND | POLLIN | POLLPRI`.
Still not sure why the same opcode generates different masks...

**Comment by axboe** [comment]
```cqe->res``` is indeed always the call result, so a mask for poll (just like the poll/epill system calls) like Carter describes. Various files/devices may set more applicable masks when asked, that's done outside of io_uring. Generally most just care about POLLIN or POLLOUT, masking the check for that.

**Comment by romange** [comment]
Thanks!
