### ISSUE TITLE
There may be some funny questions,i just can't install it, when i make && make install, it told me that:   statx.c: In function ‘test_statx’: statx.c:48:15: error: storage size of ‘x1’ isn’t known   struct statx x1;                ^ statx.c:50:15: error: storage size of ‘x2’ isn’t known   struct statx x2;                ^ statx.c:59:40: error: ‘STATX_ALL’ undeclared (first use in this function)   io_uring_prep_statx(sqe, -1, path, 0, STATX_ALL, &x1);

### ISSUE THREAD

**Issue by Night23333** [axboe/liburing#101]

**Comment by Night23333** [comment]
then i saw the define of the struct statx in the src/include/liburing.h, it just an empty struct, so why can use   **struct  statx  x1**   in the test/statx.c  (I'm a rookie. If there's something funny, please forgive me or laugh 👍 3>  )

**Comment by michael-grunder** [comment]
Hi, not the author of liburing but:

The error `error: storage size of X isn’t known` means that the compiler doesn't know how much memory to reserve for the variable.

It appears that `struct statx` is a [kernel struct](https://github.com/torvalds/linux/blob/1c1ff4836fdab94c7c15b23be57bf64c1e56a36f/include/uapi/linux/stat.h#L99) and that header [is being included](https://github.com/axboe/liburing/blob/3d70675e33ba476274b86c378e5cd2195a861879/test/statx.c#L14) in test/statx.c

Just wildly guessing here but perhaps your kernel doesn't have that struct (e.g. too old?)

**Comment by Night23333** [comment]
I want to experience the io_uring so i just update the kernel to 5.6.2 yesterday.I don't think the kernel is too old（^_^）,i use the ELRepo to update,was there any bugs about it?

**Comment by Night23333** [comment]
Thank you for your reply O(∩_∩)O

**Comment by axboe** [comment]
I pushed a fix for this, I guess your kernel-headers are old. But it's not a huge deal, we can just skip building the test/statx regression test for that case. Can you try current -git and see if it works for you?

**Comment by Night23333** [comment]
it works!!  Thanks a lot,i update the kernel but it seems that the kernel-headers not update together 
 (ノ￣▽￣)
