### ISSUE TITLE
When using epoll to listen on multiple uring_fds, occasionally, when an event occurs on a uring_fd, it may not wake up the epoll.

### ISSUE THREAD

**Issue by sxstd001** [axboe/liburing#1029]
When using epoll to listen on multiple uring_fds, occasionally, when an event occurs on a uring_fd, it may not wake up the epoll.

Scenario:
Using epoll_wait to monitor multiple uring_fds. When submitting io_uring_prep_nop to one of the uring_fds, sometimes epoll is not awakened. a very mysterious bug.  By proactively peek the uring, can peek at the nop_sqe that was submitted earlier.

**Comment by axboe** [comment]
Do you have a reproducer for this? I can certainly take a look, but would save me a lot of time if I didn't have to write a reproducer first.

**Comment by axboe** [comment]
Please include a comment on when you close an issue. Was it a problem in your application?

**Comment by sxstd001** [comment]
> 关闭问题时请添加评论。您的应用程序中存在问题吗？

the qs  is must new uring in newthread,

**Comment by isilence** [comment]
or you can create it with `IORING_SETUP_R_DISABLED`, pass the ring to your final task/process and enable it there using `IORING_REGISTER_ENABLE_RINGS`.
