### ISSUE TITLE
2.6 release tag not present

### ISSUE THREAD

**Issue by Scottmitch** [axboe/liburing#1044]
https://github.com/axboe/liburing/blob/master/CHANGELOG indicates there is a 2.6 release but there is no corresponding 2.6 tag in the git repo. Can you please add a tag to the commit corresponding to the 2.6 release? Thanks for all the hard work on liburing!

**Comment by axboe** [comment]
I always update the version when a release is tagged, eg when 2.5 was tagged I change the internal version to 2.6 as that is what the next version will be. So there's no tag for 2.6 just yet, as I haven't tagged and released version 2.6. Will probably do that soonish though, so it's coming!

**Comment by Scottmitch** [comment]
thx for clarifying. I was confused as the changeling implied there was a 2.6 release already.
