### ISSUE TITLE
io_uring_enter man page doesn't document IORING_OP_SENDMSG_ZC

### ISSUE THREAD

**Issue by bmerry** [axboe/liburing#1045]
There is documentation for io_uring_prep_sendmsg_zc, but the specification of the opcode is missing from io_uring_enter.2.

**Comment by davidzeng0** [comment]
also `IORING_OP_FSETXATTR,
	IORING_OP_SETXATTR,
	IORING_OP_FGETXATTR,
	IORING_OP_GETXATTR,`

**Comment by axboe** [comment]
Kind of secondary as the primary documentation should be for liburing. I will add them eventually if I have nothing else to do - or also happy to take patches to add the missing bits. It would be nice if it was complete in io_uring_enter.2.
