### ISSUE TITLE
version name change

### ISSUE THREAD

**Issue by YoSTEALTH** [axboe/liburing#1046]
version names are wrong, it should be `liburing_*` not `io_uring_*`

`io_uring_major_version` -> `liburing_major_version`
`io_uring_minor_version` -> `liburing_minor_version`
`io_uring_check_version` -> `liburing_check_version`
`IO_URING_VERSION_MAJOR` -> `LIBURING_VERSION_MAJOR`
`IO_URING_VERSION_MINOR` -> `LIBURING_VERSION_MINOR`

**Comment by axboe** [comment]
Don't disagree with that, but I'm not going to change it now as that would just cause issues for no good reason. The kernel side isn't versioned at all, all we really care about is the liburing version.
