### ISSUE TITLE
Question: In `SQPOLL` mode, how does `io_uring` avoid data race in SQ between the user thread and the kernel polling thread?

### ISSUE THREAD

**Issue by ZhenbangYou** [axboe/liburing#1061]
This question is all about SQ polling. Say, I want to submit a `read` request, so I do the following three steps: 
 - `io_uring_get_sqe`,
 - `io_uring_prep_read`,
 - setting `user_data` .

However, since the kernel is polling, is it possible for the following two scenarios to happen:
 - Between step 1 and 2, the kernel takes this SQE. Since this SQE is not initialized yet, the kernel treats it as `nop`, so I will lose this `read` operation.
 - Between step 2 and 3, the kernel takes this SQE. Since `user_data` is still not set, I won't get a CQE with expected `user_data` in the CQ.

I tried very hard to find an answer to this, but I couldn't make it. Thanks so much for answering my question!

**Comment by mjasny** [comment]
No, because the SQE is only visible to the kernel thread after you do `io_uring_submit(ring);`. This would be step 4.

Internally liburing does increment the tail of the ring which is polled by the kernel in submit using ` __io_uring_flush_sq()`

**Comment by ZhenbangYou** [comment]
I see! No wonder without `io_uring_submit` my SQEs weren't executed in SQPOLL mode. Thank you so much!
