### ISSUE TITLE
Request: support `make uninstall`

### ISSUE THREAD

**Issue by ZhenbangYou** [axboe/liburing#1073]
I met the same issue as #1056 (mixed liburing versions installed). But since `make uninstall` is not supported, I had to manually find libraries and delete them.

**Comment by axboe** [comment]
If someone wants to add this target, I'd certainly help review/merge it.

**Comment by korant96** [comment]
> If someone wants to add this target, I'd certainly help review/merge it.

what about this pr
https://github.com/axboe/liburing/pull/1091
