### ISSUE TITLE
`io_uring_check_version` documentation: should be `<=` instead of `>=`

### ISSUE THREAD

**Issue by ZhenbangYou** [axboe/liburing#1074]
The man page says, "The  io_uring_check_version(3)  function  returns  true  if the liburing library loaded by the dynamic linker is ***greater-than or equal-to*** the major and minor numbers provided."
However, according to the [implementation](https://github.com/axboe/liburing/blob/097250601ff2085a86c288e94dfb619576e86175/src/version.c#L16) (also shown below), it's NOT **greater-than or equal-to**, but **less-than or equal-to**.
```
bool io_uring_check_version(int major, int minor)
{
	return major > io_uring_major_version() ||
		(major == io_uring_major_version() &&
		 minor >= io_uring_minor_version());
}
```
For example, I'm using liburing 2.6, and `io_uring_check_version(2, 4)` returns `false`.
The same issue applies to [`IO_URING_CHECK_VERSION`](https://github.com/axboe/liburing/blob/097250601ff2085a86c288e94dfb619576e86175/src/include/liburing.h#L1532).

**Comment by axboe** [comment]
Huh, how odd is that. Might be better to update the documentation, as the compile time check is identical to this one. If we just flip them that has a higher risk of breaking.

**Comment by axboe** [comment]
Actually it looks worse than that as this is what I get:

```
major=2, minor=6
2.0 0
2.5 0
2.6 1
2.7 1
3.0 1
```

**Comment by ZhenbangYou** [comment]
Thank you, Jens!
Yeah it's a little strange that it returns false when version matches, but it's a safer way.

**Comment by ZhenbangYou** [comment]
A typo in the commit message of [this commit](https://github.com/axboe/liburing/commit/3aa651508e21d66aa923f8b8bcb4d66d92d82b2b): "If the majors are the same, only if the major is larger should we return true." The latter "major" should be "minor".

**Comment by YoSTEALTH** [comment]
I think the compiler macro should be:
``` C
#define IO_URING_CHECK_VERSION(major,minor) \
  (major > IO_URING_VERSION_MAJOR ||        \
   (major == IO_URING_VERSION_MAJOR &&      \
    minor >= IO_URING_VERSION_MINOR))
```
And function should be:
``` c
bool io_uring_check_version(int major, int minor)
{
	return major > io_uring_major_version() ||
		(major == io_uring_major_version() &&
		 minor > io_uring_minor_version());
}

```
These two have different use cases.
