### ISSUE TITLE
question: idiomatic usage for a fileserver

### ISSUE THREAD

**Issue by agnivade** [axboe/liburing#108]
Hi,

I am looking to create high level Go library to play around with `liburing`. My objective is to create a file server where clients call submit read/write requests and they would get notified through callbacks.

From my meagre understanding, it will be something like this: (Apologies, the code is in Go)

```go
// queue is already inited
queueSize := 0
for {
	select {
	case sqe := <-submitChan:
		// io_uring_get_sqe
		// io_uring_prep readv/writev
		// io_uring_sqe_set_data
                queueSize++
                if queueSize > something {
                  // io_uring_submit
                  for queueSize > 0 {
			// io_uring_wait_cqe
			// io_uring_cqe_get_data
			// io_uring_cqe_seen;
                    queueSize--
                  }
                }
	case <-ticker.C: // some timer of some interval
               if queueSize > 0 {
                 // io_uring_submit
                 for queueSize > 0 {
			// io_uring_wait_cqe
			// io_uring_cqe_get_data
			// io_uring_cqe_seen;
                    queueSize--
                 }
               }
	}
}
```

Hopefully, the code is easy to understand. I am queuing items, and whenever it crosses a threshold, I submit and read from the queue. If some time elapses, within which the queue still has some items, I read and drain from it.

This seems to work at a basic level. But my question is: this seems fine if the application is doing iops at a very high rate. But if the requests come at a slow rate, then I need to rely on the ticker to read from the queue.

Is there a better way to deal with scenarios like this ? I understand that `IORING_OP_TIMEOUT` is one way to handle waiting on the completion queue. But I am failing to understand how to incorporate that here without waiting on the queue.

Thanks.

**Comment by isilence** [comment]
So, you're stuffing a submission queue and then submit it, either when it's full, or a time time interval has passed since the last submit(). Did I get it right?

**Comment by agnivade** [comment]
Correct.

**Comment by isilence** [comment]
Is there a particular reason, why you don't submit them immediately but wait for a batch? Performance I assume?

I don't know much about Go, but I'd implement it with a separate coroutine, solely allocated for completion waiting. Then it can reap cqes and

```C
completion_routine_foo()
{
    while (1) {
        io_uring_wait();
        for (cqe: cqes) {
            if (user_request(cqe)) { cqe->callback() }
            if (internal_timeout(cqe)) do_submit()
        }
        ...
    }
}

do_submit()
{
    deal_with_prev_not_fired_timeout(); // e.g. ignore, cancel, etc
    add_new_timeout()
    io_uring_submit()
}
```

Not sure about Go part, does it make sense?

**Comment by agnivade** [comment]
I am not terribly experience in this area. But if I follow what you are suggesting- won't there be 2 separate threads - one for completion waiting, and one handling submit requests from the user ? Then we would need additional locking around the ring.

**Comment by isilence** [comment]
> I am not terribly experience in this area. But if I follow what you are suggesting- won't there be 2 > separate threads - one for completion waiting, and one handling submit requests from the user ? 

Yes, something similar.

> Then we would need additional locking around the ring.

1. completion and submission queues (CQ and SQ) are totally decoupled, so you don't need any synchronisation between them.

2. do_submit() can happen from submission and completion threads/contexts. So, you may need  synchronisation there, if your program is truly parallel.

3. If your program is not really parallel, but just coroutines/goroutines. You don't ever need synchronisation. io_uring implements polling interface (e.g. works fine with epoll), so you can hook it somehow into Go core and do it as a typical goroutine.

4. I'm not sure you need a separate submission thread/goroutine with a channel. Filling a SQ with an entry is fast, a channel will kill it. Though, you may want to offload it
   - for submit syscall (i.e. io_uring_enter()) if there are a lot of entries. 
   - to deal with SQ overflows.

**Comment by agnivade** [comment]
> completion and submission queues (CQ and SQ) are totally decoupled, so you don't need any synchronisation between them.

Yes, but liburing doesn't expose them separately right ? That's the problem here.

**Comment by isilence** [comment]
> > completion and submission queues (CQ and SQ) are totally decoupled, so you don't need any synchronisation between them.
> 
> Yes, but liburing doesn't expose them separately right ? That's the problem here.

What do you mean? In terms of liburing
`io_uring_submit()` and `io_uring_get_sqe()`, etc. for the submission side.  
And `io_uring_wait_cqe()`, `io_uring_cqe_seen()` for completion

**Comment by agnivade** [comment]
I mean that all of these `io_uring_peek_cqe`, `io_uring_get_sqe`, `io_uring_cqe_seen`, `io_uring_submit` functions take a pointer to `io_uring` as a parameter. So won't using them from separate threads need synchronization ?

**Comment by isilence** [comment]
I see, the kernel API is built in the way you don't.

**Comment by agnivade** [comment]
Ah okay, so what you are basically saying is that I can have 2 separate threads one for submitting and one of picking up cqe entries, and I don't need to synchronize access to the ring struct ?

**Comment by isilence** [comment]
I'll look it up to be sure, but yes. It should work without synchronisation if you don't do something obviously submitting from the completion context, like specifying a timeout in `io_uring_wait_cqes()`.

**Comment by agnivade** [comment]
Alright, I think that answers my main question. Although it is not super-clear from the API, as long as there's no race, then I'm fine. But now my worry is will Go like what I am doing ? :smile: I guess that's my headache to worry about.

My C proficiency is not very good as it is very clear. Thanks again for being patient with my questions.

**Comment by isilence** [comment]
> Alright, I think that answers my main question. Although it is not super-clear from the API, as long as there's no race, then I'm fine. 

Double checked, it's fine awhile you don't do something obviously submisiion/completion mixed.
e.g . passes timestamp to ```*_wait_cqe()```

> But now my worry is will Go like what I am doing ? smile I guess that's my headache to worry about.

BTW, I've already saw somewhere Go wrapper of io_uring. Though never looked it up.
 
> My C proficiency is not very good as it is very clear. Thanks again for being patient with my questions.

I don't write Go, so may have said something strange myself. Glad it helped.
