### ISSUE TITLE
Missing Manual: `IORING_SETUP_REGISTERED_FD_ONLY` should be used with `IORING_SETUP_NO_MMAP`

### ISSUE THREAD

**Issue by ZhenbangYou** [axboe/liburing#1087]
This is documented in [comment in `setup.c`](https://github.com/axboe/liburing/blob/7dccf035cbca029f2ca863aaa074aa75a9d61fec/src/setup.c#L305), but it will be better if the [man page of of `io_uring_setup`](https://github.com/axboe/liburing/blob/7dccf035cbca029f2ca863aaa074aa75a9d61fec/man/io_uring_setup.2#L321) can also contain this.

**Comment by krisman** [comment]
https://lore.kernel.org/io-uring/20240403164413.16398-3-krisman@suse.de/T/#u
