### ISSUE TITLE
A bit misleading documentation for IORING_OP_POLL_REMOVE or confusing (wrong?) implemetation of io_uring_prep_poll_update()

### ISSUE THREAD

**Issue by vsolontsov-ll** [axboe/liburing#1095]
Looking at the `IORING_OP_POLL_REMOVE` operation description in the man io_uring_enter, I don't see it can **modify** the existing polling (unlike the `IORING_OP_POLL_ADD`) while `io_uring_prep_poll_update()` uses the `IORING_OP_POLL_REMOVE` one.

Could you please advise whether `io_uring_prep_poll_update()` is correct? If so, would be great to clarify the description of `IORING_OP_POLL_REMOVE`.

**Comment by isilence** [comment]
The implementation is right, `IORING_OP_POLL_REMOVE` does updates, so if man says otherwise it is in the wrong. Thanks for letting us know

**Comment by krisman** [comment]
https://lore.kernel.org/io-uring/20240403164413.16398-2-krisman@suse.de/T/#u
