### ISSUE TITLE
One thread read, another thread write, how to close(fd) ?

### ISSUE THREAD

**Issue by sxstd001** [axboe/liburing#1112]
threadA read,  threadB write.  if threadA close(fd). This synchronization is difficult to implement simply; This is far more complex than EPOLL.

**Comment by sxstd001** [comment]
like this?
```cpp
	// read	
	while(true){
		spinlock.lock();
		if(fd != -1){
			uring_prep_read(fd);
			uring_submit(...)
		}
		spinlock.ulock();
		...
	}
	
	// close
	spinlock.lock();
	fd=-1;
	uring_prep_close(fd);
	uring_submit(...)
	spinlock.unlock();
	
	// write	
	while(true){
		spinlock.lock();
		if(fd != -1){
			uring_prep_write(...);
			using_submit(...);
		}
		spinlock.ulock();
		...
	}
````

**Comment by isilence** [comment]
That would be quite a bother, can't you just dup the file and make your life much easier? Hard to tell more without knowing if it's different rings, if it's using fixed files and so on.
