### ISSUE TITLE
Loosing `sqe`?

### ISSUE THREAD

**Issue by YoSTEALTH** [axboe/liburing#1122]
On GitHub this code seems  to work fine: https://github.com/YoSTEALTH/Liburing/blob/master/test/helper/io_uring_put_sqe_test.py#L11-L23 On my local system it runs out of `sqe` if the value is higher than `_loop(1024, 255)`

This is where the error is raised https://github.com/YoSTEALTH/Liburing/blob/master/src/liburing/queue.pyx#L93-L108

``` bash
$ ulimit -a
real-time non-blocking time  (microseconds, -R) unlimited
core file size              (blocks, -c) unlimited
data seg size               (kbytes, -d) unlimited
scheduling priority                 (-e) 0
file size                   (blocks, -f) unlimited
pending signals                     (-i) 63935
max locked memory           (kbytes, -l) 8192
max memory size             (kbytes, -m) unlimited
open files                          (-n) 1024
pipe size                (512 bytes, -p) 8
POSIX message queues         (bytes, -q) 819200
real-time priority                  (-r) 0
stack size                  (kbytes, -s) 8192
cpu time                   (seconds, -t) unlimited
max user processes                  (-u) 63935
virtual memory              (kbytes, -v) unlimited
file locks                          (-x) unlimited
```
Not sure whats causing it!

**Comment by ammarfaizi2** [comment]
Can you create a reproducer in C?

I can't debug that Python code. Also, it is unclear what `io_uring_sqe(num)` and `io_uring_put_sqe(ring, sqe)` actually do as you customized it yourself, liburing does not have them.

**Comment by YoSTEALTH** [comment]
I am not really a C coder, not sure if I can do justice.

[io_uring_sqe](https://github.com/YoSTEALTH/Liburing/blob/master/src/liburing/queue.pyx#L44) you can think of it as a temp single/multiple `sqe` holder that you later copy into `io_uring_get_sqe` using [memcpy](https://github.com/YoSTEALTH/Liburing/blob/master/src/liburing/helper.pyx#L37)

**Comment by YoSTEALTH** [comment]
Is there a change `io_uring_cqe` pointer not being freed after `io_uring_queue_exit` is called? If `io_uring_cq_advance` or `io_uring_cqe_seen` isn't called before exiting?

**Comment by isilence** [comment]
What was the problem? library specific?

> Is there a change io_uring_cqe pointer not being freed after io_uring_queue_exit is called? If io_uring_cq_advance or io_uring_cqe_seen isn't called before exiting?

No, CQE pointers are io_uring rings, they are always destroyed on the ring's exit

**Comment by YoSTEALTH** [comment]
When you call `io_uring_queue_exit(ring)` does it free the `ring` memory?

**Comment by axboe** [comment]
Yes, as Pavel mentioned, when you exit the ring, it is unmapped as well. That includes the SQE and CQE memory.

**Comment by YoSTEALTH** [comment]
btw there is no clear mention in `man io_uring_queue_init` that `ring` gets assigned memory by `io_uring_queue_init` itself. For you guys it might be obvious but for people that just read the man page and code (without reading C source) its missing the obvious.

**Comment by ammarfaizi2** [comment]
> How silly, I figured since I was assigning ring memory, I should be responsible to clearing the memory as well!

What do you mean by "responsible to clearing memory"?

If what you mean is calling `io_uring_queue_exit`, then yes, you're responsible
for calling that once the ring is no longer used.

> btw there is no clear mention in man io_uring_queue_init that ring gets assigned memory by io_uring_queue_init itself. For you guys it might be obvious but for people that just read the man page and code (without reading C source) its missing the obvious.

Can you give a sentence you think should be added to the man page?

I think the `man 3 io_uring_queue_init` already explains that clearly:
```
The io_uring_queue_init(3) function executes the io_uring_setup(2)
system call to initialize the submission and completion queues in
the kernel with at least entries entries in the submission queue
and then maps the resulting file descriptor to memory shared
between the application and the kernel.

[...]

On success, the resources held by ring should be released via a
corresponding call to io_uring_queue_exit(3).
```

IOW, the initialization and destruction are already clear.
  - Use `io_uring_queue_init` to init the ring.
  - Use `io_uring_queue_exit` to free the ring.

Let's not drag the Python party into liburing problem. If you use liburing, you
will also need to embrace the discipline of C programming.
