### ISSUE TITLE
prep_accept  exists memory synchronization problem, frequent return Invalid argument error;

### ISSUE THREAD

**Issue by sxstd001** [axboe/liburing#1124]
**add sqe to thread-local  ring,  why need memory synchronization??**

frequent return Invalid argument error;  ✘
```
sockaddr_in6 addr{}  // already 0 value initialization;
socklen_t addrlen = sizeof(sockaddr_in6);
io_uring_prep_accept(sqe, fd, (sockaddr*)(&addr), &addrlen, flags);

```
no  Invalid argument error;  ✔
```
sockaddr_in6 addr{}  // already 0 value initialization;
socklen_t addrlen = sizeof(sockaddr_in6);
std::atomic_thread_fence(std::memory_order_seq_cst);   // sync memory
io_uring_prep_accept(sqe, fd, (sockaddr*)(&addr), &addrlen, flags);
```
no  Invalid argument error  ✔ 
```io_uring_prep_accept(sqe, fd, nullptr, nullptr, flags);```

**Comment by isilence** [comment]
That's odd, there shouldn't be anything that could potentially require an additional barrier especially for a thread local ring. Is it with `IORING_SETUP_SQPOLL` or without? And hunch, do you make sure @addr and @addrlen outlive the submission?

```C
foo(sqe) {
    sockaddr addr;
    prep_sqe(&addr);
    // here addr goes out of scope and gets overwritten
}

bar() {
    foo(sqe);
    // sqe is not yet submitted, but addr in foo is out of scope and contains garbage at this point 
    io_uring_submit();
}
```

And please, share a reproducer

**Comment by axboe** [comment]
'addr' going out of scope would indeed be my guess.

**Comment by sxstd001** [comment]
> 'addr' going out of scope would indeed be my guess.
**Extremely grateful!**
The reason is addrlen be destroyed.
