### ISSUE TITLE
io_uring_register_napi() and io_uring_unregister_napi() should use do_register() to work with registered rings

### ISSUE THREAD

**Issue by lano1106** [axboe/liburing#1133]

**Comment by axboe** [comment]
Oops yes indeed, thanks! Glad we caught that before release. I've pushed a fix for this, can you confirm it works?

**Comment by lano1106** [comment]
I reviewed this code because I know a new version is about to be released along with 6.9.

I confirm that it fixes the problem.

before the fix, a registered ring was receiving a EBADF error. With the fix, the error is gone.

I even have tested it with a ring possessing a fd. It does work too... In case you are wondering why I have a mix of registered/unregistered rings, it is because I am using the option IORING_SETUP_ATTACH_WQ

AFAIK, IORING_SETUP_ATTACH_WQ is not compatible with registered indexes...

**Comment by lano1106** [comment]
also previous experience with VPS has shown me that not all virtual NIC drivers are exposing NAPI id... However, at AWS, the situation is different. The NIC driver is 'ena' and on it, sockets are associated to a NAPI id... idk how close to the real thing busy polling is on those virtual NICs but it is doable...
