### ISSUE TITLE
test_disabled_ring EEXIST 

### ISSUE THREAD

**Issue by MikuChan03** [axboe/liburing#1135]
Hello.

Running the test msg-ring.t with runtests-loop.sh, eventually the cqe->res will be -17 (EEXIST) in test_disabled_ring.
This happens with the newest kernel and liburing version.
That's all.

Bye

**Comment by axboe** [comment]
What does "newest kernel" mean exactly? And can you post the exact output, there are two ways this test case is run. Can't seem to reproduce it here, so more details on system/etc might be useful.

**Comment by MikuChan03** [comment]
```
Running test msg-ring.t                                             0 sec [0]
All tests passed
Finished loop 476
Running test msg-ring.t                                             wait cqe -17
cqe res 32
test_disabled_ring failed
ring flags defer failed
Test msg-ring.t failed with ret 1
Tests failed (1): <msg-ring.t>
Tests failed at loop 477
```

liburing is 1cbd4cffa881772d54d7d1a98755101253a66d0a
linux is 6.9 rc4

I was wrong though, wait cqe return -17.

**Comment by MikuChan03** [comment]
I think I got the gist of it.
In test_remote, the aim is to setup a sqe in ring1 with io_uring_prep_msg_ring and pass the fd of the target ring2, thereby messaging ring2. So a pthread is created that runs wait_cqe_fn, waiting for messages on ring2. Under whichever circumstances the io_uring_wait_cqe in the pthread fails with EEXIST and leaves the message on ring2. Then we pass ring2 to test_disabled_ring, which incorrectly reads the message that was left on ring2.

What's more interesting now is why io_uring_wait_cqe fails with EEXIST. There are only few instances of EEXIST in your code and most of them do something along the line of

```c
static int __io_run_local_work(struct io_ring_ctx *ctx, struct io_tw_state *ts,
			       int min_events)
{
	struct llist_node *node;
	unsigned int loops = 0;
	int ret = 0;

	if (WARN_ON_ONCE(ctx->submitter_task != current))
		return -EEXIST;
```

I think that's all I can do. Bye

**Comment by MikuChan03** [comment]
Ok, here goes nothing. The issue is your basic race condition. If the pthread running wait_cqe_fn is slower than test_remote, it works out. If wait_cqe_fn is faster, which happens once every few thousand iterations, it needs to make the syscall io_uring_enter to actually wait for cqes that would have otherwise already been created. In the kernel, io_uring_enter calls io_cqring_wait, which in turn calls io_allowed_run_tw.

```c
static inline bool io_allowed_run_tw(struct io_ring_ctx *ctx)
{
	return likely(!(ctx->flags & IORING_SETUP_DEFER_TASKRUN) ||
		      ctx->submitter_task == current);
}
```

I don't know how much clearer it could be. Calling io_cqring_wait to get cqes is explicitly forbidden when IORING_SETUP_DEFER_TASKRUN is set and the submitter_task is different from the task calling io_cqring_wait. It even says something in the manpage about how if IORING_SETUP_DEFER_TASKRUN is set, the task getting the cqes has to be the one issuing them.

The only reason this test worked at all is because the race condition with the pthread running wait_cqe_fn is usually slower and the thread didn't need to actually call io_uring_enter. The nature of race conditions is also what made it difficult for you to reproduce the bug.

If you put sleep(1) after pthread_create(&thread, NULL, wait_cqe_fn, target) in test_remote, the thread will be faster and you'll be able to see the bug for yourself.
Maybe you wanna fix this, I don't know...

**Comment by axboe** [comment]
Pushed a potential fix for this, does it work for you?

**Comment by MikuChan03** [comment]
Yup, all good. Thanks for bearing with me.

**Comment by axboe** [comment]
Thanks for reporting! I'll close this one up then.
