### ISSUE TITLE
Doc Request: A working example of non-blocking sockets with liburing

### ISSUE THREAD

**Issue by Cranjis** [axboe/liburing#114]
Request to add an example of a bare bone echo server using the liburing library in the examples folder.
It would be quite helpful for many looking to use the library for socket IO. Encourages learners like myself to use/learn the new IO interface instead of select() and epoll(). Thank you.

**Comment by YoSTEALTH** [comment]
I would really like to see this as well, even if there was tests for non-blocking socket that would work for me, as i am testing this feature and there seems to be few serious bugs that needs to be addressed.

**Comment by MarkReedZ** [comment]
Here is an echo server based on my io_uring event loop mrloop

https://github.com/MarkReedZ/mrloop/blob/master/examples/echo_server.c

To create the example just using liburing you'd need to pull the code out of mrloop.c.
