### ISSUE TITLE
uring threads cant exit in background 

### ISSUE THREAD

**Issue by osevan** [axboe/liburing#1146]
Hi devs,

With my performance test with stress-ng uring tests,  threads in background still running. 

I already opened bugreport here:

https://github.com/ColinIanKing/stress-ng/issues/370

 but its uring library issue. 

Here log of stess-ng test

https://defuse.ca/b/ajF0ZKHb

Thanks and

Best  Regards

**Comment by axboe** [comment]
That looks like a kernel issue. I'll take a look.

**Comment by axboe** [comment]
Can you try a current 6.8-stable?

**Comment by axboe** [comment]
Would also be nice to know what fs and device you are running this on, the log is a bit cryptic on that front. Doesn't reproduce for me here.

**Comment by osevan** [comment]
Zfs,
Arch linux, 
haswell i7 cpu
Ok i will test

And report back

**Comment by axboe** [comment]
The symptom is that a request is stuck, so it's most likely an issue on the zfs side. The io_uring cancelation is complaining because it didn't manage to reap it after 60s of trying. There's really nothing I can do do debug an issue on a tainted kernel and with an out-of-tree module.
