### ISSUE TITLE
io_uring statx fails with AT_EMPTY_PATH

### ISSUE THREAD

**Issue by cosmosgit** [axboe/liburing#115]
I wasn't sure where to file against io_uring, so I created:
https://bugzilla.kernel.org/show_bug.cgi?id=207453

**Comment by axboe** [comment]
It would be a lot more productive to send these as emails to io-uring@vger.kernel.org, it reaches a broader audience there and hence there's a higher chance someone looking. There's no io-uring category on bugzilla, aio is a different subsystem and the person at the other end there hasn't been active in more than a decade... So thanks for posting here at least too, bugzilla by itself is a dead end.

**Comment by isilence** [comment]
Time to close it
