### ISSUE TITLE
IORING_OP_MSG_RING should have a `io_uring_register_msg_ring`

### ISSUE THREAD

**Issue by davidzeng0** [axboe/liburing#1150]
This would make it simple for thread pools to send completed tasks to a ring without creating a ring of its own. It would also avoid the need to set up futexes/event fds and polling them on the ring.

**Comment by davidzeng0** [comment]
Interestingly the eventfd method has 3x less latency than `MSG_RING` despite how simple the code for that op is. Could still be a useful feature though

**Comment by axboe** [comment]
This will be available in the 6.13 kernel.

**Comment by davidzeng0** [comment]
Is the code already in the tree somewhere? I would like to see what the API is going to look like, if possible.

**Comment by axboe** [comment]
Kernel: https://git.kernel.dk/cgit/linux/commit/?h=for-6.13/io_uring&id=d1e55003c13ca95878afe380ad3da89d37d63b1e

Liburing: https://git.kernel.dk/cgit/liburing/log/?h=sync-msg (top 3 commits)

Slated for the 6.13 kernel and next liburing release after the kernel code is merged.

**Comment by davidzeng0** [comment]
It looks good, thank you for adding this feature
