### ISSUE TITLE
Feature request: Please implement IORING_OP_TEE

### ISSUE THREAD

**Issue by cosmosgit** [axboe/liburing#116]
I was excited to see IORING_OP_SPLICE go in, but disappointed that tee didn't go in at the same time.  It would be very useful to copy pipe buffers in an async program.

**Comment by axboe** [comment]
I think it'd be more productive to post these on the io-uring mailing list, not sure who actually monitors the liburing issues for feature requests...

**Comment by isilence** [comment]
It landed in 5.8. Can be closed now, I suppose.

**Comment by isilence** [comment]
How about to close it?

**Comment by cosmosgit** [comment]
On Sun, Jan 10 2021 at 08:24:51 -0800, Jens Axboe quoth thus:

I just read Pavel's reminder and was about to do so, but you beat
me to it.  Thanks!
