### ISSUE TITLE
io_uring IORING_OP_POLL_ADD fails when fd is a tty

### ISSUE THREAD

**Issue by cosmosgit** [axboe/liburing#117]
I was unsure of where to report bugs against io_uring, so I created:
https://bugzilla.kernel.org/show_bug.cgi?id=207461

**Comment by axboe** [comment]
Yeah, this is a known issue, it'll currently fail on file/device types that double add the waitqueue for poll. It's not very prevalent, but it does impact tty. I did post a patch to fix this a few months ago, but didn't follow through on polishing it. See here:

https://lore.kernel.org/io-uring/20200212202515.15299-1-axboe@kernel.dk/

**Comment by smurfix** [comment]
Any progress on this? We'd love to add an `io_uring` event loop to Trio, but if we have to keep `epoll`running in parallel to cater for the devices io_uring can't handle that's a bit too fragile.

**Comment by axboe** [comment]
Nothing worth talking about, I'm afraid. I'll back to this soon, hopefully we can still make it happen for 5.8.

**Comment by axboe** [comment]
Updated and tested version posted just now: https://lore.kernel.org/io-uring/f67f77dc-5fbb-cdaa-5e4c-d355ac6f47f7@kernel.dk/T/#u

With this applied, it works just fine. I do wonder if this warrants a feature flag.

**Comment by YoSTEALTH** [comment]
What Linux version will this patch be available in?

**Comment by axboe** [comment]
It's been sent in for the 5.8 merge window:

https://lore.kernel.org/io-uring/dacd50ff-f674-956b-18cd-9d30e2221b09@kernel.dk/T/#u

So unless Linus complains, it'll be in the 5.8 release.

**Comment by axboe** [comment]
This is now in -git, closing.

https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=1ee08de1e234d95b5b4f866878b72fceb5372904
