### ISSUE TITLE
Will there be examples for pure  kernel side io_uring passthrough?

### ISSUE THREAD

**Issue by deepgrace** [axboe/liburing#1170]
Will there be examples for reading or writing NVMe SSD devices (/dev/ng0n1 or /dev/nvme0n2) directly by pure kernel side io_uring passthrough without any dependency on liburing?

I have looked at this [https://github.com/axboe/liburing/blob/master/test/io_uring_passthrough.c](https://github.com/axboe/liburing/blob/master/test/io_uring_passthrough.c)
and tried some times, but it's hard to rewrite the example to a pure kernel side io_uring passthrough to read or write NVMe SSD devices.

**Comment by axboe** [comment]
If helpers are written for that, they would obviously be liburing helpers. I don't have any plans to provide generic raw helpers for that. Any reason you can't just use liburing?
