### ISSUE TITLE
Documentation: referenced IORING_FEAT_ENTER_EXT_ARG flag does not exist

### ISSUE THREAD

**Issue by omion** [axboe/liburing#1171]
Reading the man page for io_uring_setup (from [man/io_uring_setup.2](https://github.com/axboe/liburing/blob/master/man/io_uring_setup.2)), there is a reference to a flag named IORING_FEAT_ENTER_EXT_ARG.
However, [io_uring.h](https://github.com/axboe/liburing/blob/master/src/include/liburing/io_uring.h) defines IORING_ENTER_EXT_ARG and IORING_FEAT_EXT_ARG, but nothing with both FEAT and ENTER.

It's a minor issue since it's fairly obvious it should be IORING_FEAT_EXT_ARG, but it tripped me up for a few minutes.

**Comment by axboe** [comment]
Thanks, I'll fix it up.
