### ISSUE TITLE
io_uring_register_files() always failed with bad file descriptor error (EBADF)

### ISSUE THREAD

**Issue by ytwang3579** [axboe/liburing#1172]
Hi, I was trying to use io_uring with SQPOLL mode for a simple network server example. When I tried to register fd with io_uring_register_files(), I am constantly getting "Bad file descriptor" error. I was doing the initialization of io_uring with the following code:

```c
    struct io_uring ring;
    struct io_uring_params params;

    std::memset(&params, 0, sizeof(params));
    params.flags |= IORING_SETUP_SQPOLL;

    int res = io_uring_queue_init_params(QUEUE_DEPTH, &ring, &params);
    if (res < 0) {
        std::cerr << "Failed to initialize io_uring:" << std::strerror(-res) << "\n";
        close(server_fd);
        return 1;
    }

    res = io_uring_register_files(&ring, &server_fd, 1);
    if (res < 0) {
        std::cerr << "Failed to register file descriptor: " << std::strerror(-res) << "\n";
        close(server_fd);
        return 1;
    }
```
Always getting the following error:
```
Failed to register file descriptor: Bad file descriptor
```

The server example is working without SQPOLL mode. I was trying to register the server_fd to get familiar with the SQPOLL feature. Am I doing anything wrong here?

I also tried running the tests provided using `sudo make runtests`, and it seems like the fds are not able to be registered in all the tests, giving the same -EBADF (-9) error:

```bash
Running test 232c93d07b74.t                                         5 sec
Running test 35fa71a030ca.t                                         5 sec
Running test 500f9fbadef8.t                                         0 sec
Running test 7ad0e4b2f83c.t                                         1 sec
Running test 8a9973408177.t                                         file register -9
Test 8a9973408177.t failed with ret 1

...(truncated)...

Running test d4ae271dfaae.t                                         register files -9
Test d4ae271dfaae.t failed with ret 247

...(truncated)...

Running test fd-install.t                                           failed register files -9
test_working failed
Test fd-install.t failed with ret 1
Running test fd-pass.t                                              Skipped
Running test file-register.t                                        test_basic: register -9
test_basic failed
Test file-register.t failed with ret 1
Running test files-exit-hang-poll.t                                 1 sec
Running test files-exit-hang-timeout.t                              1 sec
Running test file-update.t                                          test_update_multiring: register files failed
test_update_multiring w/unreg
Test file-update.t failed with ret 1

...(truncated)...

Running test iopoll.t                                               file reg failed: -9
test_io failed 0/1/0/0/0
Test iopoll.t failed with ret 1

...(truncated)...

```

What are the requirements for io_uring_register_files() to work? I was only seeing kernel version >= 5.1 [here](https://unixism.net/loti/ref-liburing/advanced_usage.html#c.io_uring_register_files). Thanks in advance!

Full test log: [io_uring_test_result.txt](https://github.com/user-attachments/files/15982437/io_uring_test_result.txt)
Environment (both failed):
- Linux 5.15.153.1-microsoft-standard-WSL2 x86_64 (WSL2 on my Windows laptop)
- Linux 5.15.0-112-generic x86_64 (a remote Linux Ubuntu server)

**Comment by axboe** [comment]
Sorry missed this - yes indeed like @RogerMarcoHernandez says, this is a kernel bug in the distro kernel you are using. If you upgrade, it should be fine. In terms of the stable series of 5.x kernels, 5.4 will be too ancient for you, but 5.10 or 5.15 based should be OK for SQPOLL and registered files.

In general, as per usual, I always recommend people at least run a 6.x based kernel.
