### ISSUE TITLE
liburing/compat.h should #define the RESOLVE_XXX symbols

### ISSUE THREAD

**Issue by cosmosgit** [axboe/liburing#118]
Currently you can not use flags like RESOLVE_NO_XDEV because they are defined in linux/openat2.h.  If both linux/openat2.h and liburing/compat.h are included, a compile error results due to different definitions of struct open_how.  It's caused by the kernel's really annoying habit of defining 64-bit integers as long long.

Until openat2 is covered by glibc:

Solution:
#define the RESOLVE_XXX symbols in liburing/compat.h, so that no inclusion of linux/openat2.h is necessary.

Work-around:
#include <liburing.h>
#define open_how open_how_XXX
#include <linux/openat2.h>
#undef open_how

**Comment by axboe** [comment]
Care to send in a patch?
