### ISSUE TITLE
Ordering guarantees between accept and close?

### ISSUE THREAD

**Issue by SUPERCILEX** [axboe/liburing#1193]
I'm observing the behavior that if a client has its connection reset, then I schedule a close and a multi accept after having run out of fixed files a while back (plus other stuff in the sq), the accept will show up in the completion queue *first* before everything else. Is this intentional? 

Logs:
```
[2024-07-31T03:39:00Z WARN  ringboard_server::reactor] Too many clients clients connected, dropping connection.
[2024-07-31T03:39:00Z TRACE ringboard_server::reactor] Queueing entries: [Entry { op_code: 9, flags: 1, user_data: 13258597302978740228 }, Entry { op_code: 10, flags: 33, user_data: 7493989779944505345 }, Entry { op_code: 19, flags: 0, user_data: 13258597302978740226 }]
[2024-07-31T03:39:00Z DEBUG ringboard_server::reactor] Handling recv completion for client 13.
[2024-07-31T03:39:00Z INFO  ringboard_server::requests] Establishing client/server protocol connection.
[2024-07-31T03:39:00Z TRACE ringboard_server::send_msg_bufs] Allocating send buffer 1.
[2024-07-31T03:39:00Z INFO  ringboard_server::reactor] Client 13 connected.
[2024-07-31T03:39:00Z DEBUG ringboard_server::reactor] Handling sendmsg completion for client 23.
[2024-07-31T03:39:00Z TRACE ringboard_server::send_msg_bufs] Freeing send buffer 0.
[2024-07-31T03:39:00Z DEBUG ringboard_server::reactor] Client 23 closed the connection before consuming all responses.
[2024-07-31T03:39:00Z DEBUG ringboard_server::reactor] Handling recv completion for client 13.
[2024-07-31T03:39:00Z INFO  ringboard_server::reactor] Client 13 closed the connection.
[2024-07-31T03:39:00Z DEBUG ringboard_server::reactor] Handling close completion for client 23.
[2024-07-31T03:39:00Z INFO  ringboard_server::reactor] Restoring ability to accept new clients.
[2024-07-31T03:39:00Z TRACE ringboard_server::reactor] Queueing entries: [Entry { op_code: 9, flags: 1, user_data: 7493989779944505356 }, Entry { op_code: 19, flags: 0, user_data: 7493989779944505346 }, Entry { op_code: 13, flags: 1, user_data: 0 }]
[2024-07-31T03:39:00Z DEBUG ringboard_server::reactor] Handling accept completion.
[2024-07-31T03:39:00Z DEBUG ringboard_server::reactor] Accepting client 13.
thread 'main' panicked at server/src/reactor.rs:293:21:
assertion failed: client_buffers[usize::from(client)].is_none()
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
The last `Queueing entries` line shows that we submitted a sendmsg to to client 13 (shift user_data by 59), a close to client 13, and a multi accept. Then the first thing the completion queue gives us is the accept.

For now I've worked around this by keeping track of pending closes and not re-submitting the accept until we flush all the closes, but that's unpleasant.

**Comment by SUPERCILEX** [comment]
It also seems like `sendmsg`s are getting re-ordered (maybe `recvmsg`s actually?), but only if the recvmsg buffers (`IORING_REGISTER_PBUF_RING`) are exhausted. I haven't ruled out a bug in my code, but it's very suspicious that ordering guarantees when you hit an error condition in io_uring.

Kernel: `Linux pop-os 6.9.3-76060903-generic #202405300957~1721174657~22.04~abb7c06 SMP PREEMPT_DYNAMIC Wed J x86_64 x86_64 x86_64 GNU/Linux`

**Comment by SUPERCILEX** [comment]
For the close/accept bug, I've got an easy reproducer (requires rust nightly): https://github.com/SUPERCILEX/clipboard-history/tree/tmp

Run `RINGBOARD_SOCK=/tmp/dev.sock XDG_DATA_HOME=/tmp RUST_LOG=trace cargo r -p clipboard-history-server` then `RINGBOARD_SOCK=/tmp/dev.sock XDG_DATA_HOME=/tmp cargo r -p clipboard-history d fuzz` in another terminal.

**Comment by isilence** [comment]
Not digging deep into your issue, first ALL requests are asynchronous and should be thought as such, so unless you order them with some `IOSQE_IO_LINK` they can complete in any order. That's true for close/accept, and also sendmsg. With sendmsg the usual way of doing is backlogging data in userspace in an iovec and sending it all at once when you get a completion for the previous send for this socket.

**Comment by SUPERCILEX** [comment]
Oh damn, ok. So just to confirm, recvmsg multis for a given connection will be in order right? But then are you saying that when I submit sendmsgs, the order they get sent out is undefined? Or is it just the order in which I reap them that's undefined?

**Comment by SUPERCILEX** [comment]
Oh yep:

```
              It is important to remember that I/O requests submitted to
              the kernel can complete in any order.  It is not necessary
              for the kernel to process one request after another, in
              the order you placed them.  Given that the interface is a
              ring, the requests are attempted in order, however that
              doesn't imply any sort of ordering on their completion.
              When more than one request is in flight, it is not
              possible to determine which one will complete first.
```

Man I have no idea how my code has worked so well thus far. I always kind of assumed operations on the same frxed files would somehow know to maintain ordering.

How hard would it be for the kernel to keep track of pending sqes on file descriptor IDs and maintain submission order a la IO_LINK, maybe called IO_LINK_FD? That would be pretty useful for a server to be able to maintain "channels".

Anyway, back to reality is there a common pattern to handle `SOCK_SEQPACKET`? This is sad cuz io_uring is basically making it so my local connection doesn't have ordering guarantees anymore. I don't think buffering replies on the server and batching sendmsgs chained with IO_LINK will work because once I've flushed the buffer how do I link the next chain? You could make that work by waiting for all the sendmsgs to show up in the completion queue, but then aren't you losing a bunch of parallelism waiting for the client to acknowledge the whole chain? Or is there kernel buffering and I'll get CQEs for the sendmsgs before the client actually recvmsgs them? Another option is to use sequence numbers in my protocol and just reorder replies on the client.

**Comment by SUPERCILEX** [comment]
Answering my own question, there's a huge amount of internal kernel buffering on sendmsg so no need to worry about parallelism when draining.

**Comment by SUPERCILEX** [comment]
I think I like the idea of server side buffering because it'll simplify my allocator code which is currently global. If I use per client reply allocators, then they can just be rings. Once the allocators is made whole on its last loan, we can flush the buffered messages in one long chain, and repeat.

Anyway this now squarely in "my problem" territory so closing. I do still like the idea of something like IO_LINK_FD.

**Comment by isilence** [comment]
> Oh damn, ok. So just to confirm, recvmsg multis for a given connection will be in order right?

Yes

> How hard would it be for the kernel to keep track of pending sqes on file descriptor IDs and maintain submission order a la IO_LINK, maybe called IO_LINK_FD?

That can be done in the user space just well

> That would be pretty useful for a server to be able to maintain "channels".

Jens added just recently something similar, i.e. buffer ring support for sends

**Comment by SUPERCILEX** [comment]
> That can be done in the user space just well

I don't think so? How would you specify ordering across SQEs that aren't next to each other? Unless you mean userspace buffering? But then you have to wait for the last sendmsg (as quick as that may be) and deal with the burstiness somehow (either with a bigger ring and/or partial buffer draining).

> Jens added just recently something similar, i.e. buffer ring support for sends

Do you mind pointing me to this? Sounds cool.

**Comment by isilence** [comment]
> > That can be done in the user space just well
> 
> I don't think so? How would you specify ordering across SQEs that aren't next to each other? Unless you mean userspace buffering? But then you have to wait for the last sendmsg (as quick as that may be) and deal with the burstiness somehow (either with a bigger ring and/or partial buffer draining).

Yes, I mean waiting for the previous completion before submitting the next one. Sendmsg returns immediately unless it has so much queued up but not yet sent/confirmed that it has to wait anyway (like POLLOUT for epoll). And you don't have to put it into the ring immediately, you can backlog it in the userspace. Pseudo code just to give an idea

```C++
class Sender {
	vector<iovec> iov, backlog;

	sendmsg(buf, len) {
		if (inflight) {
			backlog.push_back(buf, len);
			return;
		}
		iov.push_back();
		submit_sqe();
	}
	process_cqe() {
		inflight = false;
		if (!backlog.empty()) {
			swap(iov, backlog);
			send_next_batch();
		}
	}
}
```

> > Jens added just recently something similar, i.e. buffer ring support for sends
> 
> Do you mind pointing me to this? Sounds cool.

https://lore.kernel.org/io-uring/20240420133233.500590-2-axboe@kernel.dk/

Patches 2/5 and 4/5 in there are for sends

**Comment by SUPERCILEX** [comment]
Great stuff, thank you!
