### ISSUE TITLE
io_uring_prep_recv with IORING_RECVSEND_BUNDLE always fills only one buffer at a time

### ISSUE THREAD

**Issue by yaroslavros** [axboe/liburing#1197]
I cannot figure out a way to get `io_uring_prep_recv` to populate more than one bundle at a time with the new `IORING_RECVSEND_BUNDLE` option available in kernel 6.10.

For example, running proxy example in sink mode with recv bundles and decreasing buffer size to 32 while sending a single 41-byte message results in two separate recvs. In fact, I don't see any difference when I disable bundle option.

That is, running proxy as `./proxy -c1 -m0 -s1 -x1 -V -b32` and sending a message through netcat that is larger than a single buffer: `echo "1234567890123456789012345678901234567890" | nc -N 127.0.0.1 4444` results in two recvs. Reduced output below:
```
Backend: sqpoll=0, defer_tw=1, fixed_files=1, is_sink=1, buf_size=32, nr_bufs=256, host=192.168.3.2, send_port=-1, receive_port=4444, napi=0, napi_timeout=0, huge_page=0
 recv options: recvmsg=0, recv_mshot=0, recv_bundle=1
 send options: sendmsg=0, send_ring=1, send_bundle=0, send_zerocopy=0
0: recv buffer ring bgid 1, bufs 256
0: recv: bid=0, res=32, cflags=5
0: recv: bid=1, res=9, cflags=10005
Conn 0/(in_fd=-1, out_fd=-1): qps=2, msec=0
	  0: rcv=2 (short=1, enobufs=0), snd=0 (short=0, busy=0, enobufs=0)
	   : in_bytes=41 (Kb 0), out_bytes=0 (Kb 0)
	   : mshot_rcv=0, mshot_snd=0
	 Packets per recv/send:
	 bucket(  1): rcv=2 snd=0
```

Output with bundles disabled is exactly the same.

How to get recv to populate multiple buffers as a bundle?

**Comment by axboe** [comment]
Try with -m1 - I'll take a look at the singleshot case.

**Comment by yaroslavros** [comment]
Still two recvs with multishot.

```
0: recv: bid=0, res=32, cflags=7
0: recv: bid=1, res=9, cflags=10007
Conn 0/(in_fd=-1, out_fd=-1): qps=2, msec=0
	  0: rcv=2 (short=1, enobufs=0), snd=0 (short=0, busy=0, enobufs=0)
	   : in_bytes=41 (Kb 0), out_bytes=0 (Kb 0)
	   : mshot_rcv=1, mshot_snd=0
	 Packets per recv/send:
	 bucket(  1): rcv=2 snd=0
```

**Comment by axboe** [comment]
I see what it is... If you try eg 8 byte buffers, you should get the right thing in loop 2. First loop doesn't properly get it all. I'll take a look, we should be able to improve the first loop and just have it expand, it currently does not which is why you get 1 first and then one loop with the rest. Your case has less than a buffer left, so you just see one currently.

**Comment by axboe** [comment]
The reason loop 2 gets it all is because at that point we know how much is left in the socket to receive, and for the first one we do not. This is done on purpose to avoid over-selecting buffers. But would be nice if we got everything in the first loop when we can...

**Comment by yaroslavros** [comment]
Thank you for the quick response. Indeed, second recv gets multi-buffer treatment in both singleshot and multishot cases.

Would be great to document that somewhere - it's not very obvious!

**Comment by axboe** [comment]
Yeah you're right, I'll document it. The technical reason is that post the first receive, we know how much more is left, and then we can grab all of that. It does annoy me a bit, I almost wonder if we should opportunistically grab at least, say, 4 buffers for the first one. That should be cheap enough that we may as well do it, and perhaps it'll cover all of what's in the socket. But it's a bit of guesswork at that point, thought he 1 + rest is also suboptimal in the sense that it'd probably be better to do 4 + 4 or something like that, if 4 is the rest as well. I'll experiment a bit...

Doesn't change the fact that it should be documented, regardless what the first receive might end up being.

**Comment by axboe** [comment]
We could do something like the below, which will query the socket before the receive... With that, we'd always grab the maximum that we could, at the cost of doing an internal SIOCINQ upfront.

```
diff --git a/io_uring/net.c b/io_uring/net.c
index 594490a1389b..76d0a73caf45 100644
--- a/io_uring/net.c
+++ b/io_uring/net.c
@@ -10,6 +10,8 @@
 
 #include <uapi/linux/io_uring.h>
 
+#include <asm/ioctls.h>
+
 #include "io_uring.h"
 #include "kbuf.h"
 #include "alloc_cache.h"
@@ -1076,8 +1078,20 @@ static int io_recv_buf_select(struct io_kiocb *req, struct io_async_msghdr *kmsg
 			arg.mode |= KBUF_MODE_FREE;
 		}
 
-		if (kmsg->msg.msg_inq > 0)
+		if (kmsg->msg.msg_inq > 0) {
 			arg.max_len = min_not_zero(sr->len, kmsg->msg.msg_inq);
+		} else {
+			struct socket *sock = req->file->private_data;
+			struct proto *prot = READ_ONCE(sock->sk->sk_prot);
+
+			if (prot && prot->ioctl) {
+				int inq = 0;
+
+				ret = prot->ioctl(sock->sk, SIOCINQ, &inq);
+				if (!ret)
+					arg.max_len = inq;
+			}
+		}
 
 		ret = io_buffers_peek(req, &arg);
 		if (unlikely(ret < 0))
```

**Comment by yaroslavros** [comment]
I am no expert in kernel programming by any means, but I suspect that an internal SIOCINQ is cheaper than another recv.

**Comment by axboe** [comment]
> I am no expert in kernel programming by any means, but I suspect that an internal SIOCINQ is cheaper than another recv.

Certainly, it's a clear win for the case where you can get > 1 buffer upfront. But if there's only the one buffer (or less than one) ready, then it's a waste of time. However, it's certainly an all-round better solution than overshooting the buffer peeks for when you don't know upfront how much is pending.

I'm still leaning towards this being a worthwhile addition, just need to run some testing to fully vet it.

**Comment by axboe** [comment]
Agree that it's really an application decision, but the problem is that the application may also not know. Punting decisions like that to the application doesn't necessarily solve the problem.

For the SIOCINQ, this is essentially what's being done inside the receive as well, directed by io_uring wanting to know how much is left. When done in there, it's basically free, as the socket is already locked etc. Doing it upfront is certainly not free, as the socket needs to get locked first. Hence I'm reluctant to just do it unconditionally. I _think_ it may make more sense to simple cap the peeked buffers at something reasonable, like 4, and do that first receive. Worst case we have 1 more buffer, and then we're in the same situation we are now, where we would do 4+1 rather than just 1+4. Best case, we have 4 buffers. Normal case, we probably get 1-2 and there's nothing else left, in which case the extra work for picking 4 buffers is really noise.

**Comment by axboe** [comment]
Ran some testing, and the opportunistic approach of just going to 4 entries does seem to work the best, based on testing with both loaded recv (where you basically can get lots of buffers all the time) and smaller send sizes where the number of packets received is all over the map. FWIW, this is what I tested:

```
diff --git a/io_uring/kbuf.c b/io_uring/kbuf.c
index c95dc1736dd9..bbb0cffc9d9a 100644
--- a/io_uring/kbuf.c
+++ b/io_uring/kbuf.c
@@ -209,6 +209,7 @@ static int io_ring_buffers_peek(struct io_kiocb *req, struct buf_sel_arg *arg,
 	int nr_iovs = arg->nr_iovs;
 	__u16 nr_avail, tail, head;
 	struct io_uring_buf *buf;
+	int needed = 0;
 
 	tail = smp_load_acquire(&br->tail);
 	head = bl->head;
@@ -218,19 +219,21 @@ static int io_ring_buffers_peek(struct io_kiocb *req, struct buf_sel_arg *arg,
 
 	buf = io_ring_head_to_buf(br, head, bl->mask);
 	if (arg->max_len) {
-		int needed;
-
 		needed = (arg->max_len + buf->len - 1) / buf->len;
 		needed = min(needed, PEEK_MAX_IMPORT);
-		if (nr_avail > needed)
-			nr_avail = needed;
+	} else if (arg->max_vecs) {
+		needed = arg->max_vecs;
 	}
 
+	if (nr_avail > needed)
+		nr_avail = needed;
+
 	/*
 	 * only alloc a bigger array if we know we have data to map, eg not
 	 * a speculative peek operation.
 	 */
-	if (arg->mode & KBUF_MODE_EXPAND && nr_avail > nr_iovs && arg->max_len) {
+	if (arg->mode & KBUF_MODE_EXPAND && nr_avail > nr_iovs &&
+	    (arg->max_len || arg->max_vecs)) {
 		iov = kmalloc_array(nr_avail, sizeof(struct iovec), GFP_KERNEL);
 		if (unlikely(!iov))
 			return -ENOMEM;
@@ -238,7 +241,7 @@ static int io_ring_buffers_peek(struct io_kiocb *req, struct buf_sel_arg *arg,
 			kfree(arg->iovs);
 		arg->iovs = iov;
 		nr_iovs = nr_avail;
-	} else if (nr_avail < nr_iovs) {
+	} else if (nr_iovs > nr_avail) {
 		nr_iovs = nr_avail;
 	}
 
diff --git a/io_uring/kbuf.h b/io_uring/kbuf.h
index b90aca3a57fa..8248ffda3a43 100644
--- a/io_uring/kbuf.h
+++ b/io_uring/kbuf.h
@@ -53,7 +53,8 @@ struct buf_sel_arg {
 	size_t out_len;
 	size_t max_len;
 	int nr_iovs;
-	int mode;
+	unsigned short mode;
+	unsigned short max_vecs;
 };
 
 void __user *io_buffer_select(struct io_kiocb *req, size_t *len,
diff --git a/io_uring/net.c b/io_uring/net.c
index 594490a1389b..06fa66c32271 100644
--- a/io_uring/net.c
+++ b/io_uring/net.c
@@ -1078,6 +1078,8 @@ static int io_recv_buf_select(struct io_kiocb *req, struct io_async_msghdr *kmsg
 
 		if (kmsg->msg.msg_inq > 0)
 			arg.max_len = min_not_zero(sr->len, kmsg->msg.msg_inq);
+		else
+			arg.max_vecs = 4;
 
 		ret = io_buffers_peek(req, &arg);
 		if (unlikely(ret < 0))
```

**Comment by axboe** [comment]
https://lore.kernel.org/io-uring/5fa6fc2f-b39f-4327-a195-61997d36b0e8@kernel.dk/
