### ISSUE TITLE
io_poll and sqpoll cause IOPS degradation

### ISSUE THREAD

**Issue by aidosww** [axboe/liburing#1205]
The configuration of io_poll and sqpoll results in file write performance degradation. The environment used is as follows:​
1、Linux kernel 5.10​ and kernel 6.2
2. The storage device is an SSD.​
3. With sqpoll and io_poll enabled:​
======IOPS (WRITE): 47147.57 in 2.12 seconds for 409468928 bytes​
When using the default configuration without enabling the feature:​
======IOPS (WRITE): 179856.12 in 0.56  seconds for 409468928 bytes

Can anyone help me? Thank you very much.

**Comment by axboe** [comment]
SQPOLL doesn't magically make things faster. It's a way to offload submission to a dedicated thread, and leave the normal task free to do other things.

IOPOLL requires special nvme setup, setting the ```poll_queues``` parameter to assign specific pollable nvme queues. Without that, you're still using IRQ driven IO, with the only change being that you're now spinning looking for the completions generated by an IRQ. With a properly setup nvme device with pollable queues, no IRQs will be triggered, and the polling will actually do something useful.
