### ISSUE TITLE
Behavior of io_uring_wait_cqes is not documented for null `ts`

### ISSUE THREAD

**Issue by travisdowns** [axboe/liburing#1209]
It does not seem to be documented what the behavior of `io_uring_wait_cqes` when `ts` is NULL. It is implicitly allowed to be NULL by "If ts is specified and an older kernel without..." but it isn't clear what happens. Is it an infinite timeout or no timeout (like peek) or something else?

**Comment by axboe** [comment]
Like any of the timeout functions, if NULL is given it's an infinite timeout.
