### ISSUE TITLE
Threading support 

### ISSUE THREAD

**Issue by JsBlueCat** [axboe/liburing#121]
i have 8 disks to wirte and each disk holds 5T spaces.
i need to write 8 * 5T buffer to all disks as fast as possible.
what i think is using  8 threads for 8 disks, and use io_uring to sync write 5T to one disk. 
can you give me any suggestion ? 
@kkourt @bgianfo

**Comment by YoSTEALTH** [comment]
@JsBlueCat Are you still having this issue? Is it writing the same buffer to all 8 disks?

**Comment by axboe** [comment]
As mentioned in other issues, just use a ring per thread.
