### ISSUE TITLE
Unexpected cqe->res at connection refused from `connect`

### ISSUE THREAD

**Issue by vsolontsov-ll** [axboe/liburing#1217]
We received `cqe->res == EPOLLRDHUP | EPOLLHUP | EPOLLERR | EPOLLOUT` for `IORING_OP_POLL_ADD` operation when tried to tcp-connect to a free port (a not listened one).

For `epoll` it's not the case -- it doen't set `EPOLLOUT`. 

What we do with a stream IP async socket:
* connect() to a wrong port 
* `IORING_OP_POLL_ADD`  for `EPOLLOUT | EPOLLET`
* wait for completion and receive `EPOLLOUT` in addition to HUP and ERR.

I will prepare a reproducing example shortly. But please could you let me know if this behavior is intended.

**Comment by axboe** [comment]
Please post the example.

**Comment by vsolontsov-ll** [comment]
[poll_connect.c.gz](https://github.com/user-attachments/files/16853079/poll_connect.c.gz)
Here it is.

**Comment by axboe** [comment]
I get the same for poll(2), epoll(2), and io_uring - all have 0x1c as the bottom mask for this case.

**Comment by vsolontsov-ll** [comment]
I beg your pardon, I had to check it myself before raising.
