### ISSUE TITLE
liburing 2.7 _GNU_SOURCE cflags in pkg-config is breaking downstream projects

### ISSUE THREAD

**Issue by laf0rge** [axboe/liburing#1218]
I think it is not a good idea for a system library to expose `#define _GNU_SOURCE` to each and every file / compile unit of each and every downstream project.  This is highly unusual, in my opinion.

It's of course fine for liburing to `#define` whatever it wants for compiling its own sourec code.  It's equally fine to have the `#define` in specific header files that might rely on importing stuff from libc that requires `_GNU_SOURCE`.  But putting it in in the Cflags of pkg-config is a bit over-reaching, IMHO

_Originally posted by @laf0rge in https://github.com/axboe/liburing/issues/422#issuecomment-2326352870_

We've seen already fall-out from this for example in libosmocore: https://gerrit.osmocom.org/c/libosmocore/+/38003 - sure, we can work around it and one could argue that's a separate topic.

But liburing influencing key behaviour of loads if includes in every single project that depends on it still sounds like a bad idea.

**Comment by axboe** [comment]
I was a bit confused about this as we just use it internally as it should not be required and we should not be doing it, but I guess it's in liburing.pc.in and that is the complaint? Whatever liburing does internally should not matter, but we should not be exposing this to application unconditionally, agree on that.

**Comment by laf0rge** [comment]
> I was a bit confused about this as we just use it internally as it should not be required and we should not be doing it, but I guess it's in liburing.pc.in and that is the complaint? Whatever liburing does internally should not matter, but we should not be exposing this to application unconditionally, agree on that.

If you just want to use the `_GNU_SOURCE` internally, it should not be exposed via the pkg-config `Cflags` field. You can simply use it in your Makefile[.am]. The `Cflagas` in pkg-config latter is for what you as liburing request downstream projects to use when they compile their projects.

For `Libs` and `Requires`, pkg-config has a `Libs.private` and `Requires.private`, respectively.  It doesn't offer that for `Cflags`, I suppose wit the rationale that it's irrelevant to pkg-config what kind of compiler flags you used to compile liburing itself.  This is not of concern to the downstream users, and hence it should not be mentioned in pkg-config at all.

**Comment by axboe** [comment]
Yeah we could just define _GNU_SOURCE in liburing.h, I guess that'd fix the issue for applications too without being too overreaching. I'll make the change.

**Comment by axboe** [comment]
Might be easier to just tag a 2.7.1 release with that pulled in. Not quite ready to do a 2.8 release just yet, but a minor release with the fix might make sense and easier on distros.

**Comment by isilence** [comment]
> Yeah we could just define _GNU_SOURCE in liburing.h, I guess that'd fix the issue for applications too without being too overreaching. I'll make the change.

I don't see much of a difference, hmm? Sure, it's not in cflags, but it'll be dependent on the include order, which IMHO is even worse.

**Comment by axboe** [comment]
Yeah it won't cover everything, but nothing will outside of the application setting it. At least it'll have cpu_set_t and loff_t available for our definitions, and hence won't break compiles for applications that use neither. And that's enough of a reason to do it, imho.

**Comment by laf0rge** [comment]
> I don't see much of a difference, hmm? Sure, it's not in cflags, but it'll be dependent on the include order, which IMHO is even worse.

I think it makes a difference in that it constrains it to those specific files (compile units) that actually #include liburing.h, which in any reasonably complex software project is justa very small fraction.  Furthermoe, it's only affecting the libc-headers which are pulled in as dependency from liburing.h, or after it.

Normally the include order should be as follows:

* first include headers from libc / standard libray
** no _GNU_SOURCE applies in the proposed scheme
* then have includes of libraries like liburing
** here _GNU_SOURCE is applied and becomes relevant for those headers that liburing.h includes
* finally, application-private includes
** those are the only ones that might be affected by the _GNU_SOURCE

You might even improve the situation if you #undef _GNU_SOURCE again at the end of liburing.h? - but of course only if it wasn't set explicitly outside of liburing.h...

IMHO it's about minimizing the exposure.  But of course the current approach by @axboe is even more conservative, putting the _GNU_SOURCE responsibility to downstream users.

**Comment by axboe** [comment]
Might make sense to do something stupid ala:

```
#ifndef __GNU_SOURCE
#define _GNU_SOURCE
#define PLEASE_UNDEF_GNU_SOURCE
#endif

[end of liburing.h]
#ifdef PLEASE_UNDEF_GNU_SOURCE
#undef _GNU_SOURCE
#endif
```

but it's getting a bit ridiculous at that point. But it's also kind of annoying to leak it depending on header order, so...

**Comment by axboe** [comment]
Added the nasty hack above - I'll close this one as I think we have all bases covered now, at least to the extent that I care about. Just re-open if anyone disagrees.

**Comment by isilence** [comment]
> > I don't see much of a difference, hmm? Sure, it's not in cflags, but it'll be dependent on the include order, which IMHO is even worse.
> 
> I think it makes a difference in that it constrains it to those specific files (compile units) that actually #include liburing.h, which in any reasonably complex software project is justa very small fraction.

Yes, comparing to the un-patched version, but I rather mean the difference between approaches.

> Furthermoe, it's only affecting the libc-headers which are pulled in as dependency from liburing.h, or after it.

Yes, which is not a good thing because now you can suddenly get a different behaviour just because headers were pulled in different order. And let's not forget about include guards, if a header liburing depends on was included before `liburing.h` and without `_GNU_SOURCE`, liburing.h will 'see' the version of the header without `_GNU_SOURCE` regardless of whether you define it after or not.

> You might even improve the situation if you #undef _GNU_SOURCE again at the end of liburing.h? - but of course only if it wasn't set explicitly outside of liburing.h...

Same goes for this one, but it's even nastier. because that fails, the user will observe that it behaves as `_GNU_SOURCE` but it's never defined in the user program, and that would take some time to notice that liburing.h sneaked def/undef in and included a header you need.

**Comment by guillemj** [comment]
@isilence Thanks! Was going to mention exactly what you covered here. :)  @axboe And thanks for getting back to the original fix. I've now just uploaded a revision including that patch to Debian.

**Comment by laf0rge** [comment]
> Might be easier to just tag a 2.7.1 release with that pulled in. Not quite ready to do a 2.8 release just yet, but a minor release with the fix might make sense and easier on distros.

I think a patch release would be useful, as it's more likely distros will pick it up.  I've just received reports that arch users are facing the problem, too [just an example, will be the same for any distro that starts to include 2.7]. Thanks!
