### ISSUE TITLE
config error 

### ISSUE THREAD

**Issue by JsBlueCat** [axboe/liburing#122]
``` bash
$ ./configure 
```
prefix                        /usr
includedir                    /usr/include
libdir                        /usr/lib
libdevdir                     /usr/lib
relativelibdir                
mandir                        /usr/man
datadir                       /usr/share
__kernel_rwf_t                yes
__kernel_timespec             no
open_how                      no
statx                         yes

does __kernel_timespec  and open_how affect the aio?
Linux cery-ll-titanv 5.3.0-46-generic #38~18.04.1-Ubuntu SMP Tue Mar 31 04:17:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

Compiling test case __kernel_rwf_t
gcc -D_GNU_SOURCE -include config-host.h -o /tmp/fio-conf--12709-.exe /tmp/fio-conf--12709-.c
Compiling test case __kernel_timespec
gcc -D_GNU_SOURCE -include config-host.h -o /tmp/fio-conf--12709-.exe /tmp/fio-conf--12709-.c
/tmp/fio-conf--12709-.c:2:10: fatal error: linux/time_types.h: No such file or directory
 #include <linux/time_types.h>
          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
Compiling test case open_how
gcc -D_GNU_SOURCE -include config-host.h -o /tmp/fio-conf--12709-.exe /tmp/fio-conf--12709-.c
/tmp/fio-conf--12709-.c: In function ‘main’:
/tmp/fio-conf--12709-.c:7:19: error: storage size of ‘how’ isn’t known
   struct open_how how;
                   ^~~
Compiling test case statx
gcc -D_GNU_SOURCE -include config-host.h -o /tmp/fio-conf--12709-.exe /tmp/fio-conf--12709-.c

@bgianfo @thoughtpolice @wdauchy @kkourt @markpapadakis  
please help~ thanks

**Comment by JsBlueCat** [comment]
> Not sure what is being reported here. It's normal for the configure script to have errors, that's how we detect what features/defines are there, and which ones we have to provide.

i want to fix __kernel_timespec       no  to be yes 
so how can i add the times_type.h ?

**Comment by axboe** [comment]
Update your kernel/libc headers? This isn't really a liburing issue at all.

**Comment by JsBlueCat** [comment]
> Update your kernel/libc headers? This isn't really a liburing issue at all.

sorry for my stupid question.
but i really need your perfect project.  

i meet with
 open_how                      no

/tmp/fio-conf--24247-.c: In function ‘main’:
/tmp/fio-conf--24247-.c:7:19: error: storage size of ‘how’ isn’t known
   struct open_how how;

how can i fix this error . i have update libc to 5.3

**Comment by axboe** [comment]
Why do you need to fix it? liburing provides its own struct open_how, if the system doesn't have one. The whole point of the configure check is to see if we have one, or if we need to define it. If the check fails, then src/include/liburing/compat.h will have the definition.

**Comment by RamonLopezEsc** [comment]
I was having the same problem reported here. This header is necessary to complete the installation process successfully.

I downloaded the header from this URL: https://elixir.bootlin.com/linux/latest/source/include/uapi/linux/time_types.h

Later, I save it in the following path: /usr/include/linux/time_types.h

And... voila! Problem solved (:
