### ISSUE TITLE
How does io_uring_prep_timeout_remove know what to remove?

### ISSUE THREAD

**Issue by Oipo** [axboe/liburing#1243]
I'm having a hard time deciphering the `io_uring_prep_timeout_remove` man page. 

If I create a new timer like so:
```c++
auto *sqe = io_uring_get_sqe(ring);
io_uring_sqe_set_data(sqe, new SomeInternalStructWithCallback{...});
io_uring_prep_timeout(sqe, &_timespec, 0, 0); //_timespec is some long-lived variable in my class
```

How do I then remove the timeout?

**Comment by axboe** [comment]
See the man page for ```io_uring_prep_cancel()``` and related helpers, you can cancel any request based on a number of criteria. You don't need to use timeout_remove helpers, though you can.

**Comment by Oipo** [comment]
Aaah, gotcha. Thanks!
