### ISSUE TITLE
question: multithreading, sqe, cqe and io_uring_wait_cqes

### ISSUE THREAD

**Issue by bradprob** [axboe/liburing#125]
Hi,
my application handles read and writes in following fashion:
**Thread1:**
```
while(application_alive) {
  blocks_on_write_request_with_timeout();
   for_each_write_request() {
      create_io_uring_send_request()
    }
    io_uring_submit()
}
```
**Thread2:**
```
while(application_alive) {
  blocks_on_completion_queue_with_timeout();
   for_each_completed_element() {
      handle_element();
    }
}
```

A comment above `io_uring_wait_cqes` in the liburing source code says:
> * If 'ts' is specified, the application need not call io_uring_submit() before
> * calling this function, as we will do that on its behalf. From this it also
> * follows that this function isn't safe to use for applications that split SQ
> * and CQ handling between two threads and expect that to work without
> * synchronization, as this function manipulates both the SQ and CQ side.

If I understand the comment correctly, I cannot use `io_uring_wait_cqes()` in `block_on_completion_queue_with_timout()`. 

What is the solution to achieve the desired read and write handling?

**Comment by isilence** [comment]
From kernel 5.11 it will supports timeout CQ waits that don't do submit or anything SQ related, so safe to use in parallel. The liburing's interfaces will stay same, but it's as described only if IORING_FEAT_EXT_ARG is set.
