### ISSUE TITLE
io_uring_prep_cancel Not Returning -ECANCELED for Canceled Operations

### ISSUE THREAD

**Issue by Degoah** [axboe/liburing#1252]
**Description:**

When using **io_uring_prep_cancel** to cancel an ongoing recvmsg request in a separate thread, the completion queue event (cqe->res) does not always return the expected **-ECANCELED** code. Instead, it may return a different result, such as the completion result of the operation or another error code, even though the cancellation request was successfully submitted.

This behavior occurs in the following scenario:

1. A recvmsg request is submitted to io_uring via **io_uring_prep_recvmsg**.
2. A cancellation request is issued via **io_uring_prep_cancel** from a separate thread after a brief delay (e.g., 2 seconds).
3. The completion event (cqe->res) does not return **-ECANCELED**, but another code such as a regular result or error, indicating that the request was not properly marked as canceled.

**Code Snippet:**
  
```
io_uring_sqe *sqe = io_uring_get_sqe(&ring);
io_uring_prep_recvmsg(sqe, sock, &msg, 0);
io_uring_submit(&ring);
                
// After some delay, in a separate thread:
io_uring_sqe *cancel_sqe = io_uring_get_sqe(&ring);
io_uring_prep_cancel(cancel_sqe, sqe, 0);
io_uring_submit(&ring);

//.....

int ret = io_uring_wait_cqe(&ring, &cqe);
if (ret < 0) {
 std::cerr << "Error waiting for completion event: " << strerror(-ret) << std::endl;
 break;
}

// Check if the request was canceled
if (cqe->res == -ECANCELED) {
	std::cout << "Request was successfully canceled" << std::endl;
} else if (cqe->res < 0) {
	std::cerr << "I/O operation failed: " << strerror(-cqe->res) << std::endl;
} else {
	std::cout << "I/O operation completed successfully with result: " << cqe->res << std::endl;
}

io_uring_cqe_seen(&ring, cqe);
```

**Expected Behavior:**
When **io_uring_wait_cqe** receives the completion event for the canceled recvmsg operation, cqe->res should return **-ECANCELED**, indicating that the request was successfully canceled.

Actual Behavior:
In some cases, cqe->res returns a different value, such as the result of the operation or another error code, even though a cancel request was submitted and expected to take effect.

This issue appears to cause confusion when trying to cancel operations, as the result does not correctly reflect that the operation was canceled. Any guidance on why this occurs or whether this is intended behavior would be helpful.

**2nd Question/Issue** 
What is the common best-practice approach to cancel ongoing **io_uring_wait_cqe** blocking-calls if the application needs to be shutdown cleanly. 

Do we need to cancel first every single ongoing async SEQ-Request by invoking **io_uring_prep_cancel** and afterwards call **io_uring_queue_exit**. I cannot see any other way to to shutdown my application as the im blocked in my thread which blocks on **io_uring_wait_cqe**. Another thread just would issue **io_uring_prep_cancel** to make the blocking call exit.

Any suggestion are very appreciated.

Thx,

Rafael

**Comment by axboe** [comment]
Missing some key information here, like which kernel you are running. A few questions outside of that:

1) Are you sharing this ring between threads? If so, do you have proper synchronization in place?
2) Can you provide a trace of the above? Should be as simple as:

```
# echo 1 > /sys/kernel/debug/tracing/events/io_uring/enable
# run basic reproducer
# cat /sys/kernel/debug/tracing/trace > some_file
```

and then attach ```some_file``` in here.

**Comment by Degoah** [comment]
kernel: 6.1.20

1. no! 
2. not yet able to to it, as it is used on an embedded device I have no access today.

**Comment by Degoah** [comment]
To resolve this issue, maybe you can provide me an example. If you are aware that it works, so provide me a working example which acks that -ECANCELED gets returned as error code.:)

**Comment by axboe** [comment]
If you're not sharing the ring between threads, how is your cancelation request on another thread related to the first ring? One of these must be true:

1) You're sharing the ring and issuing a cancelation request on that same ring from another thread
2) The other thread is using another ring, and then how on earth would it be able to cancel a request on a different ring?

For an example, test/ in the liburing directory has many tests that include canceling a request. For a recvmsg example, test/recv-multishot.c has one.

**Comment by Degoah** [comment]
@axboe I will deliver a working example as soon as possible. Thx so far!

**Comment by Degoah** [comment]
> If you're not sharing the ring between threads, how is your cancelation request on another thread related to the first ring? One of these must be true:
> 
>     1. You're sharing the ring and issuing a cancelation request on that same ring from another thread
> 
>     2. The other thread is using another ring, and then how on earth would it be able to cancel a request on a different ring?
> 
> 
> For an example, test/ in the liburing directory has many tests that include canceling a request. For a recvmsg example, test/recv-multishot.c has one.

I just have a constallation where I start one thread. That thread is issuing a "io_uring_prep_recvmsg" request to the unique ring I manage in my app. Afterwards my application is blocking in "io_uring_wait_cqe". So fine so good.
Next, I have also register a signal handler, which has access to the ring. In that signal handler I just do this here

```
        // ....
	// Cancel any pending io_uring requests related to the receiving of data.
	io_uring_sqe *sqe = io_uring_get_sqe(&m_ring_rx);
	if (sqe) {
		// If the producer thread is blocking in the io_uring_wait_cqe call,
		// we must unblock it by pushing a "cancel" request to the io_uring queue.
		io_uring_prep_cancel_fd(sqe, m_udp_socket, 0);
		// Submit the cancel request
		io_uring_submit(&m_ring_rx);
	}
```

Now, I would expect, that the blocking call to "io_uring_wait_cqe" returns, what it actually does.

```                      
                        //...
			// Wait for the completion event
			int ret = io_uring_wait_cqe(&m_ring_rx, &cqe);
			if (cqe->res == -ECANCELED) {
				std::cout << "rariru: do_receive(): ECANCELED " << std::endl;
			}
		       //...	
```

Unfortunately, the "-ECANCELED" doesn't get set after the function "io_uring_wait_cqe" unblocks.

What Am I doing wrong here?

**Comment by redbaron** [comment]
I suspect return value is `EINTR`? then it might be expected

**Comment by Degoah** [comment]
Youre damn right. How could I overlook that;). So, for cancelling an ongoing blocking "io_uring_wait_cqe" there is actually no reason to check for "ECANCELLED", just for the EINTR instead. Is this the common way to do it?

**Comment by redbaron** [comment]
Common way to handle EINTR is to retry same operation

**Comment by axboe** [comment]
Additionally, _always_ check the return value io_uring_wait_cqe() and related wait helpers for this very reason. You can't just do:

```
ret = io_uring_wait_cqe(ring, &cqe);
if (cqe->res)
    ....
```

as you don't know if CQE is valid unless ret == 0.

**Comment by redbaron** [comment]
just for my education,  how safe it is to make io_uring calls from signal handler?

**Comment by Degoah** [comment]
Yes, it is unsafe. Looking for an alternative solution now, how to unblock the thread which is waiting in io_uring_wait_cqe() .

**Comment by axboe** [comment]
Getting a signal should very much unblock io_uring_wait_cqe_timeout(), it should abort waiting on any signal.

**Comment by Degoah** [comment]
...unfortunately it doesn't unblock. I tried it several times. Please give it a try and let me know what u got. Thx

**Comment by axboe** [comment]
```
axboe@m2max-kvm ~> ./sig-wait
^C⏎
axboe@m2max-kvm ~ [SIGINT]> ./sig-wait
wait ret: -62
axboe@m2max-kvm ~> uname -r
6.1.112-06896-gaa4cd140bba5
```

Works for me, example I used below. This is using 6.1.112 as seen above.

Example:

```
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <liburing.h>

int main(int argc, char *argv[])
{
	struct io_uring_sqe *sqe;
	struct io_uring_cqe *cqe;
	struct io_uring ring;
	struct __kernel_timespec ts;
	char buf[32];
	int fds[2];
	int ret;

	io_uring_queue_init(64, &ring, 0);

	if (pipe(fds) < 0) {
		perror("pipe");
		return 1;
	}

	sqe = io_uring_get_sqe(&ring);
	io_uring_prep_read(sqe, fds[0], buf, sizeof(buf), 0);
	io_uring_submit(&ring);

	ts.tv_sec = 5;
	ts.tv_nsec = 0;
	ret = io_uring_wait_cqe_timeout(&ring, &cqe, &ts);

	printf("wait ret: %d\n", ret);
	io_uring_queue_exit(&ring);
	return 0;
}
```

**Comment by Degoah** [comment]
Thx for the fast and great example. Will give it a trail tomorrow.

**Comment by axboe** [comment]
Thanks for the followup! Closing this one.
