### ISSUE TITLE
is there a way to add new entry while ring is waiting for cqe

### ISSUE THREAD

**Issue by Sherlock-Holo** [axboe/liburing#127]
I am trying to use io_uring and I run 2 threads:
- one is waiting for the ring, if it returns, handle the.
- the second one creates an entry and uses `prep_readv` to set it and push it into sq.

I found if the first thread is waiting, the second thread push entry won't let the first thread return.

**Comment by Sherlock-Holo** [comment]
I try submit again after push entry to sq, and the wait_for_cqe can return now.

Will there be any problems when I do this?

**Comment by axboe** [comment]
No, that is fine.
