### ISSUE TITLE
6.12-rc3: reading from O_NONBLOCK DRM file descriptor returns EAGAIN

### ISSUE THREAD

**Issue by mahkoh** [axboe/liburing#1270]
In https://github.com/mahkoh/jay/issues/297 a user reported that reading from a DRM file descriptor returns EAGAIN. This breaks my compositor since it will exit the DRM event handling loop in case of an error.

I have confirmed that systemd sets the O_NONBLOCK flag on the file descriptor before giving it to the compositor.

Explicitly unsetting this flag fixes the issue in 6.12-rc3.

This issue does not occur in 6.11 with or without the O_NONBLOCK flag.

This is similar to https://github.com/axboe/liburing/issues/364 but not the same. systemd has always set the O_NONBLOCK flag but the issue did not occur before.

**Comment by KyunLFA** [comment]
Hi, I'm the user who reported the issue on the Jay compositor's side. It's indeed fixed on my end by unsetting O_NONBLOCK as by https://github.com/mahkoh/jay/pull/298 . If needed, I can provide further testing (I compile the kernel for fun ;D) and information about my system. Anyway, here is a trimmed inxi --basic:

<details>
  <summary>System Info</summary>

  ```

System:
  Kernel: 6.12.0-rc3 arch: x86_64 Distro: CachyOS Rolling
Machine:
Mobo: ASRock model: B650M-HDV/M.2
UEFI: American Megatrends LLC. v: 3.06 date: 07/29/2024
CPU:
  Info: 12-core AMD Ryzen 9 7900X
Graphics:
  AMD Navi 32 [Radeon RX 7800 XT] (radeonsi navi32 ACO DRM 3.59)  driver: amdgpu
  Display: 
  X.org v: 1.21.1.13 with: Xwayland v: 21.1.99
  driver: X: 
  loaded: modesetting
  dri: radeonsi gpu: amdgpu 
  resolution: 1920x1080~75Hz
  API: OpenGL v: 4.6 compat-v: 4.5 
  v: 24.2.4-arch1.2.1
Network:
  Device-1: Realtek RTL8125 2.5GbE driver: r8169
Drives:
  Local Storage: total: 1.48 TiB used: 1.31 TiB (88.5%)
Memory: 
  total: 96 GiB note: est. available: 93.86 GiB used: 4.31 GiB (4.6%)
  ```

**Comment by mahkoh** [comment]
https://github.com/torvalds/linux/commit/f7c9134385331c5ef36252895130aa01a92de907 looks suspicious.

**Comment by KyunLFA** [comment]
@mahkoh I think you're right on the nose here. I reverted that commit (https://github.com/torvalds/linux/commit/f7c9134385331c5ef36252895130aa01a92de907) and now pre- https://github.com/mahkoh/jay/pull/298 Jay no longer hangs on 6.12-rc3. Good find.

**Comment by axboe** [comment]
I figured that'd be the commit. I'll take a look at this. As a side note, the drm fops really should support ->read_iter() for proper handling in general. The kernel obviously should not return -EAGAIN here, and I'll sort that out, but it'd work more efficiently if it did.

That said, thanks a ton for testing -rc kernels! I'll write a test case for this and fix the issue. Won't make -rc4, but it'll be in -rc5 for sure.

**Comment by mahkoh** [comment]
>I figured that'd be the commit. I'll take a look at this.

FYI I believe in the diff above you accidentally removed the `!` after the `&&`.

**Comment by axboe** [comment]
> FYI I believe in the diff above you accidentally removed the ! after the &&.

Does indeed look like it! Want me to just patch it up, or do you want to send a patch to fix it?

**Comment by axboe** [comment]
Pushed a commit - if you want to send the same thing, as you actually fixed it, then please just do that and I'll replace it. But since it's so simple, I think we can just sneak it into -rc4 and get this sorted out.

Just let me know what you prefer. Also happy to add reported-by tags, for which I'd just need the name + email of the folks involved here. As it stands, just the issue here is linked.

https://git.kernel.dk/cgit/linux/commit/?h=io_uring-6.12&id=da9d74efce935042f884c79ba4630ff4d5ca5f77

**Comment by mahkoh** [comment]
Sorry for some reason I missed your earlier message. Let's go with your patch. You can add attribution to

`Julian Orth <ju.orth@gmail.com>`

**Comment by axboe** [comment]
Added that - will send this out to Linus later today. Already ran the usual testing on it, and it looks fine. But I want to write a test case specifically for this just so we avoid hitting it again later.

**Comment by axboe** [comment]
Added the basic test case for this and sent out the pull request as well.

**Comment by axboe** [comment]
Closing this one, thanks everyone!

**Comment by KyunLFA** [comment]
Glad to help along with Julian, Jens. And to think, if I recall correctly I actually hit this issue while patching rc3 with your for-next tree... Could have tried reporting that way back then if I didn't think I was the one doing something amiss with patching and compilation flags.

> That said, thanks a ton for testing -rc kernels!

That does mean the world to me that my obsession with testdriving the bleeding edge actually helped someone somewhat, thank you for making my day instead :smile:

**Comment by axboe** [comment]
Not all heroes wear capes! IMHO testing the -rc kernels is VERY useful, as it'll find issues like this before they hit a released kernel.

The fix is in Linus's tree now, so it'll be in -rc4 as released later today.
