### ISSUE TITLE
Big SQE usage for IO passthrough

### ISSUE THREAD

**Issue by hansenidden18** [axboe/liburing#1271]
Dear Developers,

To note I am running it in `Linux-6.8.0` and `liburing-2.5`. I am trying to use Big SQE to take advantage 128 bytes of the SQE and use the `sqe->cmd` for IO pasthrough. But after I initialize my ring with the `IORING_SETUP_SQE128 | IORING_SETUP_CQE32` and try to print the SQE size and `sqe->cmd` size, the result is still 64 and 0. That makes me not able to use the `sqe->cmd`. Can you help? Thank you in advance!!

```
int iouring_init(unsigned entries, struct io_uring *ring)
{
    struct io_uring_params params = { };

    params.flags = IORING_SETUP_SQE128;
    params.flags |= IORING_SETUP_CQE32;
    int ret = io_uring_queue_init_params(entries, ring, &params);
    if (ret < 0) {
        perror("io_uring_queue_init_params failed");
        return ret;
    }

    if (!(params.flags & IORING_SETUP_SQE128)) {
        fprintf(stderr, "Warning: Big SQE (128 bytes) not being used\n");
    } else {
        printf("Big SQEs (128 bytes) are in use\n");
    }

    return 0;
}
```
my sqe initialization is like this
```
int iouring_enqueue(struct io_uring *ring, int fd,
                ComputeCmd *cmd) {
    struct io_uring_sqe *sqe = io_uring_get_sqe(ring);
    if (!sqe) {
        fprintf(stderr, "io_uring_get_sqe failed\n");
        return -1;
    }
    printf("SQE Size: %zu\n", sizeof(struct io_uring_sqe));

    sqe->opcode = IORING_OP_URING_CMD;
    sqe->fd = fd;
    sqe->cmd_op = NVME_URING_CMD_IO;

    printf("SQE Size: %lu\n", sizeof(*sqe));
    memcpy(sqe->cmd, cmd, sizeof(ComputeCmd));

    printf("SQE cmd field size: %zu\n", sizeof(sqe->cmd));
    sqe->user_data = 1;
    return 0;
}
```
And the output will be

<img width="259" alt="image" src="https://github.com/user-attachments/assets/75215f84-8db5-4095-9e5d-664cb4b76934">

And here I tried it for read-write as well with the `sqe->cmd` same with the test inside the repo.

```
int iouring_enqueue(struct io_uring *ring, int fd,
        ComputeCmd *cmd, int is_write) {
    struct nvme_uring_cmd *sqe_cmd;
    struct io_uring_sqe *sqe = io_uring_get_sqe(ring);
    if (!sqe) {
        fprintf(stderr, "io_uring_get_sqe failed\n");
    return -1;
    }
    printf("SQE Size: %zu\n", sizeof(struct io_uring_sqe));
    printf("Uring CMD Size: %zu\n", sizeof(struct nvme_uring_cmd));
    sqe->opcode = IORING_OP_URING_CMD;
    sqe->fd = fd;
    sqe->cmd_op = NVME_URING_CMD_IO;

    printf("SQE Size: %lu\n", sizeof(*sqe));
    sqe_cmd = (struct nvme_uring_cmd *)sqe->cmd;
    memset(sqe_cmd, 0, sizeof(struct nvme_uring_cmd));

    sqe_cmd->opcode = cmd->opcode;
    sqe_cmd->nsid = 1;
    sqe_cmd->cdw10 = cmd->slba & 0xffffffff;
    sqe_cmd->cdw11 = cmd->slba >> 32;
    sqe_cmd->cdw12 = cmd->nlb;
    sqe_cmd->addr = cmd->addr;
    sqe_cmd->data_len = cmd->data_len;

    printf("SQE cmd field size: %zu\n", sizeof(sqe->cmd));
    sqe->user_data = (__u64)(uintptr_t)cmd;
    return 0;
}
```
the result is
<img width="323" alt="image" src="https://github.com/user-attachments/assets/3b6b641c-c00f-4deb-9608-97b6980818b6">

**Comment by hansenidden18** [comment]
Thank you for the kind response. 
I have a follow up questions. When I use io_uring, which is asynchronous, and compare it with ioctl, the result does not differ so much. Is it because I only call 1 ioctl and compare it with 1 iouring passthru?

**Comment by hansenidden18** [comment]
But in one of the slide in [linux plumber](https://lpc.events/event/11/contributions/989/attachments/747/1723/lpc-2021-building-a-fast-passthru.pdf) it shows that a single job can outperform the ioctl itself. I tested it with 1 - 128 QD but the results I got was not as good as the presentation, do you know why?
Thank you.

<img width="1034" alt="image" src="https://github.com/user-attachments/assets/3bc6a848-27b7-44fa-9bc1-c84faeb84c35">

**Comment by axboe** [comment]
I'm not saying you need multiple jobs, I'm saying you need parallelism to get higher performance. If you do io_uring passthrough and use registered buffers, then even a single pending IO should be faster than the ioctl approach. Or if you have more pending, that would do it too, as there's no way to do that with the ioctl. And obviously a combination of both would be even better.

I can't say why your test doesn't perform, you're most likely missing one (or both) of those points.
