### ISSUE TITLE
multiprocess and kernel space question

### ISSUE THREAD

**Issue by NathanFreeman** [axboe/liburing#1278]
Hello, I want to use `IORING_OP_FUTEX_WAKE` and `IORING_OP_FUTEX_WAIT` to implement a multiprocess mutex. One question I have is whether the kernel allocates a separate kernel space for each process when multiple processes simultaneously instantiate `io_uring_queue_init`, or do all processes share a single kernel space where all `io_uring` requests are handled?

**Comment by axboe** [comment]
Each ring is using its own memory, there's nothing shared across rings. But for futex operations, that should not matter, all that matters is that the futex itself is located in memory that both can access.

**Comment by NathanFreeman** [comment]
Thank you
