### ISSUE TITLE
The role of IORING_ACCEPT_DONTWAIT

### ISSUE THREAD

**Issue by AomaYple** [axboe/liburing#1286]
What does the wiki mean by “allowing applications to issue a non-retryable accept attempt”

**Comment by axboe** [comment]
By default, if there's nothing to accept, it'll arm poll and wait for a connection request. Setting DONTWAIT will instead return -EAGAIN and complete the request.

**Comment by AomaYple** [comment]
> By default, if there's nothing to accept, it'll arm poll and wait for a connection request. Setting DONTWAIT will instead return -EAGAIN and complete the request.

Thank you!
