### ISSUE TITLE
Inaccurate man pages for io_uring_register_sync_cancel

### ISSUE THREAD

**Issue by AomaYple** [axboe/liburing#1287]
Here's the description from the man pages
![image](https://github.com/user-attachments/assets/6a8c81c4-6ebd-47a0-b440-1975e155bbf9)

Here's the actual description
![image](https://github.com/user-attachments/assets/7ddb0249-e405-44b6-9e5e-3b82063ea061)

The man pages don't describe the opcode member and the pad2 member, as well as the type of the wrong pad member

**Comment by axboe** [comment]
Want to send a patch/pr?

**Comment by AomaYple** [comment]
> Want to send a patch/pr?

Before that I have another question, in my testing I found that the opcode member can run without setting it, so what is the purpose of this opcode member

**Comment by axboe** [comment]
You'll have to be more specific, use pseudo code and explain where behavior differs from your expectations.

**Comment by AomaYple** [comment]
For example, when I call io_uring_register_sync_cancel, I now declare an io_uring_sync_cancel_reg variable on the stack and clear it to zero, then set the addr member and the flags member, and then initiate the request.

I know that the fd member and timeout member can be set and the pad and pad2 members must be cleared to zero.

So what is the role of the opcode member, according to io_uring_prep_cancel64, the opcode member should be set to IORING_OP_ASYNC_CANCEL, but I can successfully complete io_uring_register_sync_cancel without setting the opcode member

**Comment by axboe** [comment]
You're mixing up the opcode of the actual request, and the opcode for cancelation. The opcode in this struct is for when you use ```IORING_ASYNC_CANCEL_OP```, where you can match on specific opcodes.

**Comment by axboe** [comment]
Closing this one, re-open if there are further questions.
