### ISSUE TITLE
Few queries about liburing

### ISSUE THREAD

**Issue by anandv1223** [axboe/liburing#1288]
We have recently started evaluating io_uring for faster io with our app.
In this context, I had a few newbie queries :

1) Has anyone in this community successfully used liburing for io with tuntap interfaces?
    (single queue or multiqueue)  
2) We currently use linux kernel version 5.15 for our product. Is this a stable/recommended version if we want to integrate liburing 
    functionality into our app? If no, is there a specific kernel version you would recommend for upgrade?
    I have reviewed the discussions on this forum. The recommended version seems to be 6.x. Is 5.15 a no-go for production use
   of liburing or is it just that it might miss out on some performance enhancements but basic liburing functionality should
   be available and reliable even in 5.15? Incase upgrade is not an option, is it possible to identify and patch relevant fixes
   into our kernel version. I am not sure if its possible but just want to confirm with experts here.

**Comment by axboe** [comment]
It's not that 5.15 is a no-go, you're just going to be missing out on some efficiency improvements and speedups compared to newer kernels. For tun/tap in particular, the older kernels do not support proper efficient nonblocking issue. This isn't an io_uring issue, it's a deficiency in the tap driver itself. See:

https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=f758bfec377ad2f15d7683473b1db1cfbf8e1bb0

**Comment by anandv1223** [comment]
Thanks for the clarification @axboe .
For the tun/tap issue you referred to in 5.15, how does that manifest? Will it be that the performance benefits due to use of io_uring would get negated?
I had 1 other query, usually for tun/tap devices, read/write/readv/writev would process exactly 1 packet/frame at a time (not more). I am not very sure if its a syscall limitation or the tun/tap device. If this is indeed the case, would it really be able to utilize the batching advantage that io_uring provides?

**Comment by axboe** [comment]
You'll see worse performance and less efficiency on tun/tap using an older kernel. I'd strongly recommend updating to a stable kernel later than 5.15, there's just no reason to stick with something ancient (in general, too).

For the other question, an ideal use case here would be using multi-shot read. Then whenever something is available, it'll automatically get read and post a completion.

Closing this one, feel free to re-open if there are further questions. Though I would recommend using discussions for things like this, as it's not an issue or bug, it's just questions on how things work.
