### ISSUE TITLE
What is the default clock source for io_uring_prep_timeout

### ISSUE THREAD

**Issue by AomaYple** [axboe/liburing#1308]

**Comment by axboe** [comment]
It's literally in the man page, if you don't set ```IORING_TIMEOUT_ABS``` then a relative clock is used.

**Comment by AomaYple** [comment]
> It's literally in the man page, if you don't set `IORING_TIMEOUT_ABS` then a relative clock is used.

So it's MONOTONIC by default?

**Comment by AomaYple** [comment]
> It's literally in the man page, if you don't set `IORING_TIMEOUT_ABS` then a relative clock is used.

So the default is `MONOTONIC`?

**Comment by axboe** [comment]
Right, monotonic and relative.
