### ISSUE TITLE
Potential kernel thread persistence issue in io_uring with IORING_SETUP_SQPOLL when queue depth exceeds 32

### ISSUE THREAD

**Issue by suxinggm** [axboe/liburing#1310]
# Description
When using io_uring with the following setup parameters:

IORING_SETUP_SQPOLL
IORING_SETUP_CQE32
IORING_SETUP_SQE128
The program creates and destroys an io_uring queue in a loop. If queue_depth > 32, each loop iteration leaves a kernel thread persistently running after the queue is deleted. However, this issue does not occur when queue_depth <= 32.

The test program demonstrates this behavior. It initializes an io_uring instance, deletes it after 5 seconds, and repeats this process 100 times.

# Test Program
```
#include <liburing.h>
#include <iostream>
#include <thread>
#include <chrono>

void sleep_for_seconds(int seconds) {
    std::this_thread::sleep_for(std::chrono::seconds(seconds));
}


int main() {
    const int queue_depth = 33; // Change to 32 or below to avoid issue
    const int loop_count = 100;

    for (int i = 0; i < loop_count; ++i) {
        std::cout << "Iteration: " << i + 1 << std::endl;

        // Initialize io_uring parameters
        struct io_uring_params params = {};
        params.flags = IORING_SETUP_SQPOLL | IORING_SETUP_CQE32 | IORING_SETUP_SQE128;

        // Create io_uring queue
        struct io_uring ring;
        int ret = io_uring_queue_init_params(queue_depth, &ring, &params);
        if (ret < 0) {
            std::cerr << "Failed to initialize io_uring, error: " << ret << std::endl;
            return 1;
        }

        std::cout << "io_uring queue created." << std::endl;

        // Sleep for 5 seconds
        sleep_for_seconds(5);

        // Delete io_uring queue
        io_uring_queue_exit(&ring);
        std::cout << "io_uring queue deleted." << std::endl;

        // Sleep for another 5 seconds
        sleep_for_seconds(5);
    }

    std::cout << "Completed 100 iterations." << std::endl;
    return 0;
}
```

# Observations
With queue_depth <= 32:

Kernel threads created by IORING_SETUP_SQPOLL terminate correctly after io_uring_queue_exit.
With queue_depth > 32:

Kernel threads persist after io_uring_queue_exit.
Over 100 iterations, this results in 100 persistent threads, which can be observed with tools like htop or ps.

# Steps to reproduce:
1. Compile and run the above program.
2. Run `pstree -p | grep main` to see the "main" process
3. change queue_depth to 32 and 33 to find the difference.

# OS Version
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=24.04
DISTRIB_CODENAME=noble
DISTRIB_DESCRIPTION="Ubuntu 24.04 LTS"
Kernel: 6.8.0-31-generic

**Comment by axboe** [comment]
Funky, I'll take a look.

**Comment by axboe** [comment]
Looks like a liburing bug, can you try current -git?

**Comment by axboe** [comment]
Fix by above referenced commit.
