### ISSUE TITLE
Does signalfd now work with poll?

### ISSUE THREAD

**Issue by raphaelcohn** [axboe/liburing#133]
At one time, signalfd didn't work with poll completions. I'd really like to use it so I can batch process signal handling in thread loops.

Does it now work with read and read fixed completions, too?

**Comment by CarterLi** [comment]
See https://github.com/axboe/liburing/issues/5

**Comment by raphaelcohn** [comment]
So that's... no, then?

**Comment by raphaelcohn** [comment]
Closing as gone stale.
