### ISSUE TITLE
can open() with flag O_CREAT also provide non-blocking operation

### ISSUE THREAD

**Issue by openalmeida** [axboe/liburing#134]
is the linux systemd call `open` (and libc's `open()`, and Python's builtin `open()`) absolutly non-blocking operation ? thus the io_uring seems not provide a new system call to instead the exists system call `open`, but when system call `open` has flag O_CREAT specialized may case file systemd change which spend a lot of time and i think this "equal to blocking IO".

i just writing Python toys which known almost nothing about Linux kernel, sorry for this fool issue.

**Comment by CarterLi** [comment]
`open(2)` may block too

We have [io_uring_prep_openat](https://github.com/axboe/liburing/blob/master/src/include/liburing.h#L339)

**Comment by openalmeida** [comment]
> `open(2)` may block too
> 
> We have [io_uring_prep_openat](https://github.com/axboe/liburing/blob/master/src/include/liburing.h#L339)

Wow, that it. Thanks a lot.

**Comment by axboe** [comment]
As Carter says, OPENAT or OPENAT2 with io_uring will not block for any open type operation. I'm going to close this one as resolved.

**Comment by openalmeida** [comment]
> As Carter says, OPENAT or OPENAT2 with io_uring will not block for any open type operation. I'm going to close this one as resolved.

thanks, and will liburing/examples/* change logic from `open` to `io_uring_prep_openat` as sort of liburing officiall standard ? thus i am asking here beacuse of some other articles which introduce liburing's awesome features used `open` for open type opeartion as liburing/examples/* do so, but which confused me, maybe others will too.

**Comment by axboe** [comment]
Those examples pre-date the support for file open. But yes, they could all use the OPENAT support, it provides the same functionality just in an async manner.

**Comment by openalmeida** [comment]
Beg your pardon. Would you meaning `glibc.open` is bad (or wrong) for async, but `glibc.open` in liburing/exampes/* only act as demos which will not replaced ? in fact, as a newbie (both the kernel layer programming and the clang) i have no idea how to write io_uring_prep_openat based open type operation and ready to steal from these demos : {

**Comment by openalmeida** [comment]
> Those examples pre-date the support for file open. But yes, they could all use the OPENAT support, it provides the same functionality just in an async manner.

Beg your pardon. Would you meaning `glibc.open` is bad (or wrong) for async, but `glibc.open` in liburing/exampes/* only act as demos which will not replaced ? in fact, as a newbie (both the kernel layer programming and the clang) i have no idea how to write io_uring_prep_openat based open type operation and ready to steal from these demos : {

**Comment by axboe** [comment]
The end result of both is the same, they carry out the same operation. The only difference is that if you use io_uring_prep_openat() and do the open that way, then it happens in an async manner. If you use the normal open(2) system call, then that operation may block.

There's an example in test/open-close.c that shows how to open at file with io_uring:

https://git.kernel.dk/cgit/liburing/tree/test/open-close.c#n65

**Comment by openalmeida** [comment]
thanks again and sorry for spending of your time.

hope someone looking for totally async io solution like me may get whatever a bit help when reach this ticket.
