### ISSUE TITLE
read a file smaller than expected

### ISSUE THREAD

**Issue by deafwolf** [axboe/liburing#135]
I have add a line  above io_uring_cqe_seen in io_uring-test.c
fprintf(stdout, "res=%d, data=%s\n", cqe->res, (char *)iovecs[i].iov_base);

1. create file1 with a * 4096 + b * 4096 + c * 4096 + d * 4096
then run the test with file1, the output is
res=4096, data=aa.....
res=4096, data=bb.....
res=4096, data=cc.....
res=4096, data=dd....

2. create file2 with a * 4096 + b * 4096 + c * 4096
remove the check of cqe->res != 4096, run the test with file2, the output is
res=0, data=
res=4096, data=bb.....
res=4096, data=cc......
res=4096, data=

3. change the print code to
fprintf(stdout, "res=%d, data=%s\n", cqe->res, (char *)iovecs[QD - i -1].iov_base);
run the test with file2, the output is
res=0, data=
res=4096, data=cc.....
res=4096, data=bb.....
res=4096, data=aa.....

I think 1st and 3rd test work fine.
Is the 2nd output expected?

**Comment by axboe** [comment]
This is expected, as the completions are out of order. The ones that actually read data will complete once the data has been read, the one that is end-of-file will complete directly inline. If you set ->user_data to match up issues with completions that should also show which completion is what.
