### ISSUE TITLE
libaio-wrapper ?

### ISSUE THREAD

**Issue by Gatak** [axboe/liburing#141]
Hello, I saw these branches/commits regarding a libaio-wrapper:
https://github.com/axboe/liburing/tree/libaio-wrapper
https://git.kernel.dk/cgit/liburing/commit/?h=libaio-wrapper&id=fd728d61e5535f82cab93e4581e008dc8b034efc

Is it planned that liburing can be a drop-in replacement for libaio? It would be wonderful, since it would mean we can get some of the benefit from io_uring without patching all existing/current apps.

Another option that could be considered is to make it possible to use LDPRELOAD=liburing to replace aio, similar to how we use LDPRELOAD=jemalloc and such to replace the default malloc.

**Comment by axboe** [comment]
That was more of a thought experiment than anything else. To make it work 100% with all applications, io_uring would need to mimic the libaio user mapped completion ring as well. This requires kernel changes. While not impossible to do, it would also mean that it'd add extra complexity to the fast path of io_uring. At the end, I decided against this for multiple reasons, the former being one of them.

**Comment by Gatak** [comment]
Right, I understand. Thanks for the explanation. I do hope that a lot will see the benefits of io_uring. Samba implemented support and the performance is great!
