### ISSUE TITLE
Regression v5.7: Read from non-blocking eventfd via io_uring repeatedly returns EAGAIN

### ISSUE THREAD

**Issue by tkp1n** [axboe/liburing#143]
As reported (including repro) here: https://bugzilla.kernel.org/show_bug.cgi?id=208039

Additionally specifying EFD_NONBLOCK in the line below, lets the test in this repo fail as well...
https://github.com/axboe/liburing/blob/929fedfcb25df9f2dba553c4df7ec2950ac62fc4/test/eventfd.c#L43

**Comment by axboe** [comment]
Thanks for reporting, I'll take a look at this.

**Comment by YoSTEALTH** [comment]
Could this be effecting `io_uring_prep_recv` and others as well? I been wondering why i been getting `EAGAIN` as well.

**Comment by axboe** [comment]
This should fix it:

https://git.kernel.org/pub/scm/linux/kernel/git/viro/vfs.git/patch/?id=12aceb89b0bce19eb89735f9de7a9983e4f0adae

I'll get that shoved into -stable when it lands in mainline.

**Comment by tkp1n** [comment]
> Could this be effecting `io_uring_prep_recv` and others as well? I been wondering why i been getting `EAGAIN` as well.

@YoSTEALTH yes, this is effecting all read operations via `io_uring` (read, read_fixed, readv and recv).

> This should fix it:
> I'll get that shoved into -stable when it lands in mainline.

@axboe Thank you for the swift reply. Looking forward to that patch in a 5.7 stable release.

**Comment by YoSTEALTH** [comment]
@tkp1n Thanks for the bug report, this one has been wasting a lot of my time wondering whats going on!!!

**Comment by YoSTEALTH** [comment]
@axboe I don't see these changes in stable ``5.7.1`` or ``5.6.17`` that was just released, will it be in the next stable release?

**Comment by axboe** [comment]
It's going through Al's tree and hasn't made it to Linus's tree yet. Should happen before 5.8-rc1. Once it's upstream, I'll point stable at it, but I can't do that before it's upstream.

**Comment by YoSTEALTH** [comment]
@tkp1n have you checked for writing as well? I am getting ``EGAIN`` for that as well, not sure if @axboe patch accounts for it.

**Comment by YoSTEALTH** [comment]
@tkp1n I tested in ``linux 5.8-rc1`` this issue seems to be resolved!

**Comment by axboe** [comment]
Closing, next 5.7-stable will be fine too.
