### ISSUE TITLE
API compatibility

### ISSUE THREAD

**Issue by rch0wdhury** [axboe/liburing#144]
Hi Jens,
My application dynamically links with liburing.so . I have tested my application with version 0.5 and 0.6 . Going by the old commits I see before 0.3 there have been some changes to the API but after that it has remained same. What are your thoughts about future API changes and ways to make it backward compatible ? Is it possible to bump up a specific version number or maybe denote a specific version as LTS?

**Comment by axboe** [comment]
There are no plans to make incompatible changes, that's always been the case. Obviously that's a bit more up in the air for the really early versions, but in general you should consider it stable now.
