### ISSUE TITLE
Can I create a ring per socket?

### ISSUE THREAD

**Issue by ghost** [axboe/liburing#145]
Can I create a ring per socket and multiplex the rings with epoll?

**Comment by MarkReedZ** [comment]
What are you trying to do?  I created an event loop using io_uring and am considering adding support for multiple rings, but am not sure of the use cases. 

https://github.com/MarkReedZ/mrloop

**Comment by ona993** [comment]
@MarkReedZ 
You need to specify the queue size when you create the ring. In your code you use 128.
My idea was to create a small ring per socket with queue size 2 (one receive / one send) to avoid having to specifing a limit for the whole application.

**Comment by MarkReedZ** [comment]
Ah yes I see exactly what you mean.  I'll play around a bit.

**Comment by MarkReedZ** [comment]
For sure axboe has tests with large numbers of connections and large numbers of rings created.  I don't know offhand where the io_uring tests are, but will look another time.
