### ISSUE TITLE
IORING_OP_ASYNC_CANCEL and serializing operations

### ISSUE THREAD

**Issue by withoutboats** [axboe/liburing#147]
Hey :)

I want to guarantee users of my library that certain events they schedule on a ring will be serialized with respect to one another. Specifically, these are types like `File` and `TcpStream` that are supposed to provide a misuse-resistant API for performing IO on a specific file or tcp socket. Each IO handle like this only supports a single operation being performed at a time. In general, Rust's type system makes it easy to ensure that these operations are serialized.

The problem has to do with cancellation. In Rust's async IO model, its very simple to cancel interest in an IO event. However, if users cancel interest in an event, I want to make sure that subsequent events scheduled on the handle will occur after that event has either completed or been cancelled.

The nightmare scenario is this: a user schedules a write event, then cancels interest in that write and schedules a close. Concurrently, another part of their program schedules an openat event. If the close isn't serialized after the write (or a cancel of the write), the worst case scenario is that these events are processed in the oder close -> openat -> write, and the openat reuses the file descriptor for the new file, resulting in the write succeeding on a totally different file.

My attempt to solve this is that if users cancel interest an event without completing it, the next event they schedule is hard linked after an IORING_OP_ASYNC_CANCEL on the event they cancelled interest in. We don't care if the cancel succeeds or not, just that it either succeeds or fails (failure meaning the event completed) before the next operation occurs.

So I am writing to confirm: is this sufficient to guarantee that the subsequent event will serialize after the event being cancelled? Is it possible that an event will become uncancellable (causing the cancel to error), but still not be processed until after subsequent events linked after the cancel using the same fd?

**Comment by isilence** [comment]
> The nightmare scenario is this: a user schedules a write event, then cancels interest in that write and schedules a close. Concurrently, another part of their program schedules an openat event. If the close isn't serialized after the write (or a cancel of the write), the worst case scenario is that these events are processed in the oder close -> openat -> write, and the openat reuses the file descriptor for the new file, resulting in the write succeeding on a totally different file.

If it's not SQPOLL, it won't ever happen. Request grab a file reference on submission, like temporal dup() which will be put on a request completion.

**Comment by isilence** [comment]
> So I am writing to confirm: is this sufficient to guarantee that the subsequent event will serialize after the event being cancelled? Is it possible that an event will become uncancellable (causing the cancel to error), but still not be processed until after subsequent events linked after the cancel using the same fd?

There may be cases where it just can't cancel inflight request. So a cancellation request may be outlived by the request it targets. But you will get an appropriate return code.
