### ISSUE TITLE
`const` correctness in `io_uring_prep_connect`

### ISSUE THREAD

**Issue by KayEss** [axboe/liburing#151]
At least one of the APIs differs in its handling of `const`, that is `io_uring_prep_connect`. The underlying API takes the `sockaddr` as `const`, but the io_uring API takes it mutably.

* io_uring API: https://github.com/axboe/liburing/blob/master/src/include/liburing.h#L325
* connect API: https://man7.org/linux/man-pages/man2/connect.2.html

I could do a PR for this if it's something that can be fixed. I guess the documentation web site also needs to be updated (where would that fix need to be directed?)

**Comment by axboe** [comment]
Yes, please do send a patch for that. The documentation is in man/io_uring_enter.2

**Comment by KayEss** [comment]
How does the documentation at https://unixism.net/loti/ref-liburing/submission.html get updated, or is that outside the scope of changes here?

**Comment by axboe** [comment]
Outside of the scope. We’ll just let him know, but external documentation is external... Nothing I control or manage.
