### ISSUE TITLE
Cannot allocate memory

### ISSUE THREAD

**Issue by YoSTEALTH** [axboe/liburing#157]
After a while of using Liburing I start getting ``OSError: [Errno 12] Cannot allocate memory`` message, no matter what I do after this point, its sticks to this message. Its as if `io_uring_queue_exit()` does not clean up after itself. I have to restart my system at this point.

**Comment by isilence** [comment]
Looks like memory leak. A few quick questions:

1. What kernel version do you use?
2. What op types you submit (i.e. IORING_OP_*)? E.g. *READV, *READ_FIXED, *READ, *TIMEOUT
3. Do you use fixed files and/or fixed buffers?
4. Are you re-creating io_uring instances dynamically or allocate them at the beginning?
5. Is it mult-threaded?
6. Did you check /proc/slabinfo ?

**Comment by isilence** [comment]
BTW, there is a new patch [[1](https://lore.kernel.org/io-uring/20200710141420.3987063-1-yangyingliang@huawei.com/T/#u)] dealing with memory leaks, can be related.

And it would be even more useful, if you can provide a reproducer or your program that triggered it.

[1] https://lore.kernel.org/io-uring/20200710141420.3987063-1-yangyingliang@huawei.com/T/#u

**Comment by YoSTEALTH** [comment]
>     1. What kernel version do you use?
linux5.8-rc4
> 
>     2. What op types you submit (i.e. IORING_OP_*)? E.g. *READV, *READ_FIXED, *READ, *TIMEOUT
normally happens with `socket` for some reason file io seems to work fine. So `io_uring_prep_recv`, `io_uring_prep_send` with `MSG_DONTWAIT` and `io_uring_prep_poll_add`
>     3. Do you use fixed files and/or fixed buffers?
no, not yet
>     4. Are you re-creating io_uring instances dynamically or allocate them at the beginning?
set at beginning
>     5. Is it mult-threaded?
no
>     6. Did you check /proc/slabinfo ?
no, what should I keep an eye out for?

I am using this in Python

If that patch is going to be in the next rc5 I can test and let you know.

**Comment by isilence** [comment]
Thanks!

> no, what should I keep an eye out for?

I want to see which bucket grows indefinitely. That can make obvious what
kernel structure leaks. E.g. struct io_kiocb, representing a single io_uring's
request, is in "kmalloc-256" or something similar.

You can attach its content here either after getting the error, or, If you can't
get it because of OOM, after running it for some time.

> I am using this in Python  

Doesn't matter
 
> If that patch is going to be in the next rc5 I can test and let you know.

Great, that would be helpful

**Comment by axboe** [comment]
slabtop can be helpful in getting an overview of slabs that are growing out of control.

Where are you getting -ENOMEM? Please be specific. Is it in a cqe, or is it doing io_uring_queue_init()?

**Comment by YoSTEALTH** [comment]
It would happen when `io_uring_prep_init()` would run again.

I will keep looking at `slabtop`, I will have to wait till next time it happens.

Would something like `strace` help?

**Comment by axboe** [comment]
What is io_uring_prep_init()? Please be as specific as you can, we don't necessarily have your source code or what you are running. An strace would certainly help, as it'll show where the error is occuring. Right now I'm just guessing it's io_uring_queue_init() -> io_uring_setup().

**Comment by axboe** [comment]
And even better than that, a reproducer would be very helpful too.

**Comment by YoSTEALTH** [comment]
`io_uring_prep_init(512, ring, 0)`

**Comment by YoSTEALTH** [comment]
I figure I run the test that comes with liburing at this point and this is the result. If I where to restart my system and run this test again, I am sure it would pass!
>
make[1]: Entering directory '.../Liburing/libs/liburing/test'
Running test poll
Running test poll-cancel
Running test ring-leak
Running test fsync
Running test io_uring_setup
io_uring_setup(0, 0x7ffe6ff476a0), flags: none, feat: none, resv: 0x00000000 0x00000000 0x00000000, sq_thread_cpu: 0
io_uring_setup(1, (nil)), flags: none, feat: none, resv: , sq_thread_cpu: 0
io_uring_setup(1, 0x7ffe6ff476a0), flags: none, feat: none, resv: 0x00000001 0x00000001 0x00000001, sq_thread_cpu: 0
io_uring_setup(1, 0x7ffe6ff476a0), flags: 0xffffffff, feat: none, resv: 0x00000000 0x00000000 0x00000000, sq_thread_cpu: 0
io_uring_setup(1, 0x7ffe6ff476a0), flags: IORING_SETUP_SQ_AFF, feat: none, resv: 0x00000000 0x00000000 0x00000000, sq_thread_cpu: 0
io_uring_setup(1, 0x7ffe6ff476a0), flags: IORING_SETUP_SQPOLL|IORING_SETUP_SQ_AFF, feat: none, resv: 0x00000000 0x00000000 0x00000000, sq_thread_cpu: 16
Needs root, not flagging as an error
PASS
Running test io_uring_register
RELIMIT_MEMLOCK: 65536 (65536)
io_uring_register(-1, 0, (nil), 0)
io_uring_register(3, 0, (nil), 0)
io_uring_register(4, 4294967295, (nil), 0)
io_uring_register(4, 0, 0x7fffed6f3fa0, 1)
io_uring_register(4, 0, 0x7fffed6f3fa0, 1)
io_uring_register(4, 0, 0x7fffed6f3fa0, 1)
Unable to map a huge page.  Try increasing /proc/sys/vm/nr_hugepages by at least 1.
Skipping the hugepage test
reserve file-backed buffers
io_uring_register(4, 0, 0x7fffed6f3fa0, 1)
expected 95, got 12
io_uring_register of 131072 bytes failed with ENOMEM (expected).
io_uring_register of 65536 bytes failed with ENOMEM (expected).
successfully registered 32768 bytes (0).
io_uring_register(4, 0, 0x5617154da6c0, 1025)
io_uring_register(4, 0, 0x5617154da6c0, 1024)
expected success, got 12
allocated 17179869180 bytes of address space
io_uring_register(4, IORING_REGISTER_FILES, 0x7f755867e000, 32767)...succeeded
io_uring_register(4, IORING_UNREGISTER_FILES, 0, 0)...succeeded
io_uring_submit:
    opcode: 6
    flags:  0x00000000
    fd:     4
    poll_events: 0x00000005
io_uring_register(4, 2, 0x7fffed6f3f1c, 1)
FAIL
Test io_uring_register failed with ret 1
Running test io_uring_enter
io_uring_queue_init: Cannot allocate memory
Test io_uring_enter failed with ret 1
Running test nop
Running test sq-full
Running test cq-full
Running test 35fa71a030ca-test
Running test 917257daa0fe-test
Running test b19062a56726-test
Running test eeed8b54e0df-test
Running test link
Running test send_recvmsg
queue init failed: -12
Running test a4c0b3decb33-test
Running test 500f9fbadef8-test
Running test timeout
Running test sq-space_left
Running test stdout
This is a pipe test
This is a fixed pipe test
Running test cq-ready
Running test cq-peek-batch
Running test file-register
Running test cq-size
Running test 8a9973408177-test
Running test a0908ae19763-test
Running test 232c93d07b74-test
Running test socket-rw
Running test accept
test_accept_sqpoll: skipped, not root
accept: accept.c:229: test_accept_many: Assertion `io_uring_queue_init(2 * nr, &m_io_uring, 0) >= 0' failed.
timeout: the monitored command dumped core
./runtests.sh: line 58: 82947 Aborted                 timeout --preserve-status -s INT $TIMEOUT ./$T $D
Test accept failed with ret 134
Running test timeout-overflow
Running test defer
ring setup failed
Test defer failed with ret 1
Running test read-write
SQPOLL requires root, skipping
buffer reg failed: -12
test_io failed 0/0/0/1/0/0
Test read-write failed with ret 1
Running test io-cancel
ring create failed: -12
test_io_cancel 1 1 failed
Test io-cancel failed with ret 1
Running test link-timeout
Running test cq-overflow
Running test link_drain
Running test fc2a85cb02ef-test
Test needs failslab/fail_futex/fail_page_alloc enabled, skipped
Running test poll-link
Running test accept-link
Running test fixed-link
Running test poll-cancel-ton
ring setup failed: -12
Test poll-cancel-ton failed with ret 1
Running test teardowns
Running test poll-many
failed ring init
poll-many failed
Test poll-many failed with ret 1
Running test b5837bd5311d-test
Running test accept-test
Running test d77a67ed5f27-test
SQPOLL requires root, skipped
Running test connect
Running test 7ad0e4b2f83c-test
Running test submit-reuse
Running test fallocate
Running test open-close
Running test file-update
Running test accept-reuse
io_uring_init_failed: -12
Test accept-reuse failed with ret 1
Running test poll-v-poll
Running test fadvise
Running test madvise
Suspicious timings (56 > 44)
Running test short-read
Running test openat2
Running test probe
Running test shared-wq
Running test personality
Not root, skipping
Running test eventfd
Running test send_recv
./send_recv: skipping SQPOLL variant
Running test eventfd-ring
Running test across-fork
Running test sq-poll-kthread
sqpoll requires root!
test_sq_poll_kthread_stopped_exit: skipped
sqpoll requires root!
test_sq_poll_kthread_stopped_noexit: skipped
Running test splice
Running test lfs-openat
Running test lfs-openat-write
Running test iopoll
iopoll requires root, skipping
Running test d4ae271dfaae-test
Test requires root, skipping
Running test eventfd-disable
Running test close-opath
Running test ce593a6c480a-test
Running test cq-overflow-peek
OVERFLOW not set on -EBUSY, skipping
Running test statx
Running test sq-full-cpp
Tests  <io_uring_register> <io_uring_enter> <accept> <defer> <read-write> <io-cancel> <poll-cancel-ton> <poll-many> <accept-reuse> failed
make[1]: *** [Makefile:100: runtests] Error 1
make[1]: Leaving directory '.../Liburing/libs/liburing/test'
make: *** [Makefile:20: runtests] Error 2

**Comment by axboe** [comment]
What's your ulimit -l setting for the user you are using?

I discovered a small gap where ring exit + ring init could fail, because we account the memory freed only after the async ring exit work has run. Posted a fix here. Not sure if it's your issue, but it's definitely an issue if you are very tight on your ulimit -l setting and you do back-to-back exit+init of rings.

https://git.kernel.dk/cgit/linux-block/commit/?h=io_uring-5.8&id=309fc03a3284af62eb6082fb60327045a1dabf57

In any case, please try it.

**Comment by YoSTEALTH** [comment]
`ulimit -l` is `64` for the user, I have tried messing with that setting before in the past, I could only change it as `su` and it would reset back.

Yes, I would be working on Liburing for hours and slowly these problems would start here and there and it would gradually get worst.

I would have to wait till next Linux5.8-rc5 to try the patches.

**Comment by axboe** [comment]
For now, just edit /etc/security/limits.conf and add this line at the end:

```
*                -                memlock                -
```

and you should be fine.

**Comment by YoSTEALTH** [comment]
Ok, done, thanks.

**Comment by axboe** [comment]
The fix is upstream now, so it'll be in -rc5. Please do retry with -rc5 once released, or just use current linus -git.

**Comment by YoSTEALTH** [comment]
I am not getting that error anymore on rc5, loos like that patch did the job, nicely done.. @axboe

**Comment by axboe** [comment]
Great, it was just down to timing then, no leak.Thanks for re-testing!

**Comment by aep** [comment]
any workaround for older kernels? 
since ubuntu is the most popular linux thing, this will take a while until uring is usable :/

**Comment by axboe** [comment]
The patch is going into 5.7-stable (it's already been added, so will be in the next release). Earlier kernels are not affected.

**Comment by aep** [comment]
ah nice. i'm on 5.7.8 and affected. so this version is unpopular enough to ignore the problem?

**Comment by axboe** [comment]
The distros will track -stable, so once 5.7.9 is out it should propagate to the distros pretty quickly. As a work-around until that happens, just increase the memlocked limit as mentioned above.

**Comment by axboe** [comment]
https://lwn.net/Articles/826290/

5.7.9 is out, was released an hour ago.
