### ISSUE TITLE
How to know how many bytes got written/read by io_uring_prep_writev and io_uring_prep_readv?

### ISSUE THREAD

**Issue by expnkx** [axboe/liburing#159]
Thank you so much!!!

**Comment by YoSTEALTH** [comment]
`cqe->res` lets you know, `if cqe->res >= 0` is how much bytes got read/written `if cqe->res < 0` its an error.

Here are some resources to look into:
- https://github.com/axboe/liburing/tree/master/examples
- https://github.com/axboe/liburing/tree/master/test
- https://unixism.net/loti/
- https://developpaper.com/?s=io_uring
...
