### ISSUE TITLE
__io_uring_get_cqe

### ISSUE THREAD

**Issue by YoSTEALTH** [axboe/liburing#160]
Seems like any function that is using `__io_uring_get_cqe` and using the `wait_nr` doesn't not return proper `cqes` ?

``` python
import os
import liburing


def test_weirdness(tmpdir):
    fd = os.open(os.path.join(tmpdir, '1.txt'), os.O_RDWR | os.O_CREAT, 0o660)

    ring = liburing.io_uring()
    cqes = liburing.io_uring_cqes(2)

    # prepare for writing two separate writes and reads.
    one = bytearray(b'abc')
    two = bytearray(b'hello')
    vec_one = liburing.iovec(one)
    vec_two = liburing.iovec(two)

    try:
        # initialization
        assert liburing.io_uring_queue_init(2, ring, 0) == 0

        # write "abc"
        sqe = liburing.io_uring_get_sqe(ring)
        liburing.io_uring_prep_writev(sqe, fd, vec_one, len(vec_one), 0)

        # write "hello"
        sqe = liburing.io_uring_get_sqe(ring)
        liburing.io_uring_prep_writev(sqe, fd, vec_two, len(vec_two), 3)

        # submit both writes
        assert liburing.io_uring_submit(ring) == 2

        fail(ring, cqes)

        # * or *

        # success(ring, cqes)

        liburing.io_uring_cq_advance(ring, 2)

    finally:
        os.close(fd)
        liburing.io_uring_queue_exit(ring)


def fail(ring, cqes):
    # wait for ``2`` entry to complete
    assert liburing.io_uring_wait_cqe_nr(ring, cqes, 2) == 0
    print('cqe-0:', cqes[0].res)

    # ERROR HERE >>>>
    print('cqe-1:', cqes[1].res)
    # Fatal Python error: Segmentation fault


def success(ring, cqes):
    # Just added this to show how it should have worked.
    while True:
        # wait for ``2`` entry to complete
        received = liburing.io_uring_peek_batch_cqe(ring, cqes, 2)
        if received == 2:
            break

    print('cqe-0:', cqes[0].res)
    # output: cqe-0: 3
    print('cqe-1:', cqes[1].res)
    # output: cqe-1: 5
```

**Comment by isilence** [comment]
That's yours library, isn't it? Check the following

1. Even with `io_uring_wait_cqe_nr()`, you have to call io_uring_cq_advance after getting each CQE.
At least that's how it works in C liburing. `io_uring_cq_advance(nr>1)` should be used with `io_uring_for_each_cqe()`

2. Not sure, I'm looking at the right code, but I don't understand how this supposed to work.
```py
# liburing/helper.py
def io_uring_cqes():
    return ffi.new('struct io_uring_cqe **')

# your code
cqes = liburing.io_uring_cqes(2)
liburing.io_uring_peek_batch_cqe(ring, cqes, 2)
```

**Comment by YoSTEALTH** [comment]
Its a CFFI wrapper so Python can use Liburing. Also that code is outdated, I am in middle of updating for 0.7.0 release.

It will be:
```python
def io_uring_cqes(no=1):
    '''
        Type
            no:      int
            return:  <cdata>

        Example
            >>> cqes = io_uring_cqes()
            >>> cqes[0]

            >>> cqes = io_uring_cqes(12)
            >>> cqes[0]
            ...
            >>> cqes[11]
    '''
    return ffi.new('struct io_uring_cqe *[]', no)
```
```python
cqes = liburing.io_uring_cqes(2)
```
Is equal to:
``` C
struct io_uring_cqe *cqes[2];
```

As far as I know "wait_nr: number of completions to wait for." regardless of when `io_uring_cq_advance` was called. `io_uring_wait_cqe_nr(wait_nr=2)` should have return ``2`` entries. Same would apply for `io_uring_wait_cqes` as well.

**Comment by isilence** [comment]
1. `io_uring_wait_cqe_nr()` returns only the first CQE, not an array of them
2. it waits for them to be present in CQ, the other thing is getting them from the queue.
And the library API requires pairing {wait,peek}_cqe() with *cqe_seen(). E.g.

```C
for (int i = 0; i < n; ++i) {
    io_uring_wait_cqe(&cqe_ptr);
    do_something_with(cqe_ptr)
    io_uring_cqe_seen(cqe_ptr);
}
```

**Comment by isilence** [comment]
Think of `io_uring_wait_cqe_nr()` as a way todo less syscalls.
And if you need to look through without `io_uring_cqe_seen()`,
there is `io_uring_for_each_cqe()` macro.

**Comment by YoSTEALTH** [comment]
O i c, now that you have explained how it actually works internally... it makes sense.

I knew how `io_uring_wait_cqe` works, but `io_uring_wait_cqe_nr`, `io_uring_wait_cqes` was confusing. Having to call these function multiple times just to get access to already ready `cqe` still seems weird to me...

I fixed up the file test based on your input https://github.com/YoSTEALTH/Liburing/blob/master/test/file_test.py#L20

thanks @isilence for clarifying.

**Comment by axboe** [comment]
Please remember to close issues.

**Comment by isilence** [comment]
@YoSTEALTH, yes, may be a bit confusing, but makes sense
from for a C library. CQEs are already sequentially in CQ, no
need to copy pointers.

You can add a C function to your project that would fill a
CQE array using io_uring_for_each_cqe() to have such an interface.

**Comment by YoSTEALTH** [comment]
@isilence Yeah! something  like `io_uring_wait_cqes_batch` would be really cool. Its a mix between `io_uring_peek_batch_cqe` and `io_uring_wait_cqe`

``` python
max_wait_nr = 10  # it should wait to fill at least ``1``, and maximum of ``10`` cqe entries.

result = io_uring_wait_cqes_batch(ring, cqes, max_wait_nr)  # `result` type: unsigned int
for i in range(result):
    cqe = cqes[i]
    # do something with `cqe`
    io_uring_cqe_seen(ring, cqe)
```
Unfortunately my C skill is very limited to write something like this comfortably atm.
