### ISSUE TITLE
Unable to successfully run make-debs.sh Ubuntu 18.04

### ISSUE THREAD

**Issue by mmccor26** [axboe/liburing#166]
When running `sudo ./make-deb.sh` this error occurs 

**Now signing changes and any dsc files...
 signfile dsc liburing_0.7-1.dsc root <root@user>
gpg: WARNING: unsafe ownership on homedir '/home/user/.gnupg'
gpg: WARNING: unsafe ownership on homedir '/home/user/.gnupg'
gpg: skipped "root <root@user>": No secret key
gpg: /tmp/debsign.kuGZO17o/liburing_0.7-1.dsc: clear-sign failed: No secret key
debsign: gpg error occurred!  Aborting....
debuild: fatal error at line 1081:
running debsign failed**

But within /tmp/release/Ubuntu/liburing the following is created: 
liburing-0.7, liburing_0.7-1.debian.tar.xz, liburing1_0.7-1_amd64.deb
liburing_0.7-1_amd64.build, liburing_0.7-1.dsc, liburing1-dbgsym_0.7-1_amd64.ddeb
liburing_0.7-1_amd64.buildinfo, liburing_0.7.orig.tar.gz, liburing1-udeb_0.7-1_amd64.udeb, liburing_0.7-1_amd64.changes, liburing-0.7.tar.gz           liburing-dev_0.7-1_amd64.deb

**Comment by axboe** [comment]
This is really beyond what I can provide support on, probably up to you to try and make that work. CC'ing @metze-samba who most recently touched these bits.

**Comment by mmccor26** [comment]
Thanks for the quick response!

**Comment by metze-samba** [comment]
It works for me using
$> cat ~/.devscripts
DEBUILD_DPKG_BUILDPACKAGE_OPTS="--no-sign"

You can also use /etc/devscripts.conf

Otherwise you can edit make-deb.sh and change the last line
to 'debuild --no-sign'.

See also https://github.com/axboe/liburing/pull/167 for debian/ubuntu related fixes
