### ISSUE TITLE
I meet error "Bad file descriptor", when I use "IORING_SETUP_SQPOLL" and get cqes.

### ISSUE THREAD

**Issue by vampire321** [axboe/liburing#168]
My kernel is linux 5.4.0-42-lowlatency, and the cpu is a two socket xeon platinum.
I did register the fds,  and I can watch the kernel thread running on normally.
Did any one met this problem?

**Comment by vampire321** [comment]
Here is my source code(which is modified from the demo on official website) , I met this problem that cqe->res < 0 and the stderror is Bad file descriptor.
(by the way, if I use linux kernel 5.1, 5.2 and 5.3 I got Error about bad device or address)

// gcc -Wall -D_GNU_SOURCE test.c -o test -luring
#include <stdio.h>
#include <unistd.h>
#include <stdlib.h>
#include <fcntl.h>
#include <liburing.h>
#include <string.h>

#define BUF_SIZE    4096
#define FILE_NAME1  "/mnt/nvme_ssd/test.file"

#define LEN 20
int fds[2];

void print_sq_poll_kernel_thread_status() {

    if (system("ps --ppid 2 | grep io_uring-sq" ) == 0)
        printf("Kernel thread io_uring-sq found running...\n");
    else
        printf("Kernel thread io_uring-sq is not running.\n");
}

int start_sq_polling_ops(struct io_uring *ring) {
    void * buf;
    struct iovec *iovecs = calloc(2, sizeof(struct iovec));
	for (int i = 0; i < 2; i++) {
		if (posix_memalign(&buf, BUF_SIZE, BUF_SIZE)) // 4K
			return 1;
		iovecs[i].iov_base = buf;
		iovecs[i].iov_len = BUF_SIZE;
		memset(iovecs[i].iov_base, 0, BUF_SIZE);
	}

    struct io_uring_sqe *sqe;
    struct io_uring_cqe *cqe;

    int fd= open(FILE_NAME1,  O_RDONLY | O_DIRECT);//, S_IRUSR|S_IWUSR);
    fds[0] = fd;
    if (fds[0] < 0 ) {
        perror("open");
        return 1;
    }
    int ret = io_uring_register_files(ring, fds, 1);
    if(ret) {
        fprintf(stderr, "Error registering buffers: %s", strerror(-ret));
        return 1;
    }

    sqe = io_uring_get_sqe(ring);
    if (!sqe) {
        fprintf(stderr, "Could not get SQE.\n");
        return 1;
    }

    io_uring_prep_readv(sqe, fd, &iovecs[0], BUF_SIZE, 0);
    sqe->flags |= IOSQE_FIXED_FILE;

    sqe = io_uring_get_sqe(ring);
    if (!sqe) {
        fprintf(stderr, "Could not get SQE.\n");
        return 1;
    }
    io_uring_prep_readv(sqe, fd,  &iovecs[1], BUF_SIZE, BUF_SIZE);
    printf("fd: %d\n", fds[0]);
    sqe->flags |= IOSQE_FIXED_FILE;
    
    io_uring_submit(ring);

    for(int i = 0; i < 2; i ++) {
        int ret = io_uring_wait_cqe(ring, &cqe);
        if (ret < 0) {
            fprintf(stderr, "Error waiting for completion: %s\n",
                    strerror(-ret));
            return 1;
        }
        /* Now that we have the CQE, let's process the data */
        if (cqe->res < 0) {
            fprintf(stderr, "Error in async operation: %s\n", strerror(-cqe->res));
        }
        printf("Result of the operation: %d\n", cqe->res);
        io_uring_cqe_seen(ring, cqe);
    }
    char buf2[100];
    char obj_file[100];
    snprintf(buf2, sizeof(buf2), "/proc/self/fd/%d", fds[0]);
    readlink(buf2, obj_file, 50);
    printf("fds[0]:%d, path:%s \n", fds[0], obj_file);
    return 0;
}

int main() {
    struct io_uring ring;
    struct io_uring_params params;

    if (geteuid()) {
        fprintf(stderr, "You need root privileges to run this program.\n");
        return 1;
    }
    //print_sq_poll_kernel_thread_status();

    memset(&params, 0, sizeof(params));
    params.flags |= IORING_SETUP_SQPOLL;
    params.sq_thread_idle = 2000;//2000;

    int ret = io_uring_queue_init_params(8, &ring, &params);
    //print_sq_poll_kernel_thread_status();
    if (ret) {
        fprintf(stderr, "Unable to setup io_uring: %s\n", strerror(-ret));
        return 1;
    }
    start_sq_polling_ops(&ring);
    io_uring_queue_exit(&ring);
    close(fds[0]);
    return 0;
}

**Comment by vampire321** [comment]
Here is the output of my code:
fd: 4
Error in async operation: Bad file descriptor
Result of the operation: -9
Error in async operation: Bad file descriptor
Result of the operation: -9
fds[0]:4, path:/mnt/nvme_ssd/test.file

**Comment by tofes** [comment]
I got the same error and took a while to figure out IORING_SETUP_SQPOLL was the cause. Why is this issue closed? Is there any more details to share?

**Comment by axboe** [comment]
Reporter closed it, don't know. But older kernels and SQPOLL require registered files, which is most likely what the reporter figured out.

**Comment by tofes** [comment]
Thank you @axboe, I set the SQPOLL flag and also registered the fd, but got invalid fd consistently. After trying everything I know I removed the SQPOLL and finally no longer getting invalid fd (errno 9). Do you know if SQPOLL flag is working on older kernels like 5.4 or 5.5?

**Comment by axboe** [comment]
Did you also use the registered index for the fd afterwards? And set IOSQE_FIXED_FILE?

**Comment by axboe** [comment]
Flags should be set after calling the prep helper for the command, as the prep helper clear them first.
