### ISSUE TITLE
Support asynchronous-but-blocking socket reads

### ISSUE THREAD

**Issue by paxostv** [axboe/liburing#17]
I have an open socket from which I'm reading data, with the following behavior:

(1) If the socket is blocking, then preparing a read [io_uring_prep_readv] and submitting it [io_uring_submit] causes the submit to block until data can be read from the socket.

(2) If the socket is non-blocking, then doing (1) causes EAGAIN to be returned on the CQE, unless the socket has data available.

(3) If the socket is non-blocking, then polling the socket for input [io_uring_prep_poll_add + POLLIN], flagging it with IOSQE_IO_LINK, followed by a consecutive read SQE causes the error EINVAL to be returned on the poll CQE.

Ideally (3) would work and perform the read when the socket received input. In order to get it to work, I have to split up the poll and read and only submit the latter after I receive the former.

Likewise when sending data on a socket. In the rare occurrence where the output buffer is full, instead of registering a POLLOUT and retrying the write, it'd be nice to send the data and only have to worry about my total outstanding operations.

Perhaps I'm missing something, but can this be supported? Thanks!

**Comment by axboe** [comment]
This is fixed in the current Linus kernel and it will get backported to stable as well. Your #1 will no longer block, that was a bug.

**Comment by paxostv** [comment]
Great to hear, thank you!
