### ISSUE TITLE
API consistency with libc

### ISSUE THREAD

**Issue by quininer** [axboe/liburing#170]
I noticed that liburing some early APIs were inconsistent with libc.
for example, the `nbytes` of `io_uring_prep_read_fixed`  use `unsigned` instead of `size_t` like `read`. I guess this is because sqe's `len` field only allows u32 type, and using `size_t` may cause arithmetic overflow.

But I found that liburing uses `size_t` in newer `io_uring_prep_send`. I want to know if this is intentional to ensure that the API is more consistent with libc.

**Comment by axboe** [comment]
The max number of IO that can be done with any system call in Linux is 2G, so an unsigned will fit this just fine. That's most likely the source of the inconsistency, and hence it doesn't really matter which one is used.

**Comment by quininer** [comment]
makes sense, thank you.
