### ISSUE TITLE
IORING_OP_OPENAT example

### ISSUE THREAD

**Issue by alphaonex86** [axboe/liburing#172]
Hi,
I search improve https://github.com/Confiared/fastcgicdn with io_uring.
But I don't found example with IORING_OP_OPENAT (needed due to lot of small file).
I have

- Unix socket server
- Curl (then UDP/TCP socket)
- File manipulation (open,close,read,write)

Can you provide example?

Cheers,

**Comment by axboe** [comment]
See test/open-close.c, it's a test case for both IORING_OP_OPENAT and IORING_OP_CLOSE.
