### ISSUE TITLE
Any possibility to add io_uring_prep_sendfile?

### ISSUE THREAD

**Issue by expnkx** [axboe/liburing#173]
I want an async zero-copy to transmit! read/write pair sucks :(

**Comment by axboe** [comment]
Just use splice()? It's what sendfile uses under the covers anyway, there's no difference on the kernel side.

**Comment by expnkx** [comment]
> Just use splice()? It's what sendfile uses under the covers anyway, there's no difference on the kernel side.

Then what about providing a user-level api for io_uring_prep_sendfille to wrap spliace?

**Comment by expnkx** [comment]
BTW, can I mmap the buffer of pipe?

**Comment by axboe** [comment]
> Then what about providing a user-level api for io_uring_prep_sendfille to wrap splice?

It basically consist of a pipe, and setting the size of that to something that works for your use case. Then you splice data to it from a file (for example, or vmsplice() data from your address space), and then you splice from it to a socket.

> BTW, can I mmap the buffer of pipe?

You can't mmap a pipe. See vmsplice(2).
