### ISSUE TITLE
liburing.h looks incompatible with anything that may include /usr/include/sys/mount.h

### ISSUE THREAD

**Issue by majieyue** [axboe/liburing#174]
I met this compiler error when I build libfuse together with liburing:

[6/49] Compiling C object 'lib/76b5a35@@fuse3@sha/mount.c.o'
FAILED: lib/76b5a35@@fuse3@sha/mount.c.o
cc -Ilib/76b5a35@@fuse3@sha -Ilib -I../lib -Iinclude -I../include -I. -I.. -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -g -D_REENTRANT -DHAVE_CONFIG_H -Wall -Wextra -Wno-sign-compare -Wstrict-prototypes -Wmissing-declarations -Wwrite-strings -fno-strict-aliasing -Wno-unused-result -fPIC -pthread -DFUSE_USE_VERSION=35 '-DFUSERMOUNT_DIR="/usr/local/bin"' -MD -MQ 'lib/76b5a35@@fuse3@sha/mount.c.o' -MF 'lib/76b5a35@@fuse3@sha/mount.c.o.d' -o 'lib/76b5a35@@fuse3@sha/mount.c.o' -c ../lib/mount.c
In file included from /usr/include/liburing/io_uring.h:11:0,
                 from /usr/include/liburing.h:15,
                 from ../include/fuse_i.h:8,
                 from ../lib/mount.c:12:
/usr/include/sys/mount.h:35:3: error: expected identifier before numeric constant
   MS_RDONLY = 1,  /* Mount read-only.  */
   ^
In file included from ../lib/mount.c:28:0:
../lib/mount.c:127:13: error: ‘MS_RDONLY’ undeclared here (not in a function)
  {"rw",     MS_RDONLY,     0},
             ^
../lib/mount.c:129:14: error: ‘MS_NOSUID’ undeclared here (not in a function)
  {"suid",    MS_NOSUID,     0},
              ^
../lib/mount.c:131:14: error: ‘MS_NODEV’ undeclared here (not in a function)
  {"dev",     MS_NODEV,     0},
              ^
../lib/mount.c:133:14: error: ‘MS_NOEXEC’ undeclared here (not in a function)
  {"exec",    MS_NOEXEC,     0},
              ^
../lib/mount.c:135:14: error: ‘MS_SYNCHRONOUS’ undeclared here (not in a function)
  {"async",   MS_SYNCHRONOUS, 0},
              ^
../lib/mount.c:137:14: error: ‘MS_NOATIME’ undeclared here (not in a function)
  {"atime",   MS_NOATIME,     0},
              ^
../lib/mount.c:140:14: error: ‘MS_DIRSYNC’ undeclared here (not in a function)
  {"dirsync", MS_DIRSYNC,     1},
              ^
../lib/mount.c: In function ‘get_mnt_flag_opts’:
../lib/mount.c:502:14: error: invalid operands to binary & (have ‘int’ and ‘const struct mount_flags *’)
  if (!(flags & MS_RDONLY) && fuse_opt_add_opt(mnt_optsp, "rw") == -1)
              ^
../lib/mount.c: In function ‘parse_mount_opts’:
../lib/mount.c:522:24: error: invalid operands to binary | (have ‘const struct mount_flags *’ and ‘const struct mount_flags *’)
  mo->flags = MS_NOSUID | MS_NODEV;
                        ^
../lib/mount.c:522:12: warning: assignment makes integer from pointer without a cast [-Wint-conversion]
  mo->flags = MS_NOSUID | MS_NODEV;
            ^

it looks like liburing includes linux/fs.h，which already defines such macros that conflicts with sys/mount.h?
part of quoted from linux/fs.h:
/*
 * These are the fs-independent mount-flags: up to 32 flags are supported
 */
#define MS_RDONLY    1  /* Mount read-only */
#define MS_NOSUID    2  /* Ignore suid and sgid bits */
#define MS_NODEV     4  /* Disallow access to device special files */
#define MS_NOEXEC    8  /* Disallow program execution */
#define MS_SYNCHRONOUS  16  /* Writes are synced at once */
#define MS_REMOUNT  32  /* Alter flags of a mounted FS */
#define MS_MANDLOCK 64  /* Allow mandatory locks on an FS */
#define MS_DIRSYNC  128 /* Directory modifications are synchronous */
#define MS_NOATIME  1024    /* Do not update access times. */
#define MS_NODIRATIME   2048    /* Do not update directory access times */
#define MS_BIND     4096
#define MS_MOVE     8192
#define MS_REC      16384
#define MS_VERBOSE  32768   /* War is peace. Verbosity is silence.
                   MS_VERBOSE is deprecated. */
#define MS_SILENT   32768
#define MS_POSIXACL (1<<16) /* VFS does not apply the umask */
#define MS_UNBINDABLE   (1<<17) /* change to unbindable */
#define MS_PRIVATE  (1<<18) /* change to private */
#define MS_SLAVE    (1<<19) /* change to slave */
#define MS_SHARED   (1<<20) /* change to shared */
#define MS_RELATIME (1<<21) /* Update atime relative to mtime/ctime. */
#define MS_KERNMOUNT    (1<<22) /* this is a kern_mount call */
#define MS_I_VERSION    (1<<23) /* Update inode I_version field */
#define MS_STRICTATIME  (1<<24) /* Always perform atime updates */
#define MS_LAZYTIME (1<<25) /* Update the on-disk [acm]times lazily */

quoted from sys/mount.h
enum
{
  MS_RDONLY = 1,        /* Mount read-only.  */
#define MS_RDONLY   MS_RDONLY
  MS_NOSUID = 2,        /* Ignore suid and sgid bits.  */
#define MS_NOSUID   MS_NOSUID
  MS_NODEV = 4,         /* Disallow access to device special files.  */
#define MS_NODEV    MS_NODEV
  MS_NOEXEC = 8,        /* Disallow program execution.  */
#define MS_NOEXEC   MS_NOEXEC
  MS_SYNCHRONOUS = 16,      /* Writes are synced at once.  */
#define MS_SYNCHRONOUS  MS_SYNCHRONOUS
  MS_REMOUNT = 32,      /* Alter flags of a mounted FS.  */
#define MS_REMOUNT  MS_REMOUNT
  MS_MANDLOCK = 64,     /* Allow mandatory locks on an FS.  */
#define MS_MANDLOCK MS_MANDLOCK
  MS_DIRSYNC = 128,     /* Directory modifications are synchronous.  */
#define MS_DIRSYNC  MS_DIRSYNC
  MS_NOATIME = 1024,        /* Do not update access times.  */
#define MS_NOATIME  MS_NOATIME
  MS_NODIRATIME = 2048,     /* Do not update directory access times.  */
#define MS_NODIRATIME   MS_NODIRATIME
  MS_BIND = 4096,       /* Bind directory at different place.  */
#define MS_BIND     MS_BIND
  MS_MOVE = 8192,
#define MS_MOVE     MS_MOVE
  MS_REC = 16384,
#define MS_REC      MS_REC
  MS_SILENT = 32768,

**Comment by majieyue** [comment]
I removed fs.h from liburing.h and the build is OK

the only dependency of fs.h is 

typedef int __bitwise __kernel_rwf_t;

and I did a dirty work to define it in liburing.h

**Comment by majieyue** [comment]
another way is to adjust the header file include sequences, the mount.h must be included before liburing.h

**Comment by axboe** [comment]
This isn't a liburing issue, liburing.h doesn't use any mount related bits. This should be fixed in the system headers, or in the application.
