### ISSUE TITLE
Suggestion: IORING_OP_TIMEOUT with sqe->off == 0

### ISSUE THREAD

**Issue by CarterLi** [axboe/liburing#18]
I noticed that for IORING_OP_TIMEOUT, [if completion event count is not set, it defaults to 1](https://github.com/torvalds/linux/blob/31f4f5b495a62c9a8b15b1c3581acd5efeb9af8c/fs/io_uring.c#L1949). It's not very useful in my opinion. I suggest if `sqe->off` equals to 0, IORING_OP_TIMEOUT acts like a timer. That is to say, IORING_OP_TIMEOUT won't be completed through other requests' completion.

With this change, timerfd can be partially replaced. `interval` is not suit for io_uring though.

Yes it's a breaking change. `sqe->off == -1` is also considerable.

**Comment by axboe** [comment]
We haven't released a kernel with it yet, it'll b ein 5.4. So a change could still be made, if it's important enough. But sqe->off == -1U gets you what you want, only difference is it would still trigger when the ring has rolled through 4 billion entries. Is this a concern?

**Comment by CarterLi** [comment]
> only difference is it would still trigger when the ring has rolled through 4 billion entries. Is this a concern?

It's not perfect. In addition, the logic can be simplified if other requests' completion won't affect the timer ( I guess )

**Comment by axboe** [comment]
I don't disagree with you, just trying to see if there's strong reasoning for doing it that way. It'll mean some changes on the kernel side since we have to track those requests a bit differently.

So let me ask again - is it really an issue to use -1U as the completion count, if it then potentially completes early if the ring goes through 4 billion requests? Serious question, I'm willing to entertain the change if the reasoning is strong enough.

**Comment by CarterLi** [comment]
io_uring is designed for high concurrency. Since the timeout value can be very long, you can't say 4 billion is always enough. A bug is still a bug though it happens very rarely, for rigorousness.

**Comment by axboe** [comment]
OK, this should do it, I'll post it for review:

```
diff --git a/fs/io_uring.c b/fs/io_uring.c
index 0f709949a26d..78e90475fdf5 100644
--- a/fs/io_uring.c
+++ b/fs/io_uring.c
@@ -341,6 +341,7 @@ struct io_kiocb {
 #define REQ_F_ISREG		2048	/* regular file */
 #define REQ_F_MUST_PUNT		4096	/* must be punted even for NONBLOCK */
 #define REQ_F_INFLIGHT		8192	/* on inflight list */
+#define REQ_F_TIMEOUT_NOSEQ	16384	/* no timeout sequence */
 	u64			user_data;
 	u32			result;
 	u32			sequence;
@@ -481,9 +482,13 @@ static struct io_kiocb *io_get_timeout_req(struct io_ring_ctx *ctx)
 	struct io_kiocb *req;
 
 	req = list_first_entry_or_null(&ctx->timeout_list, struct io_kiocb, list);
-	if (req && !__io_sequence_defer(req)) {
-		list_del_init(&req->list);
-		return req;
+	if (req) {
+		if (req->flags & REQ_F_TIMEOUT_NOSEQ)
+			return NULL;
+		if (!__io_sequence_defer(req)) {
+			list_del_init(&req->list);
+			return req;
+		}
 	}
 
 	return NULL;
@@ -2293,18 +2298,24 @@ static int io_timeout(struct io_kiocb *req, const struct io_uring_sqe *sqe)
 
 	hrtimer_init(&req->timeout.timer, CLOCK_MONOTONIC, mode);
 
+	req->flags |= REQ_F_TIMEOUT;
+
 	/*
 	 * sqe->off holds how many events that need to occur for this
-	 * timeout event to be satisfied.
+	 * timeout event to be satisfied. If it isn't set, then this is
+	 * a pure timeout request, sequence isn't used.
 	 */
 	count = READ_ONCE(sqe->off);
-	if (!count)
-		count = 1;
+	if (!count) {
+		req->flags |= REQ_F_TIMEOUT_NOSEQ;
+		spin_lock_irq(&ctx->completion_lock);
+		entry = ctx->timeout_list.prev;
+		goto add;
+	}
 
 	req->sequence = ctx->cached_sq_head + count - 1;
 	/* reuse it to store the count */
 	req->submit.sequence = count;
-	req->flags |= REQ_F_TIMEOUT;
 
 	/*
 	 * Insertion sort, ensuring the first entry in the list is always
@@ -2316,6 +2327,9 @@ static int io_timeout(struct io_kiocb *req, const struct io_uring_sqe *sqe)
 		unsigned nxt_sq_head;
 		long long tmp, tmp_nxt;
 
+		if (nxt->flags & REQ_F_TIMEOUT_NOSEQ)
+			continue;
+
 		/*
 		 * Since cached_sq_head + count - 1 can overflow, use type long
 		 * long to store it.
@@ -2342,6 +2356,7 @@ static int io_timeout(struct io_kiocb *req, const struct io_uring_sqe *sqe)
 		nxt->sequence++;
 	}
 	req->sequence -= span;
+add:
 	list_add(&req->list, entry);
 	req->timeout.timer.function = io_timeout_fn;
 	hrtimer_start(&req->timeout.timer, timespec64_to_ktime(ts), mode);
```

**Comment by axboe** [comment]
I built a test case and verified it works, we don't complete even if the ring wraps. I've posted this for review and CC'ed you, please reply with a reviewed-by or tested-by comment so I can add that to the commit.

**Comment by CarterLi** [comment]
Done. Thanks for your quick patch!

**Comment by axboe** [comment]
Thanks for reporting! I've got this patch queued up for going into 5.4-rc this week.

**Comment by CarterLi** [comment]
Looking forward to the release of Linux 5.4!
