### ISSUE TITLE
signalfd with io_uring causes kernel hang on 5.8.3-arch1-1 

### ISSUE THREAD

**Issue by DmtKats** [axboe/liburing#180]
I tried bumping up today to the 5.8.3 version of the kernel and my kernel started hanging when working with io_uring. After some investigation I discovered that if you queue signalfd to be handled by io_uring, firing any signal, even if it has not been blocked or added to the signalfd instance still causes the kernel to start hanging, with applications becoming unresponsive until eventually everything freezes(within a matter of seconds). I tried using this to test a minimal use case:

https://gist.github.com/CarterLi/b8db2fcfea689b96eeae382c38130afb

The epoll case works as intended, io_uring cases(both test_uring and test_workaround) cause the stall. I have tried both with io_uring_prep_poll_add and io_uring_prep_read, both have the same result.

uname -a:
`Linux arch 5.8.3-arch1-1 #1 SMP PREEMPT Fri, 21 Aug 2020 16:54:16 +0000 x86_64 GNU/Linux`

**Comment by axboe** [comment]
This should fix it:

https://git.kernel.dk/cgit/linux-block/commit/?h=io_uring-5.9&id=fd7d6de2241453fc7d042336d366a939a25bc5a9

**Comment by DmtKats** [comment]
I tested this with the latest arch release and it is fixed. Thanks for the fast response!
