### ISSUE TITLE
io_uring_prep_splice type mismatch with test

### ISSUE THREAD

**Issue by YoSTEALTH** [axboe/liburing#182]
Type of `off_in` and `off_out` for `io_uring_prep_splice`
https://github.com/axboe/liburing/blob/master/src/include/liburing.h#L200

does not match with type used in test of `loff_t`
https://github.com/axboe/liburing/blob/master/test/splice.c#L137

**Comment by axboe** [comment]
They are ultimately the same type, as loff_t with LFS is 64-bit.

**Comment by YoSTEALTH** [comment]
`uint64_t` being unsigned cause problem for ``-1`` values?

**Comment by axboe** [comment]
It should work just fine. But that said, let's just fix it up, causes less confusion too. I pushed out a fix:

https://git.kernel.dk/cgit/liburing/commit/?id=10ffacfbda29f2183c86c2cadd5704526d81fa85
