### ISSUE TITLE
Reading from stdin hangs at EOF, unless submitted with IOSQE_ASYNC

### ISSUE THREAD

**Issue by wisp3rwind** [axboe/liburing#184]
With kernel `Linux 5.8.3-arch1-1 #1 SMP PREEMPT Fri, 21 Aug 2020 16:54:16 +0000 x86_64` and liburing 0.7, running the following program as `dd if=/dev/urandom count=1 | ./program` hangs in `io_uring_wait_cqe` after `dd`exits and all the data is read from stdin

```c
#define _GNU_SOURCE

#include <errno.h>
#include <stdio.h>
#include <string.h>
#include <unistd.h>
#include <liburing.h>

int
main(int argc, char **argv)
{
    const ssize_t bufsize = 512;
    char buf[bufsize];
    ssize_t size = 0;
    struct io_uring ring;
    struct io_uring_sqe *sqe;
    struct io_uring_cqe *cqe;

    io_uring_queue_init(8, &ring, 0);
    while (1) {
        sqe = io_uring_get_sqe(&ring);
        io_uring_prep_read(sqe, STDIN_FILENO, buf, bufsize, 0);
        /* sqe->flags |= IOSQE_ASYNC; */
        io_uring_submit(&ring);
        io_uring_wait_cqe(&ring, &cqe);

        if (cqe->res < 0) {
            fprintf(stderr, "Read error: %s\n", strerror(-cqe->res));
            return 1;
        }
        if (cqe->res == 0) {
            fprintf(stderr, "EOF\n");
            break;
        }
        size += cqe->res;
        io_uring_cqe_seen(&ring, cqe);
    }

    fprintf(stderr, "Read: %zd\n", size);
    return 0;
}
```

whereas it finishes at EOF when uncommenting the line that adds the `IOSQE_ASYNC` flag. I would expect that both cases behave the same, i.e. generate a CQE with zero bytes read after the writer has closed the pipe.

Is reading from/writing to pipes even a thing that is supposed to be supported by `io_uring`? If so, would it be possible to also support `offset=-1` in the arguments to `io_uring_prep_{read,write}` instead of `offset=0`as used above? That seems to be more consistent with regular files, for which `offset=0` has a different meaning. In particular, for programs that can read both from stdin or a regular file, that would obliterate the need to distinguish these cases (when reading the entire file sequentially).

Thanks for your work! I hope this is the right place to report the issue, since this is probably something in the kernel rather than liburing, but I saw a note of @axboe on the kernel bugzilla that he doesn't usually read anything there.

**Comment by axboe** [comment]
Oops, that's a bug! It should work just fine with pipes etc, just made a mistake in how the poll handling is done. This should work:

```
diff --git a/fs/io_uring.c b/fs/io_uring.c
index 384df86dfc69..d15139088e4c 100644
--- a/fs/io_uring.c
+++ b/fs/io_uring.c
@@ -4889,12 +4889,20 @@ static bool io_arm_poll_handler(struct io_kiocb *req)
 	struct async_poll *apoll;
 	struct io_poll_table ipt;
 	__poll_t mask, ret;
+	int rw;
 
 	if (!req->file || !file_can_poll(req->file))
 		return false;
 	if (req->flags & REQ_F_POLLED)
 		return false;
-	if (!def->pollin && !def->pollout)
+	if (def->pollin)
+		rw = READ;
+	else if (def->pollout)
+		rw = WRITE;
+	else
+		return false;
+	/* if we can't nonblock try, then no point in arming a poll handler */
+	if (!io_file_supports_async(req->file, rw))
 		return false;
 
 	apoll = kmalloc(sizeof(*apoll), GFP_ATOMIC);
```

Can I have your real name and email, so I can add proper reporting attribution to the patch I'll queue for upstream?

**Comment by axboe** [comment]
Here it is in patch form:

https://git.kernel.dk/cgit/linux-block/commit/?h=io_uring-5.9&id=68faa4727c0e2d7d255d9b97e754f2cda748f141

**Comment by axboe** [comment]
And I adapted your test case into something that fits with the liburing regression suite and pushed it out:

https://git.kernel.dk/cgit/liburing/commit/?id=43e05df7cd2b4463bec0cdf5457ac0e666334d01

**Comment by wisp3rwind** [comment]
Thanks for the quick fix! I'm Benedikt Ames, `wisp3rwind at posteo dot eu`.

Regarding
> [...] would it be possible to also support `offset=-1` in the arguments to `io_uring_prep_{read,write}` instead of `offset=0` as used above? That seems to be more consistent with regular files, for which `offset=0` has a different meaning. In particular, for programs that can read both from stdin or a regular file, that would obliterate the need to distinguish these cases (when reading the entire file sequentially).

What I meant is that in the program above, when changing
```c
io_uring_prep_read(sqe, STDIN_FILENO, buf, bufsize, 0);
```
to
```c
io_uring_prep_read(sqe, STDIN_FILENO, buf, bufsize, -1);
```
the `cqe` for this request returns with an `EINVAL` error code. I would have expected it to behave as described for `IORING_FEAT_RW_CUR_POS` in `io_uring_setup(2)`. If it did so, the meaning of the offset `-1` would also be equivalent for regular files and pipes, i.e. just read the whole data sequentially. The same happens with `io_uring_prep_write`.

**Comment by axboe** [comment]
The offset behavior should be the same as for eg ```pread``` and friends, is it not?

**Comment by wisp3rwind** [comment]
To be honest, I didn't check, but it makes sense that this should behave like `pread(v2)`, however that treats the offset. I only searched for documentation, which is pretty sparse with regard to pipes. According to [`pread(3)`](https://linux.die.net/man/3/pread), the offset is ignored for pipes (but POSIX `pread` does not support -1 offsets for any kind of file). [`preadv2(2)`](https://www.man7.org/linux/man-pages/man2/preadv2.2.html) doesn't really say anything about pipes in particular, and what an offset of -1 should do in their case.

**Comment by axboe** [comment]
I just checked pread and it behaves the same, you get -EINVAL if you specify an offset of -1. Let me check preadv2, but I'd be surprised if it's not the same.

**Comment by wisp3rwind** [comment]
In fact, the following (essentially your pipe eof testcase, but without io_uring) works with the offset `-1`

```c
#define _GNU_SOURCE

#include <errno.h>
#include <pthread.h>
#include <stdio.h>
#include <string.h>
#include <sys/uio.h>
#include <unistd.h>
#include "liburing.h"

#define BUFSIZE	512

struct data {
	char *str;
	int fds[2];
};

static void *t(void *data)
{
	struct data *d = data;
	int ret;

	strcpy(d->str, "This is a test string");
	ret = write(d->fds[1], d->str, strlen(d->str));
	close(d->fds[1]);
	if (ret < 0)
		perror("write");

	return NULL;
}

int main(int argc, char *argv[])
{
	static char buf[BUFSIZE];
	static char str[BUFSIZE];
	pthread_t thread;
	struct data d;
	int ret;
	struct iovec iov;

	if (pipe(d.fds) < 0) {
		perror("pipe");
		return 1;
	}
	d.str = str;

	pthread_create(&thread, NULL, t, &d);

	while (1) {
		iov.iov_base = buf;
		iov.iov_len = BUFSIZE;
		/* signature: (fd, iov, iovcnt, offset, flags) */
		ret = preadv2(d.fds[0], &iov, 1, -1, 0);
		if (ret < 0) {
			fprintf(stderr, "Read error: %s\n", strerror(-ret));
			return 1;
		}
		if (ret == 0)
			break;
	}

	pthread_join(thread, NULL);
	return 0;
}
```
but fails with `Read error: Operation not permitted` when setting the offset to `0`.

**Comment by axboe** [comment]
Yep same with preadv, agree with your test that preadv2 does work with -1. Pretty inconsistent...

**Comment by wisp3rwind** [comment]
But then, it's probably not `io_uring`s job to do anything about it. Although `io_uring_setup(2)` claims
> IORING_FEAT_RW_CUR_POS
If this flag is set, applications can specify offset == -1 with IORING_OP_{READV,WRITEV} , IORING_OP_{READ,WRITE}_FIXED, and IORING_OP_{READ,WRITE} to mean current file position, which behaves like preadv2(2) and pwritev2(2) with offset == -1. It'll  use  (and  update) the current file position. This obviously comes with the caveat that if the application has multiple reads or writes in flight, then the end result will not be as expected. This is similar to threads sharing a file descriptor and doing IO using the current file position.

Anyway, thanks again for all the support! I guess this issue can be closed :tada:

**Comment by axboe** [comment]
Well, we could still make it consistent. Should be pretty trivial:

```
diff --git a/fs/io_uring.c b/fs/io_uring.c
index d9b88644d5e8..bd2d8de3f2e8 100644
--- a/fs/io_uring.c
+++ b/fs/io_uring.c
@@ -2866,6 +2866,11 @@ static ssize_t io_import_iovec(int rw, struct io_kiocb *req,
 	return iov_iter_count(&req->io->rw.iter);
 }
 
+static inline loff_t *io_kiocb_ppos(struct kiocb *kiocb)
+{
+	return kiocb->ki_filp->f_mode & FMODE_STREAM ? NULL : &kiocb->ki_pos;
+}
+
 /*
  * For files that don't have ->read_iter() and ->write_iter(), handle them
  * by looping over ->read() or ->write() manually.
@@ -2901,10 +2906,10 @@ static ssize_t loop_rw_iter(int rw, struct file *file, struct kiocb *kiocb,
 
 		if (rw == READ) {
 			nr = file->f_op->read(file, iovec.iov_base,
-					      iovec.iov_len, &kiocb->ki_pos);
+					      iovec.iov_len, io_kiocb_ppos(kiocb));
 		} else {
 			nr = file->f_op->write(file, iovec.iov_base,
-					       iovec.iov_len, &kiocb->ki_pos);
+					       iovec.iov_len, io_kiocb_ppos(kiocb));
 		}
 
 		if (iov_iter_is_bvec(iter))
@@ -3139,7 +3144,7 @@ static int io_read(struct io_kiocb *req, bool force_nonblock,
 		goto copy_iov;
 
 	iov_count = iov_iter_count(iter);
-	ret = rw_verify_area(READ, req->file, &kiocb->ki_pos, iov_count);
+	ret = rw_verify_area(READ, req->file, io_kiocb_ppos(kiocb), iov_count);
 	if (unlikely(ret))
 		goto out_free;
 
@@ -3262,7 +3267,7 @@ static int io_write(struct io_kiocb *req, bool force_nonblock,
 		goto copy_iov;
 
 	iov_count = iov_iter_count(iter);
-	ret = rw_verify_area(WRITE, req->file, &kiocb->ki_pos, iov_count);
+	ret = rw_verify_area(WRITE, req->file, io_kiocb_ppos(kiocb), iov_count);
 	if (unlikely(ret))
 		goto out_free;
 
```

**Comment by axboe** [comment]
https://lore.kernel.org/io-uring/eee81ef8-8669-fb73-954d-99a75e940d02@kernel.dk/T/#u

**Comment by wisp3rwind** [comment]
Ignoring the offset entirely seems sensible :+1:,  even though `preadv2` does fail with non-negative offset (probably it still attemps to seek in the file?).

> Yep same with preadv, agree with your test that preadv2 does work with -1. Pretty inconsistent...

Actually, on my system, I can't make `pread`/`preadv` work at all, which would be consistent with their man pages:

> The file offset is not changed by these system calls.  The file referred to by fd must be capable of seeking.

(from  `preadv(2)`)

**Comment by axboe** [comment]
> Actually, on my system, I can't make pread/preadv work at all, which would be consistent with their man pages:

Right, I didn't mean in terms of man pages, just in terms of behavior between the two.
