### ISSUE TITLE
IOSQE_IO_LINK - ECANCELED

### ISSUE THREAD

**Issue by YoSTEALTH** [axboe/liburing#187]
For `IOSQE_IO_LINK` I don't get why "eg, a short read will also terminate the remainder of the chain." couldn't `sqe.res` just return the length read? even if its shorter then buffer specified, just like normal `io_uring_prep_read*`, why must this be an error?

**Comment by isilence** [comment]
Because if, for instance, you have "read(buf, N bytes) -> send(buf, N)",
and it's a short read, you'll be surprised sending garbage data. And that
garbage may even be confidential information.

**Comment by YoSTEALTH** [comment]
It could be more less:
``` python
read(buf, ...)
send(buf[0:sqe.res])
```

**Comment by isilence** [comment]
Right, but not for IOSQE_IO_LINK, because linked requests are set upfront before you know `cqe.res`.

**Comment by YoSTEALTH** [comment]
That is a good point, hmm... so there is no accountability internally to know how much was read before sending, eh...

**Comment by YoSTEALTH** [comment]
Another concern i had was say if you are linking:
``` python

read(buf, 1024)
send(buf, 1024)
```
is the `send` guaranteed to send ``1024`` bytes? what if it only sends ``512`` bytes? socket send can fluctuate right.

**Comment by axboe** [comment]
Doesn't matter, since it's end of the chain. So you get to deal with it in the app, exactly how you would a standalone send/write/whatever that's short.

**Comment by YoSTEALTH** [comment]
By that logic if i `read(buff, 1024)` and it reads ``512`` bytes it will raise `ECANCELED` at the same time if i `send(buff, 1024)` and it sends ``512`` bytes it doesn't raise `ECANCELED`? this isn't consistent.

**Comment by axboe** [comment]
Your example had read <link> send, so if the read is short, it fails dependent links - which is the send. The send doesn't have anything linked after it, so nothing to cancel. This is fully consistent with how links work. If you swapped the order of them, then a short send would of course cancel the read.

**Comment by axboe** [comment]
What would the short send cancel? Nothing. So the status of that is reported as expected.

**Comment by YoSTEALTH** [comment]
>If you swapped the order of them, then a short send would of course cancel the read.

ok, this is good to know... so pretty much any task that doesn't do exactly as specified will `ECANCELED` under `IOSQE_IO_LINK`. 

Say if you link and submit ``5`` sqe using `IOSQE_IO_LINK` flag, is it guaranteed to return one after another when you `io_uring_wait_cqe_nr(ring, cqes, 5)` just as submitted? Since you "linked" it, can we asssume it return cqes in same order?

Its actually good to know such small details.

**Comment by axboe** [comment]
This isn't small details, this is the basic understanding of how links work. It is fully documented.
