### ISSUE TITLE
empty `io_uring_get_sqe`

### ISSUE THREAD

**Issue by YoSTEALTH** [axboe/liburing#188]
Should empty `io_uring_get_sqe` be allowed? A test like this passes
``` python
# flake8: noqa
from liburing import *


def test_empty_event(tmpdir):
    ring = io_uring()
    cqes = io_uring_cqes()
    try:
        # initialization
        assert io_uring_queue_init(2, ring, 0) == 0

        # do nothing with sqe
        sqe = io_uring_get_sqe(ring)
        # ...
        assert io_uring_submit(ring) == 1
        assert io_uring_wait_cqe(ring, cqes) == 0

        cqe = cqes[0]
        assert cqe.res == 0
        io_uring_cqe_seen(ring, cqe)
    finally:
        io_uring_queue_exit(ring)
```
In a larger event manager extra/empty `io_uring_get_sqe` will make it hang in limbo.

**Comment by isilence** [comment]
Do you mean you've got non-NULL sqe but not initialised it? Then it contains garbage.
If so, could you post here what's inside your SQE (i.e. binary dump)?

**Comment by YoSTEALTH** [comment]
> Do you mean you've got non-NULL sqe but not initialised it? Then it contains garbage.

Yes, sql is not null.
> If so, could you post here what's inside your SQE (i.e. binary dump)?

I am not sure what you are asking for.

I have recreated this "limbo" issue - sorry for my made up lingo :)
``` python
# flake8:noqa
import os
from liburing import *


def test_limbo_event(tmpdir):
    # prep
    fd = os.open(os.path.join(tmpdir, 'limbo.txt'), os.O_RDWR | os.O_CREAT, 0o660)
    os.write(fd, b'hello world')

    ring = io_uring()
    cqes = io_uring_cqes()
    try:
        # initialization
        assert io_uring_queue_init(4, ring, 0) == 0

        one = bytearray(5)
        two = bytearray(6)
        iov = iovec(one, two)

        # do nothing with sqe
        sqe = io_uring_get_sqe(ring)
        io_uring_prep_read(sqe, fd, iov[0].iov_base, len(one), 0, 0)
        # sqe.flags |= IOSQE_IO_LINK  # no hanging problems
        sqe.flags |= IOSQE_IO_LINK | IOSQE_ASYNC  # this will be in limbo.

        sqe = io_uring_get_sqe(ring)
        io_uring_prep_read(sqe, fd, iov[1].iov_base, len(two), 5, 0)
        sqe.flags |= IOSQE_ASYNC

        # empty sqe
        sqe = io_uring_get_sqe(ring)
        if sqe:
            print()
            print('sqe is not null')
            # output: sqe is not null

        assert io_uring_submit(ring) == 3

        # empty sqe
        assert io_uring_wait_cqe_nr(ring, cqes, 3) == 0
        cqe = cqes[0]
        assert cqe.res == 0
        io_uring_cqe_seen(ring, cqe)

        # one
        assert io_uring_wait_cqe_nr(ring, cqes, 3) == 0
        cqe = cqes[0]
        assert cqe.res == 5
        io_uring_cqe_seen(ring, cqe)
        assert one == bytearray(b'hello')

        # two
        assert io_uring_wait_cqe_nr(ring, cqes, 3) == 0
        cqe = cqes[0]
        assert cqe.res == 6
        io_uring_cqe_seen(ring, cqe)
        assert two == bytearray(b' world')
    finally:
        os.close(fd)
        io_uring_queue_exit(ring)
```

**Comment by isilence** [comment]
You have an SQE, it's a chunk of memory probably filled with zeros.
I want to know whether it's really zeros, and if not what byte sequence
it contains specifically for your system.

**Comment by YoSTEALTH** [comment]
Could you tell me what I need to run to get this info?

**Comment by isilence** [comment]
Ok, could you please elaborate on what you mean by "empty io_uring_get_sqe()"?

**Comment by isilence** [comment]
Look, all SQEs are stored in a single contigous chunk of memory of
size N * sizeof(struct io_uring_sqe), and io_uring_get_sqe() returns
an index to it, that's it. Apps have to initialised an SQE somehow,
otherwise it doesn't make sense, and because of that io_uring_get_sqe()
don't do memzero() or something but just returns garbage.

The most probable reason why it "hang in limbo" is because
with time it returns already used before SQE and uses previously
recorded into it command, which is no longer valid.

e.g.
Lets's address for your 1st SQE was X, and you filled it with recv().
And then n'th SQE also have the same memory address X, and
as you didn't initialise it, it still retains the mentioned recv(), which
you may not expect.

Let me know if that's still not clar.

**Comment by isilence** [comment]
You can hide it in your library. For instance:
```python
def lib_io_uring_prep_read():
    sqe = io_uring_get_sqe()
    io_uring_prep_read(sqe)
```

All io_uring_prep_*() functions just set 64B of data. So, I'm not even sure
what would be faster in Python -- to call liburing.so's io_uring_prep_read()
or reimplement it in python. E.g.
```python
def lib_io_uring_prep_read():
    sqe = io_uring_get_sqe()
    sqe.opcode = ...;
    sqe.addr = ...;
    ....
```

And BTW, I'm

**Comment by axboe** [comment]
The memory is likely cleared, so you're just submitting a NOP. And yes,
that'll succeed just fine.

**Comment by isilence** [comment]
> The memory is likely cleared, so you're just submitting a NOP. And yes,
that'll succeed just fine.

Right, for this test case.

> In a larger event manager extra/empty io_uring_get_sqe will make it hang in limbo.

But as I understood the phrase above, the issue was about long runs as well.

**Comment by YoSTEALTH** [comment]
Let me try to simply...

The first example works even with ``sqe = io_uring_get_sqe(ring)`` having nothing assigned right? ok good.

The second example we have ``3`` `sqe` being assigned and the 3rd one having nothing assigned to it.
``` python
# empty sqe
sqe = io_uring_get_sqe(ring)
```
This should also pass without any problems right? no, why?

The problem is
``` python
sqe.flags |= IOSQE_IO_LINK | IOSQE_ASYNC  # this will be in limbo.
```
It has something to do with `IOSQE_ASYNC` that makes the second example go into "limbo".

If i change above code to
``` python
sqe.flags |= IOSQE_IO_LINK  # this will be in limbo.
```
There is no problems.

Thus my comment about empty ``sqe = io_uring_get_sqe(ring)`` not working well with `IOSQE_ASYNC`, as far as i can tell, maybe there is something else going on! i dono, why i am reporting this issue.

**Comment by isilence** [comment]
Ok, the request should be a nop and so be executed instantly.
And in any case I don't see how first read influences the nop.
I'll try to reproduce it

**Comment by YoSTEALTH** [comment]
This issue was stressful so took few days off of this subject.

Now that I am looking back at it might be because I am using ``3`` in multiple `io_uring_wait_cqe_nr(ring, cqes, 3)` vs 3 2 1? This does fix the issues.

What a pain.

**Comment by YoSTEALTH** [comment]
PS. Just wanted to note that empty `sqe` are very cool now that I find use-case for this.

**Comment by isilence** [comment]
What do you mean? The thing you was calling "empty sqe" is just
a nop request (i.e. a request with `IORING_OP_NOP` opcode).

Would you mind sharing your use case?

**Comment by YoSTEALTH** [comment]
O ok then empty sqe = IORING_OP_NOP. 

I use the nop as a way to track linked `IOSQE_IO_LINK`

```python
sqe = io_uring_get_sqe(ring)  # 1
io_uring_prep_read(sqe, ...)
sqe.flags |= IOSQE_IO_LINK

sqe = io_uring_get_sqe(ring)  # 2
io_uring_prep_read(sqe, ...)
sqe.flags |= IOSQE_IO_LINK

# last nop sqe as tracker
sqe = io_uring_get_sqe(ring)  # 3
```
Since linked entries happens one after another, I know when I receive the last `sqe` everything is completed in success or failure. Also last sqe tells me if ``2`` sqe broke its link or not. And no I can't use ``2`` as the tracker cause its hard to tell what is last!

Above code would be auto generated by something like
```python
read_1 = io_uring_prep_read, (...)
read_2 = io_uring_prep_read, (...)
results = await entries([read_1, read_2], IOSQE_IO_LINK | IOSQE_ASYNC)
```

This solves a lot of problems
    - Being able to submit multiple entries in a single `await` is huge boost for speed.
    - allows for single `io_uring_submit` that doesn't separate link
    - Returning multiple `results` as `[11, 10]` also in the same `await` call.


I could keep going writing an article about it. Point being it simplifies complex linking into a single call/result.

**Comment by isilence** [comment]
I'm asking because using not-initialised requests is buggy, at least sqe->opcode should be set.
For your case it should be like below, otherwise with time io_uring will reuse some old sqe
and give you not a nop but something more random -- a previously filled request, to be exact.

```python
# last nop sqe as tracker
sqe = io_uring_get_sqe(ring)  # 3
io_uring_prep_nop(sqe, ...)
```

**Comment by YoSTEALTH** [comment]
O i c, thank you very much for letting me know about using `io_uring_prep_nop` I will adapt my code :)
