### ISSUE TITLE
io_uring_register  with IORING_REGISTER_BUFFERS failed on hugepages 

### ISSUE THREAD

**Issue by optimistyzy** [axboe/liburing#197]
The issue is that: 
We use io_uring_register with IORING_REGISTER_BUFFERS  opcode to register hugepages. Previously it works, and now it fails 
 with EOPNOTSUPP error code.  After I checking the  " man io_uring_register.2", I  found that  

 EOPNOTSUPP
              User buffers point to file-backed memory.

Our huge pages are allocated from the file, so it fails with errno =  EOPNOTSUPP. So the buffer registration fails.  So may I ask a question for hugepages, can we not restrict the usage to file-backed memory.  
@axboe 

I think that it may be related with the kernel restriction for uring support. My Kernel version is 5.8

Thanks.

**Comment by axboe** [comment]
Please include what version it worked on as well, the huge pages being file backed check has been there since 5.1 when io_uring was introduced. This never changed over the life time of io_uring in the kernel.

What's your test case?

**Comment by optimistyzy** [comment]
@axboe 

My testcase is to register lots of memory ranges from huge pages.  It is very strange, after I reboot the machines and recomplile some codes, the issue disappears.

For liburing:

I used  b868f7394f234067bc6b2c96d6bc1dd745fcf397 this version

Let me close this issue. If the similar issue happens again, I will reopen this issue.

Thanks.
