### ISSUE TITLE
determine sqe still available

### ISSUE THREAD

**Issue by YoSTEALTH** [axboe/liburing#198]
I would like to know how many `sqe` are still available so:
``` C

io_uring_queue_init(8, &ring, 0);

unsigned int available = &ring->sq->kring_entries - &ring->sq->sqe_tail
```
This this accurate? Am I missing anything?

**Comment by axboe** [comment]
liburing has a helper for this - if you can't use that, you should implement it identically:

https://git.kernel.dk/cgit/liburing/tree/src/include/liburing.h#n461

You'd want to subtract this value from sq_entries to tell you how many are left, as the helper returns how many are ready to be consumed.

**Comment by YoSTEALTH** [comment]
Does it have to be `sq_entries` in `io_uring_params`? Wouldn't ``&ring->sq->kring_entries - io_uring_sq_ready(&ring)`` work? It would be pain to access `sq_entries` since its not directly in `&ring`

**Comment by axboe** [comment]
You can use either one, doesn't matter, they are identical.

**Comment by YoSTEALTH** [comment]
o wait `io_uring_sq_space_left` already exists that does what I want. That "space" could we rename it to "entry" or "entries"

**Comment by axboe** [comment]
Right, there is a helper that does just that. But no, cannot rename something like that, it'll potentially break compilation of existing apps.

**Comment by YoSTEALTH** [comment]
Ok, Thanks for your awesome support, looks like you have already thought about these feature and implemented it ahead of time ;) ;)
