### ISSUE TITLE
privilege requirement for using SQPOLL

### ISSUE THREAD

**Issue by wuxb45** [axboe/liburing#2]
Calling io_uring_setup with ...SQPOLL returns -1 with errno = 1 (EPERM)
After several failed search on documentations, I eventually found in the kernel code it requires CAP_SYS_ADMIN.

Could you add a few words in liburing's comments, or maybe in a newer version of "Efficient IO with io_uring" to warn new SQPOLL enthusiasts of this possible error?

BTW, this privilege check really makes it hard to use SQPOLL since the user process have to run with "escalated" privilege level, or no SQPOLL at all...

**Comment by axboe** [comment]
That is correct, due to how much CPU usage we can gobble up on the kernel side, SQPOLL needs root privileges to create the ring. You can drop privileges after creation, if you want to, however.

I'll add some notes about this in the io_uring doc.
