### ISSUE TITLE
Documentation of IORING_OP_PROVIDE_BUFFERS is unclear

### ISSUE THREAD

**Issue by withoutboats** [axboe/liburing#204]
The man page states:

> * *fd* must contain the number of buffers to provide,
> * *addr* must contain the starting address to add buffers from,
> * *len* must contain the length of each buffer to add from the range,

I can't tell from this documentation if addr is meant to point to an allocation of `fd * len` bytes, which will be divided into `fd` buffers of `len` size, or to an array of `fd` pointers to allocations of `len` bytes.

**Comment by axboe** [comment]
I pushed out an update that hopefully clarifies this, it's case one in your two examples.

**Comment by withoutboats** [comment]
Thanks!
