### ISSUE TITLE
io_uring_sqe_set_data after io_uring_submit?

### ISSUE THREAD

**Issue by ciconia** [axboe/liburing#207]
Would it be possible to call `io_uring_sqe_set_data` after calling `io_uring_submit` such that the new data value would be reflected in the CQE on completion?

**Comment by YoSTEALTH** [comment]
No, https://github.com/axboe/liburing/blob/master/src/include/liburing.h#L185
`io_uring_sqe_set_data` sets ``sqe->user_data`` so calling it after `io_uring_submit` would probably be an error.

Here is a good documentation for how to use liburing and its features https://unixism.net/loti/index.html

**Comment by isilence** [comment]
Right, it is not possible. Is there a good reason you need it?

**Comment by ciconia** [comment]
I'm building a io_uring-based backend for [Polyphony](https://github.com/digital-fabric/polyphony), a Ruby gem for fiber-based concurrency. In Polyphony, any blocking operation can be cancelled at any time by raising an exception, which would cause the io_uring backend to cancel the submitted operation using `IORING_OP_ASYNC_CANCEL`, which apparently is only available beginning in Linux kernel 5.5.

I'd like though to be able to support Kernel 5.4. So I thought resetting the user data might be a way to signal that the operation has been cancelled. Anyway even if it were possible it probably would have been racy. I'm closing this issue...
