### ISSUE TITLE
What does write complete mean? 

### ISSUE THREAD

**Issue by johalun** [axboe/liburing#208]
Not so much a bug or issue but more of a question. Say for example for a TCP connection, when is a write regarded as complete? Is it when all the data has been ACKed by the peer, or before that? 

Thanks!

**Comment by johalun** [comment]
To give some context, we have an epoll patch that notifies us when the TCP send buffer is empty (all data ACKed). We're now experimenting with switching to liburing and I wonder if we need to patch it as well, or if it has the functionality we need.

**Comment by axboe** [comment]
It's signaled as completed in the exact same fashion as an eg sendmsg() or similar regular system call would, there's no differences there.
