### ISSUE TITLE
Question about size of the ring buffer

### ISSUE THREAD

**Issue by boxerab** [axboe/liburing#209]
First of all, thank you for making this incredible new feature available - really excited to start using it in my codec project.
I was wondering what the performance impact is of varying the size of the ring buffer - should I expect to see any difference
in performance between a 1k vs 16 k size buffer ? I ask because I plan on using the library for asynch writes, and I don't want to have to wait if the ring buffer is full. So I plan on sizing the buffer relative to the file size and write buffer size so that I never have to wait. 
Thanks!

**Comment by ciconia** [comment]
I'd like to add to this question: in the case of highly dynamic applications, say a web server that might need to deal with varying amounts of concurrent connections, what would be the best way to handle changes in demand? If, for example, we setup an io_uring with 1024 entries, and at a certain moment the SQE ring buffer is saturated, what would be the best way to handle this? Is there a way to resize the ring buffers, or is there any other technique that could be employed?

**Comment by chrisvest** [comment]
After the SQEs have been submitted with `io_uring_enter`, the SQEs can be reused for other commands. The kernel can have more operations in flight that the size of the submission ring buffer. The size of the submission buffer is the maximum number of SQEs you can submit in one call - like a max batch size. It's also the max number of SQEs you can put in a single linked chain.

**Comment by ciconia** [comment]
So if I understand correctly, with an io_uring with 1024 entries, I can prepare up to 1024 SQEs before calling `io_uring_submit`? Is there any limit on the number of concurrent ongoing operations on the kernel side? How are completions processed if more than 1024 operations are in flight? Sorry @boxerab for highjacking the issue, I hope this is relevant for you as well :-)

**Comment by isilence** [comment]
> So if I understand correctly, with an io_uring with 1024 entries, I can prepare up to 1024 SQEs before calling `io_uring_submit`? 

Yes, up to 1024. And if the submision succeeds, then you can
submit a bunch of new requests without waiting for completions
of previous ones.

> Is there any limit on the number of concurrent ongoing operations on the kernel side?

No, but you can count it on the userspace side.

> How are completions processed if more than 1024 operations are in flight?

Since IORING_FEAT_NODROP landed, if there is no place in
CQ to add an CQE, it will be delayed until there is place for it.

Note that userspace should be careful about it, as the kernel won't
be automagically notified about freed space in CQ, there should be
sys_io_uring_enter() call to make it happen.

**Comment by isilence** [comment]
> First of all, thank you for making this incredible new feature available - really excited to start using it in my codec project.
> I was wondering what the performance impact is of varying the size of the ring buffer - should I expect to see any difference
> in performance between a 1k vs 16 k size buffer ?

@boxerab, apart from differences of using a bit more memory,
it doesn't matter performance-wise.

**Comment by boxerab** [comment]
thanks a lot, @isilence !  all my questions are answered. Closing.

**Comment by ciconia** [comment]
Thanks everybody, this makes things a lot clearer!
