### ISSUE TITLE
Why cancel* function requires flags?

### ISSUE THREAD

**Issue by CarterLi** [axboe/liburing#21]
Noticed this:

https://github.com/axboe/liburing/blob/2e7d74490387c62eb2f20e536acb9f5ab761d1aa/src/include/liburing.h#L267

Then I found this:

https://git.kernel.dk/cgit/linux-block/tree/fs/io_uring.c?h=for-5.5/io_uring-post#n2353

Is it reserved for future use? I think it's kind of strange and doesn't seem to be useful in my opinion.

**Comment by axboe** [comment]
It's reserved for future use, pretty much the same for all commands. It's to help future proof it. Might not seem useful to you now, but then at some point you need to modify behavior a bit, and without a flag there to do it, you're screwed. Maybe cancel without breaking links? The whole point of the flags is that you don't have a crystal ball and can't predict the future.

**Comment by CarterLi** [comment]
We'd better document it somewhere, as the [man page](https://github.com/axboe/liburing/blob/2e7d74490387c62eb2f20e536acb9f5ab761d1aa/man/io_uring_enter.2#L263) says nothing about the flag.

[io_uring_prep_poll_remove](https://github.com/axboe/liburing/blob/master/src/include/liburing.h#L240) doesn't require a flag, which is inconsistent with other cancel functions.

**Comment by axboe** [comment]
Not sure it makes sense do document, as no flags exist. If at some point a valid flag is added, then yes, I agree it should most definitely get documented.

The poll commands are basically inherited from aio, which explains why there's no flags there. It would be better to have them for consistency, but...
