### ISSUE TITLE
update timeout

### ISSUE THREAD

**Issue by YoSTEALTH** [axboe/liburing#210]
You know how we have `io_uring_prep_timeout` and `io_uring_prep_timeout_remove`, Is there anyway to update timeout without having to remove and create a new?

**Comment by isilence** [comment]
That shouldn't be difficult to add. I'll try it out.

Do you have some interesting use case in mind?

**Comment by YoSTEALTH** [comment]
Current plan is to use it for `ttl`. Say you had an object to expire after x amount of time, some condition changed and you want to update timeout.

I am not really sure how you would reference it with the old timeout? maybe to old `sqe.user_data`?

**Comment by isilence** [comment]
> Current plan is to use it for `ttl`. Say you had an object to expire after x amount of time, some condition changed and you want to update timeout.

Got it, may be useful

> I am not really sure how you would reference it with the old timeout? maybe to old `sqe.user_data`?

Right, `sqe.user_data` is consistent with how `io_uring_prep_timeout_remove()` does it.

**Comment by YoSTEALTH** [comment]
> Got it, may be useful

If you think of a higher level usage ``event -> http -> ttl -> cookie -> session -> login`` now you have a function like `io_uring_prep_timeout_update()` being highly used.

Every small function added to liburing/io_uring makes a huge difference elsewhere.

> Right, sqe.user_data is consistent with how io_uring_prep_timeout_remove() does it.

cool

**Comment by YoSTEALTH** [comment]
@isilence just curios any update on this?

**Comment by isilence** [comment]
@YoSTEALTH, I wrote a patch a month ago, just haven't covered it enough with tests.

**Comment by isilence** [comment]
kernel + liburing patches
https://lore.kernel.org/io-uring/cover.1606669225.git.asml.silence@gmail.com/T/#t
https://lore.kernel.org/io-uring/cover.1606670836.git.asml.silence@gmail.com/T/#t

**Comment by YoSTEALTH** [comment]
@isilence  Thank you very much for adding this feature.

Currently I am on Linux `5.9.11` is there anyway you can upload `io_uring` patch into `5.9.12` or `5.9.13` release? That way I can test it.

**Comment by isilence** [comment]
Let me clarify, do you want these patches backported to 5.9 (not-upstreamed) so you can apply them, build a new kernel and test?
Because for official releases it's for 5.11, not earlier.

**Comment by YoSTEALTH** [comment]
@isilence Currently `5.11` is not available at https://www.kernel.org/ I can test in `5.9` or `5.10`

**Comment by isilence** [comment]
@YoSTEALTH, ah, just take linux-next. Current one is 5.10, so next is going to be 5.11

**Comment by YoSTEALTH** [comment]
@isilence Doesn't look like `5.11` is out, maybe next week! I would rather not break my system, will just wait

**Comment by isilence** [comment]
Makes sense. Need to say that "rc" means that it's still in
development and may contain bugs, so 5.10 is not yet out
as well (but will be soon).

**Comment by YoSTEALTH** [comment]
@isilence so I finally got to install Linux `5.11` and initial `io_uring_prep_timeout_update` test case does pass.

**Comment by YoSTEALTH** [comment]
Could something in `io_urinig_prep_timeout*` functions be making `io_uring_prep_send` to hang?

**Comment by YoSTEALTH** [comment]
Going to close this as everything seems to be working, If there is anymore issues will reopen. Thank you @isilence @axboe
