### ISSUE TITLE
How do I flush all in flight requests ?

### ISSUE THREAD

**Issue by boxerab** [axboe/liburing#211]
Suppose I have made 10 write submissions, and now it is time to close the file.
If I just call ` io_uring_queue_exit(&ring);`, then the file is corrupt. How can I ensure
that all writes have been flushed to disk before I exit ?

**Comment by YoSTEALTH** [comment]
Not sure why the files would be corrupt, are you not waiting for the `cqe`? None the less there is `io_uring_prep_fsync` you can use.

**Comment by boxerab** [comment]
@YoSTEALTH thanks, by corrupt, I meant that not all writes complete before the file is closed. I looked into `io_uring_prep_fsync`;
is there a blocking call that guarantees that all in flight writes are complete before I close the file ?

**Comment by CarterLi** [comment]
https://github.com/axboe/liburing/blob/73250a069ffac8bf41754aac2f99f6ce94f4c862/src/include/liburing.h#L103

**Comment by YoSTEALTH** [comment]
@boxerab I am not sure why you are closing the file before the writes are done! If you have the code online or can post here, maybe people can give you better advise.

**Comment by boxerab** [comment]
@YoSTEALTH thanks, here is my work flow:

1. start program
1. process 1 MB of data
1. submit 1 MB write
1. process 1 MB data
1. submit write
1. exit program

So, before I exit, I want to flush all remaining writes.  I currently run `fsync`, then `io_uring_queue_exit`, then `close`.

This still leaves some unflushed bytes.

**Comment by chrisvest** [comment]
You could issue an `IORING_OP_FSYNC` with `IOSQE_DRAIN` (so it'll run _after_ all prior writes have completed), and then wait for that to complete before exiting and closing the ring.

**Comment by boxerab** [comment]
ok, sorry guys!! a bug in my code - I was passing a buffer from the stack  to `io_uring`, when I should have been allocating one on the heap.

**Comment by YoSTEALTH** [comment]
@boxerab  after you "submit write" you have to
- wait for entry to complete `io_uring_wait_cqe()`
- then you have to use `io_uring_cqe_seen()` to clear the old entry

I can't think of good C example I can link, if you can read Python this is a simple example https://github.com/YoSTEALTH/Liburing/blob/master/example/open_write_read_close.py

**Comment by boxerab** [comment]
Thanks, @YoSTEALTH .

Here is what I am using:


```
int process_completion(struct io_uring *ring) {
    struct io_uring_cqe *cqe;
    int ret = io_uring_wait_cqe(ring, &cqe);

    if (ret < 0) {
        perror("io_uring_wait_cqe");
        return 1;
    }

    if (cqe->res < 0) {
        /* The system call invoked asynchonously failed */
        return 1;
    }

    /* Retrieve user data from CQE */
    io_data *data = (io_data*)io_uring_cqe_get_data(cqe);
    delete[] (uint8_t*)data->iov.iov_base;
    delete data;
    /* process this request here */

    /* Mark this completion as seen */
    io_uring_cqe_seen(ring, cqe);
    return 0;
}
```

**Comment by boxerab** [comment]
Thanks everyone - problem solved. 
Closing this.

**Comment by boxerab** [comment]
Hopefully these details are in the documentation somewhere ?
