### ISSUE TITLE
IORING_OP_RECVMSG fails when msg_control is set

### ISSUE THREAD

**Issue by romange** [axboe/liburing#220]
`struct msghdr` has `msg_control` and `msg_controllen` fields that could be set before calling `recvmsg()`. 
`recvmsg` returns successfully with those fields set. 

`IORING_OP_RECVMSG`, on the other hand fails with `22/Invalid argument`.

To reproduce, see https://github.com/romange/liburing/commit/fd9c810c6cf6c73c7f3b27aacf144a229ee56313

**Comment by axboe** [comment]
This is known, cmsg is currently disabled through io_uring. This will be relaxed or 5.10.

**Comment by isilence** [comment]
Do we really need this? Is there a user for whom SCM*
are performance critical?

I guess they would require one by one handling in io_uring
with a swtich or something and would need extra resources.
->files for SCM_RIGHTS who knows what else for others.

**Comment by axboe** [comment]
Taking a closer look, I don't think we do.

**Comment by isilence** [comment]
#128, but don't know their use case and how critical to do that via io_uring.

**Comment by axboe** [comment]
I don't think we need it for SCM_RIGHTS, I don't view that as performance critical. But other uses cases of cmsg are useful and we do need, like MSG_ERRQUEUE. I'd be quite content to leave SCM_RIGHTS disabled forever.

**Comment by axboe** [comment]
https://git.kernel.org/pub/scm/linux/kernel/git/netdev/net-next.git/commit/net/socket.c?id=583bbf0624dfd8fc45f1049be1d4980be59451ff

**Comment by romange** [comment]
I wanted to use cmsg in order to timestamp RX packets and to see how much my application layer/io_uring contributes to the latency tail.

**Comment by axboe** [comment]
Closing this one
