### ISSUE TITLE
API to check for capabilities

### ISSUE THREAD

**Issue by rch0wdhury** [axboe/liburing#222]
Hi,
While replacing aio with io_uring, I am finding it increasingly useful to have an API that can be used to discover io_uring capabilities supported by the kernel being used. For example, these capabilities come to mind -

io_uring available
WQ sharing available
non-root IOPOLL available
etc.

This will help write applications that can query the capabilities and use features as needed or fall back to libaio.

Is this something that sounds interesting and/or viable?

**Comment by YoSTEALTH** [comment]
https://unixism.net/loti/tutorial/probe_liburing.html

**Comment by rch0wdhury** [comment]
Thanks! Should have searched better. Closing the discussion.
