### ISSUE TITLE
user_data unsigned long

### ISSUE THREAD

**Issue by YoSTEALTH** [axboe/liburing#224]
Something odd is going on while
``sqe->user_data = 18446744073709551615;`` it seems to hang
``sqe->user_data = 18446744073709551615 - 1;`` it works
`unsigned long` should support `18446744073709551615` in 64bit system right?

Also someone said https://github.com/axboe/liburing/blob/master/src/include/liburing.h#L185 should be ``sqe->user_data = *((unsigned long*)data);``

**Comment by CarterLi** [comment]
18446744073709551615 equals to `LIBURING_UDATA_TIMEOUT`, which is reserved for liburing internal use.

https://github.com/axboe/liburing/blob/1a02de422f3c9818869eec85081bb790efddedbe/src/queue.c#L197

**Comment by CarterLi** [comment]
> Also someone said https://github.com/axboe/liburing/blob/master/src/include/liburing.h#L185 should be `sqe->user_data = *((unsigned long*)data);`

No, it of course shouldn't.

**Comment by CarterLi** [comment]
I suggest that you should have some basic knowledge of C then file any issues here.

**Comment by YoSTEALTH** [comment]
> 18446744073709551615 equals to `LIBURING_UDATA_TIMEOUT`, which is reserved for liburing internal use.

O right, Thanks for pointing this out. I forgot about `LIBURING_UDATA_TIMEOUT`. The numbers were generated dynamically so I didn't make the connection.
