### ISSUE TITLE
A question：Does the LVM support io_ring IOPOLL?

### ISSUE THREAD

**Issue by chenxuqiang** [axboe/liburing#227]
Recently，I tested io_uring `IOPOLL` on an **LVM device**. However, the submitted request cannot be completed, and the program is always blocked in the `io_uring_cqe_wait()` function. So I want to ask whether the LVM supports io_ring IOPOLL。

**Comment by axboe** [comment]
Not yet, some folks are working on it though. This isn't an io_uring/liburing deficiency, it's the driver in the kernel lacking support.
