### ISSUE TITLE
ABI breakage in 0.7 due to new kflags member in io_uring_cq

### ISSUE THREAD

**Issue by guillemj** [axboe/liburing#228]
Hi!

Steinar H. Gunderson has reported in Debian (https://bugs.debian.org/972758) that the 0.7 release broke the ABI in commit 0f0517331307605e576b3492c93dc4988e06fdc0 when adding the kflags member to struct io_uring_cq. I think at this point the best way forward might be to just quickly release 2.0 and request any downstream to avoid 0.7 and package that instead?

**Comment by axboe** [comment]
Oops yes, that is unfortunate. As 0.7 is 3 months old, it's definitely out there. I guess people just recompiled, I hadn't heard any complaints.

In any case, I don't think we need to be quick on the next release, we're already more than 3 months into this. For 2.0, at least the padding is there for future cases.

**Comment by axboe** [comment]
> I hadn't heard any complaints.

Should clarify, before this one :-)
