### ISSUE TITLE
add support for connect(2)

### ISSUE THREAD

**Issue by some-coder366** [axboe/liburing#23]

**Comment by axboe** [comment]
See:

https://lore.kernel.org/io-uring/20191123212709.4598-1-axboe@kernel.dk/T

and

https://git.kernel.dk/cgit/linux-block/log/?h=for-5.5/io_uring-post

(top two patches). Please test it!

**Comment by axboe** [comment]
I'm closing this as it's supported, I would however appreciate if you actually test it.
