### ISSUE TITLE
arch supports?

### ISSUE THREAD

**Issue by JsBlueCat** [axboe/liburing#231]
i try your lib in linux it works. how about the support in windows , mac ?

**Comment by isilence** [comment]
This library is a wrapper around a new Linux kernel ABI, so unless win/mac
to adopt the ABI, that doesn't look realistic, it won't work. IMHO, it's up
to higher level libraries/applications to use either liburing or some other
native interface supported by your OS.

Also, there always may be someone willing to write a library to [try to]
emulate the ABI for win/mac, it most probably wouldn't be as effecient as it
should be, so I don't see it happening.
