### ISSUE TITLE
io_uring_prep_timeout count

### ISSUE THREAD

**Issue by YoSTEALTH** [axboe/liburing#232]
What exactly is `count` in `io_uring_prep_timeout`?
```C
static inline void io_uring_prep_timeout(struct io_uring_sqe *sqe,
                     struct __kernel_timespec *ts,
                     unsigned count, unsigned flags)
{
    io_uring_prep_rw(IORING_OP_TIMEOUT, sqe, -1, ts, 1, count);
    sqe->timeout_flags = flags;
}
```
Is it count of `ts`? Is it index of `ts`? Wait for something if `IOSQE_IO_LINK` is used? In test there are ``0`` value used for `count`, its not clear.

**Comment by isilence** [comment]
Apart from working as a normal timeout, `IORING_OP_TIMEOUT` also fires after `count` requests completed (i.e. new `count` CQEs appeared) after the timeout's submission. If `count` is 0 this is disabled. Don't know what was the use case, but that's how it is.

**Comment by CarterLi** [comment]
The history:

* https://github.com/axboe/liburing/issues/4
* https://github.com/axboe/liburing/issues/18

The (only) usage:

* https://github.com/axboe/liburing/blob/master/src/queue.c#L245

The future:

* <https://lore.kernel.org/io-uring/1604307047-50980-1-git-send-email-haoxu@linux.alibaba.com/T/#t>

**Comment by YoSTEALTH** [comment]
O i c, For normal timeout (sleep, ttl) I had the `count` set to `1` thinking it was number of `ts` and I was getting weird behaviorism for months now. It would work, then not work, not knowing what was causing this weird behavior!

Anyways... some of these function could sure use documentation. As an outsider using these function would have no clue what they mean/do.

**Comment by CarterLi** [comment]
It's documented here: https://github.com/axboe/liburing/blob/master/man/io_uring_enter.2#L309

I don't know if `io_uring_prep_timeout` is documented, but you'd better look for the document of io_uring_enter, since it's updated more often.

**Comment by axboe** [comment]
As Carter says, the 'count' is documented in the man pages shipped with liburing. liburing doesn't have a set of full man pages yet just for itself, hopefully that'll happen at some point...

**Comment by YoSTEALTH** [comment]
I had read the `IORING_OP_TIMEOUT` docs though it wasn't clear to me, sorry.

I think timeout is a really useful feature to have and has many use-case.

How about if the function was split into `io_uring_prep_timeout` & `io_uring_prep_timer`? This way 2 feature can be separated and it could lessen the confusion for future users
