### ISSUE TITLE
what the aim of this lib ?

### ISSUE THREAD

**Issue by JsBlueCat** [axboe/liburing#235]
is it a socket lib?
can we use it to accelerate the write process of big file ?

**Comment by YoSTEALTH** [comment]
It allows for asynchronous(non-blocking) IO(input/output)

Up until now file io would block the process/thread running it till files task completed. Only way to do asynchronously file io was to open new thread to handle the task. With `io_uring` you don't have to open new thread to handle file io anymore, you can do multiple non-blocking file io task in a single process/thread.

This is not limited to files, you can do socket and other type of IO as well, all in a single interface.

I would really recommend watching https://www.youtube.com/watch?v=-5T4Cjw46ys

**Comment by JsBlueCat** [comment]
> It allows for asynchronous(non-blocking) IO(input/output)
> 
> Up until now file io would block the process/thread running it till files task completed. Only way to do asynchronously file io was to open new thread to handle the task. With `io_uring` you don't have to open new thread to handle file io anymore, you can do multiple non-blocking file io task in a single process/thread.
> 
> This is not limited to files, you can do socket and other type of IO as well, all in a single interface.
> 
> I would really recommend watching https://www.youtube.com/watch?v=-5T4Cjw46ys

can we use four Queues in four threads?  is the aio comcapt with thread?
