### ISSUE TITLE
Easier way to track patchsets to kernel?

### ISSUE THREAD

**Issue by Qix-** [axboe/liburing#236]
Hey Jens,

I'm finding a number of patch requests to the kernel that I'd like to test in a custom Arch build, for example [the changes that improve the SQPOLL situation and add support for `CAP_SYS_NICE`, etc.](https://www.spinics.net/lists/io-uring/msg04073.html) - is there an easier way to find a list of those patches? Do you have a public fork of the kernel I could be checking?

Thanks in advance!

**Comment by axboe** [comment]
Generally everything I have queued up for the next release is in for-x.yy/io_uring - right now that would be for-5.11/io_uring. That should cover most of the stuff posted, unless it hasn't been reviewed/tested and added yet. The patch you mention is in there. So just pull:

```git://git.kernel.dk/linux-block for-5.11/io_uring```

into 5.9 or current -git, and build that.

**Comment by Qix-** [comment]
Awesome, thanks for the quick response :) That's exactly what I needed.
