### ISSUE TITLE
Can this library be used with a tun device?

### ISSUE THREAD

**Issue by jawline** [axboe/liburing#239]
I've been trying to use liburing to read from a tun device. Normally after setting up a file descriptor to the tun I can pull packets with a call to read. Whenever I try to read with prep_read I get error -22 (EINVAL) from the read operation. Where previously I had 

`return read(tun_fd, buf, count);`

I am now trying to queue reads with

```
  struct io_uring_sqe *sqe = io_uring_get_sqe(&tundev->ring);

  if (!sqe) {
    // Can't read if there's no read space available
    printf("No read space");
    abort();
  }

  io_uring_prep_read(sqe, tundev->tun_fd, data_buffer, 2048, 0);
  io_uring_sqe_set_data(sqe, data_buffer);
```
Here, the result of the read always ends up as -22 (EINVAL). Is this due to incompatibility or am I just using liburing incorrectly? I have left my read and setup code below as reference.

```
ssize_t read_from_tun(int event_fd, void *buf, size_t count) {
  struct io_uring_cqe *cqe;
  int ret = io_uring_peek_cqe(&tundev.ring, &cqe);
  if (ret != 0) {
    if (ret == -EAGAIN) {
      return -1;
    }
    return -1;
  }
  void* ring_buf = io_uring_cqe_get_data(cqe);
  ssize_t read_bytes = cqe->res;
  if (read_bytes < 0 && read_bytes != EAGAIN && read_bytes != EWOULDBLOCK) {
    read_bytes = 0;
    goto requeue;
  }
  memcpy(buf, ring_buf, read_bytes);
requeue:
  io_uring_cqe_seen(&tundev.ring, cqe);
  queue_read(&tundev, ring_buf);
  return read_bytes;
}
```

```
int create(struct tun_state *tundev, int tun_fd) {
  tundev->tun_fd = tun_fd;
  tundev->event_fd = eventfd(0, 0);
  if (tundev->event_fd < 0) {
    return -1;
  }
  if (io_uring_queue_init(128, &tundev->ring, 0) != 0) {
    return -1;
  }
  if (io_uring_register_eventfd(&tundev->ring, tundev->event_fd) != 0) {
    return -1;
  }
  for (size_t i = 0; i < 128; i++) {
    void* data_buffer;
    if (posix_memalign(&data_buffer, 2048, 2048) != 0) {
      return -1;
    }
    queue_read(tundev, data_buffer);
  }
  io_uring_submit(&tundev->ring);
}
```

**Comment by jawline** [comment]
Some additional data, if the file descriptor is in non-blocking mode then I repeatedly get EAGAIN (but never anything other than EAGAIN) from the tun device.

If the file descriptor is in blocking mode then the first call to io_uring_submit(...) blocks forever.

**Comment by axboe** [comment]
Looks like a bug in tun, it's not honoring IOCB_NOWAIT:

https://lore.kernel.org/netdev/e9451860-96cc-c7c7-47b8-fe42cadd5f4c@kernel.dk/

**Comment by jawline** [comment]
Oh wow - thanks so much for replying, I would never have figured that out.

I'll try out your patch and see how it goes.

**Comment by jawline** [comment]
I've just applied your patch to 5.9 and tested, it does seem to solve the blocking issue. Thanks!

Now if I read from the ring and write directly to the tun_fd I can pass data, though my overall throughput does seem to be lower than just using read and write directly.

I now have a an issue with writing using the ring. While reads now work asynchronously if I queue up writes and then execute submit on a timer the ring seems to stall with writes failing to confirm.

Weirdly, if I call io_uring_submit(...) exactly once after each new write rather than on a timer it seems to work. I assume this is likely a case of operator error but can you think of any reason why this would happen? Perhaps something to do with the blocking behaviour, since tun_fd is usually in non blocking mode for writes?

An additional issue: if I enable sqpoll then I get a bad file descriptor error. 

To motivate this work: with mitigations=auto on the current kernel performance of tun using just read/write is reduced by 30-40% at high bandwidths. I speculate a large part of this is just due to the syscalls taking too long since we will often service 40-50 read/writes in a loop with one syscall per packet which is why I was hopefull that io_uring would help. Do you think this is a valid use case?
