### ISSUE TITLE
What is the (inteded) behavior of SQPOLL + timeouts?

### ISSUE THREAD

**Issue by Qix-** [axboe/liburing#240]
Note this question is in the context of using the low-level sycall interface, not liburing specifically.

I can kind of guess that you wouldn't use SQPOLL with timeouts in any meaningful way - I'm trying to figure out a good way to implement async `sleep()`-like timers, which historically (see: epoll) are implemented using a min-heap and poll timeouts, _not_ with something like timerfd.

Since under the SQPOLL mode we do active polling of the completion queue until we receive the flag that the underlying kernel thread has shut down, is there a performant way to "wait" for a completion queue event in this mode? Or is the intended behavior of the userspace application to also perform as-fast-as-possible polling of the completion queue, too?

As per my understanding, in such a case the vDSO provided by the kernel can give us efficient time of day lookups without syscalls, so we can simply cache and check the min-heap's next timeout value against it with minimal overhead, correct? I know we could be using io_uring timeout events for this directly but I'd rather keep the submission queue as free as possible.

Thanks for any insight :)

---

EDIT: one other somewhat related question that the documentation isn't clear about (I've seen conflicting verbiage):

Does the SQPOLL thread shut down (time out) even if there are _in-flight_ submissions? E.g. if I have a long-running operation that completes at a time later than the timeout, will the thread still timeout? In this case, I would have to keep waking up the thread until all of my in-flight requests have been completed, right?

Some of the documentation makes it seem like a submitted event that hasn't yet completed could be "lost" if the kernel polling thread wasn't woken up periodically.

Ideally it would only time out once the number of in-flight submissions reaches zero _and_ there have been no submissions for X amount of time.

EDIT2: Just confirmed that `std::chrono::high_resolution_clock::now()` uses the vDSO values and not a syscall on our system/compiler, so getting that information should be quite cheap.

**Comment by Qix-** [comment]
Doing an `strace` of the sq-poll-kthread test, it appears `io_uring_enter()` is still being called with `GETEVENTS` which goes against my theory above.

It seems like, with SQPOLL, there will always need to be an initial syscall to kick off the kthread upon the first submission, correct? It would be like `IORING_SQ_NEED_WAKEUP` being `1` by default.

Without confirming this is actually the case and not some other mis-use of the low level syscalls on my part, would it be possible to have the kernel automatically populate the sq ring's `flags` with `|= IORING_SQ_NEED_WAKEUP`? Sure it's trivial bookkeeping on our part but it's an easily missed bug.

This would also allow the kernel implementation to move to an automatic thread kickoff in the future with full backwards compatibility, since in a lot of cases a service is going to be called when we know we'll be performing I/O in the very near future (e.g. in systemd socket-driven service initialziation).

**Comment by isilence** [comment]
1. SQPOLL is about polling **S**ubmission **Q**ueues by a kernel thread. Completions are waited as usual.
2. SQPOLL only takes SQ Entries (SQE) from SQ, it doesn't necessarily executes them. E.g. it may throw it for async execution by some other means. SQPOLL is awake if it tries to exeucte a request, but shouldn't be important for users.
3. So, SQPOLL can fall asleep while there are still inflight requests, and that's ok. The requests will complete asynchronously. Regardless of how they executed, they can be waited as usual (see 1.)

> would it be possible to have the kernel automatically populate the sq ring's flags with |= IORING_SQ_NEED_WAKEUP?

4. That what SQPOLL thread do before going to sleep, so users can react. On the user end it's like below

```C
for (...)
    add_new_cqe_into_shared_memory(); // aka into SQ

if (io_uring->flag & IORING_SQ_NEED_WAKEUP) // thread is sleeping, need to wake it up
    io_uring_enter(...);
else
    ; // do nothing, the kthread will find SQEs without extra help
```

> This would also allow the kernel implementation to move to an automatic thread kickoff in the future with full backwards compatibility, since in a lot of cases a service is going to be called when we know we'll be performing I/O in the very near future (e.g. in systemd socket-driven service initialization).

Not sure what you mean, automatic kickoff by whom or by what event?

**Comment by isilence** [comment]
Completion timeouts were historically implemented in liburing by timeout SQEs (i.e. submit SQE, wait CQE).
This approach has its problems, so there is a new API for that queued for 5.11. But again, completion waiting
is not a busy loop/polling by anyone, you call a syscall and it actually sleeps until the right moment.

Another story for **IO**POLL, but you haven't mentioned it.

**Comment by Qix-** [comment]
> That what SQPOLL thread do before going to sleep, so users can react. On the user end it's like below

That's what I'm saying - there needs to be an initial call to `enter` in order to start the submission queue, and by default the `flags` parameter is `0`. In my own testing, the `NEED_WAKEUP` flag is never raised directly after a `setup` syscall - you always have to submit at least one I/O message.

The tests all seem to assume there will be at least one submission before the `NEED_WAKEUP` is checked, but that isn't always going to be the case in more generalized frameworks... By default, you need to wake up the submission thread via an `enter` syscall, right?

Or am I misunderstanding something?

> This approach has its problems, so there is a new API for that queued for 5.11. But again, completion waiting
is not a busy loop/polling by anyone, you call a syscall and it actually sleeps until the right moment.

I see, I don't see how this really solves the syscall problem though. I thought this would be a mode where the entire message passing mechanism is handled via busy polling on both sides and using memory barriers to ensure ordered memory R/W. This would forego all syscalls under heavy load, which I figured was the goal here.

Is there a mode for polling for completions without syscalls, e.g. a CQPOLL mode, planned?

**Comment by axboe** [comment]
> That's what I'm saying - there needs to be an initial call to enter in order to start the submission queue, and by default the flags parameter is 0. In my own testing, the NEED_WAKEUP flag is never raised directly after a setup syscall - you always have to submit at least one I/O message.

It should start out running, then go to sleep (and set ```NEED_WAKEUP``` when it does).

There seems to be some confusion here on what polling is, and how it affects the SQ and CQ ring, so let me try and clarify that a little bit. SQPOLL is asking a thread to poll the SQ ring for events. When it sees them, they are dispatched, and when complete, the post an entry to the CQ ring. There's no CQPOLL mode because it is nonsensical. Either events happen async, in which case you can just poll the CQ ring from userspace (no kernel support needed for that), or you run in ```IOPOLL``` mode, in which case you very much DO want to enter the kernel as it's the application responsibility to poll for and process completions. In other words, a request will either complete async at some point by itself, or it's an ```IOPOLL``` completion which doesn't trigger anything async, it must be handled explicitly.

Hence if you're not doing ```IOPOLL```, then your suggested CQPOLL mode is simply just reading the CQ ring for changes from userspace.

**Comment by isilence** [comment]
> That's what I'm saying - there needs to be an initial call to enter in order to start the submission queue, and by default the flags parameter is 0. In my own testing, the NEED_WAKEUP flag is never raised directly after a setup syscall - you always have to submit at least one I/O message.

So, you're saying that initially it sleeps but doesn't set NEED_WAKEUP. Right?
That's not nice if so, I need to check that

> I see, I don't see how this really solves the syscall problem though. I thought this would be a mode where the entire message passing mechanism is handled via busy polling on both sides and using memory barriers to ensure ordered memory R/W. This would forego all syscalls under heavy load, which I figured was the goal here.
Is there a mode for polling for completions without syscalls, e.g. a CQPOLL mode, planned?

That's userspace, nobody keeps you from polling CQ. Actually liburing first checks if there is anything in the CQ, and may return without doing any syscall.

**Comment by axboe** [comment]
> So, you're saying that initially it sleeps but doesn't set NEED_WAKEUP. Right?

That would most certainly be a bug, of course. We start out running, but the going to sleep is no different than subsequent versions of that. So hard to imagine how that bug would exist and be exclusive to just the initial sleep.

What kernel is being used?

**Comment by axboe** [comment]
Just ran a quick test on my current tree, and it works as described:

```
[root@archlinux liburing]# test/sqpoll-sleep 
Got wakeup after 106 msec
```

This is setting up the ring with 100msec idle period, so we expect the flag to NOT be set initially, then be set sometime after 100 msec. The test exits when it's set, which is right around that time. Test case:

```
#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <sys/time.h>
#include "liburing.h"

static unsigned long long mtime_since(const struct timeval *s,
				      const struct timeval *e)
{
	long long sec, usec;

	sec = e->tv_sec - s->tv_sec;
	usec = (e->tv_usec - s->tv_usec);
	if (sec > 0 && usec < 0) {
		sec--;
		usec += 1000000;
	}

	sec *= 1000;
	usec /= 1000;
	return sec + usec;
}

static unsigned long long mtime_since_now(struct timeval *tv)
{
	struct timeval end;

	gettimeofday(&end, NULL);
	return mtime_since(tv, &end);
}

int main(int argc, char *argv[])
{
	struct io_uring_params p = {};
	struct timeval tv;
	struct io_uring ring;
	int ret;

	if (argc > 1)
		return 0;

	p.flags = IORING_SETUP_SQPOLL;
	p.sq_thread_idle = 100;

	/* Setup the ring with a registered event fd to be notified on events */
	ret = io_uring_queue_init_params(1, &ring, &p);
	if (ret) {
		fprintf(stderr, "queue_init=%d\n", ret);
		return 1;
	}

	gettimeofday(&tv, NULL);
	do {
		usleep(1000);
		if ((*ring.sq.kflags) & IORING_SQ_NEED_WAKEUP) {
			printf("Got wakeup after %ld msec\n", (long)mtime_since_now(&tv));
			goto done;
		}
	} while (mtime_since_now(&tv) < 1000);

	printf("No wakeup in %ld msec\n", (long)mtime_since_now(&tv));
	return 1;
done:
	return 0;
}
```

**Comment by Qix-** [comment]
I'm an idiot, I apologize.

I was casting the result of the first sq offsets `mmap()` call to a `uint32_t*` instead of a `char *` (in c++, since `void*` arithmetic is not allowed). The offset math was being scaled by 4 when setting up the pointers.

For anyone curious, here's the low-level reproduction of the above liburing snippet (which works as expected):

```c
#include <unistd.h>
#include <linux/io_uring.h>
#include <sys/syscall.h>
#include <sys/mman.h>

#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <stdatomic.h>

#define NUM_RING_ENTRIES 64
#define IORING_FEAT_SQPOLL_NONFIXED (1U << 7) /* not defined in system headers */

#define IO_URING_READ_ONCE(var) \
        atomic_load_explicit((_Atomic __typeof__(var) *)&(var), memory_order_relaxed)

int main(void) {
        int status = 1;

        size_t sq_ring_sz;
        void *sq_ring;

        struct io_uring_params params;
        memset(&params, 0, sizeof(params));

        params.flags |= IORING_SETUP_SQPOLL;
        params.sq_thread_idle = 2000;

        int fd = syscall(
                SYS_io_uring_setup,
                NUM_RING_ENTRIES,
                &params
        );

        if (fd == -1) {
                perror("io_uring_setup()");
                goto exit;
        }

        if (!(params.features & IORING_FEAT_SQPOLL_NONFIXED)) {
                fputs("SQPOLL_NONFIXED feature not present", stderr);
                goto exit_close;
        }

        sq_ring_sz = params.sq_off.array + params.sq_entries * sizeof(uint32_t);
        sq_ring = mmap(
                NULL,
                sq_ring_sz,
                PROT_READ | PROT_WRITE,
                MAP_SHARED | MAP_POPULATE,
                fd,
                IORING_OFF_SQ_RING
        );

        if (sq_ring == MAP_FAILED) {
                perror("mmap(IORING_OFF_SQ_RING)");
                goto exit_close;
        }

        uint32_t *sq_flags = (uint32_t *)( sq_ring + params.sq_off.flags );

        while (!(IO_URING_READ_ONCE(*sq_flags) & IORING_SQ_NEED_WAKEUP));

        status = 0;

        munmap(sq_ring, sq_ring_sz);
exit_close:
        close(fd);
exit:
        return status;
}
```

---

Quick note because I know it'll come up:

I understand it's probably best to use liburing where possible but in our case the low-level approach is necessary. Lots of little places where user-error can occur.

Thanks for the information, this cleared a lot of unrelated things up either way. I apologize for the noise.

**Comment by axboe** [comment]
There's no requirement to use liburing, it's just provided as a perhaps more approachable introduction than using the raw interface. So whatever works for you, all good.
