### ISSUE TITLE
sqe_tail appears to assume tail starts at 0 instead of being initialized from sq->ktail

### ISSUE THREAD

**Issue by Qix-** [axboe/liburing#242]
Excuse me if I'm misunderstanding something, but..

1. The ring is `memset()`'d and zeroed, which includes the `sq` member
2. This means `sq->sqe_tail` is initialized to 0
3. `ktail` is initialized to the SQ offset `.tail` value cast to a pointer
4. Upon getting an `sqe` instance, we read from the cached `sqe_tail` value, not (read-barrier) reading from the `ktail` pointer
5. Upon flushing SQE's, we overwrite the `ktail` pointer's value

Is this intended? Is the `.tail` offset's value always zero upon a new uring instance? Is that a documented guarantee?

EDIT: I just realized, this is because we **know** we control the SQE (from userspace) and thus upon initialization the kernel has no submitted events and thus we can start the ring really from anywhere we want, right? Corollary, the assignment from `sqe_tail` -> `sq->ktail` is always unidirectional, right?

**Comment by Qix-** [comment]
Another thing I noticed:

You expect the number of entries to be a power of two in order to enable AND-based modulo arithmetic, only further confirmed by the fact that in the liburing implementation, `sqe_tail` will ultimately overflow and wrap back to 0, which would cause problems if the number of items is not a power of 2.

Is this the rationale behind the manpage notes of the kernel scaling the value to a power of two?

**Comment by axboe** [comment]
> I just realized, this is because we know we control the SQE (from userspace) and thus upon initialization the kernel has no submitted events and thus we can start the ring really from anywhere we want, right? Corollary, the assignment from sqe_tail -> sq->ktail is always unidirectional, right?

Exactly

For the other question, the sizes are guaranteed to always be a power of 2. It's designed such that AND always works, and so that wrapping is safe.
