### ISSUE TITLE
sendmsg/recvmsg return -14 (EFAULT) sometimes with SQPOLL

### ISSUE THREAD

**Issue by ShuochengWang** [axboe/liburing#245]
I write a rust crate to do sendmsg/recvmsg with liburing. My scene is that multithreads use ther same io_uring instance with SQPOLL. To make multithreads use the same io_uring instance, I use one lock for sq and one lock for cq.

I find that, when program run a while, sendmsg/recvmsg will always return -14 (EFAULT). I checked my parameters many times, but I can not find reason, does anyone have an idea ?  thanks

kernel version: 5.9.6
liburing version: latest

**Comment by ShuochengWang** [comment]
I use ftrace to trace the io_uring kernel functions, I find the EFAULT is returned from `static int __io_sq_thread_acquire_mm(struct io_ring_ctx *ctx)` . But I still don't know why it happened....
kernel verison 5.9.6

**Comment by isilence** [comment]
it should happen with SQPOLL when other threads/processes continue to use the instance after the owner/creator exits.
Is that your case?

**Comment by ShuochengWang** [comment]
> it should happen with SQPOLL when other threads/processes continue to use the instance after the owner/creator exits.
> Is that your case?

no, I didn't exit the io_uring in my case. I have two threads to use the the same io_uring instance with mutex lock. Two threads will sendmsg / recvmsg to each other.  Then I meet EFAULT in the middle of the program ( The first few requests are executed successfully, and then all the following requests return EFAULT)

**Comment by isilence** [comment]
I was mentioning not exiting the io_uring, but killing the creator thread itself (exit(), abort() or any other way).  
Anyway it doesn't seem to be what you have. Do you have a reproducer?

**Comment by ShuochengWang** [comment]
> I was mentioning not exiting the io_uring, but killing the creator thread itself (exit(), abort() or any other way).
> Anyway it doesn't seem to be what you have. Do you have a reproducer?

no, the threads are alive.
I have a reproducer, but the thing is a little strange:  My C language program works, but the Rust language pragram with the same logic doesn't work ( EFAULT ),  and I try just wrapper the correct C code in the rust, it still not work....

**Comment by ShuochengWang** [comment]
> I was mentioning not exiting the io_uring, but killing the creator thread itself (exit(), abort() or any other way).
> Anyway it doesn't seem to be what you have. Do you have a reproducer?

Oh, the creator thread itself exit() is existed......
In my case, I have one server thread and one client thread.
At first, there are server thread S and client thread C,   (the io_uring instance is created by S or C, it is not stable)
Then, after several sendmsg/recvmsg, the client thread C will exit() and start a new client thread C2,  (Then I get EFAULT)

The point is, if the io_uring instance is created by C, it will return EFAULT, if the io_uring instance is created by S, it will work successfully, am i understanding correctly？

**Comment by isilence** [comment]
> > I was mentioning not exiting the io_uring, but killing the creator thread itself (exit(), abort() or any other way).
> > Anyway it doesn't seem to be what you have. Do you have a reproducer?
> 
> Oh, the creator thread itself exit() is existed......
> In my case, I have one server thread and one client thread.
> At first, there are server thread S and client thread C, (the io_uring instance is created by S or C, it is not stable)
> Then, after several sendmsg/recvmsg, the client thread C will exit() and start a new client thread C2, (Then I get EFAULT)
> 
> The point is, if the io_uring instance is created by C, it will return EFAULT, if the io_uring instance is created by S, it will work successfully, am i understanding correctly？

Exactly

**Comment by tatetian** [comment]
> > > I was mentioning not exiting the io_uring, but killing the creator thread itself (exit(), abort() or any other way).
> > > Anyway it doesn't seem to be what you have. Do you have a reproducer?
> > 
> > 
> > Oh, the creator thread itself exit() is existed......
> > In my case, I have one server thread and one client thread.
> > At first, there are server thread S and client thread C, (the io_uring instance is created by S or C, it is not stable)
> > Then, after several sendmsg/recvmsg, the client thread C will exit() and start a new client thread C2, (Then I get EFAULT)
> > The point is, if the io_uring instance is created by C, it will return EFAULT, if the io_uring instance is created by S, it will work successfully, am i understanding correctly？
> 
> Exactly.
> note: this restriction is for SQPOLL only, without it should work just fine.

This restriction seems very strange to me. Actually, it sounds more like a bug to me. Is this restriction at the liburing level or the kernel level? Do you have any reference materials that give some explanation?

**Comment by isilence** [comment]
> > Exactly.
> > note: this restriction is for SQPOLL only, without it should work just fine.
> 
> @isilence This restriction seems very strange to me. Actually, it sounds more like a bug to me. Is this restriction at the liburing level or the kernel level? Do you have any reference materials that give some explanation?

Kernel level. SQPOLL thread needs to know which file table (for file based requests),
memory space, etc. to use. Considering that users usually don't even do syscalls (just
writing into shared memory), there is no way for it to know.
Not sure about references, but you may take a look at liburing/man.

**Comment by tatetian** [comment]
> Considering that users usually don't even do syscalls for
> submissions (just writing into shared memory), there is no way for it to know a right
> context to execute from.

@isilence Thanks for the explanation. But it does not really make sense to me. OS resources, from file descriptors to memory mappings, are managed in the units of processes, not threads. A file descriptor won't become invalid simply because the thread that creates it exits; the file descriptor has to be closed explicitly or closed automatically when the owner process terminates.

The process should have provided enough "context" for the kernel SQPOLL thread. I cannot think of any other things that the creator thread of an io_uring instance can offer.

I have looked at every mentioning of "polling" in [the man pages of io_uring](https://manpages.debian.org/unstable/liburing-dev/) and found nothing about the restriction we are discussing here. So how do you know about the restriction (except maybe from experimentation)?

**Comment by isilence** [comment]
On Sat, Dec 5, 2020, 12:59 Tate, Hongliang Tian <notifications@github.com>
wrote:

> Considering that users usually don't even do syscalls for
> submissions (just writing into shared memory), there is no way for it to
> know a right
> context to execute from.
>
> @isilence <https://github.com/isilence> Thanks for the explanation. But
> it does not really make sense to me. OS resources, from file descriptors to
> memory mappings, are managed in the units of processes, not threads. A file
> descriptor won't
>
If there ever would be a notion of a thread in the Linux kernel... It's
possible to alleviate that, eg for mm, but there are certain implementation
problems that make it easier to leave it this way.

> become invalid simply because the thread that creates it exits; the file
> descriptor has to be closed explicitly or closed automatically when the
> owner process terminates.
>
The process should have provided enough "context" for the kernel SQPOLL
> thread. I cannot think of any other things that the creator thread of an
> io_uring instance can offer.
>
> I have looked at every mentioning of "polling" in the man pages of
> io_uring <https://manpages.debian.org/unstable/liburing-dev/> and found
> nothing about the
>
Ok, we need to get it documented then

> restriction we are discussing here. So how do you know about the
> restriction (except maybe from experimentation)?
>
Because I'm developing the kernel side

**Comment by isilence** [comment]
@ShuochengWang, please close the issue if you haven't got
any more questions about this problem.

Somebody may want to create another issue to change that behaviour,
but I can't guarantee that's going ever to happen.

**Comment by ShuochengWang** [comment]
> @ShuochengWang, please close the issue if you haven't got
> any more questions about this problem.
> 
> Somebody may want to create another issue to change that behaviour,
> but I can't guarantee that's going ever to happen.

OK~ thanks a lot
