### ISSUE TITLE
Submit scope of IOSQE_IO_LINK and IOSQE_IO_HARDLINK

### ISSUE THREAD

**Issue by openalmeida** [axboe/liburing#247]
Call `io_uring_submit` 3 times, each time with 1 `SQE` item only, and the flag `IOSQE_IO_LINK` enabled (except the 3rd SQE, expect as link tail), will all 3 `SQE` items still act as one chain ?

Under Python binding of Liburing @YoSTEALTH [repo:YoSTEALTH/Liburing](https://github.com/YoSTEALTH/Liburing), I've found all `SQE` items have to apply in one submit if I want them to be one chain.

If treat each `io_uring_submit` as some kind of Session, e.g. the HTTP Session, did I do something wrong? I've lost the "HTTP Cookie" ?

Or there is no so called "Session" under liburing/io_uring world, turn this Issue to be a Feature Request, please.

**Comment by isilence** [comment]
> Call `io_uring_submit` 3 times, each time with 1 `SQE` item only, and the flag `IOSQE_IO_LINK` enabled (except the 3rd SQE, expect as link tail), will all 3 `SQE` items still act as one chain ?

No, it will 3 separate requests. For SQPOLL it might be submitted as a link, but that's racy.

> Under Python binding of Liburing @YoSTEALTH [repo:YoSTEALTH/Liburing](https://github.com/YoSTEALTH/Liburing), I've found all `SQE` items have to apply in one submit if I want them to be one chain.
> 
> If treat each `io_uring_submit` as some kind of Session, e.g. the HTTP Session, did I do something wrong? I've lost the "HTTP Cookie" ?
> 
> Or there is no so called "Session" under liburing/io_uring world, turn this Issue to be a Feature Request, please.

Think of io_uring as a mean to do send(2), etc., which by itself doesn't have a notion of
seesion. However, the socket it operates on has (e.g. TCP session). That's it, there is
nothing like cookies, sessions, HTTP neither in io_uring nor in liburing.

**Comment by isilence** [comment]
@openalmeida, please don't forget to close issues, if they were solved
