### ISSUE TITLE
Short read handling inconsistency for IOSQE_IO_LINK

### ISSUE THREAD

**Issue by CarterLi** [axboe/liburing#248]
Hi all,

Short read of IORING_OP_READ in a link chain is considered an error, because it
will break READ-WRITE chain, which is good.

The problems are:

1. Short read of IORING_OP_RECV in a link chain is *NOT* considered an error,
which is odd and not consistant with IORING_OP_READ. Is it a bug or by design?

2. Short read of IORING_OP_SPLICE in a link chain is considered an error. It is
consistant with IORING_OP_READ, but not very useful because the link
    1) splice(fd1, NULL, pfd1, NULL, -1, 0)
    2) splice(pfd2, NULL, fd2, NULL, -1, 0)

    is a valid operation since the kernel knows how much data can be read in a pipe.

Any thoughts?

**Comment by openalmeida** [comment]
Short read of IORING_OP_SPLICE in a link chain is considered an error. 
> maybe this is related to the Linux Pipe size limit (65536) ?
> the maximum cqe.res (from splice(pfd2, NULL, fd2, NULL, -1, 0)) I can reach is 65536
> even a large request setuped (splice(fd1, NULL, pfd1, NULL, large, 0) and splice(pfd2, NULL, fd2, NULL, large , 0))
> the last splice operation will return a 65536 cqe.res and return with code -22 which means "EINVAL 22 Invalid argument".
> and it seems splice from pipe to socket is not allowed ?  ref: https://github.com/axboe/liburing/issues/258

ref: https://unix.stackexchange.com/questions/11946/how-big-is-the-pipe-buffer

**Comment by CarterLi** [comment]
> it seems splice from pipe to socket is not allowed

It's allowed and works fine with me.

> maybe this is related to the Linux Pipe size limit (65536)

It doesn't matter.

The motivation of short read handling is to avoid out-of-buffer reading / writing. Even though `splice(fd1, NULL, pfd1, NULL, -1, 0)` spliced less data than user expected, the next `splice(pfd2, NULL, fd2, NULL, -1, 0)` should work fine ( aka. without out-of-buffer reading )

---

`short read handling` 的初衷就是为了避免缓冲区越界读写。

举例说明：

1. `splice(fd1, NULL, pfd1, NULL, -1, 0)`：假如pfd的buffer是65536，而fd1里的数据有1000000可读，那么最终是有65536的数据被写入pfd(1)里，这里返回cqe.res=65536
1. `splice(pfd2, NULL, fd2, NULL, -1, 0)`：现在pfd(2)有65536的数据可读，尽管用户要求读-1的数据，但是pfd(2)是个文件描述符，系统知道pfd(2)只有65536的数据，所以最终只会将65536的数据写入人fd2里。

没有缓冲区越界读写。这和 `RECV-SEND` 不一样

1. `recv(sockfd1, buf, 512, 0)`：假如sockfd1只有100数据可读，那么最终有100的数据写入buf
1. `send(sockfd2, buf, 512, 0)`：用户要求将512的数据写入sockfd2，但是buf里面只有100的数据可读。请注意这里buf是用户申请的内存区域，内核不知道buf里面到底有多少数据可读，所以操作系统只能忠实的把512的数据写入sockfd2。于是后面412的数据都是垃圾。

**Comment by openalmeida** [comment]
> 所以我期望的是如果RECV实际读的数据（100）比用户期望（512）少，这时就应该将整个IOSQE_IO_LINK链断掉。但是现在并没有

1. 就描述看，貌似是bug啊。
2. 多唠几句，你用的是自己构造的buf吗？能用linux的pipe代替吗？貌似pipe不会获取后面的“垃圾”，因为pipe没有“先全0填充”这样的机制，是有含量语义(即填多少，“含量”就是多少，而“容量”只是限制“含量”上限)的。

我用 splice + splice 组成sqe链(flags有设置IOSQE_IO_LINK)，若第一个splice读入的数据少于期望，第一个splice会成功(cqe.res > 0)，第二个splice的cqe.res会返回-125即canceled，***整个链此时断掉：后续sqe不会执行，不过仍然会生成sqe同数量的cqe，只是从第二个cqe开始，获取到的cqe都是canceled的状态。***

recv + send 组成链我没有试过……按道理说IOSQE_IO_LINK确实应该导致断掉才对，所以我怀疑是bug。

如果官方说不是bug，那改逻辑啊，再次安利pipe或者pipe无效的话：分成两次提交sqe，前一次的cqe.res作为后一次的nbytes，但是估计性能感人……不过作为菜鸡，我用io_uring的需求是无阻塞，别的就自我安慰了。

基于我写过的实际例子说明，比如用io_uring实现`cp file1 file2` 这个操作的“断点续传且有进度百分比提示版本”以用于超大文件的“用户友好(慢的一匹)”拷贝，我会不获取file1尺寸(少调用少依赖……)而直接一把梭：只循环操作`file1->splice->pipe, pipe->splice>file2 `来实现。其中2个细节：除非file1尺寸正好整除buf或pipe的大小，否则最后那次循环的第一个splice返回的cqe.res所代表那部分就必然成了“尾巴”，会导致pipe阻塞(因后续splice的cancel导致内容没有被拿走)或buf有“垃圾”的情况，那么补一个操作即可：用pipe就读空(比如提交一个pipe->/dev/null的sqe)避免阻塞或用buf就抛弃且重做(nbytes此时重设为“尾巴”的大小，强行整除)一次上文的循环操作。另一个细节，自然是每次循环的时候记录偏移输出进度百分比，遇到用户阻断则落盘和记录会话以便下次“续传”……

**Comment by CarterLi** [comment]
官方对short read的定义很模糊，[只有这一句话](https://github.com/axboe/liburing/blob/bd0befa63da9724adb61c6e3fbfb56d91c8537c0/man/io_uring_enter.2#L712)

> This means that, eg, a short read will also terminate the remainder of the chain.

> 多唠几句，你用的是自己构造的buf吗？能用linux的pipe代替吗？貌似pipe不会获取后面的“垃圾”，因为pipe没有“先全0填充”这样的机制，是有含量语义(即填多少，“含量”就是多少，而“容量”只是限制“含量”上限)的。

用pipe不就是splice了么

> 我用 splice + splice 组成sqe链(flags有设置IOSQE_IO_LINK)，若第一个splice读入的数据少于期望，第一个splice会成功(cqe.res > 0)，第二个splice的cqe.res会返回-125即canceled，整个链此时断掉：后续sqe不会执行，不过仍然会生成sqe同数量的cqe，只是从第二个cqe开始，获取到的cqe都是canceled的状态。

其实还有个IOSQE_IO_HARDLINK可以用，只不过用了这个HARDLINK之后其他报错也不会中断LINK

**Comment by openalmeida** [comment]
用pipe不就是splice了么
> 对啊，uring的奥义是零拷贝，貌似pipe就是内核提供的暂存区域
> 如果不用pipe，而传递自己造的buf句柄去暂存，
> 如果我没理解错，buf是位于用户空间？
> 拉到用户空间的buf……又塞回内核空间，这样uring就没意义了
> 可能你的buf有特殊场景……recv->send这有点像代理服务器，这一般是直接转发。
> 用pipe不是更合适？如果不是代理，那没必要绑一起提交，
> 因为必然有其它逻辑在两次sqe之间需要单独额外处理。

其实还有个IOSQE_IO_HARDLINK可以用，只不过用了这个HARDLINK之后其他报错也不会中断LINK
> 对，hardlink用于打包提交。所以觉得你发现的这个更像是IOSQE_IO_LINK的bug。
> 但是不知为何uring不对比获取和写入数据长度做判断(没看到那里去，看了感觉也啃不明白)。

It's allowed and works fine for me.
> 惭愧，是我自作聪明，非要教off_out做事以为是传了预期偏移……而没有传-1让其自动处理fd_out的偏移造成的
