### ISSUE TITLE
Issue: io_uring_prep_timeout seems use previous submitted timespec as its timespec

### ISSUE THREAD

**Issue by CarterLi** [axboe/liburing#25]
```c
// test.c
#include <liburing.h>
#include <stdio.h>
#include <time.h>

int main() {
    struct io_uring ring;
    io_uring_queue_init(32, &ring, 0);
    printf("0: %ld\n", time(NULL));

{
    struct io_uring_sqe *sqe = io_uring_get_sqe(&ring);
    io_uring_prep_nop(sqe);
    io_uring_submit(&ring);

    struct __kernel_timespec ts = {
        .tv_sec = 10,
        .tv_nsec = 0,
    };
    struct io_uring_cqe *cqe;
    io_uring_wait_cqe_timeout(&ring, &cqe, &ts);
    io_uring_cqe_seen(&ring, cqe);
    printf("1: %ld\n", time(NULL));
}
{
    struct __kernel_timespec ts = {
        .tv_sec = 1,
        .tv_nsec = 0,
    };
    struct io_uring_sqe *sqe = io_uring_get_sqe(&ring);
    io_uring_prep_timeout(sqe, &ts, 0, 0);
    io_uring_submit(&ring);

    struct io_uring_cqe *cqe;
    io_uring_wait_cqe(&ring, &cqe);
    io_uring_cqe_seen(&ring, cqe);
    printf("2: %ld\n", time(NULL));
}

    io_uring_queue_exit(&ring);
    return 0;
}
```

Actual: The last io_uring_prep_timeout waits for 10s

```shell
$ clang test.c -luring -o test
$ ./test 
0: 1575128130
1: 1575128130
2: 1575128140
```

Expect: It should only wait for 1s

```
Linux carter-virtual-machine 5.4.0-999-generic #201911282213 SMP Fri Nov 29 03:17:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

https://kernel.ubuntu.com/~kernel-ppa/mainline/daily/2019-11-29/

**Comment by axboe** [comment]
I'l take a look at this.

**Comment by axboe** [comment]
Can you try 5.5-rc? Just ran your test with current liburing and kernel, and I get:

```
[root@archlinux liburing]# test/carter-timeout 
0: 1575133973
1: 1575133973
2: 1575133974
[root@archlinux liburing]# test/carter-timeout 
0: 1575133977
1: 1575133977
2: 1575133978
[root@archlinux liburing]# test/carter-timeout 
0: 1575133979
1: 1575133979
2: 1575133980
```

I'll try 5.4 as well, might be a missing -stable backport (or something else, don't remember).

**Comment by axboe** [comment]
And on 5.4:

```
[root@archlinux liburing]# test/carter-timeout 
0: 1575134418
1: 1575134418
2: 1575134419
[root@archlinux liburing]# test/carter-timeout 
0: 1575134420
1: 1575134420
2: 1575134421
[root@archlinux liburing]# test/carter-timeout 
0: 1575134422
1: 1575134422
2: 1575134423
```

Maybe try updating liburing?

**Comment by CarterLi** [comment]
Well that's strange.

The kernel I'm using is indeed 5.5, with IO_URING_CONNECT support.

<https://kernel.ubuntu.com/~kernel-ppa/mainline/daily/2019-11-29/> is the newest linux image I can find, and it targets [linux repo head](https://github.com/torvalds/linux/commit/81b6b96475ac7a4ebfceae9f16fb3758327adbfe)

liburing that I'm using is [the latest commit](https://github.com/axboe/liburing/commit/ad2028eaed404bb29be03f400f73ebc04c3d0b9b) of course.

I'll reopen this issue if I find more information.

**Comment by CarterLi** [comment]
Just ran `make runtests`, all tests passed

**Comment by axboe** [comment]
There is a bug here, I looked a bit closer last night. We don't get the 1 second request submitted due to how we add that internal timeout, it just depends on what stack values we get from what I can tell. I'm testing a fix, reopening this one for now.

This is a liburing issue, not a kernel issue.

**Comment by axboe** [comment]
Can you try and use the issue25 branch and see if that works for you? I'm experimenting a bit, this is the current patch:

https://git.kernel.dk/cgit/liburing/commit/?h=issue25&id=6b360ec9b34375eba094c60c54fce3a59e3e5d78

**Comment by axboe** [comment]
Updated: https://git.kernel.dk/cgit/liburing/commit/?h=issue25&id=7ad0e4b2f83c25a996b918585b019afb044acc9f

**Comment by CarterLi** [comment]
I tried it and it worked fine
