### ISSUE TITLE
IORING_SETUP_IOPOLL is supported which kernel version ？

### ISSUE THREAD

**Issue by ArthurZangCN** [axboe/liburing#250]
first， i have a queston : this is supported which kernel version ？
on a centos 8.2 (kernel 5.9.12) , i run test program, result the file empty, but when i call io_uring_queue_init() set flags is 0 , file fill "hello world". the test code:
`#include <liburing.h>
#include <unistd.h>
#include <fcntl.h>
#include <stdio.h>

int main()
{
    struct io_uring ring;
    io_uring_queue_init(32, &ring, IORING_SETUP_IOPOLL);

    struct io_uring_sqe *sqe = io_uring_get_sqe(&ring);
    int fd = open("test.txt", O_WRONLY | O_CREAT);
    struct iovec iov = {
        .iov_base = "Hello world",
        .iov_len = strlen("Hello world"),
    };
    io_uring_prep_writev(sqe, fd, &iov, 1, 0);
    io_uring_submit(&ring);

    struct io_uring_cqe *cqe;

    for (;;) {
        io_uring_peek_cqe(&ring, &cqe);
        if (!cqe) {
            puts("Waiting...");
        } else {
            puts("Finished.");
            break;
        }
    }
    io_uring_cqe_seen(&ring, cqe);
    io_uring_queue_exit(&ring);
}`

**Comment by isilence** [comment]
Check for errors, i.e. cqe->res

Also I have no idea why are you looping instead of waiting with `io_uring_wait_cqe()`.

**Comment by axboe** [comment]
You can't use ```IORING_SETUP_IOPOLL``` with buffered IO. Remove that flag, and I suspect it'll work. But yes, you should be using wait_cqe(), not polled peeking.

**Comment by ArthurZangCN** [comment]
> You can't use `IORING_SETUP_IOPOLL` with buffered IO. Remove that flag, and I suspect it'll work. But yes, you should be using wait_cqe(), not polled peeking.

thanks，but the example does not make it clear the difficult: in my code called io_uring_cqe_get_data(), and get cqe->res is -95 (means 'filesystem/driver/kernel doesn't support polled IO'),  so i want to find why? my program is run on centos8.2(linux 5.9.13), and  nvme disk and bluesfs, please give me some advance, the problem is fs ? driver ? kernel ? thanks.

**Comment by ArthurZangCN** [comment]
> You can't use `IORING_SETUP_IOPOLL` with buffered IO. Remove that flag, and I suspect it'll work. But yes, you should be using wait_cqe(), not polled peeking.

now, i read linux kernel code, find why return -95, in kernel program the file io_uring.c line 2586 (static int io_prep_rw(struct io_kiocb *req, const struct io_uring_sqe *sqe,  bool force_nonblock)):
        `if (ctx->flags & IORING_SETUP_IOPOLL) {
		**if (!(kiocb->ki_flags & IOCB_DIRECT) ||
		    !kiocb->ki_filp->f_op->iopoll)
			return -EOPNOTSUPP;**

		kiocb->ki_flags |= IOCB_HIPRI;
		kiocb->ki_complete = io_complete_rw_iopoll;
		req->iopoll_completed = 0;
	} else {
		if (kiocb->ki_flags & IOCB_HIPRI)
			return -EINVAL;
		kiocb->ki_complete = io_complete_rw;
	}`
so i guess , if we set IORING_SETUP_IOPOLL, we must set sqe rw_flags, if not the option will return -95, is right? if is my guess , please tell me how i set the sqe's rw_flags?

**Comment by isilence** [comment]
> > You can't use `IORING_SETUP_IOPOLL` with buffered IO. Remove that flag, and I suspect it'll work. But yes, you should be using wait_cqe(), not polled peeking.
> 
> thanks，but the example does not make it clear the difficult: in my code called io_uring_cqe_get_data(), and get cqe->res is -95 (means 'filesystem/driver/kernel doesn't support polled IO'), so i want to find why? my program is run on centos8.2(linux 5.9.13), and nvme disk and bluesfs, please give me some advance, the problem is fs ? driver ? kernel ? thanks.

I get that return codes are not always obvious, but at least it gives us a bit of a context to figure out the problem.

**Comment by isilence** [comment]
> > You can't use `IORING_SETUP_IOPOLL` with buffered IO. Remove that flag, and I suspect it'll work. But yes, you should be using wait_cqe(), not polled peeking.
> 
> now, i read linux kernel code, find why return -95, in kernel program the file io_uring.c line 2586
> 
> so i guess , if we set IORING_SETUP_IOPOLL, we must set sqe rw_flags, if not the option will return -95, is right? if is my guess , please tell me how i set the sqe's rw_flags?

```C
io_uring_prep_writev(sqe, ...);
sqe->rw_flags |= IOCB_DIRECT;
```

**Comment by axboe** [comment]
That isn't correct. IOCB_DIRECT is set automatically if the file is opened with O_DIRECT, the latter being a prerequisite for polled IO. It isn't the right namespace either, ->rw_flags takes RWF_* flags.

**Comment by axboe** [comment]
In general, for polled IO to work, the following must be satisfied:

- The file must be opened with O_DIRECT, polled IO isn't supported for buffered IO
- The file system must support it (if a file system is used)
- The block device must support it

All of these must be met in order for polled IO to work, otherwise the first attempt will be errored.

**Comment by isilence** [comment]
> That isn't correct. IOCB_DIRECT is set automatically if the file is opened with O_DIRECT, the latter being a prerequisite for polled IO. It isn't the right namespace either, ->rw_flags takes RWF_* flags.

Thanks for correcting it, seems I need to sleep more.
