### ISSUE TITLE
possibly broken connect with link_timeout 

### ISSUE THREAD

**Issue by romange** [axboe/liburing#255]
Please take a look here: https://github.com/axboe/liburing/pull/254

I created scenario where a connect call should block (if we put a regular blocking connect it hangs).

When using `io_uring_prep_connect` followed up by `io_uring_prep_link_timeout` we get `ECANCELED` but according to documentation ETIME is expected.

**Comment by isilence** [comment]
Thanks for the test! I commented out in a review what's wrong, but in short a linked timeout generate an CQE with `cqe->res` stating what happened, e.g. `-ETIME` for fired timeout. Or, you may be interested in `io_uring_wait_cqe_timeout()` which sets not a per-request timeout, but per-wait. This one IIRC returns result directly

**Comment by romange** [comment]
Thanks, I totally misunderstood how link timeout works. 
@axboe Do you prefer to add my (fixed) test  to the suite or you prefer to close https://github.com/axboe/liburing/pull/254

**Comment by isilence** [comment]
On Thu, Dec 10, 2020, 11:23 Roman Gershman <notifications@github.com> wrote:

> Thanks, I totally misunderstood how link timeout works.
> @axboe <https://github.com/axboe> Do you prefer to add my (fixed) test to
> the suite or you prefer to close #254
> <https://github.com/axboe/liburing/pull/254>
>

That's a good test, let's keep it. One moment is that I don't know how you
delay connect, could you give a clue?

**Comment by romange** [comment]
Sure, I've setup a listening socket with `backlog=0` which allows exactly one client to be connected immediately (to get to the accept queue). Since we do not accept anything, all the next are kept in linux SYN-queue - the kernel does not ACK these connections so they keep sending SYN underneath with exponential backoff. From client's perspective it looks like a blocked connection.  Here is better explanation: http://veithen.io/2014/01/01/how-tcp-backlog-works-in-linux.html :)

**Comment by isilence** [comment]
TIL, thanks
