### ISSUE TITLE
IORING_FEAT_SQPOLL_NONFIXED in Linux  5.10.0-051000-generic #202012132330

### ISSUE THREAD

**Issue by wapxmas** [axboe/liburing#259]
Hi!

A manual for io_uring_setup says "The presence of this feature can be detected by
              the  IORING_FEAT_SQPOLL_NONFIXED  feature flag.  In version **5.10** and later, it is no
              longer necessary to register files to use this feature. **5.10** also allows using  this
              as non-root, if the user has the CAP_SYS_NICE capability."

Is it still so?

I've checked params returned from io_uring_queue_init_params and it says that Linux kernel 5.10.0-051000 lacks this feature.

Thanks.

**Comment by axboe** [comment]
This will be true from 5.11, the feature wasn't pushed for 5.10 after all.

**Comment by axboe** [comment]
Also see the pull request I just sent out for 5.11:

https://lore.kernel.org/io-uring/917fc381-ae7d-bd35-1b4e-fc65f338b84c@kernel.dk/T/#u

**Comment by wapxmas** [comment]
Thanks!
