### ISSUE TITLE
Issue: io_uring_prep_connect always returns -EINPROGRESS

### ISSUE THREAD

**Issue by CarterLi** [axboe/liburing#26]
```c
// connect.c
#include <liburing.h>
#include <stdio.h>
#include <netdb.h>
#include <sys/socket.h>
#include <unistd.h>

int main() {
    struct addrinfo hints = {
        .ai_family = AF_UNSPEC,
        .ai_socktype = SOCK_STREAM,
    }, *addr;

    if (getaddrinfo("github.com", "http", &hints, &addr) < 0) {
        return 1;
    }
    int clientfd = socket(addr->ai_family, addr->ai_socktype, addr->ai_protocol);
    if (clientfd < 0) return 2;

#ifndef USE_PLAIN_CONNECT
    struct io_uring ring;
    io_uring_queue_init(32, &ring, 0);

    struct io_uring_sqe *sqe = io_uring_get_sqe(&ring);
    io_uring_prep_connect(sqe, clientfd, addr->ai_addr, addr->ai_addrlen);
    io_uring_submit(&ring);

    struct io_uring_cqe *cqe;
    io_uring_wait_cqe(&ring, &cqe);
    io_uring_cqe_seen(&ring, cqe);
    int ret = cqe->res;

    io_uring_queue_exit(&ring);
#else
    int ret = connect(clientfd, addr->ai_addr, addr->ai_addrlen);
#endif

    printf("%d\n", ret);
    close(clientfd);
    return 0;
}
```

```shell
$ clang connect.c -luring -o connect && ./connect
-115
$ clang connect.c -luring -o connect -DUSE_PLAIN_CONNECT && ./connect
0
$ uname -a
Linux carter-virtual-machine 5.4.0-999-generic #201911282213 SMP Fri Nov 29 03:17:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by CarterLi** [comment]
And a suggestion: implement io_uring_getaddrinfo in liburing.

We now have io_uring_prep_connect but getaddrinfo is still blocking. getaddrinfo_a exists but it's purely implemented using userland threadpool and doesn't seem integrating with io_uring well.

Implementing getaddrinfo using io_uring should be very useful for programs using liburing for main event loop, if possible.

**Comment by axboe** [comment]
It's known that it will return -EINPROGRESS, you then (currently) need to poll for it to be writeable. I'll look into making io_uring handle this case next week.

No plans for getaddrinfo(), but I'll happily take patches.

**Comment by axboe** [comment]
Queued up: https://lore.kernel.org/io-uring/36e61a79-8e7c-e869-99d3-eaafdd6ad63d@kernel.dk/T/#u

**Comment by ioquatix** [comment]
Was any progress made adding `getaddrinfo` to `io_uring`? It would be exceptionally useful.

**Comment by isilence** [comment]
It's not planned because it's not a single operation but a complex beast reading files, exchanging messages, etc.
IMHO, as it's not a single operation it fundamentally doesn't fit liburing, but implementing under some framework
on-top would be more viable.
