### ISSUE TITLE
Question regarding performant use of IORING_REGISTER_FILES_UPDATE inplace

### ISSUE THREAD

**Issue by goldsteinn** [axboe/liburing#267]
See edit.
I have not read the source code for this. So if that is a prerequisite for a question type issue feel free to close.

Regarding IORING_REGISTER_FILES_UPDATE what are the performance implications of updating the entire array inplace whenever you want to add file descriptors? Will this be vastly more expensive than a memmove (e.g blocking all IO for some fairly expensive registration computation)?

If so, assuming you can try and localize updates to a tight change, will this allow IO to continue on all file descriptor indexes outside of the update range? Or is there some chunk size for locking (e.g every N file descriptors in the array are synchronized together)? Or is IORING_REGISTER_FILES_UPDATE guranteed to shutdown all processing during the registration (but it still can be beneficial to try and minimize the range to reduce the time of the shutdown)?

Thank you!

Edit: read through some of the source. Seems re-updating non -1 files will be quite expensive. 
Out of curiosity is there anything that would prevent https://github.com/torvalds/linux/blob/master/fs/io_uring.c#L7882 from first checking if fd corresponds to the file already at the index?

**Comment by isilence** [comment]
> Regarding IORING_REGISTER_FILES_UPDATE what are the performance implications of updating the entire array inplace whenever you want to add file descriptors? Will this be vastly more expensive than a memmove (e.g blocking all IO for some fairly expensive registration computation)?

A couple of atomics + allocations + retpolines + background work per entry, so yes it should be much more expensive than memmove, but still linear and bearable.

> Edit: read through some of the source. Seems re-updating non -1 files will be quite expensive.
> Out of curiosity is there anything that would prevent https://github.com/torvalds/linux/blob/master/fs/io_uring.c#L7882 from first checking if fd corresponds to the file already at the index?

fd may point to a different file at the call moment, so at least fget() which is expensive enough comparing to copying 4 bytes. How about -2 for "just ignore these entries" or something similar? Should make sense if you're updating a large range but e.g. you know that every second fd is good.

**Comment by goldsteinn** [comment]
As in if fd[idx] == -2 keep previous fd at that index? That would be awesome :)

What do you mean by "you know that every second fd is good"?

**Comment by isilence** [comment]
> As in if fd[idx] == -2 keep previous fd at that index? That would be awesome :)

Yep, to skip this entry during update. I'll hack it up, maybe this weekend.

> What do you mean by "you know that every second fd is good"?

I was thinking about a case when you have quite a large range of fds, and many of them are "good" from the application point in terms that you don't need to update them. Then the only option would be to issue update (i.e. IORING_REGISTER_FILES_UPDATE) many times avoiding these "good" requests. I guess that's what you have.

**Comment by goldsteinn** [comment]
> I was thinking about a case when you have quite a large range of fds, and many of them are "good" from the application point in terms that you don't need to update them. Then the only option would be to issue update (i.e. IORING_REGISTER_FILES_UPDATE) many times avoiding these "good" requests. I guess that's what you have.

I see. Makes sense. 

I was actually writing over fds to avoid syscall overhead (i.e replace fd[idx] with fd[idx]) if I couldnt find a range of -1s. Do you think I would be better off interleaving?

**Comment by isilence** [comment]
> I was actually writing over fds to avoid syscall overhead (i.e replace fd[idx] with fd[idx]) if I couldnt find a range of -1s. Do you think I would be better off interleaving?

Like repacling it but with the same file descriptor? It's extra overhead, but the greater problem for generic implementation is that fds may have changed since last registration, but you don't want to update them.

**Comment by isilence** [comment]
@goldsteinn, can the issue be closed?
