### ISSUE TITLE
Question about liberal mixing of atomic and non-atomic "operations"

### ISSUE THREAD

**Issue by twissel** [axboe/liburing#268]
Sorry for bothering you, but I have a question about correctness (in terms of c11 memory model) of this library. For example: this load 
https://github.com/axboe/liburing/blob/31a9f9cb495b468f3a93c4edaf8fccd65aa86f64/src/queue.c#L214  is not "atomic", (btw you are using atomic write after of couple  lines  https://github.com/axboe/liburing/blob/master/src/queue.c#L226) keeping in mind that there  can be a (sqpoll) thread enabled , its a data race.

**Comment by axboe** [comment]
The application is the only one updating the sq tail, so there's no atomic access needed there. We just need to write it so it's visible to the kernel. The opposite is true for cq head.

**Comment by twissel** [comment]
what about this https://github.com/axboe/liburing/blob/master/src/queue.c#L228?

**Comment by axboe** [comment]
That one should use load acquire. But since it's just the flush side, it's either fine (for !SQPOLL), or it's fine to be racy (for SQPOLL) since for the latter case it doesn't matter if it's a stable value or not. It'll potentially be out-of-sync right after the load.

So I'd say it just needs a comment.

**Comment by twissel** [comment]
Once again, sorry,  I don't what to be annoying but you can't use non atomic loads(or stores) when other threads updating the same variable(according to c11 m.m), and there is no happens before between load/store.  It's really important because when you use some checkers like http://plrg.ics.uci.edu/c11tester/ or https://plv.mpi-sws.org/genmc/, they go mad. And there is no guarantee that compiler dont't do something stupid.

**Comment by axboe** [comment]
It's a load - it's either going to be old or current, it's not going to be broken. My point is that we're OK with an older value, since either an older or current value is potentially out-of-date the instant it's done right there in case of SQPOLL. I'm not too worried about what some checker says there, those are the two only outcomes, and either one is fine as it doesn't change anything. The result is going to be racy in how it's used in any case, and the point here is that we're fine with it.

Let me just say that I don't find you annoying, it's fine to question these things. But the ultimate source of truth is understanding _how_ values are used, not what some checker might find problematic. It's totally right in flagging this one as it could be suspect, but false positives are not impossible.

**Comment by twissel** [comment]
The reason why I'm complaining it's all about c11 mm,  according to c11 mm 
```
When an evaluation of an expression writes to a memory location and another evaluation reads or modifies the same memory location, the expressions are said to conflict. A program that has two conflicting evaluations has a data race unless

both evaluations execute on the same thread or in the same signal handler, or
both conflicting evaluations are atomic operations (see std::atomic), or
one of the conflicting evaluations happens-before another (see std::memory_order)
If a data race occurs, the behavior of the program is undefined.
```
If you don't agree with that definition of data race(I know many of kernel guys doesn't agree) and you are  sure that gcc/llvm/etc   will not do something stupid evaluating ```ktail = *sq->ktail```, ok, but if you don't mind I will open a pull request to change "all conflicting" non-atomic  ring accesses to (load/store)_relaxed. Many thanks for your time!.

**Comment by axboe** [comment]
Yes, I'm pretty confident that it's fine, unless the compiler is utterly broken. And I don't want to slow down the fast path for a speculative race that isn't even real. At least until evidence is presented that makes it apparent it is real. Memory ordering is memory ordering, language or not. The statement is correct in that there COULD be a problematic data race, but fact is there isn't.

I'd be fine if we could tell the compiler not to do something stupid here, just in case one DOES decide to do that. But we don't need acquire semantics here.

**Comment by isilence** [comment]
```ktail = *sq->ktail;``` is "on same thread" in terms of c++ mm.
```io_uring_smp_store_release(sq->ktail, ktail);``` makes visible what is in SQ to SQPOLL thread.
and acquire is done by the kernel. BTW, IIRC if not SQPOLL it could have been deleted.

https://github.com/axboe/liburing/blob/master/src/queue.c#L228
Actually can use a ```READ_ONCE()```. see ```IO_URING_READ_ONCE()``` which is basically an atomic read.

**Comment by twissel** [comment]
Nobody saying about the need of  acquire semantics here. (load/store)_relaxed have no overhead, right?(at least on platforms that have atomics).

**Comment by twissel** [comment]
> `ktail = *sq->ktail;` is "on same thread" in terms of c++ mm.
> `io_uring_smp_store_release(sq->ktail, ktail);` makes visible what is in SQ to SQPOLL thread.
> and acquire is done by the kernel. BTW, IIRC if not SQPOLL it could have been deleted.
> 
> https://github.com/axboe/liburing/blob/master/src/queue.c#L228
> Actually can use a `READ_ONCE()`. see `IO_URING_READ_ONCE()` which is basically an atomic read.

Yes, thats I was trying to say.

**Comment by axboe** [comment]
READ_ONCE is exactly what I was thinking, it'd be appropriate here.

**Comment by isilence** [comment]
@twissel, would that make your tools happy, or is it just theoretical?
I would love to see somewhat formally verifying it.

**Comment by isilence** [comment]
edit: IO_URING_READ_ONCE() which is basically an atomic **relaxed** read.

**Comment by twissel** [comment]
> @twissel, would that make your tools happy, or is it just theoretical?
> I would love to see somewhat formally verifying it.

I'm afraid that formal verification is not for me, I will try to make "my tools" happy.
