### ISSUE TITLE
Does idle in IORING_SETUP_SQPOLL refer to no events being added to the cq_ring or the sq_ring?

### ISSUE THREAD

**Issue by goldsteinn** [axboe/liburing#269]
Man page has:
"
              If  the  kernel  thread is idle for more than sq_thread_idle milliseconds, it will
              set the IORING_SQ_NEED_WAKEUP bit in the flags field  of  the  struct  io_sq_ring.
              When  this happens, the application must call io_uring_enter(2) to wake the kernel
              thread.  If I/O is kept busy, the kernel thread will never sleep.  An  application
              making  use of this feature will need to guard the io_uring_enter(2) call with the
              following code sequence:
"
which is a bit ambiguous about whether idle A) no events being added to the sq_ring or B) no events being added to the cq_ring.

Looking at the code here https://github.com/torvalds/linux/blob/master/fs/io_uring.c#L7023 it seems to me that it will never idle as long as the sq_ring is not empty but I may be re reading this.

Use case is I am wondering if adding an accept operation to an SQPOLLed io_uring (and keeping it readded) if it will effectively prevent the need for idle check.

Thank you!

**Comment by isilence** [comment]
> which is a bit ambiguous about whether idle A) no events being added to the sq_ring or B) no events being added to the cq_ring.

The main role of SQPOLL is SQEs dispatching, so if the thread isn't idling (i.e. `IORING_SQ_NEED_WAKEUP`) it will process all SQEs that had been added before. All is about SQ. 

> Use case is I am wondering if adding an accept operation to an SQPOLLed io_uring (and keeping it readded) if it will effectively prevent the need for idle check.

SQPOLL supports only restricted set of requests, that's reads/writes and provide/remove buffers. But if accepts had been allowed, it wouldn't have been a problem.

**Comment by goldsteinn** [comment]
Thanks!

**Comment by axboe** [comment]
> SQPOLL supports only restricted set of requests, that's reads/writes and provide/remove buffers. But if accepts had been allowed, it wouldn't have been a problem.

Worth noting that this is 5.10 and earlier, for 5.11 and on SQPOLL basically supports the same set of operations as !SQPOLL.

But for the topic at hand, it is indeed all about the SQ ring. If that is empty, that's when idling starts. Only real exception here is SQPOLL|IOPOLL, where the SQ thread is also tasked with polling for completions, just like the task itself would have been for IOPOLL alone.

**Comment by isilence** [comment]
> > SQPOLL supports only restricted set of requests, that's reads/writes and provide/remove buffers. But if accepts had been allowed, it wouldn't have been a problem.
> 
> Worth noting that this is 5.10 and earlier, for 5.11 and on SQPOLL basically supports the same set of operations as !SQPOLL.

Thanks Jens, let me correct myself. reads/writes and provide/remove buffers is the restriction of **IO**POLL. **SQ**POLL had a different set which have got lifted recently. Still wouldn't have been a problem because SQPOLL is more about dispatching SQ entries and not (necessarily) about their execution.

**Comment by axboe** [comment]
> Thanks Jens, let me correct myself. reads/writes and provide/remove buffers is the restriction of IOPOLL

Ah yes, didn't even think of that mixup!

**Comment by goldsteinn** [comment]
> Thanks Jens, let me correct myself. reads/writes and provide/remove buffers is the restriction of **IO**POLL. **SQ**POLL had a different set which have got lifted recently, as Jens noted. Still wouldn't have been a problem because SQPOLL is more about dispatching SQ entries and not (necessarily) about their execution.

Oh I had been misunderstanding the manpages. Had believed SQPOLL was automatically the equivalent of IOPOLL | SQPOLL (now it makes sense why I've been running into issues with O_NONBLOCK).

**Comment by goldsteinn** [comment]
> But for the topic at hand, it is indeed all about the SQ ring. If that is empty, that's when idling starts. Only real exception here is SQPOLL|IOPOLL, where the SQ thread is also tasked with polling for completions, just like the task itself would have been for IOPOLL alone.

Is there a way to setup SQPOLL | IOPOLL s.t the kernel thread will automatically pop from SQ ring / publish to CQ ring but not immediately publish EAGAIN for nonblocking fds that are not ready yet?
