### ISSUE TITLE
Issue: IORING_OP_READV sometimes returns 0 or -EFAULT after dropping caches

### ISSUE THREAD

**Issue by CarterLi** [axboe/liburing#27]
This issue only happens when you submit multiple read requests.

```c
#include <liburing.h>
#include <unistd.h>
#include <fcntl.h>
#include <stdio.h>

char str1[32768];
char str2[32768];

struct io_uring ring;

void prep(int fd, char *str) {
    struct io_uring_sqe *sqe = io_uring_get_sqe(&ring);
    struct iovec iov = {
        .iov_base = str,
        .iov_len = sizeof(str1),
    };
    io_uring_prep_readv(sqe, fd, &iov, 1, 0);
    sqe->user_data = fd;
    io_uring_submit(&ring);
    printf("SUBMIT: %d\n", fd);
}

void wait() {
    struct io_uring_cqe *cqe;
    io_uring_wait_cqe(&ring, &cqe);
    io_uring_cqe_seen(&ring, cqe);
    printf("FINISH: %d with res %d\n", (int)cqe->user_data, cqe->res);
}

int main() {
    io_uring_queue_init(32, &ring, 0);
    int fd1 = open("/path/to/large/file1", O_RDONLY);
    int fd2 = open("/path/to/large/file2", O_RDONLY);

    prep(fd1, str1);
    prep(fd2, str2);
    wait();
    wait();

    close(fd2);
    close(fd1);
    io_uring_queue_exit(&ring);
}
```

Before executing the program, run `sync && echo 3 > /proc/sys/vm/drop_caches && swapoff -a && swapon -a`

You will get -EFAULT when debugging the program using GDB

```
(gdb) run
Starting program: /root/test/./test

SUBMIT: 8
SUBMIT: 9
FINISH: 9 with res -14
FINISH: 8 with res 32768
[Inferior 1 (process 16788) exited normally]
Missing separate debuginfos, use: debuginfo-install glibc-2.17-292.el7.x86_64
```

If you run it directly, the program will crash with segfault.

```
$ ./test
SUBMIT: 4
SUBMIT: 5
FINISH: 4 with res 32768
FINISH: 5 with res 3568
[1]    16893 segmentation fault (core dumped)  ./test
```

If you run the program again without dropping caches, it will work as expected

```
Linux localhost 5.4.0-1.el7.elrepo.x86_64 #1 SMP Mon Nov 25 09:18:09 EST 2019 x86_64 x86_64 x86_64 GNU/Linux
```

Original post: https://github.com/hakasenyang/openssl-patch/pull/22#issuecomment-523019477

EDIT: verified on 5.5rc too

**Comment by CarterLi** [comment]
I found this issue when testing my [io_uring nginx patch](https://github.com/hakasenyang/openssl-patch/pull/22). After hours of debugging, I found it only happens when you submit multiple read requests.

```
Linux localhost 5.4.0-1.el7.elrepo.x86_64 #1 SMP Mon Nov 25 09:18:09 EST 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by axboe** [comment]
Here's what I think is going on - if your sqe gets punted to async context, then your iovs are out-of-scope by the time the kernel reads them. So we really don't know what the kernel is reading at that point, hence -EFAULT is very possible. Dropping caches makes this much more likely to happen.

We probably should ensure that this is not the case - if we do punt to async context, it'd be nicer if the iov was already copied. Then the application could rely on the fact that any submission side context (like the iovec on the stack) is 100% safe.

**Comment by axboe** [comment]
Case in point, if you do:

```
#include <liburing.h>
#include <unistd.h>
#include <fcntl.h>
#include <stdio.h>

char str1[32768];
char str2[32768];

struct iovec iov[2];

struct io_uring ring;

void prep(int fd, char *str, int i) {
    struct io_uring_sqe *sqe = io_uring_get_sqe(&ring);
    iov[i].iov_base = str;
    iov[i].iov_len = sizeof(str1);
    io_uring_prep_readv(sqe, fd, &iov[i], 1, 0);
    sqe->user_data = fd;
    printf("SUBMIT: %d\n", fd);
}

void wait() {
    struct io_uring_cqe *cqe;
    io_uring_wait_cqe(&ring, &cqe);
    io_uring_cqe_seen(&ring, cqe);
    printf("FINISH: %d with res %d\n", (int)cqe->user_data, cqe->res);
}

int main() {
    io_uring_queue_init(32, &ring, 0);
    int fd1 = open("/data/1", O_RDONLY);
    int fd2 = open("/data/2", O_RDONLY);

    prep(fd1, str1, 0);
    prep(fd2, str2, 1);
    io_uring_submit(&ring);
    wait();
    wait();

    close(fd2);
    close(fd1);
    io_uring_queue_exit(&ring);
}
```

then it works reliably.

**Comment by CarterLi** [comment]
> Case in point, if you do:
> 
> ```
> #include <liburing.h>
> #include <unistd.h>
> #include <fcntl.h>
> #include <stdio.h>
> 
> char str1[32768];
> char str2[32768];
> 
> struct iovec iov[2];
> 
> struct io_uring ring;
> 
> void prep(int fd, char *str, int i) {
>     struct io_uring_sqe *sqe = io_uring_get_sqe(&ring);
>     iov[i].iov_base = str;
>     iov[i].iov_len = sizeof(str1);
>     io_uring_prep_readv(sqe, fd, &iov[i], 1, 0);
>     sqe->user_data = fd;
>     printf("SUBMIT: %d\n", fd);
> }
> 
> void wait() {
>     struct io_uring_cqe *cqe;
>     io_uring_wait_cqe(&ring, &cqe);
>     io_uring_cqe_seen(&ring, cqe);
>     printf("FINISH: %d with res %d\n", (int)cqe->user_data, cqe->res);
> }
> 
> int main() {
>     io_uring_queue_init(32, &ring, 0);
>     int fd1 = open("/data/1", O_RDONLY);
>     int fd2 = open("/data/2", O_RDONLY);
> 
>     prep(fd1, str1, 0);
>     prep(fd2, str2, 1);
>     io_uring_submit(&ring);
>     wait();
>     wait();
> 
>     close(fd2);
>     close(fd1);
>     io_uring_queue_exit(&ring);
> }
> ```
> 
> then it works reliably.

oh yes.

> if we do punt to async context, it'd be nicer if the iov was already copied. Then the application could rely on the fact that any submission side context (like the iovec on the stack) is 100% safe.

I agree. Another option is that adding 2 new ops: IOURING_OP_READ, IOURING_OP_WRITE. I think these two ops fits for most cases.

**Comment by CarterLi** [comment]
Oh my god this issue puzzled me about 3 months. Never realized that the problem came from iovec 😭

**Comment by axboe** [comment]
At least you have closure on it now :-). But yes, it kind of sucks, and I think we should just ensure that whenever the sqe is consumed, all related submission resources have been consumed as well. It's quite normal to put the iov on the stack just for submission, the caller shouldn't have to retain it until IO completes. Right now it basically has to, since the caller doesn't know when it has been consumed.

**Comment by axboe** [comment]
Can you try with these two patches applied?

[0001-io_uring-add-general-async-offload-context.txt](https://github.com/axboe/liburing/files/3912636/0001-io_uring-add-general-async-offload-context.txt)
[0002-io_uring-ensure-async-punted-read-write-requests-cop.txt](https://github.com/axboe/liburing/files/3912637/0002-io_uring-ensure-async-punted-read-write-requests-cop.txt)

**Comment by CarterLi** [comment]
I'm sorry but I have no idea how to build the kernel. I'll test it once it's merged into mainline.

But in this case, I'll store ioves into heap for backward compatibility

**Comment by axboe** [comment]
That's fine. I'm adding IORING_FEAT_SUBMIT_STABLE to show that a given kernel has consumed any resources needed for async punt.
