### ISSUE TITLE
confusing types

### ISSUE THREAD

**Issue by YoSTEALTH** [axboe/liburing#275]
In https://github.com/axboe/liburing/blob/master/src/include/liburing.h `user_data` as parameter is used in few different function as such sometimes the type is `__u64` and other places its `void *` this isn't consistent. Could this be cleaned up to be just `__u64`?

It leads to having to do weird monkey patching https://github.com/YoSTEALTH/Liburing/issues/11

**Comment by YoSTEALTH** [comment]
@axboe @isilence any comment on this? If this can't be done I would like to account for this in python's library.

**Comment by isilence** [comment]
@YoSTEALTH, sorry for the silence. It's worth discussing, but I just have hands full.

**Comment by YoSTEALTH** [comment]
@isilence No worries, it just effected 3 functions (that I could notice) and I ended up creating a wrapper for it https://github.com/YoSTEALTH/Liburing/commit/17ae3317a74a31a389a20bfd68f3a588e9cab19a
