### ISSUE TITLE
Should io_uring_cqe contain the opcode for the completed event?

### ISSUE THREAD

**Issue by kplantjr** [axboe/liburing#276]
It seems that if a user wants to know what type of event has completed, it can't be done by looking at the CQE alone. The user would have to supply some sort of unique value for `user_data`. A downside to this behavior is that a user may have to allocate a unique piece of memory for each event type.

If the CQE provided the opcode, users could instead use one allocated object per fd and instead switch on the cqe->opcode, greatly simplifying the design and lowering memory usage.

Current approach:
```
/* sqe submission, allocating a specific object for reads and another for writes */
struct event *read_event = allocate_some_read_event_object();
struct io_uring_sqe *sqe = io_uring_get_sqe(&ring);

io_uring_prep_read(sqe, read_event->fd, buf, nbyte, 0);
io_uring_sqe_set_data(sqe, read_event);


struct event *write_event = allocate_some_write_event_object();
struct io_uring_sqe *sqe = io_uring_get_sqe(&ring);

io_uring_prep_write(sqe, write_event->fd, buf2, nbyte2, 0);
io_uring_sqe_set_data(sqe, write_event);
.
.
.
/* cqe retrieval */
struct event *some_event;
struct io_uring_cqe *cqe;

io_uring_wait_cqe(&ring, &cqe);
some_event = io_uring_cqe_get_data(cqe);
/* 
 * some_event can't really be NULL unless you want to ignore it entirely
 * without knowing what kind of event it is.
 */
switch (some_event->type) { /* ... */ }
```

Proposed change:
```
/* sqe submission, can now use one allocated object for many events... or NULL */
struct event *event = allocate_some_generic_event_object();
struct io_uring_sqe *sqe = io_uring_get_sqe(&ring);

io_uring_prep_read(sqe, event->fd, buf, nbyte, 0);
io_uring_sqe_set_data(sqe, event);

sqe = io_uring_get_sqe(&ring);
io_ring_prep_write(sqe, event->fd, buf2, nbyte2, 0);
io_uring_sqe_set_data(sqe, event);

sqe = io_uring_get_sqe(&ring);
io_uring_prep_something_else(sqe, ...);
io_uring_sqe_set_data(sqe, NULL); /* NULL user_data is fine since we can see the opcode on the CQE side */
.
.
.
/* cqe retrieval */
struct io_uring_cqe *cqe;

io_uring_wait_cqe(&ring, &cqe);
switch (cqe->opcode) { /* ... */ }
```

**Comment by axboe** [comment]
Not sure what I'm missing here, but why can't you just assign statics to ->user_data? Have one ready for each opcode you care about (or multiple per opcode, if you need to differentiate between them). Don't see what adding the opcode would help, when you could just match on ->user_data instead. Yes, it'll mean you need some static struct even where you'd use NULL in your example, but you'd still save more memory in total as the op would take up space in every CQE.

This doesn't get into why we can't just change the cqe either, I'd prefer to focus on how we can make the existing setup work for you.

**Comment by kplantjr** [comment]
That's reasonable, there could be a gap I haven't jumped past yet; I think statics are fine for a small number of events known at the time of design. What about something like sockets where you could have thousands of open descriptors at any given time, and that number could be changing many times a second? I would still think each descriptor would need an allocated object for each opcode.

**Comment by isilence** [comment]
Let me ask, is it a purely synthetic test or a real example? Most of real applications would need a backing struct anyway.  

Anyway, kernel ABI is set in stone, so the only way is to to maintain backward compatibility, and that would be too much of a trouble, especially without a really good justification.

**Comment by kplantjr** [comment]
It's a real example, let me try to briefly explain:

Let's say I have n connections all with one backing struct per connection: `struct conn { int fd; /* ... */ };`

When preparing and submitting syscalls via io_uring, I set `user_data` to point to the `conn` struct instance for that connection.

When waiting for completed events, I get back the same `user_data` pointing to the `conn` struct instance, however I have no additional data telling me what type of event completed. Was it a read(), write(), connect(), accept(), close(), etc?

Picking on epoll as an example, I am able to get back both the `conn` struct instance and a u32 with the triggered events.

--------------------------------

If my complaints are valid, might it be possible to borrow 8 bits from cqe->flags to mask in the opcode? This might preserve the current ABI.

**Comment by isilence** [comment]
Yes, IIRC it can be fitted into cflags, but the space is tight, and would be better to leave it for something more beneficial.

If you allocate conn yourself, why not prepend it with opcode similarly to the snippet below?
It can be done in a generic manner not io_uring specific, if designed right.

```C
struct req {
    u8 opcode;
    union {
       conn;
       ...
    };
};

allocate_conn_req() {
    return malloc(sizeof(struct cqe));
};

// or 
struct cqe {
    opcode;
    char payload[];
};
```

**Comment by kplantjr** [comment]
I do like your idea of creating a wrapper pairing the opcode together with a `conn` pointer. That improves on my earlier worst-case of allocating an entire `conn` per opcode. It still seems a _little_ clunky compared to the epoll example, but I definitely see the value in not breaking backwards compatibility.

**Comment by isilence** [comment]
Yeah, there are plenty of reasons of not doing that.
Great that helps. It's actually a common pattern in C world. With container_of you can place it anywhere in the struct.

```C
struct req { u8 opcode; };
struct conn { struct req req; /* conn fields */ };

// submit
sqe->user_data = &conn->req;

// complete
struct req *r = cqe->user_data;
if (r->opcode == CONN) {
    struct conn *c = container_of(r, struct conn, req);
    ...
}
```

Or for C++ it can be a virtual or base class.

```C++
struct req {
    virtual void complete() = 0;
};

// or 
struct req {
    inline u8 get_opcode() { return opcode; }
private:
    u8 opcode;
};


```

**Comment by kplantjr** [comment]
So this is where I feel like one instance wouldn't work, if I have the following:

```c
struct req { u8 opcode };
struct conn { int fd; struct req req; };

struct conn *conn = create_some_conn_instance();

sqe = io_uring_get_sqe(&ring);
conn->req.opcode = IORING_OP_CONNECT;
io_uring_prep_connect(sqe, conn->fd, ...);
sqe->user_data = &conn->req;

sqe = io_uring_get_sqe(&ring);
conn->req.opcode = IORING_OP_READ;
io_uring_prep_read(sqe, conn->fd, ...);
sqe->user_data = &conn->req;

sqe = io_uring_get_sqe(&ring);
conn->req.opcode = IORING_OP_WRITE;
io_uring_prep_write(sqe, conn->fd, ...);
sqe->user_data = &conn->req;
```

Wouldn't all CQEs have user_data that points back to &conn->req thus all having opcode be IORING_OP_WRITE?

**Comment by isilence** [comment]
There is a workaround for you, or break down that struct and store a
pointer to your conn, but in the end you need to figure out yourself
a design that would suit you.

Honestly, storing a connection but not something representing an actual
request is limiting if not odd. Though may be pretty ok for forwarding or
some alike simple stuff.

```C
struct req { u8 opcode };
struct conn { struct req poll_hook, read_hook; };

// submit
sqe->opcode = POLL;
sqe->user_data = &conn->poll_hook;
sqe2->opcode = READ;
sqe->user_data = &conn->read_hook;

// complete
if (opcode == READ) {
    conn = container_of(user_data, struct req, read_hook);
   ...
} else if (opcode == POLL) {
    conn = container_of(user_data, struct req, poll_hook);
   ...
}

```

**Comment by isilence** [comment]
btw, io_uring does polling internally since some version, so IORING_OP_POLL_ADD be not needed

**Comment by kplantjr** [comment]
I think we're saying the same thing at this point, each opcode would require a unique structure to identify what opcode had completed on the CQE side. That's kind of where I was going in my initial message and that it feels clunky to do so.

**Comment by kplantjr** [comment]
I'm going to mark this closed, just wanted to make the suggestion. Appreciate the discussion.
