### ISSUE TITLE
io_uring_cqe_get_data() (cqe->user_data) returns NULL

### ISSUE THREAD

**Issue by yogch** [axboe/liburing#277]
I'm on latest `master`. I have this simple code that do:
```
io_uring_queue_init(...)
io_uring_register_buffers(...)
struct io_uring_sqe *sqe = io_uring_get_sqe(ring);
io_uring_sqe_set_data(sqe, (void*)1);
io_uring_prep_write_fixed(...)
io_uring_submit(ring);
...
int ret = io_uring_wait_cqe(ring, &cqe);
// (ret < 0) and (cqe->res < 0) checks
io_uring_cqe_get_data(cqe); // <--------------- returns NULL
```

I used both Ubuntu 18.04 kernel `5.4.0-58-generic` and Ubuntu 20.04 (I think that's kernel 5.8.*)
Is this a known issue? Please let me know if I should bring a reproduced example.

Thanks!

**Comment by axboe** [comment]
Reproducer will be required, not aware of any bugs like that in past kernels, but who knows.

**Comment by yogch** [comment]
Sorry, my bad.
I call `io_uring_sqe_set_data()` before `io_uring_prep_write_fixed()`.
It should be the opposite order.
Thanks!

**Comment by axboe** [comment]
Indeed, it'll clear it. Was sure this was an application error :-)
