### ISSUE TITLE
Irregular short reads with OP_SPLICE under load

### ISSUE THREAD

**Issue by 3541** [axboe/liburing#278]
I'm experiencing an odd issue with `OP_SPLICE` under constant load. Intermittently, some reads (i.e., splice from file to pipe) will return short. Moreover, all of these short reads are precisely 4096 bytes.

My understanding of pipes and `splice` suggests that it should not actually ever return short, unless the pipe is specifically put in non-blocking mode.

[I've attached a test program](https://gist.github.com/3541/a45f5ac873b00eb45b8cf2c75f1e74f9) which seems to reliably trigger the issue with liburing-0.7 on kernel 5.8.0, 5.9.16, as well as the latest (a9f7c7a1f) from the [`for-next` branch here](https://git.kernel.dk/cgit/linux-block/). It repeatedly fills the entire submission queue with chained splices from a random file, into a pipe, into `/dev/null`. In order to trigger the issue, a somewhat large submission queue is necessary, and it may therefore be necessary to raise the locked memory and open file limits in order to run.

Apologies if I've missed something obvious or am doing something wrong — I'm not experienced with the kernel nor with io_uring. Either way, any advice on how to diagnose this further would be much appreciated.

**Comment by NobodyXu** [comment]
Maybe you shouldn't assume that `splice` would copy number of bytes you requested.
`read` and `write` on linux explicitly state that short return is possible, so it is not surprised `splice` also exhibit the same behavior.

Since no short return guarantee isn't part of the API of `read`, `write` or `splice`, IIMHO you probably shouldn't assume that short return is impossible.

**Comment by 3541** [comment]
Hm. Yes, I suppose that is the case. There goes my irrational hope of being lazy and avoiding handling that particular case for chains involving splice. Thanks for the clarification, though.

**Comment by CarterLi** [comment]
> Since no short return guarantee isn't part of the API of read, write or splice

Source for splice?

**Comment by NobodyXu** [comment]
Well, the man page of `splice` doesn't explicitly state that the return value must be equal to the requested byte size, so I take it as any return value bigger than 0 is valid.

**Comment by CarterLi** [comment]
You are right.

For 4096 bytes problem, it is because the buffer size of pipe.

https://unix.stackexchange.com/questions/11946/how-big-is-the-pipe-buffer
