### ISSUE TITLE
RWF_NOWAIT return value

### ISSUE THREAD

**Issue by YoSTEALTH** [axboe/liburing#280]
When using `io_uring_prep_readv` with `RWF_NOWAIT` flag and the file being read is empty `cqe.res` returns `-11` (EAGAIN)

According to `man preadv2`
``` bash
RWF_NOWAIT (since Linux 4.14)
    Do not wait for data which is not immediately available.  If this flag is specified, the preadv2() sys‐
    tem  call  will  return  instantly if it would have to read data from the backing storage or wait for a
    lock.  If some data was successfully read, it will return the number of bytes read.  If no  bytes  were
    read,  it  will  return  -1  and  set  errno  to  EAGAIN.   Currently, this flag is meaningful only for
    preadv2().
```
> If no  bytes  were read,  it  will  return  -1

Shouldn't `io_uring_prep_readv` -> `cqe.res` return `-1` or `0` vs `-11` (EAGAIN) as functions
- io_uring_peek_cqe
- io_uring_wait_cqe*
- ...

return `-11` (EAGAIN) if blocking happens?

**Comment by isilence** [comment]
No, they should not.

Pairing 0/-1 return with errno is a hack from old days, useless for async mult-completion APIs as io_uring, and would just bring more problems.

**Comment by axboe** [comment]
On top of that, this is mixing up per-request completion state (eg cqe->res) with per-ring wait state. If io_uring_peek_cqe() returns -EAGAIN that isn't related to any particular request, it just means that there are no completions in the ring that haven't been seen.

And totally agree with Pavel on the other part, errno never works for retrieving async results. That's also why liburing returns the error value directly.

**Comment by YoSTEALTH** [comment]
This problem leads to infinity loop. If the `cqe.res` is returning `EAGAIN` you try again thinking file read is being blocked!

How to tell the difference between file content is `0` vs BlockingIO taking place?

**Comment by axboe** [comment]
But that's how non-blocking IO works, io_uring or not... Generally you use either nonblocking IO with some sort of poll mechanism, or blocking IO. If you're using RWF_NOWAIT you must expect -EAGAIN and handle that appropriately, you can't just keep retrying and expecting different results.

**Comment by axboe** [comment]
-EAGAIN isn't about a given read being blocked, it's about no data being available to read without needing to block waiting for it. For regular files, RWF_NOWAIT will return data if said data is in the page cache. If it's not, then you'd need issue a read without RWF_NOWAIT to actually read the data, or use eg some kind of read-ahead to bring it into the cache. Probably not a lot of use cases for RWF_NOWAIT with io_uring, as we handle it async in any case. If the data is not there, then won't block the submission, we'll just ensure that it happens in the background and then trigger a completion event when it's done.

**Comment by YoSTEALTH** [comment]
Ok, I would have to agree with all the points you made :)

> Probably not a lot of use cases for `RWF_NOWAIT` with `io_uring`, as we handle it async in any case.

Does `io_uring` account for page cache data as well like `RWF_NOWAIT` does?

**Comment by axboe** [comment]
> Does io_uring account for page cache data as well like RWF_NOWAIT does?

It does, yes. If you submit a read and the data is in cache, then the copy happens inline and the cqe will be posted before your submit returns. If it's not in cache, then a read is issued for it, and we return from submit. When the data is populated, then a callback into io_uring enables the task to retry behind-the-scenes. That retry will succeed (in normal cases) and the data is copied and a cqe is posted.

**Comment by YoSTEALTH** [comment]
That is really AWESOME!!!

Totally dumping `RWF_NOWAIT` usage now.

Thanks @axboe nicely done.
