### ISSUE TITLE
Potential application deadlock when handling `EAGAIN`?

### ISSUE THREAD

**Issue by jorangreef** [axboe/liburing#281]
If an application attempts to submit an `sqe` using `io_uring_enter()`, it's possible that `EAGAIN` may be returned:

```
EAGAIN
The kernel was unable to allocate memory for the request, or otherwise ran out of resources to handle it.
The application should wait for some completions and try again.
```

The application may then attempt to handle this `EAGAIN` as recommended by the man page by calling `io_uring_enter()` but this time with `to_submit=0` and with `min_complete=1` in an attempt to flush the cq ring.

However, what if this was the very first `sqe` submitted by the application, so that there are no `cqes` inflight or available to be flushed when calling `io_uring_enter()` with `min_complete=1`? Would this not result in an application deadlock?

What's the best way to handle `EAGAIN`?

**Comment by jorangreef** [comment]
Just to clarify the main point here:

**`EAGAIN` could also be caused by another component of the system, outside of io_uring**, so that the man page's advice of "wait for some completions and try again" could actually result in deadlock if there are no inflight requests in the io_uring instance.

**Comment by axboe** [comment]
That's certainly true, it could be outside of io_uring hands at that point. Generally io_uring tries to ensure that we can always make forward progress, at least in terms of requests. The man page is a bit outdated in that sense.

That said, if the system is driven way out of resources, most kernel APIs end up being unreliable in the sense that you _can_ get spurious -ENOMEM. That's really not something specific to io_uring, and there's sadly not too much that can be done about it. In practice, the kernel tries very hard to allocate data for operations, so you'd only really run into this if the system is run into the ground anyway.

**Comment by jorangreef** [comment]
Thanks @axboe!
