### ISSUE TITLE
READV_FIXED and WRITEV_FIXED?

### ISSUE THREAD

**Issue by 00pauln00** [axboe/liburing#283]
Hi,
I am wondering if FIXED versions of `[read|write]v` are feasible?  It seems that having a group of registered buffers,  which can be managed by SGLs, would be very useful for applications dealing with variably sized io's using fixed sets of source and sink buffers.   

After a brief read of io_uring.c, it seems that having to provide an array of `buf_index` would make things tricky for both user and kernel space.  So would it be possible to restrict usage so that all iov_base pointers refer to the same chunk of registered user memory?  This would simplify efforts around `io_import_fixed()` since only one `buf_index` would need to be checked.
Thanks,
paul

**Comment by 00pauln00** [comment]
I see there is some discussion on the io-uring kernel mailing list regarding this feature: 
https://www.spinics.net/lists/io-uring/msg05358.html

**Comment by isilence** [comment]
Unless there is a real app which numbers go up with it, I would say it doesn't worth complexity, at least for now. Well, at least I can think of several not very obvious cases that would add some ugliness, would be glad to be proven wrong.
