### ISSUE TITLE
Question about passing off_t in prep helpers

### ISSUE THREAD

**Issue by twissel** [axboe/liburing#29]
Why does prep helpers have offt_t in their arguments, example: https://github.com/axboe/liburing/blob/8f24d3c550d6450febfb44aec1edabdac05c3f95/src/include/liburing.h#L166  and io_uring_sqe have __u64 in definition https://github.com/axboe/liburing/blob/8f24d3c550d6450febfb44aec1edabdac05c3f95/src/include/liburing/io_uring.h#L22 ?

**Comment by axboe** [comment]
Because the actual user api between app and kernel must be 32-bit vs 64-bit agnostic, while the off_t type can vary depending on 32-bit and LFS, etc.
