### ISSUE TITLE
Unexpected CQE result -512 (recvmsg+cancel)

### ISSUE THREAD

**Issue by paxostv** [axboe/liburing#30]
I have a socket open that has an asynchronous recvmsg (io_uring_prep_recvmsg + io_uring_sqe_set_data) outstanding. No data is being supplied by the other end. Subsequently, the recvmsg is being canceled (io_uring_prep_cancel). The CQE for the cancel is giving -114 (-EALREADY) which is expected, however the CQE for the recvmsg is receiving -512, which is not.

Not sure where the result is being generated. In the case it's a kernel issue, I'm testing with https://kernel.ubuntu.com/~kernel-ppa/mainline/daily/2019-12-01/.

**Comment by axboe** [comment]
I think you need this:

https://git.kernel.dk/cgit/linux-block/commit/?h=for-linus&id=441cdbd5449b4923cd413d3ba748124f91388be9

**Comment by axboe** [comment]
It'll go upstream this week and is marked for stable. Closing.
