### ISSUE TITLE
Kernel lockup in make runtests with kernel 5.8.18

### ISSUE THREAD

**Issue by jbreitbart** [axboe/liburing#301]
When I try to run `make runtests` my systems hangs and I get soft and hard lockup messages from the kernel. I am running Ubuntu 18.04 with 5.8.18. Is there a known bug that causes this and I should try to update to the latest kernel or is it worth investigating this further? Is there anything I could do to help fix this bug?

```
 ᨂ git rev-parse HEAD
5671af310f7c2b0b88101511163188171ba4715d

 ᨂ uname -a
Linux ABTZ0FTE 5.8.18-050818-generic #202011011237 SMP Sun Nov 1 12:40:15 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by isilence** [comment]
Most probably it is fix in newer kernels, but haven't go backported/propagated (yet?).

Would be nice to have:
1. liburing git hash
2. those messages your kernel prints

**Comment by axboe** [comment]
The liburing regression tests aggressively test for crashes or issues that we found in testing. This means that older kernels may very well crash on them. The problem with 5.8 is that the stable versions of it have been discontinued, hence no further fixes can be ported to that kernel.

**Comment by jbreitbart** [comment]
> The liburing regression tests aggressively test for crashes or issues that we found in testing. This means that older kernels may very well crash on them. The problem with 5.8 is that the stable versions of it have been discontinued, hence no further fixes can be ported to that kernel.

Thanks for letting me know. I seemed to be the latest version available that did not result in any problems with the proprietary NVIDIA drivers. I guess, I'll should find a way to upgrade to the latest release.

> Most probably it is fix in newer kernels, but haven't go backported/propagated (yet?).
> 
> Would be nice to have:
> 
>     1. liburing git hash
5671af310f7c2b0b88101511163188171ba4715d

> 
>     2. those messages your kernel prints

I am not sure how to extract that info after the system crashed. Here is a photo: https://imgur.com/a/5BiLD7K

> 
>     3. which test exactly failed as described

I guess `d77a67ed5f27-test`, but I am not sure. This is the output I get when running it via ssh

```
 make runtests
make[1]: Entering directory '/home/rbj2abt/source/liburing/src'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/rbj2abt/source/liburing/src'
make[1]: Entering directory '/home/rbj2abt/source/liburing/test'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/rbj2abt/source/liburing/test'
make[1]: Entering directory '/home/rbj2abt/source/liburing/examples'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/rbj2abt/source/liburing/examples'
make[1]: Entering directory '/home/rbj2abt/source/liburing/test'
Running test 232c93d07b74-test
Running test 35fa71a030ca-test
Test 35fa71a030ca-test timed out (may not be a failure)
Running test 500f9fbadef8-test
Polling not supported in current dir, test skipped
Running test 7ad0e4b2f83c-test
Running test 8a9973408177-test
Running test 917257daa0fe-test
Running test a0908ae19763-test
Running test a4c0b3decb33-test
Running test accept
test_accept_sqpoll: skipped, not root
Running test accept-link
Running test accept-reuse
Running test accept-test
Running test across-fork
Running test splice
Running test b19062a56726-test
Running test b5837bd5311d-test
Running test ce593a6c480a-test
Running test close-opath
Running test connect
Running test cq-full
Running test cq-overflow
Running test cq-overflow-peek
Running test cq-peek-batch
Running test cq-ready
Running test cq-size
Running test d4ae271dfaae-test
Test requires root, skipping
Running test d77a67ed5f27-test
SQPOLL requires root, skipped
Running test defer
test_thread_link_cancel: skipped, not root
```

If you need anything else let me know. If you think it is already fixed, feel free to close this issue.
