### ISSUE TITLE
Inconsistent return values for cqe single/batch peek API

### ISSUE THREAD

**Issue by hassila** [axboe/liburing#307]
Looking at the API, there seems to be a small bit of dissonance in the single peek and batch peek functions return values.

    /*
    * Fill in an array of IO completions up to count, if any are available. 
    * Returns the amount of IO completions filled.
    */
    
    unsigned io_uring_peek_batch_cqe(struct io_uring *ring, struct io_uring_cqe **cqes, unsigned count);

and 

     /*
     * Return an IO completion, if one is readily available. Returns 0 with
     * cqe_ptr filled in on success, -errno on failure.
     */
    
     static inline int io_uring_peek_cqe(struct io_uring *ring, struct io_uring_cqe **cqe_ptr)

Wouldn't it make sense to have both return success/failure (0/-errno) and be unsigned and add a separate optional pointer to an int for returning the number of cqe:s returned to the batch peek?

At least from a library users point of view it seems surprising that single event peeks can fail with (e.g. EAGAIN from looking at the code) while the batch can't?

**Comment by axboe** [comment]
I agree, but we're kind of stuck with that return since I don't want to break existing users. You could add a new batch waiter to make the API a bit more symmetric for the two.

**Comment by hassila** [comment]
Thanks, would you want a PR for that? Could perhaps have a section of "discontinued" old API that eventually might be phased out just to guide new users to the more consistent one?

**Comment by axboe** [comment]
A bit late on this one... Yes that actually sounds like a good plan, and a PR would be appreciated.

**Comment by hassila** [comment]
Cool, will take a bit of time (offline a couple of weeks now in practice), but will revert.
