### ISSUE TITLE
Leaking of io_wqe_worker-0 and -1 after TCP connection drop

### ISSUE THREAD

**Issue by KayEss** [axboe/liburing#308]
We're using io_uring to connect to a control system implemented in Python over websockets. A bug in the Python process which caused it to drop the connection made us notice that large numbers of `io_wqe_worker-0` and `io_wqe_worker-1` processes appear as the client attempted a reconnect only to have the server drop the connection almost straight away (after the web socket handshake and the client sending the first web socket frame). When we kill the client process (the io_uring one) then the kernel processes also die.

We're seen this on both the 5.8.0-44-generic and 5.8.0-45-generic kernels (Ubuntu 20.10) and the latest liburing code.

Is this a known problem that's been fixed already, or is this a problem we should be filing somewhere else? Is there anything further we can do to help?

**Comment by isilence** [comment]
Is the socket pair was closed from the other side or locally?

Requests take a reference to a socket file, so it's not enough to close userspace fd to kill the socket, all requests using it should be removed as well. So, was it just `close()`? Or `shutdown()`? The latter should help if my guess is right.

**Comment by isilence** [comment]
Ping

**Comment by sajal** [comment]
> Is the socket pair was closed from the other side or locally?

The socket pair was being closed from the remote end (python server).

**Comment by KayEss** [comment]
Just to be clear, when the socket errors from the io_uing side it is also closed there, but in this case it's in response to the error from the remote end.
