### ISSUE TITLE
unsubmitted entries when using io_uring_submit is a bit unexpected - clarification of usage

### ISSUE THREAD

**Issue by hassila** [axboe/liburing#309]
After spending one day tracking down that io_uring_submit could submit less than all IO prepared, I'd just want to make sure I understand the proper usage of submissions when preparing multiple IO. 

Specifically, I did a number of io_uring_prep_poll_add followed by a io_uring_submit - what ended up happening was that one of the poll fds in the middle of this range was closed, so the submission stopped there with bad fd. This meant that I got a lost wakeup as one of the later poll submissions were for the eventfd I used for waking up the uring when needed for e.g. shutdown. (sidenote, it would be nice to be able to add polls for fds that aren't oneshot for this use case, it basically have the same lifecycle as the uring, so it just are a number of unnecessary re-registrations)

Luckily I found this mention (and re-read the usage much more carefully):

> Yeah, it'll lose "sync" with the liburing side when this happens, I can see how that can be somewhat confusing. Let me see if I can handle that.
> 
> _Originally posted by @axboe in > https://github.com/axboe/liburing/issues/92#issuecomment-598747822_

So given that, I take it that the robust way of submitting multiple prepared IO (I don't particularly care if a fd was closed that I'm registering, it is in this case something that I would have a pending CQE for anyway):

```c
while (io_uring_sq_ready(&ring) > 0)
{
  io_uring_submit(&ring);
}
```

Rather than without checking sq_ready as many of the sample are written around the www.

Is this correct?

**Comment by isilence** [comment]
> After spending one day tracking down that io_uring_submit could submit less than all IO prepared, I'd just want to make sure I understand the proper usage of submissions when preparing multiple IO.
> 
> Specifically, I did a number of io_uring_prep_poll_add followed by a io_uring_submit - what ended up happening was that one of the poll fds in the middle of this range was closed, so the submission stopped there with bad fd. This meant that I got a lost wakeup as one of the later poll submissions were for the eventfd I used for waking up the uring when needed for e.g. shutdown. (sidenote, it would be nice to be able to add polls for fds that aren't oneshot for this use case, it basically have the same lifecycle as the uring, so it just are a number of unnecessary re-registrations)

It is in plans. @axboe wants it for 5.13, I believe.
https://git.kernel.dk/cgit/linux-block/log/?h=poll-multiple

> Luckily I found this mention (and re-read the usage much more carefully):
> 
> > Yeah, it'll lose "sync" with the liburing side when this happens, I can see how that can be somewhat confusing. Let me see if I can handle that.
> > _Originally posted by @axboe in > [#92 (comment)](https://github.com/axboe/liburing/issues/92#issuecomment-598747822)_
> 
> So given that, I take it that the robust way of submitting multiple prepared IO (I don't particularly care if a fd was closed that I'm registering, it is in this case something that I would have a pending CQE for anyway):
> 
> ```c
> while (io_uring_sq_ready(&ring) > 0)
> {
>   io_uring_submit(&ring);
> }
> ```
> 
> Rather than without checking sq_ready as many of the sample are written around the www.
> 
> Is this correct?

Right. Usually errors that lead to undersubmission are rather userspace bugs, like
setting non-existing flags / etc., so many programs just ignore it, but I guess your
example with fds getting closed may have place in some cases.

And mostly each call will consume at least one SQE with some exceptions, e.g.
it may return -EAGAIN or -ENOMEM when there is not enough memory to do
internal allocations.

**Comment by hassila** [comment]
Thanks!

> (sidenote, it would be nice to be able to add polls for fds that aren't oneshot for this use case, it basically have the same lifecycle as the uring, so it just are a number of unnecessary re-registrations)
> 
> It is in plans. @axboe wants it for 5.13, I believe.
> https://git.kernel.dk/cgit/linux-block/log/?h=poll-multiple
> 

That's awesome. One other question was to be able to do modify the poll mask in that case instead of just add/delete, currently I'm faking that will remove/add, but it would be very useful to be able to just SQE away modifications in poll mask as needed and then receive a continuous stream of poll CQE:s (realising I may get an 'old' completion, but that is absolutely find and is already handled).

**Comment by hassila** [comment]
Or rather that the semantics of IORING_POLL_ADD_MULTI would be that subsequent calls to IORING_POLL_ADD_MULTI with the same user data would replace the previous poll mask in use. Then one could just update away.

**Comment by axboe** [comment]
> Or rather that the semantics of IORING_POLL_ADD_MULTI would be that subsequent calls to IORING_POLL_ADD_MULTI with the same user data would replace the previous poll mask in use. Then one could just update away.

I don't like that, because it would mean that any new add would be a lookup as well. If a poll update operation is going to be supported, it should be specifically flagged as such. Eg a ```IORING_POLL_ADD_UPDATE``` flag, for instance, that matches on user_data and re-adds the poll internally based on the new events mask. That would work for both multi and one-shot poll requests.

**Comment by hassila** [comment]
Thanks @axboe, Adding IORING_POLL_ADD_UPDATE would be awesome and cleaner. On a related note congrats to io_uring, most exiting thing in terms of async IO in the last 30 years IMHO.

**Comment by hassila** [comment]
I opened https://github.com/axboe/liburing/issues/310 for that. I think this case can be closed as things have been sorted out (and pleasant surprise that IORING_POLL_ADD_MULTI was in the pipeline already).
