### ISSUE TITLE
Feature request: Allow sqe flags like IOSQE_IO_LINK for IORING_OP_TIMEOUT with off == 0

### ISSUE THREAD

**Issue by CarterLi** [axboe/liburing#31]
Currently we forbid flags for IORING_OP_TIMEOUT.

https://github.com/torvalds/linux/blob/63de37476ebd1e9bab6a9e17186dc5aa1da9ea99/fs/io_uring.c#L2456

I think it's reasonable for `io_uring_wait_cqe_timeout`. But for pure timeout ( ie REQ_F_TIMEOUT_NOSEQ ), this operation should behave like other operations and should allow for common sqe flags.

This is a valid usage:

1. readv
1. timeout(1s)
1. writev

And this should be valid too:

1. timeout(1s)
1. timeout(1s)
1. timeout(1s)

**Comment by axboe** [comment]
Agree, I sent out a patch to remove this restriction.

**Comment by CarterLi** [comment]
Should we read timespec earlier like what we did for read/write?

For example timeout is delayed by IOSQE_IO_LINK

**Comment by axboe** [comment]
Yeah we should, I'm going to add support for that.

**Comment by axboe** [comment]
https://git.kernel.dk/cgit/linux-block/commit/?h=for-linus&id=2d28390aff879238f00e209e38c2a0b78717360e

**Comment by CarterLi** [comment]
Thanks. I'll try it after it's merged into mainline.
