### ISSUE TITLE
Trying out liburing

### ISSUE THREAD

**Issue by suhasu** [axboe/liburing#318]
I downloaded this package and was trying it on my Debian VM running 10.0, but I get following error when I try it out:

esis-debian10-x64-test{samn}: ./read-write /tmp/tstfile
queue init failed: -38
esis-debian10-x64-test{samn}: 

Wondering why this is the case? Any ideas what I may be missing here? Does the linux kernel I'm using not support uring as yet?

**Comment by axboe** [comment]
You're kernel doesn't support it, -38 is -ENOSYS which is what the kernel returns if the kernel doesn't support the syscall.

**Comment by suhasu** [comment]
> You're kernel doesn't support it, -38 is -ENOSYS which is what the kernel returns if the kernel doesn't support the syscall.

Thank you. So, what's the latest release of Debian where I can find support for liburing?

**Comment by hassila** [comment]
You would need Debian 11 which afaik is not released yet. https://www.debian.org/releases/testing/i386/release-notes/ch-whats-new.en.html

First uring was in 5.1 kernel, so you need at least that. Debian 11 seems to ship with 5.10.

**Comment by suhasu** [comment]
Thank you!
