### ISSUE TITLE
Add IOSQE_SUPRESS_CQE_ON_SUCCESS & IOSQE_SUPRESS_CQE_ALWAYS flags (feature request)

### ISSUE THREAD

**Issue by hassila** [axboe/liburing#321]
For some operations (e.g. poll mask modifications when running multishot polls, #310), there are really nothing that needs to be done when receiving the CQE for my use case, so it would be neat if I could mark such requests (where I only want to handle possible errors) with e.g. a IOSQE_SUPRESS_SUCCESS flag such that the kernel only performs the operation silently and doesn't generate any CQE for it when it is successful (avoid the overhead of processing the return CQE). 

In the best of worlds, it would be possible to suppress a set of return values where I know no operation will be required on the application side, but realize it may be difficult to pass that information on, so have a flag for suppressing success would handle a lot of the interesting cases.

**Comment by CarterLi** [comment]
Ref: https://lore.kernel.org/io-uring/67b28e66-f2f8-99a1-dfd1-14f753d11f7a@gmail.com/T/

**Comment by hassila** [comment]
@CarterLi - cool, much related although not exactly identical. Both are useful for different use cases I think.

IOSQE_SUPRESS_CQE_ON_SUCCESS
IOSQE_SUPRESS_CQE_ALWAYS
... ?

**Comment by hassila** [comment]
Then one would set IOSQE_SUPRESS_CQE_ON_SUCCESS for linked SQE:s (except for the last) and IOSQE_SUPRESS_CQE_ALWAYS for SQE:s where we truly don't care about the result (like deregistration/modification of poll events).

This would help shedding a huge amount of CQE reaping on the user side for me currently.

**Comment by isilence** [comment]
> Then one would set IOSQE_SUPRESS_CQE_ON_SUCCESS for linked SQE:s (except for the last) and IOSQE_SUPRESS_CQE_ALWAYS for SQE:s where we truly don't care about the result (like deregistration/modification of poll events).

As you may see in the thread referenced above both options were discussed, and even though killing always doesn't see like "the right thing to do", "supress but last" looks reasonable and useful. I had it implemented long before, but performance of links in general was bad to hide any benefits on that side, so it have never came to the light.  Though, lots of link-specific preparations was shed, so it may worth to raise to from ashes... I even have a test bundle for it somewhere.

> This would help shedding a huge amount of CQE reaping on the user side for me currently.

Right. The main problems is 1) such features in the common paths, meaning adding overhead for those not using add and complicates the code. 2) we almost out of flags unfortenatuly (8 bits field in SQE), and foldering 2 fields would only add even more overhead. But if performance would be good enough, together with this userspace niceness may overweight. It's worth to repeat the experiment in any case.

**Comment by hassila** [comment]
I would have great use for especially IOSQE_SUPRESS_CQE_ON_SUCCESS actually completely without using linking at all when using the new poll update feature.

When I perform an update of the poll mask and it succeeds, the user space handling of the success is a NOP - there is nothing to do - so I just get wakeup and a CQE to throw away. Same thing for deletes basically. 

For failures, it is typically almost always the same too actually for both modifications and delete of poll operations (as my modifications/delete basically fail when e.g. the fd already have been closed in a race, but I don't care too much at that point, as all internal cleanup already would have been done and it basically becomes a NOP.) 

Now, this second case one can argue that 'real' errors should be handled anyway, but for the first case (successful operations that are NOP:s on the user side) is very useful even without linked operations for the poll mask modifications (and deletes too). So IOSQE_SUPRESS_CQE_ON_SUCCESS would be very useful in that case.

**Comment by ioquatix** [comment]
These two flags would be very great. There are some cases e.g. `close` where you can't do anything meaningful with the error code... so both flags could be useful.

**Comment by isilence** [comment]
Here we go: https://lore.kernel.org/io-uring/cover.1631367587.git.asml.silence@gmail.com/

`sqe->flags` are limited, I'd rather to save on them and so there is just one flag, basically `IOSQE_SUPRESS_CQE_ON_SUCCESS`. When fails, it also suppresses CQEs for all linked requests. For linked timeout the rules are different, in essence it allows to unconditionally ignore emitting CQEs for them, and IMHO it makes more sense that some conditional approach.

What it covers:
1) Ignoring successfully completed requests
2) Generating only 1 CQE per link: either the final success, or a fail CQE for the first failed. For that, mark all requests in the link except for the last one with the flag.

It doesn't cover ignoring failed requests, e.g. a single failed close, but I don't think it's a good pattern, and it should already be covering most of the cases and userspace overheads.

Thoughts? Any more use cases?

p.s. will add attributes when re-posting the series, I believe Carter Li was the first proposing this.

**Comment by isilence** [comment]
Related issues: #376, #53, #79

**Comment by ioquatix** [comment]
I look forward to trying this out.

**Comment by CarterLi** [comment]
> Here we go: [lore.kernel.org/io-uring/cover.1631367587.git.asml.silence@gmail.com](https://lore.kernel.org/io-uring/cover.1631367587.git.asml.silence@gmail.com/)
> 
> `sqe->flags` are limited, I'd rather to save on them and so there is just one flag, basically `IOSQE_SUPRESS_CQE_ON_SUCCESS`. When fails, it also suppresses CQEs for all linked requests. For linked timeout the rules are different, in essence it allows to unconditionally ignore emitting CQEs for them, and IMHO it makes more sense that some conditional approach.
> 
> What it covers:
> 
> 1. Ignoring successfully completed requests
> 2. Generating only 1 CQE per link: either the final success, or a fail CQE for the first failed. For that, mark all requests in the link except for the last one with the flag.
> 
> It doesn't cover ignoring failed requests, e.g. a single failed close, but I don't think it's a good pattern, and it should already be covering most of the cases and userspace overheads.
> 
> Thoughts? Any more use cases?
> 
> p.s. will add attributes when re-posting the series, I believe Carter Li was the first proposing this.

Long awaited feature! Thanks.

Question: If a CQE is suppressed, will the completion event awake the user land?

**Comment by isilence** [comment]
> Long awaited feature! Thanks.

Indeed. As I remember, links were quite heavy and I wouldn't consider them hot back then. Lots has changed since.

> Question: If a CQE is suppressed, will the completion event awake the user land?

In short, it won't.

`sys_io_uring_enter(nr_wait=N)` will usually only return when there are N CQEs in the queue. As it doesn't post new completions waiter will continue to wait.  Even if the userspace waits for many requests, it's still more performant for the (in-kernel) waiter side. There are three parts it optimses:
- locking for emitting CQEs (kernel side)
- not checking for CQ waiters (may be expensive)  and potentially unnecessary waking them (kernel side)
- may improve userspace CQE handling

**Comment by CarterLi** [comment]
> > Long awaited feature! Thanks.
> 
> Indeed. As I remember, links were quite heavy and I wouldn't consider them hot back then. Lots has changed since.
> 
> > Question: If a CQE is suppressed, will the completion event awake the user land?
> 
> In short, it won't.
> 
> `sys_io_uring_enter(nr_wait=N)` will usually only return when there are N CQEs in the queue. As it doesn't post new completions waiter will continue to wait. Even if the userspace waits for many requests, it's still more performant for the (in-kernel) waiter side. There are three parts it optimses:
> 
> * locking for emitting CQEs (kernel side)
> * not checking for CQ waiters (may be expensive)  and potentially unnecessary waking them (kernel side)
> * may improve userspace CQE handling

Another question: Will there be something like IORING_FEAT_SUPRESS_CQE_ON_SUCCESS?

**Comment by isilence** [comment]
> Another question: Will there be something like IORING_FEAT_SUPRESS_CQE_ON_SUCCESS?

Good idea to add

**Comment by CarterLi** [comment]
> > Another question: Will there be something like IORING_FEAT_SUPRESS_CQE_ON_SUCCESS?
> 
> Good idea to add

Well, I don't think Axboe like add more IORING_FEAT flags. I can accept if older kernels ignore this flag. In this case I can ignore CQEs whose user_data is NULL.

**Comment by isilence** [comment]
> > > Another question: Will there be something like IORING_FEAT_SUPRESS_CQE_ON_SUCCESS?
> > 
> > 
> > Good idea to add
> 
> Well, I don't think Axboe likes adding more IORING_FEAT flags. I can accept if older kernels ignore this flag silently. In this case I can ignore CQEs whose user_data is NULL.

The argument is against adding a flag for each small behavioural deviation or a tiny feature of one specific opcode. It's a big enough and generic feature, IMHO a good candidate for IORING_FEAT*.

**Comment by axboe** [comment]
I think a FEAT flag for this purpose is a good idea.

**Comment by ioquatix** [comment]
I'm not sure if a per-io_uring feature flag works because there are some opcodes where you don't care about success (e.g. close) and others where you do (e.g. poll).

However, maybe one way to control this is when `user_data` is `NULL` indicates you don't care about the result.

**Comment by axboe** [comment]
Some people do care about close(2).

The kernel should place no value into what user_data may or may not contain. That's purely an application interpreted value. The FEAT flag just tells you that the feature is available, it still needs to get turned on for a request. And user_data is not the way to do that.

**Comment by isilence** [comment]
> I'm not sure if a per-io_uring feature flag works because there are some opcodes where you don't care about success (e.g. close) and others where you do (e.g. poll).

@ioquatix, IORING_FEAT* is about testing at runtime whether a feature is supported or not. The actual implementation is a per SQE flag, i.e. IOSQE_*. 
 
> However, maybe one way to control this is when `user_data` is `NULL` indicates you don't care about the result.

I'd break the userspace. It actually looks to me that the left "ignore always" variant is rather too marginal to burden the kernel with it. For instance, the current patch adds only one extra "if" per request (almost) in the hot path.

**Comment by CarterLi** [comment]
What about `IORING_FEAT_SUPRESS_CQE_ON_SUCCESS && user_data == NULL` means `ignore always`?

I saw the special case for `IORING_OP_LINK_TIMEOUT`. With `ignore always`, we don't need to handle this special case. The same behavior applies to `IORING_OP_TIMEOUT`, which falls always with `-ETIME` too.

Another case is `IOSQE_IO_HARDLINK`. With `IOSQE_IO_HARDLINK` specified, users mean to ignore the failed requests always. For example `TIMEOUT-(HARDLINK)-SOME_OP`, `SPLICE-(HARDLINK)-SPLICE`

**Comment by axboe** [comment]
> What about IORING_FEAT_SUPRESS_CQE_ON_SUCCESS && user_data == NULL means ignore always?

Hard no, for two reasons. Reason 1 being that, as Pavel expanded on, FEAT is a reporting flag. You would _break_ applications with that kind of assumption. Reason 2 being that we will not ever imply any meaning to user_data. It's simply passed through the kernel, and it means nothing to the kernel.

And there's imply no need for this. There's an SQE flag for this very purpose. If the SQE supress-cqe flag is set, no cqe is generated. It's that simple. No need to imply further magic meaning of anything for that.

**Comment by CarterLi** [comment]
> > What about IORING_FEAT_SUPRESS_CQE_ON_SUCCESS && user_data == NULL means ignore always?
> 
> Hard no, for two reasons. Reason 1 being that, as Pavel expanded on, FEAT is a reporting flag. You would _break_ applications with that kind of assumption. Reason 2 being that we will not ever imply any meaning to user_data. It's simply passed through the kernel, and it means nothing to the kernel.
> 
> And there's simply no need for this. There's an SQE flag for this very purpose. If the SQE supress-cqe flag is set, no cqe is generated. It's that simple. No need to imply further magic meaning of anything for that.

OK.

In this case, I'd suggest that instead of specifying a special case for `IORING_OP_LINK_TIMEOUT`, we should better make `IOSQE_SUPRESS_CQE_ON_SUCCESS` work with `IOSQE_IO_HARDLINK`: if `IOSQE_IO_HARDLINK` is used together with `IOSQE_SUPRESS_CQE_ON_SUCCESS`, the linked SQE should never generate a CQE, no matter if it's errored or not.

For example:

1. `LINK_TIMEOUT(SUPRESS_CQE_ON_SUCCESS) --HARDLINK-- READ`: IORING_OP_LINK_TIMEOUT should never generate a CQE
2. `TIMEOUT(SUPRESS_CQE_ON_SUCCESS) --HARDLINK-- READ`: IORING_OP_TIMEOUT should never generate a CQE
3. `TIMEOUT(SUPRESS_CQE_ON_SUCCESS) --LINK-- READ`: IORING_OP_TIMEOUT should generate a CQE, because it falls with `-ETIME`

It's a much more general way than specifying a special behavior for a special request type

**Comment by isilence** [comment]
Let's start with normal timeouts, I have no clue why -ETIME is a fail, we just need to make it sane and stop doing that... It'd probably break the userspace, so may do via a new timeout flag. E.g. (kernel code)

```C
timeout_callback(req) {
	if (!(req->timeout_flags & IORING_TIMEOUT_DONT_FAIL_FIRED))
		req_set_fail(req);
	io_req_complete_post(req, -ETIME, 0);
}
```

That's a good case you mentioned, but I'd rather say it's our problem in "fail" semantics. With that fixed, I don't see why we'd want to ignore fails. 

Linked timeouts are a special case because 1) it makes sense, its result is visible through errors of main request, unlike for every other opcode. And nothing else is wanted from it.  2) Because it's racy, e.g. you can get a success for the main request and -ETIME for the linked timeout.

> In this case, I'd suggest that instead of specifying a special case for IORING_OP_LINK_TIMEOUT, we should better make IOSQE_SUPRESS_CQE_ON_SUCCESS work with IOSQE_IO_HARDLINK: if IOSQE_IO_HARDLINK is used together with IOSQE_SUPRESS_CQE_ON_SUCCESS, the linked SQE should never generate a CQE, no matter if it's errored or not.

Let me know if there is even a need in this after the timeout change, but I see it restricting use cases. It should be possible to do something like ```read(sz=4096) ->(HARDLINK) notify() // e.g. write(eventfd), bpf, etc.``` The notified side, would go through a CQ, and if there is nothing, it'd just assume it's completed with 4096.

**Comment by hassila** [comment]
For me IOSQE_SUPRESS_CQE_ON_SUCCESS + FEAT checking removes the majority of overhead, glad to see this moving forward!

**Comment by CarterLi** [comment]
I just want it constant. If TIMEOUT with IOSQE_IO_LINK will fail, TIMEOUT with SUPRESS_CQE_ON_SUCCESS should fall. if IOSQE_IO_HARDLINK just works no matter if the request fails, SUPRESS_CQE_ON_SUCCESS with IOSQE_IO_HARDLINK should work like that.

> Let me know if there is even a need in this after the timeout change

I had an example before:

`splice(filefd1, pipefd1, -1)` --HARDLINK-- `splice(pipefd2, sockfd2, -1)`

`splice(filefd1, pipefd1, -1)` fails always because there's no enough bytes to read in filefd1 or there's no enough buffer in pipefd2. But it doesn't matter. `splice(pipefd2, sockfd2, -1)` should work as expected because kernel knows how many bytes can be read in pipefd2

**Comment by isilence** [comment]
Back to the problem.

@CarterLi, would have been great to have it simpler, but I think we should be able to derive result from the io_uring state.

IIRC, the main use cases for hard links is some kind of notification like eventfd. For instance, if we have OP1 ->(hard) write(efd), we may be not interested in CQE of the write(efd), so perhaps can be supressed, but the waked thread should be able to see an error if it occured.
Another case is hardlinking some kind of reactor, BPF request in particular, and it's pretty much interested in seeing an error if there was one.

**Comment by CarterLi** [comment]
> Back to the problem.
> 
> @CarterLi, would have been great to have it simpler, but I think we should be able to derive result from the io_uring state.
> 
> IIRC, the main use cases for hard links is some kind of notification like eventfd. For instance, if we have OP1 ->(hard) write(efd), we may be not interested in CQE of the write(efd), so perhaps can be supressed, but the waked thread should be able to see an error if it occured. Another case is hardlinking some kind of reactor, BPF request in particular, and it's pretty much interested in seeing an error if there was one.

In this case

`OP1(no flags) --hard-- write(IOSQE_SUPRESS_CQE_ON_SUCCESS)`

* OP1 will generate CQE because IOSQE_SUPRESS_CQE_ON_SUCCESS is not specified.
* write will generate CQE on success only

For `OP1(IOSQE_SUPRESS_CQE_ON_SUCCESS) --hard-- write(IOSQE_SUPRESS_CQE_ON_SUCCESS)`, OP1 will not generate CQE as I suggested.

**Comment by isilence** [comment]
> > Back to the problem.
> > @CarterLi, would have been great to have it simpler, but I think we should be able to derive result from the io_uring state.
> > IIRC, the main use cases for hard links is some kind of notification like eventfd. For instance, if we have OP1 ->(hard) write(efd), we may be not interested in CQE of the write(efd), so perhaps can be supressed, but the waked thread should be able to see an error if it occured. Another case is hardlinking some kind of reactor, BPF request in particular, and it's pretty much interested in seeing an error if there was one.
> 
> In this case
> 
> `OP1(no flags) --hard-- write(IOSQE_SUPRESS_CQE_ON_SUCCESS)`
> 
>     * OP1 will generate CQE because IOSQE_SUPRESS_CQE_ON_SUCCESS is not specified.
> 
>     * write will generate CQE on success only
> 
> 
> For `OP1(IOSQE_SUPRESS_CQE_ON_SUCCESS) --hard-- write(IOSQE_SUPRESS_CQE_ON_SUCCESS)`, OP1 will not generate CQE as I suggested.

That's exactly the problem, in most cases on failure users would still want to get an error. The simplest example is if OP1 is write(socket), and repeating again the same request is not an option, but there are more. There might be cases as yours where you can derive the state from something apart from io_uring, e.g. from pipes, but that doesn't look to me generic enough to cover all cases.

**Comment by ioquatix** [comment]
@axboe do you mind pointing me at what was eventually implemented? Thanks!

**Comment by isilence** [comment]
@ioquatix,

https://github.com/axboe/liburing/blob/master/man/io_uring_enter.2#L1131
https://lore.kernel.org/all/0220fbe06f7cf99e6fc71b4297bb1cb6c0e89c2c.1636559119.git.asml.silence@gmail.com/

It's just one flag in the end but it covers most of the cases. In short, If a request succeeds it doesn't post a CQE, if fails it adds an error CQE but suppresses completion generation from all requests linked to it. That's true for all request types but linked timeouts, which have different rules.

For non-hard links without linked timeouts
1) if you set the skip flag to all requests except the last one, it'll generate only one CQE per link.
2) if you set it to all requests, you get only 1 CQE and only in case it fails. Same for standalone requests, i.e. not links.

Same rules for linked timeouts, but when it started execution of the request the linked timeout is attached to, the flag will unconditionally silence the result from the timeout.

3) `OP1 -> linked timeout (SKIP_SUCCESS)`, will only generate one CQE for `OP1`, which can be `-ECANCELED` if it was killed by the timeout.

And there might be more ways to use it.
