### ISSUE TITLE
io_uring-worker ?

### ISSUE THREAD

**Issue by YoSTEALTH** [axboe/liburing#323]
I been wanting to try out new `io_uring-worker` but can't find it in Liburing! Is this feature not added yet? I am on `Linux 5.12`.

**Comment by axboe** [comment]
The feature is transparent, there's nothing you (or liburing) needs to do to take advantage of it. 5.12-rc has it already, 5.11 does not (yet...).

**Comment by YoSTEALTH** [comment]
I see, that's cool.

What is the use case for `IORING_FEAT_NATIVE_WORKERS` ?

**Comment by isilence** [comment]
In theory, it's nothing that should be visible to a normal userspace app. Nevertheless opens up some stuff, like
allowing CMSG, and non-privileged SQPOLL (now with this FEAT, but in 5.13), etc.

**Comment by YoSTEALTH** [comment]
"non-privileged SQPOLL" would be really handy
