### ISSUE TITLE
Add IORING_SETUP_SQPOLL_SHARED_POLLTHREAD (feature request)

### ISSUE THREAD

**Issue by hassila** [axboe/liburing#325]
### Background
Cleanup of discussion in #324 

It's currently possible to use a single SQPOLL kernel thread by specifying a previously existing io_uring instances fd with wq_fd and setting IORING_SETUP_ATTACH_WQ.

For some (most?) use cases, one only wants a single polling kernel thread as multiple io_uring instances are commonly created by users of a framework (up to NCPU:s or sometimes even a few more...).

For robustness, I simply create a minimal SQPOLL-enabled io_uring instance the first time a user of the framework asks for SQPOLL, and then subsequently uses that  minimal io_uring instance ring fd for wq_fd for the rest of the io_urings as needed - this works fine, but it would be nice to avoid the minimal io_uring instance (or otherwise bookkeeping to keep track of valid instances), but doesn't work easily when there are multiple peer frameworks who might use independent rings it would be nice to let peer frameworks / libraries who use io_uring to be able to shared a single sqpoll kernel thread.

### Feature request

Add a new flag: `IORING_SETUP_SQPOLL_SHARED_POLLTHREAD` which if set, will automatically attach to a shared sqpoll kernel thread if one exists, otherwise create a shared instance (for the process). 

### Benefits

This makes it trivial from the user side to share the sqpoll thread which is helpful for some (many?) use cases
It also makes it possible to share the kernel poll thread even if multiple peer frameworks use io_uring independently - this will likely become more important going forward as io_uring usage proliferates.

**Comment by isilence** [comment]
I'm on the side that the kernel should stay as slim as possible, and if something can be done from the usespace it should be it. I like the multi framework argument, but frankly using multiple rings sounds wrong -- you need to somehow bind them, e.g. for CQE waiting, adding something artificial like eventfd notifying from one ring to another or other option, and that's a huge burden. Anyway, frameworks if so necessary can provide some way/extension exposing rings/ring_fd/etc. outside.

So, tbh, I don't see a good reason why to put it into the kernel...

**Comment by hassila** [comment]
Ok, fair enough - it definitely possible to work around it, so let's close, thanks for consideration.
