### ISSUE TITLE
Possible bug with IOSQE_IO_DRAIN

### ISSUE THREAD

**Issue by tchaloupka** [axboe/liburing#33]
Hi,
I'm trying to test various aspects of `io_uring` and came to fsync test in this lib.
I've noticed this line: https://github.com/axboe/liburing/blob/master/test/fsync.c#L117
and added just a printf to let me know if my kernel is ok with it or not.

And unfortunatelly it doesn't work.
I've tested it on kernels 5.2.x (where this flag was introduced) and kernel 5.3.x.
It just returns that error and I don't understand why..

When I've added `IOSQE_IO_LINK` to sumbission flags of flush operation, it started to run ok.

But it seems to be against what is documented and what is actually tested with the `IOSQE_IO_DRAIN`.

I've also tried to search the internet if someone already hasn't faced the same issue and found only this maybe relevant post: https://www.mail-archive.com/linux-block@vger.kernel.org/msg39033.html, but without any followup..

It this an issue or some misunderstanding? Thanks!

PS: This line https://github.com/axboe/liburing/blob/master/test/fsync.c#L101 should probably be `if (ret == -EINVAL)` but is unrelated to this problem.

**Comment by axboe** [comment]
Interesting, I completely missed that email from Andres. I just tried all of this on my current tree, and I don't see any issues. I'll try 5.3 as well.

**Comment by axboe** [comment]
[drain.txt](https://github.com/axboe/liburing/files/3922780/drain.txt)

I've sent this patch in for stable, the issue is affecting 5.2..5.4 (not current 5.5-git). It should show up in stable, or feel free to apply this patch to fix it. The patch is against 5.4, will apply against 5.3 and 5.2 if  you remove the last hunk from the patch.
