### ISSUE TITLE
Waiting on single `POLL_OUT` event doesn't seem to trigger correctly.

### ISSUE THREAD

**Issue by ioquatix** [axboe/liburing#333]
Thanks for inventing `liburing` and `io_uring`, and I'm very excited about it.

I'm integrating `io_uring` into Ruby and I'm encountering a problem which I don't understand. In addition, we have implementations using `select` and `epoll` which appear to be working.

So, we are building an interface and the most basic interface is `io_wait(file descriptor, events)`. Events can be readable,  writable or priority.

We are adopting fiber based concurrency which means we switch away from a fiber while it's waiting for an event to complete.

So, here is the test that's failing:

```ruby
local, remote = UNIXSocket.pair

fiber = Fiber.new do
	events << :wait_writable
	subject.io_wait(Fiber.current, local, Event::WRITABLE)
	events << :writable
end

events << :transfer
fiber.transfer

events << :select
# (1) write to remote end of socket:
# remote.puts "Hello World"
subject.select(1)

expect(events).to be == [
	:transfer, :wait_writable,
	:select, :writable
]
```

This event never triggers. However, seemly unrelated, if we write to the remote end of the socket (1), the test will pass.

I checked all the io_uring code and it seems fine to me.

Here is where we submit the event:

https://github.com/socketry/event/blob/c533c7c7188ba5d16eeb599d0c736c60b713f635/ext/event/backend/uring.c#L99-L132

Here is where we read the events that are completed:

https://github.com/socketry/event/blob/c533c7c7188ba5d16eeb599d0c736c60b713f635/ext/event/backend/uring.c#L160-L192

I actually don't know if this is a bug with `io_uring` or just Linux in general, however the exact same code, using `epoll` passes, which makes me suspicious that we are doing something wrong with `io_uring`.

Any thoughts or ideas would be most helpful.

**Comment by hassila** [comment]
You are trying reading the event twice if duration is set? io_uring_wait_cqe_timeout will reap the first pending event which you don’t process (and you don’t call io_uring_cqe_seen for it), then you try to get events with io_uring_peek_batch_cqe again.

**Comment by ioquatix** [comment]
Ohhhhhhhhh that might make sense. Okay, I'll try to fix it now I have this information. Is there a better way to wait for the timeout?

**Comment by hassila** [comment]
I've usually first tried to do a peek to reap max events and process - only if peek is empty, I would call the wait (and then just reap a single event, but if more were pending they would be reaped the next time around in my case).

**Comment by ioquatix** [comment]
That makes total sense.

Well, I tried this, and it didn't work:

<img width="918" alt="image" src="https://user-images.githubusercontent.com/30030/116057387-da417d00-a6d2-11eb-8b67-957134464f6a.png">

**Comment by ioquatix** [comment]
Okay, following your advice, this seemed to work:

<img width="952" alt="image" src="https://user-images.githubusercontent.com/30030/116058008-81beaf80-a6d3-11eb-951a-960168d4f48a.png">

Do you have any suggestions about that approach?

**Comment by ioquatix** [comment]
Okay, I tried the original test and it's still failing even with this updated code:

<img width="953" alt="image" src="https://user-images.githubusercontent.com/30030/116058837-5ab4ad80-a6d4-11eb-8c5a-6d0dea680cdb.png">

Not sure what's going on here, it seems like the result is 0, and then -62 (-ETIME).

**Comment by ioquatix** [comment]
It's odd because the test passes if you just write to the remote end, but that doesn't impact the flow of the event loop in any way.

**Comment by hassila** [comment]
It seems that you get flags == 2, which would be just "POLLPRI"? Seems you might want to check how the mask is specified.

**Comment by ioquatix** [comment]
Okay that seems like it could be a issue thanks I will check it. Your insight is most helpful :)

**Comment by ioquatix** [comment]
Okay, I took a look at the constant values on my computer:

![image](https://user-images.githubusercontent.com/30030/116153844-0fce8080-a73c-11eb-99f7-a4fecf22c6d2.png)

It seems like 2 is the correct value for "writable" i.e. `POLL_OUT`.

**Comment by ioquatix** [comment]
Looking at https://github.com/axboe/liburing/blob/ba57d216074196b2e298e36059dcb3b238630c95/test/connect.c#L58, I see that `io_uring_prep_poll_add` is using `POLLIN`, `POLLOUT`, `POLLPRI`, etc directly.

Also, looking at the constants `POLL_IN`, `POLL_OUT`, `POLL_PRI` etc, they seem to be bit offsets rather than flags.

i.e.

```
[cling]$ POLL_IN
((anonymous)) (POLL_IN) : (unsigned int) 1
[cling]$ POLL_OUT
((anonymous)) (POLL_OUT) : (unsigned int) 2
[cling]$ POLL_PRI
((anonymous)) (POLL_PRI) : (unsigned int) 5
[cling]$ POLL_HUP
((anonymous)) (POLL_HUP) : (unsigned int) 6
[cling]$ POLL_ERR
((anonymous)) (POLL_ERR) : (unsigned int) 4
```

If these are flags, you cannot distinguish `POLL_PRI` from `POLL_IN | POLL_ERR`. What am I missing here? Should I be converting `POLL_XYZ` into a mask by shifting a bit? e.g.

```
static inline
int mask(int bit) {
	return 1 << (bit - 1);
}

static inline
short poll_flags_from_events(int events) {
	short flags = 0;
	
	if (events & READABLE) flags |= mask(POLL_IN);
	if (events & PRIORITY) flags |= mask(POLL_PRI);
	if (events & WRITABLE) flags |= mask(POLL_OUT);
	
	flags |= mask(POLL_ERR);
	flags |= mask(POLL_HUP);
	
	return flags;
}
```

Or should I be using `POLLXYZ` constants directly? (they don't seem to be the same even if you shift the bits).

**Comment by ioquatix** [comment]
Here is what I ended up with and tests confirm it's working: https://github.com/socketry/event/blob/master/ext/event/backend/uring.c#L99-L146

I think the `POLL_` constants are misleading and this should be more clearly documented. Either I've made a mistake, or something is wrong with the implementation.

**Comment by hassila** [comment]
You were right in using POLLXYX directly from poll.h
