### ISSUE TITLE
io_uring_queue_exit returns void, man page says it returns int.

### ISSUE THREAD

**Issue by le-migou** [axboe/liburing#337]
Which one should it be?

**Comment by isilence** [comment]
https://github.com/axboe/liburing/blob/7ff4feed7e93e42fb7cec689f7131535f1a128ca/man/io_uring_queue_exit.3#L22-L23

https://github.com/axboe/liburing/blob/7ff4feed7e93e42fb7cec689f7131535f1a128ca/src/include/liburing.h#L113

Please specify where man says so.

**Comment by le-migou** [comment]
In the synopsis, line 13:

    .BI "int io_uring_queue_exit(struct io_uring *" ring );

**Comment by isilence** [comment]
> In the synopsis, line 13:
> 
> ```
> .BI "int io_uring_queue_exit(struct io_uring *" ring );
> ```

Got it, should be corrected. The function returns nothing since the very first day.

**Comment by isilence** [comment]
Want to send a patch fixing the description?

**Comment by isilence** [comment]
And `"`s are set strangely in that line as well

**Comment by le-migou** [comment]
Here it is.

Le 04/05/2021 à 12:46, Pavel Begunkov a écrit :

**Comment by le-migou** [comment]
Sorry I don't know how to join a patch to a comment. I'll make a PR.

**Comment by isilence** [comment]
It's either a patch to `io-uring@vger.kernel.org`, or Jens takes PRs
