### ISSUE TITLE
Question about versioning

### ISSUE THREAD

**Issue by withoutboats** [axboe/liburing#34]
Thanks for your work on io_uring, its a really stellar interface! I'm working on wrapping liburing in a Rust library to make it accessible from Rust (as well as higher level memory-safe integrations into our async/.await ecosystem, which haven't born fruit yet).

First, I just want to confirm this is the best place for you to receive questions & pull requests. Let me know if not.

My main question: what is the backwards compatibility story for liburing right now? In general, would you say you will not remove or break APIs exposed by liburing (excepting obviously `__` functions for example)? I noticed that you recently removed the syscall helpers from liburing, but I think that was a special case because you expect them to be upstreamed to glibc.

I'm asking to determine my own versioning for my Rust wrappers. Most Rust users use cargo to perform version resolution for them, and cargo makes strong assumptions about backwards compatibility between "semver compatible" versions, so I just need to figure out if I should prepare for possible breaking changes between updates to liburing.

**Comment by axboe** [comment]
Thanks! In general, I try not to break anything, ever. What worked with liburing 0.1 should also work with 0.3 (when that's released, in a week or two) without any changes needed on the application side. The syscall wrappers were indeed an exception, and honestly those should only have been used by liburing to begin with. So for strong cases, I might make an exception. We're getting pretty far down the line at this point and folks are relying on it, so I try to take the compatibility aspect seriously. Coming from a kernel background where we never break ABI (knowingly), this is what I intend to do for liburing as well.

I'm fine with using github for discussion and issues, it's been working OK so far. Ditto for pull requests, as long as the commits in the pull request adhere to the style used in liburing already (one line title, 72/74 chars wide at most, decent commit message, and signed-off-by at the end).

**Comment by withoutboats** [comment]
Sounds great! That's what I hoped your policy was.

Are there any other definitions exposed through the header files that are meant to be private but not prefixed with `_`? I'll make sure not to re-export them if so.

**Comment by withoutboats** [comment]
One last question, what's the best way to be notified when you release a new version of liburing? Right now I've been proactively tracking git master, but in the longer term I'd like to only depend on release versions of liburing and to be notified when a new version is coming out.

**Comment by axboe** [comment]
> Are there any other definitions exposed through the header files that are meant to be private but not prefixed with _? I'll make sure not to re-export them if so.

Just the single __io_uring_get_cqe() declaration and export, but that should already be covered under the "__ is not really meant to be used directly" clause.

**Comment by axboe** [comment]
For notifications, not sure but doesn't github support getting notified when a new release is tagged? If it does, that would probably be the easiest way. I've seen you on twitter as well, and I will announce releases there too, but that's more likely to drown in noise, I'm sure...

**Comment by withoutboats** [comment]
> Just the single io_uring_get_cqe() declaration and export, but that should already be covered under the " is not really meant to be used directly" clause.

Was also clear from its `__` prefix! Thanks so much!
