### ISSUE TITLE
io_uring_sq_ready() question

### ISSUE THREAD

**Issue by lano1106** [axboe/liburing#342]
I am spotting 1 assumption in that function and I want to open a discussion about those to make sure that this code is 100% correct.

io_uring_sq_ready() is assuming that for non-SQPOLL setup, this function is necessarily called after having used io_uring_get_sqe() and skip acquiring the memory barrier.

Is the result valid if io_uring_sq_ready() if called after returning from io_uring_enter() and before having called io_uring_get_sqe()?

Is the barrier acquisition that expensive to warrant this micro-optimization that is risking to return an invalid result?

**Comment by lano1106** [comment]
I ended up using 'iouring_ring.sq.sqe_tail - iouring_ring.sq.sqe_head' like what is done in function __io_uring_flush_sq() to compute the io_uring_enter() to_submit param value.

This seems to be the foolproof way to find out the number of unsubmitted sqes in non SQPOLL setup...

Not sure exactly why this is not how io_uring_sq_ready() is doing it or when someone would prefer io_uring_sq_ready() over the local  'iouring_ring.sq.sqe_tail - iouring_ring.sq.sqe_head' method...

**Comment by YoSTEALTH** [comment]
There is also `io_uring_sq_space_left` https://github.com/axboe/liburing/blob/master/src/include/liburing.h#L571

**Comment by isilence** [comment]
Not sure why you need to know number of SQEs you're submitting, Are you using `io_uring_submit`, because it should do all the job for you.

Regarding synchronisation, putting aside whether it's a meaningful optimisation, there single threaded users, who are in-sync by design, why would you add it in their way just for your use case?

**Comment by lano1106** [comment]
here is the reason:
I add sqes in 1 function (lets call it funcA), and I do the sqes submission and cqes in another function (funcB).

The state about if submission is needed or not is transported by one function to the other with the struct io_uring handle.

in this second function, I am going to call io_uring_enter() (indirectly through the API) only if there is something to submit or if a non-null timeout param has been passed.

Also, I am going to select io_uring_wait_cqe_timeout() if I have a non-null timeout or else call io_uring_submit().

My code looks like this in funcB:
```

  /* only enter the kernel if we have something to submit, or we need to wait */
  unsigned to_submit = iouring_ring.sq.sqe_tail - iouring_ring.sq.sqe_head;
  if (timeout || to_submit)
    {
      int res;
      if (timeout)
          res = iouring_enter (EV_A_ timeout);
      else
          // This will even not make a syscall if SQPOLL enabled.
          res = io_uring_submit(&iouring_ring);
```

Now the issue that I have tried to explain in the opening of this thread is this.

io_uring_sq_ready() needs a memory barrier to make sure that when it use sq head, it is the right value even if SQPOLL is not set.
The memory barrier protection is invoked in io_uring_get_sqe() but when funcB is called, I just don't know if io_uring_get_sqe() has been called since I have returned from io_uring_enter().

Therefore its usage is unsafe, imho.

and as I have discovered. I can do 'iouring_ring.sq.sqe_tail - iouring_ring.sq.sqe_head' to answer my question just like how liburing code do.

**Comment by YoSTEALTH** [comment]
I had solved this problem by adding external counters, so I suppose in your case every time you `io_uring_get_sqe()` you `count += 1` and `if count: io_uring_submit(ring); count = 0`

For my case I have to account for event loop going from python to io_uring and back, also have to account for when to place io_uring into wait state.

**Comment by lano1106** [comment]
The wrong impression that I got about memory barrier may in part be coming from the comment at the fs/io_uring.c file:

 

> A note on the read/write ordering memory barriers that are matched between
> the application and kernel side.
> 
> After the application reads the CQ ring tail, it must use an
> appropriate smp_rmb() to pair with the smp_wmb() the kernel uses
> before writing the tail (using smp_load_acquire to read the tail will
> do). It also needs a smp_mb() before updating CQ head (ordering the
> entry load(s) with the head store), pairing with an implicit barrier
> through a control-dependency in io_get_cqring (smp_store_release to
> store head will do). Failure to do so could lead to reading invalid
> CQ entries.
> 
> Likewise, the application must use an appropriate smp_wmb() before
> writing the SQ tail (ordering SQ entry stores with the tail store),
> which pairs with smp_load_acquire in io_get_sqring (smp_store_release
> to store the tail will do). And it needs a barrier ordering the SQ
> head load before writing new SQ entries (smp_load_acquire to read
> head will do).

Would it be more accurate to mention that all that is only applicable if SQPOLL thread is activated?
