### ISSUE TITLE
Issue generating core dumps since using io_uring

### ISSUE THREAD

**Issue by lano1106** [axboe/liburing#346]
I took care of the usual suspects when this is happening.

ulimit -c unlimited

Adding:
prctl(PR_SET_DUMPABLE, 1);
in the main() because I do set few cap bits to the binary exec file.

When my io_uring process is killed with SEGV signal, the generated core dump has a size of 0 bytes.

Could it be related to some security feature around the fact that memory is shared with the kernel when using io_uring?

If it is, any way to circumvent the kernel from NOT core dumping?
Not having core dumps is seriously reducing my capability to debug my app...

**Comment by isilence** [comment]
Weird. Try to do a fair experiment -- first crash the same exactly code with all yours prctl but without io_uring, and then with it.
I really doubt it's io_uring related.

**Comment by lano1106** [comment]
Almost there but why is it so painful....

$ ./io_uring_echo_server 1976
io_uring echo server listening for connections on port: 1976
Before memset() in io_uring_queue_mmap(): p->sq_entries: 2048
After memset() in io_uring_queue_mmap(): p->sq_entries: 0
io_uring_init_failed...
: Invalid argument

**Comment by lano1106** [comment]
ok ok... I'm getting sloppy... I should take a day off to have a clearer mind... My function succeeds and I do use 2 io_uring instances.

Let me change things to force epoll instead...

**Comment by lano1106** [comment]
no I do not think that it is:

```
top - 10:59:49 up 10:44,  2 users,  load average: 2.31, 2.11, 2.04
Threads: 199 total,   3 running, 196 sleeping,   0 stopped,   0 zombie
%Cpu(s):  0.2 us,  0.2 sy, 24.9 ni, 74.5 id,  0.0 wa,  0.0 hi,  0.1 si,  0.0 st
MiB Mem :  64267.1 total,  60413.3 free,   3271.9 used,    581.9 buff/cache
MiB Swap:      0.0 total,      0.0 free,      0.0 used.  60395.7 avail Mem 

P     PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND          
2    1101 lano1106 -99   0  380852  23664  10588 S   2.7   0.0   0:02.74 test      
1     404 lano1106  20   0   15944   9092   7644 S   0.0   0.0   0:00.03 systemd          
4     405 lano1106  20   0   21652   2692      0 S   0.0   0.0   0:00.00 (sd-pam)         
4     411 lano1106  20   0   12848   4404   3148 S   0.0   0.0   0:00.04 sshd             
5     414 lano1106  20   0   12848   4492   3240 S   0.0   0.0   0:00.62 sshd             
0     415 lano1106  20   0    8564   4936   3376 S   0.0   0.0   0:00.01 bash             
0     441 lano1106  20   0   10820   3956   3388 R   0.0   0.0   0:52.06 top              
1     497 lano1106  20   0   13260   5528   3856 S   0.0   0.0   0:01.60 sshd             
0     498 lano1106  20   0    9072   5728   3708 S   0.0   0.0   0:00.15 bash             
4    1103 lano1106  20   0  380852  23664  10588 S   0.0   0.0   0:00.00 Logging          
4    1106 lano1106  20   0  380852  23664  10588 S   0.0   0.0   0:00.00 Housekeeping     
2    1107 lano1106 -99   0  380852  23664  10588 S   0.0   0.0   0:00.00 iou-mgr-1101     
5    1110 lano1106  20   0  380852  23664  10588 S   0.0   0.0   0:00.00 MariaDB   
0    1111 lano1106  20   0  380852  23664  10588 S   0.0   0.0   0:00.00 Account   
3    1112 lano1106  rt   0  380852  23664  10588 S   0.0   0.0   0:00.00 Execution SVC    
3    1113 lano1106  rt   0  380852  23664  10588 S   0.0   0.0   0:00.00 iou-mgr-1112     
6    1114 lano1106 -99   0  380852  23664  10588 S   0.0   0.0   0:00.00 iou-wrk-1101     
5    1109 lano1106  20   0    5396    740    656 S   0.0   0.0   0:00.00 tail 
```

**Comment by lano1106** [comment]
Here is a quick test program that attempts to capture the essence of my app io_uring usage.
My libev app crash when completion events are processed.
I assume that when it crash, 1 thread is inside io_uring_enter, while the other is processing the events.
The way libev does its magic inside its main_function ev_run:
1. Add new fd to the fd set
2. Call backend_poll (io_uring_enter)
3. Process all cqes and put them in a standard format in a pending event list
4. After having returned from backend_poll, traverse the pending event list and call the registered user callbacks (This is where my app crash when it does)

Rename to [test_io_uring_coredump.cpp
[test_io_uring_coredump.txt](https://github.com/axboe/liburing/files/6461578/test_io_uring_coredump.txt)

**Comment by lano1106** [comment]
I did find fs/coredump.c

It can leaves some traces when the kernel has some problems with generating the coredump. I see nothing in dmesg...

The only differences that I see between epoll and io_uring is the kernel thread iou-mgr-xxx and iou-wrk-xxx...

Is it possible that the way those kernel threads get terminated during the crash, is stopping the kernel from generating the dump?

This start to be above my skillset/knowledge at this point...

```
$ sudo dmesg | grep core
[    0.285670] watchdog: Disabling watchdog on nohz_full cores by default
[    0.291118] pinctrl core: initialized pinctrl subsystem
[    0.388245] usbcore: registered new interface driver usbfs
[    0.388245] usbcore: registered new interface driver hub
[    0.388245] usbcore: registered new device driver usb
[    0.388245] pps_core: LinuxPPS API ver. 1 registered
[    0.388245] pps_core: Software ver. 5.3.6 - Copyright 2005-2007 Rodolfo Giometti <giometti@linux.it>
[    0.730500] usbcore: registered new interface driver usbserial_generic
[    0.731814] intel_pmc_core INT33A1:00:  initialized
[    3.346239] RAPL PMU: hw unit of domain pp0-core 2^-14 Joules
[    3.780473] usbcore: registered new interface driver usbhid
[    3.780474] usbhid: USB HID core driver
[    4.031182] intel_rapl_common: Found RAPL domain core
[25066.617500] audit: type=1130 audit(1620742357.635:157): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-coredump@0-1029-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[25067.005283] audit: type=1131 audit(1620742358.025:158): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-coredump@0-1029-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
```

**Comment by lano1106** [comment]
isilence, I think that I have unmasked you. I was looking emails that I did exchange with io_uring list and I have just noticed that one of the list participants does have silence in his email address ;-)

Yes, I can modify my code to revert back to the polling only io_uring usage... It should take me few hours to do and report back the results.

Can you be more explicit about what I should do with the IOSQE_ASYNC flag?
Is it meant to be used with IORING_OP_POLL_ADD/IORING_OP_POLL_REMOVE operations?
What is it for?

**Comment by isilence** [comment]
> oh. I have just read about IOSQE_ASYNC in the io_uring_enter() man page... Very useful flag... I already get something positive from all this misfortune... I can certainly make good use of it now that I am aware of it...
> 
> super cool! the API that keep surprise its users!
> 
> Most of my reads have to be ASYNC...

Don't remember what's in man, but don't get fooled by that cunning document. io_uring will always try to do its job in async manner and there are lots of mechanisms for that, but when it runs out of better options it will fallback to worker threads, that is a slow path. And IOSQE_ASYNC instructs to punt requests to the worker threads.

Poll requests are better off, they are async by other mean, bdev read/write as well, buffered reads got a better async path, for sockets -- it depends. Tl;dr; better to not use it unless you have a problem, e.g. with latency when `io_uring_enter()` takes too much time submitting requests.

**Comment by isilence** [comment]
I wasn't following the thread, but sounds similar

http://mail.spinics.net/lists/io-uring/index.html#08075
http://mail.spinics.net/lists/io-uring/msg08395.html

**Comment by isilence** [comment]
> I have seen the gdb related commit thread pass... My understanding of it was to make the threads more gdb friendly not that without the patch, core dump generation was impossible... thx for the pointers... I will carefully read them to see if they would contain the solution to my problem...

Not just friendly, gdb was not working with it doing some strange stuff in that case.
 
> Bottomline, if it solve my problem... This is 5.13 code and we are many weeks away from its release. Correct?

Yes, almost a full release, vaguely ~2 months (if it ever got applied)

**Comment by lano1106** [comment]
Ok. worse case scenario, it doesn't seem like a super big commit that would be a nightmare to apply on my 5.12 kernel source code.

Like every good problems, it seems this one is a multi step problem. First step is to get the core dump, next I'll start worrying about gdb...

Concerning the IOSQE_ASYNC, I believe that my TCP sockets would be good candidates for it. My epoll code was obviously manipulating non blocking fds. On my first io_uring async run, my read sqes were most of the time completed with the error EAGAIN.

iow, I have replaced the EPOLLIN polling with async reads...

**Comment by lano1106** [comment]
> Yes, almost a full release, vaguely ~2 months (if it ever got applied)

you are correct. Now that 5.13-rc1 is released, I have read that the targetted release date was something around the end of june...

**Comment by lano1106** [comment]
Ok I see what you mean when you said use IOSQE_ASYNC as a last resort only. Using that flag did create dozens of iou worker threads...

I do not like what I see in top... I will revert back from using IOSQE_ASYNC...

**Comment by victorstewart** [comment]
for what it's worth i ran the test program on my machine then triggered the crash and the core dumped.

```
root@clr-18a47c16c91c437c8ce854a37e6f5e26~ # uname -a
Linux clr-18a47c16c91c437c8ce854a37e6f5e26 5.12.1-1038.native #1 SMP Tue May 4 14:25:03 PDT 2021 x86_64 GNU/Linux

root@clr-18a47c16c91c437c8ce854a37e6f5e26~ # ./test_io_uring_coredump
Aborted (core dumped)
```

**Comment by victorstewart** [comment]
maybe your code using the io_uring path is poisoning the stack? aka you're overwriting it somehow somewhere so when it goes to produce the dump bad things happen?

**Comment by lano1106** [comment]
Hi Victor, same for me.

I haven't been able to reproduce the problem with the small test program. Something is missing in it. I believe that what might be missing is actually use the io_uring instances a bit before crashing it so that it has the chance to actually create an io_worker thread.

Since when I have posted the test program, I did find the source of my problem that was making my app crash with other means and I have been working on fixing it.

I suspect that this will become an io_uring classic. An IORING_OP_READ with the IOSQE_BUFFER_SELECT completes after its associated fd has been closed and the fd/lib user data structure to handle the result has already been destructed. Therefore, I was leaking buffers, and eventually, io_uring was returning me ENOBUFS.

I have been searching if the cqe would contain the bgid somewhere ... It didn't... I had to squeeze the bgid into user_data and I also had to store the buffer groups base addresses into the library doing the low-level handling to be able to return to io_uring the buffer when the describe situation arise...

I wonder if io_uring did foresee this scenario and if they did consider to add functionality to support the user to handle it such as
returning back the bgid in the cqe and somehow allow the user to query io_uring API to retrieve back the buffer group base address.

That being said, it wasn't that terrible to do the right thing on the user-space side alone...

All that to say, that I might have some time now to tweak the test program to make it do what it is designed to do....

**Comment by isilence** [comment]
btw, can be a problem of systemd-coredump of some other layer. Did you look through journalctl?

**Comment by lano1106** [comment]
good point. My problem is making systemd-coredump core dump as well ;-)

```
$ coredumpctl list
TIME                          PID  UID  GID SIG     COREFILE EXE                                     SIZE
Mon 2021-05-10 15:35:53 PDT 17192 1000 1000 SIGSEGV present  /usr/lib/systemd/systemd-coredump     601.0K
Mon 2021-05-10 21:29:40 PDT 17416 1000 1000 SIGSEGV present  /usr/lib/systemd/systemd-coredump     381.0K
Wed 2021-05-12 13:07:27 PDT  2414 1000 1000 SIGSEGV present  /usr/lib/systemd/systemd-coredump     452.8K
Wed 2021-05-12 20:31:43 PDT  7193 1000 1000 SIGSEGV present  /usr/lib/systemd/systemd-coredump     452.6K
```
but no, this isn't as trivial as this. I have changed /proc/sys/kernel/core_pattern to work around it and this is how I got the core dumps that I did open to document this ticket...

**Comment by lano1106** [comment]
Fixed by commit coredump: Limit what can interrupt coredumps
https://lore.kernel.org/io-uring/274c764afe34abdf06abc6a7eaf753a2911c967b.camel@trillion01.com/T/#t
