### ISSUE TITLE
unexpected high count of io_worker threads by using the IOSQE_ASYNC flag

### ISSUE THREAD

**Issue by lano1106** [axboe/liburing#349]
I am not sure if this is expected or not but I do have pretty much as many io worker threads as I have IORING_OP_READ requests on different TCP sockets.

```
$ uname -a
Linux tau 5.12.3-arch1-1 #1 SMP PREEMPT Wed, 12 May 2021 17:54:18 +0000 x86_64 GNU/Linux

$ ps -L --pid 10334
    PID     LWP TTY          TIME CMD
  10334   10334 pts/0    00:00:00 test
  10334   10336 pts/0    00:00:00 Logging
  10334   10338 pts/0    00:00:00 Housekeeping
  10334   10339 pts/0    00:00:00 iou-mgr-10334
  10334   10341 pts/0    00:00:00 MariaDB 
  10334   10342 pts/0    00:00:00 Account 
  10334   10343 pts/0    00:00:00 Execution SVC
  10334   10344 pts/0    00:00:00 iou-mgr-10343
  10334   10345 pts/0    00:00:00 iou-wrk-10343
  10334   10346 pts/0    00:00:00 iou-wrk-10343
  10334   10347 pts/0    00:00:00 iou-wrk-10334
  10334   10348 pts/0    00:00:00 iou-wrk-10334
  10334   10349 pts/0    00:00:00 iou-wrk-10334
  10334   10350 pts/0    00:00:00 iou-wrk-10334
  10334   10351 pts/0    00:00:00 iou-wrk-10334
  10334   10352 pts/0    00:00:00 iou-wrk-10334
  10334   10353 pts/0    00:00:00 iou-wrk-10334
  10334   10354 pts/0    00:00:00 iou-wrk-10334
  10334   10355 pts/0    00:00:00 iou-wrk-10334
  10334   10356 pts/0    00:00:00 iou-wrk-10334
  10334   10357 pts/0    00:00:00 iou-wrk-10334
  10334   10358 pts/0    00:00:00 iou-wrk-10334
  10334   10359 pts/0    00:00:00 iou-wrk-10334
  10334   10360 pts/0    00:00:00 iou-wrk-10334
  10334   10361 pts/0    00:00:00 iou-wrk-10334
  10334   10362 pts/0    00:00:00 iou-wrk-10334
  10334   10363 pts/0    00:00:00 iou-wrk-10334
  10334   10364 pts/0    00:00:00 iou-wrk-10334
  10334   10365 pts/0    00:00:00 iou-wrk-10334
  10334   10366 pts/0    00:00:00 iou-wrk-10334
  10334   10367 pts/0    00:00:00 iou-wrk-10334
  10334   10368 pts/0    00:00:00 iou-wrk-10334
  10334   10369 pts/0    00:00:00 iou-wrk-10334
  10334   10370 pts/0    00:00:00 iou-wrk-10334
  10334   10371 pts/0    00:00:00 iou-wrk-10334
  10334   10372 pts/0    00:00:00 iou-wrk-10334
  10334   10373 pts/0    00:00:00 iou-wrk-10334
  10334   10374 pts/0    00:00:00 iou-wrk-10334
  10334   10375 pts/0    00:00:00 iou-wrk-10334
  10334   10376 pts/0    00:00:00 iou-wrk-10334
  10334   10377 pts/0    00:00:00 iou-wrk-10334
  10334   10378 pts/0    00:00:00 iou-wrk-10334
  10334   10379 pts/0    00:00:00 iou-wrk-10334
  10334   10380 pts/0    00:00:00 iou-wrk-10334
  10334   10381 pts/0    00:00:00 iou-wrk-10334
  10334   10382 pts/0    00:00:00 iou-wrk-10334
  10334   10383 pts/0    00:00:00 iou-wrk-10334
  10334   10384 pts/0    00:00:00 iou-wrk-10334
  10334   10385 pts/0    00:00:00 iou-wrk-10334
  10334   10386 pts/0    00:00:00 iou-wrk-10334
  10334   10387 pts/0    00:00:00 iou-wrk-10334
  10334   10388 pts/0    00:00:00 iou-wrk-10334
  10334   10389 pts/0    00:00:00 iou-wrk-10334
  10334   10390 pts/0    00:00:00 iou-wrk-10334
  10334   10391 pts/0    00:00:00 iou-wrk-10334
  10334   10392 pts/0    00:00:00 iou-wrk-10334
  10334   10393 pts/0    00:00:00 iou-wrk-10334
  10334   10394 pts/0    00:00:00 iou-wrk-10334
  10334   10395 pts/0    00:00:00 iou-wrk-10334
  10334   10396 pts/0    00:00:00 iou-wrk-10334
  10334   10397 pts/0    00:00:00 iou-wrk-10334
  10334   10398 pts/0    00:00:00 iou-wrk-10334
  10334   10399 pts/0    00:00:00 iou-wrk-10334
  10334   10400 pts/0    00:00:00 iou-wrk-10334
  10334   10401 pts/0    00:00:00 iou-wrk-10334
  10334   10402 pts/0    00:00:00 iou-wrk-10334
  10334   10403 pts/0    00:00:00 iou-wrk-10334
  10334   10404 pts/0    00:00:00 iou-wrk-10334
  10334   10405 pts/0    00:00:00 iou-wrk-10334
  10334   10406 pts/0    00:00:00 iou-wrk-10334
  10334   10407 pts/0    00:00:00 iou-wrk-10334
  10334   10408 pts/0    00:00:00 iou-wrk-10334
  10334   10409 pts/0    00:00:00 iou-wrk-10334
  10334   10410 pts/0    00:00:00 iou-wrk-10334
  10334   10411 pts/0    00:00:00 iou-wrk-10334
  10334   10412 pts/0    00:00:00 iou-wrk-10334
  10334   10413 pts/0    00:00:00 iou-wrk-10334
  10334   10414 pts/0    00:00:00 iou-wrk-10334
  10334   10415 pts/0    00:00:00 iou-wrk-10334
  10334   10416 pts/0    00:00:00 iou-wrk-10334
  10334   10417 pts/0    00:00:00 iou-wrk-10334
  10334   10418 pts/0    00:00:00 iou-wrk-10334
  10334   10419 pts/0    00:00:00 iou-wrk-10334
  10334   10420 pts/0    00:00:00 iou-wrk-10334
  10334   10421 pts/0    00:00:00 iou-wrk-10334
  10334   10422 pts/0    00:00:00 iou-wrk-10334
  10334   10423 pts/0    00:00:00 iou-wrk-10334
  10334   10424 pts/0    00:00:00 iou-wrk-10334
  10334   10425 pts/0    00:00:00 iou-wrk-10334
  10334   10426 pts/0    00:00:00 iou-wrk-10334
  10334   10427 pts/0    00:00:00 iou-wrk-10334
  10334   10428 pts/0    00:00:00 iou-wrk-10334
  10334   10429 pts/0    00:00:00 iou-wrk-10334
  10334   10430 pts/0    00:00:00 iou-wrk-10334
  10334   10431 pts/0    00:00:00 iou-wrk-10334
  10334   10432 pts/0    00:00:00 iou-wrk-10334
```

**Comment by lano1106** [comment]
I keep reading the doc over and over... I have just noticed IORING_FEAT_FAST_POLL bit.

Does the fast poll feature totally removes the need of punting async requests to an io thread?
is the request/thread relation is a 1to1 relation?
What are the pros/cons of punting a request vs letting it be fast polled?

or am I mixing different concepts?

**Comment by isilence** [comment]
> I keep reading the doc over and over... I have just noticed IORING_FEAT_FAST_POLL bit.
> 
> Does the fast poll feature totally removes the need of punting async requests to an io thread?

yes, partially, but that's far from being the whole story

> is the request/thread relation is a 1to1 relation?

No, even without IORING_FEAT_FAST_POLL

> What are the pros/cons of punting a request vs letting it be fast polled?

As I already told you, there are many means to do I/O asynchronous depending on many factors, worker threads is slow and expensive but sometime inevitable. io_uring tries to choose the best path, but IOSQE_ASYNC forces to go via worker threads. So, I'd highly discourage you to use the flag unless you know really know what it is.

**Comment by lano1106** [comment]
thx for your feedback Pavel.

I keep reading fs/io_uring.c to figure out the answers myself but I have a hard time understanding this aspect of io_uring.

I hope perseverance will eventually pay off. I think that I got an ahah moment this morning. I think that maybe there is a single work queue per io_uring instance and it is the io_mgr thread that spawn io threads and do the work dispatching to the appropriate thread. I will read a bit fs/io-wq.c to validate this hypothesis.

Bottomline, I did open this issue because I wanted to make sure that the high thread count was normal. Since, you didn't comment on that specifically, I will assume that all is good and will close this issue.

thank you

**Comment by lano1106** [comment]
> > I keep reading the doc over and over... I have just noticed IORING_FEAT_FAST_POLL bit.
> > Does the fast poll feature totally removes the need of punting async requests to an io thread?
> 
> yes, partially, but that's far from being the whole story

Do you have any pointers for me if I wanted to get the whole story?
design discussion threads, a small list of functions to study to get a better grasp of what io_uring do in that area... or anything else
> 
> > is the request/thread relation is a 1to1 relation?
> 
> No, even without IORING_FEAT_FAST_POLL
> 
but this is what I am experiencing with the test I did above... I did count my fds and I have 88 fds and this happens to be the exact number of io threads spawn.. Any ideay why I get this result?

**Comment by lano1106** [comment]
oh, and I have another question... Since it is kinda related to this one, I am going slip it here instead of creating a new issue.

I am starting to consider playing with more than 2 io_uring instances and I have noticed the IORING_SETUP_ATTACH_WQ setup option.

That sounds like a very good idea!
What could be the reasons for NOT using this feature?
What is the best way to measure the load of the io workers to figure out that there is too much contention from the various io_uring instances to justify letting some instances using a private thread pool?

**Comment by lano1106** [comment]
I did experiment with the IORING_SETUP_ATTACH_WQ option. TBH, by looking at the threads spawn by io_uring, I am not sure at all that I am understanding what it is doing. From the man page:

> IORING_SETUP_ATTACH_WQ
> This flag should be set in conjunction with struct io_uring_params.wq_fd being set to an existing io_uring ring file descriptor. When set, the io_uring instance being created will share the **asynchronous worker thread backend** of the specified io_uring ring, rather than create a new separate thread pool.

My confusion comes from what I think is an **asynchronous worker thread backend** and what it is actually. In my mind, a **worker thread backend** is the set of mgr/wrk threads sharing the same tid in their name.

This is obviously wrong because I have made several tests with 2 io_uring instances with different flags value:
1. Using IORING_SETUP_SQPOLL does add an additional mgr thread.
2. IORING_SETUP_ATTACH_WQ did never change the # of threads spawned

So maybe what a **asynchronous worker thread backend** really is, it is only the set of wrk threads but each actor, even with IORING_SETUP_ATTACH_WQ set, still needs its own mgr thread... It is hard to tell because in my current setup, I only have a single wrk thread (I will put back the IOSQE_ASYNC option to confirm ;-))

Case #1:
io_uring #1:
flags = 0

io_uring #2:
flags = 0

```
    PID     LWP TTY          TIME CMD
  13270   13270 pts/0    00:00:01 test
  13270   13275 pts/0    00:00:00 iou-mgr-13270
  13270   13280 pts/0    00:00:00 Execution SVC
  13270   13281 pts/0    00:00:00 iou-mgr-13280
  13270   13282 pts/0    00:00:00 iou-wrk-13270
```

Case #2:
io_uring #1:
flags = IORING_SETUP_SQPOLL

io_uring #2:
flags = 0

```
    PID     LWP TTY          TIME CMD
  13325   13325 pts/0    00:00:00 test
  13325   13330 pts/0    00:00:07 iou-sqp-13325
  13325   13331 pts/0    00:00:00 iou-mgr-13325
  13325   13332 pts/0    00:00:00 iou-mgr-13325
  13325   13337 pts/0    00:00:00 Execution SVC
  13325   13338 pts/0    00:00:00 iou-mgr-13337
  13325   13340 pts/0    00:00:00 iou-wrk-13325
```

Case #3:
io_uring #1:
flags = 0

io_uring #2:
flags = IORING_SETUP_ATTACH_WQ

```
    PID     LWP TTY          TIME CMD
  13390   13390 pts/0    00:00:01 test_kraken
  13390   13392 pts/0    00:00:00 Logging
  13390   13394 pts/0    00:00:00 Housekeeping
  13390   13395 pts/0    00:00:00 iou-mgr-13390
  13390   13397 pts/0    00:00:00 Kraken MariaDB 
  13390   13398 pts/0    00:00:00 Kraken Account 
  13390   13399 pts/0    00:00:00 Execution SVC
  13390   13400 pts/0    00:00:00 iou-mgr-13399
  13390   13401 pts/0    00:00:00 iou-wrk-13390
```

Case #3:
io_uring #1:
flags = IORING_SETUP_SQPOLL

io_uring #2:
flags = IORING_SETUP_ATTACH_WQ

```
$ ps -L --pid 9428
    PID     LWP TTY          TIME CMD
   9428    9428 pts/1    00:05:09 test
   9428    9435 pts/1    02:09:02 iou-sqp-9428
   9428    9436 pts/1    00:00:00 iou-mgr-9428
   9428    9437 pts/1    00:00:00 iou-mgr-9428
   9428    9442 pts/1    00:00:00 Execution SVC
   9428    9443 pts/1    00:00:00 iou-mgr-9442
   9428    9444 pts/1    00:00:00 iou-wrk-9428
```

**Comment by lano1106** [comment]
I have redone Case #3 with IOSQE_ASYNC:
io_uring #1:
flags = 0

io_uring #2:
flags = IORING_SETUP_ATTACH_WQ

io_uring instance #2 still has its won iou-wrk thread (iou-wrk-13873) so, I have zero clue about what IORING_SETUP_ATTACH_WQ is supposed to do...

```
   PID     LWP TTY          TIME CMD
  13864   13864 pts/0    00:00:00 test
  13864   13869 pts/0    00:00:00 iou-mgr-13864
  13864   13873 pts/0    00:00:00 Execution SVC
  13864   13874 pts/0    00:00:00 iou-mgr-13873
  13864   13875 pts/0    00:00:00 iou-wrk-13873
  13864   13877 pts/0    00:00:00 iou-wrk-13864
  13864   13878 pts/0    00:00:00 iou-wrk-13864
  13864   13879 pts/0    00:00:00 iou-wrk-13864
  13864   13880 pts/0    00:00:00 iou-wrk-13864
  13864   13881 pts/0    00:00:00 iou-wrk-13864
  13864   13882 pts/0    00:00:00 iou-wrk-13864
  13864   13883 pts/0    00:00:00 iou-wrk-13864
  13864   13884 pts/0    00:00:00 iou-wrk-13864
  13864   13885 pts/0    00:00:00 iou-wrk-13864
  13864   13886 pts/0    00:00:00 iou-wrk-13864
  13864   13887 pts/0    00:00:00 iou-wrk-13864
  13864   13888 pts/0    00:00:00 iou-wrk-13864
  13864   13889 pts/0    00:00:00 iou-wrk-13864
  13864   13890 pts/0    00:00:00 iou-wrk-13864
  13864   13891 pts/0    00:00:00 iou-wrk-13864
  13864   13892 pts/0    00:00:00 iou-wrk-13864
  13864   13893 pts/0    00:00:00 iou-wrk-13864
  13864   13894 pts/0    00:00:00 iou-wrk-13864
  13864   13895 pts/0    00:00:00 iou-wrk-13864
  13864   13896 pts/0    00:00:00 iou-wrk-13864
  13864   13897 pts/0    00:00:00 iou-wrk-13864
  13864   13898 pts/0    00:00:00 iou-wrk-13864
  13864   13899 pts/0    00:00:00 iou-wrk-13864
  13864   13900 pts/0    00:00:00 iou-wrk-13864
  13864   13901 pts/0    00:00:00 iou-wrk-13864
  13864   13902 pts/0    00:00:00 iou-wrk-13864
  13864   13903 pts/0    00:00:00 iou-wrk-13864
  13864   13904 pts/0    00:00:00 iou-wrk-13864
  13864   13905 pts/0    00:00:00 iou-wrk-13864
  13864   13906 pts/0    00:00:00 iou-wrk-13864
  13864   13907 pts/0    00:00:00 iou-wrk-13864
  13864   13908 pts/0    00:00:00 iou-wrk-13864
  13864   13909 pts/0    00:00:00 iou-wrk-13864
  13864   13910 pts/0    00:00:00 iou-wrk-13864
  13864   13911 pts/0    00:00:00 iou-wrk-13864
  13864   13912 pts/0    00:00:00 iou-wrk-13864
  13864   13913 pts/0    00:00:00 iou-wrk-13864
  13864   13914 pts/0    00:00:00 iou-wrk-13864
  13864   13915 pts/0    00:00:00 iou-wrk-13864
  13864   13916 pts/0    00:00:00 iou-wrk-13864
  13864   13917 pts/0    00:00:00 iou-wrk-13864
  13864   13918 pts/0    00:00:00 iou-wrk-13864
  13864   13919 pts/0    00:00:00 iou-wrk-13864
  13864   13920 pts/0    00:00:00 iou-wrk-13864
  13864   13921 pts/0    00:00:00 iou-wrk-13864
  13864   13922 pts/0    00:00:00 iou-wrk-13864
  13864   13923 pts/0    00:00:00 iou-wrk-13864
  13864   13924 pts/0    00:00:00 iou-wrk-13864
  13864   13925 pts/0    00:00:00 iou-wrk-13864
  13864   13926 pts/0    00:00:00 iou-wrk-13864
  13864   13927 pts/0    00:00:00 iou-wrk-13864
  13864   13928 pts/0    00:00:00 iou-wrk-13864
  13864   13929 pts/0    00:00:00 iou-wrk-13864
  13864   13930 pts/0    00:00:00 iou-wrk-13864
  13864   13931 pts/0    00:00:00 iou-wrk-13864
  13864   13932 pts/0    00:00:00 iou-wrk-13864
  13864   13933 pts/0    00:00:00 iou-wrk-13864
  13864   13934 pts/0    00:00:00 iou-wrk-13864
  13864   13935 pts/0    00:00:00 iou-wrk-13864
  13864   13936 pts/0    00:00:00 iou-wrk-13864
  13864   13937 pts/0    00:00:00 iou-wrk-13864
  13864   13938 pts/0    00:00:00 iou-wrk-13864
  13864   13939 pts/0    00:00:00 iou-wrk-13864
  13864   13940 pts/0    00:00:00 iou-wrk-13864
  13864   13941 pts/0    00:00:00 iou-wrk-13864
  13864   13942 pts/0    00:00:00 iou-wrk-13864
  13864   13943 pts/0    00:00:00 iou-wrk-13864
  13864   13944 pts/0    00:00:00 iou-wrk-13864
  13864   13945 pts/0    00:00:00 iou-wrk-13864
  13864   13946 pts/0    00:00:00 iou-wrk-13864
  13864   13947 pts/0    00:00:00 iou-wrk-13864
  13864   13948 pts/0    00:00:00 iou-wrk-13864
  13864   13949 pts/0    00:00:00 iou-wrk-13864
  13864   13950 pts/0    00:00:00 iou-wrk-13864
  13864   13951 pts/0    00:00:00 iou-wrk-13864
  13864   13952 pts/0    00:00:00 iou-wrk-13864
  13864   13953 pts/0    00:00:00 iou-wrk-13864
  13864   13954 pts/0    00:00:00 iou-wrk-13864
  13864   13955 pts/0    00:00:00 iou-wrk-13864
  13864   13956 pts/0    00:00:00 iou-wrk-13864
  13864   13957 pts/0    00:00:00 iou-wrk-13864
  13864   13958 pts/0    00:00:00 iou-wrk-13864
  13864   13959 pts/0    00:00:00 iou-wrk-13864
  13864   13960 pts/0    00:00:00 iou-wrk-13864
  13864   13961 pts/0    00:00:00 iou-wrk-13864
  13864   13964 pts/0    00:00:00 iou-wrk-13864
  13864   13965 pts/0    00:00:00 iou-wrk-13864
```

**Comment by lano1106** [comment]
ok, based on what I have understood from my fs/io_uring.c digging,

**asynchronous worker thread backend** = SQPOLL thread.

so maybe:
1. Clarify this in the man page
2. Maybe make sure that if IORING_SETUP_ATTACH_WQ is set, IORING_SETUP_SQPOLL is also set or else return EINVAL in io_uring_setup()

**Comment by isilence** [comment]
1. Since 5.12 `IORING_SETUP_ATTACH_WQ` does not affect io-wq, but is only for sqpoll sharing  
2. io-wq is not related to SQPOLL, apart from that both sqpoll and non-sqpoll modes might use it.
3. io-wq is already shared, automatically and in a bit more complex manner.

**Comment by isilence** [comment]
> ok, based on what I have understood from my fs/io_uring.c digging,
> 
> **asynchronous worker thread backend** = SQPOLL thread.

Wrong

**Comment by isilence** [comment]
Good point about creating too many threads, there are restrictions, but in some cases it will exhaust RLIMIT_NPROC. May make sense to allow to limit them.

**Comment by lano1106** [comment]
> > ok, based on what I have understood from my fs/io_uring.c digging,
> > **asynchronous worker thread backend** = SQPOLL thread.
> 
> Wrong

Why?

The only places where wq_fd is accessed are:
io_attach_sq_data() and
io_sq_offload_create()

io_attach_sq_data() appears to be only called from io_get_sq_data() which is called from io_sq_offload_create()...

So in the end only when SQPOLL is created that wq_fd is accessed. Therefore my conclusion that it is only useful for it...

**Comment by isilence** [comment]
> > > ok, based on what I have understood from my fs/io_uring.c digging,
> > > **asynchronous worker thread backend** = SQPOLL thread.
> > 
> > 
> > Wrong
> 
> Why?
> 
> The only places where wq_fd is accessed are:
> io_attach_sq_data() and
> io_sq_offload_create()
> 
> io_attach_sq_data() appears to be only called from io_get_sq_data() which is called from io_sq_offload_create()...
> 
> So in the end only when SQPOLL is created that wq_fd is accessed. Therefore my conclusion that it is only useful for it...

Exactly, since 5.12 it's effectively used only for SQPOLL, but that doesn't mean that worker thread backend is SQPOLL. Legacy reasons... just think that it's `IORING_SETUP_ATTACH` and `attach_fd` and nothing with wq in naming.

**Comment by lano1106** [comment]
Does the constraint of not being allowed to mix and match polled and non-polled I/O from using IORING_SETUP_IOPOLL is propagated to the second io_uring when it attaches itself with IORING_SETUP_ATTACH_WQ?

**Comment by lano1106** [comment]
Case #5:
io_uring #1:
flags = IORING_SETUP_SQPOLL

io_uring #2:
flags = IORING_SETUP_SQPOLL|IORING_SETUP_ATTACH_WQ

```
    PID     LWP TTY          TIME CMD
  14189   14189 pts/0    00:00:00 test
  14189   14194 pts/0    00:00:11 iou-sqp-14189
  14189   14195 pts/0    00:00:00 iou-mgr-14189
  14189   14196 pts/0    00:00:00 iou-mgr-14189
  14189   14200 pts/0    00:00:00 Execution SVC
  14189   14202 pts/0    00:00:00 iou-wrk-14189
```

  
It has a single sqp thread which is pretty cool. SQPOLL is literally taking over a single CPU. If you have to have one, you better let all your io_ring instances benefit from it...

Now, I only have to find out what is the whole story with IORING_SETUP_IOPOLL. Would

io_uring #1:
flags = IORING_SETUP_SQPOLL|IORING_SETUP_IOPOLL

io_uring #2:
flags = IORING_SETUP_SQPOLL|IORING_SETUP_ATTACH_WQ

be valid?

or it would absolutely need to be:

io_uring #1:
flags = IORING_SETUP_SQPOLL|IORING_SETUP_IOPOLL

io_uring #2:
flags = IORING_SETUP_SQPOLL|IORING_SETUP_ATTACH_WQ|IORING_SETUP_IOPOLL

**Comment by isilence** [comment]
> Does the constraint of not being allowed to mix and match polled and non-polled I/O from using IORING_SETUP_IOPOLL is propagated to the second io_uring when it attaches itself with IORING_SETUP_ATTACH_WQ?

No, can be intermixed

> ie: Could the first io_uring be a IORING_SETUP_IOPOLL instance and the second attached io_uring using IORING_SETUP_ATTACH_WQ is not?

Yes

**Comment by lano1106** [comment]
ok then. all is good. I'll be closing this issue for good. thx a lot for your help and feedback!
