### ISSUE TITLE
Please clarify intent of license

### ISSUE THREAD

**Issue by ceejatec** [axboe/liburing#350]
The README says that liburing is "dual-licensed LGPL and MIT", but as far as I can tell "dual-licensed" isn't a legal term with a specific meaning. Was the intent that users of liburing could use either LGPL or MIT when deciding whether the library could be used in their product? Or was the intent that BOTH licenses would apply in full? (If the latter, I'm not sure that the two licenses are compatible in that way.)

Please let us know the author's intent of the licensing, and if possible please update the README to clarify this.

**Comment by axboe** [comment]
It's the former, it's meant to allow more permissive use cases for the user, not to restrict.

**Comment by ceejatec** [comment]
Thanks for the confirmation! It'd be good to clarify this in the README just in case others have the same concern.
