### ISSUE TITLE
undefined reference to `__io_uring_flush_sq`

### ISSUE THREAD

**Issue by YoSTEALTH** [axboe/liburing#356]
`Linux 5.13.0-1-MANJARO`
``` Bash
/usr/bin/ld: /tmp/ccvi4sW1.o: in function `test_io_uring_submit_enters':
.../test/iopoll.c:238: undefined reference to `__io_uring_flush_sq'
collect2: error: ld returned 1 exit status
make: *** [Makefile:147: iopoll] Error 1
```

**Comment by isilence** [comment]
What liburing version or git hash you use?
Do you have an access to sources to check if `__io_uring_flush_sq()` is in `<liburing_dir>/src/queue.c`?
If there, is it static?

**Comment by YoSTEALTH** [comment]
Using current Liburing `master` version.
Just checked and `__io_uring_flush_sq` is in `queue.c` file.
Not sure what you mean by `static`! Its `int` exactly like https://github.com/axboe/liburing/blob/master/src/queue.c#L197

**Comment by isilence** [comment]
`static` is a C keyword, there is no, so it's good. Let's try first something simple.

`make clean && make -B` for all liburing.

**Comment by YoSTEALTH** [comment]
`make clean && make -B`  # will do this before running test every time now
`sudo make runtests`
"All tests passed"

Thanks @isilence

**Comment by isilence** [comment]
It's just some make failure, probably with thinking that a file haven't changed since the last compilation when it was. Not necessary every time, but may be nice after checking out to a new version of if you have some build problems.

**Comment by isilence** [comment]
fwiw, `make clean && make` or `make -B` should be actually enough.
Other options may be added, e.g. -j<N> for parallel compilation

**Comment by YoSTEALTH** [comment]
Good to know. Makes sense `make` would only check for cached files, it should also check for source files timestamp! O right, should have used the `-j` was wondering why test was running slow :D
