### ISSUE TITLE
Allow registering buffers backed by memfd

### ISSUE THREAD

**Issue by mrakh** [axboe/liburing#358]
My application makes use of ring buffers that implement transparent wraparound via consecutive virtual pages mapping to the same physical page. I would like to register these ring buffers with `io_uring_register_buffers(...)`.

At the moment, an `io_uring_register` syscall invoked with `IORING_REGISTER_BUFFERS` returns `EOPNOTSUPP` when attempting to register file-backed memory. But perhaps memfd-backed memory can be made a special case? Since memfd files are guaranteed to reside purely in memory, its semantics are similar to those of anonymous mmap allocations. Can support for registration of memfd-backed buffers be added? Without it, my aforementioned use case would not be possible, because there's no way to create aliasing virtual pages without using file-backed memory.

**Comment by isilence** [comment]
Reasonable, I'll take a look

**Comment by YoSTEALTH** [comment]
Can you even use `io_uring_register_buffers` on anonymous mmap?
When I try it I get `Errno 95 - operation not supported.`

**Comment by isilence** [comment]
@mrakh, memfd/shmem is queued for 5.14, would be great if you test iti

@YoSTEALTH, anon pages are surely supported, but seems MAP_SHARED fails and there is vm_file assigned. Will take a look later.

**Comment by YoSTEALTH** [comment]
@isilence actually you are right.. if I `mmap(-1, 123, flags=MAP_PRIVATE)` it works :)

**Comment by isilence** [comment]
> anon pages are surely supported, but seems MAP_SHARED fails and there is vm_file assigned. Will take a look later.

fwiw, looks I just switched to a kernel without the shmem registration patch [1]. I believe registration of anon MAP_SHARED will work well in 5.14 as those are going through shmem. Will test it later.

[1] https://git.kernel.dk/cgit/linux-block/commit/?h=for-5.14/io_uring&id=ea6278ee71ac085e6110f44861f7527d658f5fb2

**Comment by mrakh** [comment]
> > anon pages are surely supported, but seems MAP_SHARED fails and there is vm_file assigned. Will take a look later.
> 
> fwiw, looks I just switched to a kernel without the shmem registration patch [1]. I believe registration of anon MAP_SHARED will work well in 5.14 as those are going through shmem. Will test it later.
> 
> [1] https://git.kernel.dk/cgit/linux-block/commit/?h=for-5.14/io_uring&id=ea6278ee71ac085e6110f44861f7527d658f5fb2

Thanks! Will test and re-open if I encounter any issues.

**Comment by isilence** [comment]
just in case" there is also a simple test merged into liburing

https://github.com/axboe/liburing/commit/9ef0e54099230ac7d3a44820f8431ddb87688f30

**Comment by isilence** [comment]
@mrakh, also if you can tell your full name + email, I will ask to add a tag to the kernel commit/patch to give a credit. Like

`Reported-by: Full Name <email_address@example.com>`

**Comment by mrakh** [comment]
> just in case: there is also a simple test merged into liburing
> 
> [9ef0e54](https://github.com/axboe/liburing/commit/9ef0e54099230ac7d3a44820f8431ddb87688f30)

Thanks for the commit hash, I’ll be sure to check it out.

> @mrakh, also if you can tell your full name + email, I will ask to add a tag to the kernel commit/patch to give a credit. Like
> 
> `Reported-by: Full Name <email_address@example.com>`

Mahdi Rakhshandehroo <mahdi.rakhshandehroo@gmail.com>

**Comment by YoSTEALTH** [comment]
Just an confirmation that `mmap(..., flags=MAP_SHARED)` is working for `Linux 5.14-rc1`
