### ISSUE TITLE
buffer leak when using IOSQE_BUFFER_SELECT

### ISSUE THREAD

**Issue by lano1106** [axboe/liburing#359]
the man page says the following:

> **If succesful**, the resulting CQE will have IORING_CQE_F_BUFFER set in the flags part of the struct, and the upper IORING_CQE_BUFFER_SHIFT bits will contain the ID of the selected buffers.

based on my understanding of the kernel code, the buffer will be returned even if the underlying syscall fails. (I have validated this by looking for IORING_OP_READ).

At the minimum, the man page should be clarified to better reflect the code behavior. (and there is a missing 's' in succesful)

ideally, I believe the code should be modified to do what the man page says because:

1. doing otherwise is counter-intuitive and error-prone (I cannot think of a single example of a syscall failing and still require the user to free the allocated resources)
2. it is inefficient because the buffer is unneeded since there is no data to transfer back to the user and the buffer will need to be returned back to io_uring to avoid a leak.

**Comment by isilence** [comment]
> At the minimum, the man page should be clarified to better reflect the code behavior. (and there is a missing 's' in succesful)

Patches are welcome, including man. However, I think there might be other problems around buf-id delivery.

>     2. it is inefficient because the buffer is unneeded since there is no data to transfer back to the user and the buffer will need to be returned back to io_uring to avoid a leak.

From the current kernel impl perspective it's easier to return it back unconditionally. Does it happen often? I want to get a grasp on the extent of inefficiency we're talking about, because we don't really care about not real world cases.

**Comment by lano1106** [comment]
Hi Pavel,

it doesn't happen very often but just enough to eventually run out of buffers.

In this case, it is really an issue of correctness much more than performance...

I have been surprised by this unexpected behavior... Once you know, you can deal with it. Again, not many people had the chance to play with io_uring yet... I predict this problem to become another classic...

TBH, I have been struggling with provided buffers leaks since last week. The connected service used to be very stable (ie: reconnection was happening once per week) to now drop connections many times each hour. This is making all the leak issues resurface... which can be considered a good or a bad thing depending on your point of view...

I have a patch in the pipe but I wanted to test it thoughtfully before submitting it... During its development, I have experienced my first mutex deadlock due to an oversight!

I am going to email it soon... Given my io_uring patch acceptance track record I have not much hope to see this one accepted but at least it is going to be recorded in the list archive in case it can help someone at some point...

I got another surprising result with io_uring that I am going to share in another issue...

**Comment by isilence** [comment]
> it doesn't happen very often but just enough to eventually run out of buffers.
> 
> In this case, it is really an issue of correctness much more than performance...

I don't deny that it might be not convenient, just wanted to clarify that it's rather not about performance but usability 

> I have been surprised by this unexpected behavior... Once you know, you can deal with it. Again, not many people had the chance to play with io_uring yet... I predict this problem to become another classic...

There are features that are rarely/not so often used in real environments, it looks to me that this is one of them...

> TBH, I have been struggling with provided buffers leaks since last week. The connected service used to be very stable (ie: reconnection was happening once per week) to now drop connections many times each hour. This is making all the leak issues resurface... which can be considered a good or a bad thing depending on your point of view...
> 
> I have a patch in the pipe but I wanted to test it thoughtfully before submitting it... During its development, I have experienced my first mutex deadlock due to an oversight!
> 
> I am going to email it soon... Given my io_uring patch acceptance track record I have not much hope to see this one accepted but at least it is going to be recorded in the list archive in case it can help someone at some point...

You're fine in regards of patching, it's just everybody is busy. Patches with traces I believe will be accepted in no time, reissue is a good thing, but we want to see if it can be done even better -- need to get back to the thread. You're raising good points.

> 
> I got another surprising result with io_uring that I am going to share in another issue...

**Comment by lano1106** [comment]
yes, I know you are very busy... You are a super dev. I have no idea how you do to be that productive... I see all the changes that you push. Jens is lucky to have you. There is no doubt in my mind that io_ruing would not be as excellent as it is without you. I think the other day, I was looking an article on lwn where it was showing the release stats and I think that you had the top #1 position for the most active contributor...

I am impressed
