### ISSUE TITLE
Issue: IORING_OP_TIMEOUT with IOSQE_IO_LINK always cancels the next operation, which makes it unusable

### ISSUE THREAD

**Issue by CarterLi** [axboe/liburing#36]
IORING_OP_TIMEOUT returns -ETIME when expires, which is considered an error and will breaks the entire link. As a result, operations after IORING_OP_TIMEOUT with IOSQE_IO_LINK will always be canceled.

```c
#include <unistd.h>
#include <liburing.h>

int main() {
	struct io_uring ring;
	io_uring_queue_init(8, &ring, 0);

    struct io_uring_sqe *sqe1 = io_uring_get_sqe(&ring);
    struct __kernel_timespec ts = {
        .tv_sec = 1,
        .tv_nsec = 0,
    };
    io_uring_prep_timeout(sqe1, &ts, 0, 0);
    io_uring_sqe_set_flags(sqe1, IOSQE_IO_LINK);

    struct io_uring_sqe *sqe2 = io_uring_get_sqe(&ring);
    struct iovec iov = {
        .iov_base = "OK\n",
        .iov_len = sizeof("OK\n"),
    };
    io_uring_prep_writev(sqe2, STDERR_FILENO, &iov, 1, 0);
    io_uring_submit_and_wait(&ring, 2);

    io_uring_queue_exit(&ring);
}
```

Expected: waits 1s then print "OK"  
Actual: nothing is printed

**Comment by CarterLi** [comment]
I suggest that we should make IORING_OP_TIMEOUT with off == 0 return 0, as it will always expire.

**Comment by axboe** [comment]
How about we just don’t break links for timeouts with off == 0 when they expire?

**Comment by CarterLi** [comment]
A common solution: how about adding a new sqe flag indicates that we should not break links no matter whether an error is returned

**Comment by axboe** [comment]
I like that idea. Maybe IOSQE_IO_FOO that works like IOSQE_IO_LINK, just doesn't break regardless of completion value of the parent? I think that'd be cleaner than needing to set both IOSQE_IO_LINK and IO_SQE_IO_LINK_NOBREAK (or whatever name).

Just need to think of a good name, maybe something that implies a stronger link.

**Comment by axboe** [comment]
Probably just IOSQE_IO_HARDLINK

**Comment by CarterLi** [comment]
> Probably just IOSQE_IO_HARDLINK

good name

**Comment by axboe** [comment]
https://git.kernel.dk/cgit/linux-block/commit/?h=io_uring-5.5&id=a261a2acaa0b8650d885fac33dbd1581cb0659e5

**Comment by CarterLi** [comment]
Thanks. I will test it when it's merged into mainline.

**Comment by DavidBuchanan314** [comment]
The link to the commit is now broken - any hints as to where I can find it?

**Comment by isilence** [comment]
https://git.kernel.dk/cgit/linux-block/commit/?h=io_uring-5.5&id=4e88d6e7793f2f445f43bd608828541d7f43b608
