### ISSUE TITLE
Adding `RESOLVE_*` flags to `configure`

### ISSUE THREAD

**Issue by YoSTEALTH** [axboe/liburing#360]
Could `open_how` `RESOLVE_*` defines be added to `configure` file?

``` C
cat >> $compat_h << EOF
#include <inttypes.h>

struct open_how {
    uint64_t    flags;
    uint64_t    mode;
    uint64_t    resolve;
};

EOF
```
to
``` C
cat >> $compat_h << EOF
#include <inttypes.h>

struct open_how {
    uint64_t    flags;
    uint64_t    mode;
    uint64_t    resolve;
};

/* how->resolve flags for openat2(2). */
#define RESOLVE_NO_XDEV       0x01
#define RESOLVE_NO_MAGICLINKS 0x02
#define RESOLVE_NO_SYMLINKS   0x04
#define RESOLVE_BENEATH       0x08
#define RESOLVE_IN_ROOT       0x10
#define RESOLVE_CACHED        0x20

EOF
```

If I manually `#include <linux/openat2.h>` it says `open_how` is already defined in `compat.h` and
if I do not `#include <linux/openat2.h>` I can't access the `RESOLVE_*` flags.

Maybe a better option ...

**Comment by axboe** [comment]
Would probably need to be a separate test, but yes that would be possible. Somewhat outside the scope of liburing, though.

**Comment by YoSTEALTH** [comment]
@axboe good call, I can see how it can get out of hand! If you account for one, would have to account for everything else as well.

I managed to come up with a way to resolve this issue.

**Comment by axboe** [comment]
My stance on this is still the same, but if you want to write the configure change for it, then I'll certainly take a look.

**Comment by YoSTEALTH** [comment]
I am not sure why `open_how="no"` on my system! inside `<fcntl.h> it has `#include <linux/openat2.h>`, so why would it not find it in `configure`? This is not my area of expertise.
