### ISSUE TITLE
Non-blocking `waitpid`?

### ISSUE THREAD

**Issue by ioquatix** [axboe/liburing#361]
Does this exist? Should we create it? Or should we prefer pidfd?

**Comment by ammarfaizi2** [comment]
What's the deal with liburing?
Don't we have `WNOHANG` for this?

Quoted from `man 2 waitpid`:
```
 int waitid(idtype_t idtype, id_t id, siginfo_t *infop, int options);
 [...]
 The value of options is an OR of zero or more of the following constants:
 [...]
 WNOHANG
              return immediately if no child has exited.
 [...]
```

**Comment by ioquatix** [comment]
@ammarfaizi2 I'm not sure how `WNOHANG` relates to my use case? Are you suggesting I should call this for every PID in a tight loop?

**Comment by ammarfaizi2** [comment]
@ioquatix oh right, I missed the use case. Now I think it makes sense to poll for `waitpid`.

**Comment by ioquatix** [comment]
On more recent Linux we can use `pidfd_open`. But I'm not sure if there is better approach. Maybe we can introduce `OP_WAITPID`.

**Comment by ioquatix** [comment]
For reference, here is what I did: https://github.com/socketry/event/blob/1278eab1d7b1af9d5aa3d5f4acd246e686786315/ext/event/backend/uring.c#L154-L174

**Comment by isilence** [comment]
> Does this exist? Should we create it? Or should we prefer pidfd?

Is it somewhat CPU time limited on pid waiting? If it's just an occasional thing and there are no other problems, than I'd say pidfd is a better option

**Comment by ioquatix** [comment]
In some cases there could be hundreds of child processes. It may be nice to provide a better interface, for consistency sake.

**Comment by ioquatix** [comment]
Just bumping this, I'm still interested in such an interface.

**Comment by isilence** [comment]
```
       IORING_OP_WAITID
              Issue  the  equivalent of a waitid(2) system call.  len must contain the idtype being queried/waited for and fd must contain the 'pid' (or id) being waited for.  file_index is the 'options' being set (the child state
              changes to wait for).  addr2 is a pointer to siginfo_t, if any, being filled in. See also waitid(2) for the general description of the related system call. Available since 6.5.
```

There is `IORING_OP_WAITID`, and it has been there for a while now.  There are also some examples/test in liburing, see `liburing/test/waitid.c`.

**Comment by ioquatix** [comment]
Nice, so we should be able to close this, right?

**Comment by axboe** [comment]
This was added in kernel 6.7.

**Comment by ioquatix** [comment]
Thank you so much for your amazing work.
