### ISSUE TITLE
outstanding read operations don't notice that the underneath fd change

### ISSUE THREAD

**Issue by lano1106** [axboe/liburing#363]
I am not sure if it is a problem but I have been surprised by the result. So I am sharing it here.

1. Establish a TCP connection.
2. Submit a IORING_OP_READ on the TCP socket fd.
3. Detect at the application level that the connection is dead. Close the socket and reopen a new one to create a fresh new connection with the server that ends up with the exact fd value as the previous connection

Expected result:
The pending read operation would notice that the fd is gone and returns back an error.

Result:
io_uring never noticed that the old connection is gone. When data will become available on the new connection, the read operation launched for the previous connection will complete.

I guess that the correct way to handle this situation would be to submit a IORING_OP_ASYNC_CANCEL request but I wish the kernel would be smart enough to cancel the pending operations when a file get closed...

**Comment by YoSTEALTH** [comment]
There could be so many things that could have gone wrong or not accounted for!

- Keep and internal track of socket `fd` and check its close state on every call.
- use `shutdown` `SHUT_RDWR` to make sure closed connection doesn't send/recv
- it could be that socket was set to `SO_KEEPALIVE`
- even if its using the same `fd` the `port` might be different.
- ...

Even though people think socket is asynchronous, its not truly asynchronous, there is a slight delay in connection where one or both ends of the connection doesn't know what is happening.

I could be totally mistaken in thinking its not `io_uring` fault :)

**Comment by isilence** [comment]
> I am not sure if it is a problem but I have been surprised by the result. So I am sharing it here.
> 
>     1. Establish a TCP connection.
> 
>     2. Submit a IORING_OP_READ on the TCP socket fd.
> 
>     3. Detect at the application level that the connection is dead. Close the socket and reopen a new one to create a fresh new connection with the server that ends up with the exact fd value as the previous connection
> 
> 
> Expected result:
> The pending read operation would notice that the fd is gone and returns back an error.
> 
> Result:
> io_uring never noticed that the old connection is gone. When data will become available on the new connection, the read operation launched for the previous connection will complete.
> 
> I guess that the correct way to handle this situation would be to submit a IORING_OP_ASYNC_CANCEL request but I wish the kernel would be smart enough to cancel the pending operations when a file get closed...

I believe recv(2) works in the same way, it grabs a file ref and the actual file (not a particular fd) will be alive until the request is interrupted anyhow. Same for io_uring registered files, it will keep it alive until unregistered. There is little can be done about it.

The right way is to do shutdown() first, it will cut connection and so any request (including inflight and recv(2)/etc.) will be aborted.

**Comment by lano1106** [comment]
thx Pavel for your suggestion.

FYI, after having read it, I went to look into the WebSocket library that I am using (not my code) to see how it was handling the socket closing.

I have found out that it did call shutdown(SHUT_WR)

I did change that for shutdown(SHUT_RDWR) as you suggested. This could maybe trigger a read completion indicating EOF.

If not, I guess that adding an extra IORING_OP_ASYNC_CANCEL should really solve my issue in the worst-case scenario...

**Comment by YoSTEALTH** [comment]
It's hard to tell what you are doing at this point.

You should be using `io_uring_prep_shutdown` + `io_uring_prep_close`, at this point it should finishes in success or error. Either case there should be no reason to be calling `io_uring_prep_cancel` (IORING_OP_ASYNC_CANCEL) since both of those task have completed.

One of the gotcha for shutdown is you need to check if `fd` is still alive `if fd: # do shutdown` so you need to track socket `fd` state, throughout your socket class/application.

**Comment by lano1106** [comment]
YoSTEALTH,

This is a very interesting exchange... My brain hasn't fully made the switch to fully think in terms of io_uring operations. This didn't occur to me to perform the shutdown and close calls through io_uring.

TBH, the effort to complete the transition to io_uring might not be worth the necessary effort. What attracted me to io_uring in the first place was the performance gain that I could get when my connection is in the connected state... Initiating and shutting down the connection represent only a very small negligible part of the whole execution time...

io_uring_prep_cancel might not be necessary but since io_uring operations are made from a library, I suppose that it is a good idea to not make any assumption about how its users are using it and I'll keep it for when it is notified that async reading is not desired anymore.

I am touching wood but I think that I have finally found out my issue. I am using an event loop (libev). Upon receiving the connection error event, the code was: 1. shutting down the current connection and initiating a new connection.

This was leading to the variable containing the read bid being overwritten. What I had to do was give back the control between the shutdown and the reconnection to the event loop so that io_uring completion events generated by shutting down the socket had the opportunity to be processed before moving on to the reconnection..

**Comment by YoSTEALTH** [comment]
Joke is socket programing and brain damage go hand in hand :)

If you already had software written using `libev`, it makes sense to stick with it. Looks like they did add support for `io_uring` http://cvs.schmorp.de/libev/ev_iouring.c?revision=1.25&view=markup though they should have wrote it on top of `liburing`

As long as you have access to `fd` you should still be able to use `liburing` functions and use `libev` to submit that `sqe`

Just to clarify further, you can actually call `shutdown` multiple times!

As an example say you are a "server"
connection-1 = you `recv` clients request, you can call `shutdown(SHUT_RD)` this will stop any more reading.
connection-2 = a new connection/fd/port would be created if clients makes another request.
connection-1 = is still able to `send` data back to client and you can call `shutdown(SHUT_WR)` + `close`.

**Comment by lano1106** [comment]
you have to put yourself in the shoes of a multiplatform library creator. He doesn't want to bring in more dependencies on his users. therefore he took the decision to replicate the boilerplate code. I cannot criticize the decision.

However, because my application was already using the libev lightweight abstraction allowing the application to easily switch backends and I do really value this feature, I did substantially modify libev (using liburing to keep my sanity was one of those changes) to be able to do async i/o over just polling and keep around the option to switch backend.

For your clarification, yes. I already kinda know this stuff. My only problem was that I had to find a way to cancel the pending read when the connection gets closed (either remotely or locally and for the records, my app is a client not a server). Giving back control to the loop between completing the socket close and reopening the connection did the thing. My app has been running for the last 2 days and so far, not a single buffer ha been lost despite hundreds of reconnection!
