### ISSUE TITLE
Max registered buffers size in io_uring

### ISSUE THREAD

**Issue by SkyRzn** [axboe/liburing#365]
I've tried to register a set of buffers by io_uring_register_buffers() but I couldn't register buffers big enough. Either one buffer bigger than 32768 bytes or a few buffers with the total size bigger 32768 lead to the ENOMEM error. I've read the maximum buffer size is 1GB for one buffer.

There is an example:
```
#include <stdlib.h>
#include <stdio.h>
#include <liburing.h>

#define LEN 4096
#define CNT 9

int main()
{
    struct io_uring ring;
    struct iovec iov[CNT];
    char *buf;
    int res;

    if (io_uring_queue_init(64, &ring, 0) != 0)
        return -1;

    buf = malloc(LEN*CNT);

    for (int i = 0; i < CNT; i++) {
        iov[i].iov_base = buf + (i * LEN);
        iov[i].iov_len = LEN;
    }

    res = io_uring_register_buffers(&ring, iov, CNT);
    printf("%d\n", res);

    io_uring_queue_exit(&ring);

    return 0;
}
```

If I define CNT as 9, I have ENOMEM error. The same thing with CNT==1 and LEN==65536. What is wrong?
Thank you!

**Comment by isilence** [comment]
You hit RLIMIT_MEMLOCK. The limit is usually 64KB, but I guess you stumble on 32KB because malloc return not aligned chunk, but registration works with pages, so for each buffer it registers 2 adjacent pages that's twice as much.

Also, if memory is not page aligned it 


```C
#include <stdio.h>
#include <sys/resource.h>

int main()
{
    struct rlimit l;

    if (!getrlimit(RLIMIT_MEMLOCK, &l))
        fprintf(stderr, "%i %i\n", (int)l.rlim_max, (int)l.rlim_cur);
    return 0;
}
```

**Comment by SkyRzn** [comment]
Thank you for your answer!
Yes, with aligned by 4096 buffer I have 64K limit. 
So the only way to have a big buffer or many small buffers is system reconfiguring?

**Comment by isilence** [comment]
Right, and can be done at runtime, e.g. `/etc/security/limits.conf`, `setrlimit(2)` and/or anything you can find about RLIMIT_MEMLOCK.

**Comment by SkyRzn** [comment]
Thanks a lot!
