### ISSUE TITLE
Clarify and document back-pressure behaviour in man pages

### ISSUE THREAD

**Issue by dcoutts** [axboe/liburing#368]
Following on from issue #293, it would be great if we could document the new back-pressure behaviour in the man page. I volunteer to write a PR for the man page if I can understand the behaviour myself!

Let me try and elaborate the issue a bit...

Right now the man page tells us we can get

> EAGAIN The kernel was unable to allocate memory for the request, or otherwise ran out of resources to handle it. The application should wait for some completions and try again.

> EBUSY The application is attempting to overcommit the number of requests it can have pending. The application should wait for some completions and try again. May occur if the application tries to queue more requests than we have room for in the CQ ring, or if the application attempts to wait for more events without having reaped the ones already present in the CQ ring.

The description of the latter has recently been extended, but the distinction between the two still isn't very clear.

I think most people get that if the completion queue is full then it's reasonable to expect a failure like this, and the solution is just to process all the completions, clear the completion queue and try again.

The case that's really unclear though is if we can get either of these errors when the completion queue is empty. Of course that's exactly what issue #293 was about (that there was no back-pressure in this case). Presumably the new answer now that #293 is fixed is yes: yes we can get one or the other of these errors even if the completion queue is empty. What are we to do in this case? Are we guaranteed that if we call `io_uring_enter` again with 0 `to_submit` and `min_complete > 0` that we'll then be able to submit more? Or perhaps not just once but calling it repeatedly then we're eventually guaranteed to be able to submit more? Presumably this would only be true when we have enough pending operations on the uring that are not-blocking (e.g. not most socket ops).

And for guidance, should we assume there's different limits or costs to different operations? For example, are blocking things like `IORING_OP_POLL_ADD` cheaper than things like `IORING_OP_OPENAT` or `IORING_OP_CONNECT`?

I ask because of course if one maxes out the memory limits using operations that may block for an indefinite time (like poll add) then we could get really stuck since waiting for operations to complete could take arbitrary time. So applications (or frameworks, runtime systems etc) might want to follow a policy of allowing X blocking ops (e.g. socket things) but keeping enough space left for short-term non-blocking things like disk operations. So if we can provide some guidance on this, we can help app/framework authors handle this robustly (e.g. doing their own accounting, or imposing their own limits). e.g. how would they estimate safe limits?

Lots of questions :-). I don't expect answers to everything, but if we can get a better idea then we can document it in the man page for everyone else.

**Comment by victorstewart** [comment]
i agree clarity on all permutations enables deterministic engineering, but as an aside, if someone is triggering such limits the problem is a failure of resource planning and a need to scale horizontally.

**Comment by isilence** [comment]
The first constraint, recently added as per other thread, is memcg accounting all requests, each request in that regard takes the same amount of memory. And we also do memcg tracked allocations for overflowed CQEs, but those should always be shortly reaped by the userspace.
We have some internal request caching, meaning they are accounted once and then used again and again, but there are exceptions. I'll be pushing for 5.14 making them fully reusable in all cases, so once there has been N inflight requests, there will always be possible to issue N inflight requests.

The second limitation is that requests may allocate some more memory on demand, which is not tracked by memcg.  The upper limit for it can be approximated out of number of requests inflight, but widely depends on types of requests issued and particular cases. In some cases we'll ignore the error and try to execute another way, but not always possible.

That's for io_uring, there are other places down the stack when it can fail and we have little control over.

**Comment by axboe** [comment]
It's _really_ hard to fully describe the conditions, as (like others have mentioned) we don't have full control of the stack. If you look at man pages for eg libaio or other APIs that do IO, the conditions are a bit vague on purpose. It would be nice if that wasn't the case, but even suggestions like "for -EAGAIN, wait on previously submitted IO" isn't fully correct, as it may indeed happen for an ill configured system without the application having any previously submitted IO in-flight. -EBUSY is clearer as the condition is entirely internal to io_uring.

**Comment by blahgeek** [comment]
It seems that the "EBUSY" description is not true anymore since linux 5.13? I cannot trigger this error anymore during testing. I found this commit: https://github.com/torvalds/linux/commit/c82d5bc703825a47af5c600e82e1e0c1db49e036

**Comment by isilence** [comment]
@blahgeek, right, that one was pretty annoying when there are different threads for submission and completion sides forcing some extra sync between them. You can check a flag on the userspace side if some similar behaviour is needed.  E.g.

```
static inline bool cq_ring_needs_flush(struct io_uring *ring)
{
	return IO_URING_READ_ONCE(*ring->sq.kflags) & IORING_SQ_CQ_OVERFLOW;
}
```

**Comment by dcoutts** [comment]
@axboe sorry to be a pain, did anything get updated in any man page, or is this a case of "too hard, can't document" as you outlined above ("It's really hard to fully describe the conditions")? Assuming the latter, perhaps you or anyone can comment on a plausible design.

The problem arises for frameworks and runtime systems -- things which are not themselves the final application.

@victorstewart previously noted:
> if someone is triggering such limits the problem is a failure of resource planning and a need to scale horizontally

Which is indeed true for an application, and we might reasonably blame an app author. But for a runtime system that wants to implement I/O using uring, or some library framework, these things are not the final app and have to deal with silly application behaviour somehow, even if that means throwing helpful errors to help app authors realise and debug their problems. Nevertheless, perhaps the answer is to try really hard to prevent an app from ever hitting a kernel limit on the amount of outstanding I/O.

Here's one possible design:

* Assume that all operations can be divided into blocking (e.g. most socket ops) and non-blocking (e.g. most disk ops).
* Assume (hope) that blocking ops are quite cheap and we can have lots of them outstanding (e.g. dealing with 10k sockets), but assume that non-blocking disk ops are expensive and we can only have a few outstanding.
* Have framework imposed limits for each kind, e.g. 10k and 1k respectively
* (For example: enforce limits on blocking ops by throwing an exception, and limits on non-blocking by stalling the submitting thread until there is space within the limit)
* Hope these limits are enough to remain within kernel resource limits, but allow tuning them as framework params

This means we don't rely on hitting the kernel limit to know when to back-off and prevent the app from doing too much I/O concurrently. The design has obvious downsides: we may pick our limit too low or to high, because we don't rely on any info or feedback from the kernel. Also, the assumption that we can divide into blocking and non-blocking with corresponding assumed costs may be far to naive.

Thoughts?
