### ISSUE TITLE
Consider CLOCK_BOOTTIME (monotonic, but accurate over suspend) over CLOCK_MONOTONIC

### ISSUE THREAD

**Issue by jorangreef** [axboe/liburing#369]
I understand that io_uring currently uses `CLOCK_MONOTONIC` internally for measuring elapsed time for the purpose of timeouts.

This is mostly fine, but where timeouts are long-lived, e.g. an hour or two, and where the system or VM is suspended, then io_uring will measure these timeout intervals incorrectly, because `CLOCK_MONOTONIC` excludes the elapsed time during the suspend.

`CLOCK_BOOTTIME` might be a better choice because it's the higher resolution, more resilient interface of the two. For example, any system that needs to measure monotonic time intervals that also correspond to actual time passing across systems, such as a distributed databases tracking leader leases, would probably want to use `CLOCK_BOOTTIME` when submitting timeouts to io_uring.

**Comment by YoSTEALTH** [comment]
Hmm this is an interesting situation. If you have a countdown and you suspend your system, you would want to resume the countdown right? vs just going boom when you unsuspend! :D

Wouldn't it make more sense to add this databases tracking outside of suspending vm?

**Comment by jorangreef** [comment]
Yes, but again, it all depends on the application context. Some applications might want a timeout N hours into the future, and might want this to reflect the passing of actual time, not just non-suspend time. Others might not. It depends. The argument cuts both ways.

The kernel was actually going to switch the behavior of `CLOCK_MONOTONIC` to `CLOCK_BOOTTIME` at one point but this broke applications. However, io_uring only works with `CLOCK_MONOTONIC` at present, without exposing `CLOCK_BOOTTIME`, so the question is, which is a better building block?

**Comment by YoSTEALTH** [comment]
It would be nice if you can set your own flags, Like there is a `sqe->timeout_flags` flag option but right now it seems its only for
`0` Relative Timeout
`1` `IORING_TIMEOUT_ABS`

It would be nice if you could pass `CLOCK_*` flags into it and well. https://elixir.bootlin.com/linux/v5.13-rc6/source/include/uapi/linux/time.h#L49

It could also be that @axboe had already planned for this and just forgot to mention/implement it

**Comment by jorangreef** [comment]
@YoSTEALTH that would be perfect.

**Comment by YoSTEALTH** [comment]
Could you not make it so developers can pass their own `CLOCK_*` flag? This way they can choose what type of timing they need for their application, also not break things currently implemented.

**Comment by axboe** [comment]
The only way to do that would be to set aside some timeout flags to do just that. Which is indeed possible, we currently have ~12 clock sources, which would mean 4 bits in the flags. It's a bit ugly though, but would be more flexible.

**Comment by YoSTEALTH** [comment]
Giving user that flexibility and not breaking current timeout is a +1

**Comment by axboe** [comment]
The proposed patch doesn't risk any breakage, but it does only allow choosing monotonic or boottime. My worry here is the interface, then you'll have to do things like:

```
io_uring_prep_timeout(sqe, &ts, 0, flags | (clocksource << some_shift);
```

and some flags might conflict with the clock source, and the clock source would have to be validated as well. I'm just worried it's too much flexibility or over-designing it, when monotonic/boottime might be the only truly useful cases because a lot of the other sources don't really make sense for this use case. realtime might be an exception, not sure.

**Comment by YoSTEALTH** [comment]
Wait, I actually use the realtime/CLOCK_REALTIME/`0` currently or whats called relative time?

ok then,  how about realtime, monotonic, boottime for now then add other feature as users request it?

It would also be nice to get another person or two's point of view.

**Comment by axboe** [comment]
Since I think REALTIME is the only other sane option, it actually ends up not being too bad as we can just keep them as bits. Here's an updated version:

https://lore.kernel.org/io-uring/0e110ae2-f744-df44-e017-bf603f481348@kernel.dk/

**Comment by YoSTEALTH** [comment]
I might be wrong here but don't you already have relative / `IORING_TIMEOUT_REALTIME` set `0`?
Like https://elixir.bootlin.com/linux/v5.13-rc6/source/include/uapi/linux/time.h#L49 also you already have tests written for it https://github.com/axboe/liburing/blob/master/test/timeout.c#L980 also this man https://github.com/axboe/liburing/blob/master/man/io_uring_enter.2#L331

**Comment by axboe** [comment]
Relative is independent of clocksource, it can be set or not for either clocksource. Don't confuse the bit values in the timeout mask with the absolute clock source values, that's why io_timeout_get_clock() translates them.

The posted patch will break nothing, the default behavior is the same as before. If you set nothing, then monotonic is used. If you set _ABS, then absolute values is used for monotonic.

**Comment by YoSTEALTH** [comment]
True, was confusing `IORING_TIMEOUT_*` with `CLOCK_*` naming/values. `io_timeout_get_clock` makes sense now.

Thank for the patch and clarification  :)

**Comment by jorangreef** [comment]
Thanks @axboe and @YoSTEALTH, awesome to see this.

**Comment by YoSTEALTH** [comment]
@axboe close, thanks.
