### ISSUE TITLE
io_uring_prep_write on socket

### ISSUE THREAD

**Issue by ciconia** [axboe/liburing#370]
Is doesn't seem to be possible to do a `io_uring_prep_write` on sockets, as there is apparently no way to tell io_uring to ignore the offset argument, and the completion result is `-EPIPE`. This seems inconsistent with `io_uring_prep_splice`, which can take -1 as the offset in order to ignore it. Is this correct? Or is there any way to do a `io_uring_prep_write` on a socket?

**Comment by isilence** [comment]
Should help

https://github.com/axboe/liburing/blob/603111a58a04926088bd0493ea5d4d2ff8aaef93/man/io_uring_enter.2#L200

**Comment by isilence** [comment]
fwiw, that's how it's with `preadv(2)` and has always been the case with io_uring, just man was adjusted recently.

```C
static ssize_t sock_write_iter(struct kiocb *iocb, struct iov_iter *from)
{
        ....
	if (iocb->ki_pos != 0)
		return -ESPIPE;
}
```

**Comment by ciconia** [comment]
Thanks @isilence for the prompt reply. FWIW I asked specifically about `IORING_OP_WRITE`, for which the manpage has no such mention, but says it's the equivalent of `pwrite`. The manpage for `pwrite` states:

> The file referenced by fd must be capable of seeking.

So the docs are not clear on that.

**Comment by isilence** [comment]
All io_uring's write opcodes behave similarly in that regard, and there is a note about offsets in the `IORING_OP_WRITE` section. Perhaps, hasn't been released yet and/or your liburing/man is outdated.

https://github.com/axboe/liburing/blob/603111a58a04926088bd0493ea5d4d2ff8aaef93/man/io_uring_enter.2#L597

**Comment by ciconia** [comment]
Thanks again. closing...
