### ISSUE TITLE
[Question] Feature detection for IORING_POLL_ADD_MULTI

### ISSUE THREAD

**Issue by CarterLi** [axboe/liburing#371]
Maybe a stupid question, how can I detect if the kernel supports IORING_POLL_ADD_MULTI? I didnt find something like IORING_FEAT_POLL_ADD_MULTI.

**Comment by isilence** [comment]
1) A hack-ish way is to test for `IORING_FEAT_RSRC_TAGS`.
2) A bulky way is to try to issue it at the beginning of a program and derive from the result
3) However, it should be possible to add a new `FEAT` flag as 5.13 is not yet released.

@axboe, what do you think?

**Comment by axboe** [comment]
Generally I dislike FEAT flags for per-request type of changes, I think those are a mistake. Ideally the prob op would have a way to pass back per-request type flags supported, I've been mulling that over for a while.

So I'd suggest nr 2 for now. It's not super pretty, but would be trivial enough to call pipe(2) and attempt a poll add with MULTI set and see if you get -EINVAL or not.

**Comment by CarterLi** [comment]
> Generally I dislike FEAT flags for per-request type of changes, I think those are a mistake.

Why? I think FEAT flags are the most straightforward and the most easy-to-use method for feature detection. Even probe needs an extra io_uring_enter syscall.

**Comment by axboe** [comment]
Because they are per-request, FEAT flags should mostly be for features that transcend any particular request type. And because it's not scalable, we'll run out of feature flags very soon if we throw every kind of per-request change in there.

> Even probe needs an extra io_uring_enter syscall.

But it's a startup thing, not hot path / runtime. So not a huge deal imho.

**Comment by CarterLi** [comment]
Make sense.
