### ISSUE TITLE
IOSQE_IO_LINK and IOSQE_IO_HARDLINK

### ISSUE THREAD

**Issue by YoSTEALTH** [axboe/liburing#372]
Curious, what happens if `IOSQE_IO_LINK` and `IOSQE_IO_HARDLINK` are both set together in `sqe->flags`?

**Comment by axboe** [comment]
HARDLINK implies LINK already, so won't be any different than if just HARDLINK was set.

**Comment by YoSTEALTH** [comment]
I see, so `IOSQE_IO_HARDLINK` will override `IOSQE_IO_LINK` then

**Comment by axboe** [comment]
Not sure what you mean. There's no overriding, HARDLINK is LINK + don't break on error. Hence it implies LINK.

**Comment by isilence** [comment]
Let's say there is no difference b/w `IOSQE_IO_HARDLINK|IOSQE_IO_LINK` and `IOSQE_IO_HARDLINK`

**Comment by axboe** [comment]
Right, that's what I was saying in the first comment.

**Comment by YoSTEALTH** [comment]
OK, thanks for clarifying. I just wanted to double check.
