### ISSUE TITLE
Issues with SQPOLL and connecting to unix domain sockets

### ISSUE THREAD

**Issue by johalun** [axboe/liburing#373]
I'm working on porting over an application from epoll to io_uring. In the single process case everything works great and the performance with SQPOLL enabled is outstanding. However, when I run multiple processes which communicate over unix domain sockets I get issues like connection failed when stressing the application with many requests (>2000/s). If I disable SQPOLL the multiprocess case works fine and handles over 9k request/s.

Are there any known issues with unix sockets used in combination with SQPOLL? 

Thanks!
Linux 5.12.13
liburing - HEAD as of last week.

**Comment by axboe** [comment]
Do you have a test case of some sort? That would make getting to the bottom of this a lot easier/quicker. Not aware of any SQPOLL related issues for sockets.

**Comment by johalun** [comment]
Not yet. Thought I ask here first if there are any known issues. The application I'm working on is really complicated and messy so the problem could be there as well. If I can't find the bug, I'll try write a test case see if I can reproduce it.

**Comment by johalun** [comment]
I found the issue. My code failed because io_uring_submit() returns a value larger than 1 (I've seen up to 8) sometimes when using sqpoll, even though I call io_uring_submit() after each io_uring_prep_xxx() call. Without sqpoll it always returns 1. Do you have an explanation for this? 

Closing this issue.

**Comment by axboe** [comment]
The return value of the system call or io_uring_submit() is not really stable with SQPOLL, as submission happens out-of-line from the SQPOLL thread. The most common return value will be the to_submit count in that case.

**Comment by johalun** [comment]
That makes sense. Thanks for clarifying!

**Comment by axboe** [comment]
I just committed a change to the io_uring_enter.2 man page to clarify that. Unfortunately liburing doesn't have a full set yet, but at least it's documented in one place now...

**Comment by isilence** [comment]
In case of SQPOLL the syscall always returns the number of SQEs we asked to submit (if no errors and so). I'd guess liburing specifies to submit all SQEs in the queue, and SQPOLL haven't reaped the events by that moment yet, but don't remember exactly and need to check the code.
