### ISSUE TITLE
Feature request: Support fallocate()

### ISSUE THREAD

**Issue by paxostv** [axboe/liburing#38]
It's not clear if/when fallocate blocks (notable exception for supportive network file systems) but regardless it'd be nice to include in the iouring framework since we can link fsyncs to commit file metadata changes.

**Comment by axboe** [comment]
https://git.kernel.dk/cgit/linux-block/commit/?h=io_uring-5.5&id=7c86138b7fba9d8876dbaf5c6783e78e30b7845b

**Comment by axboe** [comment]
Test case: https://git.kernel.dk/cgit/liburing/commit/?id=01e247d79d96fa59b373db7705a2055720be3cf6

**Comment by paxostv** [comment]
Awesome, thank you!
