### ISSUE TITLE
The lock &rd.mutex is locked twice (may lead to error)

### ISSUE THREAD

**Issue by anson-lo** [axboe/liburing#380]
Hi developers:
    It seems the lock `re.mutex` is released twice, which can lead to deadlock. I guess the second statement should be unlocked, which may be a programming mistake. It is in the test folder but still worth fixing for higher quality. Thank you for your checking.

The lock is acquired first.
https://github.com/axboe/liburing/blob/a209abe65befe603311b6fcd861e14d28e3e2f2d/test/send_recv.c#L248

The lock is acquired again.
https://github.com/axboe/liburing/blob/a209abe65befe603311b6fcd861e14d28e3e2f2d/test/send_recv.c#L258

The relevant code is shown here.

```
static int test(int use_sqthread, int regfiles)
{
	pthread_mutexattr_t attr;
	pthread_t recv_thread;
	struct recv_data rd;
	int ret;
	void *retval;

	pthread_mutexattr_init(&attr);
	pthread_mutexattr_setpshared(&attr, 1);
	pthread_mutex_init(&rd.mutex, &attr);
	pthread_mutex_lock(&rd.mutex);

	...;
	pthread_mutex_lock(&rd.mutex);

}
```

Best,

**Comment by axboe** [comment]
The thread created releases this, the double lock is to serialize between them.

**Comment by anson-lo** [comment]
@axboe  Hi, thank you for your detailed reply. The created thread `&recv_thread` could not release the lock `&rd.mutex` that is held by the main thread. A thread can release a lock except acquiring that before.

The lock is acquired by the main thread twice or the created thread releases the lock without being acquired, which might lead to undefined behavior.


Thus, the lock should be removed to the beginning of the recv_fc.
https://github.com/axboe/liburing/blob/a209abe65befe603311b6fcd861e14d28e3e2f2d/test/send_recv.c#L248

```

static void *recv_fn(void *data)
{
	// pthread_mutex_lock(&rd->mutex); // insert here.
        struct recv_data *rd = data;
	char buf[MAX_MSG + 1];
	struct iovec iov = {
		.iov_base = buf,
		.iov_len = sizeof(buf) - 1,
	};
	struct io_uring_params p = { };
	struct io_uring ring;
	int ret, sock;

	if (rd->use_sqthread)
		p.flags = IORING_SETUP_SQPOLL;
	ret = t_create_ring_params(1, &ring, &p);
	if (ret == T_SETUP_SKIP) {
		pthread_mutex_unlock(&rd->mutex);
		ret = 0;
		goto err;
	} else if (ret < 0) {
		pthread_mutex_unlock(&rd->mutex);
		goto err;
	}

	if (rd->use_sqthread && !rd->registerfiles) {
		if (!(p.features & IORING_FEAT_SQPOLL_NONFIXED)) {
			fprintf(stdout, "Non-registered SQPOLL not available, skipping\n");
			pthread_mutex_unlock(&rd->mutex);
			goto err;
		}
	}

	ret = recv_prep(&ring, &iov, &sock, rd->registerfiles);
	if (ret) {
		fprintf(stderr, "recv_prep failed: %d\n", ret);
		goto err;
	}
	pthread_mutex_unlock(&rd->mutex);
	ret = do_recv(&ring, &iov);

	close(sock);
	io_uring_queue_exit(&ring);
err:
	return (void *)(intptr_t)ret;
}
```

**Comment by anson-lo** [comment]
Also, since the created thread does not acquire the lock, race conditions may happen.

**Comment by axboe** [comment]
> The created thread &recv_thread could not release the lock &rd.mutex that is held by the main thread

It most certainly can, and it does. If it wasn't for that, then the test itself would deadlock every time as the lock is acquired to lock it, and then re-locked later to synchronize with the recv_fn() thread. If the recv_fn() didn't release it, then we'd deadlock in the main thread forever.

**Comment by axboe** [comment]
Note that this is somewhat platform specific. POSIX may not guarantee that it works, but it does on Linux and the liburing code is (so far) Linux specific. Is it the best or most obvious way to do thread synchronization? No, definitely not. I'll be happy to take patches to eg change it to pthread barriers instead.

**Comment by anson-lo** [comment]
@axboe Thank you for your detailed reply.

Additionally, because the execution of the created thread that runs the `recv_fn` method is not deterministic, even if the lock `&rd.mutex` can be released by the created thread, the release of the lock at which statements (line 248 or 259) is also non-determinsitic. I still believe there is an error.

https://github.com/axboe/liburing/blob/master/test/send_recv.c#L248

https://github.com/axboe/liburing/blob/master/test/send_recv.c#L259

```
static int test(int use_sqthread, int regfiles)
{
	...;
	pthread_mutex_lock(&rd.mutex);  // first lock statement
	rd.use_sqthread = use_sqthread;
	rd.registerfiles = regfiles;

	ret = pthread_create(&recv_thread, NULL, recv_fn, &rd);
	if (ret) {
		....;
	}

	pthread_mutex_lock(&rd.mutex); // second lock statment
	do_send();
	pthread_join(recv_thread, &retval);
	return (int)(intptr_t)retval;
}
```


```
static void *recv_fn(void *data)
{
	...;
	if (ret == T_SETUP_SKIP) {
		pthread_mutex_unlock(&rd->mutex);
		ret = 0;
		goto err;
	} else if (ret < 0) {
		pthread_mutex_unlock(&rd->mutex);
		goto err;
	}

	if (rd->use_sqthread && !rd->registerfiles) {
		if (!(p.features & IORING_FEAT_SQPOLL_NONFIXED)) {
			fprintf(stdout, "Non-registered SQPOLL not available, skipping\n");
			pthread_mutex_unlock(&rd->mutex);
			goto err;
		}
	}

	ret = recv_prep(&ring, &iov, &sock, rd->registerfiles);
	if (ret) {
		fprintf(stderr, "recv_prep failed: %d\n", ret);
		goto err;
	}
	pthread_mutex_unlock(&rd->mutex);
	ret = do_recv(&ring, &iov);

	close(sock);
	io_uring_queue_exit(&ring);
err:
	return (void *)(intptr_t)ret;
}

```

**Comment by axboe** [comment]
Not sure what you mean here, those two lines are acquiring the lock, not releasing it.

**Comment by anson-lo** [comment]
I mean, suppose that the child thread can release the lock held by the parent thread. In the above program, the `pthread_mutex_unlock(&rd->mutex);` in the created thread can release the lock held by the main thread at Line 258 or at Line 248, which is not deterministic. 

I am also very curious about this. I would try to extract this code pattern and run it on Linux. Let me show you the results soon. Thank you!

**Comment by axboe** [comment]
The point is that the main thread cannot proceed until the created thread has released the mutex. Hence we're waiting for setup etc in the created thread. The lock at 258 cannot be held before the created thread has already released the mutex, this is fully deterministic.

And then let's finally put this to rest.

**Comment by anson-lo** [comment]
@axboe Hi, I successfully ran this test case in Linux, and no bugs were found. Learn a lot from this issue and thank you for your detailed reply!
