### ISSUE TITLE
The lock mutex is locked twice (may lead to error),similar to  #380 but in different functions

### ISSUE THREAD

**Issue by anson-lo** [axboe/liburing#381]
Hi developers:
It seems the lock re.mutex is released twice, which can lead to deadlock. I guess the second statement should be unlocked, which may be a programming mistake. It is in the test folder but still worth fixing for higher quality. Thank you for your checking.

The lock is acquired first.

https://github.com/axboe/liburing/blob/a209abe65befe603311b6fcd861e14d28e3e2f2d/test/send_recvmsg.c#L292

The lock is acquired again.
https://github.com/axboe/liburing/blob/a209abe65befe603311b6fcd861e14d28e3e2f2d/test/send_recvmsg.c#L304

The relevant code is shown here.

```
static int test(int buf_select, int no_buf_add, int iov_count)
{
	...;
	pthread_mutex_lock(&mutex);  // first acquisition
        ...;
	ret = pthread_create(&recv_thread, NULL, recv_fn, &rd);
	...;
	pthread_mutex_lock(&mutex);  // second acquisition
	...;

	return ret;
}
```

**Comment by axboe** [comment]
Same serialization setup as the previous issue you created.
