### ISSUE TITLE
io_uring_enter may hang under high network IO loads

### ISSUE THREAD

**Issue by npuichigo** [axboe/liburing#383]
Recently, I use io_uring in libunifex to construct a tcp socket program. (my kernel is 5.13)

Here I use io_uring together with coroutines like:
```c++
io_context ctx;
inplace_stop_source stop_source;
std::thread t{[&] { ctx.run(stop_source.get_token()); }};

sync_wait([&]() -> task<void> {
    auto listener = listen_on(scheduler, 6666);
    while (true) {
      auto[socket, client_address] = co_await async_accept(listener);
      char data[1024];
      auto bytes_read = co_await async_recv(socket, as_writable_bytes(span{data}));
      co_await async_send(socket, as_bytes(span{message, strlen(message)}));
    }
  }());
```

But it may hang at the line of io_uring_enter under high IO loads.

```
io_uring_enter() - submit 0, wait for 1, sqUnflushedCount 0, cqPendingCount 2
```

I wrote some demo codes [here](https://github.com/npuichigo/crpc) and u can use benchmarking tool like [wrk](https://github.com/wg/wrk) to test the server. It's nice of you to take a look.

The server may hang if you increase the connections and extend the testing duration.

**Comment by npuichigo** [comment]
It seems that someone also has related [issues](https://github.com/frevib/io_uring-echo-server/blob/io-uring-feat-fast-poll/benchmarks/benchmarks.md#extra-info).

**Comment by npuichigo** [comment]
@axboe

**Comment by isilence** [comment]
Has it been resolved?

**Comment by npuichigo** [comment]
@isilence Yes. It's not a issue of io_uring but starve of coroutines in my implementation

**Comment by isilence** [comment]
Great that you narrowed it down
