### ISSUE TITLE
Async request failed: Resource temporarily unavailable

### ISSUE THREAD

**Issue by MarcoF1** [axboe/liburing#390]
I am working on a multithreaded version of [this io_uring echo server](https://github.com/openanolis/io_uring-echo-server) and running into issues with some of the completion queue entries. 

When I add an error handling message lines 241-248 as shown in [this github gist](https://gist.github.com/MarcoF1/041e56464711d9b9430954f0b40b5c48) (error handling message taken from [io_uring by example](https://unixism.net/2020/04/io-uring-by-example-part-3-a-web-server-with-io-uring/) lines 398-402),
I run into: 

> Async request failed: Resource temporarily unavailable for event: 3

Is this an issue with how the request is structured? If so, where is it going wrong? Without that error handling code, it seems to be working but I am not sure if it is just failing silently.

I am running Linux kernel 5.13 on Ubuntu, using the most recent version of liburing on master (commit hash: e3ad4f33a7cda4e0b5f86c009e3f587e02830753), and running the code as described in the echo server github repo

**Comment by YoSTEALTH** [comment]
1. Try to use `socket()` without `| SOCK_NONBLOCK` https://gist.github.com/MarcoF1/041e56464711d9b9430954f0b40b5c48#file-io_uring-echo-server-c-L171 Unixism example doesn't use that as well. To put it simple, you don't need to use `*_NONBLOCK` with `io_uring`, its already asynchronous!
2. Even if you were wanting to use `*_NONBLOCK` you weren't catching that `EGAIN` to poll and try again.
3. You should check `cqe->res` result before trying to get `user_data` info from it https://gist.github.com/MarcoF1/041e56464711d9b9430954f0b40b5c48#file-io_uring-echo-server-c-L237-L243

**Comment by YoSTEALTH** [comment]
I had to come back and look at this when I had bit of free time.

I am not sure what you are doing with `io_uring_register_files_update` https://gist.github.com/MarcoF1/041e56464711d9b9430954f0b40b5c48#file-io_uring-echo-server-c-L256 seems like you register `fd` but don't really use it! Also you are suppose to keep track of `index` not `fd`. You then use `index` as
`io_uring_prep_recv(sqe, index, ....)`

Maybe you are still trying to figure out how to use it...
- https://github.com/axboe/liburing/blob/master/test/file-register.c
- https://github.com/YoSTEALTH/Liburing/blob/master/test/register_file_test.py (if you can read python code)

**Comment by isilence** [comment]
> You should check cqe->res result before trying to get user_data info from it https://gist.github.com/MarcoF1/041e56464711d9b9430954f0b40b5c48#file-io_uring-echo-server-c-L237-L243

@YoSTEALTH, that's not true in general. You're always free to check `user_data` after getting a CQE. Moreover, it may be necessary in some cases, e.g. when you interpret result based on what kind of request it was.

**Comment by isilence** [comment]
> I had to come back and look at this when I had bit of free time.
> 
> I am not sure what you are doing with `io_uring_register_files_update` https://gist.github.com/MarcoF1/041e56464711d9b9430954f0b40b5c48#file-io_uring-echo-server-c-L256 seems like you register `fd` but don't really use it! Also you are suppose to keep track of `index` not `fd`. You then use `index` as
> `io_uring_prep_recv(sqe, index, ....)`

This should be fine, it just makes io_uring file table to mimic the normal process' fdtable, so indexes are always of the same values as fds.

**Comment by isilence** [comment]
@MarcoF1, Looks "Resource temporarily unavailable" is -EAGAIN (please, just print a numeric value next time), and it can happen if you specify NONBLOCK in any way. See the comment of @YoSTEALTH above about it, should help.

**Comment by MarcoF1** [comment]
Yep getting rid of `| SOCK_NONBLOCK` fixed the error. Thanks!
