### ISSUE TITLE
Feature Request: Single Register/Unregister FD

### ISSUE THREAD

**Issue by YoSTEALTH** [axboe/liburing#391]
Currently `io_uring_register_files_update()` requires liburing user to keep track of list/array of indexes.
- There isn't a good reason to keep track of all the indexes (io_uring at the back-end does this anyways?!)
- waste of resources.
- It might be confusing user since you can register same fd `value` over and over as new files fd, if previous fd was closed and being reused.

New functions needs to be added:

``` C
// note: still have to initialize with `io_uring_register_files` first

index = int io_uring_register_file_fd(&ring, int fd);
// note: should only allow for single update and returns: `index` or `-errno`

int io_uring_unregister_file_index(&ring, int index);
// note: single `index` removal, should return: `0` or `-errno`

// Optional - could add a way to also close fd:
index = int io_uring_register_file_fd(&ring, int fd, bool close_fd);
```

These feature would be nice to have but not really required, since there are current plans for open/register/close `sqe->buf_index` patch!

**Comment by isilence** [comment]
I could be misunderstanding, but do you know that `io_uring_register_files_update()` already can update/remove a single file? Even more, true any amount of consecutive indexes...

```C
int update_fds[2];

// prepare
{
    // limit scope of the var, not needed after io_uring_register_buffers().
    int table[50] = {-1, -1, 0, -1, ...};
    io_uring_register_buffers(table, 50);
}

// place @some_fd and @some_fd2 at indexes 2 and 3 respectively,
// which would also remove previously set files for there if any, e.g.
// fd=0 at index 2 in the example.
// Note: it doesn't modify anyhow @table.
update_fds[0] = some_fd;
update_fds[1] = some_fd2;
io_uring_register_files_update(update_fds, off=2, nr=2);

```

**Comment by YoSTEALTH** [comment]
> but do you know that io_uring_register_files_update() already can update/remove a single file?

Yes, I know you can do that, I have already written functions to do so. My point was more towards having io_uring at the back-end handling such tasks. Realistically speaking, don't see many use-case for update multiple fds at once.

``` Python

keep_track_fds = [-1, -1, -1]       # assume you enable 3 fds to keep track of
all_fds = files(keep_track_fds)     # convert int to c using cffi

fd = open()

index = 0
for value in keep_track_fds:
    if value == -1:
        keep_track_fds[index] = fd
        c_fd = files(fd)            # convert to c using cffi
        io_uring_register_files_update(ring, index, c_fd, 1)
    index += 1
```
All these conversion/tracking take speed hit for dynamic languages.

Could have been:

``` Python

io_uring_register_files(ring, 3)    # count of max keep track of fds (or set to max 2^15 by default)

fd = open()
index = io_uring_register_file_fd(ring, fd)
...
io_uring_unregister_file_index(ring, index)
```

Passing something like `int` directly back and forth is much better/faster then passing `struct` and such...

**Comment by isilence** [comment]
Ok, than it's not about registering a single fd, but rather "register, and make io_uring to find an empty slot".

I don't see why to do that, when the userspace already has all the flexibility. If that's a problem of managed languages, just write a chunk of code in C and allocate an array for fds in advance.

**Comment by YoSTEALTH** [comment]
ok, thanks.

**Comment by YoSTEALTH** [comment]
@isilence functions like `io_uring_prep_openat_direct` with the `*_direct` does that open and close `fd` automatically feature right? Then assigns `index` as the new fd like tracker...

Or is using anything with `fd` with `__io_uring_set_target_fixed_file` gives it that open/close behavior?
