### ISSUE TITLE
io_uring_wait_cqe_timeout() + IORING_ENTER_EXT_ARG doubling timeout duration

### ISSUE THREAD

**Issue by kplantjr** [axboe/liburing#393]
So far I have only observed this behavior with one sqe pending submission. If there are >1 sqes pending submission, the first `io_uring_enter()` call returns immediately.

When there is one cqe pending submission and a timeout is being provided via `IORING_ENTER_EXT_ARG` through `io_uring_wait_cqe_timeout()`, `io_uring_enter()` will submit the single pending sqe and wait for completion until the specified timeout. If `io_uring_enter()` successfully submits the sqe but the event has not completed within the timeout duration, `_io_uring_get_cqe()` will loop around to `io_uring_enter()` once more, this time with nothing to submit, and wait the timeout duration before returning -1 and setting errno to ETIMEDOUT.

In this scenario `io_uring_enter()` blocks for the entire timeout duration for both calls.

Summary:
```
struct io_uring_sqe *sqe;

sqe = io_uring_get_sqe(&ring);
io_uring_prep_whatever(sqe, ...);

/* one sqe not yet seen by the kernel */
io_uring_wait_cqe_timeout()

/*
 * io_uring_wait_cqe_timeout()
 * -> io_uring_wait_cqes()
 *    -> io_uring_wait_cqes_new()
 *       -> _io_uring_get_cqe() 
 *            __sys_io_uring_enter2()   sqe submitted, waiting for completion or timeout
 *            __sys_io_uring_enter2()   nothing to submit, waiting for completion or timeout
 */

**Comment by isilence** [comment]
Tried to reproduce with the test below, no luck, it enters the kernel only once. Also, I don't see `io_uring_wait_cqes_new()` flushing requests. See @data in the function, data->submit is defaulted to 0. 

What liburing version do you use? liburing git hash? What kernel version it was? Also, can you confirm whether `IORING_FEAT_EXT_ARG` is set? E.g. `ring->features & IORING_FEAT_EXT_ARG`.

```C
static int test(struct io_uring *ring)
{
	struct __kernel_timespec ts = { .tv_sec = 0, .tv_nsec = 10000000 };
	struct io_uring_cqe *cqe;
	struct io_uring_sqe *sqe;
	int ret, fds[2];
	char buffer[200];

	if (pipe(fds)) {
		perror("pipe");
		return 1;
	}
	sqe = io_uring_get_sqe(ring);
	io_uring_prep_read(sqe, fds[0], buffer, 10, 0);

	ret = io_uring_wait_cqe_timeout(ring, &cqe, &ts);
	fprintf(stderr, "ret %d\n", ret); // -62
	return 0;
}
```

**Comment by isilence** [comment]
@kplantjr, any comments?

**Comment by kplantjr** [comment]
@isilence apologies, I missed your first reply.

I have re-tested with a fresh pull of liburing 2.1 and am currently on 5.14, it's been a while but I believe my previous tests were all on 5.10/5.11.

My experience now mirrors yours exactly, no double timeout. My previous tests were likely invalid or something has changed to fix this. Either way thanks for taking a look, going to close this issue.

Thanks!
