### ISSUE TITLE
utilizing wq_fd together with IORING_SETUP_ATTACH_WQ returns EINVAL

### ISSUE THREAD

**Issue by akseg73** [axboe/liburing#398]
We are trying to utilize multiple threads to submit and reap i/o events. As suggested we initialize the first ring as normal and it works. But when we set the above on the second uring it returns error EINVAL. Does this feature even work at the moment?

#define IO_URING_DEPTH 4
  struct io_uring_params params;
  memset(&params, 0, sizeof(params));
  params.flags |= IORING_SETUP_SQPOLL;
  params.sq_thread_idle = __SQ_THRD_IDLE;

  if(__first_ring_fd_set) {
    /* this allows multiple user io_urings to utilize the same async
     * backend. Thus it should utilize the same SQLPOLL thread as well */
    params.wq_fd = cntxt->ring.ring_fd;
    params.flags = IORING_SETUP_ATTACH_WQ;
  }

  if((rc = io_uring_queue_init_params(IO_URING_QDEPTH, &cntxt->ring, &params))!=0) {
    rc = -1;
    goto cleanup;
  }

  if((rc = io_uring_register_files(&cntxt->ring, &fd, 1))!=0) {
    rc = -1;
    goto cleanup;
  }

**Comment by axboe** [comment]
What kernel? And are the rings created from the same task?

**Comment by akseg73** [comment]
Thanks for the response, This is being done in linux 5.4 in AWS linux

**Comment by axboe** [comment]
5.4 is too old to support that feature. Basically -EINVAL here means "some flag you set in the ring setup is not supported".

**Comment by akseg73** [comment]
What is the oldest linux version that supports that feature. We really need to get this working as soon as we can.

**Comment by axboe** [comment]
5.6 would be the oldest, but honestly if you're swapping kernels, I'd recommend using the latest stable. Even 5.6 is pretty old in that regard, that's almost 2 years ago.

**Comment by akseg73** [comment]
We can utilize linux kernel-5.10. Hopefully it will work well enough there. Do we have to download a specific version of liburing code for that kernel? Or can we simply download the most recent version of liburing and it will know that we are working on kernel-5.10 and support features that it can?

Basically we create the first ring single threaded and the remaining rings are created concurrently... hopefully there is no issue with concurrently created/destroying rings. If there is we can isolate those code points as they are quite infrequent.

regards

**Comment by axboe** [comment]
5.10 seems reasonable. The current release of liburing will work fine, there are really no library dependencies for this feature.

**Comment by akseg73** [comment]
thanks so much for the quick response. We will download the most recent version of liburing from Github ...and i will close this issue.

**Comment by akseg73** [comment]
I spent the whole of last day upgrading to Linux 5.10 in AWS and i also downloaded the latest version of liburing from Github and rebuilt everything from scratch and i still get EINVAL when utilizing wq_fd together with IORING_SETUP_ATTACH_WQ.

The code is as indicated in the first comment. And this is what i see with uname -r:
5.10.50-44.132.amzn2.x86_64

We are doing this in docker containers. However the host is also the same kernel.  Is it possible that this is not working because we are utilizing docker containers?  

Any help is greatly appreciated.

**Comment by axboe** [comment]
Could very well be that it's not working since it's in a docker container, I really have very little idea about that. I'd recommend cloning the liburing repo and building it all, then run test/shared-wq from there. That's a basic functionality test. If that works, then you are likely doing something wrong. If it doesn't, then likely docker is doing something funky.

**Comment by akseg73** [comment]
It sounds strange that it should be an issue. We are also utilizing this in combination with  IORING_SETUP_SQPOLL.
Is it known to work together with IORING_SETUP_ATTACH_WQ?

Allright i will rebuild and run. So far we were running in Docker and without ATTACH_WQ some of our tests pass.

**Comment by axboe** [comment]
Yes, it'll work with SQPOLL, in fact liburing also has a test case for that, test/sq-poll-share

**Comment by akseg73** [comment]
When rebuilding liburing i do run into the following problem:
io_uring_register.c:509:10: warning: implicit declaration of function 'memfd_create'; did you mean  timer_create'? [-Wimplicit-function-declaration]
  memfd = memfd_create("uring-shmem-test", 0);
          ^~~~~~~~~~~~
          timer_create
/tmp/cc91MvfX.o: In function `test_shmem':

after a bit of looking around it seems that including <syscall.h> together with utilizing SYS_memfd_create seems to make it work and additionally all the tests appear to pass, i ran

source ./test/runtests.sh

So the tests seem to pass ...

So inside the Docker container, all the tests pass. But when we run this in the product it fails with EINVAL. Is there anyway we can debug this further to see what may be causing it to return EINVAL. Is there some system call it is attempting which returns EINVAL. If so we can poke around to see what may be causing it to fail.

**Comment by akseg73** [comment]
should we fall back on strace to see why it failed ... let me try that?

**Comment by axboe** [comment]
Looking at your example:

```
if(__first_ring_fd_set) {
/* this allows multiple user io_urings to utilize the same async
* backend. Thus it should utilize the same SQLPOLL thread as well */
params.wq_fd = cntxt->ring.ring_fd;
params.flags = IORING_SETUP_ATTACH_WQ;
}

if((rc = io_uring_queue_init_params(IO_URING_QDEPTH, &cntxt->ring, &params))!=0) {
rc = -1;
goto cleanup;
}
```

it's not clear to me what is being set in params->wq_fd - just to be clear, that one should be set to the ring fd of the _original_ ring, and I can't tell if that's what you're doing as cnxt appears to be the new ring being registered. But it could just be that you're not including all of the code, and cnxt is allocated after that setting and it's the original ring to begin with?

In any case, if the test cases work, then you're doing something wrong in your code. -EINVAL is a horrible error code, but there's really nothing else that covers it. It'll get set for any invalid field in the params or setup.

**Comment by axboe** [comment]
io_uring_queue_init_params() boils down to a io_uring_setup(), and then later ring mmaps if that succeeds. If you strace, you're most likely seeing io_uring_setup() return -EINVAL due to some invalid parameter.

**Comment by akseg73** [comment]
You are right about that one. That is a copy paste error on my part. Sorry to bother you. Let me try to address that one.

**Comment by akseg73** [comment]
Thanks so much for your help. Im really sorry for taking up your time for what is my bug. Hopefully this fix will work. regards.

**Comment by axboe** [comment]
It's Friday, wasting a bit of time on this is healthier than drinking beer ;-)

**Comment by akseg73** [comment]
We are hoping that the SQPOLL will setup one thread which will be polling for the sqes. And our application on the other hand has potentially 100 threads each one of which has a tiny seq, cqe ring of length 4/8. All threads are actively submitting and reaping ... hopefully we should be able to leverage the random i/o aspects of SSDs with that. If you are interested i can keep you posted on any performance reads we see.

We are looking at doing random i/o on massive databases. In the ballpark of a few TBs. 

You have done a great service to the community by providing this library. Incidentally we also intend to look closely at SPDK which is utilizing a user mode polling model. In some usage scenarios that might offer some further advantages.

**Comment by axboe** [comment]
Definitely, keep us updated. If completion polling ends up being interesting as well, you can use IOPOLL with SQPOLL, fwiw.

**Comment by akseg73** [comment]
Sorry i read some articles which indicate that IOPOLL should not be combined with SQPOLL ... i don't know what the reasoning was provided ...  if you search for io_uring samsung, performance on google you will find the pdf document that talks about it ... it also compares it with SPDK.

Don't know why they suggest not combining IOPOLL with SQPOLL.

**Comment by akseg73** [comment]
Below is the link, they suggest do not utilize IOP with SQPOL

https://www.usenix.org/sites/default/files/conference/protected-files/vault20_slides_lund.pdf

**Comment by akseg73** [comment]
After the fix i get the error: ENXIO ... probably some incorrect fd sent it ... let me check ...

**Comment by akseg73** [comment]
Here is what i am finding about ENXIO:

The test sq-poll-share.c  does not utilize io_uring_register_files() to register fd.  From what i can see we have to utilize this API in order to register files for SQPOLL. If we do not utilize this API we can't even make a most basic test work. So there is something amiss.

**Comment by akseg73** [comment]
Incidentally we have a separate test that utilizes SQPOLL and it works very well and we follow nearly the same steps.
Its when we try to go multi-threaded that we run into issues. At the moment i am getting error ENXIO when invoking
io_uring_queue_init_params().

**Comment by akseg73** [comment]
closing the issue for now. It looks like sq-poll-share.c test is not working on linux. We have to understand that, and hopefully that will resolve this issue.
