### ISSUE TITLE
[Feature request] update / remove multi-shot poll reqs with fd?

### ISSUE THREAD

**Issue by CarterLi** [axboe/liburing#399]
Currently we support [updating / removing poll reqs with `user_data`](https://github.com/axboe/liburing/blob/72a943982615b655d0cfc08f882ab91079f3287e/src/include/liburing.h#L326). The api designs are aligned with other update / remove prep functions. However as epoll is currently widely used, the api design makes it harder migrating epoll to io_uring because [epoll uses fd to match the old poll requests](https://man7.org/linux/man-pages/man2/epoll_ctl.2.html).

I'm suggesting that [when the `fd` field of IORING_OP_POLL_REMOVE is set to value other then `-1`](https://github.com/axboe/liburing/blob/72a943982615b655d0cfc08f882ab91079f3287e/src/include/liburing.h#L329), we should use `fd` field to match the old poll request, which makes migrating existing epoll code much easier.

**Comment by TheClonerx** [comment]
But if you added multiple poll requests to the same file descriptor, which one should be removed then?

**Comment by axboe** [comment]
We do have cancel support based on eg fd now.
