### ISSUE TITLE
Feature request: timed waiting support

### ISSUE THREAD

**Issue by CarterLi** [axboe/liburing#4]
Timed waiting is [commonly](https://github.com/libuv/libuv/blob/040543eebf4983b1459a1e0e0e26dae68b80cc28/src/unix/linux-core.c#L284) [used](https://github.com/nginx/nginx/blob/master/src/event/modules/ngx_epoll_module.c#L493) and a necessary feature to replace epoll_wait (for fewer syscalls and better integration with io_uring file aio).

AFAIK the old [Linux AIO does support timed-wait](https://github.com/torvalds/linux/blob/master/fs/aio.c#L2073). Please consider adding timed-wait support to io_uring too.

**Comment by axboe** [comment]
Can you elaborate on what would be most handy? Are you thinking a wait primitive added to io_uring_enter() for when GETEVENTS is set?

**Comment by CarterLi** [comment]
> Can you elaborate on what would be most handy? Are you thinking a wait primitive added to io_uring_enter() for when GETEVENTS is set?

Yes.

```c
int io_uring_enter(unsigned int fd, unsigned int to_submit,
                   unsigned int min_complete, unsigned int flags,
                   sigset_t *sig, unsigned long timeout);
```

But it breaks old code. I don't know if we should introduce a new fn like `io_uring_enter2` or something else.

**Comment by axboe** [comment]
It would have to be a new system call, and more arguments is slower. 7 arguments is the max, don't even know if all platforms are OK with this or run that at full speed.

How about we add a specific timeout command? Before doing io_uring_enter() waiting for events, the application fills in an SQE with a IORING_OP_TIMEOUT command. The application does io_uring_enter(fd, 1, min_complete, IORING_ENTER_GETEVENTS, ...) which submits the timeout command and proceeds to wait. The timeout command will complete in the specified time, and post a completion event like any other command. This completion event will wake up the io_uring_enter() application waiting on the cq ring, if nothing else has already.

Just requires me to add a timeout command, should be trivial.

**Comment by axboe** [comment]
Here it is:

https://lore.kernel.org/linux-block/f0488dd6-c32b-be96-9bdc-67099f1f56f8@kernel.dk/

and liburing has a test case as well for it:

http://git.kernel.dk/cgit/liburing/commit/?id=8362ba6029911ab3c45fa22fa9e4bda659a28607

**Comment by CarterLi** [comment]
`timeout` is useful, but it's a little different from timed waiting. Because `timeout` will always finish no matter the `IORING_ENTER_GETEVENTS` operation that you are waiting expires or not.

```c
// dummy code
io_uring_prep_noop();
io_uring_prep_timeout(100ms); // timeout1
io_uring_submit_and_wait(); // how can I know whether the operation finished?

// prep_noop was finished but prep_timeout is still running, and there is no way to cancel the timeout.

io_uring_prep_preadv();
io_uring_prep_timeout(100ms); // timeout2
io_uring_submit_and_wait(); // how can I know which timeout expires?
```

In order to fix this issue, we must introduce a loop

```c
enum async_operation {
  noop,
  preadv,
  timeout,
};

struct my_data {
  async_operation op;
  int id;
};

// dummy code
io_uring_prep_noop();
struct my_data data1 = { .op = noop, .id = unique_id1 };
io_uring_sqe_set_data(&data1);
io_uring_prep_timeout(100); // timeout1
struct my_data data2 = { .op = timeout, .id = unique_id1 };
io_uring_sqe_set_data(&data2);
io_uring_submit_and_wait();
assert(((struct my_data*)io_uring_cqe_get_data())->op == noop); // the operation didn't expire.
io_uring_cqe_seen();

io_uring_prep_other_operation();
struct my_data data3 = { .op = preadv, .id = unique_id2 };
io_uring_sqe_set_data(&data3);
io_uring_prep_timeout(100); // timeout1
struct my_data data4 = { .op = timeout, .id = unique_id2 };
io_uring_sqe_set_data(&data4);

struct my_data *pdata;
do {
    io_uring_submit_and_wait();
    pdata = io_uring_cqe_get_data();
    io_uring_cqe_seen();
} while (pdata->id == unique_id2);

bool preadv_expired = pdata->op === timeout;
```

In real code that uses event loop, `prep_operation` and `io_uring_submit_and_wait` are often called in different places. Userdata must be allocated in heap and timed wait is called rather often. Therefore more syscalls timeout_ops and mallocs are needed.

Thus I still think extending io_uring_enter is better.

**Comment by CarterLi** [comment]
Because IORING_OP_TIMEOUT is not cancelable, I would rather prefer polling a timer fd because IORING_OP_POLLADD can be removed and the timeout of timerfd can be reset using timerfd_settime

**Comment by axboe** [comment]
A few comments - the timeout op really has to finish and post a completion, that's how io_uring works. If we make timeout behave differently, then that's a bit odd. You don't need to allocate memory for the timeout. Most IO commands will have per command data associated with it, but a timeout really doesn't need that. And you can bundle the timeout sqe queue with the application calling io_uring_wait_cqe_timeout() or something like that, then it happens behind your back. Only restriction would then be that you need an SQE entry free in the ring, but that's something that can be factored in (even if it's not the prettiest).

**Comment by axboe** [comment]
That said, we could introduce TIMEOUT flags to manage this behavior:

- Flags == 0, behavior that is in the above patch. When the timeout expires, the cq ring is woken as a completion event is placed.
- Flags == TIMEOUT_COUNT, and sqe->off == count. Wake the ring and post a completion event only if less then count entries have been posted to the ring since queued. If count or more entries have been posted since the timeout was queued, nothing happens.

**Comment by CarterLi** [comment]
> the timeout op really has to finish and post a completion, that's how io_uring works.

I agree. That's why I think timeout for timed_waiting should not be implemented using opcode.

> And you can bundle the timeout sqe queue with the application calling io_uring_wait_cqe_timeout() or something like that, then it happens behind your back.

I don't quite understand what you said. Do you mean let the userdata of sqe be NULL, and test cqe->userdata == NULL? In this case you can't determine which timeout is expired as shown in my code above. Could you please write some pseudo code?

> Flags == TIMEOUT_COUNT, and sqe->off == count. Wake the ring and post a completion event only if less then count entries have been posted to the ring since queued. If count or more entries have been posted since the timeout was queued, nothing happens.

Still don't understand, sorry for my bad English.

**Comment by axboe** [comment]
Why do you care which timeout expired? If you do care, you could stuff the required data on the stack for the timeout, since it will expire in the same scope as your io_uring_enter() call. You don't need a dynamic allocation for this. Right now I made the timeout either -ETIME if it times out, or 0 if the number of events cancelation triggers it instead. I can see the case being made for using -ECANCELED for that instead. But if you know what the event is, see above, then -ETIME vs 0 should tell you that. And to be honest, races can happen where both conditions trigger at the same time, so it should not really matter which one it is for timeouts.

See:

http://git.kernel.dk/cgit/linux-block/commit/?h=for-5.4/io_uring&id=16c73a2fe7667f15a6bb389765bc2ff4e7613c7f

and the liburing test cases:

http://git.kernel.dk/cgit/liburing/commit/?id=55468e5eca8c70a3f3d798218c708d7bf485481e

**Comment by CarterLi** [comment]
See example/ucontext-cp. If you want to replace io_uring_wait_cqe at https://github.com/axboe/liburing/blob/master/examples/ucontext-cp.c#L168 with io_uring_timedwait_cqe, how can you ensure that every timedwait won't be incorrectly waked up by previous IOURING_TIMEOUT_OP?

> If you do care, you could stuff the required data on the stack for the timeout

You can't if you are in a loop, like in examples/ucontext-cp.c. You can't use iteration variable, because you can't distinguish if it's a pointer set/generated in other place.

Please provide a function named io_uring_timedwait_cqe, and you'll see what I'm warrying about is.

**Comment by axboe** [comment]
http://git.kernel.dk/cgit/liburing/commit/?h=timeout&id=095bafc04ef9b72ebfcf61c5665ca1267542381f

Something like this, untested outside of the simple test case. Idea is pretty simple - handle the timeout sqe internally. Queue one up before entering timed wait, and discard it when we find completions. Use a reserved ->user_data value to distinguish the timeout from other cqes.

**Comment by axboe** [comment]
This obviously relies on having an SQE available, we can call io_uring_submit() if we don't. So that's not a huge worry. Other than that, it obviously commandeers ->user_data being 0xffffffffffffffff, so that value can't be used by the application. I don't think the latter is a huge concern, though it should be made clear in the documentation for io_uring_wait_cqe_timeout() of course.

**Comment by CarterLi** [comment]
```
io_uring_prep_noop()
submit()
io_uring_wait_cqe_timeout(100ms)
io_uring_prep_work() // requires 200ms
submit()
io_uring_wait_cqe_timeout(300ms)
```

How long will the last wait_cqe_timeout wait?
