### ISSUE TITLE
sq-poll-share.c

### ISSUE THREAD

**Issue by akseg73** [axboe/liburing#400]
I built liburing with the most recent Github download and built it and i had to make a small change to io_uring_register.c:

change: fd = memfd_create( ....
to:  fd = syscall(SYS_memfd_create, ....

After the above change it builds fine and when i run the test like so:
./test/sq-poll-share
No SQPOLL sharing, skipping

when i do uname -r i get:
5.10.50-44.132.amzn2.x86_64

It looks like sq-poll-share is not working on linux 5.10.

Any help is greatly appreciated.  This was done on a linux machine without utilizing any containers.

**Comment by isilence** [comment]
5.10 does actually support SQPOLL sharing, that's just the test is wrong. `sq-poll-share` checks for `IORING_FEAT_SQPOLL_NONFIXED`, which came in 5.11, fails to find it and fails with that confusing message.

**Comment by akseg73** [comment]
Ok thanks. So i should ignore that error message. Now i will try to utilize register file descriptor to see what happens.

**Comment by akseg73** [comment]
I changed the sq-poll-share.c to add the below line immediately below the io_uring_queue_init_params() invocation

                if((ret = io_uring_register_files(&rings[i], &fd, 1))!=0) {
                   goto err;
                }
I get the following error when i run the test:
Unexpected ret -9

Which is EBADF

So i am not able to register file descriptor ...

**Comment by akseg73** [comment]
In our product tests we have also noticed that when we don't register the fd, we get EBADF on the reads.

**Comment by isilence** [comment]
That's weird, but hard to guess without source code.
I hope that `fd` var is not an io_uring fd, because it's disallowed.

**Comment by akseg73** [comment]
the source code is sq-poll-share.c ... we only added the one line to register the file descriptor with io_uring_register_files

**Comment by isilence** [comment]
> In our product tests we have also noticed that when we don't register the fd, we get EBADF on the reads.

SQPOLL wasn't working with non-registered files and that got lifted in 5.11. That what this `IORING_FEAT_SQPOLL_NONFIXED` flag is about.

**Comment by akseg73** [comment]
SQPOLL wasn't working with non-registered files and that got lifted in 5.11. That what this IORING_FEAT_SQPOLL_NONFIXED flag is about.

@isilence, we are registering the files and we still get EBADF in the test sq-poll-share.c ... so there must be something still missing.

**Comment by axboe** [comment]
Are you using the registered index and not the real fd for your sqe? If you get -EBADF, it's not liking the file descriptor, and the most likely explanation is that.

As Pavel said, it's hard to debug anything without source code, and guessing at a problem isn't super productive unfortunately.

**Comment by isilence** [comment]
I get it, that's the reason you can't use non-registered with 5.10. For the `EBADF`, apart from registering a file did you modify your code to actually use it?

```diff
diff --git a/test/sq-poll-share.c b/test/sq-poll-share.c
index a46b94f..677cd59 100644
--- a/test/sq-poll-share.c
+++ b/test/sq-poll-share.c
@@ -61,7 +61,9 @@ static int queue_io(struct io_uring *ring, int fd, int nr_ios)
 		sqe = io_uring_get_sqe(ring);
 		if (!sqe)
 			break;
-		io_uring_prep_read(sqe, fd, vecs[i].iov_base, vecs[i].iov_len, off);
+		fd_index = 0; // you registered only 1 file, so it's index 0
+		io_uring_prep_read(sqe, fd_index, vecs[i].iov_base, vecs[i].iov_len, off);
+		sqe->flags |= IOSQE_FIXED_FILE;
 		nr_ios--;
 		i++;
 		off += BS;
@@ -107,6 +109,9 @@ int main(int argc, char *argv[])
 			fprintf(stderr, "queue_init: %d/%d\n", ret, i);
 			goto err;
 		}
+		if((ret = io_uring_register_files(&rings[i], &fd, 1))!=0) {
+			goto err;
+		}
 		/* no sharing for non-fixed either */
 		if (!(p.features & IORING_FEAT_SQPOLL_NONFIXED)) {
 			fprintf(stdout, "No SQPOLL sharing, skipping\n");
```

**Comment by akseg73** [comment]
@islience your hunch was correct we did not utilize the fd the ode that utilizes it is
    io_uring_prep_read(sqe, fd, vecs[i].iov_base, vecs[i].iov_len, off);

we change it to:
  io_uring_prep_read(sqe, 0, vecs[i].iov_base, vecs[i].iov_len, off);

but we still get EBADF ....

**Comment by isilence** [comment]
Just to be clear, did you also set IOSQE_FIXED_FILE?

**Comment by akseg73** [comment]
@iselience, no I forgot to do that. Let me do that now.

**Comment by axboe** [comment]
@akseg73 I'd be willing to bet that your code is buggy. We don't mind helping, but please spend some time on the issue on your end first. As mentioned in the previous comment, debugging by guessing what the code issue is, is not very productive.

**Comment by akseg73** [comment]
Thanks for your response. I am sorry to be bothering you. We are newbies and quite frequently shoot ourself in the foot.

It would be great if we can enhance sq-poll-share.c with registered file descriptor. It would be a reasonable test to keep around.

**Comment by akseg73** [comment]
Right now right out of the box when we run sq-poll-share.c without any modifications (except for commenting out check for ORING_FEAT_SQPOLL_NONFIXED)  at all we get EBADF. 

We are now running the test sq-poll-share.c without much change and it returns EBADF. There must be something related to environment/compiler etc which is interfering.

please let us know .... this does not really look like our bug. We have not changed the test much.

**Comment by isilence** [comment]
You was getting EBADF because 5.12 doesn't support non-registered files. After registering but not using it, you was getting EBADF for the same reason, it was trying to create a requests with normal / non-registered file. And now I'd be reasonable to guess you get it because registered files are still not or wrongfully used.

Paste a diff with __all__ your changes, otherwise it's hard to blind guess. Or try out the one above + killed `IORING_FEAT_SQPOLL_NONFIXED` check with a fresh liburing. I haven't tried it with 5.10, but should work.

**Comment by akseg73** [comment]
@isilence, we are simply trying to run sq-poll-share.c with the only lines commented out because of your advice, we commented these lines out because you said that iin 5.10 it is mistakenly checking for this, other than this one change we did not modify the test at all:

                /* no sharing for non-fixed either */
                //if (!(p.features & IORING_FEAT_SQPOLL_NONFIXED)) {
                //      fprintf(stdout, "No SQPOLL sharing, skipping\n");
                //      return 0;
                //}

We are literally not modifying the test other than the above lines and it still returns EBADF.

**Comment by isilence** [comment]
And that's expected, because even though it supports SQPOLL sharing in 5.10, SQPOLL doesn't support non-registered files, so it returns -EBADF.

I mean the changes with attempts to use registered files

**Comment by akseg73** [comment]
@isilence. So first of all you are acknowledging that the test is broken out of the box. At this point rather than relying on my code, it would be better if you can add the 2  lines  of code yourself where ever you see appropriate. It would be good to do that anyway because it will be better to checkin a working tests that others can utilize.

This is all sq-poll-share.c at this point. This is not our code at all.

**Comment by isilence** [comment]
> @isilence, we are simply trying to run sq-poll-share.c with the only lines commented out because of your advice, we commented these lines out because you said that iin 5.10 it is mistakenly checking for this, other than this one change we did not modify the test at all:

I'll emphasize for history, it's not a wrong check, just the message it prints is misleading.

**Comment by akseg73** [comment]
It would be good to have the test working with registered file descriptors because that is a use case others might be trying to mimic.

**Comment by isilence** [comment]
> @isilence. So first of all you are acknowledging that the test is broken out of the box.

No, it's not. You did remove the check on which it had been relying, and it started to fail. Do you see a connection here?

**Comment by akseg73** [comment]
@isilince i request that the test be enhanced a little bit to include registering of files and that version be checked in so that users can simply mimic what this test does.

As i mentioned below we are taking baby steps and at this point we will just mimic what we see is working.

**Comment by isilence** [comment]
The diff is above, posted an hour ago. Should work with 5.11+, and with 5.10 if you also remove the `IORING_FEAT_SQPOLL_NONFIXED` check. You're welcome

**Comment by akseg73** [comment]
Yes, that diff does indeed work, i forgot about that diff in the middle of the other stuff. Would you like to check that in with the test? It does work i am able to confirm it.

**Comment by akseg73** [comment]
Thanks so much for helping with this. I will close this issue now.

**Comment by akseg73** [comment]
There is an associated question to understand. When we invoke:

io_uring_register_files(ring, fdarr, sz)

what is the require lifetime of the fdarr?  Could it be stack local variable?  Is the array required to be alive or could it be on the stack and die later?

**Comment by axboe** [comment]
It can be on-stack, lifetime is just for the duration of the registration call.

**Comment by akseg73** [comment]
Yes so we debugged our code and as you pointed out its our fault. In a multi-threaded process we have to be careful that when the threads are done running, the very first thread that setup the ring can not exit the ring or close the associated file descriptor.
Because it is still being referenced by the other threads.

Its a mistake that newcomers are likely to make.

**Comment by akseg73** [comment]
I have a related question about O_DIRECT which is required for the IOPOLL mode. If we open a file descriptor with O_DIRECT and utilize it for a read(). If a page happens to be in the OS buffer pool will O_DIRECT read from the OS buffer pool?  If not then there is a danger that O_DIRECT will return older version of a page if the page has been modified. O_DIRECT seems to indicate direct i/o but does that means OS buffer pool will be completely ignored?

**Comment by axboe** [comment]
Yes, it ignores the page cache. This is a pretty tricky topic and lots have been written on it, I'd encourage you to google and look for mixed O_DIRECT and buffered - it's generally discouraged.

**Comment by akseg73** [comment]
Simply enabling IORING_SETUP_SQPOLL starts to interfere with the performance of our product. If we
disable it then performance is as expected. This is without even performing any i/o. We simply enable
IORING_SETUP_SQPOLL and the product starts to see all kinds of performance issues. I would have
imagined that sq_thread_idle is supposed to take care of this issue. Is this to be expected? I hope we
are making some mistake.
