### ISSUE TITLE
[Question] Is io_uring_wait_cqes safe with IORING_FEAT_EXT_ARG?

### ISSUE THREAD

**Issue by seunghunee** [axboe/liburing#402]
For kernels with `IORING_FEAT_EXT_ARG`, `io_uring_wait_cqes` do not implicitly submit.
https://github.com/axboe/liburing/blob/master/src/queue.c#L274

But, `io_uring_wait_cqes_new` which `io_uring_wait_cqes` call when `IORING_FEAT_EXT_ARG` is enabled seems like flushing sq to submit sqes.
https://github.com/axboe/liburing/blob/master/src/queue.c#L251

Which one is correct?

**Comment by axboe** [comment]
That does look like a bug in the new handling, it should not flush the SQ ring. I'll take a look!

**Comment by YoSTEALTH** [comment]
Would it be too late to change `io_uring_wait_cqes_new` to `__io_uring_wait_cqes` and have it be an internal function to `io_uring_wait_cqes`? Some might think the `_new` is replacement to the current function. Also calling `io_uring_wait_cqes_new` directly assumes `ts` and `IORING_FEAT_EXT_ARG` is set, does it not?

**Comment by axboe** [comment]
It is an internal function, and hence not visible nor available to applications.

> Also calling io_uring_wait_cqes_new directly assumes ts and IORING_FEAT_EXT_ARG is set, does it not?

Not sure I follow that question, the function itself sets the flag.
