### ISSUE TITLE
sq_thread_idle is it in milliseconds?

### ISSUE THREAD

**Issue by akseg73** [axboe/liburing#407]
when setting sq_thread_idle to 2000 we see severe degradation in performance without any i/o going on. Presumably any thread being run on behalf of SQPOLL is causing it. When we change the value to 10, then the performance problems go away.

Is sq_thread_idle really in milliseconds?  hopefully it is not in seconds. A small comment in the code may be useful for others.

**Comment by ammarfaizi2** [comment]
> Is sq_thread_idle really in milliseconds?

Yes, it is in milliseconds. It has already been mentioned in `man 2 io_uring_setup`.

IORING_SETUP_SQPOLL

When this flag is specified, a kernel thread is created to perform submission queue polling. An io_uring instance configured in this way enables an application to issue I/O without ever context switching into the kernel. By using the submission queue to fill in new submission queue entries and watching for completions on the completion queue, the application can submit and reap I/Os without doing a single system call.

If the kernel thread is idle for more than sq_thread_idle **milliseconds**, it will set the IORING_SQ_NEED_WAKEUP bit in the flags field of the struct io_sq_ring.

Ref: https://manpages.debian.org/unstable/liburing-dev/io_uring_setup.2.en.html

**Comment by akseg73** [comment]
I read that documentation. Perhaps we should tie this thread to a specific CPU core so that it does not impact the rest of the product. May be that is the explanation for what we are seeing. when we have the sq_thread_idle set to 2000 it seems to cause a lot of problems, whereas when it is set to 10 it doesnt. This is a situation when i/o is not actually needed.

perhaps utilizing a specific cpu core is the solution

**Comment by ammarfaizi2** [comment]
> Perhaps we should tie this thread to a specific CPU core so that it does not impact the rest of the product.

@akseg73 io_uring does provide this feature. Please take a look at `IORING_SETUP_SQ_AFF`.

IORING_SETUP_SQ_AFF

If this flag is specified, then the poll thread will be bound to the cpu set in the sq_thread_cpu field of the struct io_uring_params. This flag is only meaningful when IORING_SETUP_SQPOLL is specified.

Ref: https://manpages.debian.org/unstable/liburing-dev/io_uring_setup.2.en.html

**Comment by akseg73** [comment]
We will test it out. Simply enabling the SQPOLL together with 2000 idle time makes our product unusable. It severely degrades performance all around. 

Its also a bit confusing that if 2000 is only milliseconds then changing it to 10 should not have made much of a difference. But when we change it to 10 there is no performance problem with the product (off course this is when no actual i/o is going on).

The behavior just seems very strange and we don't have an explanation for it.

**Comment by akseg73** [comment]
Utilizing IORING_SETUP_SQ_AFF did not help, its likely because we are not using it right. We are noticing that simply enabling SQPOLL tanks the performance of our server. This would suggest that SQPOLL kicks of some threads which are taking up the CPU. We have to investigate what is really going on.  Any ideas how we should go about this.

How many threads are created by SQPOLL?

Additionally does IOPOLL do polling in an additional thread or the polling happens in the thread that is looking for cqe.

any help is greatly appreciated. If i am able to create a working example, i will also submit it for other users.
