### ISSUE TITLE
Running out of file descriptors when using SQPOLL

### ISSUE THREAD

**Issue by johalun** [axboe/liburing#408]
Hi
Kernel is Linux 5.11
`ulimit -n` is 32K.

My (multi-process) application runs fine without SQPOLL, handling thousands of concurrent connections, however, when I enable SQPOLL, some of the processes randomly run out of file descriptors. What could be the reason for this? 

Thanks!

**Comment by johalun** [comment]
This could be a bug my application (porting from epoll). Once I have fixed all bugs and got things working perfectly without SQPOLL I will revisit this.

**Comment by YoSTEALTH** [comment]
This might be silly thing to say but are you not closing `fd` once the task is done? `close(fd)` or `io_uring_prep_close(sqe, fd)`

**Comment by johalun** [comment]
The code is the same with or without SQPOLL. It could be the case that SQPOLL brings higher performance = more FDs open at any given time if close calls are delayed but IIRC that didn't seem to be the case. 
I will close this for now until I have time to revisit this.
