### ISSUE TITLE
Possible erroneous behavior when reusing SQEs

### ISSUE THREAD

**Issue by paxostv** [axboe/liburing#41]
I'm issuing an accept() SQE subsequently followed by a connect() SQE. The connect result is success, however the accept() returns with CQE status ENOTCONN. Ignoring the error, the connected socket is fine and can issue I/O.

I presume this has something to do with the asynchronous connect case. Running with linux kernel at e31736d9fae841e8a1612f263136454af10f476a (12/14).

**Comment by axboe** [comment]
Please include a test case, saves me so much time in debugging something like this. Thanks!

**Comment by paxostv** [comment]
Good call. As I started reducing the case, I realized this only occurs when multiple threads are in play (we synchronize submissions/consumes to the rings and avoid liburing for these parts), which exponentially increases the chance that it's a bug on our end. I'll continue to investigate and reopen if there's indeed an issue here.

**Comment by paxostv** [comment]
I was able to isolate the issue, however you will want to sanity check what the code we have here is valid.

We're encountering the issue when reusing an SQE. In the program below, SQE at offset `0` is used for both IO ring submissions, where io_uring_enter() is called after each use with a return code of `1` that suggests the SQE was consumed.

It is our understanding that the update to sq->ktail is what effectively prepares the index for SQE consumption, with the io_uring_enter for publishing. If there is a bug in our code, it'd likely be in submit_sqe(), which assumes index `0` is always going to be published.

This fails 100% for me. Please let me know if you're unable to reproduce.

```
#include <cassert>
#include <liburing.h>
#include <netdb.h>
#include <string.h>
#include <sys/socket.h>
#include <sys/types.h>
#include <syscall.h>
#include <unistd.h>

struct io_uring io_uring;

int sys_io_uring_enter(const int fd,
                       const unsigned to_submit,
                       const unsigned min_complete,
                       const unsigned flags,
                       sigset_t* const sig) {
  return static_cast<int>(syscall(__NR_io_uring_enter,
                                  fd, to_submit, min_complete, flags,
                                  sig, _NSIG / 8));
}

void submit_sqe() {
  io_uring_sq* const sq = &io_uring.sq;
  const unsigned tail = *sq->ktail;
  sq->array[tail & *sq->kring_mask] = 0;
  io_uring_smp_store_release(sq->ktail, tail + 1);

  const int ret = sys_io_uring_enter(io_uring.ring_fd, 1, 0, 0, nullptr);
  assert(ret == 1);
}

int main(int argc, char** argv) {
  {
    io_uring_params params;
    memset(&params, 0, sizeof(params));
    const int ret = io_uring_queue_init_params(1024, &io_uring, &params);
    assert(ret == 0);
    assert(params.features & IORING_FEAT_SUBMIT_STABLE);
  }

  addrinfo* addr_info_list = nullptr;

  {
    addrinfo hints;
    memset(&hints, 0, sizeof(hints));
    hints.ai_family = AF_UNSPEC;
    hints.ai_socktype = SOCK_STREAM;
    hints.ai_flags = AI_PASSIVE | AI_NUMERICSERV;

    const int ret = getaddrinfo(nullptr, "12345", &hints, &addr_info_list);
    assert(ret == 0);
  }

  addrinfo* addr_info = nullptr;
  for (addrinfo* ai = addr_info_list; ai; ai = ai->ai_next) {
    if (ai->ai_family == AF_INET || ai->ai_family == AF_INET6) {
      addr_info = ai;
      break;
    }
  }
  assert(addr_info);

  io_uring_sqe* const sqe = &io_uring.sq.sqes[0];

  int listen_fd = -1;

  {
    const int ret =
        socket(addr_info->ai_family, SOCK_STREAM, addr_info->ai_protocol);
    assert(ret >= 0);
    listen_fd = ret;

    int value = 1;
    setsockopt(listen_fd, SOL_SOCKET, SO_REUSEADDR, &value, sizeof(int));
    setsockopt(listen_fd, SOL_SOCKET, SO_REUSEPORT, &value, sizeof(int));
  }

  {
    const int ret = bind(listen_fd, addr_info->ai_addr, addr_info->ai_addrlen);
    assert(ret == 0);
  }

  {
    const int ret = listen(listen_fd, SOMAXCONN);
    assert(ret == 0);
  }

  {
    sockaddr sa;
    memset(&sa, 0, sizeof(sa));
    socklen_t sa_size = sizeof(sa);

    io_uring_prep_accept(sqe, listen_fd, &sa, &sa_size, 0);
    io_uring_sqe_set_data(sqe, reinterpret_cast<void*>(1));
    submit_sqe();
  }

  int connect_fd = -1;
  {
    const int ret =
        socket(addr_info->ai_family, SOCK_STREAM, addr_info->ai_protocol);
    assert(ret >= 0);
    connect_fd = ret;
  }

  io_uring_prep_connect(sqe,
                        connect_fd,
                        addr_info->ai_addr,
                        addr_info->ai_addrlen);
  io_uring_sqe_set_data(sqe, reinterpret_cast<void*>(2));
  submit_sqe();

  for (int i = 0; i < 2; ++i) {
    io_uring_cqe* cqe = nullptr;
    const int ret = io_uring_wait_cqe_timeout(&io_uring, &cqe, nullptr);
    assert(ret == 0);
    assert(cqe);
    assert(cqe->res >= 0);  // FAILS HERE

    io_uring_cq_advance(&io_uring, 1);
  }

  freeaddrinfo(addr_info_list);
  io_uring_queue_exit(&io_uring);
  return 0;
}
```

**Comment by axboe** [comment]
I just tried it, and I get -EISCONN, not -ENOTCONN here? That's errno 106, not 107. Can you confirm that you are indeed seeing -ENOTCONN (-107), and not -EISCON (-106) here?

**Comment by axboe** [comment]
I also see that on the connect request, not the accept.

**Comment by paxostv** [comment]
In this instance, yes, I'm also seeing EISCONN, which is why I changed the title to be more generic. However I'm receiving the error on the accept() (user data '1').

Note if I change the connect() to use SQE at index '1', and pass that in for the submit_sqe(), all is well and no error is encountered.

**Comment by axboe** [comment]
Ahhh, now I see! I think I see the bug.

**Comment by axboe** [comment]
```
diff --git a/fs/io_uring.c b/fs/io_uring.c
index 9240bc12ec1a..3f0cfadfc2c6 100644
--- a/fs/io_uring.c
+++ b/fs/io_uring.c
@@ -2559,11 +2559,18 @@ static int io_accept(struct io_kiocb *req, struct io_kiocb **nxt,
 
 	ret = __sys_accept4_file(req->file, file_flags, addr, addr_len, flags);
 	if (ret == -EAGAIN && force_nonblock) {
+		if (req->io)
+			return -EAGAIN;
+		if (io_alloc_async_ctx(req)) {
+			ret = -ENOMEM;
+			goto out;
+		}
 		req->work.flags |= IO_WQ_WORK_NEEDS_FILES;
 		return -EAGAIN;
 	}
 	if (ret == -ERESTARTSYS)
 		ret = -EINTR;
+out:
 	if (ret < 0)
 		req_set_fail_links(req);
 	io_cqring_add_event(req, ret);
```

**Comment by paxostv** [comment]
Great, appreciate the fix! Feel free to close if you believe it's resolved. I'll verify when it makes its way into the nightly builds.

**Comment by axboe** [comment]
Should be fixed, queued up:

https://git.kernel.dk/cgit/linux-block/commit/?h=io_uring-5.5&id=2b17d732e89ceeadedd69678e7a35b845430eab6

Closing here, thanks for reporting! Do report when you've tested as well, thanks.

**Comment by axboe** [comment]
Just a heads up that I came up with a better fix that does not need to allocate memory: https://git.kernel.dk/cgit/linux-block/commit/?h=io_uring-5.5&id=d4f5dc5a78840b3d19531bf181bd04484101aa4c

I also committed your test case and made it part of the liburing regression suite: https://git.kernel.dk/cgit/liburing/commit/?id=6827bf8cac6177c062171f3e35f50ab9ccde13de

**Comment by paxostv** [comment]
Verified - thank you!

**Comment by axboe** [comment]
Thanks for reporting, and re-testing!
