### ISSUE TITLE
Builds failing using musl libc

### ISSUE THREAD

**Issue by UmanShahzad** [axboe/liburing#422]
Recently started getting these errors when building:

```bash
$ make -C src/
make: Entering directory 'src'
     CC queue.ol
In file included from queue.c:14:
include/liburing.h:162:39: error: unknown type name ‘cpu_set_t’
  162 |                                 const cpu_set_t *mask);
      |                                       ^~~~~~~~~
make: *** [Makefile:45: queue.ol] Error 1
make: Leaving directory 'liburing/src'
```

It seems that `-D_GNU_SOURCE` isn't defined, and musl libc requires this before defining `cpu_set_t`.

This patch fixes it, but not 100% sure if this is the right way and if it covers cpp or not:

```diff
diff --git a/src/Makefile b/src/Makefile
index dfca826..0614f30 100644
--- a/src/Makefile
+++ b/src/Makefile
@@ -6,7 +6,7 @@ libdevdir ?= $(prefix)/lib
 CPPFLAGS ?=
 override CPPFLAGS += -Iinclude/ -include ../config-host.h
 CFLAGS ?= -g -fomit-frame-pointer -O2
-override CFLAGS += -Wall -Wextra -Wno-unused-parameter -Wno-sign-compare
+override CFLAGS += -D_GNU_SOURCE -Wall -Wextra -Wno-unused-parameter -Wno-sign-compare
 SO_CFLAGS=-fPIC $(CFLAGS)
 L_CFLAGS=$(CFLAGS)
 LINK_FLAGS=
```

**Comment by UmanShahzad** [comment]
I think an equivalent change would be needed in all the Makefiles in which CFLAGS is added to like this, i.e. examples/Makefile and test/Makefile.

**Comment by axboe** [comment]
We do set it in some spots, just not all. Care to submit a pull request for that?

**Comment by UmanShahzad** [comment]
Sure, made https://github.com/axboe/liburing/pull/423

**Comment by UmanShahzad** [comment]
(It builds properly now for me with musl libc with that patch)

**Comment by laf0rge** [comment]
I agree it is not a good idea for a system library to expose `#define _GNU_SOURCE` to each and every file / compile unit of each and every downastream project.  This is highly unusual, in my opinion.

It's of course fine for liburing to `#define` whatever it wants for compiling its own sourec code.  It's equally fine to have the `#define` in specific header files that might rely on importing stuff from libc that requires `_GNU_SOURCE`.  But putting it in in the Cflags of pkg-config is a bit over-reaching, IMHO
