### ISSUE TITLE
upgrading liburing from 2.0 to 2.1 is making my app compiled against 2.0 freeze

### ISSUE THREAD

**Issue by lano1106** [axboe/liburing#429]
Is 2.1 known to break binary compatibility?

I don't have more info about what is going on now...

Initial socket state is NONBLOCK.
I call connect() then poll the socket for POLLOUT with io_uring
As soon as the socket is reported as connected, I change the socket to blocking and start using with io_uring_prep_write() and io_uring_prep_recv() to perform async IO.

It works like a charm with 2.0. With 2.1, after connect is called, POLLOUT event appears to never be reported...

The first thing that I have tried was to recompile against 2.1. This didn't fix my freeze.

I had to rollback to 2.0 to fix my problem.

I am going to use this issue as a placeholder to add more info as I better understand what has broke with the new lib version...

**Comment by lano1106** [comment]
is there a small release notes of what 2.1 is adding over 2.0 beside the commit logs?

**Comment by axboe** [comment]
Since it seems easily reproducible, can you try and run a git bisect between 2.0 and 2.1? That's usually the first best step in figuring out what the issue might be.

**Comment by lano1106** [comment]
thx for quick reply. Yes that is a good idea. I'm not sure that I'll be able to look into it before monday but after the week-end, I will have some time to debug this...

**Comment by axboe** [comment]
Did you get a chance to run the bisect?

**Comment by lano1106** [comment]
no. I am going to look at it later today or tomorrow.

I had a nasty low-level bug in my custom io_uring libev lib that kept me busy tracking it since Sunday.

I have finally nailed that one this morning.

The next item on my todo list is to check for the liburing 2.1 upgrade issue. Stay tuned. I should figure out soon what is happening...

**Comment by axboe** [comment]
Sounds good, thanks!

**Comment by lano1106** [comment]
I have found the culprit of my issue. It is commit 0ea4ccd1c0e4 ("src/queue: don't flush SQ ring for new wait interface")

I am calling io_uring_wait_cqes() and IORING_FEAT_EXT_ARG is present. With 2.0, sq was flushed. With 2.1, it is not anymore.

What is the 2.1 way to flush sq when calling io_uring_wait_cqes()?

**Comment by axboe** [comment]
Kind of split on this one, it'd be nice not to have to do that implicit flush as it's really an artifact of the older interface _needing_ to do so since it submitted a new request internally. Hence I'd prefer to keep it as-is. For flush, I'd just use io_uring_submit(), that's the defined way to ensure pending requests are submitted before flushing. Would that work for you?

**Comment by lano1106** [comment]
I guess that explicitly calling io_uring_submit() would work before waiting for cqes would work well for my code.

That being said, it appears that calling io_uring_submit() does a little bit more than just flushing the sq. It does evaluate too if it needs to make a syscall. It doesn't appear to be much but considering that calling io_uring_wait_cqes() is in my application hot path, it might not be negligible.

In an ideal world, __io_uring_flush_sq() would be exposed to the API user. If that was the case, this is what I would choose to call

**Comment by axboe** [comment]
That's a good point, definitely don't want to add the cost of an extra system call since we're going to be waiting anyway. We're probably better off just reverting that commit. That also seems saner from a compatibility point of view. Agree?

**Comment by lano1106** [comment]
Jens,

from a compatibility point of view, this is saner. However, I think that the motivation behind this commit is legit. It has been done for multithreaded apps where cqe handling is done in a separate thread from the thread submitting the sqes.

maybe having 2 distinct functions or adding an extra parameter to differentiate the desired behavior would be the solution.

That being said, I did a small review of the code and I think that I have found something suspicious. In _io_uring_get_cqe(),

should

`if (data->submit) {
                        sq_ring_needs_enter(ring, &flags);
                        need_enter = true;
                }
`
not be

`if (data->submit && sq_ring_needs_enter(ring, &flags)) {
                        need_enter = true;
                }
`
instead?

**Comment by axboe** [comment]
I think the main issue here is mostly that doing submit from wait breaks the new guarantee that you can have separate threads do that, if you wish, without synchronization. So can't really just revert it either...

I think you're right on that check, should probably just make it:

```
need_enter = data->submit && sq_ring_needs_enter(ring, &flags);
```

**Comment by lano1106** [comment]
If you agree on the last point, I can create a pull request to fix this...

I think that it has to be as I proposed it to be because there is another conditional block that can set need_enter if the requested number of cqe is greater than the number of available cqe. That would be a bug to overwrite need_enter if set to true by the first condition.

Concerning the question to revert or not the commit... idk the best option. I was under the impression that reverting would be the outcome so I went ahead and I reverted it back in my private build.

I have kept thinking about the situation and I believe that if the API could offer 2 distinct functions to address both situations, it would be the best solution. On top of that, with all the nice building blocks already in place, it could be very trivial to do. The only difference would be whether or not get_date submit field is set or not by using __io_uring_flush_sq() return value.

**Comment by axboe** [comment]
See about 10 min ago, I did push out a fix for that mistake you found. It's referenced in here.

We do kind of have two variants of this - io_uring_wait_cqe() or io_uring_submit_and_wait(). The latter should work for you, as it'll flush the sq ring side too and submit if there's anything there. Perhaps that'd be a suitable replacement for your specific case?

**Comment by lano1106** [comment]
yes. I have seen your fix pass by.

Concerning your suggestion, I cannot use io_uring_submit_and_wait() because I pass a struct __kernel_timespec pointer to io_uring_wait_cqes().

I suspect that some API functions are there for legacy reasons for older kernels. If there was an io_uring_submit_and_wait() like function that I could pass a sigmask and a timestamp, that is the function that I would use.

**Comment by axboe** [comment]
Ah, maybe we should add a io_uring_submit_and_wait_timeout() for that purpose? Care to submit a PR for that?

**Comment by axboe** [comment]
BTW, then I plan on doing a 2.2 release fairly quickly after that. No point in not doing so.

**Comment by lano1106** [comment]
yes np. I will create a PR for that. BTW, you found an excellent name for the new function!

**Comment by axboe** [comment]
> BTW, you found an excellent name for the new function!

It's a bit long, but at least it's descriptive ;-)
