### ISSUE TITLE
question: are queue items processed in the order they are submitted ?

### ISSUE THREAD

**Issue by boxerab** [axboe/liburing#431]
Just curious: if I submit N file writes, are they guaranteed to be written to disk in the order that I submitted them in ?

**Comment by axboe** [comment]
They will be _issued_ in the order in which you submitted them, but there's no ordering guaranteed otherwise. The block layer or the drive itself is free to reorder them.

**Comment by boxerab** [comment]
excellent, thanks! And, thank you again for this incredible new API.
