### ISSUE TITLE
Question on documenation

### ISSUE THREAD

**Issue by zethra** [axboe/liburing#435]
In the `io_uring(7)` man page, it says IORING_OP_READ is equivalent to to `read(2)` but it seems to behave like `pread(2)` with the `-1` offset behavior of `preadv2(2)`. Additionally, it saids `res` will be what `read(2)` would return but IORING_OP_READ, as with all OPs, returns the negative error val on error whereas `read(2)` returns `-1` and set errno. Am I missing something here or are the docs incorrect?

**Comment by YoSTEALTH** [comment]
You could say `IORING_OP_READ` and `IORING_OP_READV` are "similar" to `read` and `preadv2` but they are not exactly the same! `io_uring` reads are better in many ways, you can find some info about it in this conversation  https://github.com/axboe/liburing/issues/280

**Comment by axboe** [comment]
That's correct, it's not meant as if it's exactly like read, it does indeed behave like a mix between pread2(2) with the -1 semantics of preadv2(2).

In terms of return value, cqe->res will either be a positive result in case of success, indicating the number of bytes read. Or if the request failed, it'll be the equivalant of -errno for the error value. For example, if a regular read(2) would have returned -1 with errno set to EINVAL, then cqe->res would be -EINVAL. This means that a negative value is an error, and a positive is success. errno cannot be used in an async environment, obviously.

I'll happily take a documentation update to make this easier to grok!

**Comment by axboe** [comment]
Or I can update it myself, if you tell me exactly what you were reading (where in what man page).

**Comment by axboe** [comment]
Found and improved it. I hope.

**Comment by zethra** [comment]
Awesome thanks!

**Comment by axboe** [comment]
Thanks for letting me know! First of all I don't always see those things as I'm so familiar with how it works, and secondly I don't re-read the documentation often. So always appreciate when someone brings up stuff that is confusing.
