### ISSUE TITLE
Consider supporting unvectored read/write?

### ISSUE THREAD

**Issue by withoutboats** [axboe/liburing#44]
io_uring currently only supports vectored reads and writes (except for the _fixed operations). While vectored reads and writes are in theory a superset of single reads and writes, the required indirection of the array of iovecs presents some problems.

In particular, I'm interested in creating a memory safe abstraction of io_uring's completion-based API in Rust. Realistically, the best way to do this is for the abstraction to have logical ownership of the buffers until the IO is complete. The naive solution would be to just always allocate an intermediate buffer, which would mean an extra allocation for every read or write operation. There are better solutions which avoid the allocation, but they can be tricky to implement.

It would be easier to create a safe API for unvectored read/write (the common case) if it were supported directly by the io_uring interface. Then the abstraction would only need to manage the lifetime of the actually buffer and not the indirection array as well.

**Comment by axboe** [comment]
Definitely, I can do that, should be only a few lines of code. Are you able to test based on development kernels? I can write this up tomorrow and push to my for-5.6/io_uring branch.

**Comment by axboe** [comment]
Literally a 5 minute job, I pushed it out:

https://git.kernel.dk/cgit/linux-block/commit/?h=for-5.6/io_uring&id=e307ca6464c7160fe34b8d9aca6e840aa63fd8fd

**Comment by withoutboats** [comment]
Looks good! I don't think I'll be able to test until after the new year but thanks :)

**Comment by CarterLi** [comment]
For 5.5, we already support [IORING_FEAT_SUBMIT_STABLE](https://lore.kernel.org/io-uring/20191203025444.29344-1-axboe@kernel.dk/T/#t), which means that you only need to make sure that iovecs are valid until the sqes are submitted.

I suggest that you should better reconsider the implementation strategy, because {send,recv}msg have the same problem.

**Comment by axboe** [comment]
That's easy enough to do if you already have the iovec, it's not trivial to do if you're doing async and can't put them on the stack. But yes, in general, any operation that needs to pass in data must have consistent data until the submit is done, that's a given.

**Comment by withoutboats** [comment]
Holding the iovecs until the submission is done would be an easier problem than until the completion is done, though again not having the layer of indirection makes the whole thing more straightforward.

Not clear on the implications of `IORING_FEAT_SUBMIT_STABLE`. Surely in every read/write the actual buffers behind the iovecs that reads are written into and writes are read out of need to be unmodified until the completion comes back or you'll have a data race with the kernel? Similar for any parameter to other ops that functions as an out pointer? What precisely does that feature guarantee is copied during submission?

**Comment by axboe** [comment]
It means that things like the iovec only need to be persistent for submit, not until completion. The io buffers themselves always need to be stable across completion. 

Arguably we should have had non vec reads and writes since the beginning. It’s extra work to copy the vec from the kernel side, and ditto on the user side unless you are already using iovecs. I don’t see a reason NOT to do this, we’re not adding any new code to handle this at all outside of wiring up the opcode. Additionally, async punt or non iovec opcodes don’t need any extra state to be stable.

**Comment by axboe** [comment]
I added fio support for the non-vectored commands and ran some verification workloads, works fine for me. Here's the fio support: https://git.kernel.dk/cgit/fio/commit/?id=b10b1e70afaff8c9b00005e9238f2ad347a9c00a

**Comment by axboe** [comment]
Considering this one closed/done.

**Comment by CarterLi** [comment]
What about recv/send? Will it be supported too?

**Comment by axboe** [comment]
Sure, that would be trivial too, it's just a wrapper around the sendmsg/recvmsg support with the msghdr on the stack (internally).

**Comment by axboe** [comment]
Like this, totally untested. Really needs someone to test it, even though it's pretty trivial.

```
diff --git a/fs/io_uring.c b/fs/io_uring.c
index 4ee53ad80110..00b5a0f126a7 100644
--- a/fs/io_uring.c
+++ b/fs/io_uring.c
@@ -376,8 +376,12 @@ struct io_connect {
 
 struct io_sr_msg {
 	struct file			*file;
-	struct user_msghdr __user	*msg;
+	union {
+		struct user_msghdr __user *msg;
+		void __user		*buf;
+	};
 	int				msg_flags;
+	size_t				len;
 };
 
 struct io_open {
@@ -667,6 +671,18 @@ static const struct io_op_def io_op_defs[IORING_OP_LAST] = {
 		.needs_file		= 1,
 		.unbound_nonreg_file	= 1,
 	},
+	{
+		/* IORING_OP_SEND */
+		.needs_mm		= 1,
+		.needs_file		= 1,
+		.unbound_nonreg_file	= 1,
+	},
+	{
+		/* IORING_OP_RECV */
+		.needs_mm		= 1,
+		.needs_file		= 1,
+		.unbound_nonreg_file	= 1,
+	},
 };
 
 static void io_wq_submit_work(struct io_wq_work **workptr);
@@ -2658,6 +2674,7 @@ static int io_sendmsg_prep(struct io_kiocb *req, const struct io_uring_sqe *sqe)
 
 	sr->msg_flags = READ_ONCE(sqe->msg_flags);
 	sr->msg = u64_to_user_ptr(READ_ONCE(sqe->addr));
+	sr->len = READ_ONCE(sqe->len);
 
 	if (!io)
 		return 0;
@@ -2739,6 +2756,56 @@ static int io_sendmsg(struct io_kiocb *req, struct io_kiocb **nxt,
 #endif
 }
 
+static int io_send(struct io_kiocb *req, struct io_kiocb **nxt,
+		   bool force_nonblock)
+{
+#if defined(CONFIG_NET)
+	struct socket *sock;
+	int ret;
+
+	if (unlikely(req->ctx->flags & IORING_SETUP_IOPOLL))
+		return -EINVAL;
+
+	sock = sock_from_file(req->file, &ret);
+	if (sock) {
+		struct io_sr_msg *sr = &req->sr_msg;
+		struct msghdr msg;
+		struct iovec iov;
+		unsigned flags;
+
+		ret = import_single_range(WRITE, (void __user *) sr->msg,
+						sr->len, &iov, &msg.msg_iter);
+		if (ret)
+			return ret;
+
+		msg.msg_name = NULL;
+		msg.msg_control = NULL;
+		msg.msg_controllen = 0;
+		msg.msg_namelen = 0;
+
+		flags = req->sr_msg.msg_flags;
+		if (flags & MSG_DONTWAIT)
+			req->flags |= REQ_F_NOWAIT;
+		else if (force_nonblock)
+			flags |= MSG_DONTWAIT;
+
+		ret = __sys_sendmsg_sock(sock, &msg, flags);
+		if (force_nonblock && ret == -EAGAIN)
+			return -EAGAIN;
+		if (ret == -ERESTARTSYS)
+			ret = -EINTR;
+	}
+
+	io_cqring_add_event(req, ret);
+	if (ret < 0)
+		req_set_fail_links(req);
+	io_put_req_find_next(req, nxt);
+	return 0;
+#else
+	return -EOPNOTSUPP;
+#endif
+}
+
 static int io_recvmsg_prep(struct io_kiocb *req,
 			   const struct io_uring_sqe *sqe)
 {
@@ -2831,6 +2898,59 @@ static int io_recvmsg(struct io_kiocb *req, struct io_kiocb **nxt,
 #endif
 }
 
+static int io_recv(struct io_kiocb *req, struct io_kiocb **nxt,
+		   bool force_nonblock)
+{
+#if defined(CONFIG_NET)
+	struct socket *sock;
+	int ret;
+
+	if (unlikely(req->ctx->flags & IORING_SETUP_IOPOLL))
+		return -EINVAL;
+
+	sock = sock_from_file(req->file, &ret);
+	if (sock) {
+		struct io_sr_msg *sr = &req->sr_msg;
+		struct msghdr msg;
+		struct iovec iov;
+		unsigned flags;
+
+		ret = import_single_range(READ, (void __user *) sr->msg,
+						sr->len, &iov, &msg.msg_iter);
+		if (ret)
+			return ret;
+
+		msg.msg_name = NULL;
+		msg.msg_control = NULL;
+		msg.msg_controllen = 0;
+		msg.msg_namelen = 0;
+		msg.msg_iocb = NULL;
+		msg.msg_flags = 0;
+
+		flags = req->sr_msg.msg_flags;
+		if (flags & MSG_DONTWAIT)
+			req->flags |= REQ_F_NOWAIT;
+		else if (force_nonblock)
+			flags |= MSG_DONTWAIT;
+
+		ret = __sys_recvmsg_sock(sock, &msg, NULL, NULL, flags);
+		if (force_nonblock && ret == -EAGAIN)
+			return -EAGAIN;
+		if (ret == -ERESTARTSYS)
+			ret = -EINTR;
+	}
+
+	io_cqring_add_event(req, ret);
+	if (ret < 0)
+		req_set_fail_links(req);
+	io_put_req_find_next(req, nxt);
+	return 0;
+#else
+	return -EOPNOTSUPP;
+#endif
+}
+
+
 static int io_accept_prep(struct io_kiocb *req, const struct io_uring_sqe *sqe)
 {
 #if defined(CONFIG_NET)
@@ -3670,9 +3790,11 @@ static int io_req_defer_prep(struct io_kiocb *req,
 		ret = io_prep_sfr(req, sqe);
 		break;
 	case IORING_OP_SENDMSG:
+	case IORING_OP_SEND:
 		ret = io_sendmsg_prep(req, sqe);
 		break;
 	case IORING_OP_RECVMSG:
+	case IORING_OP_RECV:
 		ret = io_recvmsg_prep(req, sqe);
 		break;
 	case IORING_OP_CONNECT:
@@ -3809,20 +3931,28 @@ static int io_issue_sqe(struct io_kiocb *req, const struct io_uring_sqe *sqe,
 		ret = io_sync_file_range(req, nxt, force_nonblock);
 		break;
 	case IORING_OP_SENDMSG:
+	case IORING_OP_SEND:
 		if (sqe) {
 			ret = io_sendmsg_prep(req, sqe);
 			if (ret < 0)
 				break;
 		}
-		ret = io_sendmsg(req, nxt, force_nonblock);
+		if (req->opcode == IORING_OP_SENDMSG)
+			ret = io_sendmsg(req, nxt, force_nonblock);
+		else
+			ret = io_send(req, nxt, force_nonblock);
 		break;
 	case IORING_OP_RECVMSG:
+	case IORING_OP_RECV:
 		if (sqe) {
 			ret = io_recvmsg_prep(req, sqe);
 			if (ret)
 				break;
 		}
-		ret = io_recvmsg(req, nxt, force_nonblock);
+		if (req->opcode == IORING_OP_RECVMSG)
+			ret = io_recvmsg(req, nxt, force_nonblock);
+		else
+			ret = io_recv(req, nxt, force_nonblock);
 		break;
 	case IORING_OP_TIMEOUT:
 		if (sqe) {
diff --git a/include/uapi/linux/io_uring.h b/include/uapi/linux/io_uring.h
index 03d2dde46152..1cfb1e6f8d3b 100644
--- a/include/uapi/linux/io_uring.h
+++ b/include/uapi/linux/io_uring.h
@@ -86,6 +86,8 @@ enum {
 	IORING_OP_STATX,
 	IORING_OP_READ,
 	IORING_OP_WRITE,
+	IORING_OP_SEND,
+	IORING_OP_RECV,
 
 	/* this goes last, obviously */
 	IORING_OP_LAST,
```

**Comment by CarterLi** [comment]
> Like this, totally untested. Really needs someone to test it, even though it's pretty trivial.
> 

Could you please commit the change first? I'll test it when I get a build.

**Comment by axboe** [comment]
It is committed:

https://git.kernel.dk/cgit/linux-block/commit/?h=for-5.6/io_uring&id=315bcd5392b2d7b2024e2b6681ce721296a8b1f0

I can't push it upstream before the 5.6 merge window opens, so this is far as it can go for now.

**Comment by CarterLi** [comment]
> It is committed:
> 
> https://git.kernel.dk/cgit/linux-block/commit/?h=for-5.6/io_uring&id=315bcd5392b2d7b2024e2b6681ce721296a8b1f0
> 
> I can't push it upstream before the 5.6 merge window opens, so this is far as it can go for now.

I mean committing changes of IORING_OP_SEND/RECV

**Comment by axboe** [comment]
Got it, I’ll get that committed.

**Comment by axboe** [comment]
Done: https://git.kernel.dk/cgit/linux-block/commit/?h=for-5.6/io_uring&id=c2c431f9d9854a17cd9cbc14ba1933ad293c05bc

**Comment by CarterLi** [comment]
> Done: [git.kernel.dk/cgit/linux-block/commit/?h=for-5.6/io_uring&id=c2c431f9d9854a17cd9cbc14ba1933ad293c05bc](https://git.kernel.dk/cgit/linux-block/commit/?h=for-5.6/io_uring&id=c2c431f9d9854a17cd9cbc14ba1933ad293c05bc)

Thanks
