### ISSUE TITLE
Missing io_uring_submit_and_wait_timeout() function in API

### ISSUE THREAD

**Issue by lano1106** [axboe/liburing#440]
before commit 0ea4ccd1c0e4 ("src/queue: don't flush SQ ring for new wait interface"),
io_uring_wait_cqes() was serving the purpose of submit sqe and wait for cqe up to a certain timeout value.

Since the commit, a new function is needed to fill this gap.

**Comment by isilence** [comment]
Related: https://github.com/axboe/liburing/issues/347

**Comment by axboe** [comment]
@lano1106 You were going to add this, correct? If not, I can do it.

**Comment by lano1106** [comment]
yes I can do it. You have more important things to take care of...

**Comment by axboe** [comment]
> You have more important things to take care of...

Feels like I need to take another look at the signal vs coredump issues...

**Comment by lano1106** [comment]
yes that but imho, this is not that urgent. It seems that I am the only one affected by the coredump issue and the fix is baked in my build (and my app isn't coredumping anymore!)...

I had in mind all the emails that I am seeing flying on the list plus the tasks required for the current dev cycle...

**Comment by axboe** [comment]
One thing is for sure, we won't run out of things to work on any time soon...

**Comment by axboe** [comment]
@lano1106 Did you make any progress on this one?

**Comment by lano1106** [comment]
I am done. I'm preparing the patch
