### ISSUE TITLE
Question: How can I close files which are opened with openat_direct / accept_direct?

### ISSUE THREAD

**Issue by CarterLi** [axboe/liburing#441]
Since IORING_IO_CLOSE doesn't support IOSQE_FIXED_FILE, I don't seem to be able to close the file. @isilence

**Comment by isilence** [comment]
> Since IORING_IO_CLOSE doesn't support IOSQE_FIXED_FILE, I don't seem to be able to close the file. @isilence

It's same as it was before, you can use  `IORING_OP_FILES_UPDATE` or `IORING_REGISTER_FILES_UPDATE`

note 1: I updated it a bit (kernel with the feature hasn't been released at that point), when you try those direct open/etc. and there is already a file in the slot, it will be replaced. So it's now consistent with behaviour of `IORING_OP_FILES_UPDATE`

note 2: as we did go this path, I think we just need to make `OP_CLOSE` to be able to remove fixed files, at least for consistency. I believe Jens mentioned it as well.

**Comment by axboe** [comment]
It's very counter-intuitive that CLOSE doesn't work on the direct descriptors, so I really think that should be added. Preferably for 5.15...

**Comment by CarterLi** [comment]
That's great! I'll leave this issue open until we add fixed_file support for IORING_OP_CLOSE.

**Comment by axboe** [comment]
This is now queued up and will be in 5.15:

https://git.kernel.dk/cgit/linux-block/commit/?h=io_uring-5.15&id=7df778be2f61e1a23002d1f2f5d6aaf702771eb8

**Comment by CarterLi** [comment]
Thanks
