### ISSUE TITLE
An option to use liburing without libc?

### ISSUE THREAD

**Issue by mrakh** [axboe/liburing#443]
There are a couple of issues with `liburing`'s `libc` dependency:

- `libc` implementations of things like `errno` and `malloc` pollute the code with global/thread-local state. This makes reentrancy impossible and relocations expensive.
- `libc` doesn't play nice with non-POSIX threading models, like green threads with small stack sizes, or direct use of the `clone()` system call. This makes interop with non-C languages/runtimes difficult.

One could use the raw syscall interface to `io_uring` to address these concerns, but that would be somewhat painful, so it would be nice for `liburing` to support this use case out of the box. Perhaps something like a `NOLIBC` macro could be added which, if defined, would patch out `libc` constructs and replace them with non-`libc` wrappers where applicable. A few API changes might be necessary for the non-`libc` case (e.g. `io_uring_get_probe`/`io_uring_free_probe`), but it shouldn't break existing applications as long as it's opt-in.

**Comment by YoSTEALTH** [comment]
As far as I know liburing has no dependency! That said I did notice liburing released by the OS distributors add `libc/glibc` as its dependency. You could just download liburing and compile it yourself.

**Comment by ammarfaizi2** [comment]
Sounds good, I actually have the same problem but never really brought it up here.

> A few API changes might be necessary for the non-`libc` case (e.g. `io_uring_get_probe`/`io_uring_free_probe`), but it shouldn't break existing applications as long as it's opt-in.

Perhaps we can use VM directly with `mmap()` / `munmap()` syscall to replace `malloc()` / `free()` for the no libc case. That shouldn't be too hard to be done. I would be happy to volunteer to bring this feature to liburing.

**Comment by ammarfaizi2** [comment]
> As far as I know liburing has no dependency! That said I did notice liburing released by the OS distributors add `libc/glibc` as its dependency. You could just download liburing and compile it yourself.

liburing *does* depend on libc, the use of `malloc()` / `free()`, `errno` are the examples of it.

**Comment by ammarfaizi2** [comment]
> > As far as I know liburing has no dependency! That said I did notice liburing released by the OS distributors add `libc/glibc` as its dependency. You could just download liburing and compile it yourself.
> 
> liburing _does_ depend on libc, the use of `malloc()` / `free()`, `errno` are the examples of it.

Here is the shared library `ldd` output.
```
ammarfaizi2@integral:~/project/now/liburing/src$ ldd liburing.so.2.1.0 
	linux-vdso.so.1 (0x00007ffea1fa0000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f45b3d24000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f45b3f30000)
```
I am sure we can safely ignore the `linux-vdso`. But to drop the `libc`, it needs to be reworked to use raw syscall directly, like invoking `__asm__`. I can start working on it for x86-64 arch, for other arch(s), I don't have the hardware to test.

**Comment by YoSTEALTH** [comment]
O, since the `*probe*` function `malloc/free`  was used. I do like the idea of using `mmap` vs `malloc`

**Comment by ammarfaizi2** [comment]
Found another libc dependency which the replacement is still unclear. I am not sure how to get the page size without `sysconf(3)`.

```c

ssize_t io_uring_mlock_size_params(unsigned entries, struct io_uring_params *p)
{
	// [...]
	// [...]
	// [...]
	// [...]

	page_size = sysconf(_SC_PAGESIZE);
	if (page_size < 0)
		page_size = 4096;

	return rings_size(entries, cq_entries, page_size);
}
```

**Comment by ammarfaizi2** [comment]
> * `libc` implementations of things like `errno` and `malloc` pollute the code with global/thread-local state. This makes reentrancy impossible and relocations expensive.

The replacement for the `errno` will be ugly. We will have something like this all over the place:
```c
		if (ret < 0) {
#ifdef LIBURING_NOLIBC
			err = ret;
#else
			err = -errno;
#endif
			break;
		}
```
 (I don't think this is the right design)

- Note that we are going to invoke syscall directly and don't use `errno` as error value.
- The syscall will return a negative value within range `-4095 .. -1` when error happens (that's the negative value of error code).

Any design idea to wrap it up?

**Comment by ammarfaizi2** [comment]
I am thinking of wrapping everything with kernel space return value style, the change might be massive, but we can have a better solution for it.

## For pointer return value 
```c
void *liburing_mmap(void *addr, size_t length, int prot, int flags,
		    int fd, off_t offset)
{	
#ifdef LIBURING_NOLIBC
	/*
	 * Assume __raw_mmap is the syscall written in ASM.
	 *
	 * The return value is directly taken from the syscall
	 * return value.
	 */
	return __raw_mmap(addr, length, prot, flags, fd, offset);
#else
	/*
	 * This is when libc exists.
	 */
	void *ret;

	ret = mmap(addr, length, prot, flags, fd, offset);
	if (ret == MAP_FAILED)
		ret = ERR_PTR(-errno);

	return ret;
#endif
}
```

## For integer return value
```c
int __sys_io_uring_register(int fd, unsigned opcode, const void *arg,
			    unsigned nr_args)
{
#ifdef LIBURING_NOLIBC
	/*
	 * Assume __raw_io_uring_register is the syscall written in ASM.
	 *
	 * The return value is directly taken from the syscall
	 * return value.
	 */
	return __raw_io_uring_register(addr, length, prot, flags, fd,
				       offset);
#else
	/*
	 * This is when libc exists.
	 */
	int ret;

	ret = syscall(__NR_io_uring_register, fd, opcode, arg, nr_args);
	if (ret < 0)
		ret = -errno;

	return ret;
#endif
}
```

**Comment by mrakh** [comment]
> Sounds good, I actually have the same problem but never really brought it up here.
> 
> > A few API changes might be necessary for the non-`libc` case (e.g. `io_uring_get_probe`/`io_uring_free_probe`), but it shouldn't break existing applications as long as it's opt-in.
> 
> Perhaps we can use VM directly with `mmap()` / `munmap()` syscall to replace `malloc()` / `free()` for the no libc case. That shouldn't be too hard to be done. I would be happy to volunteer to bring this feature to liburing.

I suppose that could work, although dedicating a whole page for a struct whose minimum size seems to be 24 bytes is wasteful. I was thinking of modifying the API so that the struct to fill in gets passed as an additional parameter, along with an inout capacity. Something like:

```
int io_uring_get_probe_ring(struct io_uring *ring, struct io_uring_probe *out, size_t *inout_size);
int io_uring_get_probe(struct io_uring_probe *out, size_t *inout_size);`
```

Then the user could allocate/deallocate the space however they want - whether through `alloca`, or `mmap`/`munmap` or whatever.

> Found another libc dependency which the replacement is still unclear. I am not sure how to get the page size without `sysconf(3)`.
> 
> ```c
> ssize_t io_uring_mlock_size_params(unsigned entries, struct io_uring_params *p)
> {
> 	// [...]
> 	// [...]
> 	// [...]
> 	// [...]
> 
> 	page_size = sysconf(_SC_PAGESIZE);
> 	if (page_size < 0)
> 		page_size = 4096;
> 
> 	return rings_size(entries, cq_entries, page_size);
> }
> ```

Looking at `musl`‘s implementation of this, it hardcodes this particular value, so I don’t see why we can’t.

> I am thinking of wrapping everything with kernel space return value style, the change might be massive, but we can have a better solution for it.
> 
> ## For pointer return value
> ```c
> void *liburing_mmap(void *addr, size_t length, int prot, int flags,
> 		    int fd, off_t offset)
> {	
> #ifdef LIBURING_NOLIBC
> 	/*
> 	 * Assume __raw_mmap is the syscall written in ASM.
> 	 *
> 	 * The return value is directly taken from the syscall
> 	 * return value.
> 	 */
> 	return __raw_mmap(addr, length, prot, flags, fd, offset);
> #else
> 	/*
> 	 * This is when libc exists.
> 	 */
> 	void *ret;
> 
> 	ret = mmap(addr, length, prot, flags, fd, offset);
> 	if (ret == MAP_FAILED)
> 		ret = ERR_PTR(-errno);
> 
> 	return ret;
> #endif
> }
> ```
> 
> ## For integer return value
> ```c
> int __sys_io_uring_register(int fd, unsigned opcode, const void *arg,
> 			    unsigned nr_args)
> {
> #ifdef LIBURING_NOLIBC
> 	/*
> 	 * Assume __raw_io_uring_register is the syscall written in ASM.
> 	 *
> 	 * The return value is directly taken from the syscall
> 	 * return value.
> 	 */
> 	return __raw_io_uring_register(addr, length, prot, flags, fd,
> 				       offset);
> #else
> 	/*
> 	 * This is when libc exists.
> 	 */
> 	int ret;
> 
> 	ret = syscall(__NR_io_uring_register, fd, opcode, arg, nr_args);
> 	if (ret < 0)
> 		ret = -errno;
> 
> 	return ret;
> #endif
> }
> ```

Yep, had something similar in mind.

**Comment by axboe** [comment]
I think wrapping it in a kernel style return value is the sanest option.

**Comment by ammarfaizi2** [comment]
> I suppose that could work, although dedicating a whole page for a struct whose minimum size seems to be 24 bytes is wasteful. I was thinking of modifying the API so that the struct to fill in gets passed as an additional parameter, along with an inout capacity. Something like:
> 
> ```c
> int io_uring_get_probe_ring(struct io_uring *ring, struct io_uring_probe *out, size_t *inout_size);
> int io_uring_get_probe(struct io_uring_probe *out, size_t *inout_size);`
> ```
> 
> Then the user could allocate/deallocate the space however they want - whether through `alloca`, or `mmap`/`munmap` or whatever.

We can't do that, that will break the userspace.

Plus I don't see the reason of why should we use `inout_size` here. The current API does not seem to have dynamic size for it. The size is constantly defined as
```c
len = sizeof(*probe) + 256 * sizeof(struct io_uring_probe_op);
```

The use of `malloc()` is probably to avoid large stack allocation or it is easy to get mess with variable-sized structure like this:
```c
struct io_uring_probe {
	__u8 last_op;	/* last opcode supported */
	__u8 ops_len;	/* length of ops[] array below */
	__u16 resv;
	__u32 resv2[3];
	struct io_uring_probe_op ops[];
};
```

The current API looks like this:
```c
struct io_uring_probe *io_uring_get_probe_ring(struct io_uring *ring)
{
	struct io_uring_probe *probe;
	size_t len;
	int r;

	len = sizeof(*probe) + 256 * sizeof(struct io_uring_probe_op);
	probe = malloc(len);
	if (!probe)
		return NULL;
	memset(probe, 0, len);

	r = io_uring_register_probe(ring, probe, 256);
	if (r >= 0)
		return probe;

	free(probe);
	return NULL;
}

struct io_uring_probe *io_uring_get_probe(void)
{
	struct io_uring ring;
	struct io_uring_probe *probe;
	int r;

	r = io_uring_queue_init(2, &ring, 0);
	if (r < 0)
		return NULL;

	probe = io_uring_get_probe_ring(&ring);
	io_uring_queue_exit(&ring);
	return probe;
}

void io_uring_free_probe(struct io_uring_probe *probe)
{
	free(probe);
}
```

I am not sure where `io_uring_free_probe()` is actually called. Do we use that?

**Comment by ammarfaizi2** [comment]
Ah, I just realized that there are tests that expect `__sys_io_uring_register()`, `__sys_io_uring_setup()` and `__sys_io_uring_enter()` to return -1 when error. This change will probably break user land too.

Is it acceptable? Any comment Jens?
Cc: @axboe

**Comment by ammarfaizi2** [comment]
Have just sent the RFC v1 here:
https://lore.kernel.org/io-uring/20210929101606.62822-1-ammar.faizi@students.amikom.ac.id/T/

**Comment by ammarfaizi2** [comment]
@mrakh I am going to post the v2 soon, can you help me to review and test?

If you can, please let me know your email, I will add you to CC list.

**Comment by ammarfaizi2** [comment]
Have just sent the RFC v2 here:
https://lore.kernel.org/io-uring/20211002012817.107517-1-ammar.faizi@students.amikom.ac.id/T/

**Comment by ammarfaizi2** [comment]
Have just sent the RFC v3 here (trivial change, remove duplicate Signed-off-by):
https://lore.kernel.org/io-uring/20211002014829.109096-1-ammar.faizi@students.amikom.ac.id/T/

**Comment by YoSTEALTH** [comment]
Naming like `liburing_mmap` seems odd to me, maybe `uring_mmap` or something a bit more clear as to what it is?

**Comment by ammarfaizi2** [comment]
> Naming like `liburing_mmap` seems odd to me, maybe `uring_mmap` or something a bit more clear as to what it is?

Agree with that, currently we have `uring_likely` and `uring_unlikely`. So it will be more compact and consistent style to have `uring_{mmap,munmap,madvise,{get,set}rlimit}`. Will address this for v4.

**Comment by ammarfaizi2** [comment]
> ```c
> void io_uring_free_probe(struct io_uring_probe *probe)
> {
> 	free(probe);
> }
>     
> ```
> I am not sure where `io_uring_free_probe()` is actually called. Do we use that?

Ah I see, looking at `test/probe.c`, we have this:
```c
static int test_probe_helper(struct io_uring *ring)
{
	struct io_uring_probe *p;

	p = io_uring_get_probe_ring(ring);
	if (!p) {
		fprintf(stderr, "Failed getting probe data\n");
		return 1;
	}

	if (verify_probe(p, 1)) {
		free(p);
		return 1;
	}

	return 0;
}
```
`io_uring_free_probe()` is the wrapper for that `free()` call. Should really use that in test.

**Comment by ammarfaizi2** [comment]
Have just sent the RFC v4 here, please review and comment!
https://lore.kernel.org/io-uring/20211003101750.156218-1-ammar.faizi@students.amikom.ac.id/T/

**Comment by ammarfaizi2** [comment]
Ahhh, wrong subject. It should have been
```
[PATCHSET v4 RFC liburing 0/3]
```
not
```
[PATCHSET v4 RFC liburing 0/4]
```
Sorry for that.

**Comment by ammarfaizi2** [comment]
Have just sent the v5 here:
https://lore.kernel.org/io-uring/20211003153428.369258-1-ammar.faizi@students.amikom.ac.id/T/

**Comment by ammarfaizi2** [comment]
Finally applied. I will start working on nolibc support, start from x86-64 arch. I will post my progress on this issue, stay tuned!

**Comment by ammarfaizi2** [comment]
> > Found another libc dependency which the replacement is still unclear. I am not sure how to get the page size without `sysconf(3)`.
> > ```c
> > ssize_t io_uring_mlock_size_params(unsigned entries, struct io_uring_params *p)
> > {
> > 	// [...]
> > 	// [...]
> > 	// [...]
> > 	// [...]
> > 
> > 	page_size = sysconf(_SC_PAGESIZE);
> > 	if (page_size < 0)
> > 		page_size = 4096;
> > 
> > 	return rings_size(entries, cq_entries, page_size);
> > }
> > ```
> 
> Looking at `musl`‘s implementation of this, it hardcodes this particular value, so I don’t see why we can’t.

Right, I have just taken a look at musl implementation, it hardcodes the page size per arch.

See here: https://github.com/ammarfaizi2/musl/search?q=%22%23define+PAGESIZE%22

**Comment by YoSTEALTH** [comment]
As long as its multiple of `512`, `4096` seems about right, also https://code.woboq.org/userspace/include/asm-generic/param.h.html#_M/EXEC_PAGESIZE

**Comment by ammarfaizi2** [comment]
I've never met a page size other than `4096` though. It's probably safe to assume it's always `4096`. In case we meet a special case, it will be a very simple change.

But of course, when we build with libc, we should rely on `sysconf(3)`. It's just for the no libc case.

**Comment by axboe** [comment]
Non-4k pages do very much exist (eg ppc), so don't make any assumptions on 4096 always being the page size or it definitely won't work on select architectures that don't use 4k pages.

**Comment by ammarfaizi2** [comment]
> Non-4k pages do very much exist (eg ppc), so don't make any assumptions on 4096 always being the page size or it definitely won't work on select architectures that don't use 4k pages.

Ah, TIL. My bad. I've just read this one https://wiki.debian.org/ArchitectureSpecificsMemo
They do exist and there are many of them.

**Comment by ammarfaizi2** [comment]
It's 10:00 PM. I have just submitted an RFC before bed. With subject: Add no libc support for x86-64 arch.

This RFC contains 6 patches. Go review and comment!
Link: https://lore.kernel.org/io-uring/20211006144911.1181674-1-ammar.faizi@students.amikom.ac.id/T/

**Comment by ammarfaizi2** [comment]
Finally we have support for nolibc x86-64. If anyone has any issue with these being applied, kindly to CC me.

Should we close this issue or leave it open until all architectures are supported?

**Comment by axboe** [comment]
Let's close it, all other archs will never happen! But now the framework is there to easily add others, I suspect that'll drip in as people need it.

**Comment by beef9999** [comment]
This option is really helpful

**Comment by beef9999** [comment]
@ammarfaizi2 
But someone added some `memset` in the latest master branch?

`relocation R_X86_64_PC32 against symbol `memset' can not be used when making a shared object; recompile with -fPIC`

**Comment by ammarfaizi2** [comment]
> @ammarfaizi2 But did someone add `memset` in the latest master branch?
> 
> `` relocation R_X86_64_PC32 against symbol `memset' can not be used when making a shared object; recompile with -fPIC ``

I did. We need a `memset()` out of the libc. Anyway, it works just fine from my end. How did you build it?

**Comment by beef9999** [comment]
> 

```
./configure --nolibc
make
```
Then I statically linked the liburing.a to my own project. The project's gcc version is 4.9.2, glibc version is 2.17.
Then the link would fail because of the error I mentioned above.

**Comment by ammarfaizi2** [comment]
Oh okay, `liburing.a` does not seem to be built with `-fPIC` here.

`liburing.a` is made of `*.ol` objects at this point:
```
ar r liburing.a setup.ol queue.ol register.ol nolibc.ol
ar: creating liburing.a
ranlib liburing.a
```

And we only build with `-fPIC` flag for `*.os` objects (that's for `liburing.so`, not `liburing.a`).
```
gcc -D_GNU_SOURCE -Iinclude/ -include ../config-host.h -nostdlib -nodefaultlibs -ffreestanding -fno-stack-protector -g -fomit-frame-pointer -O2 -Wall -Wextra -Wno-unused-parameter -Wno-sign-compare -nostdlib -nodefaultlibs -ffreestanding -fno-stack-protector -c -o setup.ol setup.c
gcc -D_GNU_SOURCE -Iinclude/ -include ../config-host.h -nostdlib -nodefaultlibs -ffreestanding -fno-stack-protector -g -fomit-frame-pointer -O2 -Wall -Wextra -Wno-unused-parameter -Wno-sign-compare -nostdlib -nodefaultlibs -ffreestanding -fno-stack-protector -c -o queue.ol queue.c
gcc -D_GNU_SOURCE -Iinclude/ -include ../config-host.h -nostdlib -nodefaultlibs -ffreestanding -fno-stack-protector -g -fomit-frame-pointer -O2 -Wall -Wextra -Wno-unused-parameter -Wno-sign-compare -nostdlib -nodefaultlibs -ffreestanding -fno-stack-protector -c -o register.ol register.c
gcc -D_GNU_SOURCE -Iinclude/ -include ../config-host.h -nostdlib -nodefaultlibs -ffreestanding -fno-stack-protector -g -fomit-frame-pointer -O2 -Wall -Wextra -Wno-unused-parameter -Wno-sign-compare -nostdlib -nodefaultlibs -ffreestanding -fno-stack-protector -c -o nolibc.ol nolibc.c
gcc -D_GNU_SOURCE -Iinclude/ -include ../config-host.h -nostdlib -nodefaultlibs -ffreestanding -fno-stack-protector -fPIC -g -fomit-frame-pointer -O2 -Wall -Wextra -Wno-unused-parameter -Wno-sign-compare -nostdlib -nodefaultlibs -ffreestanding -fno-stack-protector -c -o setup.os setup.c
gcc -D_GNU_SOURCE -Iinclude/ -include ../config-host.h -nostdlib -nodefaultlibs -ffreestanding -fno-stack-protector -fPIC -g -fomit-frame-pointer -O2 -Wall -Wextra -Wno-unused-parameter -Wno-sign-compare -nostdlib -nodefaultlibs -ffreestanding -fno-stack-protector -c -o queue.os queue.c
gcc -D_GNU_SOURCE -Iinclude/ -include ../config-host.h -nostdlib -nodefaultlibs -ffreestanding -fno-stack-protector -fPIC -g -fomit-frame-pointer -O2 -Wall -Wextra -Wno-unused-parameter -Wno-sign-compare -nostdlib -nodefaultlibs -ffreestanding -fno-stack-protector -c -o register.os register.c
gcc -D_GNU_SOURCE -Iinclude/ -include ../config-host.h -nostdlib -nodefaultlibs -ffreestanding -fno-stack-protector -fPIC -g -fomit-frame-pointer -O2 -Wall -Wextra -Wno-unused-parameter -Wno-sign-compare -nostdlib -nodefaultlibs -ffreestanding -fno-stack-protector -c -o nolibc.os nolibc.c
```

**Comment by ammarfaizi2** [comment]
The workaround for this would be always adding `-fpic -fPIC` flags for nolibc build.

Can you apply this diff and see whether it's a cure?
```diff
diff --git a/src/Makefile b/src/Makefile
index 09ff395..819ff61 100644
--- a/src/Makefile
+++ b/src/Makefile
@@ -36,9 +36,9 @@ liburing_srcs := setup.c queue.c register.c
 
 ifeq ($(CONFIG_NOLIBC),y)
        liburing_srcs += nolibc.c
-       override CFLAGS += -nostdlib -nodefaultlibs -ffreestanding -fno-stack-protector
-       override CPPFLAGS += -nostdlib -nodefaultlibs -ffreestanding -fno-stack-protector
-       override LINK_FLAGS += -nostdlib -nodefaultlibs
+       override CFLAGS += -fpic -fPIC -nostdlib -nodefaultlibs -ffreestanding -fno-stack-protector
+       override CPPFLAGS += -fpic -fPIC -nostdlib -nodefaultlibs -ffreestanding -fno-stack-protector
+       override LINK_FLAGS += -fpic -fPIC -nostdlib -nodefaultlibs
 else
        liburing_srcs += syscall.c
 endif
```

**Comment by ammarfaizi2** [comment]
Oops, tabs broken, try this diff (resend).
```diff
diff --git a/src/Makefile b/src/Makefile
index 09ff395..819ff61 100644
--- a/src/Makefile
+++ b/src/Makefile
@@ -36,9 +36,9 @@ liburing_srcs := setup.c queue.c register.c
 
 ifeq ($(CONFIG_NOLIBC),y)
 	liburing_srcs += nolibc.c
-	override CFLAGS += -nostdlib -nodefaultlibs -ffreestanding -fno-stack-protector
-	override CPPFLAGS += -nostdlib -nodefaultlibs -ffreestanding -fno-stack-protector
-	override LINK_FLAGS += -nostdlib -nodefaultlibs
+	override CFLAGS += -fpic -fPIC -nostdlib -nodefaultlibs -ffreestanding -fno-stack-protector
+	override CPPFLAGS += -fpic -fPIC -nostdlib -nodefaultlibs -ffreestanding -fno-stack-protector
+	override LINK_FLAGS += -fpic -fPIC -nostdlib -nodefaultlibs
 else
 	liburing_srcs += syscall.c
 endif
```

**Comment by beef9999** [comment]
@ammarfaizi2 It works.

BTW, what's the difference between .ol and .os ?  I'm only aware of .o object files.

**Comment by ammarfaizi2** [comment]
> @ammarfaizi2 It works.
> 
> BTW, what's the difference between .ol and .os ? I'm only aware of .o object files.

It's my first time to meet those extensions too. Only in liburing I see them.

But from the build script we know that `*.os` is to build `liburing.so`, and `*.ol` is to build `liburing.a`.

**Comment by beef9999** [comment]
Could you merge this patch above?

**Comment by ammarfaizi2** [comment]
> Could you merge this patch above?

Alright, I think it's fine to always use `-fpic` and `-fPIC` only for nolibc build. Will send a patch for that for review. I will add a `Reported-by` tag if you want, so please provide your name and email.

**Comment by beef9999** [comment]
@ammarfaizi2 
Name: beef9999
Email: beef9999@qq.com

**Comment by ammarfaizi2** [comment]
A name, not a username. We don't use stuff like that.
I assume it's the same as your GitHub account, is this fine?
```
Reported-by: Bob Chen <beef9999@qq.com>
```

**Comment by beef9999** [comment]
@ammarfaizi2 Sure

**Comment by jcelerier** [comment]
> I've never met a page size other than `4096` though. It's probably safe to assume it's always `4096`. In case we meet a special case, it will be a very simple change.
> 
> But of course, when we build with libc, we should rely on `sysconf(3)`. It's just for the no libc case.

Here is one: M1 / M2 / M3 macs (AArch64) use a 16kb page size and Linux distros are configured accordingly: https://discussion.fedoraproject.org/t/switch-to-the-kernel-16k-variant/87711

**Comment by axboe** [comment]
Not sure what that is replying too, don't see the original? But yes, non-4k pages aren't that uncommon. Typing on one such machine right now... Outside of arm64, ppc also has a variety of page sizes.
