### ISSUE TITLE
`int fd`

### ISSUE THREAD

**Issue by YoSTEALTH** [axboe/liburing#445]
Not sure why `int fd` vs `unsigned fd`

**Comment by ammarfaizi2** [comment]
Practically, file descriptor is stored as a signed integer. The appropriate data type for file descriptor is `int fd`. For the negative value, it indicates no value or simply invalid fd. In case `fd` as a return value, it can also be used to indicate error code.

A real world example for no value is `fds` array on syscall `poll(2)`. When we need to ignore the middle or front element, it can be filled with negative `fd`. This is the way to tell the kernel to ignore specific element in the `fds` array. So that we don't have to decrement the `nfds` and call `memmove()` on array to close the hole.

**Comment by YoSTEALTH** [comment]
I get that open `int open()` returns `-fd` for error. I meant for stuff after the open like `io_uring_prep_readv(..., int fd, ...)` <- this could be bit more strict with `unsigned fd`.

**Comment by ammarfaizi2** [comment]
> I get that open `int open()` returns `-fd` for error. I meant for stuff after the open like `io_uring_prep_readv(..., int fd, ...)` <- this could be bit more strict with `unsigned fd`.

There is no point to make it unsigned, the internal check for that has already been strict by returning `-EBADF` in case you supply invalid file descriptor.

Extra:
Even so, that will be some kind of inconsistency, plus I believe `[0, INT_MAX]` is enough to contain possible file descriptor. Another thing is, if you have `-Wsign-conversion` flag activated, you will need to cast from `int` to `unsigned int`, that adds more ugliness.

**Comment by YoSTEALTH** [comment]
Thanks @ammarfaizi2 your points are very valid.

I was thinking in terms of prevention

Say you have:
``` Python

    fd = open()                         # -1

    io_uring_prep_read(..., fd, ...)    # `cqe.res` error

    io_uring_prep_write(..., fd, ...)   # again `cqe.res` error

    io_uring_prep_close(..., fd)        # again `cqe.res` error
```
If `fd` isn't specifically checked after `open` or something goes wrong in the middle where `fd` was closed you would still keep passing `-1` into read, write, ... and those would go into `io_uring` event manager and return `cqe.res` errors.

So now you have to implement a check (or function) to see if `fd` is `closed/-1` before you call read, recv, write, ..., this is so much extra work and wasted resources, specially when it comes to socket fd where you have the highest chance of connection being closed in middle of an task!

Why deal with all the problems when you can just be a little strict and prevent problems from happening in the first place?

**Comment by axboe** [comment]
Some of this is traditions, and an ```fd``` is always signed in C and on the OS side. Mostly because you do:

```
fd = open(...);
if (fd < 0)
    error
```

and the equivalent action on the io_uring side when you assign ```fd``` from ```cqe->res``` of ```IORING_OP_OPEN```. If fd was unsigned, then that idiomatic model would not work anymore.

**Comment by YoSTEALTH** [comment]
@axboe Right! I wasn't really talking about `open` though, everything other then open. Also reading C doesn't have a try/exception block, maybe this is something I can implement within my software.

**Comment by ammarfaizi2** [comment]
> If `fd` isn't specifically checked after `open` or something goes wrong in the middle where `fd` was closed you would still keep passing `-1` into read, write, ... and those would go into `io_uring` event manager and return `cqe.res` errors.

Something went wrong with your app.

If `open()` returns `fd < 0`, you should never treat the return value as **a valid file descriptor**. Hence you should never call `io_uring_prep_{read,write,close}()` with `fd < 0`.

**Comment by ammarfaizi2** [comment]
> So now you have to implement a check (or function) to see if `fd` is `closed/-1` before you call read, recv, write, ..., this is so much extra work and wasted resources, specially when it comes to socket fd where you have the highest chance of connection being closed in middle of an task!

There is no such a thing, the kernel **cannot** magically change your stale fd to negative value when the connection gets closed. 

Consider the following situation:
1) You have a TCP server
2) Then `accept()` a client
3) Get a valid `fd`
4) The client associated with that `fd` close the connection.

After (4), the `fd` is still valid, every `read`/`write` will return 0. You will always have to call `close()` until the `fd` ref count is zero and every resource associated with it gets freed.

**Comment by axboe** [comment]
Closing this one up.

**Comment by YoSTEALTH** [comment]
Thanks @ammarfaizi2

Just to clarify, I don't work directly with C but through ffi's.

Also realized passing `-1` into `unsigned` gets converted to `4294967295` vs raising error. In ffi it does `OverflowError: can't convert negative value to unsigned int` I thought C did this as well! *my mistake*, but its the ffi providing such feature to prevent leaks.
