### ISSUE TITLE
Kernel header license

### ISSUE THREAD

**Issue by ammarfaizi2** [axboe/liburing#446]
On the liburing's README file, there is a license notice like this:
```
License
-------

All software contained within this repo is dual licensed LGPL and MIT, see
COPYING and LICENSE, except for a header coming from the kernel which is
dual licensed GPL with a Linux-syscall-note exception and MIT, see
COPYING.GPL and <https://spdx.org/licenses/Linux-syscall-note.html>.

Jens Axboe 2020-01-20
```

I am not sure whether what I did is legal, I am taking the kernel header file for this patch
https://lore.kernel.org/io-uring/20211002014829.109096-4-ammar.faizi@students.amikom.ac.id/
Please shed some light.

**Comment by axboe** [comment]
I'd avoid doing that, as that kernel header is GPL-2.0 only. We could go the rounds and dual-license it, but seems pointless for something this trivial where you can just write your own based on the same principles.

**Comment by ammarfaizi2** [comment]
Alright, will drop that and write my own. It's my stupidity dealing with license problem just for this trivial stuff. Thanks.
