### ISSUE TITLE
man: #include doesn't pull in a declaration of u32 or io_uring_setup()

### ISSUE THREAD

**Issue by allanwind** [axboe/liburing#447]
My initial minimal attempt:

```
#include <linux/io_uring.h>
#include <stdio.h>

int main() {
	u32 events = 10;
	struct io_uring_params params = { 0 };
	if(io_uring_setup(events, &params) == -1) {
		printf("error\n");
	}
}
```

fails on Debian 11 with:

```
$ gcc -Wall -Wextra 1.c 
1.c: In function ‘main’:
1.c:5:2: error: unknown type name ‘u32’
    5 |  u32 events = 10;
      |  ^~~
1.c:7:5: warning: implicit declaration of function ‘io_uring_setup’ [-Wimplicit-function-declaration]
    7 |  if(io_uring_setup(events, &params) == -1) {
      |     ^~~~~~~~~~~~~~
```

Is u32 a typo for __u32?  Should a user interface be documented using kernel types?  I.e. opposed to unsigned int, or stdint.h's uint32_t?   Then you figure out via a some desparate grep'ing... oh, it's different linux/io_uring.h so tried:

```
gcc -Wall -Wextra 1.c -I/usr/src/linux-headers-5.10.0-8-common/include
```

which fails on:

```
#include <asm/current.h>
```

and:

```
gcc -Wall -Wextra 1.c -I/usr/src/linux-headers-5.10.0-8-common/include -I/usr/src/linux-headers-5.10.0-8-common/arch/x86/include
```
fails on:

```
#include <asm/rwonce.h>
```
so adding anthother -I:
```
gcc -Wall -Wextra 1.c -I/usr/src/linux-headers-5.10.0-8-common/include -I/usr/src/linux-headers-5.10.0-8-common/arch/x86/include -I /usr/src/linux-headers-5.10.0-8-common/include -I /usr/src/linux-headers-5.10.0-8-amd64/arch/x86/include/generated
```
which fails with a wall of erros.

On Debian 11 that's the end of line as the only 3 man pages they ship are io_uring_enter, io_uring_register and io_uring_setup.  The examples in /usr/share/doc/liburing-dev/examples doesn't mention setup, so unless you read the pdf you wouldn't have a clue that you probably want io_uring_queue_init_params() instead.

Hope it helps.

**Comment by axboe** [comment]
You're mixing up kernel headers and liburing. All you need is liburing.h and liburing, it'll have what you need.  io_uring.h is the kernel API, things like ```struct io_uring_params``` and ```io_uring_setup()``` are liburing and are not tied to the kernel at all.

**Comment by allanwind** [comment]
Well, I was trying to show you that the path that someone new to io_uring would take on Debian due to total lack of useful man pages.  It's really rough.  The only thing that ships in Debian 11 for liburing are io_uring_enter(2), io_uring_register(2), and io_uring_setup(2), 4 examples in C and a header which are are all undocumented.  It's not so much me mixing anything as that is all the information is available.  I read the pdf you wrote, and I am working https://unixism.net/loti so I will figure it out, but those are external resources.  Also, cloned the repo to check out the additional the man pages particular io_uring_get_sqe.3, io_uring_queue_exit.3, io_uring_queue_init.3 which are essential to ship on Debian to be useful.  Anyways, I don't expect anything but this being closed but thought it would be helpful never the less.

**Comment by axboe** [comment]
I appreciate that, and unfortunately liburing does not have a good set of man pages. The kernel ones are decent and should be uptodate with the upstream kernels, but the liburing API really isn't. I'd love for that not to be the case, but there's just not enough time to get it done. At least there's a pretty good amount of resources on the web - yes, it's external, but I really don't see that as a big problem.

One day we'll have a full set of man pages for liburing, but it requires that someone writes them. So far, not much has happened there.
