### ISSUE TITLE
New operations lack man page entry.

### ISSUE THREAD

**Issue by yxhuvud** [axboe/liburing#45]
The operations defined in https://github.com/axboe/liburing/blob/master/src/include/liburing/io_uring.h#L81-L88 are missing man page descriptions: 
```

	IORING_OP_CONNECT,
	IORING_OP_FALLOCATE,
	IORING_OP_OPENAT,
	IORING_OP_CLOSE,
	IORING_OP_FILES_UPDATE,
	IORING_OP_STATX,
	IORING_OP_READ,
	IORING_OP_WRITE,

```

**Comment by axboe** [comment]
Yeah I know, I'll take patches... If not, I'll get to it in due time. There's not much to explain for new opcodes, the prep helper provided with liburing basically tells you all you need to know.
