### ISSUE TITLE
write/read single submit+wait

### ISSUE THREAD

**Issue by YoSTEALTH** [axboe/liburing#450]
Just to double check, can you not do write + read in a single submit+wait?:

``` Python
io_uring_prep_write(sqe, fd, b'hello world', 11, 0)
io_uring_prep_read(sqe, fd, read_buffer, len(read_buffer), 0)

io_uring_submit(ring)
io_uring_wait_cqe_nr(ring, cqes, 2)
# process cqe

# read buffer: bytearray(b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00')
```

**Comment by YoSTEALTH** [comment]
never mind, the read was finishing before the write!

**Comment by axboe** [comment]
Sure, that should work just fine. You can do submit 2 + wait for 2 in a single system call. But you are lacking ordering, which means your read could complete before your write. You'd need to mark the dependency here, for example link the read after the write.

**Comment by YoSTEALTH** [comment]
@axboe right, its flawless with `sqe.flags |= IOSQE_IO_LINK`. It was just tripping me up
