### ISSUE TITLE
Nolibc `malloc()` alignment

### ISSUE THREAD

**Issue by louvian** [axboe/liburing#454]
File src/nolibc.c
https://github.com/axboe/liburing/blob/471af33417242e51fff9517dc02b12269ad54613/src/nolibc.c#L20-L38

`user_p` may not be properly aligned as `sizeof(size_t)` may not always be 8 bytes. Just to be safe, can we guarantee the alignment? I think `malloc()` from libc does it.

Cc: @ammarfaizi2

**Comment by ammarfaizi2** [comment]
Oh right, I am preparing a patch to fix this.
