### ISSUE TITLE
Feature request: wait on socket readable / writeable

### ISSUE THREAD

**Issue by bgemmill** [axboe/liburing#457]
### Overview

Looking over the [io_uring operations](https://github.com/axboe/liburing/blob/master/src/include/liburing/io_uring.h#L107-L146), it doesn't look like there are any that can wait on the read and write readiness status of a socket.

If I've missed it and there are ops/flags that can allow triggering off status (and not read or write any data), please close this and point me in the right direction :smile:

### Background

During reading and writing, one thing that epoll can do that io_uring cannot is separate the readiness logic of a socket from the action on it.

While in most cases skipping the second system call is desirable, there are cases where integrating with other libraries and event loops requires handling the ready signal only.

For example, integrating with zeromq's event loop requires using [ZMQ_FD](http://api.zeromq.org/master:zmq-getsockopt#toc11), which says:
```
The returned file descriptor is intended for use with a poll or similar system call only. 
Applications must never attempt to read or write data to it directly, neither should they try to close it.
```

The use case is to wait until that socket becomes readable or writable, and then use zeromq's library functions to get data in and out. 

As another example, if one wants to write a replacement reactor for boost::asio to use io_uring instead of epoll, waiting on readiness is needed to implement [async_wait](https://www.boost.org/doc/libs/1_77_0/doc/html/boost_asio/reference/basic_socket/async_wait.html) or the older [null_buffers](https://www.boost.org/doc/libs/1_77_0/doc/html/boost_asio/reference/null_buffers.html).

**Comment by axboe** [comment]
IORING_OP_POLL_ADD should do what you need, it's a poll(2)/epoll(2) like operation.
