### ISSUE TITLE
Need some help to use liburing properly

### ISSUE THREAD

**Issue by cannium** [axboe/liburing#458]
I'm trying to write a benchmark test to see if liburing is helpful for my situation. I start 2 threads, one writer and one reaper thread. The writer thread is constantly submitting 4k sequential write operations to sq, and the reaper thread is constantly consuming results from cq. The test program is running on my laptop with an nvme SSD, with kernel `5.10.70-1-MANJARO`, but could only achieve very low bandwidth. The code is [here](https://gist.github.com/cannium/5e05174be002246f00bb4a63ac7178d4) and its output:
```
./uring E1
speed 217.441282MBps 
speed 10.808847MBps 
speed 0.137751MBps 
speed 0.177148MBps 
speed 86.678808MBps 
speed 19.653376MBps 
speed 0.496946MBps 
speed 0.556644MBps 
speed 0.443355MBps 
```
(`E1` is just a filename to write on)

I run `perf` against it and found `native_queued_spin_lock_slowpath` is dominating the CPU time.
```
Overhead  Command  Shared Object      Symbol
  97.33%  uring    [kernel.vmlinux]   [k] native_queued_spin_lock_slowpath
   0.87%  uring    [kernel.vmlinux]   [k] read_hpet
   0.20%  uring    [kernel.vmlinux]   [k] io_poll_remove_all
   0.08%  uring    [kernel.vmlinux]   [k] native_read_msr
   0.08%  uring    [kernel.vmlinux]   [k] native_write_msr
   0.06%  uring    [kernel.vmlinux]   [k] entry_SYSCALL_64
   0.05%  uring    [kernel.vmlinux]   [k] io_submit_sqes
   0.05%  uring    [kernel.vmlinux]   [k] _raw_spin_lock_irqsave
   0.05%  uring    [kernel.vmlinux]   [k] clear_page_rep
   0.04%  uring    [kernel.vmlinux]   [k] __fget_files
```
My first question would be where am I doing wrong here with the test program? It's basically copied and modified from https://github.com/axboe/liburing/blob/master/examples/io_uring-cp.c

Aside from the test program, my real-world application is to serve many small files backed with a large preallocated file(a very common practice for object store, like [haystack](https://engineering.fb.com/2009/04/30/core-data/needle-in-a-haystack-efficient-storage-of-billions-of-photos/)). I'd like to batch neighboring offset writes and send a single fsync, so when the fsync returns, I know all completed writes before the fsync is durable, for example, operations got from cq could be `Wa, Wb, Sa, Wc, Wd, Sb`, and when `Sa`(fsync a) is got, I know `Wa`(write a) and `Wb`(write b) is durable. I think io_uring is more suitable than aio in this situation, since aio requires direct IO,which requires a lot of padding. But I'm a newbie in io_uring so I'd appreciate it if someone could correct me when I'm wrong, both concept and program.

**Comment by isilence** [comment]
There were problems with native_queued_spin_lock_slowpath(), #215, and I can't find the mentioned there patch in stable 5.10. But to be sure we'd need a full stack trace to the place where spinlock is called. For instance, can you paste the file from

```sh
perf top --call-graph dwarf > output.txt
```

**Comment by cannium** [comment]
Thanks for your pointer. I ran again with `perf top --call-graph dwarf > output.txt` side-by-side, the perf output is [attached here](https://gist.github.com/cannium/af04b4adcaba986ce57a581cac44ae0e), and my test program result is:
```
./uring E1
speed 1318.714653MBps 
speed 301.856522MBps 
speed 0.466832MBps 
speed 0.480453MBps 
speed 919.455850MBps 
speed 825.752189MBps 
speed 693.301921MBps 
speed 356.511826MBps 
speed 118.222000MBps 
speed 2.121058MBps 
speed 0.506143MBps
speed 0.505581MBps
```

Also I upgraded my kernel to `5.14.10-1-MANJARO`, the results seems to be normal now:
```
./uring E1
speed 1673.851178MBps 
speed 1586.680630MBps 
speed 989.122459MBps 
speed 943.148632MBps 
speed 786.299756MBps 
speed 1020.729745MBps 
speed 861.746499MBps 
speed 854.539721MBps 
speed 845.481454MBps 
speed 855.183543MBps 
speed 832.169761MBps 
```

**Comment by isilence** [comment]
@cannium, how does the new numbers compare to the theoretical bandwidth of the drive?

**Comment by isilence** [comment]
> > Was the perf top done with 5.14? I only see 26% instead of 99+ in spinlocking.
> 
> The perf top was running on the old kernel. Previously I ran `perf record <test program> -g` and then `perf report --call-graph` reported the 97% `native_queued_spin_lock_slowpath`. This time I ran `perf top --call-graph dwarf > output.txt` side-by-side with the test program running in another shell.

Got it, `-g`. Not sure whether those patches around the spinlocking issue will be ever be ported to 5.10, but it sounds the problem is solved for you and we can close the issue.

**Comment by cannium** [comment]
Not thoroughly, but yes this issue could be closed, I'll open new ones if needed.
