### ISSUE TITLE
ucontext-cp example core dump - double free or corruption (!prev)

### ISSUE THREAD

**Issue by beef9999** [axboe/liburing#459]
CentOS Linux release 8.4.2105
gcc version 8.4.1
Master branch

https://github.com/axboe/liburing/blob/ddf26640e73064f31e561c57063189d8850632d8/examples/ucontext-cp.c#L181

**Comment by ammarfaizi2** [comment]
> @ammarfaizi2 Which debugging software were you using?

GDB
