### ISSUE TITLE
forgotten flags argument for IORING_OP_WRITEV ?

### ISSUE THREAD

**Issue by romange** [axboe/liburing#461]
Man page says that IORING_OP_WRITEV  reflects pwritev2(2). However, this call has `flags` argument that is omitted by the `io_uring_prep_writev`  function in liburing.h. Is it intentional?

**Comment by axboe** [comment]
Hmmm yes, that should have been in the helper for that. You can just set sqe->rw_flags after calling the prep helper, that's where those flags go.
