### ISSUE TITLE
provide observability on how kernel handles io_uring request

### ISSUE THREAD

**Issue by romange** [axboe/liburing#467]
io_uring decides internally on whether to punt a submission or to execute it inline. 
It can be helpful to know how the submission was handled so that app developers could optimize their code and production environment. I am guessing that punted requests use more CPU than those executed inline.

I suggest adding a flag to `cqe->flags` mask that would indicate that the corresponding submission was handled asynchronously.

P.S. if there are additional tools/techniques on how to monitor kernel for io_uring events, I am sure there are folks that would appreciate if someone from io_uring team would publish a short how-to guide or tutorial.

**Comment by isilence** [comment]
One case when one may want to add IOSQE_ASYNC is when requests were not punted (executed inline) but it took too much time, e.g. memcpy. IOW, io_uring_enter() syscall takes too much time because some of inline execution is heavy. This one won't be covered by this approach, another though for which it may be useful is when inline execution of your request almost never completes inline and punted anyway.

`cqe->flags` will be expensive (propagation, just taking the field) and I'd prefer some other way. As it's optimisation, would perf tracing do it for you? There is a trace point for that `trace_io_uring_queue_async_work()`

**Comment by romange** [comment]
Yes definitely. Do you have maybe some links to how-to guide (or any other
resources that can help) on how to use perf tracing with kernel?

Off topic - i saw you guys had major improvements with disk io and iouring.
Congrats! Will it by any chance improve networking performance as well or
its completely different path?

**Comment by isilence** [comment]
> Yes definitely. Do you have maybe some links to how-to guide (or any other resources that can help) on how to use perf tracing with kernel?

Yes, sure, I'll send some links and examples here later today.

> Off topic - i saw you guys had major improvements with disk io and iouring. Congrats! Will it by any chance improve networking performance as well or its completely different path?

Thanks! Network is definitely in near plans. And there are guys putting some work in polling and worker pools, all that should be pretty useful for net as well (even if you don't use `IORING_OP_POLL_ADD`).

**Comment by isilence** [comment]
You can get the list of traces as `grep "io_uring:" /sys/kernel/debug/tracing/available_events`
You can find some info about them at `<kernel>/include/trace/events/io_uring.h`,
e.g. https://elixir.bootlin.com/linux/latest/source/include/trace/events/io_uring.h

I was thinking about `io_uring:io_uring_queue_async_work` in particular:
```sh
// trace an app and write it into ./perf.data
perf record -e "io_uring:io_uring_queue_async_work" -- ./app_to_trace
// or same but with PID
perf record -e "io_uring:io_uring_queue_async_work" -p <pid>
// you look through the trace can view it in several ways, e.g.
perf script -i perf.data
``` 

However, if you open the link and find `io_uring_queue_async_work`, there is no opcode and user_data fields, so it's not very convenient. There is only req, which is a raw ptr and can be used together with other trace points to figure all the info out, but we reuse memory for requests, it may need some parsing. FWIW, `perf record` can track multiple trace points

```sh
// trace all io_uring events
perf record -e "io_uring:*" -- ./app_to_trace
// two specific events
sudo perf record -e "io_uring:io_uring_queue_async_work" -e "io_uring:io_uring_link" -- ./app
```

I think we just need to add ->user_data and probably ->opcode fields to all relevant trace points.

**Comment by isilence** [comment]
I guess it should cover it, but there is a lot written on perf, and it's not only about static trace points.
https://www.brendangregg.com/perf.html

There are also other tools using same stuff under the hood, e.g. I find bpftrace pretty convenient for many purposes, adds some in-kernel programmability.
https://github.com/iovisor/bpftrace/blob/master/docs/tutorial_one_liners.md

**Comment by romange** [comment]
Thanks Pavel, this is very  helpful!
