### ISSUE TITLE
Network socket read/readv support with IOPOLL

### ISSUE THREAD

**Issue by mayur-who** [axboe/liburing#470]
I have a SCTP server with SQPOLL configured and it works just fine but when I add IORING_SETUP_IOPOLL to the flags, my reads start failing with ENOTSUP. I have separate ring configured for accept calls,

So my question is, is IORING_SETUP_IOPOLL not supported on socket stream reads and writes?

**Comment by HowHsu** [comment]
> I have a SCTP server with SQPOLL configured and it works just fine but when I add IORING_SETUP_IOPOLL to the flags, my reads start failing with ENOTSUP. I have separate ring configured for accept calls,
> 
> So my question is, is IORING_SETUP_IOPOLL not supported on socket stream reads and writes?

Hi there,
AFAIK, iopoll is only for disk IO, especially for high speed block device like nvme. The aim of iopoll is to reduce latency by interruption and context switch when we read/write small piece of IO. In such cases, we
know the IO request will be done soon, so leverage cpu resource to positively ask the device if the request is done.

**Comment by mayur-who** [comment]
Hey, Thanks for the quick reply. 

I am using another ring with IOPOLL and SQPOLL for file IO. We are using spdk's reactor framework and were planning to reduce context switches and system calls as much as possible and possibility of using IOPOLL on network sockets would have helped here. I don't have a performance number as of now but Network layer would be our bottleneck in this scenario then.

**Comment by axboe** [comment]
It's on the todo to add polling support for sockets, it just hasn't been done yet.

**Comment by mayur-who** [comment]
Thanks.
