### ISSUE TITLE
cqe flags

### ISSUE THREAD

**Issue by YoSTEALTH** [axboe/liburing#471]
What exactly does `cqe->flags` do and how to properly handle it? I am getting `flags=3` and `user_data=4294967296` which I didn't assign.

**Comment by isilence** [comment]
flags should be zero apart from a couple of cases, iirc only selected buffers and multi-shot poll for now. There is a good chance there is a userspace error. Do you have a reproducer? Is it reproduced easily?

**Comment by YoSTEALTH** [comment]
Playing around with wrapping with Cython. I might be not be handling something correctly! Which is weird since normal test works fine, its when I benchmark with thousands of connection that error occurs and software stops responding.

> The flags is used for certain commands, like IORING_OP_POLL_ADD or in conjunction with IOSQE_BUFFER_SELECT , see those entries."

I am not using any of those features either.

test run - 1
```
sqe.user_data: 2048 <cyfunction io_uring_prep_close at 0x7f294b0d2b50>
sqe.user_data: 2049 <cyfunction io_uring_prep_recv at 0x7f294b0d0fb0>
sqe.user_data: 2050 <cyfunction io_uring_prep_accept at 0x7f294b0d0e10>
ready: 4
cqe res, flag, user_data: 0 0 2048
cqe res, flag, user_data: 161 0 2049
sqe.user_data: 2051 <cyfunction io_uring_prep_send at 0x7f294b0d1080>
cqe res, flag, user_data: 2 3 4294967296
cqe res, flag, user_data: 6 7 21474836484
ready: 1
cqe res, flag, user_data: 232 0 2051
sqe.user_data: 2052 <cyfunction io_uring_prep_close at 0x7f294b0d2b50>
ready: 1
cqe res, flag, user_data: 0 0 2052
```
test run - 2
```
sqe.user_data: 2048 <cyfunction io_uring_prep_close at 0x7f3d7128ab50>
sqe.user_data: 2049 <cyfunction io_uring_prep_recv at 0x7f3d71288fb0>
sqe.user_data: 2050 <cyfunction io_uring_prep_accept at 0x7f3d71288e10>
ready: 5
cqe res, flag, user_data: 0 0 2046
cqe res, flag, user_data: 0 0 2048
cqe res, flag, user_data: 161 0 2049
sqe.user_data: 2051 <cyfunction io_uring_prep_send at 0x7f3d71289080>
cqe res, flag, user_data: 2 3 4294967296
cqe res, flag, user_data: 6 7 21474836484
ready: 1
cqe res, flag, user_data: 232 0 2051
sqe.user_data: 2052 <cyfunction io_uring_prep_close at 0x7f3d7128ab50>
ready: 1
cqe res, flag, user_data: 0 0 2052
```
Looks like `2050` is `io_uring_prep_accept` is where this happens. I have run accept with `io_uring_prep_accept(sock_fd, NULL, NULL, 0)` and `io_uring_prep_accept(sock_fd, client_add, len(client_add), 0)`

Its also using `IOSQE_ASYNC` flag and `Linux 5.14.10-1`

**Comment by ammarfaizi2** [comment]
> Playing around with wrapping with Cython. I might be not be handling something correctly! Which is weird since normal test works fine, its when I benchmark with thousands of connection that error occurs and software stops responding.

Can you provide a simple minimal working code to reproduce this? I believe no one can tell what's wrong with your current story.

**Comment by YoSTEALTH** [comment]
@ammarfaizi2  I can't atm. Since I am doing this in Cython+Python, it will take bunch of installs, compiles and what not...

Its more to do with why am I getting those flags errors even though I am not using those features!

**Comment by ammarfaizi2** [comment]
> @ammarfaizi2 I can't atm. Since I am doing this in Cython+Python, it will take bunch of installs, compiles and what not...
> 
> Its more to do with why am I getting those flags errors even though I am not using those features!

We can't be sure whether:
- It's a userspace mistake (your Python app)
- a liburing bug
- or even a kernel bug

Mainly because we don't have enough information! Your app output doesn't make any sense to the readers. You need to help us to help you.

First, you need to rephrase your story, write step-by-step how to reproduce it. Start from setting up io_uring, taking SQE, submitting, reaping CQE, etc. until you find this bug. 

Try reproducing the problem yourself, in a fresh environment and make sure you can do so using only the information included in your issue. Add any relevant details you missed. Can you do that?

Or, if you can simplify your app, try to write a simple reproducer in C with minimal liburing setup, so it's easier for us to run it on our machine.
