### ISSUE TITLE
`wq_fd` field of `struct io_uring_params` is missing in man page

### ISSUE THREAD

**Issue by GalaxySnail** [axboe/liburing#473]
a very simple patch ;-)

```diff
diff --git a/man/io_uring_setup.2 b/man/io_uring_setup.2
index 88ce1f9..d527a6a 100644
--- a/man/io_uring_setup.2
+++ b/man/io_uring_setup.2
@@ -37,7 +37,8 @@ struct io_uring_params {
     __u32 sq_thread_cpu;
     __u32 sq_thread_idle;
     __u32 features;
-    __u32 resv[4];
+    __u32 wq_fd;
+    __u32 resv[3];
     struct io_sqring_offsets sq_off;
     struct io_cqring_offsets cq_off;
 };
```

**Comment by axboe** [comment]
Do you want to do a real pull request for this change? If yes, please note the general format of git commits in the repository, and include a Signed-off-by line with your real name and email.

Or if you prefer me to apply it manually, I can do so too. Just let me know.

**Comment by GalaxySnail** [comment]
Yes, thank you for guidance. I'm new to contribution, but after searching I can have a try now.
