### ISSUE TITLE
Renaming this feature.

### ISSUE THREAD

**Issue by marcfielding1** [axboe/liburing#481]
Can I just point out I've google urine about 100 times in my last sprint, now everyone's gotta pee, but really?

**Comment by axboe** [comment]
Grow up

**Comment by marcfielding1** [comment]
No seriously, have you tried googling autosuggest for this?

**Comment by marcfielding1** [comment]
Common cheer up, it's kinda funny and it really does autosuggest it if you're concentrating.

**Comment by marcfielding1** [comment]
I mean this is a great feature, but axboe !== urine - just saying.

**Comment by marcfielding1** [comment]
FYI I've now diverted accidental autocorrect searches to this repo for innocent developers who just wanted faster IO.

**Comment by axboe** [comment]
If I google liburing or io_uring, google doesn't suggest anything else and there's no auto suggest that's different. 

The name isn't being changed, sorry.

**Comment by marcfielding1** [comment]
It's not that exact search one sec, I'm actually being a div here.

**Comment by marcfielding1** [comment]
So it's where you don't use the _ and do io urin and hit enter, common mate it's a joke really, but there's literally 3 of us that keep hitting urine. It was meant to be funny not insult you.

**Comment by axboe** [comment]
I'll refrain from making the logo red, at least.

**Comment by marcfielding1** [comment]
If you've got red urine we've got bigger problems than naming conventions!

**Comment by marcfielding1** [comment]
Seriously though this feature is awesome, thanks a lot, wasn't trying to offend you, plus when google indexes this I can get the result I mistyped :-)
