### ISSUE TITLE
A possible data race in the variable td

### ISSUE THREAD

**Issue by ryancaicse** [axboe/liburing#482]
For the variable 
https://github.com/axboe/liburing/blob/469b5e80ce42be53ec748ddea8523a3c16ea5465/test/poll-v-poll.c#L92

There are two threads, running iou_poll and poll_pipe, respectively
```
	pthread_create(&threads[1], NULL, iou_poll, &td);
	pthread_create(&threads[0], NULL, poll_pipe, &td);
```

In the method `iou_poll`
```
	td->out[0] = cqe->res & 0x3f; // race
	io_uring_cqe_seen(td->ring, cqe);
	return NULL;
```

In the method `poll_pipe`
```
	ret = poll(&pfd, 1, -1);
	if (ret < 0)
		perror("poll");

	td->out[1] = pfd.revents; //race
```

Or it is a benign race?

**Comment by axboe** [comment]
You're not even describing what the race is, what do you think it is

**Comment by ryancaicse** [comment]
Thank you for your time.
It seems my detector is imprecise for handling arrays.
