### ISSUE TITLE
[Question] How do I know which liburing version I should use? (for old kernel)

### ISSUE THREAD

**Issue by beef9999** [axboe/liburing#483]
Suppose I'm using a relatively old kernel.

The latest liburing seems not to be compatible with the old kernel headers, so the errors would be like:

`liburing.h:342:7: error: ‘struct io_uring_sqe’ has no member named ‘rw_flags’`

Which liburing version should I downgrade to?

**Comment by CarterLi** [comment]
You should always use the latest liburing version.

> The latest liburing seems not to be compatible with the old kernel headers, so the errors would be like:
> 
> liburing.h:342:7: error: ‘struct io_uring_sqe’ has no member named ‘rw_flags’

Build errors have nothing to do with kernel. You can build liburing even if the kernel doesn't support io_uring at all. But you will get -ENOSYS when running tests.

**Comment by axboe** [comment]
Nor does liburing use the kernel io_uring.h header, it ships its own. In terms of rw_flags, that's been there since the initial release, so I suspect you have something else going on in your system or have modified headers.
