### ISSUE TITLE
[Question] How to get the errno when using io_uring_for_each_cqe ?

### ISSUE THREAD

**Issue by beef9999** [axboe/liburing#485]
Hi folks, I was using liburing + eventfd.

The documents only specified the return value of -errno on some of the APIs, for example, io_uring_peek_cqe and io_uring_wait_cqe.

But in terms of `io_uring_for_each_cqe`, how am I supposed to get the errno? Shall I use the `cqe->res` directly? That part is missing from the documents.

```C++
while (true) {
    // poll eventfd readable
    // read eventfd
    io_uring_for_each_cqe(ring, head, cqe) {
            // How to get the errno here ??
            io_uring_cqe_seen(ring, cqe);
    }
}
```

**Comment by axboe** [comment]
It's always cqe->res, that's the only way that io_uring can pass back per-request completion results. Doesn't matter what API you use to iterate or get a cqe, cqe->res is the result for that cqe.
