### ISSUE TITLE
FEAT_FAST_POLL explanation

### ISSUE THREAD

**Issue by godzie44** [axboe/liburing#487]
I try to create a high throughput server, based on pool of io_uring instances. At some point, I realized that I need a better understanding of work io_uring with FEAT_FAST_POLL. I'm using perf and trying to read sources, but in fact that I'm a kernel newbie, so I don’t trust too much what I found out.

Would be great if some one validate my research, or maybe explain this mechanism (for example i try to call recv on socket):

1. Call io_uring_enter for submitting recv op
2. io_uring try to call nonblock recv:
2.1 if nonblock recv call successfull -> commit cqe
2.2 if result of nonblock recv is EAGAIN then try to poll events defined in io_op_defs. Go to io_uring_poll_arm and call vfs_poll:
2.2.1 if we immediately poll needed events we recreate sqe and submit cqe at next io_queue_sqes call
2.2.1 otherwise we put some poll-work at wait_queue, wait_queue handles by io_wq worker pool (at one of io_wqe_worker-x threads), and when we successfully poll events - we commit cqe.

Thanks!

**Comment by axboe** [comment]
It's correct up until that last one, which isn't:

> 2.2.1 otherwise we put some poll-work at wait_queue, wait_queue handles by io_wq worker pool (at one of io_wqe_worker-x threads), and when we successfully poll events - we commit cqe.

wait_queue is indeed armed, and when the event triggers, that issues the callback that will retry the operation. However, that is not handled by io-wq, it's handled by the original task itself, similar to how signals are processed. io-wq can come into play. That happens if we trigger this callback and the retry yet again gets -EAGAIN, we currently do not retry with the poll callback at that point. Instead the poll is not rearmed and the request is handed to io-wq.

That last part should be improved so we just retry with poll. Generally it shouldn't be a common occurrence, however.

**Comment by godzie44** [comment]
Thanks! I.e. poll event handler is set on the thread that called io_uring_enter?

**Comment by axboe** [comment]
The poll handler runs directly from the context that triggers the event being "waited" on, and that callback handler in terms queues a task_work item with the task that called io_uring_enter to submit the original request.

**Comment by HowHsu** [comment]
> It's correct up until that last one, which isn't:
> 
> > 2.2.1 otherwise we put some poll-work at wait_queue, wait_queue handles by io_wq worker pool (at one of io_wqe_worker-x threads), and when we successfully poll events - we commit cqe.
> 
> wait_queue is indeed armed, and when the event triggers, that issues the callback that will retry the operation. However, that is not handled by io-wq, it's handled by the original task itself, similar to how signals are processed. io-wq can come into play. That happens if we trigger this callback and the retry yet again gets -EAGAIN, we currently do not retry with the poll callback at that point. Instead the poll is not rearmed and the request is handed to io-wq.
> 
> That last part should be improved so we just retry with poll. Generally it shouldn't be a common occurrence, however.

Hi Jens, is there any concern that prevent us from the improvement?

**Comment by axboe** [comment]
> Hi Jens, is there any concern that prevent us from the improvement?

Not really. The reason why I implemented it like that was to potentially avoid a case where we get repeated -EAGAIN when we retry, which would then just set us up for just doing repeated poll arm, poll trigger, retry loops. So I do think it needs to be gated somehow, but doing it on just the first retry failure after poll arm is most likely just a bit too cautious and will likely hit that condition for certain workloads.

Open to suggestions here. We do have a bit of space in io_poll_iocb so we could just add a counter for retries, using an unsigned char for that.

**Comment by isilence** [comment]
Another concern is thundering herd problem, IIRC as poll wakes all the queued callbacks, we don't want a scenario like:

1) enqueue N recv requests -> N goes to poll
2) poll triggers all N poll handlers, all N recvs retry, only 1 succeeds
3) we have N-1 requests polling
4) N=N-1, goto 1)

**Comment by axboe** [comment]
Certainly some implementation details to care about, thundering herd applies equally to once they have been io-wq offloaded.

**Comment by isilence** [comment]
> Certainly some implementation details to care about, thundering herd applies equally to once they have been io-wq offloaded.

I should be lighter I think, it's sitting blocking deeper in net stack, versus io_uring's poll+tw+retry etc., would be interesting to see what it is in reality. Anyway, queueing many recv requests for the same socket is probably not a common pattern, is it?

**Comment by axboe** [comment]
It's the same wakeup and io-wq are known to be sleeping, vs poll callback + tw trigger the task might already be running. So not sure I agree with it being less with io-wq, I'd think the opposite.

But yeah, we're not expecting this to be a common case, it'd be a pretty stupid use case.

**Comment by HowHsu** [comment]
> We also should be careful to not race. For example, make sure that `__io_arm_poll_handler()` would go to sleep right after `vfs_poll()` and following section under ->completion_lock doesn't see the second poll attempt.
> 
> ```
>                              | __io_arm_poll_handler()
>                              | -> vfs_poll()
> poll_callback()              |
> retry io_recv()              |
> another poll_callback()      |
>                              | rest of __io_arm_poll_handler();
> ```

Sure, need to be careful about race and other problems. For this one, simply put the counter increment and counter check 
at the beginning of io_arm_poll_handler() should be fine? Since io_arm_poll_handler() is called one by one:
```
                             | __io_arm_poll_handler()
                             | -> vfs_poll()
poll_callback()              |
retry io_recv()              |
->eagain?
-->arm_poll
--->counter overflow, failed
     |
                             | rest of __io_arm_poll_handler();
```

**Comment by HowHsu** [comment]
> Certainly some implementation details to care about, thundering herd applies equally to once they have been io-wq offloaded.

Agree, and users should be able to know when to add EPOLLEXCLUSIVE to avoid it.
My question about this counter is how do we know the proper number of retry times, there is a great variety of use cases
