### ISSUE TITLE
[Question] How to make sure orderless write requests will be reordered in mq-deadline I/O scheduler

### ISSUE THREAD

**Issue by yingjia-git** [axboe/liburing#488]
Hi,

I am trying to send orderless write requests to a file through liburing (for example, write offset = 0, 1, 3, 2, and at first the file size is 0), so I put them in the SQ through io_uring_get_sqe() and io_uring_prep_writev() one by one and send them in a batch through io_uring_submit(). I hope they will be reordered to 0, 1, 2, 3 in the I/O scheduler (I think mq-deadline may help me do this). But the results from CQ show that write offset = 3 will always fail, which means that the order doesn't change.

So I wonder if the orderless write requests will be reordered in the scheduler and can I use liburing achieve my goal? Thanks for help!

**Comment by CarterLi** [comment]
The order of requests are not guaranteed since they are run in parallel.

If you want them running in any order, try IO_SQE_IOLINK

**Comment by yingjia-git** [comment]
Thanks for your reply, but I think I made my question confused.

I don't want them run in specified order in the user space, on the contrary, I allow them orderless, and I know that mq-deadline scheduler will reorder my orderless write, so I want to use liburing to check if it really does it. But the result shows that it doesn't, so I am not sure if the requests sent by liburing will be processed in the block I/O layer.

**Comment by HowHsu** [comment]
> Hi,
> 
> I am trying to send orderless write requests to a file through liburing (for example, write offset = 0, 1, 3, 2, and at first the file size is 0), so I put them in the SQ through io_uring_get_sqe() and io_uring_prep_writev() one by one and send them in a batch through io_uring_submit(). I hope they will be reordered to 0, 1, 2, 3 in the I/O scheduler (I think mq-deadline may help me do this). But the results from CQ show that write offset = 3 will always fail, which means that the order doesn't change.
> 
> So I wonder if the orderless write requests will be reordered in the scheduler and can I use liburing achieve my goal? Thanks for help!

Hi,
you actually put forward two questions:
1. Is liburing write requests go to block layer?
    AFAIK, a direct write request definitely goes through block layer. While a buffered write request may probably not since it
    just write data to page cache unless it causes writeback.
2. Does mq-deadline reorder the requests?
    I haven't read the source code of this scheduler but I think it's not reasonable for a block layer scheduler to reorder requests
    by their logic offset.. it even don't know the logic offset info since when bio/request already carries the physical info.
    btw, the requests in block layer is a different concept with requests in io_uring.

**Comment by yingjia-git** [comment]
> > Hi,
> > I am trying to send orderless write requests to a file through liburing (for example, write offset = 0, 1, 3, 2, and at first the file size is 0), so I put them in the SQ through io_uring_get_sqe() and io_uring_prep_writev() one by one and send them in a batch through io_uring_submit(). I hope they will be reordered to 0, 1, 2, 3 in the I/O scheduler (I think mq-deadline may help me do this). But the results from CQ show that write offset = 3 will always fail, which means that the order doesn't change.
> > So I wonder if the orderless write requests will be reordered in the scheduler and can I use liburing achieve my goal? Thanks for help!
> 
> Hi, you actually put forward two questions:
> 
> 1. Is liburing write requests go to block layer?
>    AFAIK, a direct write request definitely goes through block layer. While a buffered write request may probably not since it
>    just write data to page cache unless it causes writeback.
> 2. Does mq-deadline reorder the requests?
>    I haven't read the source code of this scheduler but I think it's not reasonable for a block layer scheduler to reorder requests
>    by their logic offset.. it even doesn't know the logic offset info since bio/request already carries the physical info.
>    btw, the requests in block layer is a different concept with requests in io_uring.
> 
> Regards, Hao

@HowHsu Thanks for your heartful reply. If liburing surely goes through block layer using O_DIRECT, I think I should read the source of mq-deadline scheduler to find further progress.
