### ISSUE TITLE
Consider adding support for combined I/O like write-(poll)-read with a single completion

### ISSUE THREAD

**Issue by rbernon** [axboe/liburing#489]
Hi,

I was playing around with io_uring, trying to use it in Wine to implement more efficient internal communication, and I think it could be useful if `io_uring` implemented some sort of combined I/O, returning a single CQE for a group of `IOSQE_IO_LINK`-ed operations (for instance, as it is how I'm currently combining the operations together).

The use case I have is a simple server, with multiple clients, communicating through pipes. The server processes requests one at a time, writes its reply and immediately queues the read for the next one. Using `IOSQE_IO_LINK` I can already link the write and read operations together, making sure it only starts reading for the next request on a pipe after finishing writing the reply, and it is already more efficient that queue-ing the read when the write CQE is received.

However, even doing this, the write SQE still creates a CQE, and pointlessly waking up the server just to acknowledge them. I think it could be even more efficient if this combined I/O created a single CQE only when the linked read completes.

This use case is pretty simple but I'm sure it could also be useful to have such feature for more complex linked operations.

Cheers,

**Comment by rbernon** [comment]
Ha I just found `IOSQE_CQE_SKIP_SUCCESS` which looks exactly like what I need. Going to try it.

**Comment by isilence** [comment]
About particularly write-(poll)-read, if the purpose of the poll is to `POLLIN` before read, it's not needed since some version where io_uring got `IORING_FEAT_FAST_POLL`. It will be polled internally if needed.

But yeah, `IOSQE_CQE_SKIP_SUCCESS`, queued for not yet released 5.17. Just to note if you use it, your app should not use `IOSQE_DRAIN`.

**Comment by rbernon** [comment]
Thanks, I guess I'll have to wait a bit then but it's nice to see that it's going to be supported. I don't think I've got any use for `IOSQE_IO_DRAIN` anyway.

I figured already that the poll wasn't needed, it was the pattern when using epoll for instance, I've also tried adding `IOSQE_ASYNC` on the read sqes, but I'm not sure if it made any difference either.
