### ISSUE TITLE
Something similar/better to self-pipe trick.

### ISSUE THREAD

**Issue by ioquatix** [axboe/liburing#492]
We need a thread-safe way to interrupt a blocking io_uring waiting for events.

There are a couple of options:

- self-pipe trick / notification pipe.
- eventfd
- ???

`kqueue` has the ability to send user notes. This would be equivalent to adding a no-op event to the completion queue which causes anyone waiting to wake up. However this would only work if the minimum number of waiting for events was 1.

Any other ideas?

(As an aside, it might make sense to enable GitHub discussions for this repo since this is probably more of a discussion than an issue).

**Comment by ciconia** [comment]
The Polyphony io_uring backend polls for events by waiting for a single CQE (using `io_uring_wait_cqe`), then peeking at the completion queue, handling all available CQEs. [The peeking code](https://github.com/digital-fabric/polyphony/blob/b10ae242272a4f7cde8a7494bcaa8db1754ba2c1/ext/polyphony/backend_io_uring.c#L144-L171) was adapted from liburing's [`io_uring_peek_batch_cqe`](https://github.com/axboe/liburing/blob/d84c29b19ed0b130000619cff40141bb1fc3615b/src/queue.c#L142-L180):

```c
void io_uring_backend_handle_ready_cqes(Backend_t *backend) {
  struct io_uring *ring = &backend->ring;
  bool overflow_checked = false;
  struct io_uring_cqe *cqe;
  unsigned head;
  unsigned cqe_count;

again:
  cqe_count = 0;
  io_uring_for_each_cqe(ring, head, cqe) {
    ++cqe_count;
    io_uring_backend_handle_completion(cqe, backend);
  }
  io_uring_cq_advance(ring, cqe_count);

  if (overflow_checked) goto done;

  if (cq_ring_needs_flush(ring)) {
    __sys_io_uring_enter(ring->ring_fd, 0, 0, IORING_ENTER_GETEVENTS, NULL);
    overflow_checked = true;
    goto again;
  }

done:
  return;
}
```

Once you check for CQEs that way interrupting is easy, just [submit a NOP SQE](https://github.com/digital-fabric/polyphony/blob/b10ae242272a4f7cde8a7494bcaa8db1754ba2c1/ext/polyphony/backend_io_uring.c#L240-L256) and you're done :-).

**Comment by ioquatix** [comment]
Thanks @ciconia this is most helpful, you have done an amazing job trailblazing this functionality.

**Comment by ioquatix** [comment]
Out of curiosity, is your approach thread safe? How does that work?

**Comment by ciconia** [comment]
On MRI yes it's thread safe: when calling `io_uring_wait_cqe`, the backend sets a flag and [releases the GVL](https://github.com/digital-fabric/polyphony/blob/b10ae242272a4f7cde8a7494bcaa8db1754ba2c1/ext/polyphony/backend_io_uring.c#L173-L188):

```c
backend->base.currently_polling = 1;
rb_thread_call_without_gvl(io_uring_backend_poll_without_gvl, (void *)&poll_ctx, RUBY_UBF_IO, 0);
backend->base.currently_polling = 0;
```

A second thread [wishing to interrupt the first thread](https://github.com/digital-fabric/polyphony/blob/b10ae242272a4f7cde8a7494bcaa8db1754ba2c1/ext/polyphony/backend_io_uring.c#L240-L256) will hold the GVL while checking if the first thread is currently polling for CQEs, submitting a NOP if necessary:

```c
if (backend->base.currently_polling) {
  struct io_uring_sqe *sqe = io_uring_get_sqe(&backend->ring);
  io_uring_prep_nop(sqe);
  io_uring_submit(&backend->ring);
}
```

The call to `rb_thread_call_without_gvl` in the first thread will only return once it has reacquired the GVL.

**Comment by isilence** [comment]
> We need a thread-safe way to interrupt a blocking io_uring waiting for events.
> 
> `kqueue` has the ability to send user notes. This would be equivalent to adding a no-op event to the completion queue which causes anyone waiting to wake up. However this would only work if the minimum number of waiting for events was 1.
> 
> Any other ideas?

Triggered timeout requests will wake io_uring (e.g. submit a 0ns timeout request), and IIRC will also be waken by signals. Not sure about liburing, it may try to re-enter.

**Comment by ioquatix** [comment]
Submitting a nop or 0ns timeout is not thread safe, right?
