### ISSUE TITLE
Two places with memory leaks

### ISSUE THREAD

**Issue by ycaibb** [axboe/liburing#499]
`fds` is leaked at 299
https://github.com/axboe/liburing/blob/d84c29b19ed0b130000619cff40141bb1fc3615b/test/accept.c#L297-L302

`buf` is leaked
https://github.com/axboe/liburing/blob/a357750b1547a7c5f4caac49bb0c556e4d4bb8c6/test/madvise.c#L107-L110

**Comment by axboe** [comment]
These are just test programs, resources are freed when the naturally exit.
