### ISSUE TITLE
No io_uring_submit for requeue(queue_prepped) in examples/io_uring_cp?

### ISSUE THREAD

**Issue by aprilweet** [axboe/liburing#503]
I have read the source code in examples/io_uring_cp,but i get confused by the re-queue logic.
![image](https://user-images.githubusercontent.com/10728431/147033174-8a1d13a0-e83a-4f34-9f86-22b55e86d81f.png)
Now suppose that all reads and mostly writes are done, but the last write returns EAGAIN(or short write is the same), then the program will skip all the `io_uring_submit` calls and directly block at the last `io_uring_wait_cqe`.
![image](https://user-images.githubusercontent.com/10728431/147033668-d3a22c39-a0f1-4eb8-82f0-76d84bd14745.png)
Then it means no `io_uring_submit` called for the last write, the kernel won't get notified for re-queued sqe, then kernel and user program both wait for each other?
Is this a bug?Please help, thanks.

**Comment by axboe** [comment]
Yes, does look like a bug where we don't do a submit if we're at the end.

**Comment by aprilweet** [comment]
Yeah, this example does not handle EAGAIN and short-read/write well.
The fix solution i think is just appending a `io_uring_submit` inside `queue_prepped`.

**Comment by axboe** [comment]
> The fix solution i think is just appending a io_uring_submit inside queue_prepped.

Yes I think so too. Neither case should actually ever trigger, but might in ancient kernels.
