### ISSUE TITLE
Why my old epoll_wait got interrupted by the new introduced io_uring ?

### ISSUE THREAD

**Issue by beef9999** [axboe/liburing#504]
Hi, I was using epoll to poll eventfd,  which was registered to io_uring as an event notification.

But my old epoll instance would sometimes fail at epoll_wait with the return value of -1 (errno = EINTR).

Looks like it was interrupted by SIGINT that was supposed to be delivered to io-wq threads.

So why would this signal propagate to my main thread?

And the weirdest part is, this signal couldn't be caught, even if I had set sigaction + SIG_IGN ...

**Comment by axboe** [comment]
What kernel?

**Comment by beef9999** [comment]
> What kernel?

CentOS latest kernel-5.15-ml rpm, I believe it’s the same as the upstream

**Comment by axboe** [comment]
It's largely driven by the use of task_work to efficiently get a task to finish/issue a specific piece of work, a mechanism which relies on "fake" signals to ensure they get run. If you're currently waiting in epoll_wait, it may get interrupted and needs to get restarted. Could get worked around in epoll by changing the:

```
if (signal_pending(current))
        return -EINTR;
```

in ```epoll()``` to:

```
if (signal_pending(current)) {
        if (test_thread_flag(TIF_NOTIFY_SIGNAL)
                return -ERESTARTSYS;
        return -EINTR;
```

But you can also just retry the ```epoll_wait()``` from userspace if you run into this.

**Comment by beef9999** [comment]
> It's largely driven by the use of task_work to efficiently get a task to finish/issue a specific piece of work, a mechanism which relies on "fake" signals to ensure they get run. If you're currently waiting in epoll_wait, it may get interrupted and needs to get restarted. Could get worked around in epoll by changing the:
> 
> ```
> if (signal_pending(current))
>         return -EINTR;
> ```
> 
> in `epoll()` to:
> 
> ```
> if (signal_pending(current)) {
>         if (test_thread_flag(TIF_NOTIFY_SIGNAL)
>                 return -ERESTARTSYS;
>         return -EINTR;
> ```
> 
> But you can also just retry the `epoll_wait()` from userspace if you run into this.

Will other sys calls be interrupted? Like read/write and send/receive. Not all of the old code has dealt with signal retry…

**Comment by axboe** [comment]
Most code return ```-ERESTARTSYS``` on pending signals, which just means that operation gets restarted without the application being aware of it.

**Comment by axboe** [comment]
task_work got introduced later than 5.4, so it should not happen there.

**Comment by beef9999** [comment]
Re-open it.
@axboe After some more tests, now I strongly suggest the patch you wrote above be merged into the mainline kernel.
Because it's kind of too frequent to meet this EINTR on my epoll_wait. That leads to a lot of unnecessary context switches between user and kernel space, if the stress is high.

**Comment by beef9999** [comment]
@axboe I think we ought to merge the fix above into the mainline kernel.
Because the epoll manual says that EINTR only means it was interrupted by a user signal. We shouldn't let kernel signal be propagated to user space, especially when user might not have set any signal handler at all.

**Comment by lihuiba** [comment]
> 

As our app framework deals signals with _signalfd_, our entire app is considered free of interruption, and it doesn't deal with EINTR specifically in all syscalls. The app runs very well, until we try to include the new I/O engine of io_uring.

I'm wondering whether the signals are absolutely needed to cooperate with the workers.

Is it possible to implement a new mechanism that resembles signal, and it doesn't mess other threads/syscalls up?
