### ISSUE TITLE
Question: io_uring and file seeks

### ISSUE THREAD

**Issue by boxerab** [axboe/liburing#507]
Is there any problem with calling a series of `io_uring_prep_writev` calls on a file descriptor, 
with each write followed by an `lseek` on the file descriptor ?

i.e.
```
io_uring_prep_writev
io_uring_sqe_set_data(sqe, data);
io_uring_submit(ring);
...
lseek
...
io_uring_prep_writev
io_uring_sqe_set_data(sqe, data);
io_uring_submit(ring);
...
`lseek`
...
```

**Comment by axboe** [comment]
The io_uring writev command includes an offset, so the lseek wouldn't matter to io_uring.

**Comment by boxerab** [comment]
Thanks! The `lseek` is actually performed in another library, which then passes me the file descriptor. 
So, I would like to use ` io_uring writev` command always with zero offset, and let the other library manage the seek on the fd. 
Since io_uring writev is asynch, I am wondering if this will cause any issues.

**Comment by axboe** [comment]
Then you want to use ```-1``` as the offset, which means "use current file position". But if at at possible I'd avoid that, as ordering means this is kinda wonky for an async API. Would be better to just pass in the offset directly, by far.

**Comment by boxerab** [comment]
Thanks, yes, I was also thinking this would be wonky. I will try probably need to modify the other library to pass me the absolute offset and not perform the seek.
