### ISSUE TITLE
optimizing io uring performance in an image codec

### ISSUE THREAD

**Issue by boxerab** [axboe/liburing#511]
I have integrated liburing into my JPEG 2000 image codec:

https://github.com/GrokImageCompression/grok
https://github.com/GrokImageCompression/grok/blob/master/src/bin/image_format/FileUringIO.cpp

I am trying to optimise the workflow for decompressing a large, multi-tiled image :
1. a compressed image is compressed using tiles of dimension 2048x2048
1. the complete uncompressed image dimensions are 25000x25000
1. the decompressor is heavily multi-threaded - tiles are decompressed in parallel
1. when a strip of tiles of dimension 25000x2048 has been completely decompressed, this strip will be written out to disk
by the thread that has just decompressed the final tile in the strip

The old implementation used synchronous writes for each strip of tiles. My thinking was that using io uring, the thread would
be ready earlier for the next task as it doesn't have to wait for synchronous write to complete, so performance should improve.

I've tested this on a laptop with 12 threads, running Fedora with kernel 5.15, and a 48 thread Threadripper running
5.11. In both cases, the uring implementation is a bit slower than the synchronous one. 

Is there a way of optimising performance in this multi-threaded work flow ? My guess for why performance is lower with uring is that the number of iops is still rather low, so the overhead of the queues slightly degrades performance. Any insights as to why the performance is lower would be greatly appreciated. Thanks!

**Comment by YoSTEALTH** [comment]
1. `io_uring` is not thread-safe though (no-serialization).
2. Performance might have improved if you were using `io_uring` in a single thread.
3. Could read more about `io_uring` https://unixism.net/loti/
4. As for multi-threading itself ... https://twitter.com/themitcho/status/308026012455821312 comes to mind (joke).

That being said, there is still room for `io_uring` to grow in therms of user-space multi-threaded side of things.

**Comment by boxerab** [comment]
@YoSTEALTH thanks - I've read the documentation, and I am serializing  `io_uring` requests using a lock.
In my application, it doesn't make sense to use a single thread as the task is compute-bound, not io bound.
I agree with you - threads are evil :) but a necessary evil in my case.

**Comment by YoSTEALTH** [comment]
> I am serializing io_uring requests using a lock.

You are probably loosing all the benefit of `io_uring` when you do that plus extra overhead.

> it doesn't make sense to use a single thread as the task is compute-bound, not io bound.

True

**Comment by boxerab** [comment]
So, are you saying that `io_uring` was designed for single-threaded applications ?

**Comment by boxerab** [comment]
@YoSTEALTH it never occurred to me to have multiple rings, but if I use one ring per thread, then I don't need to serialize via lock.

**Comment by YoSTEALTH** [comment]
> So, are you saying that io_uring was designed for single-threaded applications ?

You would have to ask @axboe that.

From what I can gather it seems like its designed more for single thread vs multi-thread, which in itself is not a bad thing. Since `io_uring` can handle lots (millions!) of sqe/cqe io/second in a single thread, It doesn't really make sense for it to be spread throughout threads. You would have to design your software around this concept, where you have 1 main event manager and small jobs can be done in this single thread or offload the jobs that require computation to other threads.

Another potential solution https://github.com/axboe/liburing/issues/388

I tend to like the idea of `io_uring` having a parent ring where it can submit/monitor/... task from  other threads. Of course this is easy to say vs actually implementing it.

**Comment by boxerab** [comment]
@YoSTEALTH thanks for your comments.

I managed to test your hypothesis that single threaded app would see benefits of `io_uring` : the codec can be configured to be single threaded. 
Unfortunately, with one thread, with `io_uring` enabled it is about 1% faster than without.
So, I think it is more likely that the number of iops is too low for there to be a benefit.

**Comment by CarterLi** [comment]
For multi threaded apps, you may create independent io_uring instance per thread,  and share io-wq worker poll using [IORING_SETUP_ATTACH_WQ](https://github.com/axboe/liburing/blob/master/man/io_uring_setup.2#L173) flag

**Comment by YoSTEALTH** [comment]
https://blog.cloudflare.com/missing-manuals-io_uring-worker-pool/

**Comment by boxerab** [comment]
closing :  #517 has actual code that addresses the topics raised in this issue.
