### ISSUE TITLE
sqe lifetime

### ISSUE THREAD

**Issue by tickox** [axboe/liburing#514]
Hello,

Is it a bug risk to call ```io_uring_sqe_set_data()```after```io_uring_submit()```? 
From when should the sqe no longer be used so as not to create a bug?

```cpp
void c(io_uring_sqe* sqe) {
  io_uring_sqe_set_data(sqe, *);
}


void test(callback c) {
  io_uring_sqe *sqe = io_uring_get_sqe(&ring);
  io_uring_prep_*();
  io_uring_submit(&ring);
  return c(sqe)
}
```
Thanks

**Comment by axboe** [comment]
Yes that's a clear bug. Once submit is called, the sqe may have already been read and anything you write to it might not get seen. When you submit, you pass ownership of the prepared sqes to the kernel.

**Comment by tickox** [comment]
Ok, thank you for your very quick response.
