### ISSUE TITLE
Possible to get "outstanding" ops?

### ISSUE THREAD

**Issue by JonKohler** [axboe/liburing#518]
Looking through the liburing API, I didn't immediately see a way to get the amount of "outstanding" async calls, is that possible?

I'm working on extending an existing applications thread model to support io_uring. In short, the application has "functions" that get dispatched to a group of threadpools, each with one or more threads.

I'd like the "worker loop" of the threadloop to process completions (peek / process / seen) and the "function" will take care of the SQE/prep/submit.

We've got both a sleep and exit condition on the threadpool "worker loop", such that if there is absolutely no more work to do currently, we'll issue a FUTEX_WAIT and when work is added, we'll FUTEX_WAKE.

I'd like to make sure we process any outstanding io_uring based work, such that we wait for _**any**_ outstanding CQEs before issuing the FUTEX_WAIT.

I see that I can check if there are unconsumed/unsubmitted SQEs, and I see I can check if there are outstanding CQEs; however, I'm guessing I've got a blindspot with "submitted-to-the-kernel-but-not-yet-completed-by-the-kernel".

Would I just have to track that with an int on my side? or is this something io_uring can do?

**Comment by axboe** [comment]
> Would I just have to track that with an int on my side? or is this something io_uring can do?

You have to track it on your side, so basically just N_submits - N_completions or something like that. Neither io_uring nor liburing tracks the inflight count for you.

**Comment by JonKohler** [comment]
Got it, thank you. I think what I'll do is wrap the io_uring_submit call with the threadpool APIs, such that the "functions" can get sqe/prep, but then they will be required to call into the threadpool to do the submit, then we'll track it all there.

Oh the joys of layering :/
