### ISSUE TITLE
Sockets readv/writev cqes not updated after `io_uring_wait/peek_cqe` call.

### ISSUE THREAD

**Issue by tofes** [axboe/liburing#519]
Hi @[YoSTEALTH](https://github.com/YoSTEALTH)/@[isilence](https://github.com/isilence)/@[axboe](https://github.com/axboe)/All, I'm in the middle of updating my network I/O code to use io_uring (from epoll) using liburing. I run into some basic issues while using sockets to do readv/writev, I posted similar issues on [https://github.com/shuveb/loti-examples/issues/19](https://github.com/shuveb/loti-examples/issues/19), can you help to explain why the cqes values are not updated?

The sockets I created were using the existing regular functions socket(), bind(), accept(), connect() etc, no liburing functions were called. Once the sockets were set up and connected, for read and write using the sockets I switched to use the new liburing functions. e.g.` io_uring_get_sqe, io_uring_prep_writev, io_uring_sqe_set_data, io_uring_submit` for submission.

For completion, I used `io_uring_wait_cqe ` and unexpectedly on the first call the `cqes->res` value was not updated: in my code I constantly getting -9 (_errno_ 9) while in the example linked above it was always -5 (_errno_ 5). I printed out the actual _errno_ values which were different. For some reasons the kernel didn't update the cqes values after calling `io_uring_wait_cqe ` or `io_uring_peek_cqe `. Is it a bug or am I missing something?

**Comment by axboe** [comment]
Are you marking it as seen? It sounds like you're not, which means you keep looking at the same cqe which obviously doesn't update (at least until the ring wraps).

**Comment by axboe** [comment]
See all the other examples, they all follow something ala:

```
io_uring_wait_cqe(ring, &cqe);
/* inspect cqe->res */
io_uring_cqe_seen(ring, cqe); /* mark this cqe as seen, advances CQ ring */
```

**Comment by tofes** [comment]
Yes, for completion I followed the example to call ` io_uring_wait_cqe, io_uring_cqe_get_data, io_uring_cqe_seen`.  However the cqes->res value was not updated on the first `io_uring_wait_cqe ` call, will it only be updated after calling `io_uring_cqe_seen`?

**Comment by axboe** [comment]
cqe->res is written before you see the cqe when you call peek or wait cqe. if it's a new cqe and you are indeed marking it as seen when you are done with it, then that would seem to indicate that you get the same error for your requests, not that it's not being updated.

Please provide some example code, otherwise this is just going to be a guessing game on what potentially is buggy.

**Comment by axboe** [comment]
Looking at your other posting, you're using the accept command, which was added way later than the kernel you are targeting.

**Comment by tofes** [comment]
sample code below: 
```
struct io_uring_cqe* cqe;
int ret = io_uring_wait_cqe(m_uring, &cqe);
if (ret < 0) {
    printf("fatal error");
    return;
}
if (cqe->res <= 0) {
    printf("cqe->res : errno %d", -cqe->res);
    return;
}
void* data = io_uring_cqe_get_data(cqe);
io_uring_cqe_seen(m_uring, cqe);
```

**Comment by axboe** [comment]
I mean sample code that demonstrates your issue, the above doesn't do that at all.

**Comment by axboe** [comment]
Well one thing wrong in that small snippet is that you are not calling io_uring_cqe_seen() if cqe->res is less than zero, indicating an error. I'm guessing that's your actual issue...

**Comment by axboe** [comment]
```
struct io_uring_cqe* cqe;
int ret = io_uring_wait_cqe(&ring, &cqe);
if (ret < 0) {
    printf("fatal error");
    return;
}
if (cqe->res <= 0) {
    printf("cqe->res : errno %d", -cqe->res);
    io_uring_cqe_seen(&ring, cqe); /* <- if you don't call it here, you'll see the same cqe next time */
    return;
}
void* data = io_uring_cqe_get_data(cqe);
io_uring_cqe_seen(&ring, cqe);
```

**Comment by tofes** [comment]
Ah, a failed operation still needs to be marked processed. I will add the `io_uring_cqe_seen `as suggested. Thanks!

The other part of the question is still there, why is the cqe->res value not updated on the very first call of `io_uring_cqe_seen`?

**Comment by tofes** [comment]
I just tested my code adding the `io_uring_cqe_seen` after a failed operation, but the `cqes->res` is still the same value.

**Comment by tofes** [comment]
Kernel 5.5 include `accept `support, no?
![image](https://user-images.githubusercontent.com/30063707/152442863-1ae5370a-d7b9-49e3-8213-00a78d5665f9.png)
This example code [https://github.com/shuveb/loti-examples/issues/19](https://github.com/shuveb/loti-examples/issues/19) should work?

**Comment by axboe** [comment]
>Ah, a failed operation still needs to be marked processed. I will add the io_uring_cqe_seen as suggested. Thanks!

It doesn't matter what the result of the operation is, you must call seen on the cqe if it's been posted and you are done with it.

> The other part of the question is still there, why is the cqe->res value not updated on the very first call of io_uring_cqe_seen?

I think you are misunderstanding something. cqe_seen doesn't touch the cqe at all, it just increments the cq ring index telling the kernel you've seen it. Any particular cqe index is never updated after it's posted, it'll just get overwritten at some point as more cqes are generated.

**Comment by axboe** [comment]
You are right, it is available in 5.5, I misremembered. Still need the sample code that exhibits the error. If you get -9, then that indicates that the fd you are passing in isn't a socket, for example, or otherwise invalid.

**Comment by tofes** [comment]
Thank you @axboe for the explanations and I see I was reading the same cqe of the same operation, so I saw the same value of cqes->res before and after calling `io_uring_wait_cqe `or `io_uring_cqe_seen`.

I used the [https://github.com/shuveb/loti-examples/issues/19](https://github.com/shuveb/loti-examples/issues/19) example to guide my code and example has the similar issue.  I updated the example code to include the `io_uring_cqe_seen`:
```
void server_loop(int server_socket) {
    struct sockaddr_in client_addr;
    socklen_t client_addr_len = sizeof(client_addr);

    add_accept_request(server_socket, &client_addr, &client_addr_len);

    while (1) {
        struct io_uring_cqe *cqe;
        int ret = io_uring_wait_cqe(&ring, &cqe);
        printCQ(&ring.cq,0);
        if (ret < 0)
            fatal_error("io_uring_wait_cqe");
        struct request *req = (struct request *) cqe->user_data;
        if (cqe->res < 0) {
            fprintf(stderr, "Async request failed: %s for event: %d\n",
                    strerror(-cqe->res), req->event_type);
            io_uring_cqe_seen(&ring, cqe);
            exit(1);
        }

        switch (req->event_type) {
            case EVENT_TYPE_ACCEPT:
                add_accept_request(server_socket, &client_addr, &client_addr_len);
                add_read_request(cqe->res);
                free(req);
                break;
            case EVENT_TYPE_READ:
                if (!cqe->res) {
                    fprintf(stderr, "Empty request!\n");
                    break;
                }
                handle_client_request(req);
                free(req->iov[0].iov_base);
                free(req);
                break;
            case EVENT_TYPE_WRITE:
                for (int i = 0; i < req->iovec_count; i++) {
                    free(req->iov[i].iov_base);
                }
                close(req->client_socket);
                free(req);
                break;
        }
        /* Mark this request as processed */
        io_uring_cqe_seen(&ring, cqe);
        printCQ(&ring.cq);
    }
}

```
Printing out the `cqes->res` values it's still not changed and is always -5 in the example.

**Comment by axboe** [comment]
-5 for what request? Must be the read, as EIO would not be valid for accept. I suggest you add some debugging around what you are getting out of each request type, and what is being submitted. That'll make it easier for people to help you as well.

**Comment by tofes** [comment]
Sorry, the -5 was for the first `accept `call, after the updates I saw the following `cqes->res` have different values for accept, they are -6, -475, -699, -391, -47553 for different sqe operations.

**Comment by axboe** [comment]
None of those values make any sense, I think there's something deeper wrong with your code to be honest. If you provide a full example (eg something that can be compiled and run, not a snippet), then I can take a look. But I can't spend time on it otherwise, just don't have it to spend.

**Comment by tofes** [comment]
I'm using the linked example [https://github.com/shuveb/loti-examples/issues/19](https://github.com/shuveb/loti-examples/issues/19), not running my code.

**Comment by tofes** [comment]
But I think regarding this issue's topic you have resolved it for me.  The other errors are separate issues.
