### ISSUE TITLE
Are the memory layout of the rings guaranteed to remain stable?

### ISSUE THREAD

**Issue by mrakh** [axboe/liburing#524]
I've looked at the kernel source code, and I've noticed that the memory layout for the rings has changed twice: once from v5.3 to v5.4 when `IORING_FEAT_SINGLE_MMAP` was introduced, and once from v5.7 to v5.8 when the `cq_flags` field was added to `struct io_rings`. It looks like the expected usage of these rings is that the application will strictly use the offset values written by `io_uring_setup` in the `struct io_uring_params`'s `sq_off` and `cq_off` fields. But I can also imagine that some applications would ignore those and instead rely on the offsets being fixed, and any such application would have broken due to these ABI changes.

Can we expect these offsets to remain static, going forward? Or is the memory layout of these rings still subject to backwards-incompatible changes in future kernel versions?

If there is no desire to commit to static offsets, then perhaps it would be a good idea to randomize the rings' data layout each time an `io_uring` object is created. This would express the intent more clearly, and applications relying on fixed offsets would break quickly instead of silently working until the next kernel release.

**Comment by axboe** [comment]
None of those are backward incompatible changes. For the SINGLE_MMAP feature, it simply allows an application to make 2 mmap's to map the rings rather than 3. Any older application would not change behavior because of that.

When cq->flags was added to the ring, it used existing padding to add that field. That's why the padding exists in the first place. Again this is perfectly backward compatible, it does not change layout for any fields outside of the reserved fields that aren't (and never should) used for anything by liburing or applications using the raw interface.

**Comment by mrakh** [comment]
I'm not talking about the `cq_off.flags` field in `struct io_uring_params`. I'm talking about the ABI of the ring memory that is mmap'ed and exposed to userspace, which is defined by [`struct io_sq_ring`](https://elixir.bootlin.com/linux/v5.3/source/fs/io_uring.c#L93) and [`struct io_cq_ring`](https://elixir.bootlin.com/linux/v5.3/source/fs/io_uring.c#L152) in v5.1 - v5.3, and by [`struct io_rings`](https://elixir.bootlin.com/linux/v5.4/source/fs/io_uring.c#L93) in v5.4+. If you look at the history of those structs in the Linux kernel, the layout changes made to them are not backwards compatible. As an example, a program compiled from this, targeting v5.3:

```c
struct io_uring_params params;
int fd;
int ring_mask_offset;
struct io_sq_ring* sq_base; // struct definition copied from linux/fs/io_uring.c

memset(&params, 0, sizeof(params));
fd = io_uring_setup(256, &params);
sq_base = mmap(
	NULL,
	4096,
	PROT_READ | PROT_WRITE,
	MAP_SHARED | MAP_POPULATE,
	ring->fd,
	IORING_OFF_SQ_RING
);
ring_mask_offset = sq_base->ring_mask;
read_barrier();
```

...would inadvertently end up reading from the CQ head in v5.4 due to the switch from `struct io_sq_ring` to `struct io_rings` in the kernel. Same deal with the addition of the `cq_flags` member to `struct io_rings` - this program, targeting v5.7:

```c
struct io_uring_params params;
int fd;
int cq_flags;
struct io_rings* base; // struct definition copied from linux/fs/io_uring.c

memset(&params, 0, sizeof(params));
fd = io_uring_setup(256, &params);
base = mmap(
	NULL,
	4096 * 3,
	PROT_READ | PROT_WRITE,
	MAP_SHARED | MAP_POPULATE,
	ring->fd,
	IORING_OFF_SQ_RING
);
cq_flags = sq_base->cq_flags;
read_barrier();
```

...would end up reading from `cq_overflow` in v5.8.

So my question is, what guarantees (if any) are there about the stability of `struct io_rings` defined in `fs/io_uring.c`, seeing as the struct is exposed to userspace memory?

**Comment by axboe** [comment]
Ah ok, I see what you mean. The API/ABI is such that you need to use the offsets given to you to map the rings. If you hardcode offsets, then you are at risk of things breaking between releases. I'm not aware of anything that has broken because of that, no reports ever sent in on that. liburing of course handles this for you, but even the raw interface variants that I've done myself (like the fio engine, or the t/io_uring in fio) never saw anything odd because they use the passed back offsets for mapping as they should.

That's how it has been exposed from day 1. Yes, we could randomize the layout, but don't really see much point to that, and if we did, it should still be within the sq and cq rings themselves only to avoid the carefully placed cacheline alignment being messed up and things running slower than they should.

**Comment by mrakh** [comment]
> Ah ok, I see what you mean. The API/ABI is such that you need to use the offsets given to you to map the rings. If you hardcode offsets, then you are at risk of things breaking between releases. I'm not aware of anything that has broken because of that, no reports ever sent in on that. liburing of course handles this for you, but even the raw interface variants that I've done myself (like the fio engine, or the t/io_uring in fio) never saw anything odd because they use the passed back offsets for mapping as they should.
> 
> That's how it has been exposed from day 1. Yes, we could randomize the layout, but don't really see much point to that, and if we did, it should still be within the sq and cq rings themselves only to avoid the carefully placed cacheline alignment being messed up and things running slower than they should.

Thanks for the answer. But I must add that even if no breakages have been reported thus far, there is still the potential for future reported breakages from developers who don't have the good fortune of coming across this thread. It is a sad fact of life that any implementation detail exposed to userspace is subject to being relied upon, and I anticipate this to be especially true in the case of `io_uring`, as Linux's latest and greatest general-purpose I/O multiplexer sees more widespread use. It might be prudent to proactively address this before it becomes a problem. So if you're not opposed to the idea of randomizing the ring layout, I could contribute a patch to do so.

**Comment by mrakh** [comment]
The idea is to fail fast for people that *don't* obey the API. In a perfect world, everyone would use `liburing`, or at least be studious enough to re-implement it faithfully. Examples and documentation help, but they don't prevent people from straying from the spec. It's not particularly unlikely that someone trying to be clever would think "hmmm, these offsets don't ever seem to change", and hardcoding them to save a few bytes in some struct. But if you judge a randomization patch to be a fruitless effort, I can close the issue.

**Comment by axboe** [comment]
> The idea is to fail fast for people that don't obey the API

Yeah I get that, but my point is that 1) I haven't seen anyone do that, and 2) it falls very thoroughly into the "doctor it hurts [...]" kind of issue in my opinion. Obviously if you use liburing, then all of this is moot, as it handles it all for you. If you use the raw interface AND you decide to hard code random offset values, then I kind of think you get what you deserve... That's misusing the API.

**Comment by mrakh** [comment]
Fair points. In that case, I will close as the matter is resolved.
