### ISSUE TITLE
Using `io_uring_get_probe` give nullptr back on kernel 5.5?

### ISSUE THREAD

**Issue by tofes** [axboe/liburing#526]
Following https://unixism.net/loti/tutorial/probe_liburing.html, using the `io_uring_get_probe` from liburing, running the code below gave Segmentation fault.

```
            bool support = false;
            struct io_uring_probe* probe = io_uring_get_probe();
            if (probe)
            {
                support = io_uring_opcode_supported(probe, IORING_OP_ACCEPT) == 1 ? true : false;
                free(probe);
            }
```

The function `io_uring_get_probe`  returns a nullptr back. It appears the `syscall(__NR_io_uring_register, fd, opcode, arg, nr_args);` is failing. I'm running on kernel version: 5.5.0-050500-lowlatency.
```
#0  __sys_io_uring_register (fd=7, opcode=8, arg=0x770fe6bc6a00, nr_args=256) at syscall.c:53
#1  0x00005555560d0476 in io_uring_register_probe (ring=ring@entry=0x770fefffd8e0, p=0x8, p@entry=0x770fe6bc6a00, nr_ops=4139543040, nr_ops@entry=256) at register.c:204
#2  0x00005555560cf4b4 in io_uring_get_probe_ring (ring=0x770fefffd8e0) at setup.c:193
#3  io_uring_get_probe () at setup.c:211
```
Is the `io_uring_get_probe` supported for kernel 5.5? Am I missing something or it's a bug for kernel 5.5?

**Comment by axboe** [comment]
Probe isn't supported in 5.5 and earlier, it got added with the 5.6 release. Your program needs to be able to deal with a ```NULL``` probe return.
