### ISSUE TITLE
Question about LIBURING_UDATA_TIMEOUT filtering 

### ISSUE THREAD

**Issue by twissel** [axboe/liburing#53]
Currently `io_uring_peek_cqe` filters  all cqes with `user_data` set to `LIBURING_UDATA_TIMEOUT`, while io_uring_peek_batch_cqe does not. This is desired  behavior or not? 

Sample code:
```
#include "liburing.h"
#include <stdio.h>
#include <errno.h>

int main(int argc, char const *argv[])
{
    int ret;
    struct io_uring ring;
    struct io_uring_sqe *sqe;
    struct io_uring_cqe *cqe;

    ret = io_uring_queue_init(32, &ring, 0);

    if (ret)
    {
        fprintf(stderr, "queue init failed: %d\n", ret);
        return ret;
    }

    sqe = io_uring_get_sqe(&ring);
    if (!sqe)
    {
        fprintf(stderr, "sqe get failed\n");
        return 1;
    }

    // this one gets filtered
    io_uring_prep_nop(sqe);
    io_uring_sqe_set_data(sqe, (void *)LIBURING_UDATA_TIMEOUT);

    ret = io_uring_submit_and_wait(&ring, 1);

    if (ret != 1)
    {
        fprintf(stderr, "submit failed: %d\n", ret);
        return 1;
    }

    ret = io_uring_peek_cqe(&ring, &cqe);

    if (ret != -EAGAIN)
    {
        fprintf(stderr, "peek failed: %d\n", ret);
        return ret;
    }

    sqe = io_uring_get_sqe(&ring);
    if (!sqe)
    {
        fprintf(stderr, "sqe get failed\n");
        return 1;
    }

    // this one is not filtered
    io_uring_prep_nop(sqe);
    io_uring_sqe_set_data(sqe, (void *)LIBURING_UDATA_TIMEOUT);

    ret = io_uring_submit_and_wait(&ring, 1);

    if (ret != 1)
    {
        fprintf(stderr, "submit failed: %d\n", ret);
        return ret;
    }

    ret = io_uring_peek_batch_cqe(&ring, &cqe, 1);
    if (ret != 1)
    {
        fprintf(stderr, "peek batch failed, expected 1, got: %d\n", ret);
        return ret;
    }

    if (cqe->user_data != LIBURING_UDATA_TIMEOUT)
    {
        fprintf(stderr, "LIBURING_UDATA_TIMEOUT expected");
        return 1;
    }
    return 0;
}

```

**Comment by axboe** [comment]
It's a little bit awkward, not sure how best to handle it. The caller still needs to advance the cq ring, so we basically need to return it. Definitely up for suggestions on how to improve that, as the app really shouldn't have to deal with that.

**Comment by axboe** [comment]
Only idea I have is to increment the cq ring by the number of timeouts we found, and then return only the "real" ones. Then the increment by the application would make things correct again. Only downside there is that two repeated calls to peek_batch() would yield inconsistent results, which kind of sucks.

**Comment by axboe** [comment]
Outside of that, only an API change could fix it as far as I can tell. If you can return two numbers:

1) Number of CQEs for the application
2) Total number of CQEs

and have the app use #1 for iterating the array of cqes, and #2 for the cq ring increment/advance. That would work, but I don't see a way to do that within the existing function definition.

**Comment by twissel** [comment]
Hm, maybe we can have some timeout_flag like IOURING_INTERNAL_TIMEOUT, and than all of that cqes will be filtered on kernel side?

**Comment by axboe** [comment]
That's not a bad idea, would clean up that part in liburing too.

**Comment by CarterLi** [comment]
> Hm, maybe we can have some timeout_flag like IOURING_INTERNAL_TIMEOUT, and than all of that cqes will be filtered on kernel side?

What about a flag called IOSQE_IGNORE_CQE ( or something else ) which indicates that this operation should not generate a cqe. This should be an more general solution, since users usually don't care the result of POLL_REMOVE/TIMEOUT_REMOVE/ASYNC_CANCEL too

**Comment by vertexclique** [comment]
I don't know is it related or not, but whenever I set user_data for a sqe, and receive cqe with `io_uring_peek_batch_cqe` user data is coming as 0. Is it intended behavior?

**Comment by isilence** [comment]
Time to close? `LIBURING_UDATA_TIMEOUT` is long dead for good and it's rather legacy.
