### ISSUE TITLE
Questions on development workflow

### ISSUE THREAD

**Issue by rojkov** [axboe/liburing#534]
I'm trying to bring io_uring support to Envoy and we've got [some concerns](https://github.com/envoyproxy/envoy/pull/19339#issuecomment-1047328044) regarding liburing's safety:

1. Is this repo mirroring the repo at kernel.org or the other way around? If the latter then would it be possible to enable github's branch protection, to add an explicit security policy, etc?
2. Would it be possible to clarify what's expected from contributors in e.g. CONTRIBUTING.md?

**Comment by axboe** [comment]
1. The canonical location is git.kernel.dk, both this and kernel.org are mirrors of that. We can enable the branch protection. Not sure what you security policies  you think would be useful? I currently only sign tags, but commits.
2. Yes, that's a good idea, and might actually save me some explaining about the expectations in terms of pull requests. I'll take a look at that.

**Comment by rojkov** [comment]
Thank you for your quick reply! At the moment I'm seeking formal improvement of the OSSF Scorecard result for liburing. It would help a lot if there was a SECURITY.md file in the repository instructing how to report embargoed security vulnerabilities. Preferably there should be a private channel for this kind of reporting. The file will become the content of the page https://github.com/axboe/liburing/security/policy.

**Comment by axboe** [comment]
Would you be interested in submitting such a change? For now, anything that is sensitive should be emailed to ```axboe@kernel.dk```.

**Comment by rojkov** [comment]
Sure, I will do that.
