### ISSUE TITLE
does it make sense using IORING_POLL_ADD_MULTI together with IOSQE_IO_LINK ? 

### ISSUE THREAD

**Issue by romange** [axboe/liburing#545]
hi,

I currently use POLLIN with IOSQE_IO_LINK that is folllowed up by IORING_OP_READ of size 8 to drain my eventfd descriptor.

I wanted to add `IORING_POLL_ADD_MULTI` option but then understood that it would probably be ill-defined with  IOSQE_IO_LINK. 
Am I right? Does kernel allow such combination?

**Comment by axboe** [comment]
It won't really work. Links are started when a request is done, and a multi-shot poll would never really be done (unless you hit an error, for example).
