### ISSUE TITLE
user access

### ISSUE THREAD

**Issue by YoSTEALTH** [axboe/liburing#55]
Is there a way to manage user access/permission?

For example say i use liburing to be a web server and run it as a "root" user maybe i am using "IORING_SETUP_SQPOLL". I wouldn't want my web server to run everything in root privileges, maybe some of the functions(read/write, ...) needs to run as other users.

Maybe this is something we can set in sqe

sqe = io_uring_get_sqe(ring)
sqe.setuid = 123

on error it would raise permission denied error.

**Comment by axboe** [comment]
I think that would be better done as a separate command. io_uring consumes sequentially, so you would always know what the personality would be for a given later command in the chain. And we'd need to register these personalities upfront - it's not just credentials, it's things like what memory management domain to use, etc.

**Comment by YoSTEALTH** [comment]
Jens,

I see what you are saying. I like the register upfront idea as well. I will leave this to the expert ;) ;)

**Comment by YoSTEALTH** [comment]
Let me confirm how ``io_uring_register_personality`` will works...

Only ``root`` user can initialize ``io_register_personality()``?

Once established you can:
``sqe = io_uring_get_sqe(ring);
sqe->personality = 123`` any user id you choose?

**Comment by axboe** [comment]
No, see the man page. You register a personality by having THAT personality invoke io_uring_register(), and then you'll get an ID returned from that. That ID is what you use in sqe->personality.

**Comment by YoSTEALTH** [comment]
hmm... how do you go about setting multiple personalities without having to fork+set or losing current credentials?

**Comment by axboe** [comment]
You register one for each task, by having the task do the registration. After that you have an ID that you can use to request this personality for subsequent IO, regardless of who submits it.
