### ISSUE TITLE
Workaround to validate socket buffer size before read/write

### ISSUE THREAD

**Issue by tofes** [axboe/liburing#550]
Following the thread in [issues 234](https://github.com/axboe/liburing/issues/234), I have a separate question:

Our system used *epoll_wait* and I have integrated *io_uring* to our system. One of the test cases I have is to set a socket buffer size to X, then pass in an allocated buffer with a greater size Y to do read/write. I would expect some kind of failure for the mismatched buffer sizes however *io_uring* completed the read/write successfully.  In this case, even if I remember the set socket buffer size X in my code, it's tricky to check it against the passed in real buffer size Y because the buffer passed in is just a pointer by the time it reaches `io_uring_prep_writev()`. Are there any better ideas, or is this test case even valid for *io_uring*?

**Comment by victorstewart** [comment]
you can store the buffer pointer and its length in a heap allocated struct, then store the struct address in the user data field, and then cast it back to the struct address when the operation completes.

**Comment by axboe** [comment]
Or just some tag/index for the buffer, depending on how you index them. Then you don't need heap data at all, but if it's all allocated on demand, then yeah I'd just wrap a buffer in a struct with some identifying info. Then you still only need one alloc, just like for the buffer itself.

**Comment by tofes** [comment]
Ok, currently the way I did it is already allocating the buffer to heap and save its size as well, so I can check it with the saved socket buffer size before calling liburing read/write.  The user data field is used for other purposes already in my code. Maybe this is the best option for now?

**Comment by victorstewart** [comment]
also remember pointers are only 48 bits, so you have 16 free bits.

i left shift the io_uring opcode and OR it with the pointer to my stream object (which holds all relevant state) in my network server.

**Comment by axboe** [comment]
Yes, you can take advantage of memory aligning facts, just be careful making assumptions that'd break on other archs or 32-bit if you care about the latter.
