### ISSUE TITLE
What's the difference between IORING_OP_POLL_REMOVE and IORING_OP_ASYNC_CANCEL ?

### ISSUE THREAD

**Issue by beef9999** [axboe/liburing#551]
Can I use `io_uring_prep_cancel` to cancel a previous `io_uring_prep_poll_add` ?

**Comment by axboe** [comment]
You can, a generic cancel request will try to cancel all types of requests. poll_remove is just a poll specific variant of that, as it's a bit more efficient to only cancel the specific type you are interested in. In terms of cancelation, prep_cancel is a superset of poll_remove.
