### ISSUE TITLE
Question: Proper usage of io_uring_register_buffers

### ISSUE THREAD

**Issue by tkp1n** [axboe/liburing#56]
The man pages seem to indicate that it is fine to register additional/different buffers during the lifetime of a ring. It would help to add to the documentation a statement about when a call to unregister is considered safe. 
It comes down to the following question: "Is it safe to unregister and re-register buffers, while an operation like `IORING_OP_READ_FIXED` is submitted but not yet completed?" Or in other words: "Would one have to wait until all scheduled operations on registered buffers are completed before unregistering?" I assume the latter but it makes it non-trivial to register/unregister buffers at runtime based on the demand of the application. In this case, one would have to drain (`IOSQE_IO_DRAIN`) the ring before registering additional buffers which will likely cause a hiccup in throughput.

**Comment by axboe** [comment]
Right now a buffer registration would quiesce the ring, which I agree, isn't ideal. I recently implemented a relaxation of that for registered files, we can apply the same for buffers.

**Comment by tkp1n** [comment]
I'd say such a feature this would greatly simplify the use of registered buffers in more sophisticated scenarios. :+1:

**Comment by hedgefund** [comment]
Having run into some design issues regarding dynamic buffer registrations/unregistrations, I've come to believe the interface around it is lacking. It would have been much cleaner if the kernel would give you a unique buffer ID that never changes during the lifetime of the ring for each buffer you register, let you register individual buffers without having to unregister all the previous buffers, and then later let you unregister a specific buffer by its ID. Having worked with RIO on Windows this is the way they do things and it eases the development around it very much; see [RIORegisterBuffer](https://docs.microsoft.com/en-us/previous-versions/windows/desktop/legacy/hh437199(v=vs.85)) and [RIODergisterBuffer](https://docs.microsoft.com/en-us/windows/win32/api/mswsock/nc-mswsock-lpfn_rioderegisterbuffer).

**Comment by isilence** [comment]
Cc @tkp1n, @hedgefund in case you're still working with io_uring. See the message above.

I also think we can close it now unless there are questions left.
