### ISSUE TITLE
question regarding the ordering of random writes to a file

### ISSUE THREAD

**Issue by romange** [axboe/liburing#561]
Hi,

I've read the docs regarding the ordering and I understand that CQEs can come in a different order than SQEs - which is totally understandable for a system-level engine.
 
I would like to double-check regarding ordering for a single file descriptor. Suppose I submit 2 write requests A,B 
for the same range in the same file without IOSQE_IO_LINK. Is it guaranteed that A will be applied before B ?
Is it guaranteed that CQE_A will appear before CQE_B?

**Comment by isilence** [comment]
@romange, no guarantees, can get reshuffled

**Comment by romange** [comment]
So the only way to guarantee serializability is to wait for the completion of A. Thanks, got ya.
