### ISSUE TITLE
Is io_uring and liburing thread safe?

### ISSUE THREAD

**Issue by Galaxy0419** [axboe/liburing#562]
Is io_uring and liburing thread safe? Is it ok to submit requests on multiple threads?

**Comment by axboe** [comment]
Search previous discussions, it's been asked multiple times in the past. Short answer - io_uring yes, liburing no. For the latter, you can safely split submit and complete, but not multiple submitters or multiple completers. A liburing is meant to be per-thread, not shared, that defeats the purpose of the interface.

**Comment by richard0326** [comment]
thx u!

**Comment by richard0326** [comment]
> Search previous discussions, it's been asked multiple times in the past. Short answer - io_uring yes, liburing no. For the latter, you can safely split submit and complete, but not multiple submitters or multiple completers. A liburing is meant to be per-thread, not shared, that defeats the purpose of the interface.

can you link the text?

**Comment by richard0326** [comment]
@axboe

**Comment by YoSTEALTH** [comment]
@richard0326 https://github.com/axboe/liburing/search?q=thread&type=issues
