### ISSUE TITLE
put sqe?

### ISSUE THREAD

**Issue by YoSTEALTH** [axboe/liburing#564]
You know how we can do
``` C

    struct io_uring_sqe *sqe = io_uring_get_sqe(&ring)
```

What if we could do
``` C
    struct io_uring_sqe *sqe = malloc(...)

    // some user function
    io_uring_prep_read(sqe, ...)
    sqe.user_data = 123

    // put
    io_uring_put_sqe(&ring, sqe)

    // let user free the sqe if its possible
    free(sqe)
```

The goal is to have `sqe` prepared ahead of time and pass it into the `ring`. Not sure if the same sqe memory can be used by `io_uring`. This is very handy when you don't have access to `ring` in dynamic coroutine environment.

**Comment by axboe** [comment]
You can do that, but it's of course not very optimal as you're now copying the memory. Maybe that doesn't matter for your use case.

But if you already have an sqe for whatever reason, just do:

```
sqe = io_uring_get_cqe(&ring);

memcpy(sqe, my_sqe_copy, sizeof(*sqe));
```

and that'd work just fine.

**Comment by YoSTEALTH** [comment]
Yes, I do something like, as you mentioned its not optimal.

**Comment by axboe** [comment]
But what you suggest would be the same thing, it's just hidden behind a helper. We can't magically relocate memory, the only way is to copy it.

**Comment by YoSTEALTH** [comment]
O I c

Does `io_uring` internally have a block of memory it reuses it over and over for `sqe` and `cqe`, since you initially set how many entries io_uring will use?

**Comment by axboe** [comment]
Yes, that's how it works. Both sqe and cqe is just an array of the given size, and they get reused once the index wraps. The memory is shared between the app and the kernel, no copy is done between them. Hence what you suggest can work just fine, but it requires you to copy in the shared sqe.

**Comment by YoSTEALTH** [comment]
o I c, that makes sense, external memory would be an conflict for array. For my use-case copying `sqe` is still a better solution then having to pass other data around.

Thanks
