### ISSUE TITLE
split `liburing.h` file

### ISSUE THREAD

**Issue by YoSTEALTH** [axboe/liburing#569]
Would you consider splitting files like `liburing.h` into other files? Like `include/socket.h` for socket related prep function, and `include/file.h` for file related, so on...

I was just looking at `io_uring.c` its over 10k+ lines of code! I am not sure how you manage such a large code file.

Thanks

**Comment by axboe** [comment]
Those are glibc headers, and honestly I have very little interest in splitting part of liburing into glibc. It'd be a maintenance nightmare for me. That said, liburing.h could still be split, but not sure what the point would be?

**Comment by YoSTEALTH** [comment]
> Those are glibc headers, and honestly I have very little interest in splitting part of liburing into glibc.

I see, (not really sure how that works).

> It'd be a maintenance nightmare for me.

Goal is **_not_** to make anything troublesome for you.

> That said, liburing.h could still be split, but not sure what the point would be?

Liburing as a project is starting to grow with more features been added. It would be nice to have it organized (at an early stage) for easy accessibility, before it turns into a 10k+ line of header file.

For example a simple `io_uring_prep_statx` function `< 10` lines of code, by the time I am done with it would have turned into `500+` lines. If we apply the same concept to files, socket, ... it an snowball effect.

But yeah, only public facing `liburing.h` + `include` header files could be split and organized.

**Comment by YoSTEALTH** [comment]
Btw, do you use tab for indentation in your editor? Should use `Indent using space` the code looks like a mess in my editor, even github source viewer looks decent. There might be a easy auto convert tab to space in your editor. Using space will look exactly the same everywhere but tabs are rendered differently.

Sorry for being so anal :(

**Comment by axboe** [comment]
Let's not start that discussion... I use tabs, always have, and always will. And tabs are 8 spaces.

**Comment by YoSTEALTH** [comment]
O I c, Thanks for letting me know `8 spaces` now I can set my editor to that, which fixed that mess :)
