### ISSUE TITLE
Question about SQPOLL

### ISSUE THREAD

**Issue by CarterLi** [axboe/liburing#570]
With SQPOLL, a kernel will use separate thread polling for new SQEs. AFAIK the kernel may pick a new SQE at any time, so how does the kernel ensure a user has finished filling the SQE?

For example:

```cpp
auto sqe = io_uring_get_sqe(&ring); // #1
io_ring_prep_nop(sqe); // #2
sqe->user_data = 123; // #3
```

[#1](https://github.com/axboe/liburing/blob/master/src/include/liburing.h#L919) will update the SQ tail. So at this time, kernel will peek the new SQE at some time, before or after `#2` and `#3`.

Am I correct? Does the kernel has some way to ensure the atomicity?

**Comment by axboe** [comment]
It isn't visible to the kernel until you do io_uring_submit().

**Comment by CarterLi** [comment]
Oh, I missed that.

Does it mean that a user should always do `io_uring_submit` right after filling a SQE for best performance, when using SQPOLL?

**Comment by axboe** [comment]
Using SQPOLL is no different than not using it, the application should basically be written in the same way. But if you don't do io_uring_submit(), the SQPOLL will never see it. The SQPOLL thread may also be currently sleeping, if the timeout has expired, and for that case you do need to enter the kernel to wake it up. io_uring_submit() takes care of that too.

**Comment by CarterLi** [comment]
Got it, thanks.
