### ISSUE TITLE
Question: is `io_uring_cqe_get_data` still valid after file descriptor is closed ?

### ISSUE THREAD

**Issue by boxerab** [axboe/liburing#577]
Suppose I perform a number of writes to a ring, then close the underlying file descriptor.
No more writes are performed. Can I still retrieve all completed buffers
using `io_uring_cqe_get_data`, after the descriptor has been closed ?

**Comment by CarterLi** [comment]
It is valid until io_uring_cqe_seen

**Comment by boxerab** [comment]
great, thanks!!
