### ISSUE TITLE
io_uring: call __audit_uring_exit for dummy contexts

### ISSUE THREAD

**Issue by mahkoh** [axboe/liburing#584]
After porting my wayland compositor to io_uring, I noticed that my logs were getting spammed with the following messages  (tested with 5.17.7 and 5.18.0-rc7):

```
WARNING: CPU: 10 PID: 983 at kernel/auditsc.c:2041 __audit_syscall_entry+0x1>
Modules linked in: vrf wireguard curve25519_x86_64 libchacha20poly1305 chach>
 ipmi_msghandler crypto_user ip_tables x_tables ext4 crc32c_generic crc16 mb>
CPU: 10 PID: 983 Comm: jay Tainted: G        W         5.18.0-rc7-dirty #5 1>
Hardware name: Gigabyte Technology Co., Ltd. B450M DS3H/B450M DS3H-CF, BIOS >
RIP: 0010:__audit_syscall_entry+0x111/0x140
Code: e8 24 69 ff ff 48 8b 34 24 48 8b 54 24 08 85 c0 48 8b 4c 24 10 4c 8b 4>
RSP: 0018:ffffa6e480887de8 EFLAGS: 00010202
RAX: 0000000000000000 RBX: ffff969c92f22400 RCX: 0000000000000001
RDX: 0000000000000001 RSI: 0000000000000007 RDI: ffff969c8fa4c080
RBP: 00000000000001aa R08: 0000000000000001 R09: 0000000000000000
R10: 0000000000000002 R11: 0000000000000001 R12: 00000000000001aa
R13: ffffa6e480887f58 R14: 00000000000001aa R15: 0000000000000000
FS:  00007fefe020f040(0000) GS:ffff96a39ea80000(0000) knlGS:0000000000000000
CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
CR2: 00007fefac429000 CR3: 0000000103674000 CR4: 00000000003506e0
Call Trace:
 <TASK>
 ? get_signal+0x8d/0x990
 syscall_trace_enter.constprop.0+0x121/0x1a0
 do_syscall_64+0x36/0x80
 ? arch_do_signal_or_restart+0x44/0x750
 ? syscall_exit_to_user_mode+0x22/0x40
 ? exit_to_user_mode_prepare+0xd3/0x140
 entry_SYSCALL_64_after_hwframe+0x44/0xae
RIP: 0033:0x7fefe0d0b67d
Code: 5d c3 66 2e 0f 1f 84 00 00 00 00 00 90 f3 0f 1e fa 48 89 f8 48 89 f7 4>
RSP: 002b:00007fff383a6c58 EFLAGS: 00000246 ORIG_RAX: 00000000000001aa
RAX: ffffffffffffffda RBX: 00005595f1c25e00 RCX: 00007fefe0d0b67d
RDX: 0000000000000001 RSI: 0000000000000001 RDI: 0000000000000007
RBP: 00005595f1c1b700 R08: 0000000000000000 R09: 0000000000000000
R10: 0000000000000001 R11: 0000000000000246 R12: 0000000000000001
R13: 0000000000000005 R14: 00005595f1c21f60 R15: 0000000000000001
 </TASK>
---[ end trace 0000000000000000 ]---
audit: unrecoverable error in audit_syscall_entry()
```

After some debugging I've come up with the following patch that removes the problem. Since I haven't done mailing-list development for many years and don't even have a mail client set up, I'm posting the patch below.

----

```patch
From 98448e0cf9465d24347a30cd210a8dadb85cc188 Mon Sep 17 00:00:00 2001
From: Julian Orth <ju.orth@gmail.com>
Date: Mon, 16 May 2022 22:03:04 +0200
Subject: [PATCH] io_uring: call __audit_uring_exit for dummy contexts

Not calling the function for dummy contexts will cause the context to
not be reset. During the next syscall, this will cause an error in
__audit_syscall_entry:

	WARN_ON(context->context != AUDIT_CTX_UNUSED);
	WARN_ON(context->name_count);
	if (context->context != AUDIT_CTX_UNUSED || context->name_count) {
		audit_panic("unrecoverable error in audit_syscall_entry()");
		return;
	}

These problematic dummy contexts are created via the following call
chain:

       exit_to_user_mode_prepare
    -> arch_do_signal_or_restart
    -> get_signal
    -> task_work_run
    -> tctx_task_work
    -> io_req_task_submit
    -> io_issue_sqe
    -> audit_uring_entry

Signed-off-by: Julian Orth <ju.orth@gmail.com>
---
 include/linux/audit.h | 2 +-
 kernel/auditsc.c      | 6 ++++++
 2 files changed, 7 insertions(+), 1 deletion(-)

diff --git a/include/linux/audit.h b/include/linux/audit.h
index d06134ac6245..cece70231138 100644
--- a/include/linux/audit.h
+++ b/include/linux/audit.h
@@ -339,7 +339,7 @@ static inline void audit_uring_entry(u8 op)
 }
 static inline void audit_uring_exit(int success, long code)
 {
-	if (unlikely(!audit_dummy_context()))
+	if (unlikely(audit_context()))
 		__audit_uring_exit(success, code);
 }
 static inline void audit_syscall_entry(int major, unsigned long a0,
diff --git a/kernel/auditsc.c b/kernel/auditsc.c
index ea2ee1181921..f3a2abd6d1a1 100644
--- a/kernel/auditsc.c
+++ b/kernel/auditsc.c
@@ -1959,6 +1959,12 @@ void __audit_uring_exit(int success, long code)
 {
 	struct audit_context *ctx = audit_context();
 
+	if (ctx->dummy) {
+		if (ctx->context != AUDIT_CTX_URING)
+			return;
+		goto out;
+	}
+
 	if (ctx->context == AUDIT_CTX_SYSCALL) {
 		/*
 		 * NOTE: See the note in __audit_uring_entry() about the case
-- 
2.36.1
```

**Comment by axboe** [comment]
Wow, thanks for debugging this! Unfortunately I can't really take audit changes - any way for you to post this to the appropriate mailing lists? Looks like it should be:

linux-audit@redhat.com, linux-kernel@vger.kernel.org, Paul Moore <paul@paul-moore.com>

If this is problematic for whatever reason or doesn't work out, let me know and I can post it on your behalf.

And I'd also add this on top of your signed-off-by line:

```
Fixes: 5bd2182d58e9 ("audit,io_uring,io-wq: add some basic audit support to io_uring")
```

so it gets backported to the right stable kernels.

Finally, I'm curious what the wayland compositor use case, can you tell me more about it?

**Comment by mahkoh** [comment]
>Unfortunately I can't really take audit changes - any way for you to post this to the appropriate mailing lists?

Sure, I'll try to get it to work tomorrow.

>Finally, I'm curious what the wayland compositor use case, can you tell me more about it?

Originally my [compositor](https://github.com/mahkoh/jay/) used a standard epoll event loop. A few days ago I discovered a [vulnerability](https://gitlab.freedesktop.org/wayland/wayland/-/issues/296) in the wayland protocol that allows sandboxed clients to freeze the compositor. Essentially I had to find a way to call `write(2)` in a guaranteed non-blocking way even if another application had access to the same file description and could remove the `O_NONBLOCK` flag at any moment. I found that the easiest way to do this was to use io_uring. Since I didn't see a good reason to use both epoll and io_uring in my application, I afterwards completely replaced epoll by io_uring.

>Oh, and if this is some new opcode you've added, you probably want audit_skip set in the io_op_defs for it. Which will get rid of this warning too, I suspect, and mean you're not wasting cycles on calling into the audit code...

The audit calls happen during `IORING_OP_RECVMSG` and `IORING_OP_SENDMSG`. Though believe this problem in particular happens during `IORING_OP_RECVMSG` if the client sends a message at an inopportune moment. I was getting these warnings roughly once every 10 seconds with one client open.

**Comment by axboe** [comment]
> Sure, I'll try to get it to work tomorrow.

Great!

Thanks for the explanation, that makes sense.

**Comment by mahkoh** [comment]
Merged in https://github.com/torvalds/linux/commit/69e9cd66ae1392437234a63a3a1d60b6655f92ef

**Comment by axboe** [comment]
Thanks!
