### ISSUE TITLE
Support for inotify

### ISSUE THREAD

**Issue by JackyYin** [axboe/liburing#587]
Greeting,

I am currently developing a web server and I have use `liburing` for IO operations like `read`, `write` and `accept`.

One of my feature is to static serve html/css/js files and I will `mmap` those files into memory to save `read` operations, but I need a `develop` mode for web frontend developer to easily change html/css/js files and verify it on browser.

I wonder if there is any way to do `inotify` in io_uring ?

Seems like this IO operation is not currently support by kernel?

https://github.com/torvalds/linux/blob/d7227785e384d4422b3ca189aa5bf19f462337cc/include/uapi/linux/io_uring.h#L144-L195

**Comment by ciconia** [comment]
You can use liburing to read events from the inotify fd.

**Comment by JackyYin** [comment]
> You can use liburing to read events from the inotify fd.

Hi @ciconia ,

Thank you very much!

You're right.

I thought I need some mechanism to be notified when inotify fd is ready before I push read event into the sq, but actually I can just push it once and wait to retrieve it in the cq.
