### ISSUE TITLE
Question about io_uring thread-safety when reading/writing from/to the same file

### ISSUE THREAD

**Issue by topecongiro** [axboe/liburing#594]
I am trying to use liburing to implement a simple page table for a database.

If each thread has its own `io_uring` instance, is it safe to issue read/write against the same file concurrently from multiple threads when there is no overwrap between reads and writes?

**Comment by boxerab** [comment]
@topecongiro you might be interested in my benchmark at #571. I am performing multi-threaded writes to a single file.
As @isilence mentioned, this is safe as long as the writes don't overlap. However, I don't mix reads and writes, so there might
be issues there.

**Comment by topecongiro** [comment]
@isilence @boxerab Thank you!
