### ISSUE TITLE
Error while make

### ISSUE THREAD

**Issue by Nazar2** [axboe/liburing#595]
running make gives:

io_uring_register.c:38:12: error: static declaration of ‘memfd_create’ follows non-static declaration
   38 | static int memfd_create(const char *name, unsigned int flags)
      |            ^~~~~~~~~~~~
In file included from /usr/include/x86_64-linux-gnu/bits/mman-linux.h:113,
                 from /usr/include/x86_64-linux-gnu/bits/mman.h:34,
                 from /usr/include/x86_64-linux-gnu/sys/mman.h:41,
                 from io_uring_register.c:20:
/usr/include/x86_64-linux-gnu/bits/mman-shared.h:50:5: note: previous declaration of ‘memfd_create’ was here
   50 | int memfd_create (const char *__name, unsigned int __flags) __THROW;
      |     ^~~~~~~~~~~~
make[1]: *** [Makefile:220: io_uring_register.t] Error 1
make[1]: Leaving directory '/home/liburing/test'
make: *** [Makefile:11: all] Error 2

**Comment by axboe** [comment]
Please attach config.log and include some details on what distro, version, arch etc you are on.
