### ISSUE TITLE
Why linux-header-generic included for dependencies in conan repository?

### ISSUE THREAD

**Issue by newbiediver** [axboe/liburing#599]
I installed ubuntu 22.04. I use liburing through conan. But it has linux-header-generic dependency. So there are many warning like this when I build. I think linux kernel has to depend on each users. Can you remove linux-header-generic dependency in conan?

/home/newbiediver/.conan/data/linux-headers-generic/5.13.9/_/_/package/c0519e2d9702ec12d057bb15adb7a02baaf18107/include/linux/fs.h:297: warning: "RWF_APPEND" redefined
  297 | #define RWF_APPEND      ((__kernel_rwf_t)0x00000010)
      | 
In file included from /usr/include/x86_64-linux-gnu/sys/uio.h:179,
                 from syscall.c:9:
/usr/include/x86_64-linux-gnu/bits/uio-ext.h:49: note: this is the location of the previous definition
   49 | #define RWF_APPEND      0x00000010 /* per-IO O_APPEND.  */
      | 
In file included from include/liburing/io_uring.h:11,
                 from syscall.c:11:
/home/newbiediver/.conan/data/linux-headers-generic/5.13.9/_/_/package/c0519e2d9702ec12d057bb15adb7a02baaf18107/include/linux/fs.h:285: warning: "RWF_HIPRI" redefined
  285 | #define RWF_HIPRI       ((__kernel_rwf_t)0x00000001)

**Comment by isilence** [comment]
we have nothing to do with conan and/or its packaging and dependencies, you'd need to write to them

**Comment by axboe** [comment]
If it has a kernel header dependency, someone messed up the packaging. liburing is totally standalone, it doesn't have any kernel header dependencies. Agree with Pavel that this looks like a packaging issue. Closing it for now, feel free to re-open if needed.
