### ISSUE TITLE
Question: using a "nop" from a different thread as abort logic?

### ISSUE THREAD

**Issue by chris-se** [axboe/liburing#600]
I've started looking into io_uring more and I really like it. I do have a quick question though to see if something I'm doing makes sense (because it appears to work perfectly), but I'm not completely sure that my logic is correct and I'd appreciate some feedback:

(I'm using liburing 2.1 for this.)

What I have is a thread that uses io_uring_wait_cqe() in a loop (similar to the web server example in the docs) to perform network operations. And I want io_uring_wait_cqe() to block while nothing is going on to save CPU cycles. However, I do want to have the option of a separate thread being able to notify the networking thread to terminate. I could of course use the timeout-based wait functions and regularly check if we were asked to terminate, but that seems inelegant.

The solution I came up with was to queue a NOP from the thread that wants to initiate the terminate operation in the ring, which will cause the networking thread to return from io_uring_wait_cqe() and then be able to detect that a termination was requested and exit.

In order to avoid any thread safety issues, I've added a mutex around the entire submission process (i.e. everything between io_uring_get_sqe() and io_uring_submit() is guarded by a mutex), which is normally only taken from within the networking thread (hence being uncontended in most cases), but in the event of a termination request from another thread that thread will also take it.

I've boiled this down to a very simple example that starts a thread that waits for a single event on the ring, and that queues a 10s timeout by default. If "wait" is supplied as the CLI parameter to that example program, the main thread does nothing else, otherwise the main thread will queue a NOP on the ring to cause a more immediate termination. (Obviously in the real application there are going to be real operations instead of just a timeout, and there won't be this slew of global variables.)

https://gist.github.com/chris-se/949e5ccc9dd38b78f11f924d6ab60749

This appears to work extremely well from my tests, but I want to be sure I'm not doing something here that contains a rare stochastic bug that I haven't run into so far. So I'd appreciate if I could get some feedback to whether what I'm doing is safe.

Also, even if this is perfectly safe, but there's an even better way to achieve this, I'm all ears.

Many thanks in advance!

**Comment by isilence** [comment]
Take a look at `IORING_OP_MSG_RING`, it allows to post a completion to another io_uring instance

**Comment by chris-se** [comment]
Wow, thanks for the _really_ quick reply!

It took a quick look at it, and it does look promising, but then I'd need yet another ring just to post to the original ring, which I don't have in this case. (I could create one, but it seems a bit excessive to have an entire ring just for sending a single termination signal.) There isn't by any chance a direct syscall that `IORING_OP_MSG_RING` corresponds to (like `IORING_OP_RECVMSG` corresponds to `recvmsg()`)?

Furthermore, this appears to have landed only in the most recent kernels, and I do want to support kernels that are at least a bit older, so even if I can use this, I'd still need a fallback for kernels without this. (The fallback for even older kernels in my code is a standard socket syscall based implementation, which is definitely going to be slower than io_uring.)

**Comment by chris-se** [comment]
Many thanks for the suggestion, I've now tried the eventfd together with a read request and that works like a charm, and is indeed a much better idea than what I had in mind. Thanks!
