### ISSUE TITLE
io_uring_queue_init return -38(-ENOSYS) on almalinux 9

### ISSUE THREAD

**Issue by rikkei-minh** [axboe/liburing#611]
Dear liburing team.
Thank you for your excellent library.

I tried to use the liburing recently on alamalinux 9 but can not init the queues.

# Environtment:
OS: AlmaLinux 9
Kernel: 5.14.0-70.13.1.el9_0.x86_64

# liburing build:
I got the latest one on master at 2022-June-14th from github.
I built the liburing source and everything were fine.

# The error
I tried to initialize the queue by using following code
```
struct io_uring ring;
ret = io_uring_queue_init(256, &ring, 0);
```
but It always return -38(-ENOSYS) which means [Function not implemented].
So, I think may be the kernel 5.14 and the latest liburing are not worked together well?

Could you take a look about this problem?
Thank you for your kind support.

Best regards.

**Comment by ammarfaizi2** [comment]
Hello,

On Mon, Jun 20, 2022 at 2:03 PM thinminh-la-s ***@***.***> wrote:
> I tried to initialize the queue by using following code
>
> struct io_uring ring;
> ret = io_uring_queue_init(256, &ring, 0);
>
> but It always return -38(-ENOSYS) which means [Function not implemented].
> So, I think may be the kernel 5.14 and the latest liburing are not worked together well?

Linux 5.14 does have io_uring support.

If you get -ENOSYS when invoking the `io_uring_*` syscalls, that means
your kernel is not built with io_uring support. To enable io_uring
support, you need to set `CONFIG_IO_URING=y` when compiling your
kernel.

-- 
Ammar Faizi

**Comment by rikkei-minh** [comment]
Thank you so much for the speedy reply.
I confirmed on AlmaLinux 9, and the kernel was built without io_uring.
I also confirmed with AlmaLinux 9 development team and received below reference:
https://bugzilla.redhat.com/show_bug.cgi?id=1946936

> FYI, we still do not plan to support io_uring in the RHEL 9.0 kernel.  The goal is to enable support in an update release.

So may be we should wait for AlmaLinux 9.1 in order to use io_uring.

Best regards.
