### ISSUE TITLE
io_uring_cqe.res

### ISSUE THREAD

**Issue by YoSTEALTH** [axboe/liburing#62]
Think there is wrong with "io_uring_cqe.res" When i call something like

# read-1
cqe = io_uring_cqe()
... io_uring_prep_readv
cqe.res  # will output say "5"

# read-2
cqe = io_uring_cqe()
... io_uring_prep_readv
cqe.res  # will output again the same value as read-1 "5"

while read-2 content length/buffer size is totally different!

not sure whats going on.

**Comment by axboe** [comment]
Did you advance the CQ ring after reading event 1? I'm guessing not, which means you'll keep seeing the same CQE. Use io_uring_cq_advance() or io_uring_cqe_seen(), whichever is more appropriate for your use case.

**Comment by YoSTEALTH** [comment]
I do not have access to those functions.

This does pass https://github.com/YoSTEALTH/Liburing/blob/master/test/file_test.py#L21 but then again the cqe.res content would be wrong (maybe not in this case since both `bytearray(5)` are same)

**Comment by axboe** [comment]
Well, you need to advance the CQ ring somehow when you consume events. If the head remains the same, you'll keep reading the same entry.

**Comment by YoSTEALTH** [comment]
when i try to write a wrapper for `io_uring_cqe_seen` https://github.com/YoSTEALTH/Liburing/blob/master/liburing/prep.py#L145 it leads me to having to write a wrapper for everything in https://github.com/axboe/liburing/blob/master/src/include/liburing/barrier.h

I am not a C/Assembly coder.

**Comment by YoSTEALTH** [comment]
I was using the wrong tool for the job! I have moved the whole project into using cffi. Now i can access all the liburing functions, no limits, back in action :)

**Comment by axboe** [comment]
Perfect!
