### ISSUE TITLE
2.2: build fails

### ISSUE THREAD

**Issue by kloczek** [axboe/liburing#620]
```console
+ ./configure --includedir=/usr/include --libdevdir=/usr/lib64 --libdir=/usr/lib64 --mandir=/usr/share/man --prefix=/usr
prefix                        /usr
includedir                    /usr/include
libdir                        /usr/lib64
libdevdir                     /usr/lib64
relativelibdir
mandir                        /usr/share/man
datadir                       /usr/share
stringop_overflow             yes
array_bounds                  yes
__kernel_rwf_t                yes
__kernel_timespec             yes
open_how                      yes
statx                         yes
glibc_statx                   yes
C++                           no
has_ucontext                  yes
has_memfd_create              no
liburing_nolibc               no
CC                            /usr/bin/gcc
CXX                           /usr/bin/g++
+ /usr/bin/make -O -j48 V=1 VERBOSE=1
make[1]: Entering directory '/home/tkloczko/rpmbuild/BUILD/liburing-liburing-2.2/src'
/usr/bin/gcc -D_GNU_SOURCE -Iinclude/ -include ../config-host.h -MT "syscall.ol" -MMD -MP -MF "syscall.ol.d" -O2 -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fdata-sections -ffunction-sections -flto=auto -flto-partition=none -Wno-unused-parameter -Wno-sign-compare -DLIBURING_INTERNAL -c -o syscall.ol syscall.c
make[1]: Leaving directory '/home/tkloczko/rpmbuild/BUILD/liburing-liburing-2.2/src'

[..]

make[1]: Leaving directory '/home/tkloczko/rpmbuild/BUILD/liburing-liburing-2.2/src'
make[1]: Entering directory '/home/tkloczko/rpmbuild/BUILD/liburing-liburing-2.2/test'
     CC io_uring_register.t
io_uring_register.c:38:12: error: static declaration of ‘memfd_create’ follows non-static declaration
   38 | static int memfd_create(const char *name, unsigned int flags)
      |            ^~~~~~~~~~~~
In file included from /usr/include/bits/mman-linux.h:117,
                 from /usr/include/bits/mman.h:34,
                 from /usr/include/sys/mman.h:41,
                 from io_uring_register.c:20:
/usr/include/bits/mman-shared.h:51:5: note: previous declaration of ‘memfd_create’ with type ‘int(const char *, unsigned int)’
   51 | int memfd_create (const char *__name, unsigned int __flags) __THROW;
      |     ^~~~~~~~~~~~
make[1]: *** [Makefile:215: io_uring_register.t] Error 1
make[1]: Leaving directory '/home/tkloczko/rpmbuild/BUILD/liburing-liburing-2.2/test'
make: *** [Makefile:11: all] Error 2
```

**Comment by axboe** [comment]
Please include some details on what you are building on, we don't have crystal balls.

**Comment by kloczek** [comment]
Linux x86/64
gcc 12.1.1

Please let me kniow if you need other details.

**Comment by ammarfaizi2** [comment]
Can you show the output of `cat config.log`?

**Comment by axboe** [comment]
I need distro details. Can you attach your config.log as well?

**Comment by kloczek** [comment]
```console
[tkloczko@devel-g2v liburing-liburing-2.2]$ cat config.log
Compiling test case stringop_overflow
/usr/bin/gcc -D_GNU_SOURCE -include config-host.h -Werror -Wstringop-overflow=0 -o /tmp/tmp.uRR8DOdQn0/liburing-conf.exe /tmp/tmp.uRR8DOdQn0/liburing-conf.c -Wl,-z,relro -Wl,--as-needed -Wl,--gc-sections -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -flto=auto -flto-partition=none -fuse-linker-plugin -Wl,--build-id=sha1
Compiling test case array_bounds
/usr/bin/gcc -D_GNU_SOURCE -include config-host.h -Werror -Warray-bounds=0 -o /tmp/tmp.uRR8DOdQn0/liburing-conf.exe /tmp/tmp.uRR8DOdQn0/liburing-conf.c -Wl,-z,relro -Wl,--as-needed -Wl,--gc-sections -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -flto=auto -flto-partition=none -fuse-linker-plugin -Wl,--build-id=sha1
Compiling test case __kernel_rwf_t
/usr/bin/gcc -D_GNU_SOURCE -include config-host.h -o /tmp/tmp.uRR8DOdQn0/liburing-conf.exe /tmp/tmp.uRR8DOdQn0/liburing-conf.c -Wl,-z,relro -Wl,--as-needed -Wl,--gc-sections -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -flto=auto -flto-partition=none -fuse-linker-plugin -Wl,--build-id=sha1
Compiling test case __kernel_timespec
/usr/bin/gcc -D_GNU_SOURCE -include config-host.h -o /tmp/tmp.uRR8DOdQn0/liburing-conf.exe /tmp/tmp.uRR8DOdQn0/liburing-conf.c -Wl,-z,relro -Wl,--as-needed -Wl,--gc-sections -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -flto=auto -flto-partition=none -fuse-linker-plugin -Wl,--build-id=sha1
Compiling test case open_how
/usr/bin/gcc -D_GNU_SOURCE -include config-host.h -o /tmp/tmp.uRR8DOdQn0/liburing-conf.exe /tmp/tmp.uRR8DOdQn0/liburing-conf.c -Wl,-z,relro -Wl,--as-needed -Wl,--gc-sections -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -flto=auto -flto-partition=none -fuse-linker-plugin -Wl,--build-id=sha1
Compiling test case statx
/usr/bin/gcc -D_GNU_SOURCE -include config-host.h -o /tmp/tmp.uRR8DOdQn0/liburing-conf.exe /tmp/tmp.uRR8DOdQn0/liburing-conf.c -Wl,-z,relro -Wl,--as-needed -Wl,--gc-sections -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -flto=auto -flto-partition=none -fuse-linker-plugin -Wl,--build-id=sha1
Compiling test case glibc_statx
/usr/bin/gcc -D_GNU_SOURCE -include config-host.h -o /tmp/tmp.uRR8DOdQn0/liburing-conf.exe /tmp/tmp.uRR8DOdQn0/liburing-conf.c -Wl,-z,relro -Wl,--as-needed -Wl,--gc-sections -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -flto=auto -flto-partition=none -fuse-linker-plugin -Wl,--build-id=sha1
Compiling test case C++
/usr/bin/g++ -D_GNU_SOURCE -include config-host.h -o /tmp/tmp.uRR8DOdQn0/liburing-conf.exe /tmp/tmp.uRR8DOdQn0/liburing-conf-2.cpp -Wl,-z,relro -Wl,--as-needed -Wl,--gc-sections -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -flto=auto -flto-partition=none -fuse-linker-plugin -Wl,--build-id=sha1
/usr/bin/ld: /tmp/ccIP0Lnq.lto.o: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: failed to set dynamic section sizes: bad value
collect2: error: ld returned 1 exit status
Compiling test case has_ucontext
/usr/bin/gcc -D_GNU_SOURCE -include config-host.h -o /tmp/tmp.uRR8DOdQn0/liburing-conf.exe /tmp/tmp.uRR8DOdQn0/liburing-conf.c -Wl,-z,relro -Wl,--as-needed -Wl,--gc-sections -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -flto=auto -flto-partition=none -fuse-linker-plugin -Wl,--build-id=sha1
Compiling test case has_memfd_create
/usr/bin/gcc -D_GNU_SOURCE -include config-host.h -Werror=implicit-function-declaration -o /tmp/tmp.uRR8DOdQn0/liburing-conf.exe /tmp/tmp.uRR8DOdQn0/liburing-conf.c -Wl,-z,relro -Wl,--as-needed -Wl,--gc-sections -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -flto=auto -flto-partition=none -fuse-linker-plugin -Wl,--build-id=sha1
/usr/bin/ld: /tmp/cccrTTkp.lto.o: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: failed to set dynamic section sizes: bad value
collect2: error: ld returned 1 exit status
[tkloczko@devel-g2v liburing-liburing-2.2]$
```

**Comment by kloczek** [comment]
gcc is from fedora rawhide.
liburing build does not depent on anything else than gcc/g++, glibc and make.

**Comment by axboe** [comment]
> liburing build dos not depens on anything else than gcc/g++, glibc and make.

I think I know the project... But the distro generally tells us what glibc etc that are being used, and you didn't include that in the original report (nor the followup comment).

**Comment by kloczek** [comment]
Again: I;m using gcc 12.1.1 from fedora rawhide and I've already mentioned that one time.

**Comment by kloczek** [comment]
/usr/include/bits/mman-shared.h is from glibc-devel from fedora rawhide as well.

**Comment by axboe** [comment]
Not sure if I'm not being clear hear, I said your _original_ report didn't include any information like that, and your followup only had arch+compiler. We have what we need now.

Please read what I actually write before you reply, or nobody is going to have a good time here.

**Comment by axboe** [comment]
I'll take a look tomorrow unless @ammarfaizi2 beats me to it.

**Comment by ammarfaizi2** [comment]
There are two failures here:

The first is C++ check:
> ```
> Compiling test case C++
> /usr/bin/g++ -D_GNU_SOURCE -include config-host.h -o /tmp/tmp.uRR8DOdQn0/liburing-conf.exe /tmp/tmp.uRR8DOdQn0/liburing-conf-2.cpp -Wl,-z,relro -Wl,--as-needed -Wl,--gc-sections -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -flto=auto -flto-partition=none -fuse-linker-plugin -Wl,--build-id=sha1
> /usr/bin/ld: /tmp/ccIP0Lnq.lto.o: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
> /usr/bin/ld: failed to set dynamic section sizes: bad value
> collect2: error: ld returned 1 exit status
> ```

The second is the `memfd_create()` check:
> ```
> Compiling test case has_memfd_create
> /usr/bin/gcc -D_GNU_SOURCE -include config-host.h -Werror=implicit-function-declaration -o /tmp/tmp.uRR8DOdQn0/liburing-conf.exe /tmp/tmp.uRR8DOdQn0/liburing-conf.c -Wl,-z,relro -Wl,--as-needed -Wl,--gc-sections -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -flto=auto -flto-partition=none -fuse-linker-plugin -Wl,--build-id=sha1
> /usr/bin/ld: /tmp/cccrTTkp.lto.o: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
> /usr/bin/ld: failed to set dynamic section sizes: bad value
> collect2: error: ld returned 1 exit status
> ```

It is not that your environment doesn't support C++ and memfd_create().
But this:
```
 relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object
```

That `.rodata.str1.1` comes from string literal in:
```c++
std::cout << "Test";
```

and

```c
int memfd = memfd_create("test", 0);
```
---

I don't know what is going on here, but it seems you have a customized
`LDFLAGS` which I don't much understand what it does:

```
-Wl,-z,relro -Wl,--as-needed -Wl,--gc-sections -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -flto=auto -flto-partition=none -fuse-linker-plugin -Wl,--build-id=sha1
```

@kloczek can you try to omit the `LDFLAGS` and see if it's a cure?

Try to run this:
```
env LDFLAGS="" ./configure;
env LDFLAGS="" make -j8;
```

**Comment by kloczek** [comment]
Do you want to say that your custom makefiles cannot handle LTO? 🤔 
Maybe it ids time to move to meson, cmake or even GNU autotools?

**Comment by ammarfaizi2** [comment]
> Do you want to say that your custom makefiles cannot handle LTO?

Our configure script doesn't provide an option to compile with LTO, but
if you specify a proper `CFLAGS`, `CXXFLAGS` and `LDFLAGS` to use LTO,
compiling liburing with LTO that way should be fine.

> Maybe it ids time to move to meson, cmake or even GNU autotools?

There were a few attempts to add CMake and Meson support, but none of
them have landed upstream. I admit that our old-fashioned configure
script is not that comprehensive. But I don't think it's a mandatory
requirement to have CMake/Meson at the moment. Let's see if someone can
actually bring it to upstream.

**Comment by kloczek** [comment]
>  Our configure script doesn't provide an option to compile with LTO, but
if you specify a proper CFLAGS, CXXFLAGS and LDFLAGS to use LTO,
compiling liburing with LTO that way should be fine.

Maybe it is not obviouse but to compile any library usung meson, cake or GNU tools none of those tools needs to know anything about LTO.
All thise toollings are transparent for env variables like CC, CXX, CFLAGS, CXXFLAGS, LDFLAGS, LD, AR, NM and RUNLIB. Even raw make uses and passes those variables. Whout you've implemted is just kinfd "renonvent the wheel"
Really .. even GNU autotools can do that.
If you want I can try to prepare build framework using auto tools (autoscan + few adjustment should be doable in 2-3h)

**Comment by eli-schwartz** [comment]
The LDFLAGS, minus whatever is in `-specs=/usr/lib/rpm/redhat/redhat-hardened-ld`, work fine. This is NOT an lto issue.

**Comment by eli-schwartz** [comment]
Quite frankly, it sounds like some kind of mixed-up situation in that custom spec file that is setting up PIE, but not completely. The compiler error suggests adding `-fPIE` to fix the problem, so maybe just try that?

**Comment by ammarfaizi2** [comment]
> If you want I can try to prepare build framework using auto tools (autoscan + few adjustment should be doable in 2-3h)

I personally don't want to and still prefer to use the current build
method. Let's see Jens and others if they would like to have it.

**Comment by ammarfaizi2** [comment]
> The LDFLAGS, minus whatever is in `-specs=/usr/lib/rpm/redhat/redhat-hardened-ld`, work fine. This is NOT an lto issue.

If so, it's not liburing's problem then. Please just fix the compiler
and linker flags being used.

**Comment by axboe** [comment]
Not interested in changing the build system, just fix the weird setup on that box.

**Comment by kloczek** [comment]
> /usr/lib/rpm/redhat/redhat-hardened-ld

```consolw
[tkloczko@devel-g2v SPECS]$ cat /usr/lib/rpm/redhat/redhat-hardened-ld
*self_spec:
+ %{!static:%{!shared:%{!r:-pie}}}
```
This forces to link everything as PIE code.

**Comment by eli-schwartz** [comment]
Linking everything as PIE code obviously will not work if you don't compile it as PIE-compatible code. So I will reiterate my earlier advice:



> Quite frankly, it sounds like some kind of mixed-up situation in that custom spec file that is setting up PIE, but not completely. The compiler error suggests adding `-fPIE` to fix the problem, so maybe just try that?

**Comment by kloczek** [comment]
> Linking everything as PIE code obviously will not work if you don't compile it as PIE-compatible code. So I will reiterate my earlier advice:

This is done by CFLAGS spec file
```console
[tkloczko@devel-g2v SPECS]$ cat /usr/lib/rpm/redhat/redhat-hardened-cc1
*cc1_options:
+ %{!r:%{!fpie:%{!fPIE:%{!fpic:%{!fPIC:%{!fno-pic:-fPIE}}}}}}
```

**Comment by eli-schwartz** [comment]
Actually hold on.

The issue here is more complex than it has to be -- or should be.

This ./configure script uses `$LDFLAGS` in order to run test compiles... but it doesn't use `$CFLAGS`.

I'm... not entirely sure what to think about that, but there's a really good chance that @kloczek was doing exactly what he should have been doing, and putting -fPIE into the build... as part of $CFLAGS.

But this configure script is buggy and drops CFLAGS all over the floor :) and just uses LDFLAGS.

This is absolutely a bug in liburing, and the ticket should be re-opened. Regardless of how little information was actually reported about the build process (this would have been so much easier if more information was originally provided).

**Comment by kloczek** [comment]
Just in case this set of flags is working in case of few thousands other libraries if that could be kind of problem it would be firtst time case ever.

**Comment by kloczek** [comment]
> This ./configure script uses `$LDFLAGS` in order to run test compiles... but it doesn't use `$CFLAGS`.

If you are not going to switch to one of the well working build frameworks you will be spending less and less time on liburing code and more and more time on reinventing what was developed last +2 decadest on GNU auto tools, cmake and meson.
I would recommend meson however even GNU autotools wold be better allowing to focus on liburing actual code development.

**Comment by axboe** [comment]
I'm not adverse to switching to eg meson, see:

https://github.com/axboe/liburing/pull/297

But let's not pretend that maintaining the current build system takes any effort at all, because it does not. I spend roughly zero time on it in general, this one being an outlier.

**Comment by kloczek** [comment]
Issue is that what you ae developing is consumed by eople like me .. packagers.
You may try to pretensd that it is not like that but reality is different.

Look on for exwmple zstd which is possible to build custom make files, cmake and meson.
Just allow people maintain for example meson in your tree.

**Comment by kloczek** [comment]
Builsd description for single library + few test units it is not rocket science.

**Comment by axboe** [comment]
I maintain and develop a ton of stuff. Doing two build systems when I only would need to do one is extra work, extra work I don't have time for. If this was all I was doing, sure, but there's a lot more.

Going to close this one for comments, it's counterproductive and your input isn't useful, and this has wasted way too much time already.
