### ISSUE TITLE
The effect of Linux -O3 on io_uring throughput and latency

### ISSUE THREAD

**Issue by LifeIsStrange** [axboe/liburing#625]
Hi @axboe :) 
Recently there was talks on LKML about making it easier to build Linux with GCC -O3 optimization flag (which is, contrary to popular belief perfectly safe, unlike say -ffastmath)
The great Michael Larabel recently benchmarked it, and while the benchmarks do not show performance improvements for an average program, one could argue the average program isn't bottlenecked by Kernel CPU time.
However the ones that do might see very significant performance increases for free, especially programs that are heavy on IO syscalls. 
PostgreSQL see 11% improvement! And
Stress-NG context switching benchmark see a crazy 269% performance improvement.

Unfortunately Michael has not benchmarked O3 on an io_uring benchmark. It might be that the improvement is mild but it is also a possibility that it would help unlock even more performance than current io_uring.
https://www.phoronix.com/vr.php?view=31250

As such I thought you might be interested in benchmarking it.

**Comment by axboe** [comment]
For my peak IOPS runs that I've done in the past, I do use -O3 for the kernel. The branch is updated by now, but my perf-wip branch includes a patch that enables that and has so for a long time:

https://git.kernel.dk/cgit/linux-block/commit/?h=perf-wip&id=a2c35cfa21d60051881820fbcf4f5c9089eefe48

I saw nice wins from that too.

I'd be fine adding -O3 for liburing, we already do so for fio and hence the t/io_uring tool I use for peak IOPS testing too. That's been the case for many years in that repo.

**Comment by axboe** [comment]
https://git.kernel.dk/cgit/liburing/

**Comment by JonKohler** [comment]
Was there any hints from that work @axboe on what optimizations actually made a difference, generating better code? I wonder if there were hints that could then be applied to the actual source code to be smarter?

**Comment by axboe** [comment]
I didn't investigate, I did post on some gcc 11.2 vs 12 vs clang, but more from a curiosity POV in what worked the best for my test cases.

I'm sure there are hints and code changes that could be made that would make O2 as good, but that was a much more lengthy project that I didn't have the time to undertake.
