### ISSUE TITLE
Issue: IORING_OP_RECV returns -EFAULT constantly

### ISSUE THREAD

**Issue by CarterLi** [axboe/liburing#63]
```c
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <arpa/inet.h>
#include <sys/types.h>
#include <sys/socket.h>

#include <liburing.h>

int main() {
    char buffer[1024];
    struct io_uring ring;
    struct sockaddr_in saddr;
    struct io_uring_sqe *sqe;
    struct io_uring_cqe *cqe;
    int sockfd = 0, clientfd = 0, ret;

    io_uring_queue_init(32, &ring, 0);

    sockfd = socket(AF_INET, SOCK_STREAM, 0);
    if (sockfd < 0) {
        perror("socket");
        goto err;
    }

    saddr = (struct sockaddr_in) {
        .sin_family = AF_INET,
        .sin_addr = {
            .s_addr = htonl(INADDR_ANY),
        },
        .sin_port = htons(12345),
    };

    ret = bind(sockfd, (struct sockaddr *)&saddr, sizeof(saddr));
    if (ret < 0) {
        perror("bind");
        goto err;
    }

    ret = listen(sockfd, 32);
    if (ret < 0) {
        perror("listen");
        goto err;
    }

    clientfd = accept(sockfd, NULL, NULL);
    if (clientfd < 0) {
        perror("accept");
        goto err;
    }

    sqe = io_uring_get_sqe(&ring);
    io_uring_prep_recv(sqe, clientfd, buffer, sizeof(buffer), 0);

    ret = io_uring_submit_and_wait(&ring, 1);
    if (ret <= 0) {
        perror("io_uring_submit_and_wait");
        goto err;
    }

    io_uring_peek_cqe(&ring, &cqe);

    if (cqe->res < 0) {
        printf("recv failed: %d\n", cqe->res);
        goto err;
    }

err:
    io_uring_queue_exit(&ring);
    close(clientfd);
    close(sockfd);
}
```

```shell
$ gcc recv.c -o recv -luring
$ ./recv # On another terminal: curl -v localhost:12345
recv failed: -14
$ uname -a # https://kernel.ubuntu.com/~kernel-ppa/mainline/daily/2020-01-31/
Linux carter-virtual-machine 5.5.0-999-generic #202001302109 SMP Fri Jan 31 02:15:05 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by CarterLi** [comment]
IORING_OP_READ and IORING_OP_RECVMSG work fine in this case

**Comment by axboe** [comment]
Thanks, let me take a look!

**Comment by axboe** [comment]
Can you try with this:

https://git.kernel.dk/cgit/linux-block/commit/?h=io_uring-5.6&id=7a62b6c78bd82f764218335acaeb01f6f5f4d5df

Would be awesome if you could turn this into a self contained test case, perhaps something that forks a thread and uses IORING_OP_RECV and IORING_OP_SEND to pass a buffer between them to verify functionality.

**Comment by CarterLi** [comment]
> Can you try with this:
> 
> [git.kernel.dk/cgit/linux-block/commit/?h=io_uring-5.6&id=7a62b6c78bd82f764218335acaeb01f6f5f4d5df](https://git.kernel.dk/cgit/linux-block/commit/?h=io_uring-5.6&id=7a62b6c78bd82f764218335acaeb01f6f5f4d5df)

I'm sorry but I can't test it before it's merged into mainline.

> Would be awesome if you could turn this into a self contained test case, perhaps something that forks a thread and uses IORING_OP_RECV and IORING_OP_SEND to pass a buffer between them to verify functionality.

I'll have a try.

**Comment by axboe** [comment]
> I'm sorry but I can't test it before it's merged into mainline.

How do we fix this situation? It's a bit problematic for feature requests etc, where I implement something but you can't test it before it's in mainline. I'd really like things tested up front, so I know I'm not pushing untested bits to mainline.

**Comment by CarterLi** [comment]
> > I'm sorry but I can't test it before it's merged into mainline.
> 
> How do we fix this situation? It's a bit problematic for feature requests etc, where I implement something but you can't test it before it's in mainline. I'd really like things tested up front, so I know I'm not pushing untested bits to mainline.

I have no idea how to build (and install) the kernel. For now I'm testing it using [Ubuntu's daily build](https://kernel.ubuntu.com/~kernel-ppa/mainline/daily/current/), but it only targets mainline.

If you could provide daily build for whatever distribution ( Ubuntu and Archlinux are preferred ), I'm happy to test it.

**Comment by axboe** [comment]
Gotcha, I can see how that would be a problem. Since I'll have to do this manually (for now, at least), I can't do daily builds. But one-offs should be easy enough to do, hopefully.
