### ISSUE TITLE
[examples/io_uring-udp] queue_init: Invalid argument

### ISSUE THREAD

**Issue by glenn-wang** [axboe/liburing#637]
hi @DylanZA,  the udp server demo is very good, but when running the demo, get `queue_init: Invalid argument`

```
./io_uring-udp -p 10001 -b 1024 
```

https://github.com/axboe/liburing/blob/master/examples/io_uring-udp.c#L101

**Comment by DylanZA** [comment]
What kernel are you running? It requires a pretty bleeding edge one

This demo relies on multishot recvmsg, which was only merged into Linus' tree last yesterday (or it has been in for-next for the last few weeks)

**Comment by glenn-wang** [comment]
> What kernel are you running? It requires a pretty bleeding edge one
> 
> This demo relies on multishot recvmsg, which was only merged into Linus' tree last yesterday (or it has been in for-next for the last few weeks)

Fedora34
Linux f34 5.17.4-100.fc34.x86_64 #1 SMP PREEMPT Wed Apr 20 14:41:56 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by axboe** [comment]
@DylanZA We should probably turn that queue init -EINVAL into an error print on how it requires a newer kernel to run.

**Comment by axboe** [comment]
And I think the queue_init probably isn't the only part, as the example would init correctly on eg 5.19 but still won't run as mshot isn't available until 5.20 (or Linus's current git tree, post 5.19).

**Comment by DylanZA** [comment]
yes makes sense. I'll send a patch

**Comment by DylanZA** [comment]
fyi: https://lore.kernel.org/io-uring/20220803155741.3668818-1-dylany@fb.com/T/#u
