### ISSUE TITLE
[Suggestion] Fix GCC-12 `-fanalyzer` warnings

### ISSUE THREAD

**Issue by vt-alt** [axboe/liburing#638]
`liburing` is working with network data thus should be considered security sensitive. With that assumption static analyzing could be a valuable option.
GCC-12 have improved `-fanalyzer` support (in compare to previous versions which was more experimental).

Pls try to compile with `-fanalyzer` in your CI. Currently there are such warnings:

```
232c93d07b74.c:149:57: warning: use of uninitialized value 'buff[i_58]' [CWE-457] [-Wanalyzer-use-of-uninitialized-value]
eventfd-disable.c:93:25: warning: use of uninitialized value 'ptr' [CWE-457] [-Wanalyzer-use-of-uninitialized-value]
io_uring-cp.c:147:28: warning: leak of '<unknown>' [CWE-401] [-Wanalyzer-malloc-leak]
link-cp.c:131:25: warning: leak of '<unknown>' [CWE-401] [-Wanalyzer-malloc-leak]
recv-msgall.c:174:17: warning: leak of 'buf_25' [CWE-401] [-Wanalyzer-malloc-leak]
recv-msgall-stream.c:290:17: warning: leak of 'buf_29' [CWE-401] [-Wanalyzer-malloc-leak]
../src/include/liburing.h:302:9: warning: leak of '<unknown>' [CWE-401] [-Wanalyzer-malloc-leak]
```
(Besides numerous `-Wanalyzer-null-dereference -Wanalyzer-unsafe-call-within-signal-handler -Wanalyzer-possible-null-dereference` which I don't even list.)

**Comment by axboe** [comment]
Any test/ leak is irrelevant, these are just test apps. io_uring-cp.c I'm not sure is a real leak, as the buffers are freed when the IO completes. So I'd say we just ignore these for now, unless they are in the core bits of liburing.

**Comment by vt-alt** [comment]
IC. JFYI, there is `-Wanalyzer-null-dereference` results which is not in the tests:
```
setup.c:183:43: warning: dereference of NULL '0B' [CWE-476] [-Wanalyzer-null-dereference]
../src/include/liburing.h:301:21: warning: dereference of NULL '0B' [CWE-476] [-Wanalyzer-null-dereference]
../src/include/liburing.h:301:21: warning: dereference of NULL 'sqe_13(D)' [CWE-476] [-Wanalyzer-null-dereference]
../src/setup.c:183:43: warning: dereference of NULL '0B' [CWE-476] [-Wanalyzer-null-dereference]
```

**Comment by ammarfaizi2** [comment]
I honestly don't understand where the NULL-pointer-dereferences are.

> setup.c:183:43: warning: dereference of NULL '0B' [CWE-476] [-Wanalyzer-null-dereference]

setup.c:
https://github.com/axboe/liburing/blob/2757d61fa222739f77b014810894b9ccea79d7f3/src/setup.c#L176-L186

You will obviously NULL-pointer-dereference at `ring->flags` if the
argument to be passed in is NULL. But it's a misuse of the API, so I
don't think it's a valid bug report.

> ../src/include/liburing.h:301:21: warning: dereference of NULL '0B' [CWE-476] [-Wanalyzer-null-dereference]
> ../src/include/liburing.h:301:21: warning: dereference of NULL 'sqe_13(D)' [CWE-476] [-Wanalyzer-null-dereference]

The same thing with the liburing.h:
https://github.com/axboe/liburing/blob/2757d61fa222739f77b014810894b9ccea79d7f3/src/include/liburing.h#L299-L304

**Comment by vt-alt** [comment]
@ammarfaizi2 You are right. To fix this or not (or at least adding `assert`) is a philosophical question and author's choice. For example, `free(3)` allows it's argument to be `NULL`.

**Comment by vt-alt** [comment]
BTW, GCC supports ` __attribute__((nonnull ...))` which can be used to mark that (that would benefic API error checking and static analyzers).
https://gcc.gnu.org/onlinedocs/gcc/Common-Function-Attributes.html#index-nonnull-function-attribute
