### ISSUE TITLE
man/io_uring.7 page says cqe flags isn't used yet

### ISSUE THREAD

**Issue by FrankReh** [axboe/liburing#654]

**Comment by alviroiskandar** [comment]
What's the problem?

**Comment by FrankReh** [comment]
The io_uring.h already defines four bits for cqe->flags, and in one mode, even carries a buffer id. That becomes clear when one reads enough of the liburing man pages or looks at the header file itself but the io_uring man page has outdated information about this flags field still being unused. I wouldn't propose to know how much detail should be added but I can say it is confusing and probably wrong the way it is written now.

```
The flags field could carry request-specific metadata in the future, but is currently unused.
```

**Comment by axboe** [comment]
Yes, that is out of date. There are a few flags there now, just only documented in the man pages where they are relevant. Should all be in io_uring.7 as well, though.
