### ISSUE TITLE
io_uring_prep_socket_direct_alloc man missing

### ISSUE THREAD

**Issue by FrankReh** [axboe/liburing#655]
There is no man page for io_uring_prep_socket_direct_alloc() but it appears in the header.

https://github.com/axboe/liburing/blob/2fadaf2ca667fc62f2275e21c229411d0834ec4b/src/include/liburing.h#L1039

It was added with 77f3bffb3fabdf19513b675b680baedef4df92d9. The man page for io_uring_prep_socket was added with 214d53c7c5a167082921bf400599896951e91a22.

The io_uring_prep_socket man page does go into detail how any free direct socket index can be specified however. Just thought it odd that the API was in the header file but not in the man pages.

**Comment by axboe** [comment]
Good point, I'll get that added.
