### ISSUE TITLE
man page possible typo re: IOSQE_ASYNC

### ISSUE THREAD

**Issue by FrankReh** [axboe/liburing#658]
Mostly about a typo that should be easily fixable by the author who remembers the intent.

https://github.com/axboe/liburing/blob/2a8498e90ba83125d8c305ce8c41bd7cfe5d580b/man/io_uring_sqe_set_flags.3#L40

Was the intent to say it *should* be used sporadically? Or perhaps "it should not be used without an understanding of what can make a kernel thread block"?

But I have to admit, the description of *non-blocking* in the io_uring_enter.2 and io_uring_sqe_set_flags.3 leaves me wondering what *isn't* blocking. Perhaps reading data from a page already cached or writing to a page already marked dirty? Wouldn't almost all net operations be blocking?

A little guidance in the form of a manage or a io_uring blog some day would be very interesting and useful.

**Comment by ilikdoge** [comment]
I do not believe this is a typo as I did notice lower performance or massive increases in CPU% when using IOSQE_ASYNC with socket reads and writes (atleast on my 5.19 kernel).

I'm not an expert, but maybe I can help clear up what is blocking and what isn't.
Blocking I/O (atleast in the kernel) is anything that needs to wait for another device (e.g disk or network card) to complete (finish reading, or receive a message). Socket I/O does not need to block if there's already data waiting to be read or free memory for the kernel to hold on to the message you want to send. Other operations like cancel, poll, and timeout are all non-blocking.

In my testing, issuing a read request on a file that isn't cached is immediately async punted, but reading (2 GB) from a file that is in cache "blocked" on io_uring_submit for 500 ms and immediately completed. I did encounter some slightly weird behavior with O_DIRECT where submit blocked for  a whole 1700 ms! before the cqe was posted 300 ms later.

I'm just another user of io_uring but I hope I was able to answer your question :)

**Comment by FrankReh** [comment]
> as I did notice lower performance or massive increases in CPU

Thanks for the help. First question, you *did* notice lower performance or did *not*?

**Comment by ilikdoge** [comment]
I did. A simple multiplex udp server sending 700k packets/sec took 100% cpu
The same server with IOSQE_ASYNC sent 1100k packets/sec and took 600% cpu

**Comment by axboe** [comment]
It is a typo, it should say "it should be used sporadically". Which isn't great phrasing either, so maybe we just need to completely rephrase it.

Setting IOSQE_ASYNC will force a thread offload. So it can improve performance in some situations, but efficiency will be lower. It would generally be better to have multiple threads in userspace instead that handle requests, each with their own ring.

**Comment by ilikdoge** [comment]
Oh, I misunderstood the word sporadically. Thought it meant using the flag without second thought or something of the sort.

**Comment by axboe** [comment]
The phrasing was just awful, hopefully it's more understandable now.

**Comment by FrankReh** [comment]
@axboe Thank you. The phrasing makes sense now.

> Setting IOSQE_ASYNC will force a thread offload. So it can improve performance in some situations, but efficiency will be lower. It would generally be better to have multiple threads in userspace instead that handle requests, each with their own ring.

But this observation is the most interesting piece of information I have read about io_uring in quite some time. Is there anything published that goes into more details? I've begun trying to help with a Rust async framework called tokio-uring that is based on the idea of an io_uring managed by a single user thread, taking advantage of the async abilities of the rust language and the tokio framework in particular (other async rust frameworks have also supported io_uring as you are probably already aware).

 And the high level idea was always that multiple threads could each have their own io_uring, but that's just a general description. There is nothing I've found to help a user decide what is good to group together in one ring and what is better to put into its own ring. For those not so versed in what the kernel is doing, it is easy to think of the kernel as a magic black box that does everything efficiently in O(1) time - so the more that is pushed from user space to kernel space, the better.

Closing this issue but you'll probably be asked for more information and on your opinions on the tradeoffs of single ring vs multiple rings from multiple threads in the future.

**Comment by FrankReh** [comment]
> In my testing, issuing a read request on a file that isn't cached is immediately async punted, but reading (2 GB) from a file that is in cache "blocked" on io_uring_submit for 500 ms and immediately completed. I did encounter some slightly weird behavior with O_DIRECT where submit blocked for a whole 1700 ms! before the cqe was posted 300 ms later.

That's interesting too. Makes me wonder if the user community could benefit from a separate wiki somewhere with ideas and results. The async nature of the rings is a great new field for the kernel and there will be many lessons to be learned over the years I'm thinking.
