### ISSUE TITLE
missing manpage descriptions for register_sync_cancel function and 

### ISSUE THREAD

**Issue by FrankReh** [axboe/liburing#659]
man/io_uring_register.2 lists other opcodes, but not 

And other liburing functions generally get a man entry, but the io_uring_register_sync_cancel function doesn't have one.

The test/sync-cancel.c does show how it can be used however although fully understanding what the possible side effects are and expected return values is a challenge because the functions performing the tests have many options to them, making them highly reusable.

Also noticed the register_sync_cancel structure uses flags that are named IORING_ASYNC_... Not a problem, but perhaps the documentation could call them out too.

Sorry for complaining about missing manage stuff and not offering PRs. Getting a manpage right for this excellent driver is beyond me.

And thanks for offering a sync version of getting operations canceled. Certainly makes things handier in some cleanup cases.

**Comment by axboe** [comment]
Don't be sorry, I appreciate getting notifications about missing man pages, or man pages that need updating. Sometimes these get missed when adding new functionality!

**Comment by axboe** [comment]
Pushed a man page. For the flags, these are the same ones that the prep_cancel helpers take. The new man page references that one too.
