### ISSUE TITLE
Behavior of IORING_SETUP_COOP_TASKRUN

### ISSUE THREAD

**Issue by ilikdoge** [axboe/liburing#662]
I have a question reguarding the behavior of the co-op task run flag used in setup. From what I understand after reading the manpages, the flag delays processing of completion events until a later call to io_uring_enter (or some other transition).

However, from my testing (linux 5.19, pop os 22.04), it seems like my application (which is a single threaded application and does not use IOSQE_ASYNC) is still interrupted to process completions.

I'm wondering if this is a bug that may be already fixed in the 6.0 kernel?

Testing details:

Queue up a lot of hrtimers (8,388,608 to be precise) and have them all expire at the same time.
Then, a busy loop is ran and there is a massive time difference in between two iterations of the loop when the timers expire and the process is interrupted.
This time difference is about 2 seconds which is roughly how much it took the kernel to dequeue all 8 million timers, confirmed by an increase in the sys time in getrusage(2).
The function used to measure time is clock_gettime(CLOCK_MONOTONIC) which should not enter the kernel

**Comment by axboe** [comment]
COOP_TASKRUN doesn't always defer it until cqring_wait, only the 6.1 flag DEFER_TASKRUN will do that. If you transition into the kernel or end up being rescheduled, then it will still get run. What COOP_TASKRUN prevents is a forced reschedule IPI if task_work gets added.

**Comment by ilikdoge** [comment]
I see, that makes sense. Does DEFER_TASKRUN delay the issue of the sqe aswell or only the completion?

Thanks :)

**Comment by ilikdoge** [comment]
Seems like the kernel code for 6.1 isn't out yet

**Comment by DylanZA** [comment]
> I see, that makes sense. Does DEFER_TASKRUN delay the issue of the sqe aswell or only the completion?

It will issue the sqe at submission time, but if it blocks or needs to poll an fd, then the actual work (eg copying data out of a socket) will happen at the next GET_EVENTS

> Seems like the kernel code for 6.1 isn't out yet

yeah - merge window is not open yet either
