### ISSUE TITLE
why do the prep_multishot_accept operations take a sockaddr?

### ISSUE THREAD

**Issue by FrankReh** [axboe/liburing#672]
The io_uring_prep_multishot_accept and  io_uring_prep_multishot_accept_direct liburing calls take a struct sockaddr * and a socklen_t, but all the tests pass in NULL for these. And it might not make sense to expect the kernel to fill in the remote address when a socket is accepted because it will be doing so potentially often and quickly, with no chance for the user land app to read the address per accepted stream. Does the kernel ignore these fields when the IORING_ACCEPT_MULTISHOT ioprio bit is set?  Should there be something in the manpage saying those parameters are obsolete or deprecated and should/must be zero?

**Comment by axboe** [comment]
That's a good point, we should probably have had the multishot variant EINVAL if sockaddr is set. There are perhaps cases where  you could still use it appropriately - for example, if you know that a new connection cannot come in until you've dispatched of the current one. But it should be clarified in the man page.

**Comment by axboe** [comment]
Added a blurb in the referenced commit, let me know what you think.

**Comment by FrankReh** [comment]
Looks good. It even points out that the fields don't have to be set, an interesting way of saying passing 0 is okay. Thanks.

It is interesting how there are at least two levels of learning possible - not counting the mailing list as a third. One from reading the man pages, and another from reading the test code that comes with the liburing source. And too bad for C that it never became standard for manpages to have links to source code. I guess in the 70s, there weren't a lot of unit test cases being written at Bell Labs.
