### ISSUE TITLE
man/io_uring_prep_accept.3 mistakes around 'direct'

### ISSUE THREAD

**Issue by FrankReh** [axboe/liburing#673]
1. The manpage is for liburing functions in section 3, yet the second DESCRIPTION paragraph's second part reads like it belongs to a section 2 or 7 manpage - not being relevant to the use of the liburing API and definitely causing some confusion to a first time reader. https://github.com/axboe/liburing/blob/1c469ee303d0f458a6b039c9483865b3af248400/man/io_uring_prep_accept.3#L53-L64 Specifically, from the sentence beginning "To do so,". Also this paragraph reads like it is relevant to both forms of *direct* call but the *file_index* parameter only exists in the first form, for the single shot form - as it wouldn't make sense for the multishot form anyway. So perhaps the first part of the paragraph could be "For the first direct descriptor accept request,".
2. In  p3, the manpage mentions being able to use IORING_OP_ACCEPT_DIRECT to check for availability of the direct feature but such an OP has never been introduced so  probably leftover from an older idea. Some type of feature flag to check for availability would be nice. Or just a reminder what other IORING_OP was introduced in the same kernel release cycle that could be checked instead.
3. In p4, it again refers to "a direct descriptor accept request" and the *file_index* argument, but that argument only appears in the first such request. But this would be a good place to mention why the second form doesn't take a *file_index* and how the first form could also pick from the file table automatically by setting *file_index* to IORING_FILE_INDEX_ALLOC.
4. In p6, https://github.com/axboe/liburing/blob/1c469ee303d0f458a6b039c9483865b3af248400/man/io_uring_prep_accept.3#L117-L125 this seems left over from an idea when the second form would take a *file_index* so it is mostly just confusing. But it does help in understanding the io_uring interface itself, so part of this might go into a lower level manpage instead.
5. As there are already 5 liburing commands that have *direct* variations, accept, close, open, openat2, and socket, perhaps one manpage dedicated to the does and don'ts of direct socket identifiers would be useful. Part of the page could be written from the liburing use perspective, and part could be written for the lower level io_uring interface (or this second part could go in the io_uring.7 manpage.
6. As all these liburing functions take an sqe and a sockfd, they are all candidates for taking a direct fd themselves if the sqe has been set with the IOSQE_FIXED_FILE bit. Sometime, it would be nice if there were a standard way each of the liburing manpages to which this applies had a common section that referred to some general description page, like a direct_file_index.3 page.

I can offer a PR for the general problems outlined above for this manpage but I wouldn't want to guess how the lower level information should be moved to other pages or other new pages.

**Comment by axboe** [comment]
Are you going to send a PR for this as mentioned?
