### ISSUE TITLE
buf_ring details

### ISSUE THREAD

**Issue by FrankReh** [axboe/liburing#674]
There should probably be a statement about how a pbuf_ring can't be completely full because then it looks completely empty. The buf_ring advance can't add the entire size of the ring for example.

And when a buf_ring is unregistered, what happens to operations that were inflight for the same buf_ring?

**Comment by axboe** [comment]
The pbuf rings work just like the SQ/CQ rings - the masking is done when indexing, not when the head/tail is incremented. Which means you can tell the difference between totally full (abs(tail - head) == size) and empty (tail == head).

**Comment by FrankReh** [comment]
I think I was looking at it from the kernel's perspective that it wouldn't even have seen the tail move if a ring went from empty to completely full, but if it is rewriting the index or length field, I guess it can tell. Sorry for the noise.
