### ISSUE TITLE
allocating buf_ring

### ISSUE THREAD

**Issue by FrankReh** [axboe/liburing#675]
I have a question or two about allocating the memory for the buf_ring. Mostly about whether mmap is needed as it is used in the UDP example but not, I believe, in the tests/ test cases.

The io_uring_buf_ring is a union so the ring tail is overlaid with the first ring entry recv field. That's nice and I'll admit took me a minute to figure out, when first looking at the size calculations. So the buf ring entries start at the beginning of the page and the address of the tail is based off the beginning of the same page.

The io_uring-udp.c example uses mmap to allocate the memory and the size calculation seems straightforward enough - one ring entry and one buffer for each preallocated buffer (I think I understand the memory backing the buffers does not have to be contiguous with the buf_ring but because I saw this code for buf-rings first, I thought so for a while), the only requirement is the memory backing io_uring_buf_ring needs to be page aligned
https://github.com/axboe/liburing/blob/1c469ee303d0f458a6b039c9483865b3af248400/examples/io_uring-udp.c#L55-L57

But the test cases under tests/ use posix_memalign, assuring page alignment, do not use mmap, and use sizes like 4096 and in one case a size of buf entries bumped up to next page size. I'm guessing because posix_memalign assigns memory in multiple of pages anyway
https://github.com/axboe/liburing/blob/1c469ee303d0f458a6b039c9483865b3af248400/test/buf-ring.c#L280-L295
4096, the page size, is just a convenient const to use in these examples.

So is it correct to say the buf_ring memory does not have to be mmap'ed memory? Could the UDP example have used posix_memalign also or is there something else having to do with network packets requiring the entries or the buffers be mmaped?

**Comment by axboe** [comment]
Yes, the buf_ring does not need to be allocated with mmap'ed, it can use any allocator. The only requirement is the alignment.
