### ISSUE TITLE
Bug in io_uring_get_sqe?

### ISSUE THREAD

**Issue by twissel** [axboe/liburing#68]
io_uring_get_sqe sometimes fails to find vacant sqe when SQPOLL is enabled, but there is free space.Running following test case always produces `io_uring_get_sqe failed, space left : 8` :
```
#include <errno.h>
#include <stdio.h>
#include <unistd.h>
#include <stdlib.h>
#include <string.h>
#include <fcntl.h>
#include <sys/types.h>
#include <sys/poll.h>
#include "liburing.h"

#define NUM_ENTRIES 8
int setup_and_run();

int main(int argc, char *argv[])
{
    for (int j = 0; j < 100; j++)
    {
        int ret = setup_and_run();
        if (ret)
        {
            return ret;
        }
    }
    return 0;
}

int setup_and_run()
{
    struct io_uring_sqe *sqe;
    struct io_uring_cqe *cqe;
    struct io_uring_params p;
    struct io_uring ring;
    int ret, data;

    memset(&p, 0, sizeof(p));
    p.flags = IORING_SETUP_SQPOLL;
    ret = io_uring_queue_init_params(NUM_ENTRIES, &ring, &p);
    if (ret)
    {
        fprintf(stderr, "ring create failed: %d\n", ret);
        return 1;
    }

    if (p.sq_entries != NUM_ENTRIES)
    {
        fprintf(stderr, "ring create failed, wanted %d sq entries, got: %d entries\n", NUM_ENTRIES, ret);
        return 1;
    }

    for (int i = 0; i < NUM_ENTRIES; i++)
    {
        sqe = io_uring_get_sqe(&ring);
        if (!sqe)
        {
            fprintf(stderr, "io_uring_get_sqe failed\n");
            return ret;
        }

        io_uring_prep_nop(sqe);
        io_uring_sqe_set_data(sqe, (void *)(unsigned long)42);
    }

    ret = io_uring_submit(&ring);

    if (!ret)
    {
        fprintf(stderr, "io_uring_submit railed");
        return -1;
    }

    ret = io_uring_wait_cqe(&ring, &cqe);
    if (ret == 0)
    {
        data = (unsigned long)io_uring_cqe_get_data(cqe);
        if (data != 42)
        {
            fprintf(stderr, "invalid data: %d\n", data);
            return data;
        }

        int space_left = io_uring_sq_space_left(&ring);
        sqe = io_uring_get_sqe(&ring);
        if (sqe == NULL)
        {
            fprintf(stderr, "io_uring_get_sqe failed, space left: %d\n", space_left);
            return 1;
        }
    }
    else
    {
        fprintf(stderr, "io_uring_wait_cqe failed : %d\n", ret);
        return ret;
    }

    io_uring_queue_exit(&ring);
    return 0;
}
```

**Comment by axboe** [comment]
I don't think the bug is in the get sqe, it's in the space_ready helper. I just pushed a potential fix:

https://git.kernel.dk/cgit/liburing/commit/?id=dd15d761d0ec015661f8c779904c7198704437b1

Can you try and pull the latest and re-check?

**Comment by twissel** [comment]
I will try tomorrow, but how is that possible - we waited for some cqe to finish, that means kernel thread saw and submitted  sqes we prepared, and than we got null from io_uring_get_sqe? Or i'm missing something?

**Comment by axboe** [comment]
The way the submission works for sqthread is that it'll read entries from the sq ring, submit them, then update the sq ring when done submitting. Since you're doing nop's, the submission will actually complete them. This means that you can have a state where the sqe's aren't consumed yet in terms of the sqthread updating the sq ring, yet the cqe's have been posted. I suspect this is what you're seeing.

**Comment by twissel** [comment]
The same applies for other operations,  right?  I'm actually was doing reads(buffered), and perhaps data already was cached, so sq thread can complete them immediately.

**Comment by axboe** [comment]
Yes, it'll apply to any operation that can complete before all submissions are done. If the data is cached, that would indeed be the case.

There are ways we could make this a bit better - for instance, cap the number of SQEs that are submitted in one go, as io_sq_thread() updates the SQ ring for each batch. Right now the batch is however many are available in the ring when it gets woken (or notices them). The only potential issue with that is that we don't want do potentially cap the submission count, in case we have links in there.

**Comment by twissel** [comment]
Got it, many thanks for explanations.
