### ISSUE TITLE
Adding support for `select`.

### ISSUE THREAD

**Issue by ioquatix** [axboe/liburing#680]
I hesitated to create this issues but figured it can't hurt to ask.

In existing programming languages (e.g. Ruby, Python), it's common to encounter code using `select(2)`.

It is non-trivial to rewrite the semantics of select into multiple poll operations. 

One option which I've been thinking about trying is creating a nested `epoll` with all the file descriptors and registering the single file descriptor into the `io_uring`.

If it would be easy, I feel like this would be incredibly helpful to support some kind of `select` operation in `io_uring`.

I personally think `select(2)` is messy... hence my reservation regarding this issue. So, I'll have a go implementing it with `epoll`.

**Comment by axboe** [comment]
io_uring already has support for OP_POLL_ADD, through which you could have poll(2) like behavior. select(2) has been effectively deprecated for decades at this point.

**Comment by ioquatix** [comment]
While I agree, a ton of software still uses `select(2)` and I'm stuck in between trying to modernise legacy systems. The best I can do right now is kick select off to a background thread, but it would be awesome if we could do something better. `epoll` is probably not a bad idea - make a temporary `epoll` (or maybe cache it) and then add all the file descriptors to it.

**Comment by axboe** [comment]
Sure, lots of old things will use select(2), my point is that OP_POLL_ADD will do anything that does and more. Similarly to how you could just wrap select(2) in a poll(2) call basically.

I'm going to close this one, we're not going to add support for select specifically.

**Comment by ioquatix** [comment]
Thanks, okay, I'l take a look at `OP_POLL_ADD`.

**Comment by ioquatix** [comment]
So, just to clarify, because `select` takes multiple fds in a single operation, are you recommending the best way to emulate `select(2)` is to use multiple `OP_POLL_ADD`? Then, when one or more of the fds is ready, I should remove all the poll entries?

**Comment by axboe** [comment]
Definitely trickier for multiple fds, and if the use case is only to act on a single fd when it is ready, then that's not a good match. Usually the use case is "I want to know when I can send/recv on ANY of these fds", in which case yeah you'd want a POLL_ADD for each. But that doesn't mean that you'd be discarding N-1 poll requests once one completes, you'd act on them whenever a notification came in.

**Comment by ioquatix** [comment]
For the purpose of select, after the call returns, we have to remove all the associated state, unfortunately. It's a bad interface... but it is what it is and it's what I have to deal with.
