### ISSUE TITLE
Possible bug: io_uring_submit_and_wait_timeout

### ISSUE THREAD

**Issue by ilikdoge** [axboe/liburing#684]
In the man page, it says io_uring_submit_and_wait_timeout returns the number of submitted entries on success,
but it actually performs an io_uring_wait_cqe_nr which returns 0 on success

Solution:
Either the man page should be changed to reflect this or this is a bug

**Comment by axboe** [comment]
The man page should get corrected. Would you mind sending a patch?

**Comment by ilikdoge** [comment]
Sure, I'll get to it tomorrow

**Comment by axboe** [comment]
Yeah I think you're right in this case.

**Comment by metze-samba** [comment]
I guess we would need a new function that gets a pointer to a variable to store the number of submitted sqe's

**Comment by axboe** [comment]
I fixed this, see current master. Not a huge fan of changing the return value there, but:

1) It was always documented as having the right return value, but something went amiss at some point
2) It's not really possible to use without it in a sane way

Due to both of those, I made the decision that simply fixing it up was the best way forward.

**Comment by metze-samba** [comment]
I haven't test it yet, but doesn't it mean we'll almost never get -ETIME? Because we now always return the number
of submitted sqe's?

It means I now need to check for cqe == NULL (or io_uring_cq_ready() == 0) in order to notice the timeout condition?

**Comment by ilikdoge** [comment]
Seems like it, but checking for cqe == NULL doesn't really mean -ETIME, it can also mean -EINTR
Regardless, as long as it's not a fatal error it shouldn't really matter, just that there are currently no cqes available

**Comment by ilikdoge** [comment]
None of the other submit functions return -ETIME or -EINTR if there was atleast 1 submitted, this just makes it the same behavior as the other submit functions
