### ISSUE TITLE
man/io_uring_register_buf_ring.3 misses fact that entries are limited to 32768

### ISSUE THREAD

**Issue by FrankReh** [axboe/liburing#686]
The io_uring_buf_reg struct declares a __u32 for ring_entries

but the io_uring_buf_ring struct declares a __u16 for the tail.

The ring_entries argument can't allow values larger than 16 bits or else the tail size would fall short of being able to represent it.

The man page says the restriction on the field value is that it is a power of 2. It could add that it must also be representable in 16 bits or less.

I tried once with a value of 100,000 and got the invalid argument response, as if I was running the register command on an older kernel.

I can't think of a concise way to phrase the change so I won't propose a PR for this one.

**Comment by DylanZA** [comment]
The maximum value is actually 15 bits (32768) to allow for rollover calculation. 

What do you think of this change:

```
diff --git a/man/io_uring_register_buf_ring.3 b/man/io_uring_register_buf_ring.3
index f75063fc9f2c..357a3fb39a0c 100644
--- a/man/io_uring_register_buf_ring.3
+++ b/man/io_uring_register_buf_ring.3
@@ -55,7 +55,8 @@ or similar. The size of the ring is the product of
 and the size of
 .IR "struct io_uring_buf" .
 .I ring_entries
-is the desired size of the ring, and must be a power-of-2 in size.
+is the desired size of the ring, and must be a power-of-2 in size. The maximum size 
+allowed is 2^15 (32768).
 .I bgid
 is the buffer group ID associated with this ring. SQEs that select a buffer
 has a buffer group associated with them in their

```

**Comment by FrankReh** [comment]
Oh. Makes sense. And looks good. Could the invalid argument return code be mentioned if the value is exceeded?

**Comment by FrankReh** [comment]
Changed the title to avoid confusing anyone looking at issue titles in the future.
