### ISSUE TITLE
interesting buf_ring exhaustion behavior

### ISSUE THREAD

**Issue by FrankReh** [axboe/liburing#688]
Something interesting happens when read with a buf_ring is performed when the buf_ring is exhausted vs when it is not yet exhausted but becomes exhausted afterwards.

The read returns immediately with errno 105, "no buffers", if the buf_ring is empty when the read operation hits the kernel but does not if the read hits the kernel before the buf_ring was exhausted but there was no data yet to be read. In the latter case, the read sits there, waiting for data to arrive before something needs to be done.

The buf_ring does what it is designed to do - allow more connections to be opened and be in a blocked read state than there are buffers in the ring, and even than there are entries in the ring itself. This allows tens of thousands of connections to be managed (maybe hundreds of thousands?) with a single ring_buf of 32768 buffers or less (could be much less).

It seems a little odd that if the read hits the kernel while the buffer is exhausted, the error is returned right away .. even though there may not be data in the channel to read (I tested with TCP channels), while if the read hits the kernel before the buffer is exhausted, the read won't return the "no buffers" indication when the buf_ring becomes exhausted by another operation later on, unless then data appears in the channel for the connection and a buffer really would be handy to have. If the read hits the kernel while there are buffers but no data, it waits, then the buf_ring may become exhausted by other operations, then have buffers re-added to the buf_ring, then data becomes available to read, and the read returns normally with the data in a buffer.

It's not wrong, but it was a little confusing .. but I think I actually like this behavior. It might be worth documenting in the man page about buffer groups if this is by design. Or you could say it is by design but there is no need to highlight this and cause confusion.

Once the caller knows about this, they can program to sleep and try the read again or they can decide to close the connection. And connections that had already been established are not affected unless the caller wants to do something about their number also.

**Comment by axboe** [comment]
It's a bit of a chicken and egg problem - depending on request settings, we need a buffer to attempt the operation first. This means we do need to select a buffer before we attempt to receive, and hence you will hit the ```-ENOBUFS``` even if there isn't data to receive. You could get around this by setting ```IORING_RECVSEND_POLL_FIRST``` in the request. If that is set, then we don't attempt a receive upfront, we always base this decision on poll. This should mean that we don't pick a buffer until we actually need one, side stepping the issue you are facing.

**Comment by FrankReh** [comment]
That explains it nicely. Thanks. I'll give that IORING_RECVSEND_POLL_FIRST bit a try.
