### ISSUE TITLE
Am I always expected to call `io_uring_sqe_set_data`?

### ISSUE THREAD

**Issue by ioquatix** [axboe/liburing#690]
I just found a complicated to diagnose bug:

```
		io_uring_prep_nop(sqe);
		// If you don't set this line, the SQE will eventually be recycled and have valid user data which can cause odd behaviour:
		io_uring_sqe_set_data(sqe, NULL);
```

After enough SQEs were reused, I eventually ended up in situations where the user data would be valid and cause odd behaviour.

It might be nice to make it really clear in the documentation exactly what's expected after calling `io_uring_get_sqe` if it doesn't set `user_data` to 0 by default.

**Comment by axboe** [comment]
If data hasn't been set, then no expectations can be had about what it should contain. The ```io_uring_cqe_get_data``` man page says:

```
This requires that user_data has been set earlier with the function io_uring_sqe_set_data(3)
or io_uring_sqe_set_data64(3).
```

We can certainly expand on that, but it is mentioned in the appropriate function man pages.

**Comment by ioquatix** [comment]
I think we should clarify this in the `io_uring_get_sqe` page if possible, as this is a bug which is easy to make and hard to catch. Maybe the respective pages where it's likely to be forgotten, e.g. `io_uring_prep_nop` could also mention it or show it in an example.

**Comment by axboe** [comment]
I think it makes the most sense to document in the man page for the functions you'd use to retrieve this data. But adding it to io_uring_get_sqe() certainly makes sense, I can add a blurb there. Don't think we should put it in the prep handlers, then it would have to go into all of them. NOP isn't really special in that regard.

I'm a little surprised that this is a thing to be honest. If you always get the data from a cqe and rely on it, how would it not make sense that you would always have to set it too? What would be in there if you didn't set it?

Do you want to send a patch for io_uring_get_sqe(3)?

**Comment by ioquatix** [comment]
It didn't cross my mind that I'd need to set a user data for `io_uring_prep_nop(sqe);` since I was not expecting to do anything with the operation or respond to it in any way. I already skip CQEs when the user data is `NULL`/`0`. I think we should specifically call it out on this page because this is the actual source of my bug and likely to be an issue for other people who might assume the same thing. However, I don't have a strong opinion, I'm mostly just concerned with ensuring engineers who are building things with `io_uring` have all the information to build robust code. This was a very hard issue to track down - took 2 days.

**Comment by axboe** [comment]
I think you're too focused on the specific issue that you had with NOP, I don't think this is a general problem.

Do I think that we should ensure that we highlight that if you always retrieve data out of the cqe that it should be set? Certainly! And I do think we have that in a bunch of spots already. We can add it to io_uring_get_sqe() as well, as I do think it makes sense as a note in there. But I don't want to add it to the nop prep page specifically.

**Comment by ioquatix** [comment]
Let me ask you a question: Is there any reason to set user data for a nop?

**Comment by axboe** [comment]
> Thanks, I like the change you made to the manual page.

Great!

>  but in the case of io_uring_prep_nop and io_uring_prep_cancel, the most common use case would be to ignore the result.

I still don't think this is generally true. It may be in your case, but there are definitely cases where you'd set user_data for ANY request, regardless of whether it's a nop, or a cancelation. Particularly the latter, there are plenty of cases where you'd want to know which exact cancelation request this was.

> e.g. https://github.com/axboe/liburing/blob/master/test/link.c#L191 is this correct?

Are we talking about the same thing here? That particular case is using the request _result_, not the user_data. So now I'm somewhat confused as to how this relates to this particular discussion?

I don't want to add it to all the prep functions, I think it's just noise. More documentation is not necessarily better documentation. The most important spots to talk about user_data is the set and get part of them, and those were already covered. The get_sqe also has it now, I really don't think it adds anything of interest to pepper it throughout the prep handlers.

> Are there any other fields we need to clear? It might even be a good idea for io_uring_get_sqe to clear any fields.

As a general rule, any field that is reserved for a command type must be zeroed, and obviously any field that is an active component of the request must be set to something valid. This is what the prep handlers do. This is _very_ different from user_data, which the kernel doesn't care about at all. The only thing the kernel does for that is pass back the same value for the completion, allowing the application to tie a completion to a specific submission. The kernel doesn't use or interpret this field at all.

**Comment by ioquatix** [comment]
Yeah, that all makes sense.

My point about the `link.c` is that `user_data` is undefined and never specified. If someone copies this code, they may not realise that. In a system where `user_data` is used in other operations, this code will eventually blow up.

My main point is this:

- Code that use `io_uring_prep_nop` and `io_uring_prep_cancel` may not correctly handle the case when `user_data` was already set from a previous operation, because users usually don't want to do anything in this case.
- This can be a hard to diagnose problem because it only manifests when a `nop` lands on a SQE with user_data which triggers an issue. In my case, it was causing deadlocks because a user_data pointer contained a fiber and it was being resumed unexpectedly and causing invalid flow control.
- This problem is the worst kind of issue - one which in tests probably looks okay (because on a decent size SQ, the SQE is unlikely to be recycled during the test). I had tests but my default queue length is big enough that it was never triggered. I only noticed it when doing load testing.

For the sake of other engineers who may run into this issue, being clear with documentation and examples is absolutely critical and can save a lot of time.

I don't have anything else to add, except anything we can do here to make it easier for code to do the correct thing will make people who use and adopt liburing happier because they will have a good experience with robust and reliable systems.

**Comment by axboe** [comment]
The point is that if you read user_data from the CQE, you better have set user_data in the SQE. That's irrespective of what request is being used, if it's nop, cancel, or anything else. The various use cases in the file you referenced do adhere to that - the cases that read the cqe user_data, have also set it. Since the referenced one doesn't do anything with user_data at completion time, it doesn't bother setting it at submission time.

And with that, we've probably beat this dead horse adequately :-)

**Comment by ioquatix** [comment]
I know but basically I was an idiot and didn't realise that and just assumed `nop` wouldn't do anything =) and I'm trying to stop other people like me from making the same mistake.

**Comment by ciconia** [comment]
Thanks @ioquatix for the heads up! This really cleared up a few situations where I couldn't understand what was happening.

**Comment by ioquatix** [comment]
@ciconia thanks for letting us know that this was also a bug for you, as it supports my hypothesis that this is a tricky edge case of this library.
