### ISSUE TITLE
io_uring: io_submit_state_end does not flush overflow cqes

### ISSUE THREAD

**Issue by ilikdoge** [axboe/liburing#705]
I've noticed this in the 5.19 kernel, that for small cqrings that cause overflow, that:
- advancing the cqring
- submitting some sqes
- enough sqes from the comp_list (that were just submitted) fill up the cqring
- cq overflows never flushed
and the cqes in the cq_overflow_list are starved
This is true even if IORING_ENTER_GETEVENTS is set

I haven't tested this on the Linux 6.1 kernel but I have checked the source code (sync'd with master on github's remote) for any changes (that I could notice without spending too much time) and I believe it may still be affected.

I'm not sure if this is intentional, but a solution for userspace on older kernels would to be call getevents without submitting, then call again to submit.

**Comment by ilikdoge** [comment]
This isn't a liburing issue but I am not familiar with the linux kernel mailing list

**Comment by DylanZA** [comment]
If I understand correctly, on every loop you are submitting more which produces enough CQEs to fill the CQ ring, and so the overflows never get into the CQ ring?
If so this is a little bit expected, in that overflows are very much the slow path. Ideally your application should never have overflows.

Periodic get_events, if io_uring_cq_has_overflow() returns true would fix this, or alternatively if you change the completion loop to peek again after advancing the pointer.

By the way - there is a new change (in 6.1) that will always overflow CQEs while there are any, which is useful to protect CQE ordering, but will in actuality probably slow down this case as all CQEs will go via the overflow ring: https://github.com/torvalds/linux/commit/aa1df3a360a0c50e0f0086a785d75c2785c29967

> Also it would be nice (though I don't know the side effects) if instead of alloc'ing a cqe overflow, the req is just simply put in the comp_list and the req is released when the cq entry is posted. That way, for example a lost cqe that was supposed to carry a file descriptor can be gracefully closed

I think we can do something like this with IORING_SETUP_DEFER_TASKRUN, but it requires a bit of thought and might need to be opt in. My general idea is to only run IO if there is space for completions and so you should in general not hit overflows (except for with multishot)

**Comment by ilikdoge** [comment]
> If I understand correctly, on every loop you are submitting more which produces enough CQEs to fill the CQ ring, and so the overflows never get into the CQ ring?

Yes, this is correct. The application processes an event and immediately queues another up, before processing the next cqe. After the sqring fills up, submit has to be called before processing of cqes can continue. I usually use cqring sizes of 65536 but but noticed that a smaller one causes this issue.

> Ideally your application should never have overflows

That does make sense, as 65K is more than I think can be handled by a single thread

> there is a new change (in 6.1) that will always overflow CQEs

It looks like it fixes the issue

Thanks

**Comment by ilikdoge** [comment]
From what I see, **io_submit_flush_completions** doesn't attempt to flush any cqes?

That would mean even if GETEVENTS was set and there was a single overflow but the cqring has enough space, it would still
fill the comp_list in the overflow.

Since 5.19 tries to fill in cqes even without GETEVENTS, I think 6.1 should copy the behavior and try to flush any overflow in the submit path.

**Comment by DylanZA** [comment]
> From what I see, io_submit_flush_completions doesn't attempt to flush any cqes?

yeah - that is only for batching the completions that happen straight away in submits. batching here is a decent perf win.

GETEVENTS will flush overflows. my suggestion is to call GETEVENTS before submitting until you have fully flushed completions.
I think it would probably be reasonable for liburing to provide a "best practice" helper for all of this. something like

`int io_uring_process_cqes(struct io_ring *ring, void (process_cqe*)(struct io_uring_cqe *cqe, void *data), void *data);`


> 5.19 tries to fill in cqes even without GETEVENTS

it does not flush overflows I believe?

**Comment by ilikdoge** [comment]
> it does not flush overflows I believe?

no, but it does fill in some completed cqes

**Comment by ilikdoge** [comment]
> my suggestion is to call GETEVENTS before submitting until you have fully flushed completions

Yeah that would probably be best
