### ISSUE TITLE
Issue: process using io_uring hangs forever for unknown reason

### ISSUE THREAD

**Issue by CarterLi** [axboe/liburing#71]
A program written by me became a zombie process for some reason. I didn't fork other process, nor did something special, just normal stuff.

I was testing IOSQE_IO_LINK, FIXED_FILES and FIXED_BUFFERS, if helps.

![image](https://user-images.githubusercontent.com/6134068/74163633-a01ac580-4c5d-11ea-80f0-b782d4452bd0.png)

It can't be consistently reproduced, but happened several times. I couldn't kill it. When I was rebooting the system, I got:

![image](https://user-images.githubusercontent.com/6134068/74163488-6d70cd00-4c5d-11ea-84b8-c18091fb2477.png)

```shell
$ uname -a                                                           23:46:16
Linux carter-virtual-machine 5.5.0-999-generic #202002082109 SMP Sun Feb 9 02:13:41 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

https://github.com/torvalds/linux/commit/d4f309ca411887cd61ea389c7abfb70c2eb1e532

**Comment by axboe** [comment]
That's a new one - we're hanging off canceling requests that have files associated with them. Do you have a program that reproduces this that you can send me?

**Comment by CarterLi** [comment]
> That's a new one - we're hanging off canceling requests that have files associated with them. Do you have a program that reproduces this that you can send me?

Let me try getting it static linked

**Comment by CarterLi** [comment]
I can reproduce this issue using following code:

```c
// gcc echo_server.c -O2 -o echo_server -luring
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

#include <sys/socket.h>
#include <sys/poll.h>
#include <netinet/in.h>

#include <liburing.h>

#define BACKLOG 128
#define MAX_MESSAGE_LEN 1024
#define MAX_CONNECTIONS 1024

enum { ACCEPT, POLL, READ, WRITE };

struct conn_info {
	__u32 fd;
	__u32 type;
};

typedef char buf_type[MAX_CONNECTIONS][MAX_MESSAGE_LEN];

static struct io_uring ring;
static unsigned cqe_count = 0;

static int init_socket(int portno) {
	int sock_listen_fd = socket(AF_INET, SOCK_STREAM, 0);
	if (sock_listen_fd < 0) {
		perror("socket");
		return -1;
	}

	struct sockaddr_in server_addr = {
		.sin_family = AF_INET,
		.sin_port = htons(portno),
		.sin_addr = {
			.s_addr = INADDR_ANY,
		},
	};

	if (bind(sock_listen_fd, (struct sockaddr *)&server_addr, sizeof(server_addr)) < 0) {
		perror("bind");
		return -1;
	}

	if (listen(sock_listen_fd, BACKLOG) < 0) {
		perror("listen");
		return -1;
	}

	return sock_listen_fd;
}

static struct io_uring_sqe* get_sqe_safe() {
	struct io_uring_sqe *sqe = io_uring_get_sqe(&ring);
	if (__builtin_expect(!!sqe, 1)) {
		return sqe;
	} else {
		io_uring_cq_advance(&ring, cqe_count);
		cqe_count = 0;
		io_uring_submit(&ring);
		return io_uring_get_sqe(&ring);
	}
}

static void add_accept(int fd, struct sockaddr *client_addr, socklen_t *client_len, int flags) {
	struct io_uring_sqe *sqe = get_sqe_safe();
	struct conn_info conn_i = {
		.fd = fd,
		.type = ACCEPT,
	};

	io_uring_prep_accept(sqe, fd, client_addr, client_len, flags);
	io_uring_sqe_set_flags(sqe, IOSQE_FIXED_FILE);
	memcpy(&sqe->user_data, &conn_i, sizeof(conn_i));
}

static void add_poll(int fd, int poll_mask) {
	struct io_uring_sqe *sqe = get_sqe_safe();
	struct conn_info conn_i = {
		.fd = fd,
		.type = POLL,
	};

	io_uring_prep_poll_add(sqe, fd, poll_mask);
	io_uring_sqe_set_flags(sqe, IOSQE_FIXED_FILE | IOSQE_IO_LINK);
	memcpy(&sqe->user_data, &conn_i, sizeof(conn_i));
}

static void add_socket_read(int fd, size_t size, buf_type *bufs) {
	struct io_uring_sqe *sqe = get_sqe_safe();
	struct conn_info conn_i = {
		.fd = fd,
		.type = READ,
	};

	io_uring_prep_read_fixed(sqe, fd, (*bufs)[fd], size, 0, fd);
	io_uring_sqe_set_flags(sqe, IOSQE_FIXED_FILE | IOSQE_IO_LINK);
	memcpy(&sqe->user_data, &conn_i, sizeof(conn_i));
}

static void add_socket_write(int fd, size_t size, buf_type *bufs) {
	struct io_uring_sqe *sqe = get_sqe_safe();
	struct conn_info conn_i = {
		.fd = fd,
		.type = WRITE,
	};

	io_uring_prep_write_fixed(sqe, fd, (*bufs)[fd], size, 0, fd);
	io_uring_sqe_set_flags(sqe, IOSQE_FIXED_FILE);
	memcpy(&sqe->user_data, &conn_i, sizeof(conn_i));
}

int main(int argc, char *argv[]) {
	if (argc < 2) {
		fprintf(stderr, "Please give a port number: ./io_uring_echo_server [port]\n");
		return 1;
	}

	int portno = strtol(argv[1], NULL, 10);
	int sock_listen_fd = init_socket(portno);
	if (sock_listen_fd < 0) return -1;
	printf("io_uring echo server listening for connections on port: %d\n", portno);


	int ret = io_uring_queue_init(BACKLOG, &ring, 0);
	if (ret < 0) {
		fprintf(stderr, "queue_init: %s\n", strerror(-ret));
		return -1;
	}

	buf_type *bufs = (buf_type *)malloc(sizeof(*bufs));

	{
		int fds[MAX_CONNECTIONS];
		memset(fds, -1, sizeof(fds));
		fds[sock_listen_fd] = sock_listen_fd;
		io_uring_register_files(&ring, fds, MAX_CONNECTIONS);

		struct iovec iovecs[MAX_CONNECTIONS];
		for (int i = 0; i < MAX_CONNECTIONS; ++i) {
			iovecs[i] = (struct iovec) {
				.iov_base = (*bufs)[i],
				.iov_len = MAX_MESSAGE_LEN,
			};
		}
		io_uring_register_buffers(&ring, iovecs, MAX_CONNECTIONS);
	}

	struct sockaddr_in client_addr;
	socklen_t client_len = sizeof(client_addr);
	add_accept(sock_listen_fd, (struct sockaddr *)&client_addr, &client_len, 0);

	while (1) {
		io_uring_submit_and_wait(&ring, 1);

		struct io_uring_cqe *cqe;
		unsigned head;

		io_uring_for_each_cqe(&ring, head, cqe) {
			++cqe_count;

			struct conn_info conn_i;
			memcpy(&conn_i, &cqe->user_data, sizeof(conn_i));
			int result = cqe->res;

			switch (conn_i.type) {
			case ACCEPT:
				io_uring_register_files_update(&ring, result, &result, 1);
				add_accept(sock_listen_fd, (struct sockaddr *)&client_addr, &client_len, 0);
				add_poll(result, POLLIN);
				add_socket_read(result, MAX_MESSAGE_LEN, bufs);
				add_socket_write(result, MAX_MESSAGE_LEN, bufs);
				break;

			case POLL:
				// Do nothing
				break;

			case READ:
				if (__builtin_expect(result <= 0, 0)) {
					shutdown(conn_i.fd, SHUT_RDWR);
				} else if (__builtin_expect(result < MAX_MESSAGE_LEN, 0)) {
					add_socket_write(conn_i.fd, result, bufs);
				}
				break;

			case WRITE:
				if (__builtin_expect(result >= 0, 1)) {
					add_poll(conn_i.fd, POLLIN);
					add_socket_read(conn_i.fd, MAX_MESSAGE_LEN, bufs);
					add_socket_write(conn_i.fd, MAX_MESSAGE_LEN, bufs);
				}
				break;
			}
		}

		printf("cqe_count: %d\n", cqe_count);
		io_uring_cq_advance(&ring, cqe_count);
		cqe_count = 0;
	}


	close(sock_listen_fd);
	free(bufs);
}
```

Run with

```shell
./echo_server 12345
```

It works fine when testing with single connection ( `telnet 127.0.0.1 12345` ). But if you benchmark it using [rust_echo_bench](https://github.com/haraldh/rust_echo_bench) with large number of connections, the process hangs.

```shell
$ cargo run --release -- -c 200
```

**Comment by axboe** [comment]
Thanks, sorry I missed your followup! I'll look into this tomorrow morning.

**Comment by axboe** [comment]
Should be fixed with this one:

https://lore.kernel.org/io-uring/01ae4ae7-0cbb-389b-8ee9-f561b3df1d6a@kernel.dk/T/#u

That was a fun debug. Hang aside, you're overflowing the CQ ring, which I think is causing your test to exit prematurely.

**Comment by CarterLi** [comment]
> Should be fixed with this one:
> 
> [lore.kernel.org/io-uring/01ae4ae7-0cbb-389b-8ee9-f561b3df1d6a@kernel.dk/T/#u](https://lore.kernel.org/io-uring/01ae4ae7-0cbb-389b-8ee9-f561b3df1d6a@kernel.dk/T/#u)
> 
> That was a fun debug. Hang aside, you're overflowing the CQ ring, which I think is causing your test to exit prematurely.

Does it mean that I can workaround this issue by increasing cq size? I'll test it

**Comment by axboe** [comment]
> Does it mean that I can workaround this issue by increasing cq size? I'll have a test

Probably, though I didn't look too closely at what it's doing, I can only say with certainty that you are overflowing the CQ ring when I run with the 200 clients.

**Comment by CarterLi** [comment]
> > Does it mean that I can workaround this issue by increasing cq size? I'll have a test
> 
> Probably, though I didn't look too closely at what it's doing, I can only say with certainty that you are overflowing the CQ ring when I run with the 200 clients.

I've test it and it worked fine. The result was not good though.

**Comment by axboe** [comment]
> I've test it and it worked fine. The result was not good though.

Can you elaborate? I just posted a hack that allows us to run the linked request inline as well. Not anywhere near something that can go into the kernel, but perhaps we can massage it into something that can.

**Comment by CarterLi** [comment]
> > I've test it and it worked fine. The result was not good though.
> 
> Can you elaborate?

My code should be easy to understand. It's still an echo server. For every accepted connection, I issue a `POLL_ADD(POLLIN)-READ_FIXED-WRITE_FIXED` link chain ( see `case ACCEPT` ). but since `READ_FIXED` will be executed asyncly, it's slower then executing `POLL` `READ` `WRITE` separately.

**Comment by axboe** [comment]
I meant in terms of the performance numbers, sorry if that wasn’t clear.

**Comment by CarterLi** [comment]
> I meant in terms of the performance numbers, sorry if that wasn’t clear.

You may test it yourself. What I did was just making `BACKLOG` a larger number.

For example:

```c
#define BACKLOG 512
```

**Comment by CarterLi** [comment]
And you may compare with the version that doesn't use IOSQE_IO_LINK

https://github.com/CarterLi/io_uring-echo-server

Change the line below to 0

https://github.com/CarterLi/io_uring-echo-server/blob/490d647362621c7f18b11f41e86ed8abe3137404/global.h#L3

**Comment by npuichigo** [comment]
@CarterLi Have u addressed this issue? I'm working on [g6-net](https://github.com/Garcia6l20/g6-net) which uses io_uring together with c++ coroutines. When IO traffic is high, the CPU usage sometimes falls to zero and may hang forever.

**Comment by CarterLi** [comment]
@npuichigo 

My issue has been resolved by the io_uring author Axboe. Your problem may be caused by other things.
