### ISSUE TITLE
Multiple read requests on the same fd behaviour

### ISSUE THREAD

**Issue by ym1234** [axboe/liburing#711]
I'm not sure if this is documented anywhere, but what's the behaviour of multiple IORING_OP_READ submissions on the same fd?
Do they all get fulfiled when there is any input on the fd? Or does only the first one get fulfiled?

**Comment by axboe** [comment]
Depends on the file type - if it's a pipe, then depends on who gets executed first and how much data is available. If it's a buffered read from a regular file, all of them would get fulfilled. 

The same would happen if you had X tasks rather than X requests reading from the fd, basically.

**Comment by chrisvest** [comment]
You need to have the read ops linked together if you want them to run in a particular order, right?

**Comment by axboe** [comment]
> You need to have the read ops linked together if you want them to run in a particular order, right?

Yes, io_uring doesn't provide any ordering guarantees by default.

**Comment by ym1234** [comment]
I don't particularly care about the order, the reason I was asking about this was because tty's internal buffer was pretty small (4096 bytes) which was making the writing/child process stall in raw mode (I think? I haven't debugged this completely yet), and was looking into iourings as a fix for that.

Thanks!
