### ISSUE TITLE
No sqe for a long time after writing to cqe

### ISSUE THREAD

**Issue by uuuuu-diwu** [axboe/liburing#714]
After almost 1 million production sqe and consuming cqe. After the last rewrite to sqe, no cqe is received and then stuck at io_uring_submit_and_wait

![image](https://user-images.githubusercontent.com/17615704/199226509-77238103-e4bd-4154-9762-0aff8141dcd5.png)

**Comment by isilence** [comment]
I assume you found the problem and it was in the app. Is it right?
