### ISSUE TITLE
io_uring_prep_multishot_accept_direct is indistinguishable from multishot_accept

### ISSUE THREAD

**Issue by kitanatahu** [axboe/liburing#717]
the body of the function is
```
	io_uring_prep_multishot_accept(sqe, fd, addr, addrlen, flags);
	__io_uring_set_target_fixed_file(sqe, IORING_FILE_INDEX_ALLOC - 1);
```
IORING_FILE_INDEX_ALLOC is 0, we decrement one than increment it by 1 making it 0 again in the sqe,
which makes it the same as if we just left the sqe field memset to 0.

In fact from my testing there's no way to get a direct index using this function.

Maybe it's missing something or I'm missing it.

**Comment by ilikdoge** [comment]
**IORING_FILE_INDEX_ALLOC** should not be **0**, on my system its 2^32-1

**Comment by kitanatahu** [comment]
oops, my bad
