### ISSUE TITLE
IORING_SETUP_SQPOLL randomly fails IOs

### ISSUE THREAD

**Issue by sumeetb25** [axboe/liburing#72]
My toy program spins up two threads. Submits IOs from one thread and reaps IOs from the other. I have setup liburing using IORING_SETUP_SQPOLL flag. 

Following is my code:

```C
#include <errno.h>
#include <fcntl.h>
#include <pthread.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

#include "liburing.h"

#define DEVICE_SIZE (512ULL << 30)
#define BS 4096
#define QD 32

static struct io_uring ring;
static int dev_fd;

static void *setup_iov_base(size_t size)
{
        void *buf;
        int fd;

        if (posix_memalign(&buf, BS, size) != 0) {
                printf("mem aligned failed\n");
                return NULL;
        }

        fd = open("/dev/urandom", O_RDONLY);
        if (fd < 0) {
                printf("Failed to open urandom. rc=%d\n", fd);
                return NULL;
        }

        read(fd, buf, size);
        close(fd);
 
                                                                                                                                                                                         [76/282]
        return buf;
}

static int init(void)
{
        struct io_uring_params p = { 0 };
        time_t t;
        int rc;

        /* Implies no syscalls to submit IOs */
        p.flags = IORING_SETUP_SQPOLL;
        rc = io_uring_queue_init_params(QD, &ring, &p);
        if (rc != 0) {
                printf("queue_init failed. rc=%d\n", rc);
                return rc;
        }

        dev_fd = open("/dev/nvme1n1", O_RDWR | O_DIRECT);
        if (dev_fd < 0) {
                printf("Failed to open nvme device. rc=%d\n", dev_fd);
                return dev_fd;
        }

        /* SQPOLL only works with fixed files. */
        rc = io_uring_register_files(&ring, &dev_fd, 1);
        if (rc < 0) {
                printf("Failed to register files. rc=%d\n", rc);
                return rc;
        }

        srand((unsigned) time(&t));

        return 0;
}

static inline void submit_to_kernel(char *failure_message)
{
        int rc;

        rc = io_uring_submit(&ring);
        if (rc < 0) {
                printf("%s. rc=%d\n", failure_message, rc);
        }
}

static struct io_uring_sqe *get_sqe(int *yield)
{
        struct io_uring_sqe *sqe;

        while ((sqe = io_uring_get_sqe(&ring)) == NULL) {
                /* Kick kernel thread if it is taking a nap */
                submit_to_kernel("Failure to wake napping thread");

                *yield = *yield + 1;
                /* TODO: Use condition variables */
                pthread_yield();
        }

        return sqe;
}

static void *submit_io(void *input)
{
        char *buf = setup_iov_base(BS);
        off_t offset = 0;
        int total_ios = *((int *)input);
        int yield = 0;
       while (total_ios != 0) {
                struct io_uring_sqe *sqe = get_sqe(&yield);
                struct iovec iov = {
                        .iov_base = buf,
                        .iov_len = BS,
                };

                io_uring_prep_writev(sqe, 0, &iov, 1, offset);

                sqe->flags |= IOSQE_FIXED_FILE;
                sqe->user_data = offset;

                total_ios--;
                if (total_ios % QD == 0) {
                        submit_to_kernel("Failed to submit new IO");
                }

                offset += BS;
        }

        printf("submit_io yield %d times\n", yield);

        return NULL;
}

static void *reap_io_completions(void *input)
{
        int total_ios = *((int *)input);
        int failed_ios = 0;

        while (total_ios != 0) {
                struct io_uring_cqe *cqe = NULL;
                /* This call blocks if no CQE entries are available */
                int rc = io_uring_wait_cqe(&ring, &cqe);
                if (rc < 0 || cqe->res != BS) {
                        printf("rc=%d cqe->res=%d offset=%llu\n", rc, cqe->res, cqe->user_data);
                        failed_ios++;
                }

                total_ios--;
                io_uring_cqe_seen(&ring, cqe);
        }

        printf("Failed IO count=%d\n", failed_ios);

        return NULL;
}

int main(int argc, char *argv[])
{
        pthread_t submit, complete;
        int total_ios;
        int rc;

        if (argc != 2) {
                printf("Expected two arguments\n");
                return -EINVAL;
        }

        total_ios = atoi(argv[1]);

        rc = init();
        if (rc != 0) {
                return rc;
        }

        rc = pthread_create(&submit, NULL, submit_io, &total_ios);
        if (rc < 0) {
                printf("Failed to create submit thread. rc=%d\n", rc);
                return rc;
        }

        rc = pthread_create(&complete, NULL, reap_io_completions, &total_ios);

        if (rc < 0) {
                printf("Failed to create complete thread. rc=%d\n", rc);
                return rc;
        }

        pthread_join(submit, NULL);
        pthread_join(complete, NULL);

        io_uring_queue_exit(&ring);
        close(dev_fd);

        return 0;
}

```

Here is my output for multiple runs:

[root@ip-10-0-58-7 liburing]# ./examples/iouringthread 65
submit_io yield 74 times
rc=0 cqe->res=-14 offset=258048
rc=0 cqe->res=-14 offset=262144
Failed IO count=2

[root@ip-10-0-58-7 liburing]# ./examples/iouringthread 65
submit_io yield 194 times
rc=0 cqe->res=-14 offset=204800
rc=0 cqe->res=-14 offset=208896
rc=0 cqe->res=-14 offset=212992
rc=0 cqe->res=-14 offset=217088
rc=0 cqe->res=-14 offset=221184
rc=0 cqe->res=-14 offset=225280
rc=0 cqe->res=-14 offset=229376
rc=0 cqe->res=-14 offset=233472
rc=0 cqe->res=-14 offset=237568
rc=0 cqe->res=-14 offset=241664
rc=0 cqe->res=-14 offset=245760
rc=0 cqe->res=-14 offset=249856
rc=0 cqe->res=-14 offset=253952
rc=0 cqe->res=-14 offset=258048
rc=0 cqe->res=-14 offset=262144
Failed IO count=15

[root@ip-10-0-58-7 liburing]# ./examples/iouringthread 65
submit_io yield 69 times
rc=0 cqe->res=-14 offset=196608
rc=0 cqe->res=-14 offset=200704
rc=0 cqe->res=-14 offset=204800
rc=0 cqe->res=-14 offset=208896
rc=0 cqe->res=-14 offset=212992
rc=0 cqe->res=-14 offset=217088
rc=0 cqe->res=-14 offset=221184
rc=0 cqe->res=-14 offset=225280
rc=0 cqe->res=-14 offset=229376
rc=0 cqe->res=-14 offset=233472
rc=0 cqe->res=-14 offset=237568
rc=0 cqe->res=-14 offset=241664
rc=0 cqe->res=-14 offset=245760
rc=0 cqe->res=-14 offset=249856
rc=0 cqe->res=-14 offset=253952
rc=0 cqe->res=-14 offset=258048
rc=0 cqe->res=-14 offset=262144
Failed IO count=17

If I update the code to not use SQPOLL it works just fine.

liburing commit ID - a68caac2253dbb3c4c45a5bb65d76c54f6d83df5

**Comment by axboe** [comment]
You didn't mention what kernel you are running, that's a key piece of information that we'll definitely need.

**Comment by sumeetb25** [comment]
I downloaded and built kernel from https://cdn.kernel.org/pub/linux/kernel/v5.x/linux-5.4.1.tar.xz

**Comment by axboe** [comment]
For this to work, io_uring needs to support IORING_FEAT_SUBMIT_STABLE, reported in io_uring_params->features - and that wasn't available until 5.5.

**Comment by sumeetb25** [comment]
(If I've read it correctly) IORING_FEAT_SUBMIT_STABLE ensures iov can be free'd as soon as SQE is successfully submitted. 

Theoretically my code can potentially break even w/o SQPOLL. For some reasons SQPOLL is just worsening the race condition. Is my understanding accurate?

**Comment by sumeetb25** [comment]
I made iov static to make sure it is available across the lifecycle of the application. IOs work fine when I drive less than 500K IOs.

However if I try to drive heavy workload (more than a million IOs) it randomly hangs (not always but ~6/10 times)

Following is the git diff from the above code

``` C
@@ -20,6 +20,7 @@
 
 static struct io_uring ring;
 static int dev_fd;
+static struct iovec iov;
 
 static void *setup_iov_base(size_t size)
 {
@@ -70,6 +71,9 @@ static int init(void)
                return rc;
        }
 
+       iov.iov_base = setup_iov_base(BS);
+       iov.iov_len = BS;
+
        srand((unsigned) time(&t));
 
        return 0;
@@ -103,17 +107,12 @@ static struct io_uring_sqe *get_sqe(int *yield)
 
 static void *submit_io(void *input)
 {
-       char *buf = setup_iov_base(BS);
        off_t offset = 0;
        int total_ios = *((int *)input);
        int yield = 0;
 
        while (total_ios != 0) {
                struct io_uring_sqe *sqe = get_sqe(&yield);
-               struct iovec iov = {
-                       .iov_base = buf,
-                       .iov_len = BS,
-               };
 
                io_uring_prep_writev(sqe, 0, &iov, 1, offset);
```

Example output:
[root@ip-10-0-58-7 liburing]# ./examples/iouringthread 1000000
submit_io yield 7052094 times
Failed IO count=0

[root@ip-10-0-58-7 liburing]# vim examples/iouringthread.c 
[root@ip-10-0-58-7 liburing]# ./examples/iouringthread 2000000                                                                                                                            
submit_io yield 14792806 times
^C
[root@ip-10-0-58-7 liburing]#

**Comment by axboe** [comment]
That's a different issue, and could either be a race in your code, liburing, or maybe even on the kernel side. I'd suggest you close this and open a new one for that.

**Comment by axboe** [comment]
> Theoretically my code can potentially break even w/o SQPOLL. For some reasons SQPOLL is just worsening the race condition. Is my understanding accurate?

The stable part means that as soon as the sqe has been seen, you don't need to retain the associated structures anymore. For SQPOLL, this is difficult or impossible to detect, so generally you want it to be available for the life time of the request.

**Comment by sumeetb25** [comment]
Thanks for the clarification.

**Comment by sumeetb25** [comment]
> That's a different issue, and could either be a race in your code, liburing, or maybe even on the kernel side. I'd suggest you close this and open a new one for that.

Ack. I'll open a new issue.
