### ISSUE TITLE
Trace between blk layer and io_uring

### ISSUE THREAD

**Issue by korant96** [axboe/liburing#720]
In I/O layer, we can trace from bio submitting to req completing with LBA address. In io_uring, we can trace req with userdata?
But it seems an req can not be tarced between io_uring and blk layer. Is there any connection across the two layer？

**Comment by axboe** [comment]
Not currently possible. Could be done, but would require you to additionally map file offset to disk location. That's either easy (eg you're using a raw bdev for IO), or a bit harder and requires you to map extents in the file.
