### ISSUE TITLE
typo in kernel's io_uring.h

### ISSUE THREAD

**Issue by FrankReh** [axboe/liburing#721]
The include/uapi/linux/io_uring.h has a minor typo in a comment that makes it to this library's copy, of course. Probably not worth a PR on  its own. Just close this as soon as someone one the team has read it. Thank you.

'pass thig flag' -> 'pass this flag'

**Comment by axboe** [comment]
Yeah I have noticed that, mentioned it in some other thread as well. I tend to sync from kernel -> liburing, so I'll queue up a typo patch upstream first.

**Comment by axboe** [comment]
https://git.kernel.dk/cgit/linux-block/commit/?h=io_uring-6.1&id=6dcabcd398946e2b0b776a8310291aeebe1ca0e6

Queued up, marking this as done.
