### ISSUE TITLE
Question: what is .PPAA in the setup man page

### ISSUE THREAD

**Issue by FrankReh** [axboe/liburing#722]
I'm preparing a PR with manpage fixups and found a single *.PPAA" macro in one  page. It was put there less than a month ago. My searches don't find a PPAA macro definition and on my mac, where I use groff to prepare for the Preview app, there is even an error saying PPAA is not recognized.

If it's important, I can use it consistently in the other section 2 pages, or all the pages for that matter. If it was a typo, I can change it to .PP as part of the cleanup PR.

https://github.com/axboe/liburing/blob/754bc068ec482c5338a07dd74b7d3892729bb847/man/io_uring_setup.2#L10-L19

**Comment by guillemj** [comment]
Hi! This was fixed with commit 4215200cf419f7d85cefa04b11a8258d4c8f4974, so I think it can be closed now.
