### ISSUE TITLE
Missing definition of AT_FDCWD. liburing.h didn't include <fcntl.h>

### ISSUE THREAD

**Issue by beef9999** [axboe/liburing#723]
https://github.com/axboe/liburing/blob/0d4fdb416718a70a4a90c5c4722b38cf44849195/src/include/liburing.h#L914

BTW I was compiling on CentOS 8.

**Comment by axboe** [comment]
Please include a comment on why an issue is being closed - is this a problem or not? If not, why?

**Comment by beef9999** [comment]
It's not a problem.
Enabling `AT_FDCWD` in <fcntl.h> would require setting `_GNU_SOURCE`. I set it and then the latest code could compile.

**Comment by axboe** [comment]
Ah great, thank you. Now the issue is also useful to others that may run into the same thing.
