### ISSUE TITLE
liburing 2.3 breaks ABI w/o SOVERSION bump

### ISSUE THREAD

**Issue by guillemj** [axboe/liburing#724]
The latest liburing release seems to be breaking the ABI, by deprecating the kring_mask and kring_entries members by the new ring_mask and ring_entries, used by the inline functions.

The problem is that these structures are public, and there are inline functions making use of the old or new members depending on what version the callers were linked against. So code compiled against the old version should work with the new shared library as the old and new members are always filled. But code compiled against the new version will not work with the old shared library as there the new members used in the new inline functions are going to be wrong (either uninitialized or 0, have not checked).

This was introduced in commit f5cd4eb2b50840510a4c6bbe5ba34a5a2058a2ae by @calebsander.

**Comment by guillemj** [comment]
> > The problem is that these structures are public, and there are inline
> > functions making use of the old or new members depending on what
> > version the callers were linked against.
> 
> How to tell the app that the shared library needs an upgrade if it's compiled against liburing-2.3?

The Debian liburing packaging could force the dependencies for anything linked against it to be at least 2.3. We have symbol usage granularity (see https://git.hadrons.org/cgit/debian/pkgs/liburing.git/tree/debian/liburing2.symbols), so I could bump all minimum versions (but that potentially adds an artificial version restriction), I could instead go over any symbol in the library that indirectly calls  io_uring_mmap() and bump their symbol minimum version, but I'm not sure whether that will amount of a global version bump.

The problem I see though is that this is probably going to be missed by users/distros, as the headers try to be careful about the ABI with padding in structs and similar (even though the inline functions are problematic), and with the use of versioned symbols. But if the end result is that building against a new liburing requires bumping the entire minimum version (regardless of just new versioned symbols used), then this all seems a bit pointless and it could just as well bump the SOVERSION instead?

> What are the rules in the versioning if a release breaks the ABI?

There are several ways this could be handled. Bumping the SOVERSION would be one. Versioning the struct or similar so that the inline functions only use the new members if this is a new struct instead of an old one. Making the functions that use the new members not inline anymore. And perhaps others I've not considered right now.

> Does this have something to do with the recent pending pull request?
> 
> PR Link: #681

Not at all, I have nothing to do with that PR, as I don't use the packaging upstream at all. :)

**Comment by guillemj** [comment]
I might have missed some codepaths, but I guess I could do the following:

```
diff --git i/debian/liburing2.symbols w/debian/liburing2.symbols
index 9c20795..19cac25 100644
--- i/debian/liburing2.symbols
+++ w/debian/liburing2.symbols
@@ -10,16 +10,16 @@ liburing.so.2 liburing2 #MINVER#
  io_uring_enter@LIBURING_2.3 2.3
  io_uring_free_probe@LIBURING_2.0 2.0
  io_uring_get_events@LIBURING_2.3 2.3
- io_uring_get_probe@LIBURING_2.0 2.0
+ io_uring_get_probe@LIBURING_2.0 2.3
  io_uring_get_probe_ring@LIBURING_2.0 2.0
  io_uring_get_sqe@LIBURING_2.0 2.0
- io_uring_mlock_size@LIBURING_2.1 2.1
- io_uring_mlock_size_params@LIBURING_2.1 2.1
+ io_uring_mlock_size@LIBURING_2.1 2.3
+ io_uring_mlock_size_params@LIBURING_2.1 2.3
  io_uring_peek_batch_cqe@LIBURING_2.0 2.0
  io_uring_queue_exit@LIBURING_2.0 2.0
- io_uring_queue_init@LIBURING_2.0 2.0
- io_uring_queue_init_params@LIBURING_2.0 2.0
- io_uring_queue_mmap@LIBURING_2.0 2.0
+ io_uring_queue_init@LIBURING_2.0 2.3
+ io_uring_queue_init_params@LIBURING_2.0 2.3
+ io_uring_queue_mmap@LIBURING_2.0 2.3
  io_uring_register@LIBURING_2.3 2.3
  io_uring_register_buf_ring@LIBURING_2.2 2.2
  io_uring_register_buffers@LIBURING_2.0 2.0
```

But, as you can see this seems rather unintuitive, as these symbols introduced in previous versions require a newer library version when used (due to the inline function mismatch), which seems to go counter to versioning the symbols. Hmm perhaps this could also be worked around by adding symbol aliases in the library at LIBURING_2.3 and making those new symbols the default symbol to be bound to (using `symbol@@LIBURING_2.3`), so that old code would use the old versioned entry, and new code would require the new LIBURING_2.3 entries, denoting the ABI break.

**Comment by ammarfaizi2** [comment]
> But if the end result is that building against a new liburing requires
> bumping the entire minimum version (regardless of just new versioned
> symbols used), then this all seems a bit pointless and it could just
> as well bump the SOVERSION instead?

Not familiar with the SOVERSION. Does that imply bumping the version to 3.x?

**Comment by guillemj** [comment]
> Not familiar with the SOVERSION. Does that imply bumping the version to 3.x?

Yeah the SOVERSION is commonly used to refer to the version part of the SONAME, so in this case from 2 to 3 (the SOVERSION does not necessarily need to map to the project version though, but it's fine if it does). Of course bumping the SOVERSION tends to be inconvenient as that requires rebuilding any reverse dependency.

For example there seems to be space for a version member in both affected structs, so that approach could be easily implemented, or making the inline accessor not inline anymore, or the symbol aliases option. But I'd wait for @axboe's preference here.

**Comment by ammarfaizi2** [comment]
> But, as you can see this seems rather unintuitive, as these symbols
> introduced in previous versions require a newer library version when
> used (due to the inline function mismatch), which seems to go counter
> to versioning the symbols.

Let's wait for Jens' comment on this. @axboe, any comment?

**Comment by metze-samba** [comment]
Another way would be to have only inline functions and no .so file at all anymore...

**Comment by ammarfaizi2** [comment]
> Another way would be to have only inline functions and no .so file at
> all anymore...

Sounds good. But I think it should be optional, not replacing the main
shared library. 

I am thinking of creating a liburing lite where you can use liburing
by only including a header file, statically linked. It would also be
great if the header file could be auto-generated from the upstream
tree.

**Comment by ammarfaizi2** [comment]
> > Another way would be to have only inline functions and no .so file at
> > all anymore...
>
> Sounds good. But I think it should be optional, not replacing the main
> shared library.

Eh, not inline, but most importantly "static" and marked as __maybe_unused.

**Comment by guillemj** [comment]
> Another way would be to have only inline functions and no .so file at all anymore...

While certainly an option, this would be equivalent to bumping the SOVERSION on each release, requiring rebuilding all reverse dependencies. Also the semantics would be equivalent to what could be achieved today by statically linking the library. So to me there does not seem much benefit in going in that direction, TBH.
