### ISSUE TITLE
Question: map pages: direct files or fixed files

### ISSUE THREAD

**Issue by FrankReh** [axboe/liburing#725]
There are some man pages that use the terms fixed file table and fixed files or fixed file descriptors and others that seem to refer to the same things as direct file table, or direct files or direct file descriptors.

True there is an io_uring.h symbol with FIXED in its name, IOSQE_FIXED_FILE. Other symbols with FIXED in their name seem to refer only to fixed buffers though.

And there are many liburing functions the *_direct* suffix in their name that I think are operating on the same items.

Would it be okay if the man pages that refer to fixed files be changed to refer to direct files, the one symbol name notwithstanding?

At least io_uring_{enter, setup, register_file_alloc_range, and register} man pages refer to fixed file things when it seems they could be using the terms *direct file* for the table and the descriptors.

And is it correct that the terms *direct file* and *direct file descriptor* refer to the same thing? The index in the table kept by the uring for its registered files?

Then where there are man pages that refer to registered files, it could be pointed out these are called direct file descriptors in other man pages too.

**Comment by isilence** [comment]
I didn't look up how it evolved in man pages, but **_direct** helpers are for requests generating / creating new files directly into the io_uring's fixed file table instead of the conventional process file table. It was not name **_fixed** because I was afraid that it'll be too easily confused with requests accepting a fixed file, which is done via **IOSQE_FIXED_FILE** as you noticed, and with fixed_{read,write}, which are about registered buffers.

**Comment by FrankReh** [comment]
Now, browsing the driver source, I see the use of fixed_file_slot and fixed_fd.

I wonder if the man pages should converge on using the terms in the driver source, and just explain away the use of _direct in the function names - or even let the reader deduce it themselves. So maybe fixed table and fixed descriptor (*fixed_fd*) can be kept separate in the minds of the man page reader from registered buffer. (I don't find a term like fixed buffer in the driver source.)

Given the use in the kernel, when people talk about these entities down the road, it would be nice if they didn't have to differentiate between the kernel entity and the liburing entity. It's fine that the API function name is one thing, but the description of what's being managed can probably be cleaned up so it is as concise and uniform as the kernel source is itself.

At least that's how I'm leaning. Someone on your team can weigh in with a different direction and I'll be happy to do that instead.

So of course no changes to names of functions or symbols. Just man pages that try to be consistent with their terminology.

**Comment by axboe** [comment]
I think that sounds fine.

**Comment by FrankReh** [comment]
I will submit a draft PR that gets at this. But unless someone says it's urgent, what I've done isn't ready yet anyway and what with the timing of things, I don't expect the liburing man pages are the highest priority right now for anyone.

**Comment by axboe** [comment]
That sounds good, there's no immediate rush on this.
