### ISSUE TITLE
Exiting liburing event loop

### ISSUE THREAD

**Issue by nandlab** [axboe/liburing#730]
Hello,
I am trying to understand how liburing works and how to use it.

Is there a way to exit an liburing event loop when no further sqe's are pending?

**Comment by isilence** [comment]
What do you mean? liburing doesn't provide a event loop API, and it's  left up the userspace. 

```C
nr_reqs = 0;
prep_req() {
	nr_reqs++;
	sqe = get_sqe();
	prep_sqe();
}

prep_req();
prep_req();
...

nr = io_uring_submit();
if (nr == nr_reqs)
	return; // exit event loop;
```

You may have sth like this snippet non-sqpoll rings, the userspace knows how many requests it sent. Though someone have to wait  for completions.
