### ISSUE TITLE
Proper Lifetime Requirements of Buffers

### ISSUE THREAD

**Issue by cmazakas** [axboe/liburing#733]
I'm trying to write a liburing-based I/O library and I have a few questions.

Assuming I'm preparing a read request and supplying a buffer, how long must this buffer live?

In the happy path, the buffer must live at least as long as the SQE does, until the CQE is retrieved.

But I'm wondering about two other paths: `io_uring_prep_cancel()` and `close(fd)`.

If I call `io_uring_prep_cancel(my_sqe); io_uring_submit(ring); free(buffers);`, am I in danger of segfaulting?

Similarly for `close(fd)`.

i.e. should I _only_ call `free(buffers)` once I have the corresponding CQE in hand?

**Comment by axboe** [comment]
Since a CQE will be posted regardless for the original request when you do a cancelation, yes you should keep the buffer alive until you get a CQE. There's no difference between the rules there, cancelation or not.

**Comment by cmazakas** [comment]
Wow, thank you for the quick reply!

Alright, that means I have a good bit of refactoring to do. This should be pretty fun. I'm marking this issue as resolved as I have my answer.

I appreciate your time.

**Comment by axboe** [comment]
Just to be clear, if you successfully cancel the request, then the buffer can get freed immediately. But that case also means that the CQE for the canceled request will be sitting in the CQ ring for you anyway. Hence I think the cleanest solution will be to *always* honor the rule that buffers must stay alive until that particular request has posted its completion.
