### ISSUE TITLE
Clarification on cancellation

### ISSUE THREAD

**Issue by vasama** [axboe/liburing#734]
The documentation on cancellation seems a little lacking.
- [ ] 1. How do `IORING_OP_ASYNC_CANCEL` and `IORING_OP_LINK_TIMEOUT` affect the result of the target operation?
- [x] 2. What is the effect of `IORING_OP_ASYNC_CANCEL` when there are multiple operations in flight with the specified user data?
- [ ] 3. How is an `IORING_OP_LINK_TIMEOUT` operation affected by the successful cancellation via `IORING_OP_ASYNC_CANCEL` of the operation to which it is linked?
- [ ] 4. What is the effect of `IORING_OP_LINK_TIMEOUT` on subsequent operations in a chain, after the successful completion of the operation to which it is linked?

**Comment by cmazakas** [comment]
I've actually wondered about these things myself.

Most specifically:
> What is the effect of IORING_OP_ASYNC_CANCEL when there are multiple operations in flight with the specified user data?

An answer to this would be really appreciated.

**Comment by axboe** [comment]
It depends on if match all is set or not. If set, it'll match all of them and try to cancel them. If not, it'll match the first one it finds.

**Comment by DylanZA** [comment]
I suspect this is going to be an implementation detail, and subject to different states of the ring

I wouldnt make any assumptions on the ordering of completions for different requests
