### ISSUE TITLE
[examples/io_uring-udp] when  io_uring_register_files(&sockfd), sqe fd is fixed as 0 ?

### ISSUE THREAD

**Issue by glenn-wang** [axboe/liburing#735]
When after  ```io_uring_register_files``` sockfd
https://github.com/axboe/liburing/blob/liburing-2.3/examples/io_uring-udp.c#L363

the sqe fd  would be fixed as 0  like the followings?

https://github.com/axboe/liburing/blob/liburing-2.3/examples/io_uring-udp.c#L369
https://github.com/axboe/liburing/blob/liburing-2.3/examples/io_uring-udp.c#L384

**Comment by DylanZA** [comment]
I'm not sure what you are asking, but if you are clarifying then yes that looks correct.
I would say the fd is not fixed as 0, but the fd is registered to index 0 when using IOSQE_FIXED_FILE
