### ISSUE TITLE
version checking macros

### ISSUE THREAD

**Issue by chergert** [axboe/liburing#736]
It would be really handy if there were version checking macros included with liburing so that code consuming it can do things like:

```c
#if IO_URING_CHECK_VERSION(2,3)
  /* >= 2.3 */
#else
  /* < 2.3 */
#endif
```

I try not to file feature requests of others unless I'm willing to sign up to do the work, so if this is something you want, I'll take the time to do it within reason.

We have a very common pattern for this in GNOME for glib/gtk and associated libraries in the stack.

**Comment by axboe** [comment]
You're not the first to ask. My only question is what would this fix for you? I don't mind adding a version check, but there has to be a reason to do so. In general, we try pretty hard not to make breaking changes between releases, but I guess it can be useful for feature checking?

If you have a good reason for needing it, please explain and yes then I'd love for you to submit a PR for it.

**Comment by chergert** [comment]
I'd say at the moment that my thought is related to backporting.

For example, the code I'm writing now is targeting 2.3, but there is a non-zero chance I'd have to backport it to various LTS systems where I don't quite have the newest API available. So on those I might have to do something slightly different.

**Comment by axboe** [comment]
Alright, let's do it.
