### ISSUE TITLE
Any possibility to support getaddrinfo(3)?

### ISSUE THREAD

**Issue by cmazakas** [axboe/liburing#754]
Given: https://man7.org/linux/man-pages/man3/getaddrinfo.3.html

Is it possible for liburing to export something like `io_uring_prep_getaddrinfo()`?

**Comment by ammarfaizi2** [comment]
> Is it possible for liburing to export something like `io_uring_prep_getaddrinfo()`?

This was discussed in 2021. See: https://github.com/axboe/liburing/issues/234#issuecomment-770765351

**Comment by cmazakas** [comment]
Wow, quick reply!

Yeah, the reasoning for not supporting getaddrinfo make good sense.

Hmm, guess I'll have to hand-roll something myself to bring concurrency back to this aspect.

Thank you for the link. I'll be closing this issue as getaddrinfo is outside the scope of liburing
