### ISSUE TITLE
IORING_TIMEOUT_ETIME_SUCCESS not supported on WSL2?

### ISSUE THREAD

**Issue by cmazakas** [axboe/liburing#756]
I'm trying to link an `io_uring_prep_cancel()` to a timeout but it seems like on WSL2, using `IORING_TIMEOUT_ETIME_SUCCESS` causes the CQE to return with `-EINVAL`. Looking at the test for timeouts, I see: 
https://github.com/axboe/liburing/blob/4458aa0372738e844008397f71c062bd8bfadcac/test/timeout.c#L1305-L1307

i.e. if it returns with `EINVAL`, it's just not supported.

So, I'm left with a question, how do I get it supported? I'm using a relatively modern version of Ubuntu.

```bash
exbigboss@DESKTOP-08K7IHD:~/rust/rio$ uname -a
Linux DESKTOP-08K7IHD 5.15.79.1-microsoft-standard-WSL2 #1 SMP Wed Nov 23 01:01:46 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

This is all an impl detail of implementing per-operation timeouts. I have 4 SQEs with 2 linked pairs:
```
io_uring_prep_connect() -> io_uring_prep_cancel(ud2)
io_uring_prep_timeout() -> io_uring_prep_cancel(ud1)
```

It _seems_ like everything works just fine if I hard-link `io_uring_prep_timeout() -> io_uring_prep_cancel(connect_user_data)` but I don't find this particularly elegant.

Also, what's the semantic difference between `io_uring_prep_timeout_remove()` because it _seems_ like `prep_cancel()` works equally well. So, no idea what I should do if I have a timeout linked to cancel request because I want to cancel any part of the chain in a uniform interface (which cancel() seems to incidentally do).

**Comment by axboe** [comment]
```IORING_TIMEOUT_ETIME_SUCCESS``` arrived with kernel 5.16, so you're unfortunately just one revision behind it being available... 6.1 will be the next LTS kernel, so if you want to stick with those, then that should be available in ubuntu shortly I'd think.

There's no difference between using the specific poll cancel, or the generic cancel. We had poll removal/cancel before we had generic cancelations, and the generic one will find the poll one too. The poll specific one may be a bit more efficient as it will only look for poll requests, and on the other hand, the generic one has more options which may be important if you're trying to cancel more than one request at the time.

**Comment by cmazakas** [comment]
Ha, thanks for the reply! Good to know that I'm not doing anything wrong then!

Alright, I'll go ahead and close this issue as you've answered all my questions.

I'm so stoked that liburing comes with a built-in way of doing timeouts! Thank you so much!
