### ISSUE TITLE
CQ size must be power of 2

### ISSUE THREAD

**Issue by CaucherWang** [axboe/liburing#757]
```
auto ret = io_uring_queue_init(60, &ring);
```
When I set `entries` to be 60 or other numbers that are not powers of 2, it will cause bugs when I fetch data by `io_uring_cqe_get_data`. It will return a pointer to 0x100000000, and then segmentation fault happens.

I checked all the examples in this repo, and found that all of them use a power of 2 as the number to init the queue.
It hasn't been mentioned in any material. Is that a rule?

**Comment by CaucherWang** [comment]
```
err = io_uring_wait_cqe_nr(&ring, &cqe, nr);
```
I found that this function can only fill one `cqe` in the second parameter. How to get the rest `nr-1` cqes?  Simply moving pointers like `cqe + i` sometimes cause bugs, as mentioned above.

**Comment by ammarfaizi2** [comment]
> Is that a rule?

The number of SQEs and CQEs are always a power of two for efficient
modulo purpose (calculating: `head & mask` and `tail & mask`). It's
always rounded up to the power of 2 by the kernel.

See: https://github.com/torvalds/linux/blob/v6.1/io_uring/io_uring.c#L3424-L3443

So using 60 is fine, you will get 64.

Can you give a real simple reproducer that's ready to compile and run?

Running `test/link.t` with ring entries = 60 works just fine for me.

```diff
diff --git a/test/link.c b/test/link.c
index 3c8d991..62a2d8f 100644
--- a/test/link.c
+++ b/test/link.c
@@ -394,7 +394,7 @@ static int test_early_fail_and_wait(void)
 	struct iovec iov = { .iov_base = NULL, .iov_len = 0 };
 
 	/* create a new ring as it leaves it dirty */
-	ret = io_uring_queue_init(8, &ring, 0);
+	ret = io_uring_queue_init(60, &ring, 0);
 	if (ret) {
 		printf("ring setup failed\n");
 		return 1;
@@ -438,14 +438,14 @@ int main(int argc, char *argv[])
 	if (argc > 1)
 		return T_EXIT_SKIP;
 
-	ret = io_uring_queue_init(8, &ring, 0);
+	ret = io_uring_queue_init(60, &ring, 0);
 	if (ret) {
 		printf("ring setup failed\n");
 		return T_EXIT_FAIL;
 
 	}
 
-	ret = io_uring_queue_init(8, &poll_ring, IORING_SETUP_IOPOLL);
+	ret = io_uring_queue_init(60, &poll_ring, IORING_SETUP_IOPOLL);
 	if (ret) {
 		printf("poll_ring setup failed\n");
 		return T_EXIT_FAIL;
```

**Comment by ammarfaizi2** [comment]
> Simply moving pointers like `cqe + i` sometimes cause bugs, as mentioned above.

You can't do that. CQE and SQE index have to be calculated with mask.
Because they are circular. `cqe + i` may out of bound.

You have to do:
```
cqe + (i & mask)
```

**Comment by ammarfaizi2** [comment]
> How to get the rest `nr-1` cqes?

Use `io_uring_for_each_cqe()`.

**Comment by CaucherWang** [comment]
> > How to get the rest `nr-1` cqes?
> 
> Use `io_uring_for_each_cqe()`.

can I use io_uring_cq_advance(ring, nr) before calling this macro? i.e., wait -> advance -> for_each_cqe.

**Comment by ammarfaizi2** [comment]
> > > How to get the rest `nr-1` cqes?
> > 
> > 
> > Use `io_uring_for_each_cqe()`.
> 
> can I use io_uring_cq_advance(ring, nr) before calling this macro? i.e., wait -> advance -> for_each_cqe.

Yes, you can.

**Comment by CaucherWang** [comment]
> > Simply moving pointers like `cqe + i` sometimes cause bugs, as mentioned above.
> 
> You can't do that. CQE and SQE indexes have to be calculated with a mask. Because they are circular. `cqe + i` may be out of bounds.
> 
> You have to do:
> 
> ```
> cqe + (i & mask)
> ```

I guess `mask` is equal to CQ size - 1, right? (clued from io_uring_buf_ring_mask)

**Comment by ammarfaizi2** [comment]
> > > Simply moving pointers like `cqe + i` sometimes cause bugs, as mentioned above.
> > 
> > 
> > You can't do that. CQE and SQE indexes have to be calculated with a mask. Because they are circular. `cqe + i` may be out of bounds.
> > You have to do:
> > ```
> > cqe + (i & mask)
> > ```
> 
> I guess `mask` is equal to CQ size - 1, right? (clued from io_uring_buf_ring_mask)

Yes, exactly.

**Comment by CaucherWang** [comment]
Emmmm, I have tried these two methods, but still a few problems...
1. cqe_get_data(`cqe + (i & mask)`) sometimes return nullptr unexpectedly. Note that `wait` function can successfully return.

**Comment by ammarfaizi2** [comment]
> Emmmm, I have tried these two methods, but still a few problems...
> 
> 1. cqe_get_data(`cqe + (i & mask)`) sometimes return nullptr unexpectedly. Note that `wait` function can successfully return.
> 2. `io_uring_for_each_cqe` can not visit all `nr` cqe in my program.

I can't review to find out what is going wrong. Please send a simple
program to demonstrate the issue.

**Comment by CaucherWang** [comment]
I simplify my program as the following. Could you find any bugs here?
```
    io_uring ring{};
    auto ret = io_uring_queue_init(CQ_size, &ring, 0);
    io_uring_sqe* sqe;  io_uring_cqe* cqe;
    vector<vector<io_data>>io_buffer(2, vector<io_data>(CQ_size));
    for(int i = 0; i < 2 ; ++i)
        for(int j = 0; j < CQ_size; ++j)
            io_buffer[i][j].tss = new float [nbytes];
    int buffer_flag = 0, prev_buf_size =0, cur_buf_size = 0, err, len;
    bool first_time = true; io_data* data;
    int mask = CQ_size - 1;
    while(/*some condition*/){
        sqe = io_uring_get_sqe(&ring);
        assert(sqe);
        auto & tmp = io_buffer[buffer_flag][cur_buf_size];
        // fill tmp...
        io_uring_prep_read(sqe, tmp.fd, tmp.tss, nbytes, 0);
        io_uring_sqe_set_data(sqe, &tmp);
        ++cur_buf_size;
        if(cur_buf_size == CQ_size){
            if(!first_time){
                err = io_uring_wait_cqe_nr(&ring, &cqe, prev_buf_size);
                assert(err == 0);
                io_uring_cq_advance(&ring, prev_buf_size);
                err = io_uring_submit(&ring);
                assert(err == cur_buf_size);

                unsigned head = 0;
                int times = 0;
                io_uring_for_each_cqe(&ring, head, cqe){
                    ++times;
                    data = (io_data*)io_uring_cqe_get_data(cqe);
                    // do sth.
                }
                assert(times == prev_buf_size); // ERROR!   times < prev_buf_size

//                    for(int i = 0 ; i < prev_buf_size; ++i){
//                        void * t = io_uring_cqe_get_data(cqe + (i & mask));
//                        data = &io_buffer[1 - buffer_flag][i];
//                         // do sth.
//                    }

            }else{
                err = io_uring_submit(&ring);
                assert(err == cur_buf_size);
            }
            first_time = false;
            prev_buf_size = cur_buf_size;
            cur_buf_size = 0;
            buffer_flag = 1 - buffer_flag;

        }
    }

    err = io_uring_wait_cqe_nr(&ring, &cqe, prev_buf_size);
    assert(err == 0);
    io_uring_cq_advance(&ring, prev_buf_size);

    unsigned head = 0;
    int times = 0;
    io_uring_for_each_cqe(&ring, head, cqe){
        ++times;
        data = (io_data*)io_uring_cqe_get_data(cqe);
        // do sth...
    }
    assert(times == prev_buf_size);


//    for(int i = 0 ; i < prev_buf_size; ++i){
//        data = (io_data *)io_uring_cqe_get_data(cqe + (i & mask));
//        ERROR:  data is sometimes a null pointer here!
//        // do sth.
//    }
```

**Comment by ammarfaizi2** [comment]
I'm not sure what you're doing, but advancing the CQ before the
`io_uring_for_each_cqe()` will skip the CQE. Maybe you want something
like this?

```
err = io_uring_wait_cqe_nr(&ring, &cqe, n);
io_uring_for_each_cqe(&ring, head, cqe) {
	void *data;

	data = io_uring_cqe_get_data(cqe);
	// Check cqe->res
	// do something...

	++times;
}
io_uring_cq_advance(&ring, times);
```

**Comment by CaucherWang** [comment]
> 

Got that!  `io_uring_for_each_cqe` should be called before `advance` in order to obtain the `cqes`. Now it worked for me!
Then what about problem 1? Is there any wrong in the commented codes? (see `ERROR` in the 3rd line from the bottom)

**Comment by ammarfaizi2** [comment]
> Then what about problem 1? Is there any wrong in the commented codes? (see `ERROR` in the 3rd line from the bottom)

Oh, I was not clear about that. I thought your pointer arithmetic was
indexed from `0` to `N - 1` where `N` is the size of the CQ array.

When do you
```
io_uring_wait_cqe_nr(&ring, &cqe, nr);
```
the `cqe` can be located at any index depending on the CQ head value,
so `cqe + (i & mask)` can still be out of bounds.

`cqe + (i & mask)` calculation only works if the `cqe` points to the
first member of `ring->cq.cqes` array.

You can of course get the head information from `ring->cq.khead` and
continue the iteration. But that is reinventing the
`io_uring_for_each_cqe` logic.

So just use this macro instead of doing it manually.

**Comment by CaucherWang** [comment]
OK, I now basically understood the interal logic. Thanks for your patient help!
I think it might be helpful if the documentation records the `for_each_cqe` macro and tells the user to use that after `wait_cqe_nr`.

**Comment by ammarfaizi2** [comment]
Note:
> assert(times == prev_buf_size);

Your assertion on this may not always be true, sometimes you have to
`break;` the `io_uring_for_each_cqe()` manually if the value of
`times` meets the expected condition.

If you have more than `nr_wait` in-flight submissions, the number of
iterations in `io_uring_for_each_cqe()` can be more than `nr_wait`
because the kernel can generate more CQEs while you're iterating the
CQ array.

```c
// Assuming the number of in-flight submissions is 15
nr_wait = 10;
err = io_uring_wait_cqe_nr(&ring, &cqe, nr_wait);
times = 0;
io_uring_for_each_cqe(&ring, head, cqe) {
	// do something with cqe

	++times;
}
io_uring_cq_advance(&ring, times);

assert(nr_wait == times); // May trigger assertion error
```

When a completion is generated, the CQ tail value is updated.
`io_uring_for_each_cqe()` macro always reloads the tail value in every
iteration using `io_uring_smp_load_acquire()`. So you can get more
than what you have waited for.

**Comment by CaucherWang** [comment]
Oh!!! got that! Luckily, in my program there are no on-the-fly submissions. :)
