### ISSUE TITLE
Problem with defered completion and sqpoll thread (v6.1.1)

### ISSUE THREAD

**Issue by lano1106** [axboe/liburing#758]
The issue has been triggered by converting code that was using single shot recv() sqes to a single multishot recvmsg().

Here is the scenario:

1. A poll is armed to serve a multishot recvmsg()
2. A task_work is added when the socket POLLIN waiters are notified of new data available to read
3. A cqe will be added with io_post_aux_cqe() from io_recv_finish()
4. After going to the retry_multishot label from the goto, io_buffer_select() fails and -ENOBUF is returned (that is my application problem that I still need to figure out!).
5. io_poll_task_func() calls io_req_task_complete() which will call io_req_complete_defer()
6. Now because the whole point of multishot recvmsg is to remove the need to continually rearm the call by sending new sqes, the sqpoll thread will never flush the defered cqe because it never receive new sqes. It will go to sleep and keep sleeping forever from there and defered cqe will never be posted...

**Comment by lano1106** [comment]
Here is a little update. It turns out that my app is not leaking buffers. It is just that the beast that multishot-recvmsg is was doing 512 reads and taking every single available buffers in a single iteration!

I did double the number buffers to 1024 and it seems like I am having a winner this time. This indicates me that the cqe submission batching feature that you are cooking up for 6.2 might help...

That being said, the problem initially described is still a valid issue. It is just that I am not hitting it anymore...

**Comment by lano1106** [comment]
1024... is still not enough yet. multishot recvmsg has been able to perform 1024 reads in a single iteration... It may require 2048 buffers... but bottomline, from now it is only a tweaking issue from here...

**Comment by lano1106** [comment]
Here are some latency results that I got with various feature combinations by receiving WebSockets updates over a TLS encrypted TCP connection with a server behind Cloudflare
```
beta server with single shot recv:
[2022-12-22 15:14:13] INFO Main/processCollectedData rtt min/avg/max/mdev = 16.874/24.192/61.332/9.876 ms

beta server with single shot recv and napi busy poll:
[2022-12-19 13:07:23] INFO Main/processCollectedData rtt min/avg/max/mdev = 14.877/15.436/19.129/0.377 ms

beta server with beta multishot recvmsg, napi busy poll (kernel v6.1.1):
[2022-12-25 19:47:48] INFO Main/processCollectedData rtt min/avg/max/mdev = 13.910/14.367/18.887/0.279 ms
```
the multishot thing is amazing! I have spent literally a month and a half to optimize my client code. I must have succeeded on improving it reaction time by 20% which is quite an solid accomplishment but this did only translate into shaving few dozen of uSecs...

By only activating multishot recvmsg, this did make gain close to 1 mSec!

this thing is amazing!

**Comment by axboe** [comment]
Those are indeed nice results. multishot with provided ring buffers is almost like magic imho.

What napi patches are you using?

**Comment by lano1106** [comment]
more or less the one that I did offer to the list in march (I had to refactor it with all the ongoing refactoring on your side...). 2022 has not been an easy year for me. I finally did not have the time for other side projects but I saw that someone took over the effort... I am not too sure what has been the conclusion of it... The only difference with what I have offered is that I am filtering more sockets to include in the busy polling list based on a concern Jakub did express. Personally, it does not make any difference in the way I use it but this was the first step toward a possible resubmission

```
+	sk = sock->sk;
+	if (!sk || !sk_can_busy_loop(sk))
+		return;
```
prior to that, the original submitted patch was only checking on the global setting like epoll does with net_busy_loop_on()

**Comment by lano1106** [comment]
Also, I don't know if it can help to know this info but I have run the Google profiler on my client and  _io_uring_get_cqe() is the #1 hotspot by taking over 30% of the application processing time...
```
Using local file prof.data.
Total: 142857 samples
   46560  32.6%  32.6%    46643  32.7% _io_uring_get_cqe
    3785   2.6%  35.2%    40147  28.1% lws_ws_client_rx_sm_impl (inline)
    2335   1.6%  36.9%     2578   1.8% __default_morecore@GLIBC_2.2.5
    2027   1.4%  38.3%     2027   1.4% memcpy@GLIBC_2.2.5
    1643   1.2%  39.4%     1643   1.2% __nss_database_lookup@GLIBC_2.2.5
    1376   1.0%  40.4%    20974  14.7% ssl3_get_record (inline)
```
I am not sure if this includes the time inside the kernel or not. Knowing this would be important...

Besides that, I did look a little bit at the code. It is already very tight... Besides replacing a few logical operators with bitwise operator to remove a few branches that is definitely beneficial on x86 processors, I don't know what else could be improved...

**Comment by lano1106** [comment]
I have just spotted something.

if INT_FLAG_REG_RING was equal to IORING_ENTER_REGISTERED_RING

you could replace

```
		if (ring->int_flags & INT_FLAG_REG_RING)
			flags |= IORING_ENTER_REGISTERED_RING;
```
with
```
	flags |= ring->int_flags & INT_FLAG_REG_RING;
```
or even with
```
	flags |= ring->int_flags;
```
for as long as int_flags only possible values are 0 or INT_FLAG_REG_RING

**Comment by lano1106** [comment]
I have completed a much smaller profiling run with the queue patch... Unless a major refactoring of the function, one cannot hope for miracles but the micro-optimization proposal appears to slightly improve the function performance...

```
Using local file ./test_kraken_pub.
Using local file prof.data.
Total: 38285 samples
   11929  31.2%  31.2%    12041  31.5% _io_uring_get_cqe
    1073   2.8%  34.0%    10961  28.6% lws_ws_client_rx_sm_impl (inline)
     610   1.6%  35.6%      610   1.6% memcpy@GLIBC_2.2.5
     481   1.3%  36.8%      509   1.3% __default_morecore@GLIBC_2.2.5
     362   0.9%  37.8%      362   0.9% __nss_database_lookup@GLIBC_2.2.5
     355   0.9%  38.7%     1518   4.0% rapidjson::GenericReader::Transit (inline)
     351   0.9%  39.6%      351   0.9% pthread_mutex_lock@@GLIBC_2.2.5
     334   0.9%  40.5%      334   0.9% gcm_ghash_clmul
     333   0.9%  41.3%      333   0.9% _init@6e000
     331   0.9%  42.2%     6677  17.4% ssl3_read_bytes

```

**Comment by lano1106** [comment]
result with bitwise operator patch + INT_FLAG_REG_RING = IORING_ENTER_REGISTERED_RING to remove few more branches in queue.c
```
Using local file ./test_kraken_pub.
Using local file prof.data.
Total: 129333 samples
   41375  32.0%  32.0%    41750  32.3% _io_uring_get_cqe
    3606   2.8%  34.8%    35353  27.3% lws_ws_client_rx_sm_impl (inline)
    1936   1.5%  36.3%     1936   1.5% memcpy@GLIBC_2.2.5
    1927   1.5%  37.8%     2137   1.7% __default_morecore@GLIBC_2.2.5
    1309   1.0%  38.8%     1309   1.0% __nss_database_lookup@GLIBC_2.2.5
    1265   1.0%  39.8%    24256  18.8% ssl3_read_bytes
    1262   1.0%  40.7%     1262   1.0% gcm_ghash_clmul
     291   0.2%  70.9%    42925  33.2% iouring_poll
```
I am buying that... A 0.6% improvement... I may have skewed a bit the results as in the last run, I did register my ring fd. A feature that I was even not aware that it existed before looking into _io_uring_get_cqe code...

that being said, I have a hard time understanding how 30% of the time can be spent in this function while its caller is nowhere to be seen (iouring_poll) unless it is looping endlessly because of a problem that I fail to see...

or the time spent waiting inside the system call is attributed to the caller function but if it was the case, my micro-optimizations would not make any perceivable difference in the timing...

**Comment by lano1106** [comment]
I have perfected my profiling education... the google profiler is using the ITIMER_PROF timer which delivers a SIGPROF signal upon expiration which means that it will be delivered upon exiting the kernel.

So that means that all the time spent waiting in io_uring_enter will be credited to _io_uring_get_cqe.

Perhaps, if you are curious and you have benchmark programs that do go through _io_uring_get_cqe, it would be to use your benchmark programs to measure if my ideas make any difference at all...

**Comment by lano1106** [comment]
My initial analysis may be off a little bit but after putting this fact aside, there is a problem.

as soon as a multishot terminates, the last cqe is not commited. I have stumbled into the issue with ENOBUF.
Now, that I have fixed my buffering issue, the problem has reappear now that i am trying to combine ktls with multishot, ktls is notorious to occasionally return EMSGSIZE and EBADMSG from recvmsg(). Those cqes are not put into the cq ring.

**Comment by lano1106** [comment]
I created a small test in an attempt to reproduce my issue.
https://github.com/lano1106/io_uring_tests/blob/main/test_recvmsg_multishot_sqpoll.cpp

and it did not successfully reproduce the problem. It works as expected.

So my initial analysis is obviously wrong. My latest hypothesis is that I got a cq ring overflow. My code was having exactly the same number of cqe in the cq ring than I have buffers. Therefore, if I ended up with a ENOBUFS situation, more likely than not, the cq ring was full.

I am not 100% sure how io_uring cache overflowed cqe but maybe checking the presence of them and if new space has been made available before going to sleep could be a good idea...

**Comment by isilence** [comment]
> So that means that all the time spent waiting in io_uring_enter will be credited to _io_uring_get_cqe.
> 
> Perhaps, if you are curious and you have benchmark programs that do go through _io_uring_get_cqe, it would be to use your benchmark programs to measure if my ideas make any difference at all...

Sounds like profiling with perf would've been a better fit, like this

```sh
perf record -- <prog>
perf report
```

**Comment by isilence** [comment]
> It seems like the sqpoll thread code never calls io_cqring_overflow_flush(). Is calling this function from sqpoll code has ever been considered or is forcing the app to call io_uring_enter if the IORING_SQ_CQ_OVERFLOW flag is set part of the contract and just emptying the cqring not enough to keep things running?

Yeah, it's a part of the contract just as `IORING_SQ_NEED_WAKEUP` for waking up sleeping sqpoll, but we can add the flush if there are performance reasons for that.

**Comment by lano1106** [comment]
Pavel, no I am good now that I fully understand the contract. I have been caught in an exceptional situation that should never occur under normal circumstances.

Since my last comment, I went ahead and added a call to io_uring_cq_has_overflow() as an extra condition to for calling io_uring_enter() to prevent future stalling like this one
