### ISSUE TITLE
question: io_uring_enter EAGAIN return

### ISSUE THREAD

**Issue by tmds** [axboe/liburing#76]
hi, I have a question about io_uring_enter and EAGAIN.

When to_submit is zero, can io_uring_enter return EAGAIN?

When to_submit is not zero, can io_uring_enter return 0? And if so, when does it return 0, and when EAGAIN?

**Comment by isilence** [comment]
I wouldn't assume it won't in the future, but from what I see in the code (5.7), it can't.
Maybe except polling case, where a driver may decide to return that on ->poll() call.
