### ISSUE TITLE
Question/Bug:  Unexpected -EAGAIN returned in CQE res field

### ISSUE THREAD

**Issue by kelleymh** [axboe/liburing#766]
Consider the simple case of submitting a readv operation via io_uring_enter(), with no polling or other special flags.  If the readv op is unable to immediately obtain a blk-mq tag in blk_mq_submit_bio(), it doesn’t wait.  Control returns to io_queue_sqe(), which calls io_queue_async() to retry the operation.  io_uring_enter() then completes normally.   An iou-wrk-XXXX thread resubmits the I/O and waits for a tag as necessary.  Eventually the readv completes normally and the CQE res field indicates success.

Now consider the more complex case where blk_mq_submit_bio() splits the bio because the transfer size exceeds the limits for the target device.  If all bio’s making up the original request fail to immediately get a tag, then the same retry procedures are used.  An iou-wrk-XXXX thread resubmits the I/O and waits for tags as necessary, and eventually the readv completes normally.

But if some of the split bio’s get a tag immediately while others do not, the retry doesn’t happen.  For the bio’s that get a tag, those chunks of the original I/O are completed.  But the overall readv returns -EAGAIN in the CQE res field because of the bio’s that couldn’t immediately get a tag.

Is this expected behavior?  It seems desirable for io_uring code to retry the readv in this case like in the other cases, rather than requiring user space to do the retry.  But I’m just learning about io_uring and how it interacts with the blk-mq layer, and I don’t see a straightforward way to fix this.

Thoughts?

**Comment by axboe** [comment]
No, that does not seem like desirable behavior, we should not be returning -EAGAIN for that case. I'm going to try and write a test case for this and see what goes wrong so we can get that fixed.

**Comment by axboe** [comment]
Forgot to ask - what kernel are you testing with?

**Comment by axboe** [comment]
And finally, what type of device is this? SCSI based devices have some quirks that make retry really difficult.

**Comment by kelleymh** [comment]
I've observed the problem with a 5.15 kernel and a 6.1 kernel.  I have not tested the versions in between, but the code paths and decision-making seem to be the same with 5.15 and 6.1.

The device is an NVMe disk, using the standard Linux NVMe driver.  I should have stated that the readv op is directly against the raw device (i.e., /dev/nvme0n1), which was opened with O_DIRECT.

**Comment by axboe** [comment]
Try this and see if it makes a difference:

```
diff --git a/block/blk-merge.c b/block/blk-merge.c
index 35a8f75cc45d..9bf3d03f3dde 100644
--- a/block/blk-merge.c
+++ b/block/blk-merge.c
@@ -364,6 +364,8 @@ struct bio *__bio_split_to_limits(struct bio *bio,
 	if (split) {
 		/* there isn't chance to merge the splitted bio */
 		split->bi_opf |= REQ_NOMERGE;
+		split->bi_opf &= ~REQ_NOWAIT;
+		bio->bi_opf &= ~REQ_NOWAIT;
 
 		blkcg_bio_issue_init(split);
 		bio_chain(split, bio);
```

**Comment by axboe** [comment]
Another variant:

```
diff --git a/block/blk-mq.c b/block/blk-mq.c
index c5cf0dbca1db..edf4913280fc 100644
--- a/block/blk-mq.c
+++ b/block/blk-mq.c
@@ -2951,8 +2951,14 @@ void blk_mq_submit_bio(struct bio *bio)
 	blk_status_t ret;
 
 	bio = blk_queue_bounce(bio, q);
-	if (bio_may_exceed_limits(bio, &q->limits))
+	if (bio_may_exceed_limits(bio, &q->limits)) {
+		if (bio->bi_opf & REQ_NOWAIT) {
+			bio->bi_status = BLK_STS_AGAIN;
+			bio_endio(bio);
+			return;
+		}
 		bio = __bio_split_to_limits(bio, &q->limits, &nr_segs);
+	}
 
 	if (!bio_integrity_prep(bio))
 		return;
```

**Comment by kelleymh** [comment]
Both variants solve the problem in my limited test case.  To test/debug the scenario,  I’m artificially generating a failure to get a blk-mq tag on a semi-random basis.   I have a more real-world test scenario that generates lots of I/O using ‘fio’ and really does run out of tags.  It will take me more time to set that up and verify either or both fixes in that more dynamic environment.

The first fix causes the caller of io_uring_enter() to wait until tags are available for all bio’s that make up the original request.  Is io_uring_enter() allowed to pend in that way when submitting requests?  For the second fix, any request that requires splitting is immediately routed to the io_uring retry mechanism and re-submitted by an io_uring worker thread.  The splitting and any waiting for tags is done by the worker thread.  So these are two somewhat different approaches.

For the first variant clearing the REQ_NOWAIT flag, I don’t have a good sense of potential impact on other users of that flag besides io_uring.

**Comment by axboe** [comment]
Yes, they are different approaches. I've cooked up a better patch which only triggers the EAGAIN if we're actually going to split the bio, but it ends up being a bit more involved as all callers now need to handle it. I do think that's the better approach. It's still not perfect, as it is perfectly possible that a split bio will end up successfully submitting all of the split components. But there's really no way of knowing that... Hence the solution has to be either to allow all the split bios to potentially block on submission, or simply disallow splitting with REQ_NOWAIT upfront.

If we just clear REQ_NOWAIT on the split bio and constituent bios, then we'll block off REQ_NOWAIT submissions which isn't ideal. It won't break anything, but it will stall submissions potentially.

**Comment by axboe** [comment]
I send out two patches for this:

https://lore.kernel.org/linux-block/20230104160938.62636-1-axboe@kernel.dk/

**Comment by kelleymh** [comment]
These two patches work for my io_uring artificial test case.  The readv op is immediately routed to the retry path where the iou-wrk-XXXX thread can wait as necessary to get blk-mq tags.

I'll try the two patches in my more dynamic "real" environment and post a "Tested-by" to LKML if all looks good.

**Comment by axboe** [comment]
Perfect, that sounds good.

If you have time, it would also be interesting to look at any potential performance differences that you see between the posted patch series and the two-liner REQ_NOWAIT disable from:

https://github.com/axboe/liburing/issues/766#issuecomment-1370350759

**Comment by kelleymh** [comment]
Some of our "real" workload is now running without any -EAGAINs, which is a big improvement.   But other parts are still getting -EAGAIN.  I'm debugging to see why.   The patches certainly look right, so something unexpected is happening.  Hopefully I'll have an update in the next couple of days.

**Comment by kelleymh** [comment]
Even with this fix, there's still a case where the io_uring readv op completes with -EAGAIN.   If the total bytes requested in the readv exceeds BIO_MAX_VECS * PAGE_SIZE (i.e., 256 * 4096 = 1 Meg), the submission path goes to __blkdev_direct_IO(), which allocates and submits multiple bio's associated with a single dio.  The statuses from these multiple bio's are accumulated in the dio in blkdev_bio_end_io().  Like in the split bio case, if one of the bio's can't immediately get a tag, bio_wouldblock_error() sets that bio->bi_status to BLK_STS_AGAIN.  Even if other bio's associated with the dio can immediately get a tag and do the I/O for that chunk, the dio overall completes with -EAGAIN, though a portion of the I/O might have been completed.

**Comment by axboe** [comment]
@kelleymh  Can you try with this added:

```
diff --git a/block/fops.c b/block/fops.c
index 50d245e8c913..ab3140315828 100644
--- a/block/fops.c
+++ b/block/fops.c
@@ -368,6 +368,8 @@ static ssize_t blkdev_direct_IO(struct kiocb *iocb, struct iov_iter *iter)
 			return __blkdev_direct_IO_simple(iocb, iter, nr_pages);
 		return __blkdev_direct_IO_async(iocb, iter, nr_pages);
 	}
+	if (iocb->ki_flags & IOCB_NOWAIT)
+		return -EAGAIN;
 	return __blkdev_direct_IO(iocb, iter, bio_max_segs(nr_pages));
 }
 ```

**Comment by kelleymh** [comment]
This works.  My test cases that previously failed are now working.  One set of tests isn't running due to some kind of test infra problem.  Hopefully that gets resolved in the next day or two, and then I'll be 100% satisfied.  But that set of tests was already working with the fix to bio splitting, so I'm not expecting to surface any new problems.

**Comment by axboe** [comment]
OK good, thanks for testing!

**Comment by axboe** [comment]
First commit is upstream, 2nd one posted and will go upstream later this week. Closing this one up.

**Comment by axboe** [comment]
Note that 5.15-stable and newer stable should get this automatically, they already have the previous commits.
