### ISSUE TITLE
IOSQE_IO_LINK vs. submit

### ISSUE THREAD

**Issue by jclaisse** [axboe/liburing#769]
Hi,

I want to do IO linked. For that, I try to use the IOSQE_IO_LINK. It works well but it seems that the 2 following sequences gives the same results:
* Sequence 1
  - for i=0; i < 4; i++
    - prep all entries with the IOSQE_IO_LINK
    - submit
  - for i=0; i< 4; i++
    - wait cqe
    - check results
* Sequence 2
  - for i=0; i < 4; i++
    - prep all entries with the IOSQE_IO_LINK expect **for the last one**
    - submit
  - for i=0; i< 4; i++
    - wait cqe
    - check results

More generally, what does occur to the next entry after a submit if the IOSQE_IO_LINK flag is set ? 

Sequence 1, from the documentation, I was expected that all entries are linked and all IO are done sequentially. But it seems that the link tails when the submit is called and that there are 4 linked list of entry performing concurrently (like for the Sequence 2).

My liburing version is 243477691678af27dafe378f1e19be5df61e9daf.

Regards,

**Comment by axboe** [comment]
A chain of links terminates when either of these conditions are met:

1) One request doesn't have IOSQE_IO_LINK set
2) Requests are submitted

Hence there's no difference between the two examples. Generally it's cleaner to NOT set IOSQE_IO_LINK when the chain is done, rather than rely on submission terminating it.

I don't follow your last part. For a chain, each request is started when the previous finishes. They are executed serially.

**Comment by jclaisse** [comment]
Thank you for the quick answer !

I did find this information. Maybe the documentation might be updated?

For the last part, I was just trying to reformulate the question but it is not really clear (an example is always better) and you perfectly answer to the issue.

**Comment by axboe** [comment]
What I mentioned is all documented:

```
       IOSQE_IO_LINK
              When this flag is specified, the SQE forms a link with the next  SQE
              in the submission ring. That next SQE will not be started before the
              previous request completes. This, in effect, forms a chain of  SQEs,
              which  can  be arbitrarily long. The tail of the chain is denoted by
              the first SQE that does not have this flag set. Chains are not  sup‐
              ported  across submission boundaries. Even if the last SQE in a sub‐
              mission has this flag set,  it  will  still  terminate  the  current
              chain. This flag has no effect on previous SQE submissions, nor does
              it impact SQEs that are outside of the chain tail. This  means  that
              multiple chains can be executing in parallel, or chains and individ‐
              ual SQEs. Only members inside the chain are serialized. A  chain  of
              SQEs  will  be  broken,  if any request in that chain ends in error.
              io_uring considers any unexpected result an error. This means  that,
              eg, a short read will also terminate the remainder of the chain.  If
              a chain of SQE links is broken, the remaining unstarted part of  the
              chain  will be terminated and completed with -ECANCELED as the error
              code. Available since 5.3.
```

Maybe you didn't find it, or perhaps it isn't clear enough? If the latter, please do send a suggestion on how to improve it.

**Comment by jclaisse** [comment]
I don't know if it could be better. I missed the "Chains are not supported across submission boundaries". It might be reformulated like that:
"Furthermore, an implicit tail of chain is also inferred across submission boundaries."

**Comment by jclaisse** [comment]
Yes surely.
This is a point that I missed because I'm a new user of liburing.
Many thanks for your time.
