### ISSUE TITLE
question: IORING_FEAT_SUBMIT_STABLE and write/send payload

### ISSUE THREAD

**Issue by tmds** [axboe/liburing#77]
Does `IORING_FEAT_SUBMIT_STABLE` mean send/write payloads (`IORING_OP_SEND*`/`IORING_OP_WRITE*`) are copied to the kernel on `io_uring_enter`? Or should the application leave those buffers intact until the operation completes?

**Comment by sumeetb25** [comment]
I believe if the application has setup SQPOLL then the buffers need to be intact until completion. Else they are copied over on io_uring_enter

**Comment by axboe** [comment]
Payloads are not copied, only the aux data passed in (like iovecs, etc). So regardless of whether or not you're using SQPOLL, the data must remain valid until completion.
