### ISSUE TITLE
List of APIs of missing man page

### ISSUE THREAD

**Issue by heyrutvik** [axboe/liburing#777]
- [x] io_uring_prep_link_timeout
- [x] io_uring_prep_send_zc_fixed
- [x] io_uring_prep_sendmsg_zc
- [x] io_uring_prep_send_set_addr
- [x] io_uring_prep_getxattr
- [x] io_uring_prep_setxattr
- [x] io_uring_prep_fgetxattr
- [x] io_uring_prep_fsetxattr
- [ ] io_uring_cq_eventfd_enabled
- [ ] io_uring_cq_eventfd_toggle
- [ ] io_uring_queue_mmap
- [ ] io_uring_ring_dontfork
- [x] io_uring_register_buffers_tags
- [x] io_uring_register_buffers_sparse
- [x] io_uring_register_buffers_update_tag
- [x] io_uring_register_files_tags
- [x] io_uring_register_files_update_tag
- [x] io_uring_register_files_update
- [ ] io_uring_register_probe
- [ ] io_uring_register_personality
- [ ] io_uring_unregister_personality
- [ ] io_uring_register_restrictions
- [ ] io_uring_enable_rings
- [ ] io_uring_get_probe_ring
- [ ] io_uring_for_each_cqe
- [ ] io_uring_prep_msg_ring_fd

Do let me know if some of them don't require man pages or I missed any. Cc @axboe

**Comment by heyrutvik** [comment]
Got it. Thanks.

> io_uring_wait_cqes
> Puzzled, this one does have a man page?

True. My bad. Removing it from the list.

How will changes be easy to review? Separate commit for each API in single PR? Or Multiple PR groped by related APIs?

**Comment by axboe** [comment]
Just one PR ideally, and then a commit for each change.

**Comment by ammarfaizi2** [comment]
- [ ] io_uring_for_each_cqe
