### ISSUE TITLE
question: partial completion of write/sends

### ISSUE THREAD

**Issue by tmds** [axboe/liburing#78]
With regular `sendmsg`/`write` calls, the number of bytes returned can be less than the length of the buffer. The application should then make another call to send the remaining part. Is this also the case for `IORING_OP_SEND*`/`IORING_OP_WRITE*`? Or does `io_uring` handle this internally?

In case these operations are linked (`IOSQE_IO_LINK`), how does a partial send affect the next operation?

**Comment by axboe** [comment]
Yes, you need to submit again for the remainder, don't rely/depend on io_uring doing that for you. For short reads/writes, generally the chains are broken.
