### ISSUE TITLE
Direct descriptor limitations

### ISSUE THREAD

**Issue by FrankReh** [axboe/liburing#780]
Confused that man pages say any io_uring request that takes a file descriptor can use a direct descriptor but many io_uring requests explicitly disallow them.

Example of a man page: https://github.com/axboe/liburing/blob/d32d53b65377d846635387ce6c1cd2ed0d700f92/man/io_uring_prep_openat2.3#L46-L48

Example device source: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tree/io_uring/statx.c?h=v6.1.9#n30

Here's the list of uring requests that don't appear to support the direct descriptor based on looking through the source:

- renameat
- unlinkat
- mkdirat
- symlinkat
- linkat
- statx
- close (the normal uring close - there is a close_direct that is supported but it doesn't take a flag, it uses the file_index field)
- getxattr
- setxattr

**Comment by sesse** [comment]
I also hit the statx() one… that's pretty confusing. Seemingly no way to do fstat() on an opened direct descriptor, then; even disregarding correctness, you'll have to choose between doing the name lookup twice and not getting direct descriptors.

**Comment by FrankReh** [comment]
> doing the name lookup twice

I didn't get far enough where I needed a solution but I thought opening as a regular file descriptor, use any of the operations listed above, and then registering it as a fixed file descriptor was a way forward. It might require extra book keeping about which reserved fixed file descriptor slots were available.

**Comment by sesse** [comment]
The problem is that you can't link an open+statx together then, no? You'd have to go a trip through userspace to get the fd return from open registered and into the prep_statx() call.
