### ISSUE TITLE
Is there a synchronous fixed file slot close operation

### ISSUE THREAD

**Issue by FrankReh** [axboe/liburing#783]
Is there a synchronous call, like a register or an unregister, that lets us close a single entry in the fixed file table?

It's clear the async form is followed by the liburing's io_uring_prep_close_direct definition.

I thought I had seen a synchronous way of doing that, but now that I want to use, I can't find it. Maybe it doesn't exist.

The reason I ask is in our Rust package, we would have preferred to keep our destructor for a file representing a fixed file index purely synchronous. But if it can't be, it can't be.

**Comment by axboe** [comment]
I doesn't exist. Curious on what the use case is?

**Comment by FrankReh** [comment]
We try to steer the user of the tokio-uring crate towards the async close operation so they see the close return value but if they let the wrapper to the file descriptor go out of scope without explicitly closing it, we perform a synchronous close of the file descriptor, but when the wrapper is of a fixed file descriptor, we will have to initiate the async close. The drop of our structure has to be synchronous, by the nature of Rust, but we can initiate an async operation synchronously, we just don't wait for the response.

I think it will work this way but its a little more complicated. It means the user doesn't get their fixed slot index back right away - and we don't have a convenient way of telling them when they do. At least not with the auto selection - and I'm only coding the auto-selection path right now. If the requests for fixed table space were actually targeting a slot, I know the old value would be closed as the slot was reused. But for our first use of fixed files, we're not giving the user that choice - just automatic selections made by the device itself.

Given the current API, my plan is to initiate the async close for the fixed (aka direct) index. And the user just doesn't know when the table has another open slot but if they allocated enough to start with, they won't care. With a lot more logic, we could code the fact that a close was in-flight so if an open fails, the code could retry after waiting.

Mostly I wanted to make sure I wasn't over looking something. I'm not sure that my one use case, for the drop of a file or socket without expressly closing it first, warrants even asking for it. Not having it is not a show stopper for us. In fact, by not having it in 6.1 already probably means we'd have to code for the 6.1 case anyway. 6.1, being an LTS release, seems like the sweet spot for us to target the tokio-uring library to, given the amount of io_uring functionality it brings to the table.

(A few minutes later.)
While rereading my response, I realize we would have one more option but at the moment it seems draconian. But maybe not ...
In our synchronous drop, we could build in a mechanism that started the async operation and then used the submit_and_wait mechanism to actually be blocked. We could block in a busy loop for a minimum of one response at a time, knowing that eventually the one we are looking for is going to be completed. I'd be afraid that blocks our thread for a long period of time if the SQE to close wasn't serviced soon - maybe slower jobs were in front of it for example, or that the amount of time we had to wait would look minimal in our testing but only under some user's more complicated environment, the wait time could explode.

Thanks for the quick response.

**Comment by axboe** [comment]
It could of course be added, but basically all close operations will complete immediately. The exception are odd files that have a ->flush() method, like NFS. Those can obviously take a bit longer. But the approach of just reaping events until it happens would be fine. Completions aren't ordered, so whatever completes the soonest will show up first. Hence normal close waits should be fast, and generally done by the time your submit completes (eg a submit_and_wait() may make sense here).

**Comment by FrankReh** [comment]
I like that reasoning.

Sorry for a follow-up question then. close(2) doesn't force a flush - was my understanding, and you aren't implying the io_uring close adds a flush first - I'm guessing (oh wait, it seems to).

(A few minutes later.) I see in the linux/io_uring/openclose.c the io_close function has a comment and code that "punts to async" by unlocking a file_lock and returning EAGAIN if a file has a flush method. That EAGAIN is enough to get the work punted I guess.

And now I realize the io_uring device has no flush opcode, so there is no way to flush a fixed file, and that also explains why the path for closing a fixed file doesn't check on a flush method. So if we have a file that needs flushing, we can't *open* it as a fixed file, but I guess we could still add it to the fixed file table when we create the fixed file table in the first place.

Creating a fixed file table with entries already populated by file descriptors, like NFS or anything else, may not fit our model for providing the fixed file performance feature to the tokio-uring user. I regret saying that, I normally want to let the user get as many of the io_uring features as possible, but I don't see how we can mix some entries from prior established file descriptors and  others that are auto generated. On the other hand, maybe my thinking is too short sighted and I should really propose a model where the user can pick one or the other, they can register a table with prior known file descriptors and they can even have slots auto chosen for additional opens and accepts, especially multi-shot accepts - but if they want to add more file descriptors to the table manually, they have to be willing to lose any fixed table entries that had been created via the open or accept paths as they can't be saved. ... Oh wait, can they be saved by passing them to another ring? Yea I guess so. They could be passed to another ring even just temporarily and then passed back. The temporary ring could be built just for that purpose and then either released immediately or cached in case the user wants to do that more often.

Okay. Enough. Sorry that got so long winded.

So my one follow up question: what should we know about the io_uring device flushing for normal file descriptors when we issue the close? Is that more than happens when the close(2) is called directly?

**Comment by axboe** [comment]
I think you're mixing up some things here, the fops->flush() isn't really related to a sync/fsync or anything like that. And yes, close(2) very much does call it on close.

Closing a fixed file is just removing it from our internal table, that's a separate thing from the final close of the file.

There's a lot of other stuff in here, let's try and keep it relevant to the topic at hand. File other discussions, if anything remains.

**Comment by FrankReh** [comment]
Thank you.

**Comment by isilence** [comment]
Not reading into the thread too there is a way to close it "synchronously", just pass fd = -1 to `IORING_REGISTER_FILES_UPDATE`, (e.g. using `io_uring_register_files_update`).

**Comment by isilence** [comment]
There is one caveat for both, close requests and this sync option, they might not close it immediately but delay it in-kernel, but users can think of files as already closed.

**Comment by FrankReh** [comment]
@isilence Thank you for that idea. I will try to find the right place for that warning too. I think it reasonable that people/applications that want the extra security about closing will take a different path, not one that simply lets a File or Socket object go out of scope. Here, I was asking about the simplest way of getting the close sent in a synchronous way and getting the index cleared. :clap:

**Comment by isilence** [comment]
Then it sounds like this `IORING_REGISTER_FILES_UPDATE` method should suit you perfectly well.

**Comment by axboe** [comment]
Yeah good point, not sure why I didn't think of the normal io_uring_register(2) path which is in fact the original way to do this...
