### ISSUE TITLE
two threads: a thread only submits, another only peek_batch_cqe, is safety?

### ISSUE THREAD

**Issue by learnisgood** [axboe/liburing#784]
two threads,  a thread only submits, another only peek_batch_cqe,  is  safety?

**Comment by isilence** [comment]
It is safe. Be careful with old kernels, rings should have `IORING_FEAT_EXT_ARG` to be capable to safely wait on CQ with timeouts, e..g `io_uring_wait_cqe_timeout()`.

Note, any more complex types of sharing would require some synchronisation around queues' access.
