### ISSUE TITLE
feature request: indicate a request should not generate a completion event

### ISSUE THREAD

**Issue by tmds** [axboe/liburing#79]
When adding a set of linked request, the application is mostly interested when the last request completes. Completions of the `IOSQE_IO_LINK` requests are ignored.

Perhaps a flag can be added so these requests won't create completion entries, and they don't count for `io_uring_enter` `min_complete`?

**Comment by axboe** [comment]
This is already in motion, see:

https://lore.kernel.org/io-uring/67b28e66-f2f8-99a1-dfd1-14f753d11f7a@gmail.com/T/

and also:

https://github.com/axboe/liburing/issues/53

**Comment by tmds** [comment]
> This is already in motion, see:

Great!

In my use-case, I'm doing poll, linked tosend/rev.
The poll should be cancellable even when `IOSQE_IGNORE_CQE` is set.
It would be nice to ensure the linked requests can use the same `user_data`. This can then be used to cancel the linked sequence, and is used for the completion event.
It avoids having to generate unique `user_data` for each request of a linked sequence.

> #53

Maybe it makes sense to have a sentinel value for `user_data` that is detected when `IOSQE_IGNORE_CQE` is set? This value indicates the request isn't cancellable and avoids collisions with requests which are cancellable/generate completion events (and therefore need a `user_data`).

@axboe can you take a look at the questions I've added as issues?

**Comment by tmds** [comment]
> This value indicates the request isn't cancellable and avoids collisions with requests which are cancellable/generate completion events (and therefore need a user_data).

A use-case, next to LIBURING_UDATA_TIMEOUT, is with IORING_OP_ASYNC_CANCEL.
