### ISSUE TITLE
Unexpected CPU usage when working with mdraid array/brd drive

### ISSUE THREAD

**Issue by khristenkovladimir** [axboe/liburing#792]
Hi there,

Environment:
	Server: Supermicro SYS-220U-TNR;
	CPU: 2x Intel(R) Xeon(R) Platinum 8352Y CPU @ 2.20GHz (32 cores/64 threads);
	OS: Ubuntu 20.04.5;
	Kernel: 5.15.0-60-generic;
	fio: 3.16

When testing NVMe drive or other physical block device performance, the CPU cores are loaded in accordance with the test parameters (**--cpus_allowed=0-7**):
`fio --name=nvme --numjobs=8 --iodepth=16 --bs=4k --rw=randread --ioengine=io_uring --direct=1 --group_reporting=1 --filename=/dev/nvme0n1 --runtime=60 --time_based=1 --cpus_allowed=0-7`
![image](https://user-images.githubusercontent.com/11570512/219697639-21d1fe1e-cecf-43ec-a028-4337a575207b.png)

But when testing the mdraid array performance, I can see additional load on CPU cores that shouldn’t be used during testing: 
`fio --name=nvme --numjobs=8 --iodepth=16 --bs=4k --rw=randread --ioengine=io_uring --direct=1 --group_reporting=1 --filename=/dev/md0 --runtime=60 --time_based=1 --cpus_allowed=0-7`
![image](https://user-images.githubusercontent.com/11570512/219698043-2ebb628b-7d50-4450-9686-1dea28dccfb1.png)
The load on CPU cores 1-8 is totally expected but not on 9-32,73-96 cores.

Here are the mdraid5 array creation parameters: 
`mdadm --create /dev/md0 --level=5 --chunk=4K --bitmap=internal --raid-devices=3 /dev/nvme0n1p1 /dev/nvme1n1p1 /dev/nvme2n1p1`

The same behavior occurs during brd (RAM) disk testing (modprobe brd rd_nr=1 rd_size=10485760):
`fio --name=nvme --numjobs=8 --iodepth=16 --bs=4k --rw=randread  --ioengine=io_uring --direct=1 --group_reporting=1 --filename=/dev/ram0 --runtime=60 --time_based=1 --cpus_allowed=0-7`
![image](https://user-images.githubusercontent.com/11570512/219698532-9e47e3e8-ebb1-43e6-8107-55da489c6095.png)

What can be the cause of such behavior, and can this be fixed? I have also received same results on mdraid0 array and on Rocky Linux 8 with kernel 6.1. 

I’m looking to use uring module in SPDK on top of mdraid5 array and also get the same behavior there. 
Please let me know if any additional information is required from my side. 

Thank you in advance.

**Comment by isilence** [comment]
Smells like io-wq (io_uring worker pool). We need to set affinity for io-wq workers, `IORING_REGISTER_IOWQ_AFF` should be able to do it.

**Comment by axboe** [comment]
It does sound like that, but raid0 should work with nowait on newer kernels at least, but it happens on 6.1 as well? Setting io-wq affinity will help minimize the impact, but should not really be happening for raid0 in 6.1 to begin with...

**Comment by khristenkovladimir** [comment]
I have updated Ubuntu kernel to the latest 6.1.12-060112-generic.
I see that on mdraid5 and mdraid0 the issue is gone.

Is there any chance of getting the same behavior (fix the issue) on the Ubuntu 20.04 hwe kernel - 5.15.0-60-generic?

May I wonder what exactly caused this problem on kernel 5.15.0-60-generic?

Thank you.

P.S. On the brd disk the issue is still present(this is not critical for me at the moment, because my main goal is to work on top of mdraid5 array).

**Comment by axboe** [comment]
It happens when a driver doesn't support nonblocking operations. Rather than potentially block the submitting task, io_uring will punt the operation to a helper thread. Newer kernels do support no-wait for raid, and for brd, I did patch that up just recently and it'll be in 6.3 and has been marked for the stable kernels as well.

If you look at the pending changes for 6.3:

https://git.kernel.dk/cgit/linux-block/log/?h=for-6.3/block

you can find 3 brd patches from me there. I'm going to close this one up, as it has been answered.

**Comment by khristenkovladimir** [comment]
@axboe thank you!
