### ISSUE TITLE
Question: has btrfs async buffered writes made into a kernel release ?

### ISSUE THREAD

**Issue by boxerab** [axboe/liburing#795]
This LWN article describes the changes.

https://lwn.net/ml/linux-btrfs/20220901225849.42898-1-shr@fb.com/

I am currently running 6.1.11

Thanks.

**Comment by axboe** [comment]
Yes, it's in v6.0 and newer.

**Comment by boxerab** [comment]
Thanks! I've run my old [benchmark](https://github.com/axboe/liburing/issues/571) on btrfs system (Fedora) - puzzled that there is no significant timing difference between  synchronous,buffered, synchronous,direct ,  uring,buffered and uring,direct  on my system.

**Comment by boxerab** [comment]
question answered - many thanks. closing.
