### ISSUE TITLE
recv returns res 0 but flags is 4 (IORING_CQE_F_SOCK_NONEMPTY)

### ISSUE THREAD

**Issue by FrankReh** [axboe/liburing#797]
I don't have a minimal reproducer so maybe this isn't worth asking yet, but maybe someone already knows the answer.

When a test is shutting down, I see a server often reporting the unexpected response to an io_uring recv operation of a CQE with a res field of 0 but the flags field has the IORING_CQE_F_SOCK_NONEMPTY bit set. This happens for recv operations that are given a provided buffer group id belonging to a buf_ring. So since the operation was sent with a select buffer bit, the response was expected to have chosen a buffer. But no select buf bit is seen in these CQE responses. It makes sense if the zero res is saying the connection is closed and no buffer needs to be chosen anyway when the length would be zero. But how to interpret the bit saying the socket is nonempty? Does it have a different meaning in that case or should it be ignored as being invalid or can it mean the socket might have data, but this time around, zero data was pulled out so if you want, please try again?

Edit: 6.1.12 kernel.

**Comment by isilence** [comment]
Hard to tell without a way to reproduce, but it might be related to this:
https://github.com/torvalds/linux/commit/6466e715651f9f358e60c5ea4880e4731325827f

**Comment by FrankReh** [comment]
Oh, that does seem likely related. It *is* a tcp connection I'm seeing this on.

I'm currently treating it as "nothing more to read" so another `recv` is not going to be sent. I don't  know if that means the kernel's endpoint is going to be kept up longer than otherwise necessary - in which case I should figure out how to handle that to free the kernel resources earlier.

I agree, if I can create a reproducer from liburing, that would help us figure out if it's fine like this or something should be done to cover this case - on your end or mine. I'll keep this open a while in case I can get to it.
But you can also close this if you like because there's nothing left on your end to do. You've answered my question. I know you don't mind my reopening again when I have more data. Thank you.

**Comment by axboe** [comment]
Let's just close it, otherwise things tend to linger and never get closed. As you note, feel free to re-open should there ever be a need to do so.
