### ISSUE TITLE
zero-copy send doesn't have better performance

### ISSUE THREAD

**Issue by beef9999** [axboe/liburing#801]
My test was running on two physical machines (20Gbps bonding NICs), kernel version 6.2.0-1.el7.elrepo.x86_64.

First I setup a tcp server on one machine, and then run these two commands on the other, to compare `send_zc` and `send` performance.

`./example/send-zerocopy -n8 -s32768 -4 -t20 -D11.158.242.44 -p9527 -z1 tcp`
tx=1294016 (MB=40438), tx/s=64700 (MB/s=2021)

`./example/send-zerocopy -n8 -s32768 -4 -t20 -D11.158.242.44 -p9527 -z0 tcp`
tx=1528384 (MB=46343), tx/s=76419 (MB/s=2317)

The `send_zc` is even worse ...

**Comment by isilence** [comment]
First we'd need to check if it really was zc using `IORING_SEND_ZC_REPORT_USAGE`.

Please also post perf profiles, that would be helpful.
```
perf record -g
perf report > output_file.txt
```

**Comment by beef9999** [comment]
@isilence 
After adding `IORING_SEND_ZC_REPORT_USAGE `, cqe->res is still 0, rather than `IORING_NOTIF_USAGE_ZC_COPIED`. So it looks like it was not copied.



[perf.log](https://github.com/axboe/liburing/files/10810201/perf.log)

**Comment by beef9999** [comment]
I did, and I can recall the results didn't vary too much.

Instead of the bandwidth, what I actually concerned is the CPU usage. The zerocopy version didn't drop CPU usage but increased. I used to run the epoll zerocopy in the same test machine (available since kernel 4.18), and it could reduce 50% CPU.

**Comment by beef9999** [comment]
Could you share your test results?

**Comment by isilence** [comment]
That's what I wanted to ask, what is the CPU usage? I see lots of waiting in the logs, that hints that you might be under utilised, and comparing bandwidth in this case wouldn't make any sense. Try to pin it to a CPU, e.g. `taskset -c 0 <rest of the command>` and try the test again looking for CPU util.

With that being said, it's still interesting why it's lower. It may be latency, and e.g. additional scheduling effects from zc notifications. Let me cook up a patch for the example to try. Also, I'd rather omit -n8 and send more, it doesn't make much sense for TCP.

**Comment by isilence** [comment]
Another observation is that according to logs is that often it goes via the slow path (internal worker thread pool, aka io-wq), which is most probably due to sending too much and so clogging tx queues. Need to see if I can do sth about the test, but in the meanwhile, if I'm correct, if you do "-n1", it should mostly disappear.

**Comment by redbaron** [comment]
> Another observation is that according to logs is that often it goes via the slow path (internal worker thread pool, aka io-wq)

Just for my education, where do you see it?

**Comment by isilence** [comment]
> > Another observation is that according to logs is that often it goes via the slow path (internal worker thread pool, aka io-wq)
> 
> Just for my education, where do you see it?

In the @beef9999 's logs, look for io_wq, e.g. `io_wq_submit_work`

**Comment by isilence** [comment]
https://github.com/isilence/liburing/tree/sendzc-defer-taskrun

@beef9999, try this branch. It adds a new argument, pass "-d" to your test. It's not too likely to fix your problem, but I'd ask to run it and post profiles for copy and zerocopy runs and CPU utilisation.

**Comment by beef9999** [comment]
case 1:
./examples/send-zerocopy -n1 -s32768 -4 -t20 -D11.158.242.44 -p9527 -z0 -d tcp
tx=1616716 (MB=50363), tx/s=80835 (MB/s=2518)
CPU usage: 56%
[copy.txt](https://github.com/axboe/liburing/files/10839150/copy.txt)


case 2:
./examples/send-zerocopy -n1 -s32768 -4 -t20 -D11.158.242.44 -p9527 -z1 -d tcp
tx=1494701 (MB=46709), tx/s=74735 (MB/s=2335)
CPU usage: 48%
[zc.txt](https://github.com/axboe/liburing/files/10839152/zc.txt)

**Comment by isilence** [comment]
I tried to reproduce and was getting mixed results resembling yours until I defaulted network configs and got 1630 vs 1720 MB/s in favour of zerocopy. Was are you using on the receiving side? It was msg_zerocopy for me and I had to not forget to kill `SO_RCVBUF` / `SO_RCVLOWAT` configuration out of it as it completely ruins results for me.

**Comment by beef9999** [comment]
On the recv side, I was using a standard tcp socket on epoll. Didn't set any option except TCP_NODELAY.

**Comment by isilence** [comment]
> On the recv side, I was using a standard tcp socket on epoll. Didn't set any option except TCP_NODELAY.

It seems it's configuration specific. I can try to repro it if you share how do you run the rx side with code if it's self-written.

> 1720 was zerocopy?

Right

> Besides I can recall the current Linux kernel didn't support zerocopy receive until you have a NIC supports header-data splitting?

It just the name of the benchmark. Inside it's a normal `recv` throwing data away with `MSG_TRUNC`.

**Comment by beef9999** [comment]
@isilence I found it was `TCP_NODELAY` that caused the performance drop.

Below is my test code. If I comment out the `TCP_NODELAY` line, I'll get the appropriate results like yours. The copy version is slightly higher, though.

```c++
#include <sys/socket.h>
#include <netinet/in.h>
#include <netinet/tcp.h>
#include <string.h>
#include <stdlib.h>
#include <unistd.h>
#include <pthread.h>

void* handler(void* args) {
    int connfd = (int) (unsigned long) args;
    char buff[512];
    while (1) {
        read(connfd, buff, sizeof(buff));
    }
    return NULL;
}

int main() {
    int fd = socket(AF_INET, SOCK_STREAM, 0);
    if (fd < 0)
        abort();

    struct sockaddr_in server_addr, client_addr;
    memset(&server_addr, 0, sizeof(server_addr));
    server_addr.sin_family = AF_INET;
    server_addr.sin_addr.s_addr = htonl(INADDR_ANY);
    server_addr.sin_port = htons(9527);

    if (bind(fd, (struct sockaddr*) &server_addr, sizeof(server_addr)) != 0)
        abort();

    if ((listen(fd, 1024)) != 0)
        abort();

    socklen_t len = sizeof(client_addr);
    while (1) {
        int connfd = accept(fd, (struct sockaddr*) &client_addr, &len);
        if (connfd < 0)
            abort();

        int val = 1;
        if (setsockopt(connfd, IPPROTO_TCP, TCP_NODELAY, &val, sizeof(val)) != 0)
            abort();

        pthread_t thread_id;
        pthread_create(&thread_id, NULL, handler, (void*) (unsigned long) connfd);
    }
}
```

```bash
gcc -g  -O3 -Wall -o tcp-server tcp-server.c -lpthread

./examples/send-zerocopy -n1 -s32768 -4 -t10 -D11.158.242.44 -p9527 -z1 -d tcp
./examples/send-zerocopy -n1 -s32768 -4 -t10 -D11.158.242.44 -p9527 -z0 -d tcp
```

Do you have any suggestion on `TCP_NODELAY`, because almost all of our network programs have enable this feature. We used to think it's benifitial.

**Comment by beef9999** [comment]
**My code:** 
io_uring poll + non_blocking fd + sendmsg(fd, &msg, MSG_ZEROCOPY) 
20Gbps,  30% CPU

**The liburing zc example:**
13Gbps, 54% CPU

**Comment by isilence** [comment]
@beef9999, something doesn't stick with the results. You said you've been getting 16-18 Gbps before with io_uring before, what has changed? Let me also ask what is the bandwidth of your setup 2x20 Gbps?

There is one problem with the io_uring benchmark itself, namely the lack of any pacing / throttling, it just keeps pushing into it until stuck, which might be pushing requests to slow worker threads too often. There is no such thing when you poll for space in queues first as with epoll. Anyway, it still seems off, can you attach your poll version?

**Comment by isilence** [comment]
> There might be two major differences between your env and mine. 1. I'm using kernel 6.2 by CentOS el7, and I assume yours is the community version? 2. My NICs have bonding.

I was testing upstream, 6.3-rc*

**Comment by isilence** [comment]
@beef9999, what happened with your post about `TCP_NODELAY` and getting zc more or less on par with the copy version?

**Comment by beef9999** [comment]
@isilence 
1. I think the bonding NICs is useful when handling multiple connections, for this test there is only one. So the max bandwidth is 20G.
2. I noticed that the latest example in master has been changed by adding `IORING_SETUP_DEFER_TASKRUN | IORING_SETUP_SINGLE_ISSUER | IORING_SETUP_COOP_TASKRUN`. I re-run the new zc example, now it could reach the 20G limit. And CPU util is less than normal tcp, looks good.
3. `TCP_NODELAY` did have negative impact, but very small. Let's forget it.

**Comment by isilence** [comment]
Looking at some stats, io_uring spends too much time scheduling because of some internal details, that's a CPU waster. It should be better when there is more load, but it's still a good spot to try and tune. Luckily, there was a few ideas floating around.

A curious experiment: if we add some sleeping before waiting for CQEs (in cases when we do sleep / wait, e.g. the CQ is empty and we have to enter the kernel), the sys% CPU usage reduces from 22% to ~10%. The waiting time is hand picked for the setup to not hurt perf, it's kind of the ideal scenario that we can expect.

**Comment by beef9999** [comment]
@isilence One interesting thing I discovered during real work load tests is, if you just do send in the client and receive in the server, the zero copy send is not likely to surpass the libc send.

That’s because in a real scenario your send_zc should always proceed after the previous notify cqe has arrived.

The cqe notification is based on TCP ACK. Imagine you network round trip latency is 10 microseconds, so every send_zc has to wait for this period of time to start the next. But for the libc send, it just need to write to a buffer, and would immediately return to user space. So I can only observe by iftop that zc only has 4Gb bandwidth, while the libc send can reach 20Gb.

However, a more common case in networking scenario is send and receive, where you can easily observe the performance difference. Because the libc send now has a minimum 10 microseconds. The zero copy optimization starts to be effective.

In a word, zero copy is only supposed to set in a send-receive round trip.

**Comment by beef9999** [comment]
One more question, will short write occur in io_uring send_zc ?  (requested to send n, but eventually sent less than n)

**Comment by isilence** [comment]
> @isilence One interesting thing I discovered during real work load tests is, if you just do send in the client and receive in the server, the zero copy send is not likely to surpass the libc send.

If your CPU is under-utilised then that's so. However, if it's already 100% CPU, those extra cycles will go to throughput.  

> That’s because in a real scenario your send_zc should always proceed after the previous notify cqe has arrived.
> 
> The cqe notification is based on TCP ACK. Imagine you network round trip latency is 10 microseconds, so every send_zc has to wait for this period of time to start the next. But for the libc send, it just need to write to a buffer, and would immediately return to user space. So I can only observe by iftop that zc only has 4Gb bandwidth, while the libc send can reach 20Gb.
> 
> However, a more common case in networking scenario is send and receive in the client, where you can easily observe the performance difference. Because the libc version now has a minimum 10 microseconds. The zero copy optimization starts to be effective.
> 
> In a word, zero copy is only supposed to set in a send-receive round trip.

Well, no. If you're streaming data, you don't have to wait for the prev notification but can push more data using another buffer. And if you're concerned about memory consumption, in a copy mode the kernel will allocate that memory internally and keep it until it gets an ACK, which is less transparent.

**Comment by isilence** [comment]
> One more question, will short write occur in io_uring send_zc ? (requested to send n, but eventually sent less than n)

For TCP, io_uring will try to hide a short send, i.e. retry internally, but it can fail. IOW, in theory can happen but should be rare

**Comment by dreamlike-ocean** [comment]
> > [@isilence](https://github.com/isilence) One interesting thing I discovered during real work load tests is, if you just do send in the client and receive in the server, the zero copy send is not likely to surpass the libc send.
> 
> If your CPU is under-utilised then that's so. However, if it's already 100% CPU, those extra cycles will go to throughput.
> 
> > That’s because in a real scenario your send_zc should always proceed after the previous notify cqe has arrived.
> > The cqe notification is based on TCP ACK. Imagine you network round trip latency is 10 microseconds, so every send_zc has to wait for this period of time to start the next. But for the libc send, it just need to write to a buffer, and would immediately return to user space. So I can only observe by iftop that zc only has 4Gb bandwidth, while the libc send can reach 20Gb.
> > However, a more common case in networking scenario is send and receive in the client, where you can easily observe the performance difference. Because the libc version now has a minimum 10 microseconds. The zero copy optimization starts to be effective.
> > In a word, zero copy is only supposed to set in a send-receive round trip.
> 
> Well, no. If you're streaming data, you don't have to wait for the prev notification but can push more data using another buffer. And if you're concerned about memory consumption, in a copy mode the kernel will allocate that memory internally and keep it until it gets an ACK, which is less transparent.

How to understand “you don't have to wait for the prev notification”?
If I receive IORING_CQE_F_MORE from cqe.flag, can I proceed with the next send? Will this ensure the order of send operation?

**Comment by isilence** [comment]
> > > [@isilence](https://github.com/isilence) One interesting thing I discovered during real work load tests is, if you just do send in the client and receive in the server, the zero copy send is not likely to surpass the libc send.
> > 
> > 
> > If your CPU is under-utilised then that's so. However, if it's already 100% CPU, those extra cycles will go to throughput.
> > > That’s because in a real scenario your send_zc should always proceed after the previous notify cqe has arrived.
> > > The cqe notification is based on TCP ACK. Imagine you network round trip latency is 10 microseconds, so every send_zc has to wait for this period of time to start the next. But for the libc send, it just need to write to a buffer, and would immediately return to user space. So I can only observe by iftop that zc only has 4Gb bandwidth, while the libc send can reach 20Gb.
> > > However, a more common case in networking scenario is send and receive in the client, where you can easily observe the performance difference. Because the libc version now has a minimum 10 microseconds. The zero copy optimization starts to be effective.
> > > In a word, zero copy is only supposed to set in a send-receive round trip.
> > 
> > 
> > Well, no. If you're streaming data, you don't have to wait for the prev notification but can push more data using another buffer. And if you're concerned about memory consumption, in a copy mode the kernel will allocate that memory internally and keep it until it gets an ACK, which is less transparent.
> 
> How to understand “you don't have to wait for the prev notification”? If I receive IORING_CQE_F_MORE from cqe.flag, can I proceed with the next send? Will this ensure the order of send operation?

Yes. You can also read it here.

https://github.com/axboe/liburing/blob/master/man/io_uring_enter.2#L1327C1-L1332C33
