### ISSUE TITLE
submit socket+connect+send+recv+close job in one go

### ISSUE THREAD

**Issue by illiliti** [axboe/liburing#803]
IOSQE_IO_LINK linked chain where first syscall creates file descriptor and subsequent syscalls operate on it. Is it possible?

**Comment by axboe** [comment]
You can do this with direct descriptors, as you can pick what fixed file index you use for the socket operation and then use that for the remainder of the chain.

**Comment by illiliti** [comment]
Could you please show an example of code how to achieve that? I don't fully understand how you can get file index without submitting job and then getting its result.

**Comment by axboe** [comment]
You don't get the file index, you set it. You open a socket asking for a specific index, and then you know you can use that index for the recv/send/etc. Here's a basic example for doing an open/read/close of a regular file as one sequence. It's using '0' as the direct index and registers a sparse table of that size, but it could be any value really.

```
	io_uring_queue_init(8, &ring, 0);
	io_uring_register_files_sparse(&ring, 1);

	sqe = io_uring_get_sqe(&ring);
	io_uring_prep_openat_direct(sqe, AT_FDCWD, FNAME, 0, 0, 0);
	sqe->flags |= IOSQE_IO_LINK;
	sqe->user_data = 1;

	sqe = io_uring_get_sqe(&ring);
	io_uring_prep_read(sqe, 0, buf, BUF_SIZE, 0);
	sqe->flags |= IOSQE_FIXED_FILE | IOSQE_IO_LINK;
	sqe->user_data = 2;

	sqe = io_uring_get_sqe(&ring);
	io_uring_prep_close_direct(sqe, 0);
	sqe->user_data = 3;

	io_uring_submit(&ring);
```

**Comment by illiliti** [comment]
OK, I set it. But do I'm thinking right that file index can't be reused when there is already sqe that uses it? If so, how to be certain that it won't happen and does io uring provide some aid in this regard?(imagine I'm submitting multiple async socket+connect+send+recv+close jobs in loop)

**Comment by axboe** [comment]
If you pick a slot that's already in use, the existing file in that slot will get closed and replaced by the new one. If you use direct descriptors and the app is picking which slots to use, the app is responsible for managing them.

**Comment by illiliti** [comment]
Thank you very much for your help. I think I know everything I need

**Comment by illiliti** [comment]
No, turns out [IOSQE_IO_DRAIN](https://github.com/axboe/liburing/issues/804#issuecomment-1445226654) was a bad idea. It basically made all my jobs synchronous. To at least preserve some portion of async part intact, I switched to normal socket() syscall to then do prep_connect, prep_send, ... on it. It's sad that I have to make syscalls; only one but still. I hope this will get fixed.
