### ISSUE TITLE
implications of prep_close on submissions that are being processed

### ISSUE THREAD

**Issue by illiliti** [axboe/liburing#804]
Imagine you have submission that already being in the work and you just submitted close_direct operation to close direct descriptor that submission uses to actually do the work(e.g read/write from/to it). What will happen to submission in this case? It will die or return error or io uring will let it finish the work and shutdown/complete gracefully as if nothing happened? Does io uring have any flags to control this behavior?

**Comment by axboe** [comment]
If the operation using that direct descriptor has already been started, then closing it won't impact it. So that should be fine to do.

**Comment by illiliti** [comment]
Good. If I understand correctly, same thing can be said for IOSQE_IO_LINK chains, right? For example you have read and write operations chained into one. You submitted it and then immediately closed(or replaced using well-known mechanism) direct descriptor that they operate on. Will something break or such operation is entirely atomic once submitted, i.e it will proceed normally?

**Comment by axboe** [comment]
No, when links are setup, the request is only prepared, not fully setup. The fd will be resolved when that part of the link is started. So if you do:

<open direct fd 0><read direct fd 0><...>
<close direct fd 0>

then the read direct fd 0 part and later parts of that chain may not see the current fd 0. It's safe to do in a chain itself as each part is serialized with the sqe before it, but once you're outside of a chain, that is no longer the case. It _may_ work depending on timing, but it's not guaranteed.

**Comment by axboe** [comment]
Should clarify that this is a prerequisite for links working with direct descriptors to begin with. If the fd was fully resolved as the link were prepared, then it would fail the example sequence of:

<open direct fd X><read direct fd X><close direct fd X>

as direct fd X would not be valid yet before the open has successfully completed.

**Comment by illiliti** [comment]
Dammit, that ruined my entire plan

**Comment by axboe** [comment]
You could use IOSQE_IO_DRAIN for this, but it's generally not recommended as it isn't very efficient.

**Comment by illiliti** [comment]
Thank you very much again. IOSQE_IO_DRAIN looks exactly what I need, so I'll stick with it for now. Having atomic chained operations would be much better though...

**Comment by axboe** [comment]
I have been toying with a concept I termed "bundles". Basically a way to submit things like the dependent chain, except there are no dependencies. For your example, you could put everything you wanted into a bundle, and then link the bundle with the close and know that the close wouldn't run before the bundle was done. Inside the bundle you can do ordering with links as per usual, or not have any dependencies at all. Anyway, not even posted yet, just something I played with.

**Comment by illiliti** [comment]
Sounds cool! Looking forward to see it.
