### ISSUE TITLE
prep_write content could be modified after successfully submit

### ISSUE THREAD

**Issue by SHTUSIST** [axboe/liburing#808]
Thanks for your reading!

Linux kernel: v5.19 with **IORING_FEAT_SUBMIT_STABLE** feature  enabled. And flag IOSQE_IO_LINK enabled. 

I found that after io_uring_submit  the written buffer by io_uring_prep_write could still be modified even if  no overlapped offset.

An example code like below: 
```c++
	//.... some init code
    while(count < num)
    {
      char temp_buf[9];
      sprintf(temp_buf, "%08d", count);
      for(int j = 0; j < BUFFER_SIZE / 8; j++)
      {
          memcpy(write_buf + 8 * j, temp_buf, 8);
      }

        sqe = io_uring_get_sqe(&ring);
        io_uring_sqe_set_flags(sqe, IOSQE_IO_LINK); 
        // (count * BUFFER_SIZE) to calculate the correct file offset of async write. No overlapped written offset
        io_uring_prep_write(sqe, fd_, write_buf, BUFFER_SIZE, count * BUFFER_SIZE);
        io_uring_submit(&ring);

       //Result is that the file size and offset are correct but all written content is the final temp_buf's content. 
       //Expect result is like write(fd_,write_buf, BUFFER_SIZE);
       // Unless we use wait function after every write
    
        count += 1;     
    }
```

**Is this behaviour normal? Must I use wait function under this scenario?**

**Comment by isilence** [comment]
1) IOSQE_IO_LINK does not persist across `io_uring_submit()`. Your loop will send a bunch of __not__ linked requests.
2) The kernel can read data in any moment between submitting a request and getting a completion. You either need to use a new buffer for each write or wait for the cqe before sending the next request.

**Comment by SHTUSIST** [comment]
> 1. IOSQE_IO_LINK does not persist across `io_uring_submit()`. Your loop will send a bunch of **not** linked requests.
> 2. The kernel can read data in any moment between submitting a request and getting a completion. You either need to use a new buffer for each write or wait for the cqe before sending the next request.

Thanks for your patient reply! I will close this issue
