### ISSUE TITLE
examples/io_uring-udp.c: IORING_SETUP_COOP_TASKRUN is incompatible with （IORING_SETUP_SQPOLL | IORING_SETUP_SQ_AFF）?

### ISSUE THREAD

**Issue by glenn-wang** [axboe/liburing#811]
https://github.com/axboe/liburing/blob/liburing-2.3/examples/io_uring-udp.c#L98

After replace the following code chunk
```
params.flags = IORING_SETUP_SUBMIT_ALL | IORING_SETUP_COOP_TASKRUN |
		       IORING_SETUP_CQSIZE;
```
with
```
params.flags = IORING_SETUP_SUBMIT_ALL | IORING_SETUP_COOP_TASKRUN |
		       IORING_SETUP_CQSIZE | IORING_SETUP_SQPOLL | IORING_SETUP_SQ_AFF;

params.sq_thread_idle = 10;
params.sq_thread_cpu = 1;
```

I get the error code：-22; and error info is Invalid argument.

My test environment is as the following:
```
Operating System: Ubuntu 22.04.1 LTS              
          Kernel: Linux 6.2.2-060202-generic
    Architecture: x86-64
```

Is my usage correct?

**Comment by isilence** [comment]
Right, `IORING_SETUP_COOP_TASKRUN` is not compatible with `IORING_SETUP_SQPOLL`, and it wouldn't make sense to set them together. Not sure if it's obvious from manuals.

**Comment by AomaYple** [comment]
> Right, `IORING_SETUP_COOP_TASKRUN` is not compatible with `IORING_SETUP_SQPOLL`, and it wouldn't make sense to set them together. Not sure if it's obvious from manuals.

So which is more recommended to use (based on performance)

**Comment by axboe** [comment]
SQPOLL is a pretty specialized mode, not a default kind of thing. COOP_TASKRUN is fine. DEFER_TASKRUN is usually preferred if it works with the model, requiring single task/thread per ring. See the wiki page on networking for details.

**Comment by AomaYple** [comment]
> COOP_TASKRUN

So is COOP_TASKRUN better if the model is per thread per ring (these rings are independent and don't affect each other)

**Comment by axboe** [comment]
As mentioned, usually defer TASKRUN would be preferable.

**Comment by AomaYple** [comment]
> As mentioned, usually defer TASKRUN would be preferable.

Thank you!
