### ISSUE TITLE
multishot io_uring_prep_timeout

### ISSUE THREAD

**Issue by illiliti** [axboe/liburing#813]
I propose to add multishot version of io_uring_prep_timeout. Useful when you need to trigger timeout periodically.

**Comment by axboe** [comment]
That's a good suggestion, should be trivial too. I'll take a look.

**Comment by DylanZA** [comment]
was added back in https://github.com/axboe/liburing/commit/d57fa5b86d21e77ddba248c3801b0d329b72e045

**Comment by illiliti** [comment]
Nice! I was thinking about io_uring_prep_timeout_multishot, but looks like flag already does the job. Closing then
