### ISSUE TITLE
Support for DRM_IOCTL_SYNCOBJ_TIMELINE_WAIT

### ISSUE THREAD

**Issue by mahkoh** [axboe/liburing#818]
The [DRM_IOCTL_SYNCOBJ_TIMELINE_WAIT](https://github.com/torvalds/linux/blob/44889ba56cbb3d51154660ccd15818bc77276696/drivers/gpu/drm/drm_syncobj.c#L1274) ioctl allows userspace to wait for work on a GPU to be completed.

There is currently no non-blocking API to accomplish this. One suggestion for how to solve this has been to attach an eventfd to the underlying syncobj that would be signaled once the work has been completed: https://lore.kernel.org/dri-devel/20221009144001.161124-1-contact@emersion.fr/

Personally I believe that the better solution would be to support this ioctl via io_uring. Some general new OP (e.g. `IORING_OP_IOCTL`) that supports a subset of all ioctls (for now only DRM_IOCTL_SYNCOBJ_TIMELINE_WAIT) could be used for this. In the future this could also be expanded to other ioctls if the need arises.

Would such a thing be appropriate for io_uring?

**Comment by isilence** [comment]
I was telling a couple of years ago that io_uring with ioctls sounds like a very nice base for drm. We already have an alternative to ioctls, see `IORING_OP_URING_CMD`

**Comment by axboe** [comment]
```IORING_OP_URING_CMD``` should be perfect for wiring up a communication channel with drm, as it can be added per file type. Not much is needed to support that on the drm side, and then you get an async channel for request/responses.

**Comment by mahkoh** [comment]
That should probably work but I'm a bit worried about the `IORING_OP_URING_CMD` concept in general. Aside from it being blocking, the only problem with ioctl is that the ioctl numbers are not unique. This means that you cannot use ioctl easily on untrusted file descriptors: An ioctl that works fine with one file type might corrupt your memory if used with a different file type. The kernel has tried to mitigate this by only assigning unique ioctl numbers for new ioctls but now it seem that `IORING_OP_URING_CMD` has committed to the same design mistake. ublk just uses the following cmd_op IDs:

```
#define	UBLK_CMD_GET_QUEUE_AFFINITY	0x01
#define	UBLK_CMD_GET_DEV_INFO	0x02
#define	UBLK_CMD_ADD_DEV		0x04
#define	UBLK_CMD_DEL_DEV		0x05
#define	UBLK_CMD_START_DEV	0x06
```

In my usecase I receive file descriptors via unix domain sockets, so I have to trust that `IORING_OP_URING_CMD` cannot have unintended side effects.

**Comment by mahkoh** [comment]
Maybe what we could do is reserve IDs below 0x10 and tell everyone else to to use the usual ioctl numbering scheme for new cmd_ops. Unfortunately we cannot invent a new scheme because nvme has already committed to using ioctl numbers for their cmd_op IDs.

**Comment by isilence** [comment]
> That should probably work but I'm a bit worried about the `IORING_OP_URING_CMD` concept in general. Aside from it being blocking,

Can you elaborate what you mean? It's not blocking, the enter syscall should never block submitting IO. Some operation may block in a worker thread, but that depends on how the handler is implemented. E.g. nvme pass through is fully asynchronous. 

> the only problem with ioctl is that the ioctl numbers are not unique. This means that you cannot use ioctl easily on untrusted file descriptors: An ioctl that works fine with one file type might corrupt your memory if used with a different file type. The kernel has tried to mitigate this by only assigning unique ioctl numbers for new ioctls but now it seem that 
> [...]
`IORING_OP_URING_CMD` has committed to the same design mistake. ublk just uses the following cmd_op IDs:
> In my usecase I receive file descriptors via unix domain sockets, so I have to trust that `IORING_OP_URING_CMD` cannot have unintended side effects.

I don't think it's a mistake but rather the ioctl numbering is not seems like a mess (just like ioctl is). The user should know what file it operates on, it doesn't make much sense otherwise. What to do when you get a random file? It would be nice to have a way to discover the file type dynamically. Does `statx` return anything useful for that?

**Comment by mahkoh** [comment]
>Can you elaborate what you mean?

I meant that the ioctl syscall is blocking.

>The user should know what file it operates on, it doesn't make much sense otherwise.

With the unique-ioctl-system, the worst that can happen is that the user gets ENOTTY back.

>It would be nice to have a way to discover the file type dynamically.

That would be the proper solution.

>Does statx return anything useful for that?

I don't believe this is possible in general. If the kernel calls `anon_inode_getfile` then there is no way to identify the underlying fops.

**Comment by mahkoh** [comment]
I've implemented this here: https://github.com/mahkoh/linux/pull/1

I had to add the ability to cancel uring_cmds because syncobj waits are not guaranteed to ever complete. See the first commit. There is still at least one open issue with the current implementation. I've described this in a comment in the MR.

**Comment by axboe** [comment]
Looks like a good start, I added some comments to the first patch. I would suggest we move this to the mailing list though for review, if you're fine with that?

**Comment by mahkoh** [comment]
Let's complete the current round of questions in the linked MR and move to the ML for the next round.

**Comment by axboe** [comment]
> Let's complete the current round of questions in the linked MR and move to the ML for the next round.

Yep, that sounds like a good plan.

**Comment by axboe** [comment]
Did you make any progress on this?

**Comment by mahkoh** [comment]
I can only work on this over the weekend. If you believe that the ability to cancel uring cmds is independently useful, the I would be more than happy for you to take this over.

**Comment by mahkoh** [comment]
Sorry, I dropped this after a bad interaction with someone involved in DRM.

For this particular usecase, Simon Ser has submitted a less powerful mechanism which has been merged: https://lore.kernel.org/dri-devel/20230711142803.4054-1-contact@emersion.fr/T/#u

Feel free to pick up the linked MR under any license you want. It's unlikely that I'll pursue this.
