### ISSUE TITLE
Feature request: mkdirat, unlinkat support

### ISSUE THREAD

**Issue by dkadashev** [axboe/liburing#82]
With the recent addition of openat, statx and close almost every file operation can be performed using io_uring. But while `openat` allows to create new files, it's impossible to create a new dir or remove a dir entry.

**Comment by YoSTEALTH** [comment]
`scandirat()`, seems like everything with `*at()` would be needed?

**Comment by dkadashev** [comment]
`scandirat` is a libc function, not a syscall. Probably `getdents64` makes sense, but lumping everything into one big ticket isn't too useful I suppose.

**Comment by openalmeida** [comment]
+1

**Comment by openalmeida** [comment]
Directory operations is needed.

**Comment by dkadashev** [comment]
@axboe I've added a test case for `mkdirat` support, available here: https://gist.github.com/dkadashev/c949cacc85dfc2e3b8e507baab9b8da1. All comments from https://github.com/axboe/liburing/issues/111#issuecomment-712852571 apply (the liburing part is under `#if 0`, not a pull request because I guess we need all of the parts working before it can be included, etc.)

I've seen the message in the mailing list saying you've already done `unlinkat`, including the test, so I'll skip that.

I'll look if I can add `mkdirat` support myself, but it will take some time.

**Comment by dkadashev** [comment]
https://lore.kernel.org/io-uring/20201111132551.3536296-1-dkadashev@gmail.com/T/#t

Will send the liburing part tomorrow assuming the kernel patch does not get rejected

**Comment by dkadashev** [comment]
Kernel patch series: https://lore.kernel.org/io-uring/20201116044529.1028783-1-dkadashev@gmail.com/T/
Liburing series: https://lore.kernel.org/io-uring/20201116051005.1100302-1-dkadashev@gmail.com/T/

**Comment by YoSTEALTH** [comment]
Could this `io_uring_prep_mkdirat` patch be merged? There is already support to `IORING_OP_MKDIRAT` in `io_uring.h` right.

Thank you

**Comment by dkadashev** [comment]
This is work in progress, the latest version of the patch is here: https://lore.kernel.org/io-uring/20210513110612.688851-1-dkadashev@gmail.com/T/

And I'm working on the next version at the moment

**Comment by YoSTEALTH** [comment]
Thanks @dkadashev, its hard to tell what is being implemented vs whats already been implemented.

So for `io_uring_prep_unlinkat` if I wanted to recursively unlink non-empty directory, I would have to wait for `io_uring_prep_getdents` to be implemented right?

**Comment by openalmeida** [comment]
> > So for `io_uring_prep_unlinkat` if I wanted to recursively unlink non-empty directory, I would have to wait for `io_uring_prep_getdents` to be implemented right?
> 
> Yes, you'd have to walk the directory and remove stuff, and if you want to walk the directory without blocking you need `getdents` support in io_uring

Sometimes, directory read/write locking as atomic operation is required for "remove stuff", or application may confused about io logic itself. I mean no disrespect, and I know its not anyone's duty to implement locking/unlocking of io_uring/liburing, but would you please have a look about it ? This is why my application is not a totally io_uring based IO model which I prefer to:

Locking/unlocking and directory contents listing (getdents64 https://github.com/axboe/liburing/issues/111) is the first wave an totally uring drived io app will meet.

_Originally posted by @openalmeida in https://github.com/axboe/liburing/issues/85#issuecomment-752888776_

Sorry about I am not able to coding at kernel/OS level or I should submit a PR myself.

**Comment by dkadashev** [comment]
> Sometimes, directory read/write locking as atomic operation is required

I'm not sure what you mean. `flock` / POSIX style locking? You do know that they are (by default) advisory and won't prevent external apps from writing to the dir, right?

Anyway, I *might* be interested in implementing `flock`, but given my lack of experience I'll need quite a lot of help and I might be not the best person for the job. I won't give any promises at this point, sorry

**Comment by dkadashev** [comment]
FWIW `mkdirat` support was merged into 5.15 :tada:

**Comment by axboe** [comment]
Indeed, let's close this one up.
