### ISSUE TITLE
Whether the flame graphs of udp echo server using io_uring are as they should be ? And are there other features to improve the performance ?

### ISSUE THREAD

**Issue by glenn-wang** [axboe/liburing#823]
As the title.
And my server is basied on [tokio-rs/io-uring](https://github.com/tokio-rs/io-uring), it has the same effect as liburing.

used features: multishot, register_buf_ring, register socket file fd, IORING_SETUP_SUBMIT_ALL, **IORING_SETUP_SQPOLL,  IORING_SETUP_SQ_AFF**
![sqpoll - echo](https://user-images.githubusercontent.com/7918942/224540685-994b9e96-0ec7-482f-a653-710d68190371.svg)

---

used features: multishot, register_buf_ring, register socket file fd, IORING_SETUP_SUBMIT_ALL, **IORING_SETUP_DEFER_TASKRUN, IORING_SETUP_SINGLE_ISSUER**
![taskrun - echo](https://user-images.githubusercontent.com/7918942/224540715-89065518-5618-41bb-b19b-96d586055b8b.svg)

**Comment by isilence** [comment]
Looks good, most of overhead is in the network stack as expected. There is zc send, but it's feasibility depends on the packet size. I don't see what % memcpy takes here, should be sth like `.*copy_from_iter.*`. There are some network stack improvements that can be done and tentatively planned, but nothing you can turn on at the io_uring side.
