### ISSUE TITLE
provided buffer's typical usage, API, and the questions for send/write

### ISSUE THREAD

**Issue by beef9999** [axboe/liburing#825]
> Using provided buffers, an application can submit a receive operation without providing a buffer upfront.
https://github.com/axboe/liburing/wiki/io_uring-and-networking-in-2023#provided-buffers

But zerocopy send also has the need to use buf_ring. We need a way to retrieve the registered buffers before sending.

**Comment by beef9999** [comment]
The current buf_ring seems to be specially designed for the async-callback event engine. (Or the completion based model as this wiki refers to).

So the recommended code looks like this:

```
io_uring_wait_cqe(ring, &cqe);
/* IORING_CQE_F_BUFFER is set in cqe->flags, get buffer ID */
buffer_id = cqe->flags >> IORING_CQE_BUFFER_SHIFT;
/* find the buffer from our buffer pool */
buf = bufs[buffer_id];
[... app work happens here ...]
/* we’re done with the buffer, add it back */
io_uring_buf_ring_add(br, bufs[buffer_id], BUF_SIZE, buffer_id,
				    io_uring_buf_ring_mask(BUFS_IN_GROUP), 0);
/* make it visible */
io_uring_buf_ring_advance(br, 1);
/* CQE has been seen */
io_uring_cqe_seen(ring, cqe);
```

But for other sync-style engines(for example, coroutine/fiber), there is no way for users to put app code right here. The sync-style recv looks exactly like the libc version, and the function must accept a user specified address.

However, for the async-callback model, it's natural that you put your app code after the engine has received data for you. No need to specify buf pointer. And that's the difference.

I'm wondering if liburing could do something to solve this problem. The ideal usage would be:
1. Register a large space of buffers and buf_ring
2. Call a Get method from the buf_ring's tail, and got an available buffer
3. After send or recv (cqe arrived), add back to the ring's front.

**Comment by isilence** [comment]
> The current buf_ring seems to be specially designed for the async-callback event engine. (Or the completion based model as this wiki refers to).

Not really, it solves another problem, which comes from the async nature of io_uring but will be there regardless whatever user API / model you provide. Namely, there are lots of slow connections, you want to submit a recv request for each of them but don't want to waste memory by backing each request by its own buffer. E.g. 1000 sockets once per minute sending you 1MB would need 1000MB of buffers. That problem is not relevant with poll (epoll, io_uring poll requests, etc.).
   
> But for other sync-style engines(for example, coroutine/fiber), there is no way for users to put app code right here. The sync-style recv looks exactly like the libc version, and the function must accept a user specified address.
> However, for the async-callback model, it's natural that you put your app code after the engine has received data for you. No need to specify buf pointer. And that's the difference.

So, it's useful for recv/read even for coroutines and if you want to employ it, you'd need to change the userspace API. e.g. `recv(len, ..., **out_buffer)`, which return a buffer back.

For sends/writes it's not much useful considering that user have to fill in memory first and the user can implement its own buffer pool if needed, which will even be faster than doing syscalls.

**Comment by beef9999** [comment]
It suddenly sounds less interesting... Looks like I don't need to integrate provided buffers then. I used to think it's performance critical...

**Comment by axboe** [comment]
> It suddenly sounds less interesting... Looks like I don't need to integrate provided buffers then. I used to think it's performance critical...

That's a misunderstanding! They only exist to provide a way to have a ton of pending receives without also having a ton of pending buffers allocated upfront. It's just an efficient way to do that. But if you can stomach just having the memory allocated, that is going to be more efficient than even ring mapped provided buffers, as you'd be doing less work in the kernel (eg no buffer picking, etc).

**Comment by beef9999** [comment]
@axboe I think the reason I got misled is partially because I had read some words from the `io_uring_register` documents...

> Registering files or user buffers allows the kernel to take long term references to internal data structures or create long term mappings of application memory, greatly reducing per-I/O overhead.
https://man.archlinux.org/man/extra/liburing/io_uring_register.2.en

The part of register_files is true, indeed. I‘ve seen the performance increase. So this can't help but reminds me that register_buffers also has the same effect on performance...

**Comment by beef9999** [comment]
And as per the memory usage you mentioned, personally I don't think that's a big problem. Because most network protocols have headers, for example, HTTP and RPC. So server only needs to prep_recv with a small size of bytes. 

I believe we only limit the topic in the scope of `polling` connections. Because as to the process of large data receiving, libc is the same to io_uring.

**Comment by FrankReh** [comment]
> They only exist to provide a way to have a ton of pending receives without also having a ton of pending buffers allocated upfront.

I think they also provide a way to receive data without any system calls. The io_uring can be used free of system calls (when the system is busy), and feeding the buffers back to the pool can be free of system calls.

**Comment by isilence** [comment]
> > They only exist to provide a way to have a ton of pending receives without also having a ton of pending buffers allocated upfront.
> 
> I think they also provide a way to receive data without any system calls. The io_uring can be used free of system calls (when the system is busy), and feeding the buffers back to the pool can be free of system calls.

Provided buffers are also a requirement for multishot recv, if that's what you mean. In other cases (let's say paired with  SQPOLL), the user have to issue requests anyway and so can specify buffers directly, it doesn't really change what you get in terms context switches.

**Comment by axboe** [comment]
As Pavel said, they are indeed required for multishot, there's no other way to make that work.

For SQPOLL, which is what @FrankReh seems to be referring to, they are not a requirement. SQPOLL really works independently of that, no difference in terms of buffers for SQPOLL or !SQPOLL in how they can be provided.
