### ISSUE TITLE
Question: will io_uring "block" current thread when reading regular file? 

### ISSUE THREAD

**Issue by YjyJeff** [axboe/liburing#826]
I try to create a database based on io_uring, therefore, I need to perform a lot of IO operations on regular files.  After a lot of searching, I am confused about how io_uring works on the regular file.  

According to [lord of io_uring](https://unixism.net/loti/async_intro.html#does-this-problem-exist-in-io-uring), io_uring works fine for regular files. However, after reading [worker pool in io_uring](https://blog.cloudflare.com/missing-manuals-io_uring-worker-pool/),  I think reading regular files will "block" the current thread(I am a kernel newbie, so correct me if am wrong 0.0) :

1. After submission, io_uring will try to call a non-blocking read on the regular file.
2. Because it is a regular file, non-blocking read always returns `Ready`.   // [Non blocking IO with regular file](https://www.remlab.net/op/nonblock.shtml)
3. Read operation will execute in `complete inline` mode to read from the file system on the thread that calls `io_uring_enter`. "Blocking" happens here. 

According to the above assumption, I write a simple program: submit multiple read operations in batch to io_uring and wait for completion in the end. With perf command:
```
sudo perf stat -a -e 'io_uring:io_uring_*' -- ./demo
```
I do not observe the hit on  `io_uring:io_uring_poll_arm` and `io_uring:io_uring_queue_async_work`. Then I profile the program with flame graph, the flame graphs tell me that all of the cpus are used on reading from file system, which is inside the `io_uring_enter` syscall. All two profiles prove my thought. 

So, reading from the file system is pretty expensive, will it block the thread?(Can not handle the task that is waked up by socket, etc.) Shall we be encouraged to submit the read operation on a regular file with `async` to put it   on the worker pool? 

Thanks!

**Comment by axboe** [comment]
Your analysis is wrong, io_uring does not rely on poll for regular files, as that obviously doesn't work since they are always reading for reading/writing. Instead it does non-blocking issues of IO, and will retry them from io-wq if that fails. This is true for O_DIRECT for any kernel, buffered reads for quite a while, and buffered writes since a few releases ago. What is true for all kernels is that you don't need to mark them async to offload them, io_uring is aware of its limitations in those kernels and will offload them upfront as need be.

Please remember to include a kernel version and storage stack setup in your description, since things change for the better over time, it's hard to advise generically in case you are running an ancient kernel.

**Comment by YjyJeff** [comment]
> Your analysis is wrong, io_uring does not rely on poll for regular files, as that obviously doesn't work since they are always reading for reading/writing. Instead it does non-blocking issues of IO, and will retry them from io-wq if that fails. This is true for O_DIRECT for any kernel, buffered reads for quite a while, and buffered writes since a few releases ago. What is true for all kernels is that you don't need to mark them async to offload them, io_uring is aware of its limitations in those kernels and will offload them upfront as need be.
> 
> Please remember to include a kernel version and storage stack setup in your description, since things change for the better over time, it's hard to advise generically in case you are running an ancient kernel.

@axboe I am using the `Ubuntu 20.04` wither kernel version `5.15.0-67-generic`. 5 NVMe SSDs consist RAID0 and btrfs is used as the file system. Files are opened **without** O_DIRECT, buffered reads are used here.  I will try it in a new kernel

**Comment by axboe** [comment]
raid0 got nowait support fairly recently - definitely after 5.15, but not long after... I don't fully recall, will have to check the git logs for that. I think it was 6.0.

**Comment by beef9999** [comment]
@YjyJeff Try coroutine based on io_uring, you will feel like you are writing traditional libc programs. Don't need to care about the underneath details. This is one of our [experience](https://github.com/facebook/rocksdb/issues/11017) on database.

**Comment by YjyJeff** [comment]
> raid0 got nowait support fairly recently - definitely after 5.15, but not long after... I don't fully recall, will have to check the git logs for that. I think it was 6.0.

@axboe What can I observe in the perf output, if the io_uring works well? Can I observe the `io_uring:io_uring_queue_async_work`? 

> Instead it does non-blocking issues of IO, and will retry them from io-wq if that fails

BTW: What does the non-blocking issues of IO mean, when it fails? I searched a lot and does not find an answer :sob:  Could you describe it briefly? Sorry for the dumb.....

**Comment by GalaxySnail** [comment]
> > Instead it does non-blocking issues of IO, and will retry them from io-wq if that fails
> 
> BTW: What does the `it does non-blocking issues of IO` mean, when it fails? I searched a lot and does not find an answer 😭 Could you describe it briefly? Sorry for the dumb question.....

I assume that it's doing something like:

``` c
struct iovec iov = {.iov_base = buf, .iov_len = buflen};
ssize_t ret = preadv2(fd, &iov, 1, offset, flags | RWF_NOWAIT);
if (ret < 0) {
    if (errno == EAGAIN) {
        run_in_io_wq_thread_pool(...);
    } else {
        return -1;
    }
}
```

**Comment by axboe** [comment]
Yep, what @GalaxySnail said, just on the kernel side. Some exceptions on cases where we know it doesn't work (eg we can check upfront), for those it goes straight to io-wq as a nonblocking attempt isn't possible.

In general, any io-wq activity is not ideal. Seeing some on storage workloads isn't a major source for concern however, that can happen even on cases that do fully support nonblocking issue. Examples of that include queue being quisced for whatever reason, or running out of resources.

**Comment by uwydoc** [comment]
hello, i think i met the same issue, `io_uring_submit` would occasionally block for a while for read requests on regular file, whether or not the file is opened with o_direct. on kernel 5.6+, set `IOSQE_ASYNC` flag on sqe is a working solution, however, on older kernels, `IOSQE_ASYNC` is not available, and i cannot find any workaround (SQPOLL would not help).

i spent some time dig into the implementation of io_uring_enter in the kernel side, and do trace (strace and ftrace) on it, and find that ocassionally the internal io_read call (with NOWAIT flag i believe) would result in actual read, instead of EAGAIN, this is observed on all three kernel versions (5.4, 5.15, 6.8) that i test on. i am not a kernel guy, so can not provide more details.

@YjyJeff i see you mark this issue as closed, would you share your final solution? thx

**Comment by isilence** [comment]
Which filesystem is that? Something might be ignoring the nowait flag, we can (bpf)trace who is sleeping.

**Comment by uwydoc** [comment]
> Which filesystem is that? Something might be ignoring the nowait flag, we can (bpf)trace who is sleeping.

verified on xfs (host) and ext4 (vm)

**Comment by isilence** [comment]
@axboe, IIRC there was some debacle with xfs about not honouring NOWAIT. Do you know if it's solved?

**Comment by isilence** [comment]
> Try this bpftrace script:
> 
> https://gist.github.com/isilence/822a3a1116a126040928171352171ec1
> 
> You need to start it first like `bpftrace script.bt`, and while it's running execute your test. Once you got the lag, just terminate bpftrace. Would be great if you try it with the latest kernel and 6.8

Separately for xfs and ext4 please.

**Comment by uwydoc** [comment]
@isilence here the output on kernel 6.8 (ubuntu 24.04 vm)

on ext4
```
@[
    __schedule+812
    __schedule+812
    schedule+51
    io_schedule+70
    blk_mq_get_tag+341
    __blk_mq_alloc_requests+196
    blk_mq_submit_bio+400
    __submit_bio+179
    submit_bio_noacct_nocheck+316
    submit_bio_noacct+354
    submit_bio+178
    iomap_dio_submit_bio+132
    iomap_dio_bio_iter+899
    __iomap_dio_rw+987
    iomap_dio_rw+17
    ext4_file_read_iter+354
    __io_read+246
    io_read+23
    io_issue_sqe+97
    io_submit_sqes+296
    __do_sys_io_uring_enter+754
    __x64_sys_io_uring_enter+34
    x64_sys_call+3802
    do_syscall_64+127
    entry_SYSCALL_64_after_hwframe+120
]: 89
@submit[2216]: 1
```

on xfs
```
@[
    __schedule+812
    __schedule+812
    schedule+51
    io_schedule+70
    blk_mq_get_tag+341
    __blk_mq_alloc_requests+196
    blk_mq_submit_bio+400
    __submit_bio+179
    submit_bio_noacct_nocheck+316
    submit_bio_noacct+354
    submit_bio+178
    iomap_dio_submit_bio+132
    iomap_dio_bio_iter+899
    __iomap_dio_rw+987
    iomap_dio_rw+17
    xfs_file_dio_read+215
    xfs_file_read_iter+309
    __io_read+246
    io_read+23
    io_issue_sqe+97
    io_submit_sqes+296
    __do_sys_io_uring_enter+754
    __x64_sys_io_uring_enter+34
    x64_sys_call+3802
    do_syscall_64+127
    entry_SYSCALL_64_after_hwframe+120
]: 80
@submit[2230]: 1
```

**Comment by isilence** [comment]
So it's iomap. The (kernel) patch below should help, can you try it?

```diff
diff --git a/fs/iomap/direct-io.c b/fs/iomap/direct-io.c
index b521eb15759e..f24bbc3a93e0 100644
--- a/fs/iomap/direct-io.c
+++ b/fs/iomap/direct-io.c
@@ -385,6 +385,9 @@ static loff_t iomap_dio_bio_iter(const struct iomap_iter *iter,
 
 	bio_opf = iomap_dio_bio_opflags(dio, iomap, use_fua, atomic);
 
+	if (iter->flags & IOMAP_NOWAIT)
+		bio_opf |= REQ_NOWAIT;
+
 	nr_pages = bio_iov_vecs_to_alloc(dio->submit.iter, BIO_MAX_VECS);
 	do {
 		size_t n;
```

**Comment by uwydoc** [comment]
> So it's iomap. The (kernel) patch below should help, can you try it?
> 
> diff --git a/fs/iomap/direct-io.c b/fs/iomap/direct-io.c
> index b521eb15759e..f24bbc3a93e0 100644
> --- a/fs/iomap/direct-io.c
> +++ b/fs/iomap/direct-io.c
> @@ -385,6 +385,9 @@ static loff_t iomap_dio_bio_iter(const struct iomap_iter *iter,
>  
>  	bio_opf = iomap_dio_bio_opflags(dio, iomap, use_fua, atomic);
>  
> +	if (iter->flags & IOMAP_NOWAIT)
> +		bio_opf |= REQ_NOWAIT;
> +
>  	nr_pages = bio_iov_vecs_to_alloc(dio->submit.iter, BIO_MAX_VECS);
>  	do {
>  		size_t n;

@isilence at last, i managed to apply the patch, compile the kernel and bring the system up with the new kernel. the patch works as expected, `iomap_dio_rw` returns `EAGAIN` immediately now, and `io_uring_submit` would not block.

i use strace and bpftrace to verify the time and function return code:
```
sudo bpftrace -e 'kprobe:__x64_sys_io_uring_enter { @submit[tid] = 1; } kretprobe:iomap_dio_rw /@submit[tid]/ { printf("[%s] retval=%d\n", probe, retval); }'

strace -t -T io_uring_enter <command>
```

before apply the patch, `iomap_dio_rw` returns -529 (`EIOCBQUEUED`), and the first io_uring_enter (triggered by io_uring_submit) would block for a while (hundreds of milliseconds)
```
[kretprobe:iomap_dio_rw] retval=-529
```

after, `iomap_dio_rw` returns -11 (`EAGAIN`), and the first io_uring_enter takes less than a millisecond, and later io_uring_enter calls blocks on `create_io_worker` and `schedule`
```
[kretprobe:iomap_dio_rw] retval=-11
```
result from perf-record also indicate the above behaviour transition.

ps.  i spent quite some time to find a way to do incremental build on the ubuntu kernel source tree with debian/rules scripts, and i just give up. also, compile the kernel in a vm is also quite resource-intensive and slooooow, and finally decide to launch a cloud instance and do the compile there, and i really hope i made the decision earlier.

**Comment by uwydoc** [comment]
btw, on kernel 5.4 of the ubuntu kernel (NOT the upstream linux kernel), driver codes for ext4 and xfs actually check for `IOCB_NOWAIT` flag explicitly: https://git.launchpad.net/~ubuntu-kernel/ubuntu/+source/linux/+git/focal/tree/fs/xfs/xfs_file.c#n180
```
	if (iocb->ki_flags & IOCB_NOWAIT) {
		if (!xfs_ilock_nowait(ip, XFS_IOLOCK_SHARED))
			return -EAGAIN;
	} else {
		xfs_ilock(ip, XFS_IOLOCK_SHARED);
	}
	ret = iomap_dio_rw(iocb, to, &xfs_iomap_ops, NULL);
	xfs_iunlock(ip, XFS_IOLOCK_SHARED);
```
however, it do a shared lock check on the inode first, and would return `EAGAIN` only when the shared lock fails. this is the same for ext4: https://git.launchpad.net/~ubuntu-kernel/ubuntu/+source/linux/+git/focal/tree/fs/ext4/inode.c#n3902

on the upstream linux kernel, for direct io, it would NOT check for `IOCB_NOWAIT` flag: https://github.com/torvalds/linux/blob/v5.4/fs/xfs/xfs_file.c#L190
```
	xfs_ilock(ip, XFS_IOLOCK_SHARED);
	ret = iomap_dio_rw(iocb, to, &xfs_iomap_ops, NULL);
	xfs_iunlock(ip, XFS_IOLOCK_SHARED);
```

i am not a kernel guy, and i do not why.

**Comment by isilence** [comment]
> on the upstream linux kernel, for direct io, it would NOT check for `IOCB_NOWAIT` flag: https://github.com/torvalds/linux/blob/v5.4/fs/xfs/xfs_file.c#L190

You're rather interested in the stable branch, 5.4 does have the change.

**Comment by isilence** [comment]
> [@isilence](https://github.com/isilence) at last, i managed to apply the patch, compile the kernel and bring the system up with the new kernel. the patch works as expected, `iomap_dio_rw` returns `EAGAIN` immediately now, and `io_uring_submit` would not block.

@uwydoc, thanks for testing!

**Comment by uwydoc** [comment]
> You're rather interested in the stable branch, 5.4 does have the change.

ok, i just got aware that there are two repos in git.kernel.org, mainline and stable, and torvalds/linux on github is the mainline repo. thx

**Comment by uwydoc** [comment]
@isilence i see the patch you are proposing, maybe `__blockdev_direct_IO` in `fs/direct-io.c` needs patch as well, because on 5.4, `ext4_direct_IO` eventually calls `__blockdev_direct_IO` (whereas `xfs_direct_IO` calls `iomap_dio_rw`), maybe there are other fstype calls it. a quick grep shows that, even on 6.8, ocfs2 calls it.

**Comment by isilence** [comment]
Let's address iomap first and then we can return to this one.
FWIW, it's a pretty old kernel, why not upgrade it? It misses a lot on the io_uring side as well.

**Comment by uwydoc** [comment]
> Let's address iomap first and then we can return to this one.
ok

>FWIW, it's a pretty old kernel, why not upgrade it? It misses a lot on the io_uring side as well.
you are right. upgrade is way better than patch, actually on ubuntu-2004 (the main dev and prod env i am working on) the kernel can be upgraded to 5.15 with apt upgrade, which is awesome because `IOSQE_ASYNC` is available now, and the patch is not a necessity.
