### ISSUE TITLE
Kernel 6.1 does not accept IORING_POLL_ADD_LEVEL

### ISSUE THREAD

**Issue by cyanide-burnout** [axboe/liburing#829]
Getting -EINVAL in response to IORING_OP_POLL_ADD / IORING_OP_POLL_REMOVE when use IORING_POLL_ADD_LEVEL to disable edge-triggering

There few hints where that happens:
https://github.com/torvalds/linux/blob/a1effab7a3a35a837dd9d2b974a1bc4939df1ad5/io_uring/poll.c#L909
https://github.com/torvalds/linux/blob/a1effab7a3a35a837dd9d2b974a1bc4939df1ad5/io_uring/poll.c#L939

**Comment by axboe** [comment]
Level triggered poll isn't supported yet, that's why it returns -EINVAL.
