### ISSUE TITLE
hope IORING_SETUP_SQPOLL don't depend on IORING_REGISTER_FILES

### ISSUE THREAD

**Issue by ChinaXing** [axboe/liburing#83]
```
  To  successfully  use  this feature, the application must register a set of files to be
  used for IO through io_uring_register(2) using the IORING_REGISTER_FILES opcode.  Fail-
  ure to do so will result in submitted IO being errored with EBADF.

```

sometimes register files not handy, because one io_uring instance may used to serve many files,
and these file randomly accessed as needed, register them will need to keep them all open, and dynamic update registered files by update can mitigate it, but also need to manage the array's state of free slots in order to reuse them.

so, it will be nice to make IORING_SETUP_SQPOLL orthogonal with IORING_REGISTER_FILES
:)

**Comment by isilence** [comment]
Not the case anymore, see `IORING_FEAT_SQPOLL_NONFIXED`
https://github.com/axboe/liburing/blob/master/man/io_uring_setup.2

we should close the issue
