### ISSUE TITLE
flags parameter in io_uring_prep_timeout_remove

### ISSUE THREAD

**Issue by FrankReh** [axboe/liburing#834]
Why is there a `flags` parameter to `io_uring_prep_timeout_remove`?

The manual makes no reference to the meaning of flags for that command. Is it there to future proof the command in case a flag is defined later that would be relevant to removing a timeout?

**Comment by axboe** [comment]
I generally add flags to all of them, as basically all commands do take flags in an attempt to be backwards compatible when flags are added. I added a small note on the remove part not taking any flags currently, where the update flags are explained.

**Comment by FrankReh** [comment]
Thanks for the update and the explanation. Makes sense.
