### ISSUE TITLE
Direct fd produced by IORING_FILE_INDEX_ALLOC can not be used as fixed file

### ISSUE THREAD

**Issue by chimaoshu** [axboe/liburing#840]
I used `io_uring_register_files_sparse` to register an empty file table first, then use `io_uring_prep_openat_direct` with `IORING_FILE_INDEX_ALLOC` to produce a direct fd.

It seems that direct fd produced by `IORING_FILE_INDEX_ALLOC` is not in the range of file table registered by `io_uring_register_files_sparse`, and that direct fd can only be used as a regular file, but not a fixed file.

Using the direct fd produced by `IORING_FILE_INDEX_ALLOC`, a `-EBADF` will be returned when using the direct fd with `IOSQE_FIXED_FILE`, while a success will be returned without `IOSQE_FIXED_FILE` set.

If file_index is specified, not using `IORING_FILE_INDEX_ALLOC`, then the direct fd can correctly be used as a fixed file.

Here's an example:
```c
#include <unistd.h>
#include <fcntl.h>
#include <string.h>
#include <stdio.h>
#include <sys/socket.h>
#include <liburing.h>
#include <errno.h>
#include <netinet/in.h>

const char *file_path = "/var/www/html/404.html";

int get_fixed_file_by_open_direct(struct io_uring *ring)
{
    // openat direct
    struct io_uring_sqe *sqe = io_uring_get_sqe(ring);
    // io_uring_prep_openat_direct(sqe, -1, file_path, 0, O_RDONLY, 0);
    io_uring_prep_openat_direct(sqe, -1, file_path, 0, O_RDONLY, IORING_FILE_INDEX_ALLOC);
    int ret = io_uring_submit(ring);
    if (ret == -1)
    {
        printf("error");
        return 0;
    }

    // wait cqe
    struct io_uring_cqe *cqe;
    io_uring_wait_cqe(ring, &cqe);

    printf("openat_direct fixed file is %d\n", cqe->res);
    int fixed_file_idx = cqe->res;

    io_uring_cq_advance(ring, 1);
    return fixed_file_idx;
}

void read_file(struct io_uring *ring, int fixed_file_idx, __u8 flags)
{
    // submit with IOSQE_FIXED_FILE
    struct io_uring_sqe *sqe = io_uring_get_sqe(ring);
    char buf[100];
    io_uring_prep_read(sqe, fixed_file_idx, buf, 100, 0);
    sqe->flags = flags;

    int ret = io_uring_submit(ring);
    if (ret == -1)
    {
        printf("error");
        return;
    }

    // wait cqe
    struct io_uring_cqe *cqe;
    ret = io_uring_wait_cqe(ring, &cqe);
    if (ret == -1)
    {
        printf("error");
        return;
    }
    printf("output: %d\n", cqe->res);
    io_uring_cq_advance(ring, 1);
}

int main()
{

    // setup pipe
    int pipefd[2];
    int ret = pipe(pipefd);
    if (ret == -1)
    {
        printf("error");
        return 0;
    }

    // setup io_uring
    struct io_uring ring;
    struct io_uring_params params;
    memset(&params, 0, sizeof(params));
    params.flags = IORING_SETUP_SQPOLL;
    if (io_uring_queue_init_params(128, &ring, &params) < 0)
    {
        printf("error");
        return 0;
    }

    // register file sparse
    ret = io_uring_register_files_sparse(&ring, 1);
    if (ret == -1)
    {
        printf("error");
        return 0;
    }

    int fixed_file_idx = get_fixed_file_by_open_direct(&ring);

    // cqe->res=-EBADF
    read_file(&ring, fixed_file_idx, IOSQE_FIXED_FILE);

    // cqe->res>=0
    read_file(&ring, fixed_file_idx, 0);

    return 0;
}
```

**Comment by axboe** [comment]
You forgot some rather interesting details, like the kernel version being used?

**Comment by chimaoshu** [comment]
I am using kernel version 6.2.9-060209-generic, and liburing version 9134244a4e16e68cb514ea5192fcd7e9beca96f5

**Comment by axboe** [comment]
Great thanks, I'll take a look. Thanks for the reproducer!

**Comment by axboe** [comment]
>     io_uring_prep_openat_direct(sqe, -1, file_path, 0, O_RDONLY, IORING_FILE_INDEX_ALLOC);

I think you want that as:

```
io_uring_prep_openat_direct(sqe, -1, file_path, 0, O_RDONLY, IORING_FILE_INDEX_ALLOC - 1);
```

and we should have an _alloc() helper for that.

**Comment by axboe** [comment]
This is really a bug in liburing, it should factor in if ```IORING_FILE_INDEX_ALLOC``` is being used or not and do the right thing.

**Comment by chimaoshu** [comment]
> > ```
> > io_uring_prep_openat_direct(sqe, -1, file_path, 0, O_RDONLY, IORING_FILE_INDEX_ALLOC);
> > ```
> 
> I think you want that as:
> 
> ```
> io_uring_prep_openat_direct(sqe, -1, file_path, 0, O_RDONLY, IORING_FILE_INDEX_ALLOC - 1);
> ```
> 
> and we should have an _alloc() helper for that.


Oh, I see. So the correct usage is `IORING_FILE_INDEX_ALLOC - 1`. The docs may be misleading, I used `IORING_FILE_INDEX_ALLOC` directly as file_index because the man page of `io_uring_prep_openat_direct` said:
> If IORING_FILE_INDEX_ALLOC is used as the file_index for a direct  open,  then  io_uring
       will  allocate  a free direct descriptor in the existing table. The allocated descriptor
       is returned in the CQE res field just like it would be for a non-direct open request. If
       no  more  entries  are available in the direct descriptor table, -ENFILE is returned in‐
       stead.

**Comment by axboe** [comment]
The docs should be correct, it's the helpers that are bad. See the commit I pushed. I don't think it makes a lot of sense to have applications be aware of this +/- 1 detail of how it needs to be passed to the kernel.

**Comment by chimaoshu** [comment]
exactly
