### ISSUE TITLE
Increasing the performance of `io_uring-udp.c`

### ISSUE THREAD

**Issue by vorbrodt** [axboe/liburing#844]
I'm doing some benchmarking between a UDP socket I created, that uses the standard Linux network stack without any kind of modifications, and the example file called `io_uring-udp.c` in liburing. The problem I'm running into is that  `io_uring-udp.c` is underperforming compared to a regular UDP socket, which is not what I would expect.

### Setup
Here I will shortly summarize how the setup for the benchmarking looks. I'm doing the testing locally on my machine that is running Ubuntu with kernel version 6.1.9.  The NC is Ethernet Controller XL710 with Ethernet speed 40GbE (Gigabit Ethernet). The flow starts with a traffic generator, Pktgen, that transmits datagrams via the NIC to the application (UDP socket or  `io_uring-udp.c`) which then forwards the datagram back via the NIC to Pktgen where some networking metrics are read and calculated. 

With the UDP socket I'm able to get back around `475 000` packets per second to Pktgen and with  `io_uring-udp.c` I'm able to get back `430 000` packets per second. It feels as if  io_uring should be outperforming the standard Linux network stack, but it doesn't seem to be true in this case.

### Ideas I have had
I have tried to play around with some parameters to see if they could yield some better results for io_uring, but so far without any luck. 

First thing I'm interested in trying out is `IORING_SETUP_SQPOLL`.  It seems as it should be simple to add to `io_uring-udp.c` but when I try to add it using the following code I'm not able to run the program. It seems there might be some compatibility issue between them:

    params.flags =  IORING_SETUP_SUBMIT_ALL | IORING_SETUP_COOP_TASKRUN | IORING_SETUP_CQSIZE | IORING_SETUP_SQPOLL ;
    params.sq_thread_idle = 2000;	

The second thing I have seen that could potentially help to increase the packet processing performance is `IORING_SETUP_IOPOLL` but I'm not sure how it should be added.

### Questions

* Is there some obvious reason why io_uring is underperforming compared to a regular UDP socket for packet forwarding in this case? 
* Could using `IORING_SETUP_SQPOLL` or `IORING_SETUP_IOPOLL`  help increase the performance? If so, how could it be implemented in `io_uring-udp.c`
* Is there something else I can look into and add to `io_uring-udp.c` to increase the performance?

**Comment by DylanZA** [comment]
a few notes:
* ` io_uring-udp.c` was by no means designed with high performance instead. 
* IOPOLL isn't yet a thing for network sockets
* SQPOLL probably won't help you here, the context switching is likely to be a problem. I suspect it doesn't work because of IORING_SETUP_COOP_TASKRUN, which is incompatible. but again it's not likely to be useful

As to where the performance problems lie, I would start with a profile using something like `perf` to see where the cycles are currently spent.

* I would also try enable DEFER_TASKRUN, that should immediately give you a boost.
* io_uring-udp also does a lot of parsing of the recvmsg header, it might not be so useful (or it might be possible to speed it up).
* have you checked to see if any udp packets are being dropped? I cannot recall the exact way to do that, but it could be that the burst pattern ends up with packets being dropped on the tx side.

**Comment by vorbrodt** [comment]
I tried to add `IORING_SETUP_DEFER_TASKRUN` but not sure were it is suppose to go. I could not find any good examples of using it.  

What I tried doing was: `params.flags =  IORING_SETUP_SUBMIT_ALL | IORING_SETUP_COOP_TASKRUN |IORING_SETUP_CQSIZE | IORING_SETUP_DEFER_TASKRUN;` but it gives me this an error when I run the program (my kernel version is `6.1.9-060109-generic`): 

```
buf_ring init failed: Operation not supported
NB This requires a kernel version >= 6.0
Segmentation fault (core dumped)
```


Running flame graph:

![image](https://user-images.githubusercontent.com/64839037/233119700-3a1c89a1-4acd-421f-a2e5-1953fe0f5164.png)

So it looks like `sendmsg` might be a bottlneck. What do you think? And do you have any suggestion on how to add `IORING_SETUP_DEFER_TASKRUN`?

**Comment by isilence** [comment]
There are many examples in tests/ and examples/ if you're interested, but in short it also requires `IORING_SETUP_SINGLE_ISSUER` to be set.

```C
params.flags |= IORING_SETUP_SINGLE_ISSUER | IORING_SETUP_DEFER_TASKRUN;
```

**Comment by isilence** [comment]
It's a bit weird that it fails in `setup_buffer_pool()`, and apparently works well without `DEFER_TASKRUN`
