### ISSUE TITLE
io_uring_get_sqe() doesn't clear sqe->user_data all the time

### ISSUE THREAD

**Issue by bgemmill** [axboe/liburing#848]
I've been looking at switching my application from epoll to io_uring within boost::asio, and noticed ASAN failures when doing so.

So I went ahead and made my own io_uring executor to see if this was boost issue or not, and my code failed in exactly the same way. It looks like somewhere along the way the behavior around timeout preparation changed a little.

The problem seems to be if the submitter follows a pattern like this:
```
auto* sqe = io_uring_get_sqe(&_ring);
if (!sqe) { return 0; }
io_uring_prep_timeout(sqe, &ts, 1, 0);
// io_uring_sqe_set_data(sqe, nullptr); // uncomment and everything is fine
io_uring_submit(&ring);
```

And the consumer follows a pattern like this:
```
... get cqe ...
auto* ptr = (io_uring_op*) io_uring_cqe_get_data(cqe);
auto res = cqe->res;

if (!ptr) { return; } // old values pass right through here
(*ptr)(res); // invoke the handler and segfault!
```

Old user_data values from prior operations remain in place, are not cleared by the time the timeout operation is prepared, and cause segfaults on completion.

This only happens sometimes; I can get a good 100 or so operations through before seeing it. Manually clearing user data after prepping timeouts solves the problem, but seems really non-obvious.

I'd assume that io_uring_get_sqe would clear user_data with the expectation that the user would set it again with a fresh value, but there may be a use case I'm missing.

Is this expected behavior?

**Comment by axboe** [comment]
liburing never sets it, so if you don't always do so, then you're bound to run into old values once the cq ring wraps around. If you _always_ look at user_data on the completion side, you must also always set it on the submission side. There's no implied clearing being done for you, and given that these are rings, you will essentially keep seeing the same CQEs (in terms of memory) as completions are logged and reaped.

**Comment by bgemmill** [comment]
Thanks, that makes sense.
