### ISSUE TITLE
License Question about liburing

### ISSUE THREAD

**Issue by JayLiangs** [axboe/liburing#853]
Hi, @axboe  or other contributors,

My question is, can I combine my own library with "liburing" and then **redistribute the combination under MIT**?

Since I'm little confused about your license policy，readme said “_All software contained within this repo is dual licensed LGPL and MIT, see COPYING and LICENSE, except for a header coming from the kernel which is dual licensed GPL with a Linux-syscall-note exception and MIT, see COPYING.GPL_”, while the .spec claim that license is "_(GPLv2 with exceptions and LGPLv2+) or **MIT**_".

I understand that you allow receiver to free choose MIT or LGPL as "liburing"‘s license, but since the kernel part is licensed under GPL (there is only some individual files of kernel is has a dual license of MIT and GPL), how can you relicense the "liburing" - the deprive work of GPL kernel. Do you hold a relicense permission from kernel's   copyright holder？

Looking forward your friendly reply！

**Comment by axboe** [comment]
The only shared bit between the kernel and liburing is the io_uring.h uapi header, which is dual licensed MIT/GPL.

**Comment by JayLiangs** [comment]
Very helpful, thanks a lot!!
