### ISSUE TITLE
Linux 6.0+ is very fast

### ISSUE THREAD

**Issue by uNetworkingAB** [axboe/liburing#854]
Not an issue, just wanted to leave my feedback.

Some years ago I wrote that epoll beat io_uring on all my computers and that I couldn't get it to perform any good, I think this was back with Linux 5.4. As of Linux 6.0 and the multishot feature, I can now reliably beat epoll for real networked apps, significantly. This is great. Also, I love the provide-buffers feature so that you don't need to lock up receive buffers 1-to-1.

Alright, just wanted to leave this feedback.

**Comment by ammarfaizi2** [comment]
> Not an issue, just wanted to leave my feedback.

Heh, you should have posted this in the "discussion" section. Not "issues".

https://github.com/axboe/liburing/discussions/categories/show-and-tell
