### ISSUE TITLE
locking in test/recv-msgall

### ISSUE THREAD

**Issue by pobrn** [axboe/liburing#855]
`test/recv-msgall.c` has the following code:

```c
	pthread_mutexattr_init(&attr);
	pthread_mutexattr_setpshared(&attr, 1);
	pthread_mutex_init(&rd.mutex, &attr);
	pthread_mutex_lock(&rd.mutex);
	rd.use_recvmsg = use_recvmsg;

	ret = pthread_create(&recv_thread, NULL, recv_fn, &rd);
	if (ret) {
		fprintf(stderr, "Thread create failed: %d\n", ret);
		pthread_mutex_unlock(&rd.mutex);
		return 1;
	}

	pthread_mutex_lock(&rd.mutex);
```

I don't see how this can be correct since `rd.mutex` is not recursive, so the last `pthread_mutex_lock()` will try to lock it a second time. And the other thread that runs `recv_fn()` might even try to unlock the mutex without acquiring it, which is again invalid. In fact, with in build configurations (`-O0`), the program does crash.

**Comment by axboe** [comment]
It should not be recursive, it's just synchronizing startup. It's meant to block on the second lock, when the thread has unlocked it. But obviously it should just use pthread barriers, that's much simpler and easier to reason about. Feel free to send a patch.

**Comment by ammarfaizi2** [comment]
I will send two patches.
