### ISSUE TITLE
`io_uring_unregister_eventfd`

### ISSUE THREAD

**Issue by YoSTEALTH** [axboe/liburing#86]
has `io_uring_unregister_eventfd` function been removed from `register.c` ? its still referenced in https://github.com/axboe/liburing/blob/d0e4cfa2c666b0bb4c959ef77e4d2f62ba7f1e1f/src/liburing.map#L20 and https://github.com/axboe/liburing/blob/4f4eff4ca75f7ef843834ab8e66655438b1cf82f/src/include/liburing.h#L105

**Comment by axboe** [comment]
Well that's annoying... It's the classic chicken and egg problem - knowing if a release is good to go, when nobody tests anything before a release. This isn't directed at you, just a general observation. I've put it back.
