### ISSUE TITLE
Strange behaviour when batching multiple `sendmsg` sqes to scatter a UDP message 

### ISSUE THREAD

**Issue by thealexcons** [axboe/liburing#860]
Hi,

I am writing some code to scatter a message to multiple local UDP servers with the code shown below. It simply batches multiple `sendmsg` operations in a loop, only differing in the port in each iteration. 

The behaviour I am seeing is that all UDP messages are being sent to the final port in the specified range, ie: 10 messages are sent to port 5564 in this case, when I would expect to see one message being sent to each port in the range. I have attached an eBPF program at the TC layer to print the destination ports of these egress packets and it shows how all 10 packets have the same remote port specified. You can also recreate this with `netcat -ul 5564` , which will receive all 10 "scatter" messages, whereas opening netcat with any of the other 9 ports does not receive a message.

**However**, if I have an `io_uring_submit` call at the end of each iteration (rather than after the entire loop), it does correctly send the message to each port in the range.

Does anyone know why this is happening?  

Kernel version (as per `uname -r`): 5.15.0
libbpf version: latest master branch (commit e3c52b2c751b3e33e3bb0d486d1384efc186de90)

```c
// gcc scatter.c -o scatter -luring
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <net/if.h>
#include <arpa/inet.h>
#include <liburing.h>

int main(int argc, char** argv) {
    struct io_uring ring;
    struct io_uring_params params;
    memset(&params, 0, sizeof(params));

    if (io_uring_queue_init_params(1024, &ring, &params) < 0) {
        perror("Failed to initialise io_uring queue");
        exit(1);
    }

    int sock = socket(AF_INET, SOCK_DGRAM, 0);
    if (sock < 0) {
        perror("Opening datagram socket");
        exit(1);
    }
    
    /* Bind our local address so that the client can send to us */
    struct sockaddr_in name;
    memset(&name, 0, sizeof(name));
    name.sin_family = AF_INET;
    name.sin_addr.s_addr = htonl(0);
    name.sin_port = htons(0);
    if (bind(sock, (struct sockaddr *) &name, sizeof(name))) {
        perror("binding datagram socket");
        exit(1);
    }

    // Scatter the msg to UDP servers with ports [5555, 5564] on localhost
    uint16_t first_port = 5555;
    for (int i = 0; i < 10; i++) {
        char msg[8] = {0};
        strncpy(msg, "scatter", 8);

        struct iovec iov = {
            .iov_base = &msg,
            .iov_len = 8,
        };

        // destination
        struct sockaddr_in destAddr;
        memset(&destAddr, 0, sizeof(struct sockaddr_in));
        destAddr.sin_family = AF_INET;
        destAddr.sin_port = htons(first_port + i);
        destAddr.sin_addr.s_addr = 0; // localhost

        struct msghdr msgh;
        memset(&msgh, 0, sizeof(msgh));
        msgh.msg_name = &destAddr;
        msgh.msg_namelen = sizeof(struct sockaddr_in);
        msgh.msg_iov = &iov;
        msgh.msg_iovlen = 1;

        struct io_uring_sqe *sqe = io_uring_get_sqe(&ring);
        io_uring_prep_sendmsg(sqe, sock, &msgh, 0);
        io_uring_sqe_set_flags(sqe, 0);
        // io_uring_submit(&ring); // if i have this here, it works as expected
    }
    printf("events added to queue: %d\n", io_uring_sq_ready(&ring));
    io_uring_submit(&ring);
}
```

**Comment by axboe** [comment]
Your ```struct sockaddr_in destAddr``` is on the stack, and you keep overwriting the values in it. SQE entries are not consumed until you do io_uring_submit(), so you're effectively submitting 10 identical requests with the above code. It also technically goes out of scope before you use it, so it could be garbage by the time you submit. It obviously won't be because you don't put anything else on the stack or return, but that's not kosher C.

If you put that ```destAddr``` outside the loop and make it ```destAddr[10]``` and use the right index for it, then I bet it'd work.

**Comment by thealexcons** [comment]
You're absolutely correct :) rookie mistake!
Thanks

**Comment by axboe** [comment]
> You're absolutely correct :) rookie mistake!

We've all been there, staring at the code blindly ;-)
