### ISSUE TITLE
no way to enable high-level io_uring object

### ISSUE THREAD

**Issue by dankamongmen** [axboe/liburing#863]
Unless I'm missing something (very possible), there's no way to enable the high-level `io_uring` object after using `IOURING_SETUP_R_DISABLED`. I'd like to implement `io_uring_enable(3)` unless this capability does already exist. Please let me know if you'd like a different name or anything.

Thanks for the great work on iouring!

**Comment by axboe** [comment]
```io_uring_enable_rings()``` exists for this, but looks like it hasn't been documented yet.

**Comment by dankamongmen** [comment]
i'll throw you a man page for it this evening unless you'd prefer to write it!

**Comment by axboe** [comment]
Please do!

**Comment by dankamongmen** [comment]
btw, since this function hasn't been a release yet AFAIK, maybe `s/rings/ring`? unless there's something i'm missing.

**Comment by axboe** [comment]
I think you could argue both ways on ring vs rings - there are two rings there, SQ and CQ. Both are effectively disabled, even though just having the SQ ring disabled obviously means that the CQ ring is too.

**Comment by DylanZA** [comment]
> btw, since this function hasn't been in a release yet AFAIK, maybe s/rings/ring? unless there's something i'm missing.

just fyi it's been there a long time - so can't update it now. since at least 2.0: https://github.com/axboe/liburing/blob/liburing-2.0/src/include/liburing.h#L144
