### ISSUE TITLE
[noob] How do I run examples on kernels < 6.0

### ISSUE THREAD

**Issue by zhuker** [axboe/liburing#873]
Noob question here

I am on Ubuntu 22.04 on 5.19 kernel
When I run udp example I get
```
recv cqe bad res -22
NB: This requires a kernel version >= 6.0
```

Is there a way to run it on my kernel?
What README did I miss?

**Comment by DylanZA** [comment]
basically the UDP example uses features that are unavailable on your kernel

It should be possible to run Ubuntu with a newer mainline kernel, but I don't know the exact steps

**Comment by axboe** [comment]
Some features will be new opcodes, others will be something else entirely. Generally the man pages, in particular io_uring_enter(2), will have info on what was added when.

You can also use io_uring_get_probe(3) to get a list of supported opcodes on the running kernel, and on ring setup, you can check io_uring_params->features to check for IORING_FEAT_* flags.
