### ISSUE TITLE
io_uring_register_buf_ring() now returns (95) Operation not supported after 2.4 upgrade

### ISSUE THREAD

**Issue by lano1106** [axboe/liburing#877]
I have not upgraded to 6.3 yet...

The error is occurring with 6.2.10...

I will provide more info as I look into the issue...

**Comment by lano1106** [comment]
ok, I think that I have found what is happening...

prior to call io_uring_register_buf_ring(), io_uring_register_ring_fd() is called. Because I am still on 6.2, IORING_FEAT_REG_REG_RING is false, INT_FLAG_REG_REG_RING is not added to int_flags when ring->enter_ring_fd is changed to an offset from the io_uring fd value, do_register will pass an invalid fd value to __sys_io_uring_register()

**Comment by lano1106** [comment]
```
static inline int do_register(struct io_uring *ring, unsigned int opcode,
			      const void *arg, unsigned int nr_args)
{
	int fd;

	if (ring->int_flags & INT_FLAG_REG_REG_RING) {
		opcode |= IORING_REGISTER_USE_REGISTERED_RING;
		fd = ring->enter_ring_fd;
	} else
		fd = ring->ring_fd;

	return __sys_io_uring_register(fd, opcode, arg, nr_args);
}
```

appears to fix my issue

**Comment by cmazakas** [comment]
Just ran into this issue too

**Comment by axboe** [comment]
Sorry, missed this one. @lano1106 would you mind sending in a patch?

**Comment by axboe** [comment]
I'll apply it as-is with attribution instead!
