### ISSUE TITLE
`IORING_SETUP_SQPOLL` causes `io_uring_get_sqe` to be NULL

### ISSUE THREAD

**Issue by rvineet02** [axboe/liburing#895]
Hi, I am writing an application using sockets. When I attempt to use the `IORING_SETUP_SQPOLL` flag when initializing the ring, I get an immediate null for the `io_uring_get_sqe` call causing an immediate exit of my program. 

I am running on Ubuntu, kernel version: 5.15.0-60-generic

I had a similar issue earlier (#890) but ensured that there is no mismatch. Additionally, the code works with no issues when I initialize the ring with the default: `ret = io_uring_queue_init(threads->qe_val, &ring, 0);`. 

I have also tried to run the program as `sudo` with no luck. 

For reference, here is the code snippet:

```c++
static void *doTest(void *arg)
{
	// ... socket connection

	struct io_uring ring;
	struct io_uring_params params;

	struct thread_info_t *ti;

	struct iovec iov = {
			.iov_base = buffer,
			.iov_len = sizeof(buffer)};
	struct io_uring_cqe *cqe;
	struct io_uring_sqe *sqe;

	int ret;

	ti = (struct thread_info_t *)arg;



	memset(&params, 0, sizeof(params));
	params.flags |= IORING_SETUP_SQPOLL;
	params.sq_thread_idle = 100;

	ret = io_uring_queue_init_params(threads->qe_val, &ring, &params);
	
	// ret = io_uring_queue_init(threads->qe_val, &ring, 0); -> this works with no issue

	if (ret)
	{
		printf("%d: ring setup failed: %d\n", ti->num, ret);
		return arg;
	}

	size_t total_bytes_sent = 0;

	auto start = std::chrono::high_resolution_clock::now();
	auto end = start + std::chrono::seconds(15);
	while (std::chrono::high_resolution_clock::now() < end)
	{
		sqe = io_uring_get_sqe(&ring);
		if (!sqe)
		{
			printf("%d: sqe failed\n", ti->num);
			return arg;
		}

		io_uring_prep_writev(sqe, sock, &iov, 1, 0);
		ret = io_uring_submit(&ring);
		if (ret <= 0)
		{
			printf("%d: sqe submit failed: %s\n", 2, strerror(-ret));
			return arg;
		}
		
		while (1)
		{
			ret = io_uring_peek_cqe(&ring, &cqe);
			if (ret == 0)
			{
				int bytes_sent = cqe->res;
				io_uring_cqe_seen(&ring, cqe);
				if (bytes_sent < 0)
				{
					printf("%d: send failed: %d\n", ti->num, bytes_sent);
					return arg;
				}
				total_bytes_sent += bytes_sent;
				break; // Break the inner loop when completion is processed.
			}
			else if (ret == -EAGAIN || ret == -EWOULDBLOCK)
			{
				break;
			}
			else
			{
				// Handle error.
				printf("%d: peek cqe failed: %d\n", ti->num, ret);
				return arg;
			}
		}
	}

	close(connection_result);
	io_uring_queue_exit(&ring);
	return arg;
}
``` 

Sample output when I run the program:
```
./src/clientPoll -t 8 --qe 64
5: sqe failed
4: sqe failed
1: sqe failed
3: sqe failed
6: sqe failed
0: sqe failed
2: sqe failed
7: sqe failed
```

Please let me know if you would like the entire program if that would make debugging easier.

**Comment by axboe** [comment]
I suspect you just need to read the man page for io_uring_sqring_wait(). When you use SQPOLL, you don't know when entries are consumed by the other end.

**Comment by rvineet02** [comment]
ah okay, seems to be working with `io_uring_sqring_wait()`. 

Typically, is there a noticeable performance improvement when using `SQPOLL`, still doing very early testing and it seems to have similar performance to using the base setup. This is in the context of networking i/o.

**Comment by axboe** [comment]
SQPOLL being a win or not very much depends on both the type of requests being done, and how the workload behaves. Hard to be a lot more specific than that, I'm afraid.
