### ISSUE TITLE
[Feature request] waitpid(2) or waitid(2) support for io-uring with timeout support

### ISSUE THREAD

**Issue by CarterLi** [axboe/liburing#896]
`waitpid` or `waitid` *waits*, which fits io-uring model perfectly. In addition, wait* lacks timeout support, users either use busy wait with `WNOHANG`, hack it with signals or use threads. While io-uring supports IORING_OP_LINK_TIMEOUT, which can simplify user code greatly.

**Comment by axboe** [comment]
Yep that'd be pretty easy to wire up indeed. Let me take a look at it tomorrow.

**Comment by CarterLi** [comment]
It will be rather better if we don't need to touch io-wq :)

**Comment by CarterLi** [comment]
Note if the wait timeouts, users should be able to cancel the wait operation.

**Comment by axboe** [comment]
It won't add anything new that relies on io-wq, and this one is easy to wire up without blocking.

**Comment by axboe** [comment]
This is how timeouts work, it'd always cancel.

**Comment by CarterLi** [comment]
Oh yes. I confused OP_LINK_TIMEOUT with OP_TIMEOUT

**Comment by CarterLi** [comment]
Oh yes. I confused OP_LINK_TIMEOUT with OP_TIMEOUT

**Comment by axboe** [comment]
https://git.kernel.dk/cgit/linux/log/?h=io_uring-waitid

Totally untested... But it's a start. Fully async, no io-wq business.

**Comment by axboe** [comment]
Same branch name as before, but should be more complete now. It sits on top of the futex support branch, as both are adding opcodes.

For liburing, check the 'waitid' branch:

https://git.kernel.dk/cgit/liburing/log/?h=waitid

which has a basic test case as well that does some basic functionality checks, including using it with a linked timeout.

**Comment by CarterLi** [comment]
Thank you very much!

**Comment by axboe** [comment]
Did you do any testing with it? Would love to hear about it! I just posted it for review earlier today:

https://lore.kernel.org/io-uring/20230711204352.214086-1-axboe@kernel.dk/

and I'm sure we'll do a few revisions, but hopefully it can go in for the next kernel release.

**Comment by CarterLi** [comment]
I'm sorry, but I can only test it when it's merged into mainline

**Comment by axboe** [comment]
Curious, why is that? The best time to test is obviously before it hits mainline, in case you run into any bugs or behavioral issues. Once it hits mainline it's too late.

**Comment by CarterLi** [comment]
I have no skill to build the kernel image. I have to wait https://kernel.ubuntu.com/~kernel-ppa/mainline/daily/current/ to build it.

**Comment by axboe** [comment]
Gotcha, that makes sense. I'll see if I can spin you a kernel package. Would be nice in general for other cases too.

**Comment by axboe** [comment]
Assuming you're on x86-64, I built a mainline deb for you:

https://brick.kernel.dk/snaps/kernel/

which is based on current -git and with the io_uring changes on top. I hope this works... It's using the .config from the ppa you referenced above, and then I just clone my repo and build the current branch with:

```
$ make -j32 -s bindeb-pkg
```

to generate the packages.

**Comment by CarterLi** [comment]
Thank you. I will try it when I get home.

**Comment by axboe** [comment]
@CarterLi any updates??

**Comment by CarterLi** [comment]
I had a simple use case. Wait for a process for some time. If it exits in time, grab its exit code. If not, kill it.

IORING_OP_WAITID did work for me in this case without problems.

**Comment by TheClonerx** [comment]
How does this interact with `SIGCHLD`?

**Comment by axboe** [comment]
> How does this interact with SIGCHLD?

It doesn't change SIGCHLD.

**Comment by TheClonerx** [comment]
So then if I had to guess, the behavior is as if one thread wants to wait for a children while another is changing the signal disposition?

**Comment by axboe** [comment]
I don't follow that question. It'll work like waitid(2) does in this regard, if that answers your question. By default SIGCHLD is masked, and I would not expect any io_uring waitid users to define a handler for that.
