### ISSUE TITLE
io_uring_submit return negatif submit

### ISSUE THREAD

**Issue by katanatr** [axboe/liburing#913]
.

**Comment by ammarfaizi2** [comment]
Please send a full working bug reproducer. Ideally, this should be a
small, self-contained program that the maintainers can easily compile
and run. It will help them to fix the issue quickly.

Don't forget to proofread before posting. Pretend you're seeing it for
the first time: does it make sense? Try reproducing the problem
yourself, and make sure you can do so using only the information
included in your report.

**Comment by axboe** [comment]
@katanatr Can you expand please? Was this a local issue? Always nice to put some details in when closing an issue, in case others run into the same thing.
