### ISSUE TITLE
io_uring_submit undersubmits on some kernels

### ISSUE THREAD

**Issue by dkadashev** [axboe/liburing#92]
`io_uring_submit` seems to be submitting just one SQE (regardless of number of items in SQ) on kernels 5.5.4 and 5.6.0-rc2, but submits all of the items in SQ on 5.4.19.

Test program:

```c
#include <assert.h>
#include <liburing.h>
#include <signal.h>
#include <stdio.h>
#include <string.h>

int main()
{
    struct io_uring ring;
    int res = io_uring_queue_init(32, &ring, 0);
    if (res < 0) {
        printf("init: %s\n", strerror(-res));
        return 1;
    }
    int i = 0;
    for (i = 0; i < 10; ++i) {
        struct io_uring_sqe* sqe = io_uring_get_sqe(&ring);
        assert(sqe);
        io_uring_prep_close(sqe, -1);
    }
    int submitted = 0;
    while (submitted < i) {
        printf("going to submit, sq_ready=%d\n", io_uring_sq_ready(&ring));
        res = io_uring_submit(&ring);
        if (res < 0) {
            printf("submit: %s\n", strerror(-res));
            return 2;
        }
        printf("submitted %d items\n", res);
        submitted += res;
    }
    for (i = 0; i < submitted; ++i) {
        struct io_uring_cqe* cqe;
        res = io_uring_wait_cqe(&ring, &cqe);
        if (res < 0) {
            printf("wait_cqe: %s\n", strerror(-res));
            return 2;
        }
        io_uring_cqe_seen(&ring, cqe);
    }
    io_uring_queue_exit(&ring);

    return 0;
}
```

I'm using liburing-0.5, statically linked into the app.

On one box I get the expected output:

```
% uname -vr
5.4.0-4-amd64 #1 SMP Debian 5.4.19-1 (2020-02-13)
% ./a.out 
going to submit, sq_ready=10
submitted 10 items
```

On two others I get this:
```
% ./a.out 
going to submit, sq_ready=10
submitted 1 items
going to submit, sq_ready=0
submitted 1 items
going to submit, sq_ready=0
submitted 1 items
going to submit, sq_ready=0
submitted 1 items
going to submit, sq_ready=0
submitted 1 items
going to submit, sq_ready=0
submitted 1 items
going to submit, sq_ready=0
submitted 1 items
going to submit, sq_ready=0
submitted 1 items
going to submit, sq_ready=0
submitted 1 items
going to submit, sq_ready=0
submitted 1 items
```

Kernels: `5.6.0-rc2 #1 SMP Tue Feb 18 11:23:51 UTC 2020`, `5.5.4-1.el7.elrepo.x86_64 #1 SMP Thu Feb 13 18:09:18 EST 2020`

Am I doing something wrong, or is it some kind of regression?

**Comment by axboe** [comment]
Generally submissions will stop if there's an error, and your close with fd == -1 will error. If there are no submissions errors, then it'll submit all 10 in one go.

**Comment by YoSTEALTH** [comment]
Isn't `io_uring_prep_close` a Linux 5.6+ feature? As it uses `IORING_OP_CLOSE`

**Comment by dkadashev** [comment]
@axboe ah, I did not expect that it can detect errors during the submission time, thank you!

Still, it's a bit confusing that when the submission stops early the userspace data goes "out of sync" if you will. I mean, `sq_ready()` and `sq_space_left()`, e.g. with slightly modified program (to show space left in addition to sq_ready) above I get this:

```
going to submit, sq_ready=8, sq_space_left=0
submitted 1 items
going to submit, sq_ready=0, sq_space_left=8
submitted 1 items
```

This can result in silent overwriting of existing items in the queue, e.g. with the following test program:

```
#include <assert.h>
#include <liburing.h>
#include <signal.h>
#include <stdio.h>
#include <string.h>

#define COUNT 8

int submit_full(struct io_uring* ring)
{
    int prepared = 0;
    while (io_uring_sq_space_left(ring) > 0) {
        struct io_uring_sqe* sqe = io_uring_get_sqe(ring);
        assert(sqe);
        io_uring_prep_close(sqe, -1);
        ++prepared;
    }
    printf("going to submit %d items\n", prepared);
    int res = io_uring_submit(ring);
    if (res < 0) {
        printf("submit: %s\n", strerror(-res));
        assert(0);
    }
    printf("submitted %d items\n", res);
    return res;
}

int main()
{
    struct io_uring ring;
    int fds[COUNT];
    int res = io_uring_queue_init(8, &ring, 0);
    if (res < 0) {
        printf("init: %s\n", strerror(-res));
        return 1;
    }
    int submitted = 0;
    submitted += submit_full(&ring);
    // we can overflow CQ here, but that's not the point
    submitted += submit_full(&ring);
    for (int i = 0; i < submitted; ++i) {
        struct io_uring_cqe* cqe;
        res = io_uring_wait_cqe(&ring, &cqe);
        if (res < 0) {
            printf("wait_cqe: %s\n", strerror(-res));
            return 2;
        }
        io_uring_cqe_seen(&ring, cqe);
    }
    io_uring_queue_exit(&ring);

    return 0;
}
```

I get this output:
```
going to submit 8 items
submitted 1 items
going to submit 8 items
submitted 1 items
```

I.e. SQEs submitted during the first call are overwritten, because `io_uring_sq_space_left` (and io_uring_sq_ready` fwiw) are saying that the queue is empty.

@YoSTEALTH yes, but I suppose kernel just rejects those SQEs with `EINVAL` or `ENOTSUP` or similar, so the problem still can be demoed with that code on older kernels too. Interestingly, the kernel seems to be checking for invalid file descriptors early, so with `-1` I get `EBADF`, and this early check is the reason submission stops early it seems.

**Comment by axboe** [comment]
Older kernels didn't terminate the chain if one failed, which was a bit problematic. That's why the newer kernels will terminate submissions if it encounters an error in any SQE that has been queued up. So if you have 16 ready for submission and number 12 has an issue, we'll return 12 (where 12 already got a CQE filled in the CQ ring with the error), and 13..16 will remain in the SQ ring, unconsumed.

**Comment by dkadashev** [comment]
@axboe yeah, I got it the first time, thanks for another explanation :)

The only problem I see is - taking your example - SQEs 13..16 will remain in the SQ ring, **but** `io_uring_sq_ready` will return `0` - and `io_uring_sq_space_left` will return full size of the queue. And those SQEs 13..16 will be silently overwritten if e.g. `io_uring_sq_space_left` is used to determine how many SQEs can be submitted (and submit more than actual space left). The program from my comment above demonstrates that.

Feel free to keep the ticket closed if you think it does not worth to fix this or it is complicated for some reason.

**Comment by axboe** [comment]
Yeah, it'll lose "sync" with the liburing side when this happens, I can see how that can be somewhat confusing. Let me see if I can handle that.

**Comment by axboe** [comment]
Something like this should work, can you check?

```
diff --git a/src/include/liburing.h b/src/include/liburing.h
index 6285c4d51deb..eaeda8682faf 100644
--- a/src/include/liburing.h
+++ b/src/include/liburing.h
@@ -427,8 +427,7 @@ static inline void io_uring_prep_remove_buffers(struct io_uring_sqe
 *sqe,
 
 static inline unsigned io_uring_sq_ready(struct io_uring *ring)
 {
-       if (!(ring->flags & IORING_SETUP_SQPOLL))
-               return ring->sq.sqe_tail - ring->sq.sqe_head;
+       /* always use real head, to avoid losing sync for short submit */
        return ring->sq.sqe_tail - *ring->sq.khead;
 }
```

**Comment by axboe** [comment]
Pushed it out, and added a test case.

**Comment by dkadashev** [comment]
@axboe yeah, that fixes `io_uring_sq_ready`, thank you.

But another part of the problem remains: `io_uring_get_sqe` will silently overwrite items that were not consumed by the kernel if enough SQEs are requested.

Let's take the same example again: 16 SQEs ready for submission and number 12 has an issue, we'll return 12 (where 12 already got a CQE filled in the CQ ring with the error), and 13..16 will remain in the SQ ring, unconsumed. Let's assume the size of the ring is e.g. 16. If at this point `io_uring_get_sqe` is called e.g. 14 times then original SQEs 13..14 will be silently overwritten. Whereas the usual behavior for `io_uring_get_sqe` is to return NULL on full queue.

Granted, with `io_uring_sq_ready` fixed there is at least a built in way to check for this. But still it looks like `io_uring_get_sqe` breaks its contract in this case.

Here is a reproducer just in case:

```c
#include <assert.h>
#include <liburing.h>
#include <stdio.h>
#include <string.h>

#define COUNT 8

int submit_full(struct io_uring* ring)
{
    int prepared = 0;
    while (1) {
        struct io_uring_sqe* sqe = io_uring_get_sqe(ring);
        if (!sqe) {
            break;
        }
        io_uring_prep_close(sqe, -1);
        ++prepared;
    }
    printf("prepared %d items\n", prepared);
    int res = io_uring_submit(ring);
    if (res < 0) {
        printf("submit: %s\n", strerror(-res));
        assert(0);
    }
    printf("submitted %d items\n", res);
    return res;
}

int main()
{
    struct io_uring ring;
    int res = io_uring_queue_init(COUNT, &ring, 0);
    if (res < 0) {
        printf("init: %s\n", strerror(-res));
        return 1;
    }
    int submitted = 0;
    submitted += submit_full(&ring);
    // We can overflow CQ here, but that's not the point.
    // The point is on the second call we'll prepare 8 more items,
    // overwriting 7 from the previous call.
    submitted += submit_full(&ring);
    // Consume the CQ, irrelevant to the problem
    for (int i = 0; i < submitted; ++i) {
        struct io_uring_cqe* cqe;
        res = io_uring_wait_cqe(&ring, &cqe);
        if (res < 0) {
            printf("wait_cqe: %s\n", strerror(-res));
            return 2;
        }
        io_uring_cqe_seen(&ring, cqe);
    }
    io_uring_queue_exit(&ring);

    return 0;
}
```
