### ISSUE TITLE
use handle instead of struct

### ISSUE THREAD

**Issue by zzwxh** [axboe/liburing#922]
i don't know if io_uring* structs can be easily cloned like opaque handle
why not liburing use opaque handle to the structs

**Comment by zzwxh** [comment]
https://learn.microsoft.com/en-us/windows/win32/api/ioringapi/
Windows IoRing api uses HIORING

**Comment by zzwxh** [comment]
Handles provide better encapsulation and expose less detail.  Handles have no memory safety issues.  Handles can be easily passed to ffi

**Comment by zzwxh** [comment]
@axboe

**Comment by zzwxh** [comment]
It took me ten minutes to write cat to use the ioring api for windows, but for liburing it took me hours to figure out these weird and complex structures

**Comment by axboe** [comment]
The only advantage of using an opaque blob is that you can change them as long as the library and kernel agree. The downsides are that what should've just been a few memory writes is now a function call, so it's vastly more expensive. It doesn't solve any reuse issues, nor have we had any with the SQE on Linux - to do that, you'd need to copy the blog as well. If the msft ioring does that, then that'd just add a ton more overhead as it would fully negate the zero copy nature of the submission side.

**Comment by axboe** [comment]
> It took me ten minutes to write cat to use the ioring api for windows, but for liburing it took me hours to figure out these weird and complex structures

You're either joking or doing this very wrong. The only struct you need to care about is io_uring_sqe, and for most purposes it IS opaque to you. You call io_uring_get_sqe() to get a new one, io_uring_prep_read() to prepare a read, etc. Either you are using the raw kernel interface (in which case why post on the liburing GH at all?!), or you are doing something grossly misunderstood and wrong.

**Comment by zzwxh** [comment]
Sorry for not explaining clearly, I use rust not c.  With opaque handles, it's easy to manually generate rust bindings, but with structs, I pay for fields that I don't use at all like some unnamed unions

**Comment by axboe** [comment]
There's no way that we'd ever go the opaque route, and it'd have to be an entirely v2 of the entire interface for that to happen. The sqe was designed so that it's a cacheline of data. Some commands needs less, this is true, but the benefits of NOT having an blob type greatly outweigh the few downsides.

**Comment by zzwxh** [comment]
Opaque handles can obviously be copied, but can the io_uring structure be copied?

**Comment by axboe** [comment]
The only downside for you seems like it'd be that some blobs could be a bit less than 64 bytes. Right now, they'd all take 64 bytes. This would cause you some space overhead, but that should be pretty minimal at the end of the day. With going the FFI route, you'd be getting a function call anyway to set them up. Which is unfortunate, and you would indeed have to implement your own prep_read() etc if that was enough of a concern for you to care about that. I would imagine that rust and others would have this in a small liburing type crate, or at least it should be, if the FFI overhead is a problem.

**Comment by axboe** [comment]
> Opaque handles can obviously be copied, but can the io_uring structure be copied?

Why would you want to copy them? You get a pointer to one, fill it in, and you submit it. Kernel side reads the same memory. You could surely have your sqe elsewhere and copy it into the right index instead, but that would defeat the purpose of sharing this memory with the kernel.

**Comment by zzwxh** [comment]
i mean the `struct io_uring`
not `io_uring_sqe` or `io_uring_cqe`
because opaque handles are immutable
Is `struct io_uring` also immutable?

**Comment by zzwxh** [comment]
Immutable handles only need to consider the life cycle, while structures need to consider memory safety issues

**Comment by axboe** [comment]
Why do you need to copy the ring? Just embed it inside wherever you want it. You need not allocate it.

But yes, you could copy it as long as the new copy is then the only one you'd use. You cannot copy and free the original, obviously. But you could call io_uring_queue_exit() on your copy.

**Comment by zzwxh** [comment]
Please let me sort it out.
The ring is not immutable, means the api call will change the ring, means it is difficult for two objects to refer to the ring at the same time.
Most of the APIs use opaque handles, you get only one number, which can be copied and sent easily.
Is this right？

**Comment by isilence** [comment]
> It took me ten minutes to write cat to use the ioring api for windows, but for liburing it took me hours to figure out these weird and complex structures

@zzwxh, I strongly disagree that liburing is weird and complex, and 20 lines is more than enough to explain all basics, see below as an example. So, the question I will ask what specifically is the struggle you had? Is it rust specific? Is it a lack of example? Maybe sth else?

```C
#include "liburing.h"
#include <stdio.h>
#include <assert.h>

int main() {
	struct io_uring_cqe *cqe;
	struct io_uring_sqe *sqe;
	struct io_uring ring;
	int ret;

	ret = io_uring_queue_init(8, &ring, 0);
	assert(ret == 0);

	sqe = io_uring_get_sqe(&ring);
	io_uring_prep_nop(sqe);
	ret = io_uring_submit(&ring);
	assert(ret == 1);

	ret = io_uring_wait_cqe(&ring, &cqe);
	fprintf(stderr, "result, %lu %i\n", (long)cqe->user_data, cqe->res);
	io_uring_cqe_seen(&ring, cqe);

	io_uring_queue_exit(&ring);
	return 0;
}
```

**Comment by isilence** [comment]
> Please let me sort it out. The ring is not immutable, means the api call will change the ring, means it is difficult for two objects to refer to the ring at the same time. Most of the APIs use opaque handles, you get only one number, which can be copied and sent easily. Is this right？

1. `struct io_uring ring` is not immutable, it keeps changing state
2.  io_uring's (kernel, not liburing) uapi is not thread safe, rings (Submission/Completion queues) and some other bits are shared b/w userspace and the kernel. User space should never submit concurrently / from multiple threads / etc. without additional synchronisation

**Comment by isilence** [comment]
There is a chance it's safe to copy move it, i.e. you copy the object but there is still only one instance in the end.
If interesting we can look it up in the code and confirm for you. Alternatively, you can dynamically allocate memory for `struct io_uring` in the first place

**Comment by zzwxh** [comment]
ffi needs to declare the function signature on the rust side, the function signature of liburing contains a very complex structure, but the function signature of ioring(windows api) does not.
Obviously, liburing exposes too many internal implementations that I don't care about
@isilence

**Comment by zzwxh** [comment]
> The only downside for you seems like it'd be that some blobs could be a bit less than 64 bytes. Right now, they'd all take 64 bytes. This would cause you some space overhead, but that should be pretty minimal at the end of the day. With going the FFI route, you'd be getting a function call anyway to set them up. Which is unfortunate, and you would indeed have to implement your own prep_read() etc if that was enough of a concern for you to care about that. I would imagine that rust and others would have this in a small liburing type crate, or at least it should be, if the FFI overhead is a problem.

because there's `union` and `__u8 cmd[0]`
It's very hard to write `prep_read` in rust
Can you remove these zero size value?

**Comment by zzwxh** [comment]
@axboe

**Comment by axboe** [comment]
> Can you remove these zero size value?

Before asking questions like this, perhaps consider there's a reason it already looks like that. It's not like I add things just for fun.

**Comment by zzwxh** [comment]
Can't these zero-length arrays be replaced by functions？

**Comment by isilence** [comment]
Dear @zzwxh,

> ffi needs to declare the function signature on the rust side, the function signature of liburing contains a very complex structure

Again, it's quite a stretch calling it complex. It's your responsibility as a binding/library writer to understand this not so complex API including structures. Otherwise, I'd rather recommend to pick one of the existing rust libraries.

> Obviously, liburing exposes too many internal implementations that I don't care about

Well, you should. It was Microsoft's decision to provide such an API while copying io_uring. Liburing provides a slightly lower level interface for performance reasons, io_uring is even lower. You can always wrap around io_uring for your needs, or contribute to liburing adding helpers hiding some bits from the user.

**Comment by isilence** [comment]
For example, you can write a bit of C providing non inline helpers, which would basically look like

```C
int io_queue_read(...) {
    sqe = get_sqe();
    if (!sqe) return -ENOSPC;
    io_prep_read(sqe, ...);
    return 0;
}
```

**Comment by isilence** [comment]
> because there's union and __u8 cmd[0] It's very hard to write prep_read in rust Can you remove these zero size value?

What exactly the problem here? Why rust cannot work with it?

**Comment by zzwxh** [comment]
zero size type inside union isn't ffi safe
