### ISSUE TITLE
About submit and call sqe from any thread

### ISSUE THREAD

**Issue by katanatr** [axboe/liburing#926]
Previously discussed topic #109, but I couldn’t see a clear answer. Is it possible to use get_sqe and submit from any thread? Are you considering such a development?

**Comment by axboe** [comment]
It's not possible unless you provide your own mutual exclusion for that, and it'll also exclude you from current and future optimizations that limit a submitter to a single thread/task. We've continually pushed for single thread usage of a ring, and we'll continue to do that. Unless there are very strong reasons for sharing, you should reconsider.
