### ISSUE TITLE
`io_uring_queue_init()` limited?

### ISSUE THREAD

**Issue by YoSTEALTH** [axboe/liburing#93]
I have a simple run forever type of server in the background using `liburing`. I try to run another `io_uring_queue_init()` and get `OSError: [Errno 12] Cannot allocate memory`. Totally separate process/thread.

**Comment by axboe** [comment]
See the README, it has a blurb about that. The limits are per-user, not process/task.

**Comment by YoSTEALTH** [comment]
You mean "4.0 Enter io_uring" ?

I get that you want to be efficient but don't you think this could be major problem? Like if there are 2 software using liburing, only 1 can run.

One of the potential solution would have been to create a standard Liburing Event Manager and get all software to use that 1 event manager, submitting and waiting for tasks to finish.

**Comment by axboe** [comment]
I mean the "ulimit settings", This has nothing to do with being efficient, its just that rlimit memlock memory is accounted, and it's accounted on a per-user basis. Generally the default settings for a distro are low, especially if you want larger sized rings. You just want to bump the settings.

It has nothing to do with number of applications, or anything like that. Read the section:

https://git.kernel.dk/cgit/liburing/tree/README#n19

and just bump up your limits and it'll work fine.

**Comment by YoSTEALTH** [comment]
This is going to be a major pain.

In my system
1. I can't change the `ulimit` as normal user
2. `sudo` doesn't know what `ulimit` is
3. If i enter `su` and change the `ulimit -l 128`. It will only effect the `root` user and not normal user. To make things really worst after a while `su` `ulimit -a` shows the `max locked memory` to be reverted back to `64`

There needs to be a simpler solution...
