### ISSUE TITLE
Go programming language full port of liburing.

### ISSUE THREAD

**Issue by pawelgaczynski** [axboe/liburing#933]
Hi. I have recently published the [giouring](https://github.com/pawelgaczynski/giouring) library, which is an almost full Go language port of liburing. I hope that the library will prove useful to many people. A bit of information about it:

* The API is very similar to the liburing API, so anyone familiar with liburing will find it easier when writing code.
* The versioning is aligned with liburing versioning.
* It is MIT licensed.

Link to the repository: [giouring](https://github.com/pawelgaczynski/giouring)

**Comment by ammarfaizi2** [comment]
This should go to the "Discussions" section, "Show and tell" category. It's not an issue.

https://github.com/axboe/liburing/discussions/categories/show-and-tell
