### ISSUE TITLE
add a makefile target that build only source files but not tests

### ISSUE THREAD

**Issue by zzwxh** [axboe/liburing#942]
```
dummytargetname: 
         @$(MAKE) -C src 
#        @$(MAKE) -C test 
#        @$(MAKE) -C examples
```

**Comment by axboe** [comment]
Just run make -C src and that's what it does? It is literally split in src, test, and examples already.

**Comment by zzwxh** [comment]
I'm just looking for some compatibility guarantees, i.e. `make all` and `make install` will definitely always be available, but using the internal Makefile scares me
@axboe
