### ISSUE TITLE
Using linkat flags results in EINVAL

### ISSUE THREAD

**Issue by talex5** [axboe/liburing#955]
`io_uring_prep_linkat` takes a `flags` argument. The `linkat` man-page says you can use `AT_EMPTY_PATH` or `AT_SYMLINK_FOLLOW` here. However, passing either results in `EINVAL`.

It looks like liburing only ever tests with 0 here:
https://github.com/axboe/liburing/blob/b3ee3e764593ea85ba88f00b77bab2d58fbca530/test/hardlink.c#L27

Note that using a flag here still appears to pass the test, however, as the test is skipped if it returns EINVAL:

https://github.com/axboe/liburing/blob/b3ee3e764593ea85ba88f00b77bab2d58fbca530/test/hardlink.c#L99-L101

I guess this is the reason it doesn't work:

```c
if (sqe->rw_flags || sqe->buf_index || sqe->splice_fd_in)
		return -EINVAL;
```
https://github.com/torvalds/linux/blob/633b47cb009d09dc8f4ba9cdb3a0ca138809c7c7/io_uring/fs.c#L241-L247

(`rw_flags` and `hardlink_flags` are from the same union)

**Comment by axboe** [comment]
Doh that's annoying, your analysis is correct! I'll get a fix sent out for that, and sent to stable as well.

**Comment by axboe** [comment]
If you want to contribute a test case which uses ```AT_EMPTY_PATH``` and ```AT_SYMLINK_FOLLOW```, that would be great!

**Comment by axboe** [comment]
Pushed out a fix for testing. If you want a Reported-by: tag in there as well for you, then just provide your Real Identify < real@email.com> info and I'll add it. Thanks!

**Comment by talex5** [comment]
Thanks! My details are `Thomas Leonard <talex5@gmail.com>`.

I had a got at a test here: https://github.com/axboe/liburing/compare/master...talex5:liburing:hardlink-flags?expand=1 (but it just returns skipped on my machine, of course)

**Comment by axboe** [comment]
Perfect, I amended the commit to include your reported-by tag.

On the test case, I think we should just fold it into the existing test/hardlink.c, probably just add another do_linkat() helper that takes an fd and flags. It doesn't seem to work for me, using io_uring or linkat(2), however:

```
axboe@m1max-kvm ~/g/liburing (futex)> test/hardlink-flags.t
linkat: No such file or directory
axboe@m1max-kvm ~/g/liburing (futex) [1]> sudo test/hardlink-flags.t
linked files have unexpected links count
```

this is using ret = linkat(...) with the same arguments. Hmm? On a flight right now so didn't look any further, probably something mundane I'm guessing.

**Comment by talex5** [comment]
Sorry, the test had multiple problems. I've made another attempt!

**Comment by axboe** [comment]
Just send me a PR against liburing and I'll review/merge it.
