### ISSUE TITLE
Can I set `sqe->flags = SQE_IO_LINK` after io_uring_submit?

### ISSUE THREAD

**Issue by nikhedonia** [axboe/liburing#96]
I curious about the design decision of SQE_IO_LINK linking the next vs. previous command.
I guess the latter approach would be more problematic as the entries placed in a ring buffer?

**Comment by axboe** [comment]
Once an SQE has been submitted, it's no longer read again. Anything you set after submission will not be seen. In fact, it may be completed by the time you submit the next command. Hence linking backwards cannot work, and setting the flag after cannot work either.
