### ISSUE TITLE
the example can't run on ubuntu 22.04. the ubuntu runs on docker, it shows Function not implemented.

### ISSUE THREAD

**Issue by yacc2007** [axboe/liburing#962]
<img width="924" alt="image" src="https://github.com/axboe/liburing/assets/6888202/7ee05a66-b74d-4156-a125-966ea7c1cc8b">

the example can't run on ubuntu 22.04. the ubuntu runs on docker.

**Comment by yacc2007** [comment]
kernel : Linux 5.10.25-linuxkit x86_64

**Comment by axboe** [comment]
It's disabled in docker if you get ```-ENOSYS``` as the error. This is not a liburing issue.
