### ISSUE TITLE
document behavior of missing `IORING_FEAT_NODROP`

### ISSUE THREAD

**Issue by alkis** [axboe/liburing#969]
Do I understand correctly that if `IORING_FEAT_NODROP` is not set, the kernel drops CQE's if the CQ ring is full?

Is there a way to avoid drops and/or detect drops?

(this is kernel 5.4 in ubuntu 18.04)

**Comment by axboe** [comment]
That is correct, it'll drop but account them. Which means the application will know if any were dropped (in terms of the number of them), but won't get the CQE for them.

The way to avoid drops is to not use an ancient kernel, simple as that. 5.4 is ancient, particularly in terms of io_uring, I would not recommend that as a suitable base.

**Comment by alkis** [comment]
> The way to avoid drops is to not use an ancient kernel, simple as that. 5.4 is ancient, particularly in terms of io_uring, I would not recommend that as a suitable base.

Yes, fighting against the stream. We do want to use the latest and greatest but FIPS is in the way... Will do soon and most of our pain will go away.

I do know it is a tall order to ask (especially retroactively) but could some extra effort be made on man pages to list *notable* differences between kernel behaviors?

**Comment by axboe** [comment]
The main differences should be explained in FEAT flags, which should be documented.

**Comment by alkis** [comment]
Indeed this is documented in [io_uring_enter](https://man7.org/linux/man-pages/man2/io_uring_enter.2.html) but not in [io_uring_queue_init_params](https://man7.org/linux/man-pages/man3/io_uring_queue_init_params.3.html). Confusingly the latter talks about the `IORING_SQ_CQ_OVERFLOW` state which only happens when  `IORING_FEAT_NODROP ` is returned.

Should I send a PR?

**Comment by axboe** [comment]
Please do!
