### ISSUE TITLE
io_uring not maxing cpu

### ISSUE THREAD

**Issue by tmds** [axboe/liburing#97]
hi @axboe 

We're doing some experiments to measure perf changes from using io_uring in .NET Core Socket implementation. As a benchmark we're running the [TechEmpower json benchmark](https://github.com/TechEmpower/FrameworkBenchmarks/wiki/Project-Information-Framework-Tests-Overview#json-serialization). This benchmark is very network-centric.

When using io_uring we're not able to max cpu on the server machine. The machine is 16% idle.

Our server machine has 6 cores with hyperthreading.
We spawn 4 threads that use io_uring.
256 clients connect to these threads. So each io_uring thread is handling 64 clients.
io_uring is used to receive the http requests. When a request is received, handling of the request is deferred to the .NET threadpool. On the threadpool threads, we're using regular 'sendto' syscalls to generate reply.
When we check load ion io_uring threads and .NET threadpool threads, all of them are loaded less than 70%. So it seems the .NET threads are not the bottleneck.
We have some non-io_uring benchmarks that use 100% CPU and achieve higher RPS. From that we learn that the load machine, and network are not the bottleneck either.

See https://github.com/tmds/Tmds.LinuxAsync/issues/39#issuecomment-595749624 for some benchmark results.

We're using a Linux 5.5 daily kernel on Ubuntu.

Do you have some ideas why we're not able to max cpu using io_uring?
We can provide you with traces, e.g. in speedscope format.
Or run different benchmarks to see the effect.

cc @antonfirsov @adamsitnik @lpereira @tkp1n

**Comment by antonfirsov** [comment]
I've collected some traces. On application side, a typical handler thread is spending most of it's time being blocked in `io_uring_enter`.

In kernel, the most expensive call seems to be `cpuidle_enter_state`:
![image](https://user-images.githubusercontent.com/6835152/76772260-e43f3f80-67a0-11ea-902d-fc27e2db89bb.png)


```
uname -r
5.5.7-050507-generic
```

CPU is: `Intel(R) Xeon(R) CPU E5-1650 v3 @ 3.50GHz`.

**Comment by axboe** [comment]
Where is it blocked off io_uring_enter()?

**Comment by antonfirsov** [comment]
A typical processing thread of an application, using @tkp1n's [IoUring.Transport](https://github.com/tkp1n/IoUring.Transport):

![image](https://user-images.githubusercontent.com/6835152/76773127-3d5ba300-67a2-11ea-8aed-3ffd923003ce.png)

@axboe is this what you asked for? I'm happy to do any experiment & answer any question, this stuff is important for us.

**Comment by tmds** [comment]
@axboe question. We ran a benchmark with 3 io_uring threads, and one with 4 io_uring threads. With 3 threads, the io_wqe_worker-1 showed up. With 4, it did not. What does that mean?
In both cases, cpu was not maxed.
Maybe interesting to know: when we queue a receive to io_uring, it is actually linked poll + readv.

@antonfirsov if you share speedscope trace files @axboe can look into the traces using [speedscope.app](https://www.speedscope.app/) website.

**Comment by antonfirsov** [comment]
There are speedscope exports for user threads in `IoUringTransport.speedscope.json`, but none for the kernel because of dotnet/diagnostics#920.

https://microsoft-my.sharepoint.com/:f:/p/anfirszo/Enb3e3pEI2dMrGbxSstPKJQBYWLacpLMwuZz1Lkab_9-bw?e=KHn80o

**Comment by tmds** [comment]
[421k-speedscope.zip](https://github.com/axboe/liburing/files/4339084/421k-speedscope.zip)

These traces are a smaller. They are a .NET io_uring thread, a .NET ThreadPool thread, and the io_wqe_worker from t=3, io_uring, nowait (https://github.com/tmds/Tmds.LinuxAsync/issues/39#issuecomment-595749624).

**Comment by tmds** [comment]
> Where is it blocked off io_uring_enter()?

Looking at the thread using io_uring:
38% of samples is in io_uring_enter
-> 35% in io_submit_sqes
-> 1.5% in io_cqring_wait

**Comment by tmds** [comment]
@axboe I wonder if `io_wqe_worker-1` is somehow constrained in how much cpu it can use? `io_wqe_worker-1` is shared between the 4 io_urings?

**Comment by CarterLi** [comment]
`io_wqe_worker-1` means that operations get punted to async context ( i.e. executed in an extra kernel thread ). You may need to poll before `send/recv`s because async context switching turns out to having high overhead and generally should be avoided.

The good news is that in kernel 5.7 it won't be a problem.

**Comment by tkp1n** [comment]
> You may need to poll before `send/recv`

The current implementations we've tested submit
* a `IORING_OP_POLL_ADD` (`POLLIN`) linked (via `IOSQE_IO_LINK`) to each `IORING_OP_READV` 
* a `IORING_OP_POLL_ADD` (`POLLOUT`) linked (via `IOSQE_IO_LINK`) to each `IORING_OP_WRITEV`

@CarterLi Does this cause the desired effect or should the readv/writev not be submitted at all until the poll completes?

**Comment by CarterLi** [comment]
@tkp1n Don't use link before 5.7. See https://github.com/CarterLi/liburing4cpp#dont-use-iosqe_io_link

**Comment by tmds** [comment]
@CarterLi that is really useful information! I understand use of `io_wqe_worker-1` means overhead in terms of context switching. Have you observed this causing idle time?

**Comment by CarterLi** [comment]
`io_wqe_worker-1` is the kernel process/thread/worker to execute async operations. (It seems that) the kernel thread will only be created when needed. If so, extra context switching happened and performance drops are expected.

My words are mostly based on my old benchmarks and lots of guessing, and only apply to networking. Correct me if I'm wrong.

**Comment by tmds** [comment]
I expect not using linked operation will allow us to max cpu because operations will execute inline on the thread that submits.

I think idle time that we observe indicates a bottleneck. We'll no longer be passing through it by not using linked operations, but it may still be there. For example, suppose `io_wqe_worker-1` consists of a single thread. If you give it more work than 1 thread can handle, that would cause idle time because other threads would start waiting for operations to complete.

**Comment by tmds** [comment]
Avoiding the `io_wqe_worker-1` allows us to maximize cpu.

I understand this kernel threadpool may cause overhead, though that should manifest as reduced performance.
That it shows as idle time indicates there probably is a bottleneck.
In these benchmarks 500k+ request per second are sent to the worker. Maybe not a common enough case to investigate further.

@axboe you can close this if you want.

**Comment by axboe** [comment]
There should never been any io_wqe_worker use in this case, I'm going to see if I can find some time to investigate.

Would be great, if at all possible, you could try with a custom kernel. The 5.7 pending bits should really improve things for this use case.

**Comment by axboe** [comment]
To expand, the improvement on 5.7 will allow you to both use poll + recv (and so on) links without hitting the async workers. And more importantly, it'll also allow you to just do recv directly, and not use poll at all.

**Comment by tmds** [comment]
> Would be great, if at all possible, you could try with a custom kernel. The 5.7 pending bits should really improve things for this use case.

We're not building custom kernels at this point. As soon as a 5.7 preview kernel is available for Ubuntu running on the benchmark machines, we can give it a try.

> And more importantly, it'll also allow you to just do recv directly, and not use poll at all.

In our use-case we need to deal with sockets which are potentially set to non-blocking by the user and we need to respect that configuration. So I think we'll need to stick to poll+recv. Though I expect/hope overhead of the extra poll operation will be minimal with 5.7 kernel.

**Comment by axboe** [comment]
> We're not building custom kernels at this point. As soon as a 5.7 preview kernel is available for Ubuntu running on the benchmark machines, we can give it a try.

That's fine, just wanted to bring the more efficient 5.7 behavior to your attention, it you weren't already aware of it!
