### ISSUE TITLE
Version of liburing

### ISSUE THREAD

**Issue by PHDsaoudi** [axboe/liburing#972]
Hi,
I would like to install ibosmocore in ubunto i do this :
git clone https://gitea.osmocom.org/osmocom/libosmocore.git
cd libosmocore/
autoreconf -i
./configure
make
sudo make install
sudo ldconfig -i
cd ..
the result is:
configure: error: Package requirements (liburing >= 0.7) were not met:

Requested 'liburing >= 0.7' but version of liburing is 0.6
You may find new versions of liburing at http://git.kernel.dk/cgit/liburing/

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables URING_CFLAGS
and URING_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
[ERROR] Configuration failed after running at least twice.
[ERROR] Problem occurred while building package libosmocore:

Configuration failed
[ERROR] Error installing package libosmocore. Aborting.

Taking account that i have installed successfully liburing v2.5
nstall -D -m 644 include/liburing/barrier.h /usr/include/liburing/barrier.h
install -D -m 644 include/liburing/io_uring_version.h /usr/include/liburing/io_uring_version.h
install -D -m 644 liburing.a /usr/lib/liburing.a
install -D -m 644 liburing-ffi.a /usr/lib/liburing-ffi.a
install -D -m 755 liburing.so.2.5 /usr/lib/liburing.so.2.5
install -D -m 755 liburing-ffi.so.2.5 /usr/lib/liburing-ffi.so.2.5
ln -sf liburing.so.2.5 /usr/lib/liburing.so.2
ln -sf liburing.so.2.5 /usr/lib/liburing.so
ln -sf liburing-ffi.so.2.5 /usr/lib/liburing-ffi.so.2
ln -sf liburing-ffi.so.2.5 /usr/lib/liburing-ffi.so
make[1] : on quitte le répertoire « /home/crm/liburing/src »
install -D -m 644 liburing.pc /usr/lib/pkgconfig/liburing.pc
install -D -m 644 liburing-ffi.pc /usr/lib/pkgconfig/liburing-ffi.pc
install -m 755 -d /usr/man/man2
install -m 644 man/*.2 /usr/man/man2
install -m 755 -d /usr/man/man3
install -m 644 man/*.3 /usr/man/man3
install -m 755 -d /usr/man/man7
install -m 644 man/*.7 /usr/man/man7
----------------------------------------------------------
However when i do this command: pkg-config --modversion liburing
crm@crm-X570-UD:~/liburing$ pkg-config --modversion liburing
0.6
How can i obliged ubunto to work with the new version liburing 2.5 installed to be enable to install libsmocore

Because it returns that the version of liburing is 0.6

I'm so gratefull if you can help me

**Comment by PHDsaoudi** [comment]
Dear sir;
I inform you that these library doesn't exist in the path usr/local/lib; it exist on usr/lib 
Should i added it to this path or it is acceptable, because i added only the path in  environment variable  in /.bashrc:export LD_LIBRARY_PATH=/usr/local/lib
Also i ask if i should adjusting PKG_CONFIG_PATH environment variable because i add only this path
export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig
![liburin-pc](https://github.com/axboe/liburing/assets/146379001/273b6399-9c24-44c2-96ba-f61a19a4e628)
However the path of libruring's pkgconfig is   /usr/lib/pkgconfig 
What can i do in this case

**Comment by PHDsaoudi** [comment]
dear sir
when i run this command # find / | grep liburing i obtain:

./.local/share/Trash/info/liburing.4.trashinfo
./.local/share/Trash/info/liburing.10.trashinfo
./.local/share/Trash/info/liburing.6.trashinfo
./.local/share/Trash/info/liburing.9.trashinfo
./.local/share/Trash/info/liburing-0.7.tar.gz.trashinfo
./.local/share/Trash/info/liburing.trashinfo
./.local/share/Trash/info/liburing.5.trashinfo
./.local/share/Trash/info/liburing-dev_0.6-3ubuntu1_amd64.deb.trashinfo
 How can i disable it

**Comment by axboe** [comment]
I think you'll find better help for this issue in generic linux help channels, it's really beyond the scope of this project to help with issues like that.
