### ISSUE TITLE
io_uring-test 4K file error

### ISSUE THREAD

**Issue by piaoxuebingfeng** [axboe/liburing#973]
I conducted the following test：

$ dd if=/dev/zero of=test4096 bs=1024 count=4
记录了4+0 的读入
记录了4+0 的写出
4096 bytes (4.1 kB, 4.0 KiB) copied, 8.1946e-05 s, 50.0 MB/s

$ ./io_uring-test ./test4096 
ret=0, wanted 4096
Submitted=2, completed=1, bytes=0

io_uring-test  submitted 2 times ,but comleted 1 time.

**Comment by axboe** [comment]
It's reading 4K blocks, there was only one to read. This looks expected.
