### ISSUE TITLE
io_uring-close-test failed with message: queue_init: Operation not permitted

### ISSUE THREAD

**Issue by jumpapex** [axboe/liburing#989]
OS: AlmaLinux 9.3 (Redhat Enterprise Linux), kernel version: 5.14.0-362.8.1.el9_3.x86_64
liburing: 2.4

liburing make successfully.

run with root: 
io_uring-close-test some-file
_queue_init: Operation not permitted._

furthe debug shows that '__sys_io_uring_setup' failed.

while the following code show that io_uring is supported by system.
```
#include <stdio.h>
#include <errno.h>
#include <linux/io_uring.h>
#include <stddef.h>
#include <sys/syscall.h>
#include <unistd.h>

int main(int argc, char **argv) {
  if (syscall(__NR_io_uring_register, 0, IORING_UNREGISTER_BUFFERS, NULL, 0) && errno == ENOSYS) {
    printf("No io_uring\n");
  } else {
    printf("Has io_uring\n");
  }
}
```
Regards!
Paul

**Comment by axboe** [comment]
This sounds like a distro side issue, not something that we can fix from here.

**Comment by fxzjshm** [comment]
See <https://access.redhat.com/documentation/en-n/red_hat_enterprise_linux/9/html/9.3_release_notes/technology-previews>, under "The io_uring interface is available as a Technology Preview", need to set `kernel.io_uring_disabled` sysctl variable and SELinux policy.
